### ISSUE TITLE
Setup with nvim-compe

### ISSUE THREAD

**Issue by novakne** [L3MON4D3/LuaSnip#1]
So I'm trying to replace vim-snip with this plugin, right now I'm using the exemple setup in nvim-compe README.md
``` lua
local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
  local col = vim.fn.col('.') - 1
  if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
    return true
  else
    return false
  end
end

-- Use (s-)tab to:
--- move to prev/next item in completion menuone
--- jump to prev/next snippet's placeholder
MUtils.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-n>"
  elseif vim.fn.call("vsnip#available", {1}) == 1 then
    return t "<Plug>(vsnip-expand-or-jump)"
  elseif check_back_space() then
    return t "<Tab>"
  else
    return vim.fn['compe#complete']()
  end
end

MUtils.s_tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-p>"
  elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
    return t "<Plug>(vsnip-jump-prev)"
  else
    return t "<S-Tab>"
  end
end

```
and 

``` lua
map("i", "<Tab>", "v:lua.MUtils.tab_complete()", {expr = true})
map("s", "<Tab>", "v:lua.MUtils.tab_complete()", {expr = true})
map("i", "<S-Tab>", "v:lua.MUtils.s_tab_complete()", {expr = true})
map("s", "<S-Tab>", "v:lua.MUtils.s_tab_complete()", {expr = true})

```
What would be the best way to use a similar setup with LuaSnip?

**Comment by L3MON4D3** [comment]
I think you'd only need to change
```lua
  elseif vim.fn.call("vsnip#available", {1}) == 1 then
    return t "<Plug>(vsnip-expand-or-jump)"
```
to
```lua
elseif require'luasnip'.expand_or_jumpable() then
    return t "<Plug>luasnip-expand-or-jump"
```
and
```lua
  elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
    return t "<Plug>(vsnip-jump-prev)"
```
to
```lua
  elseif require'luasnip'.jumpable(-1) then
    return t "<Plug>luasnip-jump-prev"
```
Also make sure to pull the latest master, I just pushed the jumpable(direction)-function.

**Comment by L3MON4D3** [comment]
You're welcome :D
As of now there is no source for Luasnip in nvim-compe, but I have my eyes on that and will probably throw something up in the next few days.

**Comment by L3MON4D3** [comment]
Thanks!

**Comment by f3fora** [comment]
I suggest to change the example of `nvim-compe` with something like this:

```lua
local function prequire(...)
    local status, lib = pcall(require, ...)
    if (status) then return lib end
    return nil
end

local luasnip = prequire('luasnip')

local t = function(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col('.') - 1
    if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
        return true
    else
        return false
    end
end

_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif luasnip and luasnip.expand_or_jumpable() then
        return t "<Plug>luasnip-expand-or-jump"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn['compe#complete']()
    end
end
_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif luasnip and luasnip.jumpable(-1) then
        return t "<Plug>luasnip-jump-prev"
    else
        return t "<S-Tab>"
    end
end
```
In this way, if `luasnip` is loaded for only a subset of situations, `nvim-compe` will still work.

**Comment by L3MON4D3** [comment]
Okay, I can see the sense in that, I'll include it once I get back to writing documentation. Just out of interest, why do you load luasnip conditionally? LSP?

**Comment by f3fora** [comment]
I load it only for filetype which has a snippet defined. or after `nvim-lspconfig`. This is just my 
personal preference.

Concerning documentation, maybe a few lines on `nvim-compe` and a gif example will be useful. 
The possibility of using this plugin for LSP snippets or snippet source with `nvim-compe` can be 
known only reading the code. And this plugin is definitely great and deserves more popularity.

**Comment by L3MON4D3** [comment]
Ah, that makes sense.
I'll keep the gif-suggestion in mind, I think compatibility with `nvim-compe` is mentioned in both READMEs, though very briefly.

**Comment by MOHENOO** [comment]
If use [wbthomason/packer.nvim ](https://github.com/wbthomason/packer.nvim),change the example of nvim-compe with something like this:
```lua
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif require("luasnip").expand_or_jumpable() then
        return t "<cmd>lua require'luasnip'.jump(1)<Cr>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end

_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif require("luasnip").jumpable(-1) then
        return t "<cmd>lua require'luasnip'.jump(-1)<CR>"
    else
        return t "<S-Tab>"
    end
end
```

**Comment by DJuan33** [comment]
Wow, I was searching that example with packer.nvim. Thanks! @MOHENOO

**Comment by Avimitin** [comment]
> If use [wbthomason/packer.nvim ](https://github.com/wbthomason/packer.nvim),change the example of nvim-compe with something like this:
> 
> ```lua
> _G.tab_complete = function()
>     if vim.fn.pumvisible() == 1 then
>         return t "<C-n>"
>     elseif require("luasnip").expand_or_jumpable() then
>         return t "<cmd>lua require'luasnip'.jump(1)<Cr>"
>     elseif check_back_space() then
>         return t "<Tab>"
>     else
>         return vim.fn["compe#complete"]()
>     end
> end
> 
> _G.s_tab_complete = function()
>     if vim.fn.pumvisible() == 1 then
>         return t "<C-p>"
>     elseif require("luasnip").jumpable(-1) then
>         return t "<cmd>lua require'luasnip'.jump(-1)<CR>"
>     else
>         return t "<S-Tab>"
>     end
> end
> ```

This helps me a lot! I've suffered from the `<Plug>luasnip-expand-or-jump` for the whole night. And may I ask you why `vim_api_replace_termcodes` not working when using packer.

**Comment by MOHENOO** [comment]
Sory, I don't know it. I just look at LuaSnip/plugin/luasnip.vim source code. And replace it,It work fine.
```vim
ag "<Plug>luasnip-expand-or-jump" -r .
1:inoremap <silent> <Plug>luasnip-expand-or-jump <cmd>lua require'luasnip'.expand_or_jump()<Cr>
7:snoremap <silent> <Plug>luasnip-expand-or-jump <cmd>lua require'luasnip'.expand_or_jump()<Cr>
```
It looks like about vim.api.nvim_replace_termcodes how deal it.Maybe you can ask [nanotee/nvim-lua-guide](https://github.com/nanotee/nvim-lua-guide)
```vim
local t = function(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end
```
I just migrate my vim'config to lua.(English is not my mother language,)
