### ISSUE TITLE
How to correct vscode/json snippets

### ISSUE THREAD

**Issue by ayoubelmhamdi** [L3MON4D3/LuaSnip#100]
i can not use flutter snippet , `luasnip`  not recognize ${1} ${$2} 
this is my mini config file  : [mini.lua](https://gist.githubusercontent.com/ayoubelmhamdi/3c18bc539a47946577b0e04c6b56ea07/raw/5a76996528a488fff02060d41a4f21e9771c6983/mini.lua) 
but must fix #99 first to run
```
nvim -u mini.lua
```

**Comment by L3MON4D3** [comment]
Afaict that snippet is malformed, see [here](https://microsoft.github.io/language-server-protocol/specification#snippet_syntax). You have to escape `$` and `{,}`, eg. `$1 \$\{$2\}`

**Comment by ayoubelmhamdi** [comment]
can you help me to correct this `snippet` to true format:
```
"body": [
    "class ${1:name} extends StatelessWidget {",
    "  const ${1:name}({Key? key}) : super(key: key);",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Container(",
    "      child: ${0:null},",
    "    );",
    "  }",
    "}"
],
```

**Comment by L3MON4D3** [comment]
Yes, exactly.
Also, `i(0)` don't support default-text(I think it'll parse but not show up) and the parser expects the snippets to be one long string, so you'll have to `\n`-concat the separate lines.

**Comment by ayoubelmhamdi** [comment]
yeah, 
also $1 ...foo...$1 not synchronize , as `vsnip or untisnip...`   
when you type in one place , it's change immediately in another place like  
i think it's called `multicursors`

**Comment by L3MON4D3** [comment]
That can be set using `updateevents`, check the README and `Examples/snippets.lua`

**Comment by ayoubelmhamdi** [comment]
i can not see setup() function to override `updateevents` like that
```
require'luasnip'.setup{
  updateevents="TextChanged"
}
```

**Comment by L3MON4D3** [comment]
Very close, you'll have to call `require'luasnip'.config.setup(...)` (and for your behaviour you'll primarily need `TextChangedI`, `TextChanged` is for changes in normal mode)

**Comment by ayoubelmhamdi** [comment]
config.setup it's local function , i can't override it yet !  
```
: lua require'luasnip'.config.setup(){ updateevents="TextChanged" }
```

**Comment by L3MON4D3** [comment]
Nono, call it: `require'luasnip'.config.setup({updateevents="TextChangedI" }) `

**Comment by ayoubelmhamdi** [comment]
it's configured :+1: :100:
