### ISSUE TITLE
LuaSnip eating long unicodes

### ISSUE THREAD

**Issue by aloispichler** [L3MON4D3/LuaSnip#1007]
Consider the snippet 
```
    "emphasize": {
        "prefix": ["\\emph", "*"], 
        "body": "\\emph{${1:$TM_SELECTED_TEXT}}$0",
        "description": "Emphasize text"
    },
```
to emphasize selected text (this is an example from LaTeX). 
If the selected text is `𝔼f-𝔼abc`, e.g., then the result is `\emph{𝔼f-𝔼a}` instead of `\emph{𝔼f-𝔼abc}`. The reason seems to be that `𝔼` is a long unicode character (u+1d53c). As there are two 𝔼s, LuaSnip ‘eats’ 2 characters. The same happens with other long unicode characters, or with 3 long unicode characters in the selected text, etc.
It seems that LuaSnip somewhere messes the number of characters with the number of bytes.

**Comment by L3MON4D3** [comment]
Ohhhh yup, that's a bug.
I'll look into it

**Comment by L3MON4D3** [comment]
Alriiight, so multibyte characters work now :)
What doesn't is block-select with virtualedit, but I think that we can put off until there is some api-support for just retrieving the visual selection on neovims side.

**Comment by aloispichler** [comment]
Thank you again.
I have tested the behavior today with combined unicodes, as `‖͚` or `∫₀᪲`  , and found the same erroneous behavior as described above.

**Comment by L3MON4D3** [comment]
Dammit :|

**Comment by L3MON4D3** [comment]
Okay, #1013 should work

**Comment by L3MON4D3** [comment]
Finally got the PR into master, we should now have correct behaviour for all kinds of weird edgecases

**Comment by aloispichler** [comment]
Seems to work indeed now. Thank you!
