### ISSUE TITLE
Auto-reload snippets even if it was edited in another nvim instance

### ISSUE THREAD

**Issue by bew** [L3MON4D3/LuaSnip#1008]
In my workflow I open _a lot_ of nvim instances (I have 12 at the moment 👀), to work on different things, different projects...
And I usually have one opened on my dotfiles and maybe even have the correct snippets file opened already.

When I'm working on some project and I want a new snippet or want to change an existing one, if I know I have a neovim instance where the snippets file is already opened, I'm going to switch to it (usually a few keystrokes away with tmux), make my edit and go back to my project expecting to have the new/changed snippet.

:x: but no, the snippet is not here / is still the old version :disappointed: 
(I'm using the `from_lua` directory-based loader)

I think it's because the snippets are only reloaded when changed in the same neovim instance

:point_right: Feature request: I would like the ability to change my snippets in one instance, and have them reloaded in all other instances.

I think there are usable functions in `vim.loop` to monitor file changes

**Comment by L3MON4D3** [comment]
Oh yeah, that's actually something I'd wanted to tackle for some time.
My main gripe with our current system is that new files need another call to `(lazy_)load` to get loaded, whereas updates to already-existing files go through without a hitch (as long as they're from the same neovim-instance, as you know :D)

So we'd basically want to monitor the directory that was passed to (or found in) `load` for new files (or directories!), and monitor the existing files for updates.

**Comment by L3MON4D3** [comment]
Hey, I got to it, check #1033. Should be fine to use since you use the lua-loader, at the very least it's working on my machine:tm:

**Comment by L3MON4D3** [comment]
The uv-file-watchers are not enabled by default, they have to be enabled per-load-call by providing `fs_event_providers = {libuv = true}` alongside `paths`.
