### ISSUE TITLE
$ in snippet does not work

### ISSUE THREAD

**Issue by tarunzoot** [L3MON4D3/LuaSnip#101]
while working with [puppeteer](https://github.com/puppeteer/puppeteer), using puppeteer's function `$$eval`, luasnip shows
`...util/parser.lua:314 : Invalid text after $ at 2`

**Comment by L3MON4D3** [comment]
If `$$eval` is a snippet, you have to escape the `$`'s, see [here](https://microsoft.github.io/language-server-protocol/specification#snippet_syntax)

**Comment by leiserfg** [comment]
@L3MON4D3  IMHO it's time to link the snippet syntax reference to the README :smile:

**Comment by tarunzoot** [comment]
no `$$eval` is not a snippet, i have read that issue regarding snippet syntax.

**Comment by L3MON4D3** [comment]
Okay, then I'm not sure what you're doing, could you give me something I could reproduce? (I'm not familiar with puppeteer, just in advance)

**Comment by L3MON4D3** [comment]
> @L3MON4D3 IMHO it's time to link the snippet syntax reference to the README 😄

Yeah, should help a bit with syntax errors or unescaped chars.

**Comment by tarunzoot** [comment]
yeah sure,
### compe config
`require('compe').setup({
    enabled = true,
    autocomplete = true,
    debug = false,
    min_length = 1,
    preselect = 'always',
    throttle_time = 80,
    source_timeout = 200,
    resolve_timeout = 800,
    incomplete_delay = 400,
    max_abbr_width = 100,
    max_kind_width = 100,
    max_menu_width = 100,
    documentation = {
        border = { '', '', '', ' ', '', '', '', ' ' },
        winhighlight = 'NormalFloat:CompeDocumentation,FloatBorder:CompeDocumentationBorder',
        max_width = 120,
        min_width = 60,
        max_height = math.floor(vim.o.lines * 0.3),
        min_height = 1,
    },

    source = {
        path = true,
        buffer = true,
        calc = true,
        tags = true,
        spell = true,
        emoji = true,
        nvim_lsp = true,
        nvim_lua = true,
        luasnip = true,
    },
})`

### LuaSnip config
`local ls = require('luasnip')
require('luasnip.config').set_config({ history = true, updateevents = 'TextChangedI' })
require('luasnip/loaders/from_vscode').lazy_load()
vim.api.nvim_set_keymap('i', '<tab>', "<cmd>lua require('luasnip').jump(1)<cr>", { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<s-tab>', "<cmd>lua require'luasnip'.jump(-1)<cr>", { noremap = true, silent = true })
`

now create a nodejs project and install puppeteer using `npm i puppeteer`, then open `index.js` file and add the following code
`const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  // await page.$$eval() // this line produces the error

  await browser.close();
})();`
