### ISSUE TITLE
Dynamically switch between Tab and Space based on the global or buffer options?

### ISSUE THREAD

**Issue by s1n7ax** [L3MON4D3/LuaSnip#1011]
Is there a way to dynamically figure out the indentation (space/tab) to use in a snippet? Right now I'm creating text nodes with indent string. I use `get_indent_str()` to figure out whether to use tab or space? I'm just wondering if there is a cleaner way? 

```lua
function M.get_indent_str()
  local tab_stop = vim.opt.softtabstop:get()

  if vim.o.expandtab then
    return string.rep(' ', tab_stop)
  end

  return '\t'
end
```

```lua
fmt(
    bt([[
      function ({})
        {}{}
      end
    ]]),
    {
      i(1),
      t(indentation),
      i(2),
    }
  )
```

**Comment by L3MON4D3** [comment]
Oh luasnip should expand `\t` to either whatever is given by `expandtab` and `tabstop`.
Does that work?

**Comment by s1n7ax** [comment]
It's working. Thanks.
