### ISSUE TITLE
Expose passing condition and show_condition options to parse_snippet

### ISSUE THREAD

**Issue by antonk52** [L3MON4D3/LuaSnip#1012]
Hello and thank you for your work!

I would like to make a feature request. I noticed that it is currently not possible to provide `condition` and `show_condition` options to snippets that were created via `require('luasnip').parser.parse_snippet` function.

Thank you

**Comment by L3MON4D3** [comment]
Ah, you can also pass `condition` and `show_condition` in the first field.
Something like
```lua
ls.parser.parse_snippet({trig = "asdf", condition = in_comment, show_condition = in_comment}, "A ${1:snippet}")
```

**Comment by antonk52** [comment]
This works, thank you.

It wasn't clear from the documentation for me.
