### ISSUE TITLE
trigEngine="ecma" attempt to call upvalue trig_compiled 

### ISSUE THREAD

**Issue by evesdropper** [L3MON4D3/LuaSnip#1014]
Very late to the trigEngine party and decidedly rusty after many months away from snippets (thanks corporate mediocrity!), but ecma should work fine (have make install_jsregexp, and all the regex I put up there seems to be valid, yet I'm getting the following error.

![trig_compiled](https://github.com/L3MON4D3/LuaSnip/assets/82856360/553622c0-42c8-46ac-8939-72b00d74ec0b)

Snippet for reference:
```lua
autosnippet({ trig='(?<!\\)(sin|cos|tan)', name='trig', dscr='dscr', trigEngine='ecma'},
    fmta([[
    \<><>
    ]],
    { f(function (_, snip)
        return snip.captures[2]
    end),
    i(0) }
    ), { condition = math, show_condition = math }),
```

**Comment by L3MON4D3** [comment]
Hey!
Ah, could it be that the regex is incorrect? My regex-fu is not all that advanced, but `\\(?<!\\)(sin|cos|tan)`, for example, works.
I'll make it so the error is returned early on, thanks for the report!

**Comment by evesdropper** [comment]
Hm, that's interesting - using the regex you mentioned yields exact results. I'm thoroughly not sure why the double backslashes work though.

**Comment by L3MON4D3** [comment]
Ahhh, lua turns two backslashes into one, maybe that's the issue?

**Comment by evesdropper** [comment]
yep, that was it :sweat_smile: 

forgot about that momentarily. thanks for pointing it out!
