### ISSUE TITLE
luasnip fmt not escaping curly braces

### ISSUE THREAD

**Issue by Drew-Daniels** [L3MON4D3/LuaSnip#1017]
I have this `react` snippet (excuse the indentation), where I believe I am escaping each `{` and `}` correctly.

```lua
-- luasnippets/javascriptreact.lua

---@diagnostic disable: undefined-global

return {
	s(
		"rli",
		fmt(
			[[ <li key={{}}>{{}}</li> ]],
			{i(1), i(2)}
		)
	)
}
```

However, when I start up `neovim` I see this error:
![image](https://github.com/L3MON4D3/LuaSnip/assets/62859552/c6c4d026-648e-403d-bc17-a291763d9281)

**Comment by L3MON4D3** [comment]
Oh, the error is about `fmt` not using the passed nodes, if you remove them/comment them out it should work

**Comment by Drew-Daniels** [comment]
Ah yes, that was my mistake. Thanks for the help.

When I updated my snippet to this, everything worked, because now I'm escaping the `{` and `}` at the start and end, but also including placeholders for my insert nodes.

```lua
return {
	s("rli", fmt([[ <li key={{{}}}>{{{}}}</li> ]], { i(1), i(2) })),
}
```

**Comment by L3MON4D3** [comment]
Exactly right👍👍
