### ISSUE TITLE
Not working with nvim-compe

### ISSUE THREAD

**Issue by GideonWolfe** [L3MON4D3/LuaSnip#103]
I hate to make a duplicate issue, but I've been working on this for hours and I simply can't understand why this won't work.

Here's how I'm installing with packer

```lua
  -- Snippets
  use {
    "L3MON4D3/LuaSnip",
    wants = "friendly-snippets",
    event = "InsertCharPre",
    config = function()
        require "configs.luasnip"
    end
  }

  use {
    "rafamadriz/friendly-snippets",
    event = "InsertCharPre"
  }
```
The referenced `configs.luasnip`:
```lua
local present, luasnip = pcall(require, "luasnip")
if not present then
    return
end

luasnip.config.set_config(
    {
        history = true,
        updateevents = "TextChanged,TextChangedI"
    }
)
require("luasnip/loaders/from_vscode").load()
```

I'm already using nvim-compe for autocomplete. Here's my config for that.

```lua
local compe = require('compe')

compe.setup({
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  resolve_timeout = 800;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = {
    --border = { '', '' ,'', ' ', '', '', '', ' ' }, -- the border option is the same as `|help nvim_open_win|`
    --border = "double",
    --border = "single",
    border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
    winhighlight = "NormalFloat:CompeDocumentation,FloatBorder:CompeDocumentationBorder",
    max_width = 120,
    min_width = 60,
    max_height = math.floor(vim.o.lines * 0.3),
    min_height = 1,
  };

  source = {
    path = true,
    buffer = true,
    calc = true,
    nvim_lsp = true,
    nvim_lua = true,
    luasnip = true,
  };
})

local opts = {expr = true, noremap = true, silent = true}
vim.api.nvim_set_keymap('i', '<C-y>', "compe#confirm('<C-y>')", opts)
```

Here are my mappings, which I got from #1 

```lua
local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col('.') - 1
    if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
        return true
    else
        return false
    end
end

-- compe funcs WITH luasnip check
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif require("luasnip").expand_or_jumpable() then
        return t "<cmd>lua require'luasnip'.jump(1)<Cr>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end

_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif require("luasnip").jumpable(-1) then
        return t "<cmd>lua require'luasnip'.jump(-1)<CR>"
    else
        return t "<S-Tab>"
    end
end

vim.api.nvim_set_keymap("i", "<C-E>", "<Plug>luasnip-next-choice", {})
vim.api.nvim_set_keymap("s", "<C-E>", "<Plug>luasnip-next-choice", {})

vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
```

I've configured my language servers like I've seen in your dotfiles and in the compe repo

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
require'lspconfig'.pyright.setup({
  capabilities = capabilities
})
```

Then when I'm in a in a python file, I can run `:LuaSnipListAvailable`, and see all sorts of available snippets in the pager. But if I try and type one of the triggers, I simply see nothing in compe.

![image](https://user-images.githubusercontent.com/32942052/128626507-5c008d7c-b89c-407e-8be6-24bb542111b4.png)
there should be the `for` snippet ready for expansion.

**Comment by clason** [comment]
Are you sure that Pyright supports snippets?

**Comment by L3MON4D3** [comment]
I think this may be caused by lazy-loading, you could try calling [this](https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/lazy.lua#L37) manually

**Comment by leiserfg** [comment]
I will suggest not to do 
 ```lua
  use {
    "rafamadriz/friendly-snippets",
    event = "InsertCharPre"  --- THIS PART
  }
  ```
 as friendly snippet has no vim(or lua) code at all so you are not getting any extra time with this and it's probably messing up the load of the snippets.

**Comment by GideonWolfe** [comment]
> I think this may be caused by lazy-loading, you could try calling [this](https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/lazy.lua#L37) manually

Apologies, I'm very new with setting up `nvim` with `lua` configs. How would I go about calling that function manually?

**Comment by GideonWolfe** [comment]
> I will suggest not to do
> 
> ```lua
>  use {
>    "rafamadriz/friendly-snippets",
>    event = "InsertCharPre"  --- THIS PART
>  }
> ```
> 
> as friendly snippet has no vim(or lua) code at all so you are not getting any extra time with this and it's probably messing up the load of the snippets.

That didn't seem to work unfortunately :( Oh well, at least it's tidier

**Comment by L3MON4D3** [comment]
Oh, I shouldn't have marked the whole function, just put `require'compe'.register_source('luasnip', require'compe_luasnip')` in your `configs.luasnip`.

**Comment by GideonWolfe** [comment]
![image](https://user-images.githubusercontent.com/32942052/128642224-d086f39d-2b83-449d-aaed-6891359eb403.png)
Success! Now I just need to style things a bit better haha

**Comment by GideonWolfe** [comment]
There still seems to be some wonkiness with my key mappings. So here I'll just open my `luasnip` config for example.

If I'm in `INSERT` mode and at the beginning of a blank line and press `Tab`, I get this error:

```
E5108: Error executing lua /home/gideon/.config/nvim/lua/mappings.lua:53: attempt to index a boolean value
```
Here's where that's going wrong in `mappings.lua`

```lua
-- compe funcs WITH luasnip check
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif require("luasnip").expand_or_jumpable() then  -- THIS IS LINE 53
        return t "<cmd>lua require'luasnip'.jump(1)<Cr>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end

When I'm presented with that error and I press `ESC`, I get the following error
```

```
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:52: /home/gideon/.config/nvim/lua/configs/luasnip.lua:9: attempt to index local 'luasnip' (a boolean val
ue)
Press ENTER or type command to continue
Error detected while processing InsertLeave Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
Press ENTER or type command to continue
```

**Comment by L3MON4D3** [comment]
Are you loading the mappings conditionally as well?

**Comment by L3MON4D3** [comment]
Or, more precisely, are the maybe loaded before Luasnip is?

**Comment by GideonWolfe** [comment]
Should I load all my mappings after all my plugins?

**Comment by GideonWolfe** [comment]
I switched the order that I'm requiring them in my `init.lua`, and it hasn't broken anything that I can see, so we'll see if this fixes the issue (it's a bit difficult to reproduce).

However one thing that isn't working how it should be is using `Ctrl+E` to advance to the next section?

```lua
vim.api.nvim_set_keymap("i", "<C-E>", "<Plug>luasnip-next-choice", {})
vim.api.nvim_set_keymap("s", "<C-E>", "<Plug>luasnip-next-choice", {})
```

Unless I'm misunderstanding, this should advance the cursor to the next configured "slot" in the snippet? When I'm insert mode after writing something and I press `Ctrl+E`, an error flashes that says something like

```
error executing ...some/path/packer/start/luasnip/lua/luasnip/init.lua:125 attempt to index global `luasnip_active_choice` (a nil value)
```

**Comment by L3MON4D3** [comment]
Oh no, that's for changing the choice in choiceNodes. 
Not to sure about packers handles lazy-loading, but I'd expect changing choices to work :/

**Comment by GideonWolfe** [comment]
Just to confirm, what is the `Ctrl+E` bind supposed to do? What are the choiceNodes? Because I'm probably just misusing it

**Comment by L3MON4D3** [comment]
Check `DOC.md`, but if you don't know what they are you don't need to worry about the mapping :D
You only have to have expand and jump mapped somewhere.
I think somewhere further down in #1 there was an example that also works with lazy-loading.

**Comment by polyzen** [comment]
> I've configured my language servers like I've seen in your dotfiles and in the compe repo
> 
> ```lua
> local capabilities = vim.lsp.protocol.make_client_capabilities()
> capabilities.textDocument.completion.completionItem.snippetSupport = true
> require'lspconfig'.pyright.setup({
>   capabilities = capabilities
> })
> ```
> 
> Then when I'm in a in a python file, I can run `:LuaSnipListAvailable`, and see all sorts of available snippets in the pager. But if I try and type one of the triggers, I simply see nothing in compe.

pyright does not have snippet support -- that is only available in pylance.

**Comment by L3MON4D3** [comment]
@GideonWolfe Is your problem fixed?
