### ISSUE TITLE
inserting quote as the first thing removes the whole snippet and inserts a quote (nvim-cmp + luasnip)

### ISSUE THREAD

**Issue by abzrg** [L3MON4D3/LuaSnip#1037]
For example in C when I expand the snippet for `printf` I will have this:

```c
printf(<<const char *__restrict format, ...>>)
```

the thing in between `<<` and `>>` is in select mode, ready to be changed as I start to type. However, when I type a single/double quote this is what I will get:

```c
"
```

I'm not sure if this is related to `nvim-cmp`, `LuaSnip` or other things, but here's my config and neovim version:

```
$ nvim --version
NVIM v0.10.0-dev-887+g18062f70d
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
````

```lua
local cmp_loaded, cmp = pcall(require, "cmp")
if not cmp_loaded then
  return
end

local luasnip_loaded, luasnip = pcall(require, "luasnip")
if not luasnip_loaded then
  return
end


-- Luasnipt config
luasnip.config.set_config {
  history = false,
  updateevents = "TextChanged,TextChangedI",
}
require("luasnip/loaders/from_vscode").lazy_load()


local kind_icons = {
  Text = "txt",
  Method = "mthd",
  Function = "func",
  Constructor = "ctor",
  Field = "field",
  Variable = "var",
  Class = "cls",
  Interface = "interface",
  Module = "mod",
  Property = "prop",
  Unit = "unit",
  Value = "val",
  Enum = "enum",
  Keyword = "kw",
  Snippet = "snip",
  Color = "color",
  File = "file",
  Reference = "ref",
  Folder = "folder",
  EnumMember = "eunmMem",
  Constant = "const",
  Struct = "struct",
  Event = "event",
  Operator = "op",
  TypeParameter = "typeParam",
}


-- Used for super tab behavior
local has_words_before = function()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

-- Setup
cmp.setup {
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },

  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },

  mapping = cmp.mapping.preset.insert({
    ["<C-p>"]     = cmp.mapping.select_prev_item(),
    ["<C-n>"]     = cmp.mapping.select_next_item(),
    ['<C-b>']     = cmp.mapping.scroll_docs(-4),
    ['<C-f>']     = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>']     = cmp.mapping.abort(),
    ['<C-y>']     = cmp.mapping.abort(),
    ['<CR>']      = cmp.mapping.confirm({ select = false }),
    ["<Tab>"]     = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.confirm({ select = false })
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { "i", "s" }),
    ["<S-Tab>"]   = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.confirm({ select = false })
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { "i", "s" }),
  }),


  formatting = {
    fields = { "abbr", "kind", "menu" },
    format = function(entry, vim_item)
      vim_item.kind = string.format("%s", kind_icons[vim_item.kind])
      vim_item.menu = ({
        luasnip = "[Snippet]",
        nvim_lua = "[NvLua]",
        nvim_lsp = "[LSP]",
        pandoc_references = "Ref",
        cmp_git = "Git",
        buffer = "[Buffer]",
        path = "[Path]",
        -- omni = "[Omni]"
      })[entry.source.name]
      return vim_item
    end,
  },

  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
    { name = "nvim_lua" },
    { name = 'luasnip' },
    { name = "pandoc_references" },
    { name = "cmp_git" },
    { name = "buffer",           keyword_length = 3 },
    { name = "path" },
  }),

  completion = {
    -- autocomplete = true,
    completeopt = 'menu,menuone,noinsert,select'
  },

  confirm_opts = {
    behavior = cmp.ConfirmBehavior.Replace,
    select = false,
  },
}
```

**Comment by L3MON4D3** [comment]
Hey!
I can't see spot anything suspicious in your cmp-config (the native menu seems to cause issues, but you don't have that set up afaict), could you try removing other plugins/start from a clean config to make sure it's actually luasnip and nvim-cmp?

**Comment by abzrg** [comment]
Hi. I tested lazy.nvim + nvim-cmp + luasnip + lspconfig + mason and it was fine. So I think it is only me that I have this problem and on top of that my config is a big one and I think there's some bug in there and I don't care enough at the moment to fix that mess. I might start from scratch for a simpler config.

**Comment by abzrg** [comment]
Ok. After spending a lot of time, I found the bug. it is this piece of mapping and I'm not sure why this is the problem:

```lua
-- Surround stuff in visual mode
vim.keymap.set("v", "*", "S*")
vim.keymap.set("v", "_", "S_")
vim.keymap.set("v", "'", "S'")
vim.keymap.set("v", '"', 'S"')
vim.keymap.set("v", "`", "S`")
vim.keymap.set("v", "(", "S(")
vim.keymap.set("v", "[", "S[")
```

**Comment by L3MON4D3** [comment]
Ahhh no :/
So the S behaves like in Normal-Mode? That's a bit surprising, sure this mapping is all there is to it?

**Comment by abzrg** [comment]
Yes. First I noticed by not sourcing my remaps file I don't get this issue, so the bug must be there. Then I logrithmically cut my mapping config to reach this mapping. I commented this line and the problem was gone. I think for this mapping to work I need to have vim-surround installed.

**Comment by L3MON4D3** [comment]
Oh, no doubt that without the mapping everything works, and 
Maybe I'm just completely forgetting how mappings work, but if I type a S while having text selected, the selected text is replaced by a S, and not the entire line cut.
Just wondering about that😅

**Comment by abzrg** [comment]
OK. I found it:

> xmap creates a mapping for just Visual mode whereas vmap creates one for both Visual mode and Select mode

from [here](https://vi.stackexchange.com/questions/11852/should-i-use-xmap-or-vmap-in-my-mappings)

So I should instead do:

```lua
vim.keymap.set("x", '"', 'S"')
```

**Comment by abzrg** [comment]
From vim-surround.txt

> In visual mode, a simple "S" with an argument wraps the selection.  This is
referred to as the *vS* mapping, although ordinarily there will be
additional keystrokes between the v and S.  In linewise visual mode, the
surroundings are placed on separate lines and indented.  In blockwise visual
mode, each line is surrounded.

`nvim -u None` does what you expect, so I think that's the culprit

**Comment by L3MON4D3** [comment]
Aahh okay, thank you for satisfying my curiosity :)
