### ISSUE TITLE
Is there a way to align the text from an insert node inside a block?

### ISSUE THREAD

**Issue by ronisbr** [L3MON4D3/LuaSnip#1045]
Hi @L3MON4D3 !

First of all, thanks for this amazing plugin!

I am trying to achieve the following effect:

1. Type a string to trigger a snippet.
2. Get the user input in an insert node.
3. Add a text node with the following format:

```
############################################################################################
#                                  This is the user input                                  #
############################################################################################
```

I can easily do this using an insert node and a dynamic node. The problem is that when the snippet expansion is finished, the text in the insert mode remains on the buffer, leading to:

```
This is the user input
############################################################################################
#                                  This is the user input                                  #
############################################################################################
```

Is there any way to remove this node after the expansion is finished?

**Comment by L3MON4D3** [comment]
Hey!
Oh, exactly how you want it is hard to achieve :/

Have you considered letting the user type into the box directly? (which is much simpler, check [this example](https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#box-comment-like-ultisnips)
If you set your `update_events` (check `DOC.md`) to `TextChangedI`, the box-characters will even update immediately :)

**Comment by leiserfg** [comment]
@L3MON4D3  
Adding the range of text rendered to the `leave` event of the snippet should make this doable. Another user case will be to implement something like this with luasnip:
https://github.com/jceb/emmet.snippets#usage

**Comment by ronisbr** [comment]
Hi @L3MON4D3 and @leiserfg 

Thanks!

> Have you considered letting the user type into the box directly?

This behavior is waaaay better :D

**Comment by L3MON4D3** [comment]
> @L3MON4D3 Adding the range of text rendered to the `leave` event of the snippet should make this doable. Another user case will be to implement something like this with luasnip: https://github.com/jceb/emmet.snippets#usage

Oh right, yeah that would produce the exact behavior

That emmet-stuff is really cool, and almost easily implemented via dynamicNode, the only annoying bit is removing the text of the insertNode.

**Comment by L3MON4D3** [comment]
> This behavior is waaaay better :D

Was kind of hoping for that :D
Happy it works for you :)

**Comment by ronisbr** [comment]
Just for the reference, I am using this snipper:

```lua
--- Return the comment box line considering the string `str`.
function M.comment_box_line(str)
  local cur_pos   = vim.api.nvim_win_get_cursor(0)
  local str_width = vim.fn.strdisplaywidth(str)
  local tw        = vim.o.textwidth

  local ind = vim.fn.indent(cur_pos[1])
  local cbw = tw - ind

  if ((cbw >= 0) and (str_width < cbw - 4)) then
    return string.rep("#", cbw)
  else
    return string.rep("#", str_width + 4)
  end
end

--- Return the left padding of the comment box text line considering the string `str`.
function M.comment_box_left_padding(str)
  local cur_pos   = vim.api.nvim_win_get_cursor(0)
  local str_width = vim.fn.strdisplaywidth(str)
  local tw        = vim.o.textwidth

  local ind = vim.fn.indent(cur_pos[1])
  local cbw = tw - ind

  if ((cbw >= 0) and (str_width < cbw - 4)) then
    local lpad = math.floor((cbw - 2 - str_width) / 2)
    local lstr = string.rep(" ", lpad)

    return "#" .. lstr
  else
    return "# "
  end
end

--- Return the right padding of the comment box text line considering the string `str`.
function M.comment_box_right_padding(str)
  local tw        = vim.o.textwidth
  local str_width = vim.fn.strdisplaywidth(str)
  local cur_pos   = vim.api.nvim_win_get_cursor(0)

  local ind = vim.fn.indent(cur_pos[1])
  local cbw = tw - ind

  if ((cbw >= 0) and (str_width < cbw - 4)) then
    local lpad = math.floor((cbw - 2 - str_width) / 2)
    local rpad = cbw - 2 - str_width - lpad

    local rstr = string.rep(" ", rpad)

    return rstr .. "#"
  else
    return " #"
  end
end

...

      ls.snippet({
        trig = "jlcblk",
        dscr = "Julia Comment Block",
        docstring = {
          "###############################",
          "#            Comment          #",
          "###############################",
        },
      }, {
          ls.function_node(function (args)
            return M.comment_box_line(args[1][1])
          end, { 1 }),
          ls.text_node({ "", ""}),
          ls.function_node(function (args)
            return M.comment_box_left_padding(args[1][1])
          end, { 1 }),
          ls.insert_node(1, "Box"),
          ls.function_node(function (args)
            return M.comment_box_right_padding(args[1][1])
          end, { 1 }),
          ls.text_node({ "", ""}),
          ls.function_node(function (args)
            return M.comment_box_line(args[1][1])
          end, { 1 }),
        }),

...
```

leading to this amazing effect:


https://github.com/L3MON4D3/LuaSnip/assets/1068295/5bc8d9db-8392-411a-b06f-36310a1c129b

It even works inside a function where the indentation is higher than 0 :)

Thanks @L3MON4D3 ! Every day I am positively surprised by how configurable LuaSnip is :)
