### ISSUE TITLE
Invalid paths don't cause errors

### ISSUE THREAD

**Issue by fudini** [L3MON4D3/LuaSnip#1048]
For example, running this will silently fail. I think it would be useful to show an error message in cases like this.

```lua
require('luasnip.loaders.from_vscode').lazy_load({
  paths = { './idontexist' }
})
```

**Comment by L3MON4D3** [comment]
Definitely a good idea, but I'm a bit hesitant because this would certainly produce errors for lots of users.

How about we just write an error to the log, but don't really `error()`?

**Comment by L3MON4D3** [comment]
Added a `warn`ing when a passed path could not be resolved.
