### ISSUE TITLE
Snippet for empty filetypes

### ISSUE THREAD

**Issue by oysandvik94** [L3MON4D3/LuaSnip#1052]
**Problem:**

I would like to add a shebang snippet for bash scripts, and I would like it to be active for "sh" filetypes, but also for files with no file extension where there is no filetype. 

**Possible solution:**

There is a "all" filetype, but could one add a "none" as well? Or is it restricted by how vim parses filetypes?

**Comment by leiserfg** [comment]
Use `all`

**Comment by oysandvik94** [comment]
Issue with that is that the snippet would be in all files. The use case I imagined the snippet would only be relevant for .sh and empy file types.

**Comment by leiserfg** [comment]
Then use `""` so it only matches the empty filetype. You probably wanna add it as `[""]`.

**Comment by oysandvik94** [comment]
Thanks, it also worked loading the snippet from a file without a name, like ".lua"

**Comment by oysandvik94** [comment]
Thanks, it also worked loading the snippet from a file without a name, like ".lua"
