### ISSUE TITLE
Custom snippet do not work

### ISSUE THREAD

**Issue by finalclass** [L3MON4D3/LuaSnip#1053]
This snippet does not work:

![Peek 2023-11-10 10-15](https://github.com/L3MON4D3/LuaSnip/assets/1343930/c4be1069-1bf5-445b-945f-995a0dba5173)

However a snippet for ternary taken from the documentation does work fine:

```
        s("ternary", {
          -- equivalent to "${1:cond} ? ${2:then} : ${3:else}"
          i(1, "cond"),
          t(" ? "),
          i(2, "then"),
          t(" : "),
          i(3, "else"),
        }),
```

What am I doing wrong?

**Comment by L3MON4D3** [comment]
Ahh, `\n` is evil, luasnip wants linebreaks via `string[]`

(so, `"asdf\nqwer"` should be `{"asdf", "qwer"}`)

**Comment by finalclass** [comment]
Thx for help. I can confirm that this works well:

```lua
        s("tr", {
          t({
            '"": {',
            '  "pl": ""',
            "}",
          }),
        }),
```
