### ISSUE TITLE
LuaSnip tag 'v2.0.1' mistakenly reported as '2.1.0' in Releases

### ISSUE THREAD

**Issue by BrokenParity** [L3MON4D3/LuaSnip#1059]
I can't find any reference to '2.1.0'. Is it my eyes or your mistake ?

**Comment by L3MON4D3** [comment]
:facepalm:
Yeah, that's a mistake :|
Sorry about that, no idea how I missed it :(

**Comment by L3MON4D3** [comment]
Okay, let's hope two tags to the same commit doesn't cause any issues

**Comment by leiserfg** [comment]
@L3MON4D3  if there are breaking changes in the API of any sort, the 2.0.1 tag should be deleted to avoid issues with users using "2.0.*".

**Comment by L3MON4D3** [comment]
Oh true, yes, ty!
Seems like nothing bad should happen if I just delete the tag, doing that.
