### ISSUE TITLE
Multi-trigger with trigger insert

### ISSUE THREAD

**Issue by nobe4** [L3MON4D3/LuaSnip#1061]
Hi 👋 

Here's a snippet I currently use:

```lua
local conventional_commit_types = { "feat", "fix", "docs", "refactor", "test" }
for _, type in ipairs(conventional_commit_types) do
  ls.add_snippets("gitcommit", {
    ls.parser.parse_snippet(type, type .. "(${1:reference}): ${2:title}\n\n${3:body}"),
  })
end
```

This works well but I am wondering if it would be possible to define a snippet that match multiple triggers and add the match in the result string. Something like:

```lua
ls.add_snippets("gitcommit", {
  ls.parser.parse_snippet(
    { "feat", "fix", "docs", "refactor", "test" },
    "${trigger}(${1:reference}): ${2:title}\n\n${3:body}"
  ),
})
```

I looked at https://github.com/L3MON4D3/LuaSnip/issues?q=is:issue%20state:closed%20multi%20trigger and other matching issues but couldn't find what I wanted, tho https://github.com/L3MON4D3/LuaSnip/issues/921 was an interesting read.

**Comment by nobe4** [comment]
I got something working with a function node, adding it here as a reference for later lurkers:

```lua
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local ms = ls.multi_snippet

local conventional_commit_types = { "feat", "fix", "docs", "refactor", "test" }
ls.add_snippets("gitcommit", {
	ms(conventional_commit_types, {
		f(function(_, parent)
			return parent.trigger
		end, {}),
		t("("),
		i(1, "reference"),
		t("): "),
		i(2, "title"),
		i(3, "body"),
	}),
})
```

**Comment by L3MON4D3** [comment]
Ah, nifty!
Maybe a bit more generic: have you considered wrapping the snippet-construction in a function, which takes the trigger/other parameters? In this case your solution is certainly more compact, but for more complicated variations, a function can be a nice solution :)

**Comment by nobe4** [comment]
```lua
  ms(
    { "feat", "fix", "docs", "refactor", "test" },
    fmt(
      [[
      {}({}):{}

      {}
      ]],
      {
        f(function(_, parent)
          return parent.trigger
        end, {}),
        i(1, "reference"),
        i(2, "title"),
        i(3, "body"),
      }
    )
  )
```
[This](https://github.com/nobe4/dotfiles/blob/568ecc8894d9c40861167a1c02825e471b599304/nvim/after/plugin/luasnip.lua#L69-L87) is what I ended up doing, mostly adding `fmt` for newlines prettiness 💅 

I am not sure I understand which part would you wrap in a function 🤔 Do you have an example in mind?

**Comment by L3MON4D3** [comment]
Oh, just something like
```lua
function s_commit(type)
    return ls.parser.parse_snippet(type, type .. "(${1:reference}): ${2:title}\n\n${3:body}")
end

ls.add_snippets("gitcommit", {
    s_commit("feat"),
    s_commit("fix"),
    s_commit("docs"),
    s_commit("refactor"),
    s_commit("test"),
})
```

**Comment by nobe4** [comment]
ah yes, that's very nice indeed, that's almost what I started with, except I used a loop and not a functin.
