### ISSUE TITLE
LuaSnip disables `<tab>` key

### ISSUE THREAD

**Issue by mlinke-ai** [L3MON4D3/LuaSnip#1063]
When in insert mode, I cannot type in a `<tab>`. After disabling the LuaSnip configuration, the `<tab>` key behaves normally and I can insert an indentation. The strange part is, that the `<tab>` key is not mapped to anything (`:verbose imap <tab>` shows no mappings) and the `<tab>` key is not used in my configuration.

The configuration is as follows:
```lua
local ls = require("luasnip")
require("luasnip.loaders.from_lua").load({ paths = "~/.config/nvim/snippets" })

vim.keymap.set("i", "<C-i>", function()
	ls.expand()
end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-l>", function()
	ls.jump(1)
end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-h>", function()
	ls.jump(-1)
end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-e>", function()
	if ls.choice_active() then
		ls.change_choice(1)
	end
end, { silent = true })
```

**Comment by L3MON4D3** [comment]
Oh! I think `<C-i>` is the same as <tab>, if you change that mapping, does it work?

**Comment by mlinke-ai** [comment]
Yes, I changed `<C-i>` to `<C-q>` and the `<tab>` key is working again. Thank you very much

**Comment by leiserfg** [comment]
You can also use a terminal implementing kitty keyboard protocol (kitty, wezterm, foot...) in those, nvim can differentiate `<c-i>` from `tab`

**Comment by mlinke-ai** [comment]
For me, the problem is resolved, so I am closing the issue.

**Comment by leiserfg** [comment]
> Funny, because I am using kitty as my terminal.

alone or together with a terminal multiplexer?

**Comment by mlinke-ai** [comment]
> alone or with a terminal multiplexer (tmux)? 

Just plain kitty. No multiplexer.

**Comment by gambhirsharma** [comment]
> Oh! I think `<C-i>` is the same as `<tab>`, if you change that mapping, does it work?

I wish I'd known this earlier—it would have saved me two hours of debugging 🥲
