### ISSUE TITLE
bump jsregexp to 0.6

### ISSUE THREAD

**Issue by teto** [L3MON4D3/LuaSnip#1065]
thanks for uploading luasnip to luarocks.org .
I tried to package it for https://github.com/nixos/nixpkgs but in nixpkgs, we have the 0.6 version of jsregexp while luasnip 
mandates the 0.5 in the rockspec:
`dependencies = { 'lua >= 5.1', 'jsregexp == 0.0.5' } `

Would it be possible to bump jsregexp dependency to >= 0.5 . Does it trigger any special issue ?

cc @mrcjkb

**Comment by L3MON4D3** [comment]
Ah, yeah there were some api-changes from 0.0.5 to 0.0.6, so we'd have to adapt to those. But apart from having to make those, there are no issues with updating to 0.0.6

**Comment by teto** [comment]
that would be very cool !

**Comment by L3MON4D3** [comment]
Alriight, that's that :D

**Comment by teto** [comment]
adressed in https://github.com/L3MON4D3/LuaSnip/pull/1067 ty
