### ISSUE TITLE
Git crash when looking for updates of this plugin via lazy

### ISSUE THREAD

**Issue by kmoschcau** [L3MON4D3/LuaSnip#1068]
When I recently tried to check for updates of this plugin via lazy, git crashes on the first attempt, then fails on a second attempt because of a lock file that has not been cleaned up. The lock file in question is `.git/objects/info/commit-graphs/commit-graph-chain.lock`

My hunch is, this is because of the branch named `windows-😐`.

I've had this happen on both Windows and Linux, both running git version 2.43.0. The only place where it didn't happen was in WSL, where git is of version 2.34.1.

Here is the related Lazy issue: https://github.com/folke/lazy.nvim/issues/1204

**Comment by L3MON4D3** [comment]
Oh okay.. I'd be a bit surprised if it was caused by a branch-name, but I'll delete it just in case, it's old anyway.
Was it a one-time occurrence, or could you reproduce it?

**Comment by kmoschcau** [comment]
I can repro it each time I check for a new version. It's a single button press.

**Comment by L3MON4D3** [comment]
I've deleted the branch in question, does it still occur?

**Comment by kmoschcau** [comment]
I just checked again on the Windows machine and it does still occur. Even after completely fresh checkout. The initial clone, including submodule works. Just checking for updates fails. I'll have a look later on the Linux machine.

**Comment by ZeekDaGeek** [comment]
I know this really isn't a satisfying solution, it doesn't help you prevent it from happening again, but:

Placing your cursor over LuaSnip and pressing `x` to delete, then pressing `I` (capital i) to install again solved the problem.

So basically, have you tried turning it off and on again?

**Comment by V-J-P** [comment]
reinstalling the plugin with x I on lazy fixed this.

**Comment by kmoschcau** [comment]
Ultimately we found a workaround in the lazy thread: https://github.com/folke/lazy.nvim/issues/1204#issuecomment-1903577139

I tested it myself and it prevents the error from occurring. Closing this.
