### ISSUE TITLE
Source For nvim-cmp

### ISSUE THREAD

**Issue by saadparwaiz1** [L3MON4D3/LuaSnip#107]
Hi, I was wondering if there are any plans to create a source for `nvim-cmp`.  `nvim-compe` will be depercated in favour of this by the author as mention in https://github.com/hrsh7th/nvim-cmp/issues/2#issuecomment-894268581

**Comment by saadparwaiz1** [comment]
I have created a [source](https://github.com/saadparwaiz1/cmp_luasnip/tree/master) for nvim-cmp. Any feedback or changes will be really apperciated!

**Comment by L3MON4D3** [comment]
Ayy, really nice :+1:.
I didn't see any obvious issues (code-wise), I'll link it in the README :D
