### ISSUE TITLE
failed to update `LuaSnip` via `Lazy.nvim`

### ISSUE THREAD

**Issue by hopezh** [L3MON4D3/LuaSnip#1071]
I got the following error and failed to update `LuaSnip` inside [my `LazyVim` config](https://github.com/hopezh/oatLazyVim). 

May I ask if what it means, and how to fix this issue? 

Thanks. 

```
  Failed (1)
    ● LuaSnip 29.68ms 󰢱 luasnip  nvim-cmp
        You have local changes in `/Users/minioat/.local/share/OatLazyVim/lazy/LuaSnip`:
          * .github/workflows/luarocks.yml
          * .gitignore
          * .gitmodules
          * Makefile
          * deps/jsregexp
        Please remove them to update.
        You can also press `x` to remove the plugin and then `I` to install it again.
```

Screen image: 
<img width="998" alt="Screenshot 2023-12-02 at 11 31 49" src="https://github.com/L3MON4D3/LuaSnip/assets/23435810/bb47a469-8272-474b-8944-c75676883828">

**Comment by zer09** [comment]
add this
```lua
{
	"L3MON4D3/LuaSnip",
	-- follow latest release.
	version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
	-- install jsregexp (optional!).
	build = "make install_jsregexp"
}
```

then reinstall `LuaSnip`

**Comment by hopezh** [comment]
Yes, it works. Thank you very much.

**Comment by rbjorklin** [comment]
Adding a "me too" and noting that I had to run `rm -rf ~/.local/share/nvim/lazy/LuaSnip` to get rid of the errors.

**Comment by gabeio** [comment]
I was running a pretty old version (v.2.1.1) when I tried to upgrade and hit this issue. I tried a few things like trying to reclone/checkout the submodule (specifically `jsregexp005`) but I'm not well versed on submodules so I was unsuccessful and ended up moving it out of the way and forcing Lazy to reinstall it (which worked fine 🎉).

**Comment by iryan2** [comment]
Just noting that I hit this too, and was able to resolve it thanks to the comments in this thread. All I did was `rm -rf ~/.local/share/nvim/lazy/LuaSnip` and Lazy correctly did it's thing the next time I opened vim. FWIW I don't have `recurse` in my .gitconfig.

**Comment by octocron** [comment]
Currently haf this issue today.  I have placed the 3 lines correctly for Lazy using the plugin.  Worked fine for a while...

Followed `rm -rf ~/.local/share/nvim/lazy/LuaSnip` reopened and it is working again.
Just wanted you to know this problem, whatever it is, still occurs.

**Comment by nicoandmee** [comment]
> Currently haf this issue today. I have placed the 3 lines correctly for Lazy using the plugin. Worked fine for a while...
> 
> Followed `rm -rf ~/.local/share/nvim/lazy/LuaSnip` reopened and it is working again. Just wanted you to know this problem, whatever it is, still occurs.

Ditto. This fixed it for me.

**Comment by 0x14Rp** [comment]
> Currently haf this issue today. I have placed the 3 lines correctly for Lazy using the plugin. Worked fine for a while...
> 
> Followed `rm -rf ~/.local/share/nvim/lazy/LuaSnip` reopened and it is working again. Just wanted you to know this problem, whatever it is, still occurs.

this work for me! thx ^^

**Comment by TheRealMothebad** [comment]
Getting this same error on NixOS:
```bash
LuaSnip: nvim-cmp 
        fatal: not a git repository: ../../.git/modules/deps/jsregexp006
        fatal: could not reset submodule index
        You have local changes in `/home/mo/.local/share/nvim/lazy/LuaSnip`
```
It seems to be caused by the presence of some nix flakes in that folder. Would this instead be an issue with how nvim is packaged? (where do I need to post this to help get it fixed?)
```bash
LuaSnip ) ls
data/  doc/    Examples/   flake.nix  LICENSE  Makefile  README.md  tests/
deps/  DOC.md  flake.lock  ftplugin/  lua/     plugin/   syntax/
```

**Comment by TcPirate1** [comment]
I just solved this issue myself but in my case the directory didn't exist but the errors were the same as OP's but then I noticed there was a `luasnip.cloning` file in the `.local/share/nvim/lazy` directory and after deleting that file, LuaSnip was able to reinstall itself.

**Comment by TcPirate1** [comment]
Yes, you're right. I should of mentioned I had tried this already and it didn't work, which is what led me to investigate further.

To be honest I'm not sure what caused this to happen so I'm also not sure how it could be reproduced.

**Comment by L3MON4D3** [comment]
Hey wow that's not happened for some time :P
tbh I think it's because of updating git-submodules, maybe lazy can't deal with them properly? Or I'm updating them improperly somehow?
