### ISSUE TITLE
Adding exclude/include to lazy_load for vscode prevents any snippets from loading from friendly-snippets

### ISSUE THREAD

**Issue by haoming-li-ling** [L3MON4D3/LuaSnip#1077]
As in the title. In order for LuaSnip to load anything from friendly-snippets, I cannot use any `include`/`exclude` fields in the `require("luasnip.loaders.from_vscode").lazy_load()` call. I wonder why this begins to happen as of the recent updates.

**Comment by L3MON4D3** [comment]
I swapped include and exclude in some calls :|
Thank you for opening the issue :)
