### ISSUE TITLE
Using filetype_extend but the extending target snippet is empty

### ISSUE THREAD

**Issue by jackysee** [L3MON4D3/LuaSnip#1079]
In the config I have `luasnip.filetype_extend('typescript', { 'javascript'})`. But when I check using `:LuaSnipListAvailable` in a ts file, the javascript snippet is empty. I do have javascript snippet in place where I can trigger in javascript file. How should I trace the problem?

![image](https://github.com/L3MON4D3/LuaSnip/assets/30516/d42fb56b-aba6-400e-9e15-852061601403)

**Comment by L3MON4D3** [comment]
Does luasniplistavailable in a js-file show snippets?
The snippet you do have in js may be from LSP

**Comment by jackysee** [comment]
Yes `:LuaSnipListAvailable` does list snippet when I'm in js file.

**Comment by L3MON4D3** [comment]
Ah, if you use `lazy_load` to load the snippets, the filetype-extension has to exist when it is called, otherwise they may not be loaded when `typescript` becomes active..
Is `filetype_extend` called before `lazy_load`? Or do you just call `load`?

**Comment by jackysee** [comment]
Thank you! That's the problem. I called `lazy_load` before `filetype_extend`. Now that I swapped the order it's working.
