### ISSUE TITLE
Deeply confused by function, dynamic, & lambda nodes, and unsure if/how they could be used to simplify repetitive code

### ISSUE THREAD

**Issue by Corey-Keller** [L3MON4D3/LuaSnip#108]
I have the code below for creating section headers of different levels, and I'm fairly certain that it can be made more elegant, or at least less repetitive, but my lack of understanding of how to utilize f(), l(), dl() (and probably being unaware of some functionality in lua itself) has prevented me from making any headway.

**TL;DR:**
```
s("head#", sn(1, {
	p(mk_header_line,#),
	t({"",""}), -- only way to do a linebreak
	p(mk_comment_str), i(1,"Section"),
	t({"",""}),
	p(mk_header_line,#),
})),
```
I have the above snippet duplicated multiple times (with the only change being the `#` is replaced with the appropriate number, and I'm hoping there's a way to simplify that. Also, if there are better ways to do this, please let me know, as I'm quite new to lua itself

```
local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local p = require("luasnip.extras").partial

local header_levels = {
	{char = '=', len = 60 },
	{ char = '~', len = 45 },
	{ char = '>', len = 30 },
}

-- single line comment string e.g., '--' in lua, '#' in python etc. and
-- then a single space is added to separate it from the rest of the line
local function mk_comment_str()
	return require"kommentary.config".get_single(0) .. " "
end

local function mk_header_line(level)
	local comment_str = mk_comment_str()

	-- include the comment string length in the line limit
	local length = header_levels[level].len - string.len(comment_str)

	return comment_str .. string.rep(header_levels[level].char, length)
end

ls.snippets = {
	all = {
		-- =========================================================
		-- Heading 1
		-- =========================================================
		s("head1", sn(1, {
			p(mk_header_line,1),
			t({"",""}), -- only way to do a linebreak
			p(mk_comment_str), i(1,"Section"),
			t({"",""}),
			p(mk_header_line,1),
		})),
		-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		-- Heading 2
		-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		s("head2", sn(1, {
			p(mk_header_line,2),
			t({"",""}), -- only way to do a linebreak
			p(mk_comment_str), i(1,"Section"),
			t({"",""}),
			p(mk_header_line,2),
		})),
		-- >>>>>>>>>>>>>>>>>>>>>>>>>>>
		-- Heading 3
		-- >>>>>>>>>>>>>>>>>>>>>>>>>>>
		s("head3", sn(1, {
			p(mk_header_line,3),
			t({"",""}), -- only way to do a linebreak
			p(mk_comment_str), i(1,"Section"),
			t({"",""}),
			p(mk_header_line,3),
		})),
	}
}
```

**Comment by L3MON4D3** [comment]
Ouh, nice. Yes, that can be simplified using regex triggers: you'd have to first change the trigger like so
```lua
-- match 'head' followed by any number.
s({"head(%d+)", regTrig=true}, ...)
```
Using that, the triggers' capture groups can be accessed in a functionNode
```lua
-- function is passed a table containing the text of all argument-nodes(0 in this case) followed by the snippet itself.
f(function(args) return mk_header_line(tonumber(args[1].captures[1])) end, {})
```
(Also, it's not necessary to wrap the snippets' nodes in a `sn(1, ...)`, just pass a table containing the nodes)

**Comment by L3MON4D3** [comment]
I'll assume it worked, feel free to reopen if you have more questions :)

**Comment by Corey-Keller** [comment]
It works, yeah. One thing that I'm not a fan of is that using "head(%d)" results in that literal value showing up in the tab completion (with nvim-c[o]mp[e] at least), meaning that when I tab complete it fills in `head(%d)` meaning that I have to backspace 4 times before I can enter the number and then use that to create the snippet.

One of my goals with this question though was to better understand dynamic/lambda nodes for other ways that I could do this.

For example, I know I can do this with choice nodes:
```
s("shead", c(1,{
			sn(1, {
				p(mk_header_line,1),
				t({"",""}), -- only way to do a linebreak
				p(mk_comment_str), i(1,"Section"),
				t({"",""}),
				p(mk_header_line,1),
			}),
			sn(1, {
				p(mk_header_line,2),
				t({"",""}), -- only way to do a linebreak
				p(mk_comment_str), i(1,"Section"),
				t({"",""}),
				p(mk_header_line,2),
			}),
			sn(1, {
				p(mk_header_line,3),
				t({"",""}), -- only way to do a linebreak
				p(mk_comment_str), i(1,"Section"),
				t({"",""}),
				p(mk_header_line,3),
			}),
		}))
```

allowing me to alternate between various levels.

But I assume using dynamic nodes (or lambdas, or dynamic lambdas) I could do something like:
```
p(mk_comment_str), i(2,"Section " .. i(1,"1")),
```
with code above/below it that will adjust automatically to use the `mk_header_line` value of whatever I put in `i(1)` and once I have that set as I like, I move to `i(2)` (which contains `i(1)` so I can replace the entirety of `Header 2` text of `i(2)` without messing up the header lines above/below it)


I also welcome any non-related complex (but documented) examples that more clearly show the types of things that you can do with dynamic nodes, lambdas, and dynamic lambdas.

**Comment by L3MON4D3** [comment]
> It works, yeah. One thing that I'm not a fan of is that using "head(%d)" results in that literal value showing up in the tab completion (with nvim-c[o]mp[e] at least), meaning that when I tab complete it fills in `head(%d)` meaning that I have to backspace 4 times before I can enter the number and then use that to create the snippet.

Mhmm, right, I hadn't thought about that. For regex-snippets we could expand an 'intermediary snippet' that jumps between the non-text parts of the regex trigger and then to the end of it so the snippet could be expanded right there. 

> I also welcome any non-related complex (but documented) examples that more clearly show the types of things that you can do with dynamic nodes, lambdas, and dynamic lambdas.

Well, there's that big, ugly, javadoc-snippet in `Examples/snippets.lua` that makes use of a dynamicNode to create the docstring.
You could also check out the wiki, theres the Latex-list snippet that I'm pretty proud of, but not much more. You could ask in the matrix chat linked in the README, maybe people there have some complex snippets. 

```lua
p(mk_comment_str), i(2,"Section " .. i(1,"1")),
```
You'd have to replace the `i(2)` with a dynamicNode containing two insertNodes and pass that dynamicNode to the p, in mk_comment_string you'll have to get the number at the end of the dynamicNode.

**Comment by L3MON4D3** [comment]
> It works, yeah. One thing that I'm not a fan of is that using "head(%d)" results in that literal value showing up in the tab completion (with nvim-c[o]mp[e] at least), meaning that when I tab complete it fills in head(%d) meaning that I have to backspace 4 times before I can enter the number and then use that to create the snippet.

Check out [this PR to cmp_luasnip](https://github.com/saadparwaiz1/cmp_luasnip/pull/5)

**Comment by Corey-Keller** [comment]
@L3MON4D3 Thanks again for all your awesome work! I noticed another issue with pattern snippets and cmp though, and I'm not sure if the issue should be brought up to LuaSnip, cmp_luasnip, nvim-cmp, or some combination thereof.

The problem is that pattern based matches like `head(%d)` show up as suggestions any time the cursor touches a parentheses (presumably because of the parentheses in the trigger). 

1 thing I did try was using the `name`  parameter in the snippet, but it turns out that that has no bearing on the actually displayed match name.

**Comment by leiserfg** [comment]
That bites me also randomly, it's in the realm of   `cmp_luasnip`.

**Comment by leiserfg** [comment]
One workaround is to use set up  cmp as
```lua
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = false,  --- This
    })
```
So it does not autoselects the  first entry.

**Comment by leiserfg** [comment]
But I the real problem is that cmp_luasnip is providing an item (snippet) that does not match the current string. But most of the time that's the desired behavior so it's kinda tricky to fix.

**Comment by L3MON4D3** [comment]
A not-really-perfect solution would be having the user provide eg. `searchTrig` (defaults to `trig`), which is then actually used to match the snippet in `cmp_luasnip`.
