### ISSUE TITLE
[Bug] Setting `update_events` to 'TextChangedI' break nvim-cmp's `<C-n>` mapping

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#1083]
### Description

If `update_events` contains `TextChangedI` and `<C-n>` in insert mode is remapped in cmp config to select next item in the completion menu, pressing `<C-n>` when the completion menu is visible inside a snippet node will quickly close the completion menu then reopen it with only one completion entry, instead of the expected behavior (selecting the next entry).

---

### Steps to reproduce

1. Create the minimal `init.lua` (see below)
2. Create a sample lua file `test.lua`:

    ```lua

    local function foobar(arg)
        print(arg)
    end
    ```

4. `nvim --clean -u init.lua test.lua`
5. Enter insert mode, type `pck` (the trigger), then press `<Tab>` to expand the snippet

    ![image](https://github.com/L3MON4D3/LuaSnip/assets/76579810/08fda2a5-6b24-4f58-b923-6b2ea54ad02f)
    ![image](https://github.com/L3MON4D3/LuaSnip/assets/76579810/c6d4274a-fbae-4aeb-b11c-20fa869cc115)

7. Inside the snippet, type `f`, cmp auto completes with two entries `foobar` and `function`

    ![image](https://github.com/L3MON4D3/LuaSnip/assets/76579810/1429deb5-97f0-4184-a47b-6ea9dcbabbf6)

9. Press `<C-n>` to select the first entry
10. The completion menu flickers quickly and now we only have one entry `foobar`

    ![image](https://github.com/L3MON4D3/LuaSnip/assets/76579810/5d9abd5e-93cc-47b1-9648-161cc9b7b8c7)

12. Close nvim, comment out line 91 in `init.lua` (which contains `update_events = 'TextChangedI'`) and repeat the steps above, notice how the bug disappears.

**Expected behavior after step 9:**

![image](https://github.com/L3MON4D3/LuaSnip/assets/76579810/8f3f73f3-fe28-4808-bd48-3b587b9b8189)

---

### Env

nvim version: `NVIM v0.10.0-dev-1627+g879617c9bb`
OS: `Arch Linux 6.1.64-1-lts`
luasnip version: commit 954c81b53989097faaff0fabc11c29575288c3e1 (latest)
nvim-cmp version: hrsh7th/nvim-cmp@41d7633e4146dce1072de32cea31ee31b056a131 (lastest)

---

### Minimal config

minimal `init.lua`:

```lua
local tmp = '/tmp'
local data = tmp .. '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local package_root = data .. '/site'
local clone_root = package_root .. '/pack/packages/start'
local clone_info = {
  {
    path = clone_root .. '/nvim-cmp',
    url = 'https://github.com/hrsh7th/nvim-cmp.git',
  },
  {
    path = clone_root .. '/cmp-buffer',
    url = 'https://github.com/hrsh7th/cmp-buffer',
  },
  {
    path = clone_root .. '/cmp_luasnip',
    url = 'https://github.com/saadparwaiz1/cmp_luasnip',
  },
  {
    path = clone_root .. '/LuaSnip',
    url = 'https://github.com/L3MON4D3/LuaSnip.git',
  },
}

vim.fn.mkdir(clone_root, 'p')
vim.opt.pp:prepend(package_root)
vim.opt.rtp:prepend(package_root)

for _, info in ipairs(clone_info) do
  if not vim.loop.fs_stat(info.path) then
    vim.notify('cloning ' .. info.url, vim.log.levels.INFO)
    vim.fn.system({ 'git', 'clone', info.url, info.path })
  end
end

local cmp = require('cmp')
local luasnip = require('luasnip')

cmp.setup({
  enabled = true,
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  sources = {
    { name = 'buffer' },
    { name = 'luasnip' },
  },
  mapping = {
    ['<C-p>'] = {
      ['i'] = function()
        if cmp.visible() then
          cmp.select_prev_item()
        elseif luasnip.choice_active() then
          luasnip.change_choice(-1)
        else
          cmp.complete()
        end
      end,
    },
    ['<C-n>'] = {
      ['i'] = function()
        if cmp.visible() then
          cmp.select_next_item()
        elseif luasnip.choice_active() then
          luasnip.change_choice(1)
        else
          cmp.complete()
        end
      end,
    },
    ['<Tab>'] = {
      ['i'] = function(fallback)
        if luasnip.expandable() then
          luasnip.expand()
        elseif luasnip.locally_jumpable() then
          luasnip.jump(1)
        else
          fallback()
        end
      end,
    },
  },
})

local s = luasnip.snippet
local i = luasnip.insert_node
local fmta = require('luasnip.extras.fmt').fmta

luasnip.setup({
  update_events = 'TextChangedI',
})

luasnip.add_snippets('lua', {
  s(
    'pck',
    fmta(
      'print("<v>: " .. vim.inspect(<v>))',
      { v = i(1) },
      { repeat_duplicates = true }
    )
  ),
}, {})
```

**Comment by L3MON4D3** [comment]
Puh, I suspect that there is something in nvim-cmp that breaks if there is a `nvim_buf_set_text` on the line the pum is open.. since I don't know much about cmp internals, I don't think I can be a big help with that :/

But it would be interesting to figure out exactly what actions by luasnip trigger the misbehaviour:
Could you register an autocommand on TextChangedI, which mimicks luasnips behaviour here, ie. removes some text on the line, and then inserts new text at that position, and check if that also triggers the behaviour?

**Comment by Bekaboo** [comment]
@L3MON4D3 Hi thanks for your reply, you are always so quick in responding the issues :)

> Could you register an autocommand on TextChangedI, which mimicks luasnips behaviour here, ie. removes some text on the line, and then inserts new text at that position, and check if that also triggers the behaviour?

Seems that I should create a function to trigger `TextChangedI` manually (through `nvim_exec_autocmds()` or `:doau`) instead of registering an autocmd that gets called on `TextChangedI`, is that what you mean?

It is quite late now in my time zone, and I have become unfortunately very busy recently, so I might not reply on time, sorry for that in advance.

**Comment by L3MON4D3** [comment]
Yeah, I try to look into bugs soon-ish :)

> Seems that I should create a function to trigger TextChangedI manually

Oh, Nono: I'd like to see if my suspicion that those nvim_buf_set_text luasnip does in it's update_event-callback cause this issue is correct. 
Replacing the complicated update_event-callback with something slimmer (just the nvim_buf_set_text) seems to be the best way to do this.

> It is quite late now in my time zone, and I have become unfortunately very busy recently, so I might not reply on time, sorry for that in advance.

No worries, I can also look into this when I have some time to spend on luasnip :)

**Comment by Bekaboo** [comment]
@L3MON4D3 After some experiment simply changing text inside buffer in a `TextChangedI` callback does not break cmp

Based on the minimal config provided, I comment out the part that sets up luasnip and adds snippets and append this autocmd at the end:

```lua
vim.api.nvim_create_autocmd('TextChangedI', {
  group = vim.api.nvim_create_augroup('LuaSnipTest', {}),
  callback = function()
    local buf_height = vim.api.nvim_buf_line_count(0)
    vim.api.nvim_buf_set_text(0, buf_height - 1, 0, buf_height - 1, 0, {
      'abcd',
    })
  end,
})
```

Recording:

https://github.com/L3MON4D3/LuaSnip/assets/76579810/b48aeeb5-d9d9-4990-8029-1ee76b9d4ed1

As you can see the text in the last line changes without breaking cmp

Compare with luasnip:


https://github.com/L3MON4D3/LuaSnip/assets/76579810/b2d25062-9a11-42e3-9887-482472e671f2


It must be something else that cause this issue.

**Comment by L3MON4D3** [comment]
Damn okay, I'll play around with it and hope there is something minimal

**Comment by L3MON4D3** [comment]
I think one important piece was inserting text *behind* the cursor, I can reproduce it with this:
```lua
local t = "aaaaaaaaaaalellllllllllllaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaal"

vim.api.nvim_create_autocmd('TextChangedI', {
  group = vim.api.nvim_create_augroup('LuaSnipTest', {}),
  callback = function()
    local text = vim.api.nvim_buf_get_text(0, 0, 23, 0, 26, {})
    vim.api.nvim_buf_set_text(0, 0, 23, 0, 26, text)
  end,
})
```

https://github.com/L3MON4D3/LuaSnip/assets/41961280/f5ef0daf-681b-4e90-8bbe-d36b25d8714d

**Comment by Bekaboo** [comment]
Emm, so it seems there's not much we can do for this? It is a cmp bug?

**Comment by L3MON4D3** [comment]
Yeah, I think so :/
Maybe not cmp, it may even be in core, but the next step, I think, would be to open an issue with cmp, they may be able to debug this further with a good minimal example

**Comment by Bekaboo** [comment]
Alright, I will create a issue on cmp to see what can be done for this.

**Comment by L3MON4D3** [comment]
I also use cmp, but with manual triggering. I don't like always having that window on top of the buffer :sweat_smile:

Have you tried `InsertLeave` as your update_events? I think that's a good choice because you can still see the updated text anytime with a quick `<Esc>a`, but it doesn't waste too much time on updating dynamicNode (well, and in this case, sidesteps the bug :D)

**Comment by Bekaboo** [comment]
> Have you tried InsertLeave as your update_events?

Thanks for siggestion. Actually just leaving `update_events` unset will bypass the bug, the text won't be uodated in insert mode, but after leaving insert mode it gets updated. I think the default of `update_events` is 'InsertLeave' or something similar?

**Comment by L3MON4D3** [comment]
Oh, yeah, `"InsertLeave"` is the default :+1:

**Comment by Bekaboo** [comment]
Closing for now because it is not a LuaSnip bug.
