### ISSUE TITLE
util.lua:331 table expected, got number

### ISSUE THREAD

**Issue by timoleistner** [L3MON4D3/LuaSnip#1086]
When I have open a .lua file and try to update Lazy by pressing
`n  <C-P>       * <Cmd>Lazy<CR>`
the following error appears:
```
Error executing Lua callback: ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:125: FileType Autocommands f
or "*": Vim(append):Error executing lua callback: ....local/share/nvim/lazy/LuaSnip/lua/luasnip/util/util.lua:331: bad
 argument #1 to 'ipairs' (table expected, got number)
```
There is another command bound to this keystroke.
```
s  <C-P>       * <Plug>luasnip-prev-choice
n  <C-P>       * <Cmd>Lazy<CR>
```
If I only opened an empty buffer, no error appears and I can update my packages.
Editing this line [for _, ft in ipairs(fts) do](https://github.com/L3MON4D3/LuaSnip/blob/954c81b53989097faaff0fabc11c29575288c3e1/lua/luasnip/util/util.lua#L331C22-L331C22) to `for _, ft in ipairs({fts}) do` the error message is also gone.

Do I just have something miss configured, or is this really a bug?

**Comment by L3MON4D3** [comment]
Hmmm, can't reproduce..
Do you have something set for `load_ft_func` in setup?

**Comment by timoleistner** [comment]
Oh, yes
```
load_ft_func = require("luasnip.extras.filetype_functions").extend_load_ft({
        markdown = { "html" },
})
```
I wanted to be able to use html snippets in a markdown file, therefore I set this.
outcommenting this doesn't fix it. I've noticed that this error appears after I switched the buffer and then try to open Lazy.
The complete error message is this
```
Error executing Lua callback: ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:125: FileType Autocommands f
or "*": Vim(append):Error executing lua callback: ....local/share/nvim/lazy/LuaSnip/lua/luasnip/util/util.lua:331: bad
 argument #1 to 'ipairs' (table expected, got number)
stack traceback:
        [C]: in function 'ipairs'
        ....local/share/nvim/lazy/LuaSnip/lua/luasnip/util/util.lua:331: in function 'redirect_filetypes'
        ...cal/share/nvim/lazy/LuaSnip/lua/luasnip/loaders/init.lua:133: in function 'load_lazy_loaded'
        ...e/timo/.local/share/nvim/lazy/luasnip/plugin/luasnip.lua:87: in function <...e/timo/.local/share/nvim/lazy/
luasnip/plugin/luasnip.lua:86>
        [C]: in function '__newindex'
        ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:125: in function 'mount'
        ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:63: in function 'init'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:53: in function 'create'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:38: in function 'show'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:38: in function 'command'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:24: in function 'cmd'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:108: in function <...cal/share/nvim/lazy/lazy.nvim
/lua/lazy/view/commands.lua:95>
stack traceback:
        [C]: in function '__newindex'
        ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:125: in function 'mount'
        ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:63: in function 'init'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:53: in function 'create'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/view/init.lua:38: in function 'show'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:38: in function 'command'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:24: in function 'cmd'
        ...cal/share/nvim/lazy/lazy.nvim/lua/lazy/view/commands.lua:108: in function <...cal/share/nvim/lazy/lazy.nvim
/lua/lazy/view/commands.lua:95>```

If I uninstall LuaSnip the error does not appear.

**Comment by L3MON4D3** [comment]
I'm a bit stumped by the error: as it stands right now, if `fts` (the value that is nil in ipairs) is actually nil, there would have to be an error even before this (there's a `table.insert(fts, "all")`)..
Could you check if there is an older installation of luasnip in your runtimepath? See #1088 and linked issues for some hints on that.

**Comment by timoleistner** [comment]
I've reinstalled Luasnip by removing the folder in `~/.local/share/nvim/lazy/LuaSnip/` and reinstalling with lazy with the following definition:
```Lua
        {
            "L3MON4D3/LuaSnip",
            version = "v2.*",
            config = function()
                require("snippets")
            end,
            dependencies = {
                "rafamadriz/friendly-snippets"
            },
            build = "make install_jsregexp"
        },
```
It did not fix this issue.

Another thing I've tried is that I printed the `fts`object in the `redirect_filetypes(fts)` function.
`fts`is a table object untill I change the buffer. Then it returns numbers (`8`, `9`).
FYI I also have the [cmp_luasnip](https://github.com/saadparwaiz1/cmp_luasnip) package installed which is likely to return this number with this function:
```Lua
vim.api.nvim_create_autocmd({ "BufWinEnter", "FileType" }, {
	callback = function(event)
        print(event.buf)
		require("luasnip.loaders").load_lazy_loaded(tonumber(event.buf))
	end,
	group = "_luasnip_lazy_load",
})
```
If I am certain that the error is ion this other package I will create an issue there.
Thank you for the reponses so far.

**Comment by L3MON4D3** [comment]
> I've reinstalled Luasnip by removing the folder in ~/.local/share/nvim/lazy/LuaSnip/ and reinstalling with lazy with the following definition:

That does not necessarily rule out that files from an older installation are still in runtimepath! For example from a switch from packer to lazy, at least that is a common root-cause AFAICT

The output of`:lua =vim.api.nvim_get_runtime_file("lua/luasnip/init.lua", true)` (true to get all matches) should indicate if there are two installations: if there are two results, one of them is an old installation.

Another idea: print the values in the caller of `redirect_filetypes` (well, the one in the file installed by lazy), if there is not always a message, there's another file that calls `redirect_filetypes`

> FYI I also have the cmp_luasnip package installed which is likely to return this number with this function:

Oh, isn't that code from luasnip? I don't understand what you mean there :sweat_smile:

**Comment by timoleistner** [comment]
`:lua =vim.api.nvim_get_runtime_file("lua/luasnip/init.lua", true)` returns ` { "/home/timo/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua" }`.

The autocmd function I posted might also appear in your LuaSnip plugin but tracing the error messages this error came from cmp_luasnip plugin as it is saved in `lazy/luasnip` instead of `lazy/LuaSnip` (your plugin).
I suspected that this `tonumber(event.buf)` is responsible for returning a number instead of a table... changing this to `{event.buf}` leads to another error which looks like this
```
Error executing Lua callback: ....local/share/nvim/lazy/lazy.nvim/lua/lazy/view/float.lua:125: FileType Autocommands f
or "*": Vim(append):Error executing lua callback: ...cal/share/nvim/lazy/LuaSnip/lua/luasnip/loaders/init.lua:143: att
empt to index field 'vscode' (a nil value)
```
What do you mean with the caller of `redirect_filetypes`?

What kind of table does `redirect_filetypes` function expect?

**Comment by L3MON4D3** [comment]
Aw man, okay then there's something more going on..
Are you sure that cmp_luasnip is saved as lazy/luasnip? I'm not sure they ever had code like this..

> I suspected that this tonumber(event.buf) is responsible for returning a number instead of a table... changing this to {event.buf} leads to another error which looks like this

Ah, no, that is as it should be, the load_lazy_loaded accepts the bufnr and determines which filetypes should be loaded for that buffer

> What do you mean with the caller of redirect_filetypes?

I mean load_lazy_loaded, sorry, should've been more explicit😅 Iirc redirect_filetypes is called in there

**Comment by timoleistner** [comment]
Oh well I solved it. I looked up information of the luasnip packages installed by lazy and solved the mystery of the two folders.
![image](https://github.com/L3MON4D3/LuaSnip/assets/38843394/141a8533-4e1f-4ca7-8021-b4eceef136ed)
![image](https://github.com/L3MON4D3/LuaSnip/assets/38843394/8dd87e15-b370-4f24-af57-0e4900ec9b94)
As a dependency of nvim-cmp I had luasnip declared as `"l3mon4d3/luasnip"` instead of `"L3MON4D3/LuaSnip"`. This seems to be case sensitive and therefore handles it like another plugin...

I deleted both folders `luasnip` and `LuaSnip` in lazys directory and reinstalled LuaSnip.

Thank you for your time and help!

**Comment by L3MON4D3** [comment]
Ahhh oh :facepalm:
Maybe open an issue about this over at lazy, they may not be aware that there is this behaviour/it can lead to issues like this.

I'm very surprised that there was only one result for the runtimepath despite this.. well, adding this one to my go-to solutions for issues like this :D

**Comment by timoleistner** [comment]
Okay perfect.
Yes I opened an [issue](https://github.com/folke/lazy.nvim/issues/1228) over at lazy.
