### ISSUE TITLE
Expanding snippets is completely broken since a couple of days

### ISSUE THREAD

**Issue by nicholas-roether** [L3MON4D3/LuaSnip#1088]
I don't know when exactly, but at some point during the last couple days, LuaSnip broke for me entirely without any configuration change on my side that I'm aware of. The strange thing is that for some reason, on another device of mine, it works perfectly fine with the exact same configuration. I've tried really hard to debug this problem and find some sort of lead on what's going on, but I'm not getting anywhere :(

Whenever I try to expand a snippet (via `nvim-cmp`), it fails with this error message:

```
E5108: Error executing lua ...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:641: attempt to index field 'snippet_roots' (a nil value)                           
stack traceback:                                                                                                                                                           
        ...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:641: in function 'snippettree_find_undamaged_node'                                                     
        ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:633: in function 'trigger_expand'                                                                      
        ...niko/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:270: in function 'snip_expand'                                                                         
        ...niko/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:392: in function 'lsp_expand'                                                                          
        /home/niko/.config/nvim/lua/plugins/nvim-cmp.lua:15: in function 'expand'                                                                                          
        /home/niko/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:488: in function </home/niko/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:434>                     
        ...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function <...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:45>
```

This is my config for `LuaSnip`:
```lua
return {
	"L3MON4D3/LuaSnip",
	lazy = false,
	version = "v2.*",
	build = "make install_jsregexp"
}
```

This is my config for `nvim-cmp`:
```lua
return {
	"hrsh7th/nvim-cmp",
	lazy = false,
	dependencies = {
		"L3MON4D3/LuaSnip",
		"saadparwaiz1/cmp_luasnip"
	},
	config = function()
		local cmp = require("cmp")
		local luasnip = require("luasnip")

		cmp.setup {
			snippet = {
				expand = function(args)
					luasnip.lsp_expand(args.body)
				end
			},
			mapping = cmp.mapping.preset.insert {
				["<C-Space>"] = cmp.mapping.complete(),
				["<C-e>"] = cmp.mapping.abort(),
				["<CR>"] = cmp.mapping.confirm({ select = false })
			},
			sources = cmp.config.sources({
				{ name = "nvim_lsp" }
			}, {
				{ name = "buffer" }
			})
		}
	end
}
```

**Comment by L3MON4D3** [comment]
I suspect an older version of luasnip is still stuck in your runtimepath, this would explain why it works on another device of yours.
There was another issue about this recently (#1082, #1075) please look into it and try the same debug-steps

**Comment by nicholas-roether** [comment]
Thanks a lot for your response! I had suspected that something like that might be up, so obviously tried reinstalling via lazy.nvim which didn't work, but I didn't think it made sense for some other old install location to be interfering, since the paths in the stacktrace clearly point to the lazy.nvim installation...

In the end, after rummaging around a bit, it turned out that I had some old files left over in `.local/share/nvim/site` from back when I used packer - deleting that directory and reinstalling fixed the issue. I do wonder though why it only stopped working now, it's been months since I migrated to lazy.nvim...

**Comment by L3MON4D3** [comment]
Glad that helped :D
I think it only caused an error now because there were relatively few changes to the different lua-modules for some time, and then some more in the last weeks
