### ISSUE TITLE
Text instead of UI selected prompt

### ISSUE THREAD

**Issue by pronvis** [L3MON4D3/LuaSnip#1089]
Why I see this
<img width="1280" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/228536/765ea26d-d173-4676-b4ec-53a5596a7026">
on `:lua require("luasnip.loaders").edit_snippet_files()`
instead of Selected Prompt like here: https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#edit_snippets ?

Also, I dont have popup menu for snippet selection :( no ideas why (but snippets itself works fine)

Here is my config: 
luasnip itself: https://github.com/pronvis/configs/blob/nvim_to_lua_cfg/nvim/after/plugin/luasnip.lua
keymaps: https://github.com/pronvis/configs/blob/nvim_to_lua_cfg/nvim/lua/pronvis/remap.lua#L75

**Comment by L3MON4D3** [comment]
Ah: neovim provides an interface for selections like this, which may be customized by the user (or through plugins)
I think yours is the default, and the one shown in the documentation is provided by dressing.nvim, so installing that should make the popup look like in the documentation.

Also, you absolutely don't need a popup for snippet selection, using triggers works just as well (better, if you ask me :D)
