### ISSUE TITLE
Neovim becoming slow

### ISSUE THREAD

**Issue by Trid-collab** [L3MON4D3/LuaSnip#109]
I am using the latest neovim nighty have configured luasnip with compe transitioning from hrsh7th/vim-vsnip.
I found that when I use the "require("luasnip/loaders/from_vscode").load()" .
Is there something wrong. tried the lazy_load option as well without much improvement. Is something in my setup.

Also could you guide me how to configure other snippets like "friendly snippets" or "vim snippets" to be use luasnip. I was looking for an configuration guide for a layman like me, but could not find one hence writing in this forum.

My config luasnip is as follows:

local present, luasnip = pcall(require, "luasnip")
if not present then
	return
end

luasnip.config.set_config({
	history = true,
	updateevents = "TextChanged,TextChangedI",
})
require("luasnip/loaders/from_vscode").load()

**Comment by L3MON4D3** [comment]
What exactly is taking slow? Startup? Insert Mode? And what's going wrong?
As for configuration, you could check out `DOC.md` and `Examples/snippets.lua`, if you have more specific questions after that feel free to ask :D

**Comment by leiserfg** [comment]
If you are talking about the startup, use the lazy load version so not all the snippets are loaded in the startup.

**Comment by Trid-collab** [comment]
It have noticed in Insert Mode when the LSP Server is attached to the buffer and I start typing - the disk and CPU activity increases and also LSP suggestions take sometime to start to show up - only the luasnip suggestions show up initially. 

I have my setup configured with nvim-compe.

This doesn't seem to happen when I remove the "require("luasnip/loaders/from_vscode").load()"
or when I use others like hrsh7th/vim-vsnip.

and I have noticed no change when I use the lazy-load option as well


"

**Comment by L3MON4D3** [comment]
Tbh that sounds more like problems with lsp. Could you profile (eg. with plenary.nvim) to show which functions take the most time?

**Comment by Trid-collab** [comment]
Ok after using the luasnip with lsp server for lua, vim , typescript and python, I noticed that the issue of Neovim going slow with Luasnip is related when I am using a python file using the pyright server.

**Comment by L3MON4D3** [comment]
Okay, but that still very much sounds like an issue with eg. `pyright`. If you can get more specific data (which functions take the most time) there will be a chance of finding what's causing the high load.

**Comment by Trid-collab** [comment]
This is the error message which I am getting when I am opening a python file with pyright lsp configure.
when I am typing only the luasnip suggestions are poping up, LSP autocomplete are not - The pyright LSP is starting very late.
Neovim is practically hanging . No issues seen with checkhealth and lspinfo with pyright server

Observing this error

![image](https://user-images.githubusercontent.com/61322708/130599773-8a1a263e-52db-491c-ab9c-7c14334f603c.png)

**Comment by L3MON4D3** [comment]
Does that error occur before you expanded any snippet? If so, please open a new issue, that would be a problem, if not, that can happen if you expanded a snippet and deleted it without jumping to the end of it.

> The pyright LSP is starting very late

That doesn't seem to be an issue with luasnip, you could try to get help about that in their repo, or some forum

**Comment by leiserfg** [comment]
Are you enabling the snippet capability to pyright lsp? If so try disabling it, some lsp servers have issues if that's `on`.
