### ISSUE TITLE
Attempt to index a nil value. snip_expand

### ISSUE THREAD

**Issue by WinstonMDP** [L3MON4D3/LuaSnip#1090]
![screen-1702745791](https://github.com/L3MON4D3/LuaSnip/assets/61916541/4aee4a77-c48f-4a57-b995-6aea13583e59)

I don't know, how to reproduce it. It occurs periodically, when I use rust and kotlin LSP. Maybe, it was the same with other languages. When this happens, cmp stops working. My config: https://github.com/WinstonMDP/dotfiles/blob/main/.config/nvim/init.vim

**Comment by L3MON4D3** [comment]
I think this may be the same issue as #1084, could you update and check if it persists?

**Comment by WinstonMDP** [comment]
It seems like it works. Thanks
