### ISSUE TITLE
BUG: attempt to get length of local 'position_so_far' (a nil value)

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#1093]
It seems that we cannot have a restore node with jump index 0?

Repro:

```lua
local tmp = '/tmp'
local data = tmp .. '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local package_root = data .. '/site'
local clone_root = package_root .. '/pack/packages/start'
local clone_info = {
  {
    path = clone_root .. '/LuaSnip',
    url = 'https://github.com/L3MON4D3/LuaSnip.git',
  },
}

vim.fn.mkdir(clone_root, 'p')
vim.opt.pp:prepend(package_root)
vim.opt.rtp:prepend(package_root)

for _, info in ipairs(clone_info) do
  if not vim.loop.fs_stat(info.path) then
    vim.notify('cloning ' .. info.url, vim.log.levels.INFO)
    vim.fn.system({ 'git', 'clone', info.url, info.path })
  end
end

local luasnip = require('luasnip')

local s = luasnip.snippet
local r = luasnip.restore_node
local t = luasnip.text_node
local fmta = require('luasnip.extras.fmt').fmta

luasnip.setup({
  enable_autosnippets = true,
})

luasnip.add_snippets('markdown', {
  s(
    {
      trig = 'aln',
      snippetType = 'autosnippet',
    },
    fmta(
      [[
        \begin{<env>}
        \t<text>
        \end{<env>}
        ]],
      {
        env = t('align'),
        text = r(0, 'text'),
      }
    )
  ),
}, {})
```

Changing the jump index of restore nodes from 0 to 1 solves the issue, but I don't want the extra jump point. Thanks in advance!

**Comment by L3MON4D3** [comment]
Ah, that's by design :/
`i(0)` are special in that they are primarily the Exit-Point of the snippet.
A bit of that is self-imposed, it may be possible to work around this, but that would probably require some special cases, and I'm not keen on taking care of those.

**Comment by Bekaboo** [comment]
Thanks for your reply.

Is there any way that I can have the snippet expand to:

```lua
\begin{<env>}
    |
\end{<env>} | <--- I don't want this jump point
```

without the last jump point after `\env{<env>}`? Thanks!

**Comment by L3MON4D3** [comment]
No, sorry :/
You could put it immediately behind the `r(0)`, but that's probably not what you want..
Is this just an example? As it stands, you could replace the restoreNode with an `i(0)` without affecting functionality

**Comment by Bekaboo** [comment]
> No, sorry :/
;_;

> Is this just an example? As it stands, you could replace the restoreNode with an i(0) without affecting functionality

Yes, it is just a minimal example, the actual snippet is:

```lua
local fmtad = ls.extend_decorator.apply(fmta, {
  repeat_duplicates = true,
})

s(
  { trig = 'aln' },
  c(1, {
    fmtad(
      [[
      \begin{<env>}
      <idnt><text>
      \end{<env>}
      ]],
      {
        env = t('aligned'),
        idnt = un.idnt(1),
        text = r(0, 'text'),
      }
    ),
    fmtad(
      [[
      \begin{<env>}
      <idnt><text>
      \end{<env>}
      ]],
      {
        env = t('align*'),
        idnt = un.idnt(1),
        text = r(0, 'text'),
      }
    ),
    fmtad(
      [[
      \begin{<env>}
      <idnt><text>
      \end{<env>}
      ]],
      {
        env = t('align'),
        idnt = un.idnt(1),
        text = r(0, 'text'),
      }
    ),
  }),
  {
    stored = {
      text = i(0),
    },
  }
)

```

**Comment by L3MON4D3** [comment]
Ahh okay.. just so you're aware, the restrictions placedon the node with jump-index 0 are:
* is an insertNode
* is a direct child of the surrounding snippet

So something like `c(1, {i(0), t"asdf"})` would also be invalid/at least generate that auto-i0 at the end of the snippet.

> Will you accept a patch to fix this issue?

Puuh, yeah I'd say I would.. But I'm very hesitant to change this at all, since, from the very beginning, I've assumed that the 0-node is an insertNode, so we would have to take a pretty close look at all of the codebase to figure out everything that has to be changed to accomodate other nodes in this position.

**Comment by Bekaboo** [comment]
Closing now because it is the current design choice. Could be improved in the future though.
