### ISSUE TITLE
`insert_node(0)` doesn't select text target

### ISSUE THREAD

**Issue by mystilleef** [L3MON4D3/LuaSnip#110]
I'm one of those weird people who needs visual cues for the jump targets in snippets. Some editors highlight the jump targets with colors or annotations. It will be great if `luasnip` adopts something similar.   

In the meantime, I always use insert nodes with text labels. I notice `insert_node(0, "--END")` will jump to the last target, but will not select `"--END"`. I understand `insert_node(0)` is a special jump target, but is it possible to select text associated with it?

This video shows the issue.

https://user-images.githubusercontent.com/273399/129254829-6ed48881-669d-4550-81a3-1e8615da8b4b.mp4

**Comment by L3MON4D3** [comment]
> I'm one of those weird people who needs visual cues for the jump targets in snippets. Some editors highlight the jump targets with colors or annotations. It will be great if luasnip adopts something similar.

Oh boy, do I have some nice (unpushed) commits for you :D 
I'll have to do a bit of testing+doc-writing tomorrow, if all works out they'll be up soon.

As for highlighting the `i(0)`, one problem is that the `i(0)` would extend way too far:

https://user-images.githubusercontent.com/41961280/129266969-149f0a8c-d0bc-43c9-8f5e-a8836e94d589.mp4

I've managed to make the text in the `i(0)` SELECTed on first jump and keep the `i(0)` in it's 'expected' position, but I don't really like it. At first there would be text inside the `i(0)`, then, upon changing the SELECTed text, it wouldn't have text anymore.. seems kind of weird to me, but it's more practical than not having SELECTable text, so it's probably the best solution.

https://user-images.githubusercontent.com/41961280/129267693-535ae3d8-2303-4b8a-9194-47c7aa1da2b9.mp4

Another solution would be to put all text between `i(0)`-begin and next snippet into the `i(0)`, but I think that would feel bad if there's a lot of text(ie. like 10+ lines not semantically related to either snippet) between those.

**Comment by mystilleef** [comment]
> 
> Oh boy, do I have some nice (unpushed) commits for you :D
> I'll have to do a bit of testing+doc-writing tomorrow, if all works out they'll be up soon.
> 

I look forward to that. :-)

> Another solution would be to put all text between `i(0)`-begin and next snippet into the `i(0)`, but I think that would feel bad if there's a lot of text(ie. like 10+ lines not semantically related to either snippet) between those.

I need to play with this. The workaround I use is `i(num, "--")i(0)`, where `num` is the highest jump number. It seems to work for now.

**Comment by L3MON4D3** [comment]
> I look forward to that. :-)

It's on master now, if you'd like to give feedback/make suggestions, do so in #70, I think that's where it came up first.
As for the `i(0)`, I pushed to the `i_0-preselect`-branch, it contains the behaviour from `i0_solution.mp4`, please check it out and tell me what you think :D

**Comment by mystilleef** [comment]
> As for the `i(0)`, I pushed to the `i_0-preselect`-branch, it contains the behaviour from `i0_solution.mp4`, please check it out and tell me what you think :D

It works perfectly. I can now use `i(0)` as the last edit point with selected labels. I don't do any crazy or complicated nesting, so I haven't tested deeply nested use-cases. But for my simple use-case, it works. Great work. Are you going to merge this into master eventually?

**Comment by L3MON4D3** [comment]
:)
Yeah, I think I'll merge it asap, it's definitely better than the current behaviour.

**Comment by L3MON4D3** [comment]
Merged!
