### ISSUE TITLE
Select choices using complete menu

### ISSUE THREAD

**Issue by Jab2870** [L3MON4D3/LuaSnip#1101]
Apologies if I've missed something in the docs, but I don't think I have.

Is it possible to show a snippet's choices using the normal completion menu? Something like this:

![image](https://github.com/L3MON4D3/LuaSnip/assets/1909202/48c9b5f0-9b7a-4022-b13e-66f4f5d9dd2d)

I am using lua-cmp if that makes any difference.

Thanks in advance

Edit for clarity: i am referring to the options you get when adding a choice_node

**Comment by L3MON4D3** [comment]
There's [`cmp_luasnip_choice`](https://github.com/doxnit/cmp-luasnip-choice), but that is currently unmaintained I think.
Then there's my [fork](https://github.com/L3MON4D3/cmp-luasnip-choice/tree/master), which should work (see discussion [here](https://github.com/doxnit/cmp-luasnip-choice/pull/1))

I could also have sworn that there was a `vim.ui.select`-based one around, but I can't find it right now :/
(but should be straightforward to implement, if that's what you'd rather have :) )

**Comment by Jab2870** [comment]
That is exactly what I was after, thank you.

**Comment by RobberFox** [comment]
Does the plugin still work? I tried to copy the config in README (just that I use `lazy.nvim`), but it doesn't seem to work:

All in separate files. Here is cmp:
```lua
local cmp = require("cmp")
local luasnip = require("luasnip")

cmp.setup {
	snippet = {
		expand = function(args)
			luasnip.lsp_expand(args.body)
		end,
	},
        ...

	sources = {
		{
			name = "lazydev",
			group_index = 0, -- To skip loading LuaLS completions (as lazydev recommends)
		},
		{ name = "nvim_lsp" },
		{ name = "luasnip" },
		{ name = "luasnip_choice" },
		{ name = "path" },
	},
}

```
Luasnip config:
```lua
	{
		"L3MON4D3/LuaSnip",
		version = "v2.*",
		build = "make install_jsregexp",

		opts = {
			enable_autosnippets = true,
		},

		config = function()
                ... -- my config here
                end
	},

	{
		'L3MON4D3/cmp-luasnip-choice',

		config = function()
			require('cmp_luasnip_choice').setup({
				auto_open = true, -- Automatically open nvim-cmp on choice node (default: true)
			});
		end,
	}
```
