### ISSUE TITLE
[Question] Two questions regarding restore node and snippet env

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#1105]
Thanks for developing LuaSnip, it is an amazing plugin that makes coding in Neovim much more joyful. The restore node and dynamic node are powerful but as a user, I sometimes find it a little bit hard to "get it right", so my questions are

1. How to set the default text for restore nodes depending on parent snippet env? For example, consider the following snippet for the `#include` preproc in C:

```lua
s({
  trig = 'inc',
  desc = '#include preproc',
}, {
  t('#include '),
  c(1, {
    sn(nil, { t('<'), r(1, 'header'), t('>') }),
    sn(nil, { t('"'), r(1, 'header'), t('"') }),
  }),
}, {
  stored = {
    header = i(1, 'DEFAULT TEXT'),
  },
})
```

I wish the `'DEFAULT TEXT'` can be my previously selected text, i.e. `snip.env.LS_SELECT_RAW`, how can I achieve that? I've tried to set the header to be a dynamic node:

```lua
    stored = {
      header = d(1, function(_, snip)
        return sn(nil, i(1, snip.env.LS_SELECTED_TEXT))
      end)
    },
```

but only get the error `attempt to index field 'env' (a nil value)`, also tried using function node to no avail. Is it currently possible in Luasnip?

2. Dynamic node in choice node seems to lose their environment, idk if it is a bug or design choice. For example in the following snippet that chooses between a function declaration and a function definition:

```lua
s(
  { trig = 'fn' },
  c(1, {
    fmta(
      [[
        <type> <func>(<params>) {
        <body>
        }
      ]],
      {
        type = r(1, 'type'),
        func = r(2, 'func'),
        params = i(3),
        body = d(4, function(argnode_texts, snip)
          local selected = snip.env.LS_SELECT_RAW
          return sn(nil, i(1, selected))
        end),
      }
    ),
    fmta('<type> <func>(<params>);', {
      type = r(1, 'type'),
      func = r(2, 'func'),
      params = i(3),
    }),
  }),
  {
    stored = {
      type = i(1, 'type'),
      func = i(2, 'func'),
    },
  }
)
```

The `body` of the function is a dynamic node that defaults to previously selected texts if the snippet is expanded in visual mode, but again I am getting the env-is-nil error?

So I wonder how I can get these two snippets to work. Thanks in advance!

**Comment by L3MON4D3** [comment]
Hey, appreciate the kind words :)
I think both of those stem from the same issue: the dynamicNode receives the parent of the dynamicNode, which is not necessarily the snippet (and only the snippet has `env`).
`snip.snippet.env` may do it :)

**Comment by Bekaboo** [comment]
Thanks for your reply! Will try it out tomorrow.

**Comment by Bekaboo** [comment]
Problem solved, thanks!
