### ISSUE TITLE
A random post of appreciation

### ISSUE THREAD

**Issue by kuator** [L3MON4D3/LuaSnip#1109]
Luasnip is a very powerful and very customizable piece of software. I can't imagine myself ever being able to make this kind of level of plugin. Especially considering that you're doing it open-source style. That's why plugin developers like you very much deserve the praise. I have a question: do you have a github sponsor or some other way to support you fincancially?

**Comment by L3MON4D3** [comment]
Hey, I really appreciate the compliments :D
I don't have anything like that set up, I'll look into it in a spare minute ;)

**Comment by leiserfg** [comment]
Just share a paypal donation link or something like that and take it all for yourself man, my work here was to scratch my itch :smile:

**Comment by L3MON4D3** [comment]
Okay, alright, if you ever change your mind, I'll be glad to put your links there as well :)
In any case, if I get to Berlin, there's a few rounds on me waiting :D

**Comment by kuator** [comment]
@L3MON4D3 cheers
