### ISSUE TITLE
Prevent or disable folding when expanding snippets

### ISSUE THREAD

**Issue by mystilleef** [L3MON4D3/LuaSnip#111]
Is there a way to prevent folding when entering snippets? I notice my `InsertEnter` and `InsertLeave` `autocmds` to prevent folding when typing are not respected. Are there events I can watch before and after entering snippets?

**Comment by L3MON4D3** [comment]
No there aren't (yet), but `InsertEnter` should probably be triggered when entering snippets, I'll look into that.

**Comment by leiserfg** [comment]
I guess it's kinda hard to deal with that by using events as snippets could be nested, unless they are only emitted when `Luasnip_current_nodes[0]` changes from/to  `nil`

**Comment by L3MON4D3** [comment]
Yeah, also true also shouldn't one already be in insert/visualMode when jumping/expanding?

**Comment by mystilleef** [comment]
> Yep. Also, shouldn't one already be in insertMode when expanding?

Yeah, that's why I was wondering if `luasnip` temporarily leaves insert mode because I've setup vim to prevent folding in insert mode. Here's a video of the issue. Maybe I need to do checks for `visual` and `selection` modes too? I've tried remapping `<tab>` with `<tab>zv`, but no luck.

https://user-images.githubusercontent.com/273399/129417475-b8afaaaa-c4b7-4d1f-ba7b-95ad3c4bb791.mp4

**Comment by L3MON4D3** [comment]
Luasnip jumps using `feedkeys()`, could be that changing modes there doesn't trigger autocommand.
Could you post the autocommand/config for your fold behaviour so I can debug this?

**Comment by mystilleef** [comment]
I also need to mention that navigating to the jump targets get completely screwed up inside folds, especially if the jump targets have text labels, as you can see in the Video. Here's a minimal `snippets.lua`to test with, and my `autocmd` is appended.

### snippets.lua

```lua
vim.cmd([[setlocal foldmethod=indent]])

local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.snippets = {
  vim = {
    s("aug", {
      t("augroup "),
      i(1, "GroupName"),
      t({ "AuGroup", "\t" }),
      t({ "au!", "\tau " }),
      i(2, [[CursorHold * redrawstatus]]),
      i(0),
      t({ "", "augroup end" }),
    }),
  },
}
```

### autocmd

```vim
augroup FoldsBehaviorAuGroup
  au!
  au BufEnter,BufLeave * normal! zvzt
  au BufWritePre,BufWritePost,TextChanged * normal! zv
  au InsertEnter *
        \ normal! zvzt |
        \ let w:oldfdm = &l:foldmethod |
        \ setlocal foldmethod=manual |
        \ normal! zvzt
  au InsertLeave *
        \ if exists('w:oldfdm') |
        \   let &l:foldmethod = w:oldfdm |
        \   unlet w:oldfdm |
        \ endif |
        \ normal! zvzt
augroup end
```

**Comment by L3MON4D3** [comment]
Ouh, yeah I didn't even notice the entire text is selected :/
Looks like we'll have to open folds after jumping

**Comment by mystilleef** [comment]
> Ouh, yeah I didn't even notice the entire text is selected :/
> Looks like we'll have to open folds after jumping

Yeah, I don't think anyone would be surprised or upset by that. In fact, I think that is the expected behavior. I can't think of an instance where anyone would want folds closed when jumping to targets.

**Comment by L3MON4D3** [comment]
Check out master, it should be fixed (after moving, we now do `zv`, I think that should be enough and without side-effects, fingers crossed :D).

**Comment by mystilleef** [comment]
> Check out master, it should be fixed (after moving, we now do `zv`, I think that should be enough and without side-effects, fingers crossed :D).

So far, so good. I did a quick test, and it looks to be fixed. Closing the issue. Kudos.
