### ISSUE TITLE
Update breaks snippet with callback.

### ISSUE THREAD

**Issue by lacarthur** [L3MON4D3/LuaSnip#1112]
Hi,
I've recently updated my LuaSnip version to the most recent one (2.* in my packer config file), and a snippet that worked before stopped working. Here is the offending snippet :
```lua
snippet(
    {
        trig="mk",
        name="inline math",
        dscr="An inline math formula",
        wordTrig=true,
        regTrig=false,
    },
    {
        text_node("$"), insert_node(1), text_node("$")
    },
    {
        callbacks = {
            [-1] = {
                [events.leave] = function()
                    vim.api.nvim_create_autocmd("InsertCharPre", {
                        buffer = 0, -- the current buffer
                        once = true,
                        callback = function ()
                            if not table_contains(no_space_in_front, vim.v.char) then
                                vim.v.char = " " .. vim.v.char
                            end
                        end
                    })
                end
            }
        }
    }),
```
Now, it seems that the callback is executed twice : once normally, and once in the first insert node of the next snippet. Here is a gif of this happening. Notice that when I manually unlink the current callback, I can, and I don't think I should, and also, that stops the problem, for the next snippet at least.
![2024-01-17 13-49-03](https://github.com/L3MON4D3/LuaSnip/assets/108178953/f738f085-1239-46d5-91bb-22ee3473c414)
Reverting to version 1.* seems to fix this entirely, but I haven't seen anything that would obviously cause this in the breaking changes issue, so this might be a bug.

**Comment by L3MON4D3** [comment]
Ah yeah, can confirm.. I think this is due to the snippet-insertion-changes, which have to manually trigger the enter/leave-callbacks.

I'll look into it :)

**Comment by L3MON4D3** [comment]
Could you try #1113? If I understand the issue correctly, this fixes it

**Comment by lacarthur** [comment]
Yeah, it seems to solve the issue for me. Thank you very much!
