### ISSUE TITLE
how to edit default snippets, i.e. disable loremPara and loremSent

### ISSUE THREAD

**Issue by igorzhilin** [L3MON4D3/LuaSnip#1115]
Hi
On the initial install in Neovim, the snippets `loremPara` and `loremSent` pop up every time I press `l`. I see that they are in `:LuaSnipListAvailable`
I would like to disable them (and only them) but how?
Thanks.

**Comment by igorzhilin** [comment]
found out it was part of `.local/share/nvim/lazy/friendly-snippets/snippets/global.json`

**Comment by ivanjermakov** [comment]
To actually disable snippets from `global.json`, I use:
```lua
require('luasnip.loaders.from_vscode').lazy_load({ exclude = { "all" } })
```

**Comment by carried-away** [comment]
@ivanjermakov what file are you putting that require line in?

**Comment by ivanjermakov** [comment]
@carried-away wherever you call `lazy_load` on LuaSnip loader, in my case right before calling `luasnip.config.setup({})`.
It's the same in `kickstart.nvim`, replace this line: https://github.com/nvim-lua/kickstart.nvim/blob/7af594fd319fbae6b2aaa06337f3df8acbbb7f18/init.lua#L635
