### ISSUE TITLE
[Question]: How to import a helper function when using loader

### ISSUE THREAD

**Issue by rathod-sahaab** [L3MON4D3/LuaSnip#1116]
I can't seem to get function modules working, I tried importing every way this is the farthest I have come.

error I am facing now is something along the lines of

`attempt to index an upvalue 'stringz' (a boolean value)`

When I copy the function in types.lua and call local function it works. I am not familiar with lua so I am at a dead end, I appreciate any help 🙏🏼 

`types.lua`
```lua
local stringz = require("stringz")

return {
  s(
    { trig = "unionEnum", dscr = "const array enum" },
    fmt(
      [[
export const {} = [{}] as const;
export type I{} = typeof {}[number];
      ]],
      {
        i(1),
        i(2),
        f(function(args)
          return stringz.snake_to_pascal(args[1][1])
        end, { 1 }),
        rep(1),
      }
    )
  ),
}
```
`stringz.lua`
```lua
function pascal_to_camel(input)
  if input == nil then
    return input
  end
  local first_letter = input:sub(1, 1):lower()
  return first_letter .. input:sub(2)
end

function snake_to_camel(input)
  if input == nil then
    return input
  end
  return input:lower():gsub("_%w", function(match)
    return match:sub(2):upper()
  end)
end

function snake_to_pascal(input)
  if input == nil then
    return input
  end
  local first_letter = input:sub(1, 1):upper()
  return first_letter .. snake_to_camel(input:sub(2))
end
```

init.lua
```lua
require("luasnip.loaders.from_lua").lazy_load({ paths = { "~/.config/nvim/LuaSnip/" } })
```
`.config/nvim`/
```
.
├── init.lua
├── lua
│  ├── config/
│  ├── lib/
│  │  └── stringz.lua
│  ├── plugins/
│  └── stringz.lua
├── LuaSnip
│  └── typescript
│     ├── nestjs.lua
│     └── types.lua
```

**Comment by L3MON4D3** [comment]
Ah, you'll have to return something in `stringz.lua`, like `return {snake_to_pascal = snake_to_pascal}`, otherwise `require` just indicates whether the module was loaded or not.

The more idiomatic way of doing this, btw, would be something like this 
```lua
local M = {}
function M.snake_to_pascal()
...
end

-- ...other functions...

return M
```
is to put something like `local M = {}` at the top of the file, and then define all the functions as `function M.snake_to_pascal(...) ... end` and then finally `return M` at the very bottom.

**Comment by rathod-sahaab** [comment]
Thanks!! @L3MON4D3 that fixed the issue!

For anyone who stumble across this in future, changes were done in this commit [https://github.com/rathod-sahaab/nvim/commit/f8b3db5a296316ca4a6c10b15597a076d6671362](https://github.com/rathod-sahaab/nvim/commit/f8b3db5a296316ca4a6c10b15597a076d6671362)
