### ISSUE TITLE
Issue with unicode chars

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#112]
Since somewhere near  61f58e0dd9007a7c7ac73715e23406148d17046f
using multibyte chars is failing, here is a minimal snippet with the problem
```lua
    s({ trig = "tt" }, { 
      t { "╔" },
      f(function() return "0" end, {}),   -- Seems related to having `t` and then `f` with only t it works fine
      t { "1", "2" },
      i(0),
    }),
```

**Comment by L3MON4D3** [comment]
Wow, what?? I would've expected some weird highlighting, but that??? Lemme see what is going wrong there

**Comment by leiserfg** [comment]
Maybe was not that one, but was one near it, 
this one was fine 530e081eae05ba8f15aab44ae35534a93863a4ea in case you wanna bisect.

**Comment by leiserfg** [comment]
In case you wanna bisect 530e081eae05ba8f15aab44ae35534a93863a4ea was fine.

**Comment by L3MON4D3** [comment]
Okay, weird, you can reproduce it minimally by inserting `╔` into an empty file and then calling `:lua vim.api.nvim_buf_set_text(0,0,1,0,1,{"0"})`.
But I could've sworn that `set_text` uses column-indexing, not some weird byte-stuff.

**Comment by leiserfg** [comment]
Yes, the doc is misleading as they use `*_column` in the naming.

**Comment by L3MON4D3** [comment]
Yeah, specify utf-8- vs. byte-indexing.
I pushed a fix, should work again :sweat_smile:

**Comment by leiserfg** [comment]
I hope nvim team decides to introduce some utf-8/unicode  lua lib.

**Comment by L3MON4D3** [comment]
What other problems are there with beside indexing?

**Comment by leiserfg** [comment]
> What other problems are there besides indexing?
Not that I know but anyway, it's an editor, dealing with Unicode should be easier.

I have to check if my selection thingy works well in that regard too, as I only tested it with ascii chars.
