### ISSUE TITLE
Error when trying to add new snippets in my config, attempt to call field 'add_snippets' (a table value)

### ISSUE THREAD

**Issue by Qfl3x** [L3MON4D3/LuaSnip#1121]
Hello, sorry for opening an issue on this but I couldn't manage to fix it (I'm using Kickstart, on the newest commit).

I've added this line in my init.lua:
````lua
  require("luasnip.loaders.from_vscode").load({paths = "~/.config/nvim/lua/custom/luasnip.lua"})
````
then in the luasnip.lua file added a small test snippet:
````lua
local ls = require("luasnip")

ls.add_snippets("lua",  {
  ls.parser.parse_snippet("expand", "--EXPAAAAAAAND"),
})
````
I get the error: `attempt to call field 'add_snippets' (a table value)` every time I source luasnip.lua . Thanks for the help!

**Comment by Qfl3x** [comment]
It just fixed itself oddly

**Comment by 45Hnri** [comment]
Reopening Neovim fixed this for me.
