### ISSUE TITLE
Inconsistent error: BufWinEnter index field 'loaded_fts' nil value

### ISSUE THREAD

**Issue by RichardEpure** [L3MON4D3/LuaSnip#1124]
![image](https://github.com/L3MON4D3/LuaSnip/assets/43828146/49f5528a-6730-408d-b08f-eb15ca6c7afe)

Sometimes, when I start neovim, I get this error thrown at me. I'm struggling to figure out the cause especially since it doesn't always occur. When it does happen, it's always at startup and I usually just quit and restart neovim. It doesn't happen very frequently but it's still quite annoying. The error message relates to luasnip but I'm not sure if it might also be related to auto sessions as well? I've tried running my config with various plugins disabled but since I can't reproduce the error consistently, it's difficult for me to debug.

I run neovim in Windows 11 natively and also inside of WSL2. In occurs in both environments.

You can find my config files [here](https://github.com/RichardEpure/new_dotfiles/blob/main/nvim/lua/plugins/lsp.lua)

**Comment by slarse** [comment]
@RichardEpure I had the exact same error. For me it manifested either when I moved from `packer` to `lazy`, or when I upgraded `lsp-zero` from `v1.x` to `v3.x`. I did a few too many things at once so I can't be sure exactly where the problem originated.

Anyway, in messing around I think I managed to create some version conflict between plugins. What solved it for me was nuking my local data directory at `~/.local/share/nvim` and just letting Lazy bootstrap itself and reinstall everything. From your traceback I'm guessing that's the `nvim-data` directory on Windows. It may be worth a shot.

A difference for me was that it wasn't sporadic, it happened all the time, so it may be a different problem altogether. But the error message looks very similar to the one I had barring that yours looks a bit Windows-y (`AppData` etc).

**Comment by RichardEpure** [comment]
> @RichardEpure I had the exact same "loaded_fts is nil" error. For me it manifested either when I moved from `packer` to `lazy`, or when I upgraded `lsp-zero` from `v1.x` to `v3.x`. I did a few too many things at once so I can't be sure exactly where the problem originated.
> 
> Anyway, in messing around I think I managed to create some version conflict between plugins. What solved it for me was nuking my local data directory at `~/.local/share/nvim` and just letting Lazy bootstrap itself and reinstall everything. From your traceback I'm guessing that's the `nvim-data` directory on Windows. It may be worth a shot.
> 
> A difference for me was that it wasn't sporadic, it happened all the time, so it may be a different problem altogether. But the error message looks very similar to the one I had barring that yours looks a bit Windows-y (`AppData` etc).
> 
> My problem did not appear to be an issue with LuaSnip itself, but rather with Lazy and/or lsp-zero getting into a bad state. But I could be wrong.

I did the exact same thing (packer > lazy & lsp-zero update). But I was certain I removed anything related to packer. I'm not sure if I completely wiped my nvim-data. The checkhealth for lazy was fine so I thought all was good. Anyway, now I have deleted my nvim-data and installed all my plugins fresh. Will see if I encounter the error again. If I don't notice it within a week then it's probably gone and I'll close the issue.
