### ISSUE TITLE
Can't use _^ as snippet trigger

### ISSUE THREAD

**Issue by Roger-Roger-debug** [L3MON4D3/LuaSnip#1126]
I have a simple snippet for latex:

```
	s({
		trig = "__",
		name = "Subscript",
		wordTrig = false,
		snippetType = "autosnippet",
	}, {
		t({"_{"}),
		i(1),
		t({"}"})
	}, {
		condition = is_math
	}),
```

For some reason this snippet won't expand. If I change  `__` to `..` it works. From what I understand this should work (and I think it used to work in the past). 

Any help is appreciated

**Comment by L3MON4D3** [comment]
Hi, this is working just fine for me (without the condition, that is. Maybe it can't deal with __, but .. works fine?)

**Comment by Roger-Roger-debug** [comment]
Finally thought about debugging the treesitter tree. It seems writing `_` breaks the math expression (turns inline_formula into ERROR). So that would be breaking the autosnippet because the condition no longer matches.

**Comment by L3MON4D3** [comment]
Yeah, makes sense :+1:

I actually have a solution here:
You can remove the snippet-trigger from the buffer, then do the treesitter-check, and then restore the trigger (we actually have implemented something like this for treesitter-postfix, see [here](https://github.com/L3MON4D3/LuaSnip/blob/292454f9fd5f192bf089234c8565db33bb946b00/lua/luasnip/extras/treesitter_postfix.lua#L91-L105), [here](https://github.com/L3MON4D3/LuaSnip/blob/292454f9fd5f192bf089234c8565db33bb946b00/lua/luasnip/extras/treesitter_postfix.lua#L55-L81), and [here](https://github.com/L3MON4D3/LuaSnip/blob/292454f9fd5f192bf089234c8565db33bb946b00/lua/luasnip/extras/_treesitter.lua#L54-L116)).

If you're not that comfortable with lua, I can also try to get this to work on my end, might just take a bit :sweat_smile:

**Comment by Roger-Roger-debug** [comment]
It's nothing urgent. I can probably get it done myself over the next couple of months but I'd appreciate you helping out :)

**Comment by Roger-Roger-debug** [comment]
Should probably close the issue as well since this isn't really a luasnip issue.

**Comment by L3MON4D3** [comment]
Oh yeah, TY! :)
I'll definitely have time around march, so you can expect some help around that time :D

**Comment by leiserfg** [comment]
My two cents, instead of trying to fight tree-sitter just pick another trigger, live is two short :smile:

**Comment by Roger-Roger-debug** [comment]
I have no idea what changed but it suddenly works again.
