### ISSUE TITLE
Makefile invokes 'make' explicitly, causing build failure on non-GNU systems

### ISSUE THREAD

**Issue by owallb** [L3MON4D3/LuaSnip#1128]
When building on FreeBSD (and possibly other systems) which do not ship the GNU version of make, building by calling `make` will fail. It is common to instead install and use `gmake`, but it will still fail due to invoking `make` explicitly in the Makefile. 

To make the recipe more portable I suggest using `$(MAKE)` within the Makefile, which is expanded according to this:

> The value of this variable is the file name with which make was invoked.

(See [here](https://www.gnu.org/software/make/manual/make.html#MAKE-Variable) for more info)

**Comment by L3MON4D3** [comment]
I was not aware of this, thank you!
