### ISSUE TITLE
After starting a snippet, pressing p pastes instead of typing p - add p to 'safe' keybind list?

### ISSUE THREAD

**Issue by AniAggarwal** [L3MON4D3/LuaSnip#1129]
I often use the snippet `ifmain` in Python to start a snippet. From the edit mode, I typically want to type `print` but pressing p will paste my clipboard. However, pressing something like `c` will just type c rather than changing the line.
How can I add `p` to some sort of safe list to interpreter as a normal letter? 
Screenshots to reproduce:
Start snippet:
![image](https://github.com/L3MON4D3/LuaSnip/assets/52252926/540e1042-1106-4e69-b497-7cb114083a1b)

Accept snippet:
![image](https://github.com/L3MON4D3/LuaSnip/assets/52252926/3f6d98a0-0e00-4de2-b9c1-198adc578b0c)

Type p (in this case I had an image on my clipboard lol)
![image](https://github.com/L3MON4D3/LuaSnip/assets/52252926/e35c8f9b-2fea-41a3-9357-7520217b088f)

Type c (or most characters, the desired behavior):
![image](https://github.com/L3MON4D3/LuaSnip/assets/52252926/de7e54fd-df5b-408b-8e6b-8a9c0f05d479)

**Comment by bew** [comment]
There is no 'safe' list of keys, but you may have mapped `p` in select mode by mistake.

Can you give us what `:map p` gives you?

**Comment by AniAggarwal** [comment]
Outputs the following in normal mode:
`"_dP`
![image](https://github.com/L3MON4D3/LuaSnip/assets/52252926/9f717bc7-a110-4a72-926c-4ca3bf141d5b)

Interestingly (just thought to check), `:map P` is not mapped to anything and behaves as expected.
