### ISSUE TITLE
[Feature Request] Support CURRENT_YEAR, CURRENT_MONTH, etc.

### ISSUE THREAD

**Issue by ourigen** [L3MON4D3/LuaSnip#113]
Would it be possible to add the parsing of `${CURRENT_YEAR}`, `${CURRENT_MONTH}`, etc. from VSCode json templates? There are more examples of time variables [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables)

**Comment by L3MON4D3** [comment]
It wouldn't be hard, but they have to be populated on snippet expansion, so I'd like to either have very few vars by default or make it configurable to keep performance.

I think the way to go would be adding a setting where the function that populates the environment variables can be defined. We could keep the `TM*` and `SELECT*`-variables as a default to stay backwards-compabile but provide functions that extend those to eg. include date and so on.
That would even allow users to define new variables.
