### ISSUE TITLE
Snippet unfold which contain tab auto trigger completion pane

### ISSUE THREAD

**Issue by yifan0414** [L3MON4D3/LuaSnip#1132]
When i use this snippet, I type `n.cout` to unfold. Then the completion pane auto appear which i don't want.
```lua
ls.add_snippets("cpp", {
  s({
    trig = "([A-Za-z->]*[A-Za-z\\.]*[A-Za-z]+\\d*)\\.(print|cout)",
    -- regTrig = true,
    trigEngine = "ecma",
    snippetType = "autosnippet",
  }, {
    f(function(_, parent)
      return "cout << " .. parent.captures[1] .. " << endl;"
    end),
    t({ " {", "\t"}), -- \t is the reason，aka two space
    i(0),
    t({ "", "}" }),
  }),
}
```
![image](https://github.com/L3MON4D3/LuaSnip/assets/45898625/b3514182-a828-4b18-abc3-bad20b05832b)

**When I remove `\t` or replace it with one space, this issue does not occur.**

nvim-cmp config is not important, even i comment all, the bug is also appear
```
        ["<Tab>"] = cmp.mapping(function()
          if cmp.visible() then
            cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
          end
        end, { "i", "s" }),
```

**Comment by L3MON4D3** [comment]
Hi, I think this is due to the behaviour of nvim-cmps auto-completion(it doesn't pop up after words, maybe), if you disable it there will be no popup (but you'll have to trigger completion manually)

**Comment by yifan0414** [comment]
> Hi, I think this is due to the behaviour of nvim-cmps auto-completion(it doesn't pop up after words, maybe), if you disable it there will be no popup (but you'll have to trigger completion manually)

ok
