### ISSUE TITLE
Question: snippets from lsp will enter selection mode, then I need two char to trigger completion

### ISSUE THREAD

**Issue by xzbdmw** [L3MON4D3/LuaSnip#1133]
first char will terminate selection mode and display one char, second char will trigger cmp's compeletion, can I trigger completion as soon as a type one char? Thanks for help!

**Comment by L3MON4D3** [comment]
Hey, pretty sure you can find a solution to this in nvim-cmp's issues :)

**Comment by xzbdmw** [comment]
Hello I wander if you have the same experience，when snippets contain placeholders？
