### ISSUE TITLE
lag when input character "i" at snip position

### ISSUE THREAD

**Issue by zaiqiang-dong** [L3MON4D3/LuaSnip#1136]
when insert  character "i" at "true" position，will be a noticeable lag，but inserting other characters does not have this issue
![image](https://github.com/L3MON4D3/LuaSnip/assets/10396859/87d10d86-5125-40bc-aff3-d4e8c71840b6)

**Comment by L3MON4D3** [comment]
I think you have some mapping that starts on `i` for SELECT-mode, could you look at `:verbose map` and check if that's the case? You may want to set it for VISUAL only

**Comment by zaiqiang-dong** [comment]
> I think you have some mapping that starts on `i` for SELECT-mode, could you look at `:verbose map` and check if that's the case? You may want to set it for VISUAL only

yes,check verbose map, find "ic" map for a plug cmd. thanks !
