### ISSUE TITLE
bump jsregexp to 0.0.7

### ISSUE THREAD

**Issue by GaetanLepage** [L3MON4D3/LuaSnip#1139]
Nixpkgs contributor here.
I have the same request as expressed in #1065. We currently have the 0.0.7 version of `jsregex` packaged.
Could you please consider bumping the required version for this dependency ?

**Comment by L3MON4D3** [comment]
Hey, thanks for bringing it to my attention :)
AFAIK the nixpkg is generated from the luarock, so updating jsregexp in there should propagate correctly?

**Comment by L3MON4D3** [comment]
Hey, finally got to it :)

**Comment by GaetanLepage** [comment]
Thank you !
