### ISSUE TITLE
trigEngine ecma - Error while compiling regex with negative lookbehind

### ISSUE THREAD

**Issue by nakulsodhi** [L3MON4D3/LuaSnip#1142]
I am trying to make a tex snippet to add a backslash to the beginning of some keywords such as ```sin,cos,tan```. I want to make it so that there is no match when the backslash is already present at the beginning i.e. if I type \sin, it shouldn't expand. I decided to do this using negative lookbehind.

This is what I have:

```lua
    s({trig="(?<!\\)(arcsin|arccos|arctan|arccot|arccsc|arcsec|sin|cos|tan|cot|csc|sec)", 
    trigEngine = "ecma", wordTrig=false},
        fmta("\\<><>",
        {f(function(_, snip) return snip.captures[1] end),i(1)}),
        {condition = tex_utils.in_mathzone}),
```

But when I open a .tex file, I am hit with an error - trig_engines: Error while compiling regex: bad argument \# 1 to '?' (expecting ')'). I admit I am not exactly well versed in regex so I  might be doing something wrong here.

In issue #1014, there is a suggested regex for a similar situation that did not give compilation error but did not do what I expected it to (it doesn't ever get triggered).

> Hey! Ah, could it be that the regex is incorrect? My regex-fu is not all that advanced, but `\\(?<!\\)(sin|cos|tan)`, for example, works. I'll make it so the error is returned early on, thanks for the report!

**Comment by kmarius** [comment]
The solution is somewhat hidden in the linked issue:

> Ahhh, lua turns two backslashes into one, maybe that's the issue?

The correct expression is

    (?<!\\\\)(arcsin|arccos|arctan|arccot|arccsc|arcsec|sin|cos|tan|cot|csc|sec)

**Comment by nakulsodhi** [comment]
Thank you! That was it. Closing the issue.
