### ISSUE TITLE
Sometimes require('luasnip').jumpable(-1) returns false unexpectedly

### ISSUE THREAD

**Issue by hrsh7th** [L3MON4D3/LuaSnip#115]
I received the issue with `<S-Tab>` keymapping on the nvim-cmp.

I've investigated it then I found the cause that is `luasnip.jumpable(-1)` returns false.

I don't know it is a actual luasnip issue or not. It just a report for LuaSnip author.

Best regards.

**Comment by hrsh7th** [comment]
See https://github.com/hrsh7th/nvim-cmp/issues/21

**Comment by L3MON4D3** [comment]
Ty! Do you have something reproducible? For me it has always worked so far

**Comment by leiserfg** [comment]
I guess is a i(0) misplaced.

**Comment by L3MON4D3** [comment]
Oh yes, that may be it

**Comment by hrsh7th** [comment]
I was using the following snippet.
```
{
  "a": {
    "prefix": "for",
    "body": [
      "function $1($2)",
      "\t${0}",
      "end"
    ]
  }
}
```

**Comment by leiserfg** [comment]
In that case it Wil retur true from 1 and 2 but not from 0 cause in that point the snippet is dead.

**Comment by hrsh7th** [comment]
Oh. I've understand. Thank you.

**Comment by hrsh7th** [comment]
BTW, the vim-vsnip wouldn't deactivate the snippet when the cursor jumping to `$0` (I don't say the LuaSnip should do it.)

**Comment by hrsh7th** [comment]
@L3MON4D3 @leiserfg Thank you very much!
