### ISSUE TITLE
Expand Snipmate snippet after "partial word"

### ISSUE THREAD

**Issue by bn-peters** [L3MON4D3/LuaSnip#1150]
Hi,

I have snipmate snippets of the form
```
snippet Delta
	Δ
```
and would like to expand them inside a partial word, i.e. I want `HDelta<tab>` to expand to `HΔ`. Two questions about this:
1. Is it correct that setting `wordTrig` to `false` (and leaving `trigEngine` as `"plain"`)  allows this kind of expansion to happen? 
2. Is there a way to change the default setting of `wordTrig` for snippets imported from snipmate?

If not I'll probably convert my snippets to Lua (and understand the DSL...), but I'd rather not go through that process at the moment.
In either case, thanks for the amazing plugin!

**Comment by L3MON4D3** [comment]
Hey!
1 is completely correct, regarding 2, right now it's not possible to disable wordTrig for snipmat-snippets.

But, if you only need this for a few snippets, I can wholeheartedly recommend parsing the snippet from lua:

```lua
local parse = ls.parser.parse_snippet

return {
    parse({trig = "snip"}, "${1:A snipmate-snippet}"),
    parse({trig= "Delta", wordTrig=false}, "Δ")
}
```
You get all options and can fall back to lua for complicated snippets only :)

**Comment by bn-peters** [comment]
Aaah, that is a very good point; Thanks for your help!
