### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by ismayeelanver** [L3MON4D3/LuaSnip#1154]
E5108: Error executing lua /home/++++++/.config/nvim/lua/config/cmp_config.lua:15: attempt t
o index global 'args' (a nil value)
stack traceback:
        /home/+++++/.config/nvim/lua/config/cmp_config.lua:15: in function 'expand'
        ...+++++/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:488: in function <...++++
1/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:434>
        ...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function 'run'
        [string ":lua"]:1: in main chunk
configuration:
```
local cmp = require("cmp")

require("luasnip.loaders.from_vscode").lazy_load()
cmp.setup({
mapping = cmp.mapping.preset.insert({
['<C-b>'] = cmp.mapping.scroll_docs(-4),
['<C-f>'] = cmp.mapping.scroll_docs(4),
['<C-Space>'] = cmp.mapping.complete(),
['<C-e>'] = cmp.mapping.abort(),
['<CR>'] = cmp.mapping.confirm({ select = true }),
}),
snippets = {
expand = function()
require("luasnip").lsp_expand(args.body)
end,
},
sources = cmp.config.source({
{ name = 'nvim_lsp' },
{ name = 'freindlysnippets' },
{ name = 'buffer' },
{ name = 'luasnip' },
}),
})
```

**Comment by L3MON4D3** [comment]
Hey :)
Try
```lua
snippets = {
expand = function(args)
require("luasnip").lsp_expand(args.body)
end,
},
```
