### ISSUE TITLE
Nonempty node and SELECT mode in insert node text

### ISSUE THREAD

**Issue by gokberkgunes** [L3MON4D3/LuaSnip#1155]
When the user tries to modify the default text of insert node, some nonempty function that checks this node causes an unexpected behavior. Since explaining the issue with words is hard, I will be adding some demonstrations. The issue appears to be about while writing something in SELECT mode of neovim, nonempty function appears to lead snippets to misbehave.

In the below examples, I am trying to create a snippet that creates a Rust function. The caveat is that if the function returns something, snippet adds `->` before the keyword user writes. Basically, the two possible outcomes would look like as below.
```rust
fn function1(reference1: i32) {
    function1_body
}

fn function2(reference2: i32) -> i32 {
    function2_body
}

```

## First Example Issue
```lua
s(
	{
		trig = "fn",
		name = "function",
		wordTrig = false,
		hidden = true,
	},
	fmt([[
	fn {}({}){}{} {{
		{}
	}}]],
		{
			i(1),
			i(2),
			nonempty(3, " -> ", ""),
			i(3, "default"),
			i(4),
		}
	),
	{
		condition = conds.line_begin,
	}
),
```

![ex](https://github.com/L3MON4D3/LuaSnip/assets/96139011/0c5683cb-a42e-4b81-a034-09cd88967b5f)

## Second Example Issue
This example is very similar to the first one, the only difference is that if there is no default text. In this example, nonempty function works correctly until the user wants to revisit the part that nonempty function checks. At this point, SELECT mode is enabled to change already inputted node and user writes something else. This actions are followed by the same error as shown in the first example.

![ex2](https://github.com/L3MON4D3/LuaSnip/assets/96139011/12790107-1016-4d64-a33b-c530fcf0b9eb)

**Comment by L3MON4D3** [comment]
Hey, I can't reproduce this issue on my machine, I'm using luasnip `master`, neovim `NVIM v0.10.0-dev-1367+g35f475d0a5` and relevant (AFAICT :D ) settings `update_events = {"TextChangedI"}`.
What version of luasnip+neovim are you on, and what do you have set for `update_events`?
If you have the same versions as me, could you try producing the error without any other plugins? If you have some easy-to-get neovim-version, I can also try that one :)

**Comment by gokberkgunes** [comment]
I was on a commit from months ago: `65ff66db0e466369fa6fb7abb5e38627713182ff`. Indeed, after updating LuaSnip to latest commit I cannot replicate the bug anymore. 

Apologizes for not trying out the latest updates before reporting the bug. It was silly of me to not think about ensuring luasnip to be updated before creating a bug report. I had the same issue using dynamic nodes instead of using nonempty node, it appears to be gone as well.

Thank you for assistance!

**Comment by L3MON4D3** [comment]
Ahh, okay :D
Don't worry about not updating, stuff like that happens :)

**Comment by gokberkgunes** [comment]
After few more iterations, I was able to reproduce this issue when the `update_events` table had `InsertEnter` enabled. However, I am not able to recall why this event is enabled and if this event is in use.

If luasnip allows `update_events` to set `InsertEnter` current issue is valid, if not maybe giving user an error or a notice would be ideal.

Looking forward for comments before reopening the issue.
