### ISSUE TITLE
checkhealth jsregexp not found even if installed

### ISSUE THREAD

**Issue by gonedownfr** [L3MON4D3/LuaSnip#1156]
In checkhealth I see luasnip giving the "require jsregexp" warning, however I do have 
`{"L3MON4D3/LuaSnip", build = "make install_jsregexp"}` with no visible errors and nvim launches correctly.

Furthermore I also tried to clone the jsregexp repo, `make` the .so and move it to ~/.config/nvim/ with no success; also tried to install it with luarocks, still get the checkhealth warning.

**Comment by L3MON4D3** [comment]
Huh!
For a manual install, you'd have to move `jsregexp.so` to `~/.config/nvim/lua`, have you try that too?
Could you also do `make uninstall_jsregexp` (after updating luasnip :D) and `make install_jsregexp`.
If that doesn't work, also try `make -C deps/jsregexp clean` and `make -C deps/jsregexp005 clean`, and then `make install_jsregexp`

**Comment by leiserfg** [comment]
@L3MON4D3 Sometimes I think we should   cc jsregex -> wasm -> lua, it will probably be  a bit slower but 3/4 of the issues in the repo are about jsregex installation  :smile:

**Comment by L3MON4D3** [comment]
> I did have to write those commands all in the build =  in my .lua file where I have configured luasnip and then always restart, yes?

Oh, not sure that works... Could you try running all those commands in luasnips installation-directory? You can find it via `:lua =vim.api.nvim_get_runtime_file("lua/luasnip/init.lua", true)` (and there should be just one result :D)

> false vim/loader.lua:0: ~/.config/nvim/lua/jsregexp.so: undefined symbol: lua_newuserdatauv

Ahhh right, the new jsregexp.so does not work standalone.. could you remove all of those files in `~/.config/nvim/lua`?

> @L3MON4D3 Sometimes I think we should cc jsregex -> wasm -> lua, it will probably be a bit slower but 3/4 of the issues in the repo are about jsregex installation 😄

:sob:
Yeah you're probably right, but I think I'm a bit in a sunk cost fallacy, it's working correctly almost always, there are just some weird situations where it doesn't.
I think I'll start recommending using the jsregexp-luarock if it does not work via `make`

**Comment by L3MON4D3** [comment]
Thanks for the step-by-step :+1:

> don't know man, I installed via luarocks to try but nvim/luasnip weren't picking it up due lua version mismatch

Ah, yeah okay, not a silver bullet either :/
