### ISSUE TITLE
Previous character is always included in the selection when jumping to nodes

### ISSUE THREAD

**Issue by anthony-S93** [L3MON4D3/LuaSnip#1158]
For illustration purposes, let's say I have a basic snippet defined like this:
```lua
s("map_definition", {
        i(1), -- map name
        t(" := map["), 
        i(2), -- key type
        t("]"),
        i(3), -- value type
        t("{"), i(4), t("}")
    }),
```
The problem is that if the text inserted for `i(4)` begins with a newline, the previous character (`{` in this example) will always be selected everytime I jump to the `i(4)` node. 

https://github.com/L3MON4D3/LuaSnip/assets/69449791/99a86044-dbfa-4f42-b2d8-2acb7fe66d88

This is quite problematic because we only want the text in `i(4)` to get selected, not the preceeding character. With the current behavior, if I want to change the contents of `i(4)` (everything within `{` and `}`), I'll end up deleting the first `{` along with the previous contents of `i(4)`.  

On the other hand, if the text inserted for `i(4)` does not begin with a newline, everything works as expected.

https://github.com/L3MON4D3/LuaSnip/assets/69449791/8610ba24-740f-4897-a937-bf86bd959a9a

**Comment by L3MON4D3** [comment]
Ouh, yeah you're right, I'll look into this asap.

I wonder if this is due to a recent change, or if it's really just been such an edgecase..

**Comment by L3MON4D3** [comment]
Should work now, thank you for reporting this :)
