### ISSUE TITLE
VS Code loader doesn't work when specifying paths

### ISSUE THREAD

**Issue by thefuga** [L3MON4D3/LuaSnip#1160]
Hi, there!

I'm using LuaSnip with NVChad (mostly default configs) and I'm having issues with the VSCode loader when specifying custom paths.
So far I've tried both load  (`:lua require("luasnip.loaders.from_vscode").load({ paths = { "..." } })`) using both absolute and relative paths, and none of them work.
On the other hand, loading without specifying the path (`:lua require("luasnip.loaders.from_vscode").load()`) loads the snippets from `rafamadriz/friendly-snippets`.

My snippets directory, for now, has a single file `go.json`, with the content:

```json
{
   "table driven test":{
      "prefix":"tdt",
      "body":"func Test$1(t *testing.T) {\n\ttestCases := []struct {\n\t\tdesc\tstring\n\t\t$2\n\t}{\n\t\t{\n\t\t\tdesc: \"$3\",\n\t\t\t$4\n\t\t},\n\t}\n\tfor _, tC := range testCases {\n\t\tt.Run(tC.desc, func(t *testing.T) {\n\t\t\t$0\n\t\t})\n\t}\n}",
      "description":"Snippet for table driven test"
   },
   "test expected got":{
      "prefix":"texpgot",
      "body":"t.Errorf(\"expected '%v', got '%v'\", $1, $2)",
      "description":"Standard expected/got error"
   }
}
```

I've tested those snippets directly on the friendly-snippets go file and it works as expected.

I'm running the lastest LuaSnip version on NVim 0.9.5.

I've seen other issues here and on nvchads's repo, but they don't seem to have a conclusion. Is there a known issue going on that I might have missed, or maybe something else I could try?

Thank you!

**Comment by L3MON4D3** [comment]
Hi :)
So far this sounds all like it should at least show the snippets..
Could you post your logs? `:lua ls.log.open()` opens it, best clear it and then start one new session, maybe check if there's some error reported, and set the loglevel high enough before running `load()` (`:lua ls.log.set_loglevel("info")`)

**Comment by thefuga** [comment]
I'm getting an error when trying to access ls.log: `E5108: Error executing lua [string ":lua"]:1: attempt to index global 'ls' (a nil value)`

**Comment by L3MON4D3** [comment]
dammit, `s/ls/require("luasnip")/`, sorry about that

**Comment by L3MON4D3** [comment]
Ahhh alright, happy the log helped by itself :D

**Comment by y9c** [comment]
Can luasnip automatically load .json file based on file name instead of parsing from the package.json file?

**Comment by L3MON4D3** [comment]
We don't have that, but if you want to avoid the `package.json` and don't mind having all your snippets in one big file you can use the vscode-standalone-loader (search for "standalone" in DOC.md)
