### ISSUE TITLE
Snippets do not exit at exit node or i(0)

### ISSUE THREAD

**Issue by gokberkgunes** [L3MON4D3/LuaSnip#1161]
After commit https://github.com/L3MON4D3/LuaSnip/commit/d9cb6ab976bca0bbf0ce790bc3c56af5ae80f4b8, when the user reach an exit nodes, the snippet does not exit. Two screenrecordings are given below to demonstrate problems.

![first](https://github.com/L3MON4D3/LuaSnip/assets/96139011/44c81192-65ef-40bd-92de-7dc5da6ebd3d)
![second](https://github.com/L3MON4D3/LuaSnip/assets/96139011/10524440-d3bf-4b2e-85ac-653df9039d88)

**Comment by L3MON4D3** [comment]
Hi :)
Riiiight, I did not implement a substitute for this behaviour after switching from `history` to the more granular `keep_roots, link_roots, link_children`.

I believe the best fix for this would be to add a new option for toggling this behaviour, something like `exit_roots` (don't disable the snippet if it's a child-snippet), and have that default to `history` to restore the old behaviour.
