### ISSUE TITLE
Failed to copy a tab stop

### ISSUE THREAD

**Issue by uga-rosa** [L3MON4D3/LuaSnip#117]
If the tab stop starts with "tes", the copy has failed and the start position is off.
There may be others, but this is the only one I've checked.
I don't think it's a problem with the json parser, because it happened whether I defined it in lua or in json.

![render1629117721872](https://user-images.githubusercontent.com/82267684/129565992-5cb1f301-9496-4aff-84ab-4048705b2c78.gif)

**Comment by L3MON4D3** [comment]
Pretty sure that's some autoformatting, I cannot reproduce in eg. a `.lua`. Could you check if it works correctly with other filetypes?

**Comment by uga-rosa** [comment]
I couldn't reproduce it in `lua`, but I was able to reproduce it in `python` and `rust`.

**Comment by L3MON4D3** [comment]
Okay, that doesn't seem to be an issue with luasnip, do you maybe have `autoindent` or other formatting set?

**Comment by uga-rosa** [comment]
I haven't set it, but in neovim, autoindent should be true by default.
However, I don't think that is the cause. Sorry for the bad example. Take a look at this.

![render1629157590928](https://user-images.githubusercontent.com/82267684/129642717-331f9696-38ec-4309-ba1e-0a0e0a5bee26.gif)

**Comment by uga-rosa** [comment]
Once I go back, I can see that the range of the tab stops has changed.

![render1629170236730](https://user-images.githubusercontent.com/82267684/129658463-3ed389c8-492a-4b2f-9778-f88bedc18243.gif)

**Comment by L3MON4D3** [comment]
Oh okay, that is an issue with Luasnip. This happens in all filetypes, right?

**Comment by L3MON4D3** [comment]
I cannot reproduce your issue:
```lua
ls.parser.parse_snippet({trig = "lsp"}, '"${1:trigger}": {\n\t"prefix": ["$1"]\n\t"body": [\n\t\t"$2"\n\t]\n}'),
```

https://user-images.githubusercontent.com/41961280/129674780-7c1f524f-1e18-4fe1-8c50-ca588804cef4.mp4

**Comment by uga-rosa** [comment]
Minimum configuration confirmed. It seems that cmp is interfering.
I'll move this issue over there.
