### ISSUE TITLE
Ability to disabled `realpath` to handle symlinked snippets

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#1170]
I'm using home-manager to manage my dotfiles and most of my configs are just symlinks to files in nix store. Recently I updated luasnip (wasn't updating it half the year) and vscode snippets stopped loading. Issue is that luasnip resolves packages.json symlink and searches for snippets in the wrong directory. Or maybe I missed something...

# How to reproduce

Prepare test environment:

```bash
mkdir -p /tmp/repro_symlinked_snippets/snippets
cat > /tmp/repro_symlinked_snippets/abcde-package.json <<EOF
{
	"name": "example-snippets",
	"contributes": {
		"snippets": [
			{
				"language": [
					"all"
				],
				"path": "./all.json"
			}
		]
	}
}
EOF
cat > /tmp/repro_symlinked_snippets/abcde-all.json <<EOF
{
	"snip1": {
		"prefix": "all1",
		"body": [
			"expands? jumps? $1 $2 !"
		]
	}
}
EOF
ln -s /tmp/repro_symlinked_snippets/abcde-package.json /tmp/repro_symlinked_snippets/snippets/package.json
ln -s /tmp/repro_symlinked_snippets/abcde-all.json /tmp/repro_symlinked_snippets/snippets/all.json
```

* `minimal_init.lua`:
```lua
require("luasnip.loaders.from_vscode").lazy_load({paths = "/tmp/repro_symlinked_snippets/snippets"})
```

* luasnip should be installed. Run neovim: `nvim --clean --noplugin -u minimal_init.lua`

# Expected

Snippets should be loaded. Run command `:lua=require("luasnip.extras.snippet_list").open()`.

# Actual behavior

There is no snippets. `luasnip.log`:

```
WARN  | vscode-loader: Could not find file /tmp/repro_symlinked_snippets/./all.json advertised in /tmp/repro_symlinked_snippets/abcde-package.json, guessing /tmp/repro_symlinked_snippets/all.json as the absolute and normalized path.
```

Notice that luasnip tries to load files relative to expanded package.json, when it probably should do it relative to original user-provided path.

**Comment by L3MON4D3** [comment]
Hey, thanks for bringing this to my attention, and the code for reproducing, which worked splendidly :)
