### ISSUE TITLE
escape [ from fmt

### ISSUE THREAD

**Issue by juanolon** [L3MON4D3/LuaSnip#1173]
Hi,
i'm trying to make a snippet to make snippets:
```
    s({trig="sn", name="Snippet", desc="add a new snippet"},
      fmta(
        [[
        s({trig="<>", name="<>", desc="<>"<>},
        fmta(
            \[\[
            <>
            \]\],
            {
            <>
            }
        ),
        {}
        )
        ]],
        {
                    i(1, "trigger"),
                    i(2, "name"),
                    i(3, "desc"),
                    i(4, ", snippettype=\"autosnippet\""),
                    i(5, "body"),
                    i(6, "i()")
        }
      )
    )
```
it works, but it also inserts `\[\[` when expanding the snippet. if i don't escape the square bracket, it doesn't work. how can i escape the square brackets?

thanks

**Comment by stasjok** [comment]
See `:h lua-literal`. Try this:

```lua
  s(
    { trig = "sn", name = "Snippet", desc = "add a new snippet" },
    fmta(
      [=[
        s({trig="<>", name="<>", desc="<>"<>},
        fmta(
            [[
            <>
            ]],
            {
            <>
            }
        ),
        {}
        )
        ]=],
      {
        i(1, "trigger"),
        i(2, "name"),
        i(3, "desc"),
        i(4, ', snippettype="autosnippet"'),
        i(5, "body"),
        i(6, "i()"),
      }
    )
  )
```

**Comment by juanolon** [comment]
nice, that did the trick. sadly, i can't open `h lua-literal` (no help entry?). followup question, i have this string, and `[=[` also didn't work:
```
        [=[
          > <>
          <>
        ]=],
```
with error `...ite/pack/packer/start/LuaSnip/lua/luasnip/extras/fmt.lua:144: Found unescaped > outside 
placeholder; format[0:1]=">"`

**Comment by stasjok** [comment]
I don't know what you want. If you need to use `>`, then don't use `fmta`, use `fmt` and `{}` placeholders or any other placeholder with `opts.delimiters`. Doc [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#fmt).

**Comment by juanolon** [comment]
oh, that's right! thanks!
