### ISSUE TITLE
What is the next step after installing jsregexp using luarocks?

### ISSUE THREAD

**Issue by Jaehaks** [L3MON4D3/LuaSnip#1176]
I am windows 10 user. 

I failed to link jsregexp.so using gcc. gcc cannot recognize the libraries, -L options doesn't work

![image](https://github.com/L3MON4D3/LuaSnip/assets/26200835/68309ece-56d5-4c4c-888d-4b7c60dedf2d)

Anyway, For alternative method, I install jsregexp using luarocks 
![image](https://github.com/L3MON4D3/LuaSnip/assets/26200835/ac229878-1b4b-409b-9561-a06259544df5)

Although I installed jsregexp, `:checkhealth LuaSnip` cannot recognize jsregexp library
![image](https://github.com/L3MON4D3/LuaSnip/assets/26200835/87dd77c4-957a-45db-a7c8-3bf0a2ee46ce)

`:lua =require('luasnip.util.util).jsregexp` output is `nil` still as you said in #986 

Could you notice some guide after installing jsregexp using luarocks?

**Comment by L3MON4D3** [comment]
It's possible that jsregexp is installed for the wrong lua-version, could you check your `:version`, especially which lua-version it references? For me, for example it's `LuaJIT`.
I'm sure the lua-version can be adjusted somehow for luarocks :)

**Comment by Jaehaks** [comment]
@L3MON4D3 

Ok.. I tried to install lua 5.1 version and jsregexp, but it failed.
I'll check other way installing possible. Thanks

**Comment by Jecrevin** [comment]
Botherd me a few days, finally, I find a solution to this.


> It's possible that jsregexp is installed for the wrong lua-version, could you check your `:version`, especially which lua-version it references? For me, for example it's `LuaJIT`. I'm sure the lua-version can be adjusted somehow for luarocks :)

Exactly, neovim is using `LuaJIT`, so we need also a LuaJIT installed for luarocks that luasnip can recognise. For example, using `winget` to install `LuaJIT`, run:
```
winget install DEVCOM.LuaJIT
```
And then use luarocks to install jsregexp:
```
luarocks install jsregexp 0.0.5-1
```
finally, jsregexp will take effect on luasnip windows.🥳

**Comment by dev4s** [comment]
If you are still having problems with jsregexp - https://github.com/L3MON4D3/LuaSnip/issues/986#issuecomment-2425313904
