### ISSUE TITLE
How do I use snippets under `~/.config/nvim/snippets`?

### ISSUE THREAD

**Issue by pheonix9001** [L3MON4D3/LuaSnip#118]
for some reason `.lazy_load` and `.load` only include custom plugins and doesn't include `~/.config/nvim/snippets`.

The reason why I want to do this is because I develop in c/c++ and most snippet plugins provide snippets that look like this

``` c++
while(...)
{
    ...
}
```

instead of

``` c++
while(...) {
    ...
}
```

here are my configs

snippets/c.json:
``` json
{
	"sst": {
		"prefix": "sst",
		"description": "A standard starter template for a C program",
		"body": [
			"#include <stdio.h>",
			"",
			"int main (int argc, char *argv[]) {",
				"\t${1:printf(\"Hello world\");}",
				"\treturn 0;",
				"}"
		]
	}
}
```

``` lua
require'luasnip/loaders/from_vscode'.lazy_load({ paths = {"~/.config/nvim/snippets"} })
opts = { noremap = false, expr = true }
map_key('i', '<C-k>', 'luasnip#expandable() ?  "\\<Plug>luasnip-expand-or-jump" : "\\<C-k>"', opts)
map_key('s', '<C-k>', 'luasnip#expandable() ?  "\\<Plug>luasnip-expand-or-jump" : "\\<C-k>"', opts)

local ls = require"luasnip"
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node

ls.snippets = {
	['all'] = {
		s("trigger", t({"Wow! Text!", "And another line."}))
	}
}
```
replacing `.lazy_load` with `.load` changes nothing.

also: the "trigger" snippets works but "sst" doesnt.

**Comment by L3MON4D3** [comment]
I think you have to structure that folder just like eg. `friendly-snippets` does, ie. provide the [`package.json`](https://github.com/rafamadriz/friendly-snippets/blob/main/package.json)

**Comment by pheonix9001** [comment]
Big thanks!!!! it worked

```
{
  "name": "dotfiles",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": "c",
        "path": "./snippets/c.json"
      },
      {
        "language": "c",
        "path": "./snippets/ccpp.json"
      },
      {
        "language": "cpp",
        "path": "./snippets/ccpp.json"
      },
      {
        "language": "cpp",
        "path": "./snippets/cpp.json"
      }
    ]
  }
}
```

**Comment by L3MON4D3** [comment]
Nice! I'll put a note into the docs, the layout is not at all obvious :sweat_smile:

**Comment by shaeinst** [comment]
@pheonix9001 can i have your config and steps to setup? i couldn't make it to work.

**Comment by pheonix9001** [comment]
https://gitlab.com/pheonix9001/dotfiles

**Comment by shaeinst** [comment]
what a timing. i just figure it out about a hour before your replay. thank you  anyway.

for those who didn't make it work, here is my [config](https://github.com/shaeinst/roshnivim)
