### ISSUE TITLE
how to load .vscode snippets from current pwd

### ISSUE THREAD

**Issue by erlangparasu** [L3MON4D3/LuaSnip#1186]
project folder:
.vscode/*.code-snippets

**Comment by L3MON4D3** [comment]
See https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#standalone

Basically, call `require("luasnip.loaders.from_vscode").load_standalone({path = vim.fn.getcwd() .. "/.vscode/snippets.code-snippets", lazy=true})`.

We can't do globbing, so if you want to load all `.code-snippets` in `.vscode`, you'll have to write some code to get them, and do one call to load_standalone for each of them.

Pass `lazy=true` if you have some standard-name for new .code-snippets files and want to load them as soon as they're created.
