### ISSUE TITLE
Issues with parsing snippets containing nested placeholders

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#119]
I have a problem with the following snippet:
```json
"if": {
    "prefix": "if",
    "body": "if ${1:[[ ${2:condition} ]]}; then\n\t$3\nfi",
    "description": "If statement"
  }
```
The problem is I can't jump to `$3` placeholder. Instead it jumps at the end after `fi`.

Another example of a snippet, that isn't parsed correctly:
```json
"if2": {
    "prefix": "if2",
    "body": "if ${1:[[ ${2:word} -eq ${3:word2} ]]}; then\n\t$4\nfi",
    "description": "If statement"
  }
```
This snippet doesn't expand at all (probably an error in parsing). I suspect the problem is with incorrectly defined node's positions in the jumplist. If I change `$4` to `$5`, the snippet expands, but it still has the first problem (`$5` isn't jumpable).

**Comment by L3MON4D3** [comment]
Oh no :( 
> I suspect the problem is with incorrectly defined node's positions in the jumplist

Yeah, that's probably it, weird that it is spotted as late as now. I'll see what I can do

**Comment by L3MON4D3** [comment]
Should work with master, please check.
Thanks for opening the issue, no idea how I haven't noticed that before

**Comment by stasjok** [comment]
Yes, it's working now. Thank you very much.
