### ISSUE TITLE
how to remove the first snippet of html tags in jsx

### ISSUE THREAD

**Issue by ThreeStonesL** [L3MON4D3/LuaSnip#1191]
No matter which word I input, the first snippet is always the html tag. How to remove it?
![image](https://github.com/L3MON4D3/LuaSnip/assets/95917077/5c318cc1-5f45-4a32-af01-1e685f31a518)

**Comment by L3MON4D3** [comment]
We don't really properly support removing snippets after they're added, I'd suggest that you copy the repo that supplies it (friendly-snippets or vim-snippets, maybe?) into your config, and then remove it manually.

**Comment by ThreeStonesL** [comment]
> We don't really properly support removing snippets after they're added, I'd suggest that you copy the repo that supplies it (friendly-snippets or vim-snippets, maybe?) into your config, and then remove it manually.

ok, thank you for your help❤️
