### ISSUE TITLE
jsregexep: make: *** No rule to make target `install_jsregexp'.  Stop.

### ISSUE THREAD

**Issue by martenmatrix** [L3MON4D3/LuaSnip#1193]
Hey, I've seen that 3/4 of the issues here are about jsregexep and I believe I tried most of the suggested solutions, however, I'm unable to get it to work.

My config with Lazy, which does not output any errors: 
```lua
{ 'L3MON4D3/LuaSnip', build = 'make install_jsregexp', dependencies = { 'rafamadriz/friendly-snippets' } }, -- snippet engine
```

However, when running `:checkhealth luasnip`, it warns me about `jsregexep` not being installed.

I also tried navigating to `/Users/martenb/.local/share/nvim/lazy/LuaSnip/lua/luasnip/` and running `make install_jsregexp`, however I'm getting: `make: *** No rule to make target install_jsregexp'.  Stop.`

**Comment by L3MON4D3** [comment]
Hi :)
Could you try going to `/Users/martenb/.local/share/nvim/lazy/LuaSnip`, and running `make install_jsregexp` there?

**Comment by martenmatrix** [comment]
Oh. Thank you so much!
