### ISSUE TITLE
Snippets stop working when setting snippetType = "autosnippet"

### ISSUE THREAD

**Issue by Gruetterr** [L3MON4D3/LuaSnip#1196]
Standard snippets (`snippetType = "snippet"`) work correctly, but once I set `snippetType = "autosnippet"`, the snippet stops working completely. I have set `ls.config.set_config({ enable_autosnippets = true })` but it just doesn't work at all.

**Comment by Gruetterr** [comment]
I am on an MBP M2 with MacOS Sonoma 14.5, here is my luasnip.lua file:
```
return {
	"L3MON4D3/LuaSnip",
	-- follow latest release.
	version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
	-- install jsregexp (optional!).
	build = "make install_jsregexp",
	config = function()
		local ls = require("luasnip")
		local s = ls.snippet
		local t = ls.text_node

		ls.setup({
			enable_autosnippets = true,

			store_selection_keys = "<Tab>",
		})

		vim.cmd([[
      " Expand or jump in insert mode
      imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>'

      " Jump forward through tabstops in visual mode
      smap <silent><expr> <Tab> luasnip#jumpable(1) ? '<Plug>luasnip-jump-next' : '<Tab>'
      " Jump backward through snippet tabstops with Shift-Tab (for example)
      imap <silent><expr> <S-Tab> luasnip#jumpable(-1) ? '<Plug>luasnip-jump-prev' : '<S-Tab>'
      smap <silent><expr> <S-Tab> luasnip#jumpable(-1) ? '<Plug>luasnip-jump-prev' : '<S-Tab>'

    ]])

		ls.add_snippets("all", {
			s({
				trig = "hi",
				regTrig = false,
				snippetType = "autosnippet",
			}, {
				t("Hello world!"),
			}),
		})
		-- require("luasnip.loaders.from_lua").load({ paths = { "~/.config/nvim/snippets/" } })
	end,
}
```

**Comment by Sorodon** [comment]
I have the same issue, but found a very interesting thing:
If I reload the luasnip config (mine looks pretty similar to yours, only the snippets are sourced from elsewhere), by saving it (even if I haven't changed anything) thus making lazy reload, autosnippets start working until nvim is closed. Every new nvim session requires me to reload the luasnip config again.  
If it's the same for you it might have something to do with how luasnip loads plugins (can't really be lazy since non-autosnippets work, right?)

**Comment by Gruetterr** [comment]
Oh wow, sounds interesting. I'm definitely gonna try that. After saving my new config, I always restarted Neovim, that's probably why I didn't notice anything.

**Comment by Sorodon** [comment]
Another observation: 
If actually doesn't matter which plugin is saved to force the reload.
Any plugin (even one in no way related to luasnip) inside my nvim/lua directory is enough to make auto snippets work.

**Comment by Gruetterr** [comment]
Hm, didn't work for me. Guess I'll just use Vim with Ultisnips...

**Comment by L3MON4D3** [comment]
Hey :)
Sounds a bit like the config is not being sourced correctly, maybe there's an issue with lazy?
You can check the value of `enable_autosnippets` at runtime via `:lua =require("luasnip").session.config.enable_autosnippets`, if it's true and autosnippets still won't expand, there's some issue on luasnips side..

**Comment by L3MON4D3** [comment]
Yeah :/
https://github.com/L3MON4D3/LuaSnip/issues/1203#issuecomment-2198048002 also mentions lazy changing config, maybe check their issues or open one

**Comment by Gruetterr** [comment]
Huh, just reinstalled and reconfigured neovim, and now everything works as intended, I dont even have to reload anything as mentioned above. Thanks for the help guys!

**Comment by rayruitang** [comment]
> Huh, just reinstalled and reconfigured neovim, and now everything works as intended, I dont even have to reload anything as mentioned above. Thanks for the help guys!

May I know how you made it work? I've been having problems with loading autosnippets while snippets are loaded successfully.

**Comment by Sorodon** [comment]
> > Huh, just reinstalled and reconfigured neovim, and now everything works as intended, I dont even have to reload anything as mentioned above. Thanks for the help guys!
> 
> May I know how you made it work? I've been having problems with loading autosnippets while snippets are loaded successfully.

I started a [discussion at lazy](https://github.com/folke/lazy.nvim/discussions/1721) and was sent to [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim).

Unfortunately I didn't have time to look into that until now. I will try to get to it soon and post there if I find something.
