### ISSUE TITLE
Standalone snippets scope trimming issue

### ISSUE THREAD

**Issue by OneComputerGuy** [L3MON4D3/LuaSnip#1199]
It seems the loader for `vscode` doesn't have a way to trim whitespace (leading or trailing) which interferes with the filetype property when in use.

Example:

personal.code-snippets:

```
{
  "Print to console": {
    "scope": "javascript,typescript, javascriptreact, typescriptreact",
    "prefix": "clog",
    "body": ["console.log($1);"],
    "description": "Log output to console"
  }
}
```
Result: The snippet is loaded but only works on JS/TS files and not in JSX/TSX files

```
{
  "Print to console": {
    "scope": "javascript,typescript,javascriptreact,typescriptreact",
    "prefix": "clog",
    "body": ["console.log($1);"],
    "description": "Log output to console"
  }
}
```
Result: The snippet is loaded and works on JS/TS and JSX/TSX files.

This caught me off guard since on VSCode the scope works regardless of whitespace between the list. Also verified the documentation for the standalone section and it doesn't mention this being a requirement.

**Comment by L3MON4D3** [comment]
Hey, thanks for the report and looking into the correct behaviour :)
Trimming whitespace before and after a colon sounds reasonable, I'll look into it
