### ISSUE TITLE
Some snippets that make the parser fail

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#12]
When testing the pr for the loader I found some snippets that fail. For the record:
```lua
ls.parser.parse_snippet({trig="for_i", wordTrig=true}, "for ((${0:i} = 0; ${0:i} < ${1:10}; ${0:i}++)); do\n\techo \"$${0:i}\"\ndone\n"),                                
ls.parser.parse_snippet({trig="for_in", wordTrig=true}, "for ${0:VAR} in $${1:LIST}\ndo\n\techo \"$${0:VAR}\"\ndone\n"),                                                 
ls.parser.parse_snippet({trig="case", wordTrig=true}, "case \"$${0:VAR}\" in\n\t${1:1}) echo 1\n\t;;\n\t${2:2|3}) echo 2 or 3\n\t;;\n\t*) echo default\n\t;;\nesac\n"),  
ls.parser.parse_snippet({trig="texlr", wordTrig=true}, "\\left\\{ ${1:${TM_SELECTED_TEXT}} \\right\\\\}"),                                                              


```

**Comment by L3MON4D3** [comment]
I think the main issue is that some syntax is slightly off, eg. `$$` should be `\\$$`, `${2:2|3}` `${2|2,3|}` and the fourth should look something like this: `"\\\\left\\\\\\{ ${1:${TM_SELECTED_TEXT}} \\\\right\\\\\\}"`(:vomiting_face:).
For the first and second, I'm not entirely sure what is expected to happen with the multiple `$0`, normally a Snippet should only have one of those I think.

**Comment by L3MON4D3** [comment]
Oh, and `SELECTED_TEXT` sadly isn't supported yet, but that shouldn't make the parser fail.

**Comment by leiserfg** [comment]
I just made it for you to know it, is fine for me if you remove it as I don't use those snippets anyway.

**Comment by L3MON4D3** [comment]
Ah okay, then I'll just close this as the parsers behaviour on invalid Snippets is unspecified, thank you nonetheless.
