### ISSUE TITLE
Error while changing choice 

### ISSUE THREAD

**Issue by ryleelyman** [L3MON4D3/LuaSnip#120]
I'm testing the following snippet used in the docs:

```
     s("trig", c(1, {
     	t("Ugh boring, a text node"),
     	i(nil, "At least I can edit something now..."),
     	f(function(args) return "Still only counts as text!!" end, {})
     }))
```

The snippet correctly expands to "Ugh boring, a text node" and then changes to "At least I can edit something now..." when I call `<Plug>luasnip-next-choice`, which is `<C-E>` for me, but I get the following error when I call `<Plug>luasnip-next-choice` again:

`E5108: Error executing lua .../packer/start/LuaSnip/lua/luasnip/nodes/functionNode.lua.30: attempt to call field 'normal_move_on_mark_insert' (a nil value)`

When I press Enter, the text correctly changes to "Still only counts as text!!", but the text is selected as if this were an `i` node (I don't know whether this is intended). When I call `<Plug>luasnip-expand-or-jump` from there, I get another error:

`E5108: Error executing lua ...site/pack/packer/start/LuaSnip/lua/luasnip/util/util.lua:92: attempt to perform arithmetic on a nil value`

**Comment by L3MON4D3** [comment]
Whoops, I recently refactored and forgot to change a call :grimacing: 
It should be fixed on master.

**Comment by ryleelyman** [comment]
It's fixed now!
