### ISSUE TITLE
Adding the same condition to multiple snippets at once

### ISSUE THREAD

**Issue by MomoInSpace** [L3MON4D3/LuaSnip#1202]
For better readability, I wanted to create a list of snippets, and then give all those snippets the same condition. In My case:

```
local greek_letters = {
    -- alpha------------
    s(";a", {
        t({ '\\alpha' }),
    }),
    --Alpha------------
    s(";A", {
        t('\\Alpha'),
    })

for _, snip in ipairs(greek_letters) do
    snip.condition = in_mathzone
    snip.show_condition = in_mathzone 
    snip.wordTrig = false
    table.insert(auto_luasnippets, snip)
end
```
Sadly, this stopped working after I updated to the newest version and I can't find a solution. How do I add conditions to multiple snippets at once? I really can't find any documentation for this, and I think that would also be really helpful.

**Comment by L3MON4D3** [comment]
Ah, right, we stopped supporting that, sorry it cause an issue for you :/
I'd recommend using `ls.extend_decorator`:
```lua
local greek = require("luasnip").extend_decorator.apply(s, {condition = in_mathzone, show_condition = in_mathzone, wordTrig=false})
table.insert(auto_luasnippets, greek(";a", {...}) )
table.insert(auto_luasnippets, greek(";A", {...}) )
```

**Comment by MomoInSpace** [comment]
Thank you, someone should tell the LLMs though..., lol
