### ISSUE TITLE
Keymap fails in Neovim 0.10.0

### ISSUE THREAD

**Issue by Entoryvekum** [L3MON4D3/LuaSnip#1203]
Upon updating neovim to 0.10.0 from 0.9.3, I discovered that the `<Tab>` fails to expand the snippet. Here's my configuration:
```lua
vim.keymap.set(
    { "i", "n" ,"s"},
    "<Tab>",
    function()
        if require("luasnip").expandable() then
            return '<Plug>luasnip-expand-snippet'
        else
            return "<Tab>"
        end
    end, {
        expr = true,
        silent = true,
    }
)
```
Further test shows that the same configuration works for 0.9.5.
In 0.10.0 with the config below, remapping `<Tab>` only works normal mode, while in insert mode, it just insert some spaces.
```lua
vim.keymap.set(
    { "i", "n" },
    "<Tab>",
    "i?<esc>:h<cr>"
)
```
[2024-06-29 11-14-21.webm](https://github.com/L3MON4D3/LuaSnip/assets/20198566/4515b616-f5b6-476d-b741-4821e6ef22f1)
However, I can't figure out what break this keymap by just looking through the changelog.

**Comment by L3MON4D3** [comment]
Hey :)
I've tried your mapping on my machine, and it works :/
On 0.10 and master

https://github.com/L3MON4D3/LuaSnip/assets/41961280/d937b370-70d7-4f84-a37c-4d301de96df1

Maybe some other mapping of yours interferes?
Have you checked `:verbose imap <Tab>`?

**Comment by Entoryvekum** [comment]
Thanks for your help. I realized that the problem is caused by lazyvim. It overrides my settings in 0.10.0 and somehow don't affect lower versions.
