### ISSUE TITLE
[BUG] expand_or_jump and jump not work as expected after commit 0a4e557

### ISSUE THREAD

**Issue by xudyang1** [L3MON4D3/LuaSnip#1216]
Tested with commit 0a4e557 and 820d623. 820d623 works well as `<C-k>` selects first snippet when completion popup is available or it jumps to next jumpable field and `<C-j>` jumps to previous field.

0a4e557 breaks the jumps:

- `<C-j>` or `<C-k>` does not jump after exiting insert/select mode and then reenter insert mode.

- `<C-j>` does not jump if current cursor position is in the last jumpable field

Here is my luasnip setup:

```lua
return {
  "L3MON4D3/LuaSnip",
  dependencies = {
    { "rafamadriz/friendly-snippets" },
  },
  config = function()
    -- load friendly-snippets
    require("luasnip.loaders.from_vscode").lazy_load()

    local luasnip = require("luasnip")

    luasnip.config.setup({
      -- deprecated, if not nil, keep_roots, link_roots, link_children will be set to the value of history
      -- history = true,
      keep_roots = true,
      link_roots = true,
      link_children = true,
      -- default
      update_events = "InsertLeave",
      -- update_events = {"TextChanged", "TextChangedI"},
      -- region_check_events = "InsertEnter" -- disabled by default
      -- delete_check_events = "InsertLeave" -- disabled by default
      enable_autosnippets = true,
    })

    local map = vim.keymap.set

    map({ "i", "s" }, "<C-j>", function()
      if luasnip.jumpable(-1) then
        luasnip.jump(-1)
      end
    end, { silent = true })

    map({ "i", "s" }, "<C-k>", function()
      if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      end
    end, { silent = true })

    map({ "i", "s" }, "<C-l>", function()
      if luasnip.choice_active() then
        luasnip.change_choice(1)
      end
    end, { silent = true })
  end,
}
```

**Comment by L3MON4D3** [comment]
Hi :)
Regarding your second issue, the linked commit makes it so that upon reaching the last field of a snippet, you're exiting it (by default). You can disable this via `exit_roots = false` (IIRC).
I don't think I can reproduce your second issue, could you disable all formatters and stuff like that and check again? And if it still happens give me a step-by-step?

**Comment by xudyang1** [comment]
> Hi :) Regarding your second issue, the linked commit makes it so that upon reaching the last field of a snippet, you're exiting it (by default). You can disable this via `exit_roots = false` (IIRC). I don't think I can reproduce your second issue, could you disable all formatters and stuff like that and check again? And if it still happens give me a step-by-step?

That really helps! After setting `require('luasnip').config.setup({exit_roots = false})`, `<C-j>` and `<C-k>` now work as expected.

I have another question, and not sure if I should open a new issue/feature request for it:

`luasnip.expand_or_jump` now works only when user types the full prefix trigger. 
For example, if I want to use `<C-k>` (`luasnip.expand_or_jump`) to expand the first snippet (forline): 
1. typing `fl` then `<C-k>` does nothing.
![image](https://github.com/user-attachments/assets/4bf30b3b-8ebc-4a62-a175-3d526b6a4546)
2. typing `forline` then `<C-k>` works.

Here, I want to use `<C-k>` to directly expand the first available snippet without typing the full prefix or selecting it through multiple `<C-n>`. 

Should I open a new feature request for it, or the behavior is intentional?

**Comment by L3MON4D3** [comment]
That's intentional, I don't think it's a good idea for us to do some kind of fuzzy matching when `expand` is called (especially since the triggers can be regexes and stuff like that)
IMO that's exactly what the cmp-source is for, you'd only have to make it so the first item in the cmp-list is always selected so a simple `<C-y>` expands the snippet. But I can't help much figuring that out, maybe take a look at cmps' github if you need help there :)

**Comment by xudyang1** [comment]
> That's intentional, I don't think it's a good idea for us to do some kind of fuzzy matching when `expand` is called (especially since the triggers can be regexes and stuff like that) IMO that's exactly what the cmp-source is for, you'd only have to make it so the first item in the cmp-list is always selected so a simple `<C-y>` expands the snippet. But I can't help much figuring that out, maybe take a look at cmps' github if you need help there :)

Thanks, that makes sense.
