### ISSUE TITLE
Understand callbacks

### ISSUE THREAD

**Issue by banana59** [L3MON4D3/LuaSnip#1219]
Hello, I am currently working on a callback function which should be executed after a snippet is expanded.

This is my function
```lua
local function check_import_work_in_progress(args, _, user_args)
    if type(user_args) ~= "string" then
        error("Invalid check_import input")
    end

    local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
    local import_exists = false

    for _, line in ipairs(lines) do
        if line:match(user_args) then
            import_exists = true
            break  -- if found don't import anything
        end
    end

    if not import_exists then
        -- Prepend the import statement to the lines
        table.insert(lines, 1, user_args)
        vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
    end

    -- Move the cursor to the end of the buffer
    local total_lines = #lines
    local last_line_length = #lines[total_lines] or 0
    vim.api.nvim_win_set_cursor(0, {total_lines, last_line_length})
end
```

This in my snippet in _python.lua_
```lua
s({trig="plot_2d", snippetType="snippet"},
    fmta(
        [[
            fig, ax = plt.subplots(figsize=[12, 10])
            ax.plt(<>, <>)
            ax.grid()
            ax.set_xlabel("<>")
            ax.set_ylabel("<>")

            plt.show()
            <>
        ]],
        {
            i(1), i(2),
            i(3, "x-Axis"),
            i(4, "y-Axis"),
            i(0)
        }
    ),
    {
        callbacks = {
            [-1] = {
                [events.post_expand] = check_import("import matplotlib.pyplot as plt")
            }
        }
    }
),
```

But the function input doesn't seem to be accepted. Can anyone help me with that?

**Comment by L3MON4D3** [comment]
Oh MB, there actually isn't a post_expand-event, should've spotted that earlier :sweat_smile:
IIUC you could do this in `pre_expand`, that way you don't even have to worry about setting the cursor correctly again, since it will be set by luasnip :)

**Comment by L3MON4D3** [comment]
Ah, okay, I think I know what's going on (and it's a bit involved, sorry)
* the position the snippet should be expanded at (which is where the trigger was, essentially) is tracked via an extmark
* if, during pre_expand, text is inserted, it usually shifts this extmark around so the textual position remains the same. If text is inserted right on top of the extmark, it is kept on the left of the text.

So, I think what's happening here is that the code inserts the import-statement right on top of the extmark, which makes it shift to the left of, aka before, the snippet. So, this only occurs if the snippet is expanded at the first column of the first line (aka if the trigger starts exactly there).
I think it'd be nice to be able to handle even this case gracefully, so I'll make it so the `pre_expand`-callback receives the id of that extmark, so one may place it correctly after inserting the line (90333731):
```lua
ls.setup_snip_env()

-- Function to check if import statement exists and add if not
local function check_import_work_in_progress(node, args)
	local user_args_pattern = "^import matplotlib.pyplot as plt"
	local user_args = "import matplotlib.pyplot as plt"
	if type(user_args) ~= "string" then
		error("Invalid check_import input")
	end

	local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
	local import_exists = false

	for _, line in ipairs(lines) do
		if line:match(user_args_pattern) then
			import_exists = true
			break  -- if found don't import anything
		end
	end

	if not import_exists then
		-- make linebreak with `, ""`
		vim.api.nvim_buf_set_text(0, 0,0, 0,0, {user_args, ""})
		-- check for failure-case
		if vim.deep_equal(args.expand_pos, {0,0}) then
			-- move expand-pos-extmark.
			vim.api.nvim_buf_set_extmark(0, require("luasnip.session").ns_id, 1,0, {id = args.expand_pos_mark_id})
		end
	end
end

ls.add_snippets("all", {
	  s({trig="plot_2d", snippetType="snippet"},
        fmta(
            [[
                fig, ax = plt.subplots(figsize=[12, 10])
                ax.plot(<>, <>)
                ax.grid()
                ax.set_xlabel("<>")
                ax.set_ylabel("<>")

                plt.show()
                <>
            ]],
            {
                i(1), i(2),
                i(3, "x-Axis"),
                i(4, "y-Axis"),
                i(0)
            }
        ),
        {
            callbacks = {
                [-1] = {  -- -1 refers to the snippet as a whole
                    [events.pre_expand] = check_import_work_in_progress
                }
            }
        }
    ),
}, {key ="a"})
```
What you mentioned with the post_expand-callback sounds conceptually simpler, until one knows that the snippet also consists of extmarks, all of which may also have to be adjusted to support this (make sure that they will shift into the correct direction), so sticking this into pre_expand makes it a bit easier :)

**Comment by L3MON4D3** [comment]
Hmm, for me everything seems to be working, have you updated to the latest version of luasnip? I added the referenced commit just yesterday :)
If you're up-to-date, could you give some more details?


https://github.com/user-attachments/assets/5b13cd54-36d9-43de-9277-88f1cf557b1e

**Comment by L3MON4D3** [comment]
Ha, nice :)
That's almost correct, just make sure to pass the second parameter, `args` through to check_import, so `check_import(node, args, user_args)` (or omit the node altogether, I don't think it's necessary)

**Comment by L3MON4D3** [comment]
I think I'd
* pull the `if vim.deep_equal` out of the `user_args`-loop
* count the number of inserted lines at the beginning (how often did I nvim_buf_set_text)
* use that count to find the line where the snippet should now expand at
