### ISSUE TITLE
VSCode snippets custom path not working

### ISSUE THREAD

**Issue by flosker** [L3MON4D3/LuaSnip#123]
```
require('luasnip/loaders/from_vscode').lazy_load({paths = './snippets'})
```

`./snippets` tree

```
./snippets
    html.json
    lua.json
```

Plugin loads snippets correctly from `friendly-snippets` in runtimepath, but if the same files are copied to a custom folder like above, plugin doesn't load them.

**Comment by flosker** [comment]
Also is there way to hide language name like `javascript` in nvim-compe's menu (kind label)? It takes too much space.

**Comment by L3MON4D3** [comment]
> ```
> require('luasnip/loaders/from_vscode').lazy_load({paths = './snippets'})
> ```
> 
> `./snippets` tree
> 
> ```
> ./snippets
>     html.json
>     lua.json
> ```
> 
> Plugin loads snippets correctly from `friendly-snippets` in runtimepath, but if the same files are copied to a custom folder like above, plugin doesn't load them.

[See here](https://github.com/L3MON4D3/LuaSnip/blob/a4c119c8508bf1351bd5150b601eb77826776a2b/doc/luasnip.txt#L380)

**Comment by L3MON4D3** [comment]
(miss click :|)
About the second part, best to take that issue to `nvim-compe`, the Luasnip source is defined there. I think there even is an active issue with something like that.

**Comment by flosker** [comment]
I tried again, same `friendly-snippets` folder copied to custom directory & added the full path, still it doesn't load them. Only works, when path is in `runtimepath`.

```
require('luasnip/loaders/from_vscode').lazy_load({path = '~/.config/nvim/plugins/snippets'})
```

**Comment by L3MON4D3** [comment]
Oh yes, you're right, it doesn't work for me either. I'll look into it

**Comment by leiserfg** [comment]
You have a typo, it's  `paths`.

**Comment by leiserfg** [comment]
Now that I see, it's wrong in the `example.lua`, but it's correct In the `DOC.md`. My fault, let me fix it.

**Comment by flosker** [comment]
I did try both versions including `paths`, it still doesn't work.

**Comment by L3MON4D3** [comment]
Should work with master, could you try?

**Comment by flosker** [comment]
Yep! Works now.

**Comment by benbrastmckie** [comment]
Late to the party, but having similar issues. In my `init.lua` I require `luasnip.lua` which includes the lines:
```
local ls = require("luasnip")

require("luasnip.loaders.from_vscode").load({ paths = "~/.config/nvim/snippets/" })
```
My snippets folder includes `package.json` which reads as follows:
```
{
"name": "custom-snippets",
  "contributes": {
    "snippets": [
      {
        "language": "tex",
        "path": "./tex.json"
      },
      {
        "language": "markdown",
        "path": "./markdown.json"
      },
      {
        "language": "lua",
        "path": "./lua.json"
      }
    ]
  }
}
```
The snippets folder also includes the `tex.json` and other snippet files which look like:
```
{
  "Itemize": {
    "prefix": "item",
    "body": [
      "\\\\begin{itemize}",
      "\t\\item $0",
      "\\\\end{itemize}"
    ],
    "description": "Itemize"
  },
  "textit": {
    "prefix": "it",
    "body": "\\textit{${1:${TM_SELECTED_TEXT:text}}}",
    "description": "italic font"
  },
}
```
Is there anything that I'm missing? Regarding plugins, I have included:
```
  use { "L3MON4D3/LuaSnip" }
	use { "saadparwaiz1/cmp_luasnip" }
```
I have not included `use { "rafamadriz/friendly-snippets" }` since I take it this will load a bunch of snippets that I don't want. However, I have noticed that the snippets included there do work if I instal the plugin. Any thoughts would be greatly appreciated.

**Comment by L3MON4D3** [comment]
Ah, there's a trailing comma in `tex.json`, removing that should do it (check the other files too?)

**Comment by benbrastmckie** [comment]
Cheers!

**Comment by aloispichler** [comment]
Same problem here: I have
`require("luasnip.loaders.from_vscode").load({paths = "~/.config/Code/User/snippets/"})`,
the file `~/.config/Code/User/snippets/tex.json` is
`{
	"testSnippet":   { "prefix": "test", "body": ["testSnippet"], "description": "testSnippet" },
}`,
but nothing is loaded wit tex files. Any idea??? – thanks in advance
