### ISSUE TITLE
Support for importing snippets other popular editors

### ISSUE THREAD

**Issue by krishpy99** [L3MON4D3/LuaSnip#1233]
I have absolutely loved the LuaSnip experience and am currently migrating from Sublime text to neovim. I have looked for better ways to do it but as of now, I am manually refactoring snippets to be able to work with luasnip and since I have a lot of it, it feels cumbersome. I was wondering if there could be a simpler way to import snippets to luasnip. 

Similar to luasnip.loaders.from_vscode, can there be custom a custom method like luasnip.loaders.from("editor-name", "optional-dir-location"). I am completely new to both lua and the open source community so there might be severe skill-issues in my logic.

**Comment by L3MON4D3** [comment]
Hi :)
Are you aware of [snippet-converter](https://github.com/smjonas/snippet-converter.nvim)? It targets essentially the issue you have right now, moving a large existing snippet-collection

Right now I'm rather opposed to adding another loader, we have vscode for loading the most common format, snipmate as a really nice format for quickly writing a snippet, and lua for full flexibility, and for converting others there's `snippet-converter`

**Comment by krishpy99** [comment]
Thank you for the pointer! Couldn't help but notice they also have a similar ticket open. Will try working on it!
