### ISSUE TITLE
Trigger not working

### ISSUE THREAD

**Issue by centipedesquad** [L3MON4D3/LuaSnip#1237]
Here is how I call LuaSnip from Lazy:
```lua
return{
        {
		"L3MON4D3/LuaSnip",
		-- follow latest release.
		version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
		-- install jsregexp (optional!).
		build = "make install_jsregexp",
	}
}
```

I also associate the keybindings as follows:
```
local ls = require('luasnip')

-- LuaSnip
vim.keymap.set({"i"}, "<Tab>", function() ls.expand() end, {silent = true})
vim.keymap.set({"i", "s"}, "<Tab>", function() ls.jump( 1) end, {silent = true})
vim.keymap.set({"i", "s"}, "<S-Tab>", function() ls.jump(-1) end, {silent = true})

vim.keymap.set({"i", "s"}, "<C-E>", function()
	if ls.choice_active() then
		ls.change_choice(1)
	end
end, {silent = true})
```

Both the files containing the keybindings and lazy plugin are in turn `require`d in the `init.lua` file. Yet the keybindings are not working. If I make a `autosnippet` then it autoexpands, but no matter which keybinding I associate with triggering the snippets, they don't seem to work. Any idea what I might be doing wrong?

**Comment by L3MON4D3** [comment]
Well, expand is overwritten immediatly by jump :P
You can instead map `ls.expand_or_jump()`, which will try to expand and if that was not successful, jump, or find two different keys for this (I'd recommend the latter :) )

**Comment by centipedesquad** [comment]
Thanks! That was indeed rather stupid of me. This resolved it :)
