### ISSUE TITLE
Expanding with TM_DIRECTORY and jsregexp return whole path

### ISSUE THREAD

**Issue by dev4s** [L3MON4D3/LuaSnip#1246]
Hi,
I'm using NVIM 0.10.2 on Windows 11 (I know, I know...) with the latest LuaSnip & jsregexp in ver. 0.6. I have some problems with creating a snippet that will use the ${TM_DIRECTORY} and the regex for it (let's call it expanding for now because I don't know the proper wording for this). The expanding for the ${TM_DIRECTORY} works without any problems, but when I try:
```lua
${TM_DIRECTORY/([^\\\\]+)\\\\?$/${1:/upcase}/}
``` 
It expands in this way:
```lua
D:\Proj\Dev\Cpp\learn\learn02\SRC
``` 
But it should only expand to SRC

I've checked if the problem is with the regexp or jsregexp (or even luarocks) by making a simple lua file:
```lua
local jsregexp = require("jsregexp")

local regex = "([^\\\\]+)\\\\?$"

local current_dir = io.popen("cd"):read("*l") --Windows path like: C:\windows\system32

local re, err = jsregexp.compile_safe(regex, "g")

print(err)

for match in re:match_all(current_dir) do
	print(match)
	for j, group in ipairs(match) do
		print(j, group)
	end
end
```
The results:
![2024-10-22 00_20_15-Spotify Premium](https://github.com/user-attachments/assets/60a780d5-8b55-43c7-97c6-0d7aadc6d432)

I've tried many different types of regexp, but still - the same problem... What I'm doing wrong?

**Comment by L3MON4D3** [comment]
Hi :)
IIUC this happens because the non-matching parts of the path are used verbatim, and only the last part matches and is thus upcased.
To make the result exclude the other path-components, the regex has to match the entire path, which can be achieved with `${1/.*\\\\([^\\\\]+)\\\\?$/${1:/upcase}/}`

**Comment by dev4s** [comment]
Thank you! This worked. Will need to remember that :)
