### ISSUE TITLE
Feat: assign snippet.priority when adding a snippet

### ISSUE THREAD

**Issue by aarondill** [L3MON4D3/LuaSnip#1249]
By assigning the calculated priority when adding a new snippet, external projects such as [cmp_luasnip](https://github.com/saadparwaiz1/cmp_luasnip) can use this to properly sort suggestions. Currently, this priority is used to store the snippet in the `by_prio` table, which is inaccessible to outside modules. As such, it is currently impossible for outside code to accurately collect all registered snippets *and* sort by priority.

<details>
<summary>
This (one line) diff would resolve this issue by assigning the calculated priority to the snippet, thusly exposing it to outside modules through `luasnip.get_snippets`
</summary>

```diff
diff --git a/lua/luasnip/session/snippet_collection/init.lua b/lua/luasnip/session/snippet_collection/init.lua
index 33f05c0..433235c 100644
--- a/lua/luasnip/session/snippet_collection/init.lua
+++ b/lua/luasnip/session/snippet_collection/init.lua
@@ -233,6 +233,7 @@ function M.add_snippets(snippets, opts)
 					or (snip.priority and snip.priority)
 					or opts.default_priority
 					or 1000
+				snip.priority = snip_prio
 
 				-- if snippetType undefined by snippet, take default value from opts
 				local snip_type = snip.snippetType ~= nil and snip.snippetType
```

</details>

<details>
<summary> This (4-line) diff is the changes required by cmp_luasnip to take advantage of this change. Note: this is *impossible* without this change </summary>

```diff
diff --git a/lua/cmp_luasnip/init.lua b/lua/cmp_luasnip/init.lua
index 4641579..40eb7ab 100644
--- a/lua/cmp_luasnip/init.lua
+++ b/lua/cmp_luasnip/init.lua
@@ -88,6 +88,7 @@ function source:complete(params, callback)
 							word = snip.trigger,
 							label = snip.trigger,
 							kind = cmp.lsp.CompletionItemKind.Snippet,
+              priority = snip.priority,
 							data = {
 								filetype = ft,
 								snip_id = snip.id,
@@ -98,6 +99,9 @@ function source:complete(params, callback)
 					end
 				end
 			end
+      table.sort(ft_items, function(a, b)
+        return a.priority > b.priority
+      end)
 			snip_cache[ft] = ft_items
 		end
 		vim.list_extend(items, snip_cache[ft])
```
</details>

If this change is accepted, I will be opening an issue at cmp_luasnip to request this change.

**Comment by L3MON4D3** [comment]
Hi :)

Yeah, that seems sensible, no reason not to include this data :D
I'll push a commit here, if you do a PR for `cmp_luasnip`, make sure to account for the case that `priority` may be nil (for older versions of luasnip) and default to 1000 if it is.

**Comment by L3MON4D3** [comment]
Okay small issue: if we reuse the name `priority`, we will use the wrong priority if the snippets are added again with a non-1000 default_priority (first added with default_priority=1000 -> priority set to 1000 -> added again with default_priority=1001 -> priority still 1000).
Now, this is a bit contrived, but maybe there is some usecase for doing stuff like this, and I'd like to not prevent it.

Let's use `snip.effective_priority` for this, we even have a tiny bit more info in that case (was the priority set by the user or not)
