### ISSUE TITLE
"Fix lazy-loading" (314acc4) broke lazy-loading

### ISSUE THREAD

**Issue by wilriker** [L3MON4D3/LuaSnip#125]
After 314acc4 lazy-loading via
```
require("luasnip.loaders.from_vscode").lazy_load()
```
with no additional arguments and `friendly-snippets` installed does no longer work. No snippets are loaded at all. It worked before this commit (found via `git bisect`).

Eager loading (via `.load()`) still works.

**Comment by L3MON4D3** [comment]
Could you try `require("luasnip/loaders/from_vscode").lazy_load()`?

**Comment by wilriker** [comment]
Yes, that still works although sumneko is able to determine the correct source file for the above version with dots.

**Comment by leiserfg** [comment]
Will try to fix it without changing the API

**Comment by L3MON4D3** [comment]
> I think the ubiquitous standard in (neovim) Lualand is to use dots, not slashes, for module paths. I _strongly_ recommend following that convention in Luasnip as well.

Yep, that should be changed if it doesn't work otherwise

**Comment by L3MON4D3** [comment]
Okay, I'll wait for what you come up with

**Comment by leiserfg** [comment]
Have a look at #126

**Comment by clason** [comment]
> > I think the ubiquitous standard in (neovim) Lualand is to use dots, not slashes, for module paths. I _strongly_ recommend following that convention in Luasnip as well.
> 
> Yep, that should be changed if it doesn't work otherwise

I think it should be changed regardless ;)

**Comment by wilriker** [comment]
I can confirm that it works again with dots. Thanks! (also sorry, I totally misunderstood that note in the docs about using slash - I thought that was about if I provide custom paths).
