### ISSUE TITLE
Auto reload not working for me

### ISSUE THREAD

**Issue by kkrime** [L3MON4D3/LuaSnip#1256]
When I make a manual change to my snippet files ( as located in `require("luasnip.loaders.from_lua").load({ paths = "~/.config/nvim/snippets/" })`) the snippet doesn't get updated until I restart vim.

Even when I disable all other plugins and only load luasnip with minimul config that's still the case. (FYI - I'm using lazy)

macOS 14.5 (23F79)
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382

Any ideas what the issue could be?

**Comment by L3MON4D3** [comment]
Ah, you'll have to pass `fs_event_providers = {libuv=true, autocmd=true}` to the load-call (I'll assume with manual change you're talking about editing the file from outside the neovim-instance?)

**Comment by kkrime** [comment]
@L3MON4D3 that did the trick! and yea I was making the change from a different neovim-instance.

Much appreciated :)

**Comment by kkrime** [comment]
Closing issue

**Comment by kkrime** [comment]
Closing issue

**Comment by L3MON4D3** [comment]
Happy to help :)
