### ISSUE TITLE
Snippet always expands and never jumps

### ISSUE THREAD

**Issue by HeitorAugustoLN** [L3MON4D3/LuaSnip#1259]
I've created this snippet:
```lua
---@diagnostic disable: undefined-global
return {
  s("fetchFrom", {
    t("fetchFrom"),
    c(1, {
      t("GitHub"),
      t("GitLab"),
      t("Gitea"),
      t("Gitiles"),
      t("BitBucket"),
      t("Savannah"),
      t("RepoOrCz"),
      t("SourceHut"),
    }),
    t(" {"),
    t({ "", '  owner = "' }),
    i(2, "owner"),
    t('";'),
    t({ "", '  repo = "' }),
    i(3, "repo"),
    t('";'),
    t({ "", '  rev = "' }),
    i(4, "v${version}"),
    t('";'),
    t({ "", '  hash = "' }),
    i(5, "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="),
    t('";'),
    t({ "", "};" }),
  }),
}
```

And when using my keymap to jump forward, it keeps expanding into new snippets. The keymap is:

```lua
['<C-l>'] = cmp.mapping(function()
  if require("luasnip").expand_or_locally_jumpable() then
    require("luasnip").expand_or_jump()
  end
end, { 'i', 's' }),
```

You can see it in this video:

[Gravar a tela_20241117_181758.webm](https://github.com/user-attachments/assets/b9a0df10-b14a-4c06-bcd4-e413ddf1cfb2)

I don't remember this happening before with the same snippet, so maybe it is a recent bug.

**Comment by L3MON4D3** [comment]
Hi :)
Weird that this didnt happen before, I'd say that it's expected behaviour: expand ist preferred over jump (in oder to expand snippets inside of nodes that can be jumped from), so If the text before the cursor matches a snippet, it ist expanded, always :/
A solution ist to usw separate keys for expand and jump, or ro make sure snippet-triggers don't occur anywhere in your snippets

**Comment by HeitorAugustoLN** [comment]
> Hi :) Weird that this didnt happen before, I'd say that it's expected behaviour: expand ist preferred over jump (in oder to expand snippets inside of nodes that can be jumped from), so If the text before the cursor matches a snippet, it is expanded, always :/ A solution is to use separate keys for expand and jump, or to make sure snippet-triggers don't occur anywhere in your snippets

Yeah that makes sense, I tested using the keymap one character after `fetchFrom` and it works fine, so it is just my fault using this keymap instead of using a separate one for jumping. Thanks for the quick response! :)
