### ISSUE TITLE
blink.cmp Integration

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#1263]
Hi @L3MON4D3, how is live going?

I moved to blink.cmp, so now this exists in case you are interested:

https://github.com/leiserfg/blink_luasnip

**Comment by L3MON4D3** [comment]
Going fine, still finding time to tinker with neovim :D (as do you I see :P)

blink seems pretty cool, I'm definitely interested! Can blink also do trigger-on-keybind, with only a few sources, like cmp? eg. something like
```lua
vim.keymap.set("i", "<C-O>", function()
	cmp.complete({
		config = {
			sources = {
				{name = "nvim_lsp"},
				{name = "luasnip"},
			}
		}
	})
end)

vim.keymap.set("i", "<C-u>", function()
	cmp.complete({
		config = {
			sources = {
				{name = "emoji"},
			}
		}
	})
end)

vim.keymap.set("i", "<C-F>", function()
	cmp.complete({
		config = {
			sources = {
				{
					name = "path",
					option = {
						get_cwd = function(params)
							local path = {
								vim.fn.expand(('#%d:p:h'):format(params.context.bufnr)), -- default value
								vim.fn.getcwd(),
							}
							return path
						end
					},
				}
			}
		}
	})
end)
```

**Comment by leiserfg** [comment]
I don't see any similar API in blink.

**Comment by L3MON4D3** [comment]
Ah okay, guess I'll stick with cmp for a while longer :D

**Comment by Saghen** [comment]
I've included a source in blink.cmp based off blink_luasnip so feel free to close this

p.s. you might want to watch https://github.com/Saghen/blink.cmp/issues/386 :)

**Comment by L3MON4D3** [comment]
Oh amazing, thanks for the pointer!
Closing :)

**Comment by arepaFlipper** [comment]
> Hi @L3MON4D3, how is live going?
> 
> I moved to blink.cmp, so now this exists in case you are interested:
> 
> https://github.com/leiserfg/blink_luasnip

Now it is archived?
Bruh!

**Comment by leiserfg** [comment]
@arepaFlipper it is archived because it's not required anymore, the integration is now built-in.
