### ISSUE TITLE
How to disable node update after expanding?

### ISSUE THREAD

**Issue by dquevid** [L3MON4D3/LuaSnip#1267]
When i expand `rfce` snippet it asks for name of the component. Previously that was all, but now if i try to change name of the component, it overrides the return statement with the new name. I want to disable such behavior globally, or at least when using `rfce`. Is there a way to do that?

**Comment by L3MON4D3** [comment]
Could you share the snippet in question? (ie. probably find it in `friendly-snippets`?)
I'm not totally sure what you're talking about, and having the snippet would help me understand :)

**Comment by dquevid** [comment]
> Could you share the snippet in question? (ie. probably find it in `friendly-snippets`?) I'm not totally sure what you're talking about, and having the snippet would help me understand :)

I'm sorry, i forgot to mention. The issue is with `friendly-snippets` [rfce](https://github.com/rafamadriz/friendly-snippets/blob/efff286dd74c22f731cdec26a70b46e5b203c619/snippets/javascript/react-es7.json#L567) snippet.


https://github.com/user-attachments/assets/3a22e76a-1484-4762-8c83-b0dbf611b069

**Comment by L3MON4D3** [comment]
Ah, that can't be turned off unfortunately :/
If the two nodes are linked, the second one is updated whenever the first one is changed.

If you want to restore the previous behaviour, you could register your own `rfce`-snippet with higher priority (eg. 1001), so that your own rfce-snippet is expanded instead of the one provided by `friendly-snippets`.
Alternatively, fork `friendly-snippets` and change it in there.

**Comment by dquevid** [comment]
luasnip setup options [accept](https://github.com/L3MON4D3/LuaSnip/blob/33b06d72d220aa56a7ce80a0dd6f06c70cd82b9d/doc/luasnip.txt#L3447) `update_events` table to specify on which events should the snippet be updated. I wonder if there is a way to clear these event, 'cause both empty dictionary and an empty string throw an error.

**Comment by L3MON4D3** [comment]
Mhmm yeah you could disable updates by setting that to nil I think, but the return would still be updated when jumping away from the insertNode.

Supporting your use case, not discarding the changes made to insertNodes inside a dynamicNode, sounds pretty useful, I'll think about how to do it and provide a good interface to it :). (Don't think it's possible with restoreNode, at least not with official API)
(But it probably won't be possible with parsed snippets, you'd have to write your own version in lua😅)

**Comment by dquevid** [comment]
Found a workaround! Neovim has a [User](https://neovim.io/doc/user/autocmd.html#User) event that is

> Not executed automatically.

which i just pass to `update_events` [option](https://github.com/L3MON4D3/LuaSnip/blob/33b06d72d220aa56a7ce80a0dd6f06c70cd82b9d/doc/luasnip.txt#L3447) in setup table.

```lua
config = function()
    require("luasnip").setup({
        update_events = "User"
    })
end,
```

Thank you for the operative replies!
