### ISSUE TITLE
Does not load custom snippets

### ISSUE THREAD

**Issue by 1057437122** [L3MON4D3/LuaSnip#1270]
I cloned the lazy starter template from lazyvim.org with this cmd:

`git clone https://github.com/LazyVim/starter ~/.config/nvim`

in `plugins` folder, I created a file called `snippets.lua`, inside the file I copied the config:

```
return {
  "L3MON4D3/LuaSnip",
  -- follow latest release.
  version = "v2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
  -- install jsregexp (optional!).
  build = "make install_jsregexp",
}

```

then, I create a file `~/.config/nvim/my_snippets/snippets/all.json` and in init.lua, I loaded with the following cmd:

`require("luasnip.loaders.from_vscode").lazy_load({ paths = { "~/.config/nvim/lua/custom/snippets/" } })`

but this doesn't work, when I use  `LuaSnipListAvailable ` in neovim, it shows like

```
{
all = {},
lua = {}
}
```

below is my full configuration:

`https://github.com/1057437122/luasnipnotwork.git`

**Comment by L3MON4D3** [comment]
You need a `~/.config/nvim/my_snippets/snippets/package.json` which lists the snippet-file `all.json`.
```json
{
	"name": "test-snippets",
	"contributes": {
		"snippets": [
			{
				"language": [
					"all"
				],
				"path": "./all.json"
			}
		]
	}
}
```
Should work I think :)

**Comment by 1057437122** [comment]
Thank you so much! Now, when I use LuaSnipListXXX cmd, it lists all the data, look ,there's a `cbt` snip
<img width="593" alt="image" src="https://github.com/user-attachments/assets/cfa46b6b-50e2-4148-ba66-db23cb307496" />
  but it doesn't work when type in file, I typed `c` , what I expected is `cbt` but it doesn't show: 
<img width="755" alt="image" src="https://github.com/user-attachments/assets/c711347e-ded1-4b66-b9f6-fc8cc26f3303" />

**Comment by L3MON4D3** [comment]
Do you have `cmp_luasnip`? The snippets are not automatically listed by `nvim-cmp` (if you use `nvim-cmp`), you need a source and have to activate it

**Comment by 1057437122** [comment]
now it works ! Thanks a lot. But I wanna say, I used this plugin maybe a year ago since lazyvim 3, the config before was really easy, the new version is a little complicated and there is not a clear document says what I should do when do the upgrading, however, thanks for your patience and help.
