### ISSUE TITLE
snippet items duplicate every time  that resourced

### ISSUE THREAD

**Issue by ayoubelmhamdi** [L3MON4D3/LuaSnip#128]
snippet items duplicate every time  that resourced by:
```
:lua require('luasnip.loaders.from_vscode').load()
:lua require('luasnip.loaders.from_vscode').load()
```
I'm using `hrsh7th/nvim-compe` and I'm trying to `change/add` some snippet of `vscode`, I must reopen `neovim` for testing if it works without any error
so :  
  - What this better why to test `vscode` snippet without reopening `neovim`
  - is `nvim-compe` plugging that store old snippet or `luasnip` ?
     
    
   
   
![luasnip-1](https://user-images.githubusercontent.com/34358145/130557778-969971b7-5646-4820-8118-fb7a89f8daf7.png)

**Comment by L3MON4D3** [comment]
Yes, everytime the `load()`-function is called, the snippets get appended to `require("luasnip").snippets`, causing duplicates if the snippet already exists.
You could set that table to `{}` before reloading (would also delete your snippets defined in lua, but for testing lsp-snippets it sounds alright)

**Comment by ayoubelmhamdi** [comment]
I miss something bellow:
```
local f= {}
f = require('luasnip.loaders.from_vscode').load()
```

**Comment by leiserfg** [comment]
.

**Comment by leiserfg** [comment]
> I miss something below:
> 
> ```
> local f= {}
> f = require('luasnip.loaders.from_vscode').load()
> ```

No, that won't do it.


It seems like a regression, I will have a look at it tonight.

**Comment by ayoubelmhamdi** [comment]
> It seems like a regression, I will have a look at it tonight.
ok, thank you, I wait for you.

**Comment by leiserfg** [comment]
No, no, I thought it was the `lazy_load`,  the `load()` one happens with every call, as there is not how to dedupe the snippets easily (two snippets can have the same trigger).

**Comment by leiserfg** [comment]
The recommended way is to use lazy loading.

**Comment by ayoubelmhamdi** [comment]
lazy loading load snippet for one time but I want to override old snippet 
  - load append to old snippet
  - lazy load in init buffer

**Comment by L3MON4D3** [comment]
> I miss something below:
> 
> ```
> local f= {}
> f = require('luasnip.loaders.from_vscode').load()
> ```

Try
```lua
require("luasnip").snippet={}
require("luasnip.loaders.from_vscode").load()
```

**Comment by L3MON4D3** [comment]
> I miss something below:
> 
> ```
> local f= {}
> f = require('luasnip.loaders.from_vscode').load()
> ```

Try
```lua
require("luasnip").snippet={}
require("luasnip.loaders.from_vscode").load()
```

**Comment by ayoubelmhamdi** [comment]
`require("luasnip").snippet={}` not delete loaded `snippets`

**Comment by L3MON4D3** [comment]
Ah srry, `snippets`

**Comment by ayoubelmhamdi** [comment]
now it's work, bravo, think you!

**Comment by ayoubelmhamdi** [comment]
now, I can change any snippet and view error or example immediately 
```
vim.cmd([[
        autocmd BufWritePost *.json lua require("luasnip").snippets={}
        autocmd BufWritePost *.json lua require("luasnip.loaders.from_vscode").load()
]])
```
thank for @L3MON4D3  and @leiserfg :100:  :heart:

**Comment by rkoval** [comment]
@L3MON4D3 - Overriding `luasnip.snippets` does not seem to work for me. Was this behavior that was changed recently?

I'm otherwise loving this plugin! Thank you so much for building it!

**Comment by L3MON4D3** [comment]
> Was this behavior that was changed recently?

Yeeah, we're now using a function for adding snippets, `add_snippets`.
(it's described in `DOC.md`, just search for it)
It's possible to override previously loaded snippets by setting the `key`-key to some unique value.

> I'm otherwise loving this plugin! Thank you so much for building it!

:)

**Comment by rkoval** [comment]
Ahh hmm, how does this work with loaders/`require('luasnip').load`? I was under the impression `add_snippets` was used to manually import individual snippets, whereas the loaders were for importing snippets in bulk from potentially other formats?

**Comment by leiserfg** [comment]
> Ahh hmm, how does this work with loaders/`require('luasnip').load`? I was under the impression `add_snippets` was used to manually import individual snippets, whereas the loaders were for importing snippets in bulk from potentially other formats?

Loaders are just fancy wrappers of `add_snippets`. They could be done by someone else, we just did them ourselves and shipped them in `luasnip.loaders`.

**Comment by L3MON4D3** [comment]
Jup, exactly, if you're using the loaders and edit the snippet-file, the corresponding snippets in that nvim-instance should be overwritten with the new ones as soon as you `:w` the file.

**Comment by rkoval** [comment]
> Jup, exactly, if you're using the loaders and edit the snippet-file, the corresponding snippets in that nvim-instance should be overwritten with the new ones as soon as you :w the file.

Ahh hmm, I'm not seeing this behavior. That is, I'm seeing duplicated snippets per OP's original issue. If it's related to this:

> It's possible to override previously loaded snippets by setting the key-key to some unique value.

... I don't know what `key`-key is being referenced here to wipe the underlying loaded snippets.

**Comment by L3MON4D3** [comment]
Ouh, that doesn't sound good, could you open a separate issue?
 The `key`-key can be set in the `add_snippets`-call, look in `DOC.md`

**Comment by rkoval** [comment]
I can open up another issue, but isn't the behavior I'm seeing a regression of this issue? That is, calling `require("luasnip.loaders.from_vscode").load()` multiple times results in duplicate snippets? The only other detail I can think to include is that I'm technically using `require('luasnip.loaders.from_lua').lazy_load({ paths = '/path/to/snippets' })` instead. That is, passing a `path` and using `luasnip.loaders.from_lua` instead of `luasnip.loaders.from_vscode`

**Comment by L3MON4D3** [comment]
Mhmm, I can see that, a regression on the general mechanism... But since this issue is very outdated, I don't think there's any reason to continue it.
New issues are much easier to find for other users who have this same problem right now, and, if I eventually implement a fix for your problem, someone who wants to know what the issue was doesn't have to potentially wade through unrelated stuff.

When you open it, could you provide a MWE? I don't experience this issue with my local config :/
