### ISSUE TITLE
bad argument #1 to 'str_utfindex' 

### ISSUE THREAD

**Issue by kdheepak** [L3MON4D3/LuaSnip#130]
Some times when I copy paste into neovim, I get the following error:

```
Error detected while processing InsertLeave Autocommands for "*":
E5108: Error executing lua ...site/pack/packer/start/LuaSnip/lua/luasnip/util/util.lua:94: bad argument #1 to 'str_utfindex' (string expected, got nil)
Press ENTER or type command to continue
```

I'm not able to consistently reproduce it.

**Comment by L3MON4D3** [comment]
That can occur if you deleted the text of a snippet earlier, right now you have to `:LuaSnipUnlinkCurrent` to not get any errors after deleting it.

**Comment by L3MON4D3** [comment]
With newest master there is also the possibility of changing the maps for eg. `dd` to directly unlink the snippet if it was deleted entirely, [see here](https://github.com/L3MON4D3/LuaSnip/issues/116#issuecomment-904535055)

**Comment by L3MON4D3** [comment]
I'm going to go ahead and close this issue, if you experience more errors, open another issue (or reopen this one) :)
