### ISSUE TITLE
Issues when placeholder of a tabstop is defined multiple times

### ISSUE THREAD

**Issue by eosti** [L3MON4D3/LuaSnip#133]
I just started to use [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) and have noticed an issue with how placeholders are handled. For example, using this LaTeX snippet:
```
      "\\\\begin{${1:env}}",
      "\t$0",
      "\\\\end{${1:env}}"
  ```
This snippet will initially move the cursor to the _second_ instance of `$1`, in the `\end` command, and then after hitting tab, will jump to `$0` without replacing the placeholder `env` in the `\begin` statement. However, if I remove the placeholder from the `\end` tabstop:
```
      "\\\\begin{${1:env}}",
      "\t$0",
      "\\\\end{${1}}"
  ```
Here, the completion works as expected: the cursor is brought to the first `$1` tabstop and then replaces all successive instances of `$1`. This makes me think that LuaSnip is having issues with the placeholder coming up multiple times for the same tabstop. I'm not very familiar with the snippet syntax (if defining placeholders multiple times is allowed or not), so I can't tell if this is intentional behavior or a bug. Thanks!

**Comment by L3MON4D3** [comment]
Oh, right, I only looked at the LSP reference tbh :sweat_smile: 
b96572f should do it :D

**Comment by eosti** [comment]
Resolved, thank you!
