### ISSUE TITLE
Add snippet to custom position 

### ISSUE THREAD

**Issue by danymat** [L3MON4D3/LuaSnip#134]
Hello, I'm the creator of [Neogen](https://github.com/danymat/neogen), an annotation generator based on TS.

I would like to integrate cursor positioning in Neogen, and was trying to see if LuaSnip supports positioning snippets in custom positions in the file. 

Do you have such features?

Regards, Daniel

**Comment by L3MON4D3** [comment]
I'm going to go ahead and close this for now, if  you have more questions, feel free to reopen/open another issue :D
