### ISSUE TITLE
Autosnippets seem to not work sometimes

### ISSUE THREAD

**Issue by IndianBoy42** [L3MON4D3/LuaSnip#135]
```
    s("$", { t "\\(", i(0), t "\\)" }),
    s("\\(", { t "\\( ", i(0), t " \\)" }),
    s("\\it", { t "\\texit{", i(0), t "}" }),
    s("\\bf", { t "\\textbf{", i(0), t "}" }),
    s("\\eq", { t "\\begin{equation}\n", i(0), t "\\end{equation}" }),
```

I have added these autosnippets for writing latex papers/homework. The first two activate correctly, but the last three don't seem to. I wonder if it has something to do with availability of other completions and the popup of nvim-cmp being open? Or is there some other limitation to autosnippets that I don't know of?

**Comment by L3MON4D3** [comment]
> I wonder if it has something to do with availability of other completions and the popup of nvim-cmp being open?

That should be it, autosnippets are expanded on `TextChangedI`, which doesn't fire if the popupmenu is open. I'll add `TextChangedP` so they will expand if the pum is visible.

**Comment by IndianBoy42** [comment]
Another question: is it possible to have `regTrig=true` on autosnippets?

**Comment by L3MON4D3** [comment]
Yes! Autosnippets use the same expansion-routine, it is just triggered on each added character.

**Comment by IndianBoy42** [comment]
The example snippets don't work for me, although I have just noticed they don't really work from non autosnippets either. Is regtrig compatible with the 'supertab' function from the README? or is it necessary to have a separate key for luasnip expand?

**Comment by L3MON4D3** [comment]
`regTrig` should be compatible with that, and supertab shouldn't matter. Which snippet exactly does not work? Could you show your config?

**Comment by IndianBoy42** [comment]
```
		-- The last entry of args passed to the user-function is the surrounding snippet.
		s(
			{ trig = "a%d", regTrig = true },
			f(function(args)
				return "Triggered with " .. args[1].trigger .. "."
			end, {})
		),
		-- It's possible to use capture-groups inside regex-triggers.
		s(
			{ trig = "b(%d)", regTrig = true },
			f(function(args)
				return "Captured Text: " .. args[1].captures[1] .. "."
			end, {})
		),
```

Config in: 
https://github.com/IndianBoy42/LunarVim/blob/master/lua/lv-luasnips/init.lua

Snippets in:
https://github.com/IndianBoy42/LunarVim/blob/master/lua/lv-luasnips/tex.lua (i have changed some things around to try and see when regex triggers work or dont work

I cant seem to make `\w+` work, or `%s`, but `[a-zA-Z]+` does

**Comment by L3MON4D3** [comment]
Ohh okay, check out http://lua-users.org/wiki/PatternsTutorial, luasnip makes use of lua patterns, not js/vim/... regular expressions.
Make sure to set the trigger via `{trig="%w+", regTrig=true}` if you want the trigger to be interpreted as a pattern.

**Comment by L3MON4D3** [comment]
> ```
> 		-- The last entry of args passed to the user-function is the surrounding snippet.
> 		s(
> 			{ trig = "a%d", regTrig = true },
> 			f(function(args)
> 				return "Triggered with " .. args[1].trigger .. "."
> 			end, {})
> 		),
> 		-- It's possible to use capture-groups inside regex-triggers.
> 		s(
> 			{ trig = "b(%d)", regTrig = true },
> 			f(function(args)
> 				return "Captured Text: " .. args[1].captures[1] .. "."
> 			end, {})
> 		),
> ```

But these two should be working regardless, please make sure they are actually loaded and there's no other text before the trigger (wordTrig is set by default).

**Comment by IndianBoy42** [comment]
Ah I see, that's my misunderstanding, i saw `%` signs and thought it was similar to printf. And when that didn't work i tried square brackets like regex and that worked, so i was confused 

Thanks for the help

**Comment by L3MON4D3** [comment]
Oh, yeah I can see how that could be confusing.
Glad to help :D
