### ISSUE TITLE
can't input j/k in select mode

### ISSUE THREAD

**Issue by glyh** [L3MON4D3/LuaSnip#136]
When a new snippet is open, I can't input j or k because that would cause the selection range move rather than input a character

**Comment by glyh** [comment]
Also, this plugin integrate not that well with completion plugins, sometimes you use auto complete to fill-in the words in the snippet, and find that you want to jump to the next word while the auto complete menu won't close, thus you have to somehow use other ways to close the window, or you can't move to the next blank to fill

**Comment by leiserfg** [comment]
Luasnip has no knowledge about completion plugins (there are like 10 different ones) so you have to set up them in a way they don't collide. If you are more clear maybe someone can help you the other way it's more a rant than an issue.

**Comment by glyh** [comment]
> Luasnip has no knowledge about completion plugins (there are like 10 different ones) so you have to set up them in a way they don't collide. If you are more clear maybe someone can help you the other way it's more a rant than an issue.

Sorry for not stating clearly about completion tools integration, and this one is mainly about the "j" "k" problem.

**Comment by L3MON4D3** [comment]
> When a new snippet is open, I can't input j or k because that would cause the selection range move rather than input a character

I don't really get what you mean (replacing the text of a SELECTed insertNode works fine for me), could you post a snippet/give a more explicit example where that problem arises?

**Comment by glyh** [comment]
Well, after some further test, I've found out that "kana/vim-arpeggio" conflicts with this plugin, so it's not LuaSnip's problem.

**Comment by glyh** [comment]
And if you want to see how the conflits look like (from 15s, LSP takes time to init) :
[![asciicast](https://asciinema.org/a/SuRTIaXv0rgtXghd9Ot0Mwkmb.svg)](https://asciinema.org/a/SuRTIaXv0rgtXghd9Ot0Mwkmb)

**Comment by glyh** [comment]
I'm closing this, since it's not likely to be fixed.(interop problems arises everywhere), and I think the best solution is to merge arpeggio's function into neovim itself.
