### ISSUE TITLE
Parser fails with TM_SELECTED_TEXT

### ISSUE THREAD

**Issue by eosti** [L3MON4D3/LuaSnip#137]
Example snippet:
```
      "\\section{${1:section name}} % (fold)",
      "\\label{sec:${2:${1/(\\w+)(\\W+$)?|\\W+/${1:?${1:/asciify/downcase}:_}/g}}}",
      "${0:$TM_SELECTED_TEXT}",
      "% section $2 (end)"
```
Expected behavior: I should be able to complete the snippet as usual. Even if `TM_SELECTED_TEXT` isn't implemented yet, the parser should at least let me finish the snippet at `$0` regardless of if there is selected text or not. 

Actual behavior: The parser immediately throws the error ﻿﻿`E5108: Error executing Lua [...]/snippets.lua:605: Attempt to concatenate a nil value.` without letting me fill in any values. It instead inserts the following expansion after the error:
```
\subsection{subsection name} % (fold)
\label{sub:subsection name}

0% subsection  (end)
```

**Comment by leiserfg** [comment]
It's implemented, seems like it's a regression when there is not `TM_SELECTED_TEXT`.

**Comment by leiserfg** [comment]
This could be affecting not only empty TM_SELECTED_TEXT but any node returning an empty list.
