### ISSUE TITLE
Error when storing selection containing lines of whitespace

### ISSUE THREAD

**Issue by kmarius** [L3MON4D3/LuaSnip#139]
```
E5108: Error executing lua ...site/pack/packer/start/LuaSnip/lua/luasnip/util/util.lua:257: attempt to get length of local 'line_indent' (a nil value)
```

Both patterns in `get_min_indent` don't match whitespace only/empty lines and cause the above error upon storing the selection.

**Comment by L3MON4D3** [comment]
Right, thanks for reporting that :)

**Comment by leiserfg** [comment]
@L3MON4D3  I was checking this (you fix it first) and noticed that you use `gsub` to dedent, that can be dangerous as it treats the prefix as a pattern, not as a plain string, and that can  cause issues if min_index ends matching `"  ." `

**Comment by kmarius** [comment]
The error still occurs unless the first selected line is whitespace only. Something is off, you are checking for `min_indent ~= nil` and then `min_indent == nil` in lines [258](https://github.com/L3MON4D3/LuaSnip/blob/3c400dad8e504aaa34524bc3d3cd1355e6bf62f1/lua/luasnip/util/util.lua#L258) and 260.

**Comment by L3MON4D3** [comment]
> @L3MON4D3 I was checking this (you fix it first) and noticed that you use `gsub` to dedent, that can be dangerous as it treats the prefix as a pattern, not as a plain string, and that can cause issues if min_index ends matching `" ." `

That shouldn't happen I think, `min_indent` is only whitespace ("^(%s)%S" and we store the group)

**Comment by leiserfg** [comment]
> The error still occurs unless the first selected line is whitespace only. Something is off, you are checking for `min_indent ~= nil` and then `min_indent == nil` in lines [258](https://github.com/L3MON4D3/LuaSnip/blob/3c400dad8e504aaa34524bc3d3cd1355e6bf62f1/lua/luasnip/util/util.lua#L258) and 260.

I was contemplating that in my fix, so here I go again :smile:

**Comment by L3MON4D3** [comment]
> The error still occurs unless the first selected line is whitespace only. Something is off, you are checking for `min_indent ~= nil` and then `min_indent == nil` in lines [258](https://github.com/L3MON4D3/LuaSnip/blob/3c400dad8e504aaa34524bc3d3cd1355e6bf62f1/lua/luasnip/util/util.lua#L258) and 260.

Whoops, yes, it should work now I think
