### ISSUE TITLE
Failed to expand with nvim-cmp

### ISSUE THREAD

**Issue by ray-x** [L3MON4D3/LuaSnip#141]
Got an error:
```
LuaSnip/lua/luasnip/util/parser.lua:351: Invalid text after $ at49  
```
Language Go

Sample code :

```
package main

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestDog(t *testing.T) {
	require.NoError(t, nil)
	require.NoEr
}


```

![image](https://user-images.githubusercontent.com/1681295/131284568-0c681a97-fb91-4c73-b23c-96f7c6cb3c3c.png)

If I press enter. Will see the error.

**Comment by L3MON4D3** [comment]
Could you add a `print(body)` to [this](https://github.com/L3MON4D3/LuaSnip/blob/9548bc3a3475966f8fd6bc45a0a81e5e041d94cd/lua/luasnip/init.lua#L181) function and post the output after completing? I don't have anything go-related installed and need to see the snippet that's causing the error.

**Comment by ray-x** [comment]
The body:

```
"NoError(${1:t require.TestingT}, ${2:err error}, ${3:msgAndArgs ...interface{\\}})"  
```

**Comment by L3MON4D3** [comment]
Oh, yeah that's _technically_ [malformed](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax) (check `grammar`) I think, the opening { in $3 would have to be escaped, too. :/
Does it expand correctly in eg. vscode?

**Comment by ray-x** [comment]
VSCode does not expand arguments. I am not sure if an additional plugin is needed.

**Comment by L3MON4D3** [comment]
Mhm, probably.
This seems to be a mistake in `gopls`, maybe open an issue there? We could've fixed it temporarily by providing a table where known faulty snippets from language servers can be replaced with working ones, but that would probably require quite a bit of work (I think some LS, including gopls, change snippets based on context, so basic string-equality wouldn't cut it) and it'd be obviously nicer to get working snippets from the LS.

**Comment by ray-x** [comment]
From the spec:
```
 With \ (backslash), you can escape $, } and \. Within choice elements, the backslash also escapes comma and pipe characters.
```

I think the grammar is ok here:

```
"NoError(${1:t require.TestingT}, ${2:err error}, ${3:msgAndArgs ...interface{\\}})"  
```

If I understand correctly, only need to put `\` before `}`

**Comment by L3MON4D3** [comment]
Oh no, yes you're right, I've always automatically assumed it extends to `{`. Well, that complicates things a bit on the parser-side, seems unnecessarily complicated that only one of {,} needs to be escaped, but so be it.
I'll look into fixing it

**Comment by L3MON4D3** [comment]
Okay, I think only the } has to be escaped because if no unescaped $ is before the {, it counts as escaped.
I pushed a fix, it should work now

**Comment by leiserfg** [comment]
After this change, this snippet (that was used previously to test the selected text env) is failing to parse.

    ls.parser.parse_snippet({trig='boo'},
      [[
   \\section{${1:section name}} % (fold)
   \\label{sec:${2:${1/(\\w+)(\\W+$)?|\\W+/${1:?${1:/asciify/downcase}:_}/g}}}
   "${0:$TM_SELECTED_TEXT}",
    % section $2 (end)
    ]])

**Comment by L3MON4D3** [comment]
Yeah, before it didn't really matter if a _pair_ of {,} wasn't escaped, now it does, which makes the parser fail there.
I was thinking about putting it down as a breaking change, but the previous behaviour was incorrect/too loose... I'll should've put it in breaking changes, at least to avoid confusion, I'll do that now.

**Comment by bew** [comment]
Hello, I don't understand this change:
**Why** would we need to escape the closing brace in `"\\begin{$1\}"` ? What's the logic behind this? Oo

**Comment by leiserfg** [comment]
@bew it's not an extra logic, that's what the specification says. Mind that it's only when you wanna the `}` to show off not when you wanna close the input.

**Comment by bew** [comment]
The specification says exactly this:
> With `\` (backslash), you can escape `$`, `}` and `\`.

But nowhere it says that you _must_ escape `}`.
My understanding of the spec is that we _can_ escape `}` id necessary. And one case where it is necessary is when inside a default text, for example: `${1:bar\}baz}`

**Comment by L3MON4D3** [comment]
I interpreted it as "\ can be used to escape... [if you want to put them in the text literally]", but it's open to interpretation, yes.
As always, how does vscode handle these cases?

**Comment by leiserfg** [comment]
Imho it's like @L3MON4D3  said, the other way it can become a non-free of context grammar and I don't see vscode doing rare backtrackings in their implementation. Painfully testing  it by hand in vscode is the only way to know for sure.

**Comment by bew** [comment]
I've tested in vscode using this snippet:
```json
{
    "Test brace parsing": {
        "prefix": "brace",
        "body": [
            "test ${1:with {\\} default} for {} <-- this",
        ],
        "description": "Test brace parsing in snippets"
    }
}
```

![brace-vscode-snippet](https://user-images.githubusercontent.com/9730330/131386806-e43b8d40-ddeb-4e5a-82a8-8de89f68c02a.png)

:eyes:

**Comment by leiserfg** [comment]
Yes, you are right, it's out of a tabstop so there is no ambiguity.

**Comment by stasjok** [comment]
I agree with **bew** here. Escaping of `}` required only if otherwise it would be treated as closing bracket for placeholder.
All these snippets expands as expected in vscode:
```json
"test": {
	"prefix": "test",
	"body": "{ $1 }"
},
"test1": {
	"prefix": "test1",
	"body": "$1 }"
},
"test2": {
	"prefix": "test2",
	"body": "${1:a}b}"
},
"test3": {
	"prefix": "test3",
	"body": "${1:a\\}b}"
}
```

**Comment by L3MON4D3** [comment]
Yikes, okay, but I think I know how to implement that.
How about `"${1: {} texttexttext"`?

**Comment by leiserfg** [comment]
That should be ` |{| texttexttext`  isn't @bew

**Comment by L3MON4D3** [comment]
Sure hope it isn't😬😬

**Comment by bew** [comment]
Hmm with the space, so like `| {| texttexttext`:
![brace-vscode-snippet3](https://user-images.githubusercontent.com/9730330/131392211-63c059f9-1876-4d84-991c-7c3d0fb219c2.png)

**Comment by leiserfg** [comment]
Yes, I forgot the space.  @L3MON4D3  we can use github.dev to test the snippets.

**Comment by L3MON4D3** [comment]
Riiight, that exists.

**Comment by L3MON4D3** [comment]
Okay, it wasn't hard at all, I just wasn't thinking. It should work correctly now.

**Comment by L3MON4D3** [comment]
Also thank you @bew for pointing out the error :)

**Comment by leiserfg** [comment]
Gosh, I did a fix for it last night but was not working fine, now I see the problem, I did the same as you but was using  `expr` instead of `expr == 0` again :facepalm:.

**Comment by leiserfg** [comment]
I'll have to set up a custom linter for it :smile:

**Comment by L3MON4D3** [comment]
Just after getting used to arrays starting at 1, lua hits you with 0 not being false :D

**Comment by bew** [comment]
> Also thank you @bew for pointing out the error :)

You're welcome! I'm actually not using LuaSnip yet 👀, I'm still on Ultisnips (with its quirks and crashes.....) and was procrastinating the migration of all my custom snippets to the node system of this plugin which seams less readable for me...
But since this change I see I can write the snippets in a readable manner, in a way similar to Ultisnips (and only use advances nodes for specific usecases), so I'm happy 😃
I think I'll migrate soon (or on next Ultisnips unexpected crash... which can be _very_ soon...)

**Comment by leiserfg** [comment]
I was thinking of making another loader for ultisnippets files, but those including python code will be really hard.

**Comment by leiserfg** [comment]
Yes, that's the idea, you write 80% of the snippets with the lsp (derived from textmate) syntax and then use the lua nodes for the rest.

**Comment by bew** [comment]
> I was thinking of making another loader for ultisnippets files, but those including python code will be really hard.

\o/
What about starting by giving warnings for not-simple snippets and skip them?

(maybe move to another issue? we're going completely offtopic here)

**Comment by L3MON4D3** [comment]
> > Also thank you @bew for pointing out the error :)
> 
> You're welcome! I'm actually not using LuaSnip yet 👀, I'm still on Ultisnips (with its quirks and crashes.....) and was procrastinating the migration of all my custom snippets to the node system of this plugin which seamed less readable at first glance...
> But since this change I see I can write the snippets in a readable manner, as lsp snippets are similar to Ultisnips's (and only use advanced nodes for specific usecases), so I'm happy 😃
> I think I'll migrate soon (or on next Ultisnips unexpected crash... which can be _very_ soon...)

Come on over, it's nice here :P
> 
> 👉 NOTE: The `parse_snippet` is a good selling point, and I think it should be better advertised in the main readme and the examples, the node system is incredible but can be less readable for _simple_/_not-advanced_ snippets, don't you think?

You're right, it's currently only a subpoint in features. Maybe it'd be nice to put it into drawbacks as well, propose a solution next to the problem

**Comment by L3MON4D3** [comment]
> (maybe move to another issue? we're going completely offtopic here)

Probably best, I'll actually close this one, it should be fixed now :D
