### ISSUE TITLE
Support for compound filetypes

### ISSUE THREAD

**Issue by wincent** [L3MON4D3/LuaSnip#142]
This is something that UltiSnips offers when working with compound or "dotted" filetypes (eg. `foo.bar`; see `:h 'filetype'`).

Most usefully, [it does this](https://github.com/SirVer/ultisnips/blob/53e1921e3ef015ef658e540c0aa9c4835f9c18a6/doc/UltiSnips.txt#L581-L584):

> UltiSnips understands Vim's dotted filetype syntax. For example, if you define a dotted filetype for the CUDA C++ framework, e.g. `:set ft=cuda.cpp`, then UltiSnips will search for and activate snippets for both the cuda and cpp filetypes.

A common use case for this is to have snippets for your "main" language (say, `typescript`) and then define additional specific snippets for test files (using a filetype of, say, `jest`); the test files have a `'filetype'` of `typescript.jest` and so get both kinds of snippets, but non-test files just get the `typescript` ones. Similar analogies exist for other languages (eg. for `ruby` you might use RSpec for tests and so add `spec` to your `filetype` — ie. `ruby.spec` — so that you can get test-specific snippets there).

Perhaps a little less usefully, it also allows you to [explicitly merge filetypes](https://github.com/SirVer/ultisnips/blob/53e1921e3ef015ef658e540c0aa9c4835f9c18a6/doc/UltiSnips.txt#L216-L239):

> The UltiSnipsAddFiletypes command allows for explicit merging of other snippet filetypes for the current buffer. For example, if you edit a .rst file but also want the Lua snippets to be available you can issue the command
>
> ```
> :UltiSnipsAddFiletypes rst.lua
> ```

I personally haven't used that second feature at all, but I used the first feature quite a bit.

Anyway, not sure if this is possible with LuaSnip right now so just wanted to pop this in as a feature request (or perhaps it already is possible and could be added to the docs?).

**Comment by L3MON4D3** [comment]
Ouh I think right now dotted filetypes actually break luasnip a bit (we assume that there's only one filetype in `ft`, no dots), so no snippets from any filetype except global ones.
I'll change it to correctly split `ft`

**Comment by L3MON4D3** [comment]
(missclick :|)

**Comment by leiserfg** [comment]
@L3MON4D3  my pr is more complete (I also fixed it for the vscode lazy  loading)

**Comment by wincent** [comment]
Thank you both, @L3MON4D3 @leiserfg!

**Comment by shellRaining** [comment]
Very offensive, but may I ask where can I find the relevant configuration information? I am using jest and want to separately configure code snippets for files like `*.spec.ts`. However, besides this issue, I haven't seen any other information.

**Comment by leiserfg** [comment]
@shellRaining  we use the file type and not the file extension to find the set of snippets to use. So you have to use `vim.filetype.add` to make nvim  to assign a custom filetype to those  (or an autocmd).

**Comment by shellRaining** [comment]
@leiserfg I have set the filetype of `*.spec.ts` by using code below
```lua
ft.add({
    pattern = {
        [".*.spec.ts"] = "jest",
    },
})
```
and it print the expected filetype `jest`, however, the code not highlight as `typescript` file, then I search for config mult filetype for one file, and no useful information, may I ask for some solutions about how to setup snippets for `*.spec.ts` while treat this file as a normal `ts` file (and it's better that the test snippets not load in a normal ts file)

**Comment by leiserfg** [comment]
try with 
```lua
ft.add({
    pattern = {
        [".*.spec.ts"] = "jest.typescript",
    },
})
```

**Comment by shellRaining** [comment]
@leiserfg thank you, the high light does work now, but snippet still not work properly, when use `OpenUserSnippetFile` cmd, Neovim open the `jest.typescript.json` in my snippets project, and I set the `package.json` below

```json
{
  "path": "./jest.typescript.json",
  "language": [
    "spec.ts",
    "spec.js",
    "jest.javascript",
    "jest.typescript"
  ]
},
```
I'm sure that the snippets is correct, because when et the `language` to "typescript", this work as expected

**Comment by leiserfg** [comment]
It seems like there was a change, on one of the rewrites that partially broke this, in the past  it worked  as you have it currently configured.  Now it should work fine if you set the language in the json  list `languages` to be  `spec` only.

**Comment by leiserfg** [comment]
In short:
```lua
ft.add({
    pattern = {
        [".*.spec.ts"] = "jest.typescript",
    },
})
```
plus 

```json
{
  "path": "./jest.typescript.json",
  "language": [
    "spec",
  ]
},
```

**Comment by leiserfg** [comment]
Which is technically matching the way nvim behaves as it see ft with dots not as more specific ft but as having several ft in the same file.

**Comment by shellRaining** [comment]
still not work after set the `language` to `spec`😢. The relevant configurations are in this commit https://github.com/shellRaining/nvim/commit/db37ddbf47f2579716aacf102b5f31374f865f53.

**Comment by L3MON4D3** [comment]
Shouldn't the language in the `package.json` be `jest`? Or did you want to account for `ft.add` being run after the `load/lazy_load`?

**Comment by shellRaining** [comment]
@L3MON4D3  thank you very much!!! work properly 😄

**Comment by leiserfg** [comment]
> Shouldn't the language in the `package.json` be `jest`? Or did you want to account for `ft.add` being run after the `load/lazy_load`?

Sure, I had a Lapsus mentis.
