### ISSUE TITLE
Question: How to choose a snippet from choice node?

### ISSUE THREAD

**Issue by ahmedelgabri** [L3MON4D3/LuaSnip#145]
This is a silly question, but I can't figure out how to choose a snippet using a choice node.

```lua
    s(
      'trig',
      c(1, {
        t 'Ugh boring, a text node',
        i(nil, 'At least I can edit something now...'),
        f(function(args)
          return 'Still only counts as text!!'
        end, {}),
      })
    ),
    s(
      { trig = 'bang', dscr = 'Shebang!' },
      t '#!/usr/bin/env ',
      c(1, {
        t 'sh',
        t 'zsh',
        t 'bash',
        t 'python',
        t 'node',
      }),
      i(0)
    ),
```

**Comment by L3MON4D3** [comment]
You'll have to map `<Plug>luasnip-next-choice`, check the mapping-part in the README :D

**Comment by ahmedelgabri** [comment]
Thanks!

It's so hidden that I totally missed it although I read it multiple times 🤦🏼‍♂️  I suggest to make the sections more prominent with bigger headers or so

---

## Mappings

<details>
…
</details>

```md
## Mappings

<details>
…
</details>
```

**Comment by ahmedelgabri** [comment]
I still can't get it to work even after setting up mappings. I'm using `nvim-cmp` & set up the mappings as it says here https://github.com/hrsh7th/nvim-cmp#how-to-setup-supertab-like-mapping yet I can't really get the choice snippet to work…

**Comment by L3MON4D3** [comment]
Oh, but you have those mappings and the ones from the Readme, with `<Plug>luasnip-next-choice`? Also make sure to define all mappings for select and insert mode
