### ISSUE TITLE
How to make a snippet trigger/available only if some condition is met?

### ISSUE THREAD

**Issue by IndianBoy42** [L3MON4D3/LuaSnip#147]
I want to make some snippets for latex that only trigger in math mode. vimtex provides the function to determine whether we are in a math mode environment, but how can I make the snippet trigger conditional on this function?

**Comment by gegoune** [comment]
I would love that feature to limit some snippets to beginning of lines. I think I opened an issue about it while back.

**Comment by leiserfg** [comment]
In https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets  check the `condition` argument.

**Comment by IndianBoy42** [comment]
Is it possible to have 2 snippets with mutually exclusive triggers conditions? I seem to be having trouble with it. for some pairs of snippets it works but for others it doesnt, one or the other will not activate depending on the order that I put them in the table

**Comment by IndianBoy42** [comment]
Wait, sorry this was just an issue with how I was building the autosnippets list, I thought we could use `unpack` to splice a list into another list but we cant
