### ISSUE TITLE
Bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Shatur95** [L3MON4D3/LuaSnip#15]
I have this error with the following configuration:

```lua
vim.api.nvim_set_keymap('i', '<Tab>', 'luasnip#expand_or_jumpable() ? "<Plug>luasnip-expand-or-jump" : "<Tab>"', { expr = true, silent = true })
vim.api.nvim_set_keymap('i', '<S-Tab>', [[luaeval('require("luasnip").jump(-1)')]], { noremap = true, expr = true, silent = true })
vim.api.nvim_set_keymap('i', '<C-e>', 'luasnip#choice_active() ? "<Plug>luasnip-next-choice" : "<C-E>"', { expr = true, silent = true })
vim.api.nvim_set_keymap('s', '<Tab>', [[luaeval('require("luasnip").jump(1)')]], { noremap = true, expr = true, silent = true })
vim.api.nvim_set_keymap('s', '<S-Tab>', [[luaeval('require("luasnip").jump(-1)')]], { noremap = true, expr = true, silent = true })
```

Even if I just call the following in cmd:

```lua
echo luasnip#expand_or_jumpable()
```

**Comment by L3MON4D3** [comment]
Could you show more of your config? If this is all, take a look at `Examples/snippets.lua` on how to define Snippets (`require'luasnip'.snippets`-table)

**Comment by Shatur95** [comment]
Sorry, I forgot to clarify. I get this error whenever I press Tab. But I don't have any snippets.

**Comment by L3MON4D3** [comment]
Ah okay, I think Luasnip doesn't even check whether the snippets-table exists, it just assumes it does and then obviously errors :grimacing:. Could you add `require'luasnip'.snippets={all={}}`? That should fix the issue until I add some checks or defaults so that not setting `snippets` doesn't lead to errors.

**Comment by Shatur95** [comment]
It worked, thanks!
