### ISSUE TITLE
Bug (Or improvement): Conditional function which isn't available yet causes error

### ISSUE THREAD

**Issue by sandersantema** [L3MON4D3/LuaSnip#154]
I'm using the `vimtex#syntax#in_mathzone()` from [here](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/syntax.vim) as a conditional to trigger certain autosnippets for example:

```lua
local function is_math()
  return vim.fn["vimtex#syntax#in_mathzone"]()
end

ls.autosnippets = {
  tex = {
    s("neqq", {
      t("\\neq"),
      i(0),
    }, is_math()),
  },
}
```

But the plugin which provides the function (namely vimtex) is lazy loaded and only available after opening a `.tex` file. Luasnip itself is lazily loaded in my config too and is loaded on entering insert mode after which it shows the following error once on every startup when entering insert mode for the first time:
```
packer.nvim: Error running config for LuaSnip: Vim:E117: Unknown function: vimtex#syntax#in_mathzone
```
The config file mentioned here is more complete version of the code snippet above. 

After this error everything works fine, but I'd obviously rather not have the error or load vimtex when not editing latex files.

**Comment by leiserfg** [comment]
Sorry but that's not an error, that's your conditional, so you have to handle the errors in it yourself, a `pcall` there should help.

**Comment by L3MON4D3** [comment]
```lua
ls.autosnippets = {
  tex = {
    s("neqq", {
      t("\\neq"),
      i(0),
    -- no call!!!!
    }, is_math),
  },
}
```

Btw, we switched from that syntax some time ago, if you're on the newest master you'll need to do 
```lua
ls.autosnippets = {
  tex = {
    s("neqq", {
      t("\\neq"),
      i(0),
    }, {condition = is_math}),
  },
}
```

**Comment by sandersantema** [comment]
Of course the function call! Thank you very much for the quick response all is good now :) I'm looking forward to enjoying the benefits of this amazing snippets plugin after getting to grips with it. Thank you for all the work!

Fyi: I saw some other
