### ISSUE TITLE
No snippets available when editing Python

### ISSUE THREAD

**Issue by d-miketa** [L3MON4D3/LuaSnip#155]
I'm not sure why, but no snippets load at all when editing Python files, as checked by `:LuaSnipListAvailable`:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/320321/132596693-8df75a8b-86c4-4276-9209-030e091d63d2.png">

My config files are here (though edited down for readability):
https://gist.github.com/d-miketa/8ad89b4e369fc0348a614de0ba37307f

**Comment by leiserfg** [comment]
Remove the after="nord.vim" part,  I tested your config without that and it works fine.

**Comment by d-miketa** [comment]
Embarrassing, that fixed it – thank you! One day I'll understand the ins and outs of lazy loading...
