### ISSUE TITLE
refresh snippets?

### ISSUE THREAD

**Issue by ExpandingMan** [L3MON4D3/LuaSnip#156]
There's probably already a way of doing this, but I can't seem to figure it out: is there a way to refresh the snippets defined in directories that have been added with `luasnip.loaders.from_vscode` without restarting neovim?

**Comment by leiserfg** [comment]
Not easily, as there is not an identifier for luasnip to be sure the snippet was not loaded already, the trigger of the snippet is not necessarily unique.

**Comment by L3MON4D3** [comment]
Jup, automatically it won't work. If you want to reload eg. all snippets you could `:lua require("luasnip").snippets={}`(removes all snippets) followed by whichever `load()` you use (if you have snippets defined in lua, you'll also have to `:luafile your_snippet_file.lua`).

**Comment by ExpandingMan** [comment]
Yeah, I wasn't looking for automatic, that seems excessive.  I'll create a function for it, that'll be fine with me.

Would be a nice convenience feature if you ever feel like adding it, otherwise, feel free to close.

**Comment by leiserfg** [comment]
The thing is that reloading does not work well with async_loading but well if loading all the snippets at once is fine for you, that's the way to go.

**Comment by L3MON4D3** [comment]
It's pretty hard to reliably reload the snippets, we would have to store where they originated and then replace them one by one or something, would probably be too much effort to really get right, srry.
But we probably should put how to reload snippets in the docs/wiki.

**Comment by leiserfg** [comment]
I can add a funciton to clean-up the cache as well so reloading is possible, today I'm traveling so I don't think I will have time to do so. But this week I will.

**Comment by L3MON4D3** [comment]
Cleaning should work reliably (also with lazy-loading) thanks to @leiserfg s' #165. Calling `luasnip.cleanup()` instead of doing `luasnip.snippets = {}` is the recommended way of cleaning snippets from now on.

**Comment by danielo515** [comment]
Sorry for comment in an old issue, but, what's the current way of reloading snippets? I'm talking about all kinds of snippets, lua, snipmate and json.
Is it necessary to create a clean function? Can't this be created as a command of luasnip you can call manually?

**Comment by L3MON4D3** [comment]
Reloading is currently supported for the lua-loader (eg. snippets are automatically updated on `BufWritePost` from some file that contributes snippets)
I'm currently working on #409 which adds the same functionality for snipmate+vscode-loader, so very soon reload should just work (as long as you're using the loaders instead of direct `add_snippets`) :D

**Comment by danielo515** [comment]
I'm using the lazy_loaders. Will that make a difference?

**Comment by L3MON4D3** [comment]
Nope, it shouldn't
