### ISSUE TITLE
Share a working default config please

### ISSUE THREAD

**Issue by vinoff** [L3MON4D3/LuaSnip#157]
I am trying to make luasnip + snippets + cmp + tab-like-supertab working but I am just at the end of my patience. This is so utterly confusing, god damn it.

This is not a jab at any of you, it is me. I am an idiot. Having said that, I would like to make this work, so:

Can anyone share a working config for LuaSnip? The README is not very helpful to me.

**Comment by L3MON4D3** [comment]
Sorry to hear that, definitely been there myself :/
Does [this](https://github.com/hrsh7th/nvim-cmp/issues/180#issuecomment-915385367) +
```lua
-- load snippets from runtimepath, eg. friendly-snippets.
require("luasnip.loaders.from_vscode").load()
```
work?
If not, maybe try disabling other plugins.

**Comment by vinoff** [comment]
Ah yes, that does indeed work. Thank you!
