### ISSUE TITLE
<S-Tab> inserts "false"

### ISSUE THREAD

**Issue by Shatur95** [L3MON4D3/LuaSnip#16]
If I use `<S-Tab>` when no snippets are active, then false is inserted.
Is there a way to check if snippet is available instead of just using `jump(-1)`?

My configuration (as in README, but in lua):

```lua
vim.api.nvim_set_keymap('i', '<S-Tab>', [[luaeval('require("luasnip").jump(-1)')]], { noremap = true, expr = true, silent = true })
vim.api.nvim_set_keymap('s', '<S-Tab>', [[luaeval('require("luasnip").jump(-1)')]], { noremap = true, expr = true, silent = true })
```

**Comment by Shatur95** [comment]
I also tried the following:

utils/completion.lua:

```lua
function M.tab_complete()
  if vim.fn.pumvisible() == 1 then
    return vim.api.nvim_replace_termcodes('<Down>', true, true, true)
  elseif require('luasnip').expand_or_jumpable() == 1 then
    return vim.api.nvim_replace_termcodes('<Plug>(luasnip-expand-or-jump)', true, true, true)
  else
    return vim.api.nvim_replace_termcodes('<Tab>', true, true, true)
  end
end

function M.s_tab_complete()
  if vim.fn.pumvisible() == 1 then
    return vim.api.nvim_replace_termcodes('<Up>', true, true, true)
  elseif require('luasnip').jumpable() == 1 then
    return vim.api.nvim_replace_termcodes('<Plug>(luasnip-expand-or-jump)', true, true, true)
  else
    return vim.api.nvim_replace_termcodes('<S-Tab>', true, true, true)
  end
end
```

init.lua:

```lua
vim.api.nvim_set_keymap('i', '<Tab>', [[luaeval('require("utils.completion").tab_complete()')]], { expr = true })
vim.api.nvim_set_keymap('i', '<S-Tab>', [[luaeval('require("utils.completion").s_tab_complete()')]], { noremap = true, expr = true })
vim.api.nvim_set_keymap('s', '<Tab>', [[luaeval('require("utils.completion").tab_complete()')]], { expr = true })
vim.api.nvim_set_keymap('s', '<S-Tab>', [[luaeval('require("utils.completion").s_tab_complete()')]], { noremap = true, expr = true })
```

With this configuration everything works as expected except snippet expansion :(

**Comment by L3MON4D3** [comment]
Try changing `require('luasnip').expand_or_jumpable() == 1` to just `require('luasnip').expand_or_jumpable()`, it returns a boolean IIRC

**Comment by Shatur95** [comment]
@L3MON4D3, thanks! But now it just inserts `<Plug>(luasnip-expand-or-jump)` instead of snippet expansion...

**Comment by L3MON4D3** [comment]
Ah ofc, `<Plug>luasnip-expand-or-jump` instead of `<Plug>(luasnip-expand-or-jump)` should fix that

**Comment by Shatur95** [comment]
Thank you! Probably it worth to mention `compe` integration configuration in `README.md`.

**Comment by L3MON4D3** [comment]
Great! 
I'll look into that, but there isn't much to configure, I think just setting `luasnip=true` in sources is all.

**Comment by Shatur95** [comment]
@L3MON4D3, sorry, I meant not integration with `compe` exactly, only tab completion [like in compe](https://github.com/hrsh7th/nvim-compe#how-to-use-tab-to-navigate-completion-menu).

**Comment by L3MON4D3** [comment]
Ahh I see what you mean, adding it wouldn't hurt I guess, thanks for the suggestion :D
