### ISSUE TITLE
Feature request: link insert nodes with the same index

### ISSUE THREAD

**Issue by figsoda** [L3MON4D3/LuaSnip#160]
link insert nodes with the same index and update all other instances when one is updated, probably possible with function nodes but i wasn't able to make it work

choice nodes can be linked as well, not important to me but could be useful

**Comment by L3MON4D3** [comment]
You can use a [repeatNode](https://github.com/L3MON4D3/LuaSnip/blob/9748870f69236db39cc8eeb668d944bbe496634e/Examples/snippets.lua#L288), it was added specifically for repeating content of an insert or choiceNode.
Having repeated insertNodes automatically repeat the text of the first isn't really necessary if function, and specifically repeatNodes, exist.

**Comment by tom-anders** [comment]
Hi, just wanted to note that this is not yet documented in `luasnip.txt`

**Comment by L3MON4D3** [comment]
Oh, you're right, this (actually, all nodes in `luasnip.extras`) should be documented.
I'll add some recommendations on their usage, ty!
