### ISSUE TITLE
Issues with lsp_signature

### ISSUE THREAD

**Issue by Trid-collab** [L3MON4D3/LuaSnip#163]
I am using nvim cmp, along luasnip, cmp_luasnip ,autopairs  and lsp_signture and neovim nightly or novim (0.5) 
I have noticed that I am getting the following behaviour. The auto signature does'nt seem to work 

![image](https://user-images.githubusercontent.com/61322708/132945771-d30bd233-38b3-4674-83ef-1ca198e3f42f.png)

My cmp config 

vim.o.completeopt = "menu,menuone,noselect"
-- luasnip setup
local luasnip = require("luasnip")
-- lspkind setup
local lspkind = require("lspkind")
-- nvim-cmp setup
local cmp = require("cmp")
cmp.setup({
	completion = {
		completeopt = "menu,menuone,noselect",
	},
	snippet = {
		expand = function(args)
			require("luasnip").lsp_expand(args.body)
		end,
	},
	mapping = {
		["<C-p>"] = cmp.mapping.select_prev_item(),
		["<C-n>"] = cmp.mapping.select_next_item(),
		["<C-d>"] = cmp.mapping.scroll_docs(-4),
		["<C-f>"] = cmp.mapping.scroll_docs(4),
		["<C-Space>"] = cmp.mapping.complete(),
		["<C-e>"] = cmp.mapping.close(),
		["<CR>"] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Replace,
			select = true,
		}),
		["<Tab>"] = function(fallback)
			if vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<C-n>", true, true, true), "n")
			elseif luasnip.expand_or_jumpable() then
				vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
			else
				fallback()
			end
		end,
		["<S-Tab>"] = function(fallback)
			if vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<C-p>", true, true, true), "n")
			elseif luasnip.jumpable(-1) then
				vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
			else
				fallback()
			end
		end,
	},
	documentation = {
		border = { "", "", "", " ", "", "", "", " " }, -- the border option is the same as `|help nvim_open_win|`
		winhighlight = "NormalFloat:CompeDocumentation,FloatBorder:CompeDocumentationBorder",
		max_width = 120,
		min_width = 60,
		max_height = math.floor(vim.o.lines * 0.3),
		min_height = 1,
	},
	formatting = {
		format = function(entry, vim_item)
			-- fancy icons and a name of kind
			vim_item.kind = require("lspkind").presets.default[vim_item.kind] .. " " .. vim_item.kind
			-- set a name for each source
			vim_item.menu = ({
				buffer = "[Buffer]",
				nvim_lsp = "[LSP]",
				luasnip = "[LuaSnip]",
				nvim_lua = "[Lua]",
				-- latex_symbols = "[Latex]",
			})[entry.source.name]
			return vim_item
		end,
	},
	sources = {
		{ name = "nvim_lsp" },
		{ name = "luasnip" },
		{ name = "path" },
		{ name = "buffer" },
		{ name = "calc" },
		{ name = "nvim_lua" },
	},
})
-- you need setup cmp first put this after cmp.setup()
require("nvim-autopairs.completion.cmp").setup({
	map_cr = true, --  map <CR> on insert mode
	map_complete = true, -- it will auto insert `(` after select function or method item
	auto_select = true, -- automatically select the first item
})

and my luanip file had 

`local present, luasnip = pcall(require, "luasnip")
if not present then
	return
end

luasnip.config.set_config({
	history = true,
	updateevents = "TextChanged,TextChangedI",
})
require("luasnip/loaders/from_vscode").load()

found out that if I remove the `require("luasnip/loaders/from_vscode").load()` from my luasnip config
the the signature works , but then I don't get the luasnip options.

Any indicators what may I have been  missing.

**Comment by L3MON4D3** [comment]
Hmm, what if you load the snippets, but don't enable the Luasnip source for cmp?

**Comment by Trid-collab** [comment]
Have tried that removing luasnip from the cmp source resolves the problem - the signature is visible but the Luasnips options are no longer available in the completion menu. 

I have also opened an issue with lsp_signature 
https://github.com/ray-x/lsp_signature.nvim/issues/93

**Comment by L3MON4D3** [comment]
How's it looking, does it work correctly after the patches to `lsp_signature`?

**Comment by Trid-collab** [comment]
It's more of a workaround. It would be better if the snippets could be suppressed when we are in the signature brackets -like it was before when I was using compe or "hrsh7th/vim-vsnip"

![image](https://user-images.githubusercontent.com/61322708/133374130-1f6d0d14-9a60-4518-808b-04121aadf0ea.png)

**Comment by L3MON4D3** [comment]
Ouh okay, I think that's something that should be discussed and fixed in nvim-cmp(it's the completion popup that's out of place, yes?) I think, that would fix it for all sources, not just luasnip_cmp
