### ISSUE TITLE
attempt to call field 'get_snippets_filetypes'

### ISSUE THREAD

**Issue by siduck76** [L3MON4D3/LuaSnip#164]
Hi there! luasnip was working fine yesterday but today it doesnt , I updated it  and I get this error when in insertmode : 

![image](https://user-images.githubusercontent.com/59060246/132981284-f4fed58b-d798-4222-af09-43503e7d14c3.png)

**Comment by keybits** [comment]
Confirming that I have the same issue (using LunarVim).

**Comment by L3MON4D3** [comment]
Could you try updating again? It was broken for a short while yesterday, but it should work now

**Comment by keybits** [comment]
Thanks for the quick reply! Just did another update, and all working fine now.

**Comment by siduck76** [comment]
no the update didnt fix it . My config : 

```
  local luasnip = require, "luasnip"

   luasnip.config.set_config {
      history = true,
      updateevents = "TextChanged,TextChangedI",
   }
   require("luasnip/loaders/from_vscode").load()
   ```

**Comment by L3MON4D3** [comment]
Do you do some conditional/lazy loading with eg. packer?

**Comment by siduck76** [comment]
> Do you do some conditional/lazy loading with eg. packer?

yes I load this after nvim-cmp . nvim-cmp loads at insertEnter event

**Comment by L3MON4D3** [comment]
Ah okay, try loading `luasnip` and `luasnip_cmp` before `nvim_cmp`, that should work. (although I wonder why it worked before)

**Comment by siduck76** [comment]
> Ah okay, try loading `luasnip` and `luasnip_cmp` before `nvim_cmp`, that should work. (although I wonder why it worked before these changes)

nvm my luasnip wasnt updating before ( it showed this : failed to update luasnip) , reinstalled the plugin and works now! Sorry for all the trouble caused
