### ISSUE TITLE
is LuaSnip  to be  deprecated after nvim-compe

### ISSUE THREAD

**Issue by ayoubelmhamdi** [L3MON4D3/LuaSnip#168]
- `nvim-compe` is now deprecated,  it's `LuaSnip` go to be `cmp_luasnip`?
- what is better and fast `cmp_luasnip` or `LuaSnip`
- are  `cmp_luasnip`  is official and trusted for a future update

**Comment by leiserfg** [comment]
cmp_luasnip is just a  provider for  cmp, not a LuaSnip replacement.

**Comment by L3MON4D3** [comment]
`cmp_luasnip` is also official/trusted, we link to it in the README :P
