### ISSUE TITLE
How to prevent jumping out of snippet when jumping-next-prev ?

### ISSUE THREAD

**Issue by vatosarmat** [L3MON4D3/LuaSnip#170]
Hello and thank you for the great plugin. I have only one small question about one particular behavior which sometimes annoys me a little bit.

Cursor moves out of snippet If place it on the right-most placeholder and do `jump(1)`. Same happens if place it on the left-most placeholder and do `jump(-1)`. Is it possible to prevent this behavior or get cursor back into snippet? Maybe `jumpable(1)` should return `false` when on right-most placeholder and `jumpable(-1)` should return `false`  when on left-most? Currently they return `true` thus there is no way to check if current cursor position is left-most or right-most.

**Comment by L3MON4D3** [comment]
Getting the cursor back into the snippet is easily doable by setting `history=true` in `setup()`.
Is that enough to get your preferred behaviour?

**Comment by bew** [comment]
I'd be interested as well, to not have history enabled but still block the jump when at the beginning / end of the snippet (which is not possible currently from what I read here).

**Comment by vatosarmat** [comment]
History is nice but it is not always desirable because sometimes it causes jumping all over the source file while you want only jump between placeholders of the snippet currently being entered. 
Is it possible to check if current placeholder is right-most or left-most and prevent jumping out? Or which source code locations should I consider if I would like to implement this locally for myself?

**Comment by L3MON4D3** [comment]
Against jumping all over the place: you can enable `region_check_events`, setting that to a fitting event should work(checks cursor position against that of the current snippet, jumps to the end if outside).
As it is currently, blocking the jumps to the `i(0)` and the one before the snippet wouldnt work really well, for example with nested snippets(expanding a snippet in another's insertNode), you wouldn't be able to get back into the outer one.
What exactly is the problem you'd solve this way?
