### ISSUE TITLE
Cannot use variable transform in vscode style snippet

### ISSUE THREAD

**Issue by jackysee** [L3MON4D3/LuaSnip#171]
For example, a vscode snippet like:
``` 
"test": {
    "prefix": "test",
    "body": "${TM_FILENAME/(.*)/${1:/upcase}/}"
  }
```
should result in current file name all in uppercase as said in https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms

**Comment by leiserfg** [comment]
That's a known issue, lsp snippets transformations will require an ecmascript regex implementation, so no short term plans. You'll have to use a Lua snippet till then.
