### ISSUE TITLE
Autotrigger for JSON snippets

### ISSUE THREAD

**Issue by lambtho12** [L3MON4D3/LuaSnip#172]
I may be wrong, but I do not think that it is currently possible to have auto triggering snippets for the ones defined in JSON and loaded with something like this:
```lua 
require("luasnip/loaders/from_vscode").lazy_load({ paths = { '~/.config/nvim/snippets' } })
```

I would be cool if we could specify an extra field in the JSON file (_e.g._ `autotrigger`) so the snippets get added to `ls.autosnippets` instead of `ls.snippets`. 

I am not overly competent in lua, but I think that just checking if `autotrigger = true` and deciding if the snippet needs to be added to the `ls.snippet` or `ls/autosnippet` should be enough ([here](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/loaders/from_vscode.lua#L84-L93)) (I tried to do it on my own and make a PR, but after 2 hours, I stand defeated).

**Comment by lambtho12** [comment]
Also I saw that the function `available` in [init.lua](https://github.com/L3MON4D3/LuaSnip/blob/ef5dd27579eca38456a8a9ad10fc0b47fee39ea6/lua/luasnip/init.lua#L49-L61) does not have `ls.autosnippets` in it. Not sure if that is normal.

**Comment by L3MON4D3** [comment]
We could probably change `opts` in `(lazy_)load(opts)` to include a `snippet_table`-key(default `ls.snippets`), into which the snippets will be inserted, that should do it.

**Comment by lambtho12** [comment]
Wouldn't that make all snippets loaded to be autotriggered?


<details> 
  <summary>Example of what I had in mind for the JSON file </summary>
```json
{
  "test1": {
    "prefix": "test_autotrig",
    "body": [
      "This should autotrig",
    ],
    "description": "autotrig",
    "autotrigger": true
  },
  "test2": {
    "prefix": "test_regular",
    "body": [
      "This should not autotrig",
    ],
    "description": "regular",
    "autotrigger": false
  },
  "test3": {
    "prefix": "test_regular",
    "body": [
      "This should not autotrig (default when no autotrigger field is there)",
    ],
    "description": "regular 2",
  }
}
```
</details>

Ideally it would allow for all snippets (regular and autotriggered) to be in the same JSON file.

**Comment by lambtho12** [comment]
I do not see anything specific as for now, but this is a great idea to future-proof everything.

For instance, a nice function I liked in Ultisnips was also the ability to control precisely the triggering of the snippets (see [UltiSnips-snippet-options](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt). If similar options were to be added later down the road to luasnip, it may be preferable to have everything already available in the JSON within your proposed "namespace".

**Comment by L3MON4D3** [comment]
Oh, I thought you wanted to just load all latex snippets or something as autotriggered, adding a custom option is way better.

**Comment by L3MON4D3** [comment]
As for other options, I want to add some conditions to extras (stuff like `beginning of line` or a check if the cursor is inside some specified treesitter node, anything not too unusual) these could then also be made available to the json-snippets.

**Comment by leiserfg** [comment]
Well, I will be busy tonight (deployment night) but tomorrow I can implement that.

**Comment by L3MON4D3** [comment]
> Also I saw that the function `available` in [init.lua](https://github.com/L3MON4D3/LuaSnip/blob/ef5dd27579eca38456a8a9ad10fc0b47fee39ea6/lua/luasnip/init.lua#L49-L61) does not have `ls.autosnippets` in it. Not sure if that is normal.

And no, they should also be listed :sweat_smile:

**Comment by L3MON4D3** [comment]
> Well, I will be busy tonight (deployment night) but tomorrow I can implement that.

Cool Cool :ok_hand:
