### ISSUE TITLE
Luasnip next choice nil value

### ISSUE THREAD

**Issue by Nigh-ctrl** [L3MON4D3/LuaSnip#175]
while in a snippet with insert nodes, while pressing the key that i have assigned to that action, i get the following error message

`E5108: Error executing lua ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:194: attempt to index global 'Luasnip_active_choice_node' (a nil value)
`
this is my configuration https://github.com/Nigh-ctrl/nvim/blob/main/lua/config/luasnip.lua, keybindings are in a separate file but i don't think that's the problem because luasnip_active_choice_node should be global

how can i fix this error? i have done some research and can't seem to figure out how

**Comment by L3MON4D3** [comment]
Oh, the call will fail if there isn't actually an active choice. I'll make it not error, just do nothing or print some warning, until then you can map it conditionally(see README, the vim-mappings)

**Comment by Nigh-ctrl** [comment]
but there is an active choice, for example writing placeholder-1_2_3 at the i(1) location, i pressing <Tab> get me this error, is this normal? i mean writing  placeholder-1_2_3 make i(1) the active choice right?

**Comment by L3MON4D3** [comment]
Oh, changing choices is different from just jumping through placeholders, could you post your mappings?

**Comment by Nigh-ctrl** [comment]
these are my bindings https://github.com/Nigh-ctrl/nvim/blob/main/lua/keybinds.lua
in my config of luasnip i require keybinds.luasnip so that i can have the mappings in one place but called in the right place, easier to organize. this is my luasnip config https://github.com/Nigh-ctrl/nvim/blob/main/lua/config/luasnip.lua

**Comment by L3MON4D3** [comment]
Does jumping through placeholders with `<Tab>` work?

**Comment by L3MON4D3** [comment]
Oh no, of course it doesn't, you'll have to actually map the `_G.tab_complete` and `_G. s_tab_complete`, check the Vimscript-mappings in the Readme on how to do that

**Comment by Nigh-ctrl** [comment]
oh yeah that actually worked, don't know why i chose to use <Plug>luasnip-next-choice over the v:lua.tab_complete()
thanks a lot for the help it's cool ;)
