### ISSUE TITLE
Expanding snippets sometimes skips space

### ISSUE THREAD

**Issue by premell** [L3MON4D3/LuaSnip#176]
In some snippets, certain spaces are ignored. For example this snippet in react, shows the correct expansion in the window, however when expanding it it removes the space between "export" and "default"

![image](https://user-images.githubusercontent.com/65544203/133886695-87c7877c-fb54-4faf-8849-271824e6825c.png)
![image](https://user-images.githubusercontent.com/65544203/133886698-5bb963b0-b6dd-466a-922e-d6f48e727669.png)

I found this issue **https://github.com/rafamadriz/friendly-snippets/issues/62** of the same problem in the friendly snippets repo, and they said to make an issue here. However, from what I have found, the author of that issue haven't created an issue here yet, so I thought I would do so instead.

**Comment by premell** [comment]
This happens consistently when writing "export default ${TM_FILENAME_BASE}". I will do some more testing to see which variables contribute to this problem

**Comment by leiserfg** [comment]
Can you try to reproduce it with a minimal setup? As I see, the parser is doing it right (a text node with `"export default "` is created) and it's working fine to me.

**Comment by premell** [comment]
okay so I have tried some different configurations and the words "export default" seem to have no impact. Also there is no problem when either not using "\n" before or when using another variable than ${TM_FILENAME_BASE}. but when using the minimal example of "\nhello hello ${TM_FILENAME_BASE}" the problem occurs. Putting a space between "\n" and hello doesnt fix the issue

**Comment by leiserfg** [comment]
@L3MON4D3  it's an issue with the parser,  `'\nhello hello ${TM_FILENAME_BASE}'` makes the text node to be  `hellohello` but  `'\nhello hello  ${TM_FILENAME_BASE}'`  (with an extra space) does not.

**Comment by premell** [comment]
where did you put the extra space? I cannot see a difference between your two examples. I have tried pretty much every combination of spaces and the problem still occurs

**Comment by leiserfg** [comment]
Before the `$`

**Comment by premell** [comment]
hmm not sure but it didnt show up in github 
![image](https://user-images.githubusercontent.com/65544203/133888376-4a3e1b87-3f82-41d9-ac4f-2a150ffceade.png)

That seems to have fixed it though! Not it creates two spaces after the "default export", but that is goes away with formatting anyway. Thank you!

**Comment by leiserfg** [comment]
The two spaces are there, no idea why github does not uses a monospace font.  Anyway, it's an issue in the parser so don't close the issue.

**Comment by premell** [comment]
sure, thanks again for the quick answers and help

**Comment by leiserfg** [comment]
@L3MON4D3  seems like this `gsub` is the culprit: 
https://github.com/L3MON4D3/LuaSnip/blob/3cfabd133832b529a83d8f860c00a674e47fb728/lua/luasnip/util/parser.lua#L93-L105

**Comment by L3MON4D3** [comment]
Oh, that case shouldn't even apply here, I'll fix it up in a bit
