### ISSUE TITLE
Expanding a snippet with blank lines while indented leaves whitespace

### ISSUE THREAD

**Issue by ZeroKnight** [L3MON4D3/LuaSnip#177]
Apologies for the awkward title; I think it's easier to explain with an example. Assuming the following snippet definition:

```lua
s('test', {
  t('blah blah blah'),
  t({'', '', ''}),  -- Should be an empty line, but contains whitespace to indent level
  i(1, 'foo bar baz'),
  t({'', '', ''}),  -- Should be an empty line, but contains whitespace to indent level
  t('blah blah blah'),
}),
```

And the following text in a buffer, where `|` is the cursor position:
```lua
local foo_table = {
  bar = {
    test|
  }
}
```

The snippet at the cursor position expands into the following, where `∙` represents a trailing space:
```lua
local foo_table = {
  bar = {
    blah blah blah
∙∙∙∙
    foo bar baz
∙∙∙∙
    blah blah blah
  }
}
```

As you can see, this adds unwanted whitespace to the buffer. This is a side effect of LuaSnip keeping the indent of the previous line, but it shouldn't do this for empty lines. Is this a bug, or is there are more correct way to insert a blank line that I'm missing?

I tried wrapping the `t({'', '', ''})` node in an indent snippet, but that causes the following line (`foo bar baz` in this case) to lose its indent level as well.

**Comment by L3MON4D3** [comment]
Ahh, of course, right now luasnip adds indent to all lines whereas we should except empty lines from that.
Thanks for opening this, I hadn't thought about that at all till now :+1:

**Comment by ZeroKnight** [comment]
Awesome, thanks for the fix!
