### ISSUE TITLE
Understanding the argument `args` passed to function in `func_node`

### ISSUE THREAD

**Issue by jonathf** [L3MON4D3/LuaSnip#178]
I've been using luasnip a couple of weeks now, and really happy with it. I use a lot of basic features and it works really great. But as I am moving towards the more advanced stuff I got stuck regarding the argument `args` that is passed to the function which is provided to `func_nodes`. The docs gives a few example of what it contains, but the full structure and what to expect is not easy to find.

For my own sake and other after me, could we update DOCS.md to include a better description of the structure of this argument? Or link to where it exists if it is already reated?

**Comment by L3MON4D3** [comment]
I added a short example for what the table will look like, is it clearer now?

**Comment by jonathf** [comment]
Thanks for the swift reply.

Okay, so if I understand correctly:
* Given `func_node(func, indices)`, `indices` indicate what should be contained in the `args` table. E.g. `indices={2, 1}  -->  args={<string from i(2)>, <string from i(1)>, <snippet>}`. Is that correct?
* If so, does that mean that reference to the snippet is always the last element and in general could be accessed as `args[#args]`?
* What do you mean by `<snippet>` here? Is this `ls.snippet` or `ls.snippet_node`?
* Where can I find the expected attribution list associated with `<snippet>`?

**Comment by L3MON4D3** [comment]
Yes to 1 and 2 :+1:
(2 may actually be subject to change, at least I'm toying with the idea of passing the snippet separately).

`<snippet>` is the actual (through expansion) instantiated snippet-object (`ls.snippet` is the constructor), see [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md?plain=1#L88) for some attributes that can be accessed. For functions+more attributes, check out the [source](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/nodes/snippet.lua), but everything not stated in the docs may change without warning so... be warned :D

**Comment by jonathf** [comment]
Thank you, this makes more sense now.

Yeah, I think perhaps having the snippet part is conceptually different from the text insertions. I support the suggestion.

And yes, I am already subscribing to #81. :)

**Comment by L3MON4D3** [comment]
Perfect :D
