### ISSUE TITLE
Python open or closing parenthesis same 3 snippets

### ISSUE THREAD

**Issue by argapost** [L3MON4D3/LuaSnip#179]
Hello!

When I open or close parenthesis in python I get the following 3 snippets no matter the function:

![image](https://user-images.githubusercontent.com/58076098/134467091-7b0d64c8-0bba-4ec8-aacb-9a23d5b054e1.png)

Can I disable them somehow? I use nvim-cmp. I don't think I had the same problem a couple of days ago.

Thank you in advance.

**Comment by L3MON4D3** [comment]
Ouh, difficult. I think, generally, optimizing completion is something better tackled in cmp_luasnip.
What could be done from luasnips' side is just removing the offending snippets altogether by iterating over `luasnip.snippets.python`, finding these snippets (via trigger/name) and setting them to `nil`.

**Comment by argapost** [comment]
Thanks for the answer. So I guess it's better to open an issue in cmp_luasnip which is responsible for the triggering? Because it doesn't make sense that these snippets are triggered whenever I close or open parenthesis.

I tried to delete it with your suggestion by setting nil the luasnip.snippets.python[66] but I get the following error:

`Error detected while processing CompleteChanged Autocommands for "*":                                                                                  
E5108: Error executing lua ...e/pack/packer/start/cmp_luasnip/lua/cmp_luasnip/init.lua:15: attempt to index local 'snip' (a nil value)`

I guess cmp and cmp_luasnip still know about the existence of the snippet and they cannot access it since it is nil.

**Comment by L3MON4D3** [comment]
Oooooh, yeah it probably errors because `cmp_luasnip` assumes that the table doesn't have holes (which is generally a fine assumption, you could probably move the following snippets up so the hole is filled).

In any case, best open an issue about it in `cmp_luasnip`, yes :+1: (going to close it here for now)
