### ISSUE TITLE
ext_opts: Disable passive when outside of snippet

### ISSUE THREAD

**Issue by jedrzejboczar** [L3MON4D3/LuaSnip#180]
I really like the idea of having an indicators for all the tabstops in a snippet as virtual text with the current one highlighted:
![ext_opts_virt_text](https://user-images.githubusercontent.com/16623787/134470764-e4452018-3b46-4f8a-8d2d-fe2bcd4dbd61.png)
with:
```lua
ext_opts = {
    [types.choiceNode] = {
        passive = { virt_text = {{'●', 'Comment'}}, },
        active = { virt_text = {{'●', 'GruvboxOrange'}}, },
    },
    [types.insertNode] = {
        passive = { virt_text = {{'●', 'Comment'}}, },
        active = { virt_text = {{'●', 'GruvboxBlue'}} },
    }
}
```
But with `history = true` the `passive` indicators persist even after leaving the snippet (and for all the snippets in the history). What would it take to provide something like `passive_inside_snippet` to apply the virtual text only to the passive nodes in the current snippet?

**Comment by L3MON4D3** [comment]
Ouh, that shouldn't be too hard.
I think extending the keys in the `passive`, `active` table by something like `snippet_passive` could be the best solution as it is the most flexible(if the highlight should stay even while outside the snippet it can be defined as `snippet_passive`(which would then extend to `passive`, if it is unspecified)).
What do you think?

**Comment by jedrzejboczar** [comment]
If I understand correctly `snippet_passive` would do what `passive` currently does, which would be a breaking change. But I believe most users would rather expect `passive` to have that "passive only inside a snippet" behaviour, so to me it sounds good :)

**Comment by L3MON4D3** [comment]
Perfect, I'll add it
