### ISSUE TITLE
Support for simple text transformations in vscode snippets

### ISSUE THREAD

**Issue by jceb** [L3MON4D3/LuaSnip#181]
Thank you for this great plugin!

Do you have plans to support simple text transformations in vscode snippets as documented here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples?

**Comment by leiserfg** [comment]
Not short-term, it depends on moving to a new snippet parser and adding an ECMAScript regex engine.

**Comment by L3MON4D3** [comment]
Definitely not short-term xD
If `jsregexp` is installed transformations will be applied from now on, there's a bit of an overview on that [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#transformations)

**Comment by mekanix** [comment]
I managed to compile `jsregexp` on my FreeBSD laptop but I don't know where to put resulting `jsregexp.so`. If it makes any difference, I'm using LunarVim. I had to compile it by hand because FreeBSD has a bit different defaults. Thank you!

**Comment by kmarius** [comment]
I don't know about LunarVim but with a standard configuration you can simply put it into `~/.config/nvim/lua`. You should also be able to place it in one of the directories shown by running `:lua print(package.cpath)` in nvim.
