### ISSUE TITLE
Support for nested placeholders in vscode

### ISSUE THREAD

**Issue by jceb** [L3MON4D3/LuaSnip#182]
Do you plan to add support for nested placeholders like `${1:another ${2:placeholder}}`, https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholders?

I can use the syntax but the focus of the first tabstop, `another ${2:placeholder}`, but before it. So text would be inserted before `another`, however I can jump to the second placeholder properly. My expectation would be if I change placeholder 1, placeholder 2 would be dropped/overwritten. If I leave placeholder 1 untouched, I'd jump to placeholder 2.

**Comment by L3MON4D3** [comment]
Whoops, pasted the wrong link

**Comment by L3MON4D3** [comment]
I've gone into some detail on why luasnip handles nested placeholders the way it does in #89.
The behaviour you'd like is implementable via `parser_nested_assembler`, it would require overriding `jump_into` of the generated snippet I think. I'll add an example on how to do it to the wiki.

**Comment by L3MON4D3** [comment]
I managed to pretty closely replicate vscodes behaviour, check see [here](https://github.com/L3MON4D3/LuaSnip/wiki/Nice-Configs#imitate-vscodes-behaviour-for-nested-placeholders)

**Comment by mawkler** [comment]
@L3MON4D3 I tried [your snippet with nested placeholders](https://github.com/L3MON4D3/LuaSnip/wiki/Nice-Configs#imitate-vscodes-behaviour-for-nested-placeholders) but I it doesn't seem to select the outermost placeholder, only the inner placeholders. Do you have the same behaviour? If not I'll try to create a minimal config, but [here's my full config for LuaSnip](https://github.com/mawkler/nvim/blob/master/lua/configs/luasnip.lua) if you're interested.

![Peek 2022-12-16 08-55](https://user-images.githubusercontent.com/15816726/208057356-c22faa3e-0327-44e6-9d3c-f8745372d54c.gif)

**Comment by mawkler** [comment]
@L3MON4D3 Oh, I didn't realize that I needed to add a custom parser for nested placeholders to work. How would I create the same nested snippet with LuaSnip's Lua API? I.e. this snippet:

```
"test: ${1: this is ${2:nested} ${3:text}} ${4:yay!}"
```

**Comment by L3MON4D3** [comment]
Just add the code in your first link to your luasnip-setup, that might do it (might also error xD I think there were some issues with it 😅)

**Comment by mawkler** [comment]
@L3MON4D3 What I meant is how I use LuaSnip's `s`/`sn`/`t`/`i`/`d`, etc. to create the nested LuaSnip snippet instead of a VSC\*\*e snippet 🙂

**Comment by L3MON4D3** [comment]
> How would I create the same nested snippet with LuaSnip's Lua API?

Something like

```lua
s("nested", {
	c(1, {
		sn(nil, {
			t" this is ", i(1, "nested"), t" ", i(2, "text")
		}),
		t""
	}),
	t" ", i(2, "yay")
})
```

But this does not include the highlight of the `${1:...}`, it is instead simulated with a choiceNode. You could adapt the wiki-entry to produce a snippet where that snippetNode is highlighted instead (it's not really considered in luasnip, we just have that bit of code in the wiki to produce the vscode-behaviour).
But I'd generally recommend the youtube-videos from the readme for getting into the basics, like how to utilize different kinds of nodes etc.

**Comment by mawkler** [comment]
Ok, thank you!
