### ISSUE TITLE
Literal } in placeholder

### ISSUE THREAD

**Issue by jceb** [L3MON4D3/LuaSnip#183]
I doesn't seem possible to have a literal `}` in a snippet's placeholder. They seem to end the placeholder prematurely.

E.g. snippet `"${1:{text}}"` would produce `{text}` but the closing `}` is not selected and wouldn't get changed when I modify the placeholder because the first `}` ended the snippet.

**Comment by L3MON4D3** [comment]
You can escape `}` via `\` (`"${1:{text\\}}"`)
