### ISSUE TITLE
Remember state of choice nodes during snippet expansion

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#184]
The small inconvenience is if I change some placeholders, than _choose_ (by accident or in order to find out what else is in there) everything what I changed is lost. I think it would be useful to be able to cycle back to the edited state of choice.

In https://github.com/L3MON4D3/LuaSnip/issues/89#issuecomment-907629633 you suggested to open an issue.

**Comment by L3MON4D3** [comment]
(didn't mean to mention this issue there)
Right, yeah I'll get onto that, shouldn't be too hard

**Comment by L3MON4D3** [comment]
584b9db adds it as the default behaviour (not optional for now, I can't think of a situation where the choice being lost is preferable)
