### ISSUE TITLE
[question] how do i add custom snippets for every language to my init.lua

### ISSUE THREAD

**Issue by alexzanderr** [L3MON4D3/LuaSnip#186]
hello
i've read your readme. but i dont understand how to add custom snippets

i have everything configured and `friendly-snippets` are working with `nvim-cmp`.

is there a setup function for this? to add custom snippets

**Comment by L3MON4D3** [comment]
Are you talking about snippets in lua or snippets in the vscode-format?
For lua, you can check [here](https://github.com/L3MON4D3/LuaSnip/blob/5b2c1dba655818d6d9724aaa945e397ae3d21b63/Examples/snippets.lua#L160), for vscode-snippets you best read the [docs](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vscode-snippets-loader).
