### ISSUE TITLE
partial in choice node

### ISSUE THREAD

**Issue by levouh** [L3MON4D3/LuaSnip#187]
The following:

```
local function get_prefix()
    return vim.fn.line(".")
end

s({ trig = "stmt", name = "stmt", dscr = "Statement" }, {
  t("res = self.stmt"),
  c(1, {
    t({ "_fetch(", "" }),
    t({ "_execute(", "" }),
    t({ "(", "" }),
  }),
  c(2, {
    t({ "    \"a\",", "" }),
    t({ "    \"b\",", "" }),
  }),
  t({ "    \"\"\"", "    " }),
  i(0),
  t({ "", "    \"\"\"", "" }),
  t(")"),
  c(3, {
    t(""),
    p(utils.get_prefix),
  }),
}),
```

works for the first two iterations of `<Plug>luasnip-next-choice`, but eventually results in:

```
E5108: Error executing lua ...te/pack/packer/opt/LuaSnip/lua/luasnip/nodes/snippet.lua:453: attempt to index local 'node' (a nil value)
```

after going through one "cycle" of the options from choice node `3`.

---

Side note; is there a better way to do something like:

```
c(3, {
  t(""),
  fmt("asdf {} fdsa", { p(get_prefix) })
})
```

where I am essentially saying:

>Choose between nothing, or a string which contains some dynamic formatted text

?

**Comment by L3MON4D3** [comment]
Oh wow, It's a very stupid error on my part that was introduced in 584b9db, no idea how I didn't notice it failing.
As for the choosing between some node and blank text, you could introduce a shorthand for that like so:
```lua
-- best use a shorter name :D
local function node_or_nothing(indx, node)
	return c(indx, {
		t(""),
		node
	})
end
```
that way you could turn
```lua
c(3, {
	t(""),
	p(utils.get_prefix),
}),
```

into

```lua
node_or_nothing(3, p(utils.get_prefix))
```

For the dynamically formatted text you can use either a functionNode or (maybe) a [lambdaNode](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua#L284)
