### ISSUE TITLE
a1580b62 breaks integration with compe

### ISSUE THREAD

**Issue by xiaket** [L3MON4D3/LuaSnip#188]
Reporting the issue here. I'm not too sure whether we should change it in compe or here.

```pack/packer/start/nvim-compe/lua/compe_luasnip/init.lua:65: attempt to index global 'Luasnip_current_nodes' (a nil value)```

**Comment by xiaket** [comment]
The commit is: https://github.com/L3MON4D3/LuaSnip/commit/a1580b62beaffad0d631219d1b14764b17ab63aa

**Comment by xiaket** [comment]
Meanwhile, I'm locking the version of luasnip locally as a workaround:

```
use {'L3MON4D3/LuaSnip', commit = "0349dccd"}
```

**Comment by saadparwaiz1** [comment]
`nvim-compe` has been deprecated in favour of `nvim-cmp`; you should switch to `nvim-cmp` as a workround you can do this in your config
```lua
Luasnip_current_nodes = require("luasnip").session.current_nodes
```

**Comment by L3MON4D3** [comment]
I'd support switching to `nvim-cmp`, it's just as usable and has a better source for luasnip :)
Going to close, looks like it's even fixed in compe as of now.
