### ISSUE TITLE
Not working with packer.nvim

### ISSUE THREAD

**Issue by carlitux** [L3MON4D3/LuaSnip#2]
when trying to autocomplete I get this

```
Error detected while processing function luasnip#expand_or_jumpable:
E5108: Error executing lua ...hare/nvim/site/pack/packer/start/LuaSnip/lua/luasnip.lua:12: attempt to index global 'ls' (a nil value)
```

edit. looks like is related to this https://stackoverflow.com/questions/52500913/lua-attempt-to-index-global-nil-value

**Comment by L3MON4D3** [comment]
Oh, yeah, I didn't declare ```ls``` locally before using it, probably missed it until now because it was globally somewhere in my own config. Anyway, please try if it works now :)

**Comment by carlitux** [comment]
Working, I love it.

**Comment by L3MON4D3** [comment]
Great!
