### ISSUE TITLE
[QUESTION] Recursive value-printing snippet

### ISSUE THREAD

**Issue by levouh** [L3MON4D3/LuaSnip#204]
Right now I have a snippet that basically just leaves me with something like:

```c
printf("DBGSTR => [filename:123] foo=%s\n", foo);
```

so I can leave breadcrumbs that have the filename, line number, etc. The snippet looks like:

```lua
  s({ trig = "loval", name = "log_value", dscr = "Log value" }, {
    t("printf(\""),
    p(utils.get_prefix),
    f(utils.copy, 1),
    t("=%s\\n\", "),
    i(1),
    t(");"),
  }),
```

where `utils.prefix` just returns a string that has the filename and line number, and `utils.copy` just copies the typed text and escapes `"` characters in it. However, I often find that I want to log a bunch of things, and with this snippet I have to trigger it once for _each_ item. Is there a good way to have the snippet be "recursive" such that I can just keep typing values and end up with something like:

```c
printf("DBGSTR => [filename:123] foo=%s bar=%s baz=%s\n", foo, bar, baz);
```

and I imagine the workflow would be something like:

1. Expand initial snippet
2. Type `foo`
3. Press "jump" key
4. Type `bar`
5. Press "jump" key
...
6. Finish snippet

---

I've looked at the examples with a `rec_ls` (recursive) style snippet there, but that has the whole snippet copying itself over and over. Here I am just trying to repeat a single piece over and over.

**Comment by bew** [comment]
(thinking out loud, based on the example gif in Ultisnips)

Maybe another way could be to detect the comma somehow and add a new element.
The workflow would be:

1. Expand initial snipet
2. Type `foo`
3. Type `,` (changes the format string)
4. Type `bar`
5. Type `,` (changes the format string)
   ...
6. Finish snippet

**Comment by bew** [comment]
NOTE that if you use a recent python (3.8+) you can use the format string syntax with `=`, like `print(f"PREFIX {foo=} {bar=} {foo(bar, bar)=}")` :smiley:

**Comment by L3MON4D3** [comment]
Oh, ofc, `string_gen` would look something like this
```lua
local function string_gen(args, snip)
local format_text
-- treesitter-magic, fill format_text with eg. "foo=%s, bar=%s"
return sn(nil, t(format_text))
end
```
and the returned snippetNode will be inserted at the position of the dynamicNode, so you can dynamically generate snippets (actually, in this case a `functionNode` would probably suffice as only text needs to be inserted)
Also, [docs for dynamic](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#dynamicnode) [and functionNode](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#functionnode)
