### ISSUE TITLE
question: has anyone started a repo with lua snip snippet collections?

### ISSUE THREAD

**Issue by molleweide** [L3MON4D3/LuaSnip#207]
Hi guys,

I just got lua snip to work for myself and I want to ask if anyone has started a repo for user created collections of lua snippets? I am using friendly-snippets but it only used json files?
I did some quick searches but did not find anything yet.

**Comment by molleweide** [comment]
Happy new year!

I hope you are doing well.

Over the last few days I finished my plugin for making it live so here it is [LuaSnip-snippets.nvim]([https://github.com/molleweide/LuaSnip-snippets.nvim]).

It is obviously in its early stages but I have tried to add some usefull snippets myself, such as the `luasnip-helper.lua` snippets where I try to create small snippets that would aid in the development of more complex snippets. Please give me
feedback on these.

**Comment by L3MON4D3** [comment]
> Happy new year!
> 
> I hope you are doing well.

Thank you, you too :D

> Over the last few days I finished my plugin for making it live so here it is: https://github.com/molleweide/LuaSnip-snippets.nvim.
> 
> It is obviously in its early stages but I have tried to add some usefull snippets myself, such as the `luasnip-helper.lua` snippets where I try to create small snippets that would aid in the development of more complex snippets. Please give me feedback on these.

Looks cool so far :+1:
* I think it'd be nice to allow users to choose and pick single snippets (if I already have a lua-if-snippet I might not want another one, but I might want the lua-for), for example create a function that returns a snippet by eg. name, then one could include it via
    ```lua
    ls.snippets.lua = {luasnip_snippets.by_name("lua", "for")}
    ```
* Apart from that, using `fmt` for creating snippets is much more readable :P
* Looking at the comment-header-snippet, using `regTrig` to specify a custom box-char might be cool
