### ISSUE TITLE
prevent back to snippet when leaving it

### ISSUE THREAD

**Issue by aspeddro** [L3MON4D3/LuaSnip#213]
luasnip configuration not working. When pressing `Tab` the cursor back to snippet
```lua
local luasnip = require 'luasnip'

luasnip.config.set_config {
  history = false,
  region_check_events = 'CursorMoved',
}
```

https://user-images.githubusercontent.com/16160544/139190802-3e96033c-0445-43fa-ad95-732b70bff174.mp4

**Comment by dvdsk** [comment]
I just ran into this and cannibalised the function to get this (might be useful for anyone else who gets here):
```lua
-- check if the cursor is inside a snippet.
local function in_snippet()
	local session = luasnip.session
	local node = session.current_nodes[vim.api.nvim_get_current_buf()]
	if not node then
		return
	end
	local snippet = node.parent.snippet
	local snip_begin_pos, snip_end_pos = snippet.mark:pos_begin_end()
	local pos = vim.api.nvim_win_get_cursor(0)
	if pos[1] - 1 >= snip_begin_pos[1] and pos[1] - 1 <= snip_end_pos[1] then
		return true -- not on row inside snippet
	end
end

-- check if snippet is expandable or jumpable. 
-- Only jumping if the cursor is inside the snippet
local function expandable_or_locally_jumpable()
	return luasnip.expandable() or (in_snippet() and luasnip.jumpable())
end
```
I use nvim-cmp and its default mapping with luasnip. There I replace `luasnip.expandable_or_jumpable` with `expandable_or_locally_jumpable` (the one defined above)

@L3MON4D3 it might be nice to have this in luasnip. Let me know and I will open a PR.

**Comment by L3MON4D3** [comment]
Oh, thats a good alternative to the more naive active-node-check.
Feel free to open a PR :)
