### ISSUE TITLE
store_selection() for non-latin text is incorrect

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#214]
I have a problem with `$TM_SELECTED_TEXT` with cyrillic text. Last stored symbol is incorrect. I think there is some problem with multi-byte characters (?).
Example snippet: `<var>${1:$TM_SELECTED_TEXT}</var>`.
Example text: `какой-то русский текст`
I do `viw` to select word `русский`, than press *store_selection_key*. After expanding snippet I get:
`какой-то <var>русски�</var> текст` (� is looked like `<d0>`).
Also command `:echo b:LUASNIP_SELECT_RAW` prints: `['русски<d0>']`

**Comment by L3MON4D3** [comment]
Should be an easy fix, thanks for bringing it up :+1:

**Comment by L3MON4D3** [comment]
Jinxed it :|
But it's fixed, check out 2b32d2a for the details.

**Comment by stasjok** [comment]
Thank you for the quick fix.
Recently in neovim master were merged new functions vim.str_utf_{start,end}/vim.str_utf_pos. Maybe they somehow can be of help in the future.

**Comment by L3MON4D3** [comment]
Oh, yes!
We'll need a version check around usage of those, but replacing that hack would be nice
