### ISSUE TITLE
Do these features exist?

### ISSUE THREAD

**Issue by IndianBoy42** [L3MON4D3/LuaSnip#217]
I have a few questions about `TM_SELECTED_TEXT` and related features.

1. Is it possible to store the selection without deleting the selection and going into insert? Say, for example it just highlights the selection to be used the next time I expand a snippet
2. Is it possible trigger a specific luasnip snippet (by name or by value) from a command or lua function (so that I could trigger it from a keybinding in normal mode)
3. Could we have an operator style keybinding for selecting (so instead of `viw<select>` its `<select>iw`)
4. Can we make a node that depending on a function call, either inserts a string directly, or becomes an `insert_node`?

If the above three features are available then we could create a very powerful vim-surround style plugin (atleast for adding surroundings, replace and delete have to be handled separately)

**Comment by leiserfg** [comment]
1. Just yank and paste.
2. Check how cmp-luaspnip does it.
3. Yes it's possible,but I don't think we should ship two shortcuts for the same functionality.
4. You can use a dynamic node for that.

**Comment by L3MON4D3** [comment]
Concerning 1, that's also doable by just yanking and, in a `functionNode` getting the text from the `"`-register (doesn't apply in lsp-snippets, but that could be added via `env` I think).
3 would then directly be possible as `yiw`

**Comment by leiserfg** [comment]
The problem with 3 is that you will have to use a distinct shortcut for N and for V modes, cause the one for N is already the one for expanding and it does not have object arguments.

**Comment by leiserfg** [comment]
Anyway, the hardest part of something like sandwich (and similars) is not inserting the characters but finding the matching pairs correctly (handling nested ones) and that will be completely out of scope for luasnip.

**Comment by IndianBoy42** [comment]
> Anyway, the hardest part of something like sandwich (and similars) is not inserting the characters but finding the matching pairs correctly (handling nested ones) and that will be completely out of scope for luasnip.

you're totally right about this. I was mainly asking about the component features that would be necessary, and thinking about just using luasnip as a dependency for a vim-sandwich clone.

I actually kinda want to go further because there is conceptual overlap between like tabout.nvim, nvim-autopairs, vim-surround and even matchup (or any clone). In that they are all about dealing with matching pairs. and even tabout and luasnip have some overlap about having markers/placeholders to fill in and jump between. 
Feels like my config has some redundancy to deal with them all separately and make them work together.

**Comment by L3MON4D3** [comment]
I think tabout and matchup would be pretty hard to emulate with luasnip as snippets cannot easily be created over existing text (but jumping isn't that much overlap imo).
nvim-autopairs would be a likely candidate, but you'd probably need to invest a lot of time in to get on par with what autopairs provides out of the box.
