### ISSUE TITLE
vscode + luasnip snippets

### ISSUE THREAD

**Issue by ChrisTsou** [L3MON4D3/LuaSnip#219]
My init looks like this:
```
local ls = require("luasnip")

local javascript = require('snippets.javascript')
local javascriptreact = require('snippets.javascriptreact')

ls.snippets = {
    javascript = javascript,
    javascriptreact = javascriptreact,
}

ls.filetype_extend("typescript", { "javascript" })
ls.filetype_extend("javascriptreact", { "javascript" })
ls.filetype_extend("typescriptreact", { "javascriptreact", "typescript", "javascript" })

require("luasnip/loaders/from_vscode").lazy_load()
```
this makes a lot of duplicates because it seems the luasnip extend is additive with the package.json extend.
Is there a workaround for this?

**Comment by L3MON4D3** [comment]
Well, the easiest way out would be to change the `package.json` to not include `javascriptreact`,... in `javascript`.

**Comment by ChrisTsou** [comment]
ok, im sry it seems i didnt mention i use friendly-snippets. so yes i can probably fix this by changing the package json so no extends exist there, but then ill have to do it again every time friendly-snippets updates.

**Comment by L3MON4D3** [comment]
IMO the nicest solution is to not add the snippets in the first place.
The best case would be that each source contains exactly the snippets it advertises and the snippet engine can take care of providing snippets from multiple sources if so desired.

**Comment by ChrisTsou** [comment]
Basically no extends in friendly-snippets and use luasnip to extend? if that is so i think i agree. I have already opened an issue in friendly snippets, i'll mention this
