### ISSUE TITLE
Function and dynamic nodes are missplacing the extmarks

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#22]
```lua
local ls = require("luasnip")
local s = ls.s
local t = ls.t
local i = ls.i
local f = ls.f
local function date()
  return {os.date("%Y-%m-%d")}
end
ls.snippets = {
    all = {
        s({trig = "date", wordTrig = true}, {f(date, {}), i(0)}), 
        s({trig = "date2", wordTrig = true}, {f(date, {}), t({" "}), i(0)})
    }
}

```
`date` renders to
`␣2021-05-24`
instead of `2021-05-24␣`.
while `date2` renders to
`2021-05-24 ␣`

**Comment by L3MON4D3** [comment]
Oh no, I'll take a look at it later. Did this behavior start recently/can you pinpoint which commit it was?

**Comment by L3MON4D3** [comment]
Okay, I think I know what's causing this, I'll get a fix up soon.

**Comment by leiserfg** [comment]
I was bisecting the repo and seems like this was the commit
d14c737bb10b180efaccf39c2c8424962786897b

**Comment by leiserfg** [comment]
By the way, can you provide a way to render the snippet without having to jump to another node, for instance changing to normal mode, to preview the changes when using a snippet with a single input?

**Comment by L3MON4D3** [comment]
> By the way, can you provide a way to render the snippet without having to jump to another node, for instance changing to normal mode, to preview the changes when using a snippet with a single input?

Just so I get you right, when expanding `date` this way, it would be `2021-05-24` and you'd be in normal mode? I'm not sure what this would be useful for tbh, could you elaborate?

**Comment by leiserfg** [comment]
Sorry I was far from my computer, the idea is:
Going to normal mode (by pressing `<esc>`,  `<c-c>` or any other) makes the snippet to be rendered. One use case:
Having a snipped composed of an input node and function node that merely renders that node with a complex filter, having that feature will allow previewing the function result. Other implementations render the snippet on each keypress but I suppose rendering it when changing mode to normal could be a good tradeoff.

**Comment by L3MON4D3** [comment]
Ahh, that's a great idea, shouldn't be too hard to implement as well...

**Comment by L3MON4D3** [comment]
Whoops.
Thanks for the suggestion!

**Comment by L3MON4D3** [comment]
Okay, 50de33a should do it.

**Comment by leiserfg** [comment]
Unfortunately, it does not work, going to NORMAL does not render, and going to the input(0) shows:
```
5108: Error executing lua [string ":lua"]:1: attempt to index global 'ls' (a nil value)
```

**Comment by L3MON4D3** [comment]
Stupid mistake, I'll fix it soon. Try `:lua ls = require'luasnip'` as a temporary fix.
