### ISSUE TITLE
How to add snippets to ft = `shell`, include `bash, zsh, sh, etc...`

### ISSUE THREAD

**Issue by molleweide** [L3MON4D3/LuaSnip#220]
Hey man,

How would you recommend adding snippets to all kinds of shell filetypes at the same time?

**Comment by molleweide** [comment]
I realize that I can make a loop and look for `shell` and then add the snippets to every shell filetype.
Would this also work in commands where the filetype isn't explicitly set, as in `my-command`, `get-user`, etc..

I have just finished the first version of a lua snip library plugin in which this is quite easy to implement but I am pretty sure you have something more smooth and fancy to suggest? 😃 

Later I am going to show you my plugin. It is my first one. I want to get your critiqu on it and also discuss what would be a good name for it.

**Comment by L3MON4D3** [comment]
> I have just finished the first version of a lua snip library plugin in which this is quite easy to implement but I am pretty sure you have something more smooth and fancy to suggest?  :smiley:

My first thought was using a [__index-metamethod](https://www.lua.org/pil/13.4.1.html), but that doesn't work with the default `ipairs` (which we use to iterate over the snippet-tables).
Being able to override `ipairs` is a Lua 5.2 feature, but it's available in luajit via the [`-DLUAJIT_ENABLE_LUA52COMPAT`-flag](https://luajit.org/extensions.html), so you'd need to build luajit from source to get it.

That's pretty "clean" (the snippets aren't duplicated), but probably slower (at runtime) than just appending the wanted snippets to the tables :D.
Just looping should work pretty fine, something like
```lua
local shell_filetypes = {"bash", "zsh", "sh", ...}
for _, ft in ipairs(shell_filetypes) do
	-- list_extend appends to first table.
	vim.list_extend(luasnip.snippets[ft], shell_snippets)
end
```

> Later I am going to show you my plugin. It is my first one. I want to get your critiqu on it and also discuss what would be a good name for it.

Looking forward to it :D
