### ISSUE TITLE
fmt not allowing repeated use of placeholders

### ISSUE THREAD

**Issue by seblj** [L3MON4D3/LuaSnip#221]
So I just tried to use fmt for defining a snippet, and I came across the issue that it's not possible to reuse placeholders.

Lets say I have this snippet.
```Lua

local ls = require('luasnip')
local s = ls.snippet
local fmt = require('luasnip.extras.fmt').fmt
local i = ls.insert_node

local snippets = {}

snippets.typescriptreact = {
    s(
        'component',
        fmt(
            [[
            import React from 'react';
            const {filename} = () => {{
              {insert}
            }}

            export default {filename};
        ]],
            {
                insert = i(0),
                filename = f(function()
                    return vim.fn.expand('%:t:r')
                end, {}),
            }
        )
    ),
}

ls.snippets = snippets
```

I then create a file named Test.tsx, and invoke the snippet.
The snippet then expands to:

```tsx
import React from 'react';
const  = () => {
  
}

export default Test;
```

If I remove the last use of `{filename}` in the snippet, it will correctly place the filename in `const {filename} = () => {`

**Comment by L3MON4D3** [comment]
Hah, of course:
The nodes aren't copied anywhere, meaning that the same object ends up two times in the nodes-list of the snippet (which can wreak all sorts of havoc).
Definitely a bug, thanks for opening an issue about it👍
