### ISSUE TITLE
Usage in vimscript without Plug

### ISSUE THREAD

**Issue by ssipos90** [L3MON4D3/LuaSnip#222]
Hi,

According to the docs, keymaps can be set in vimscript using Plug calls, but I use minpac. How can I bind keys in vimscript?

Thanks

**Comment by L3MON4D3** [comment]
Are you sure that `<Plug>`-mappings working depend on the plugin-manager? I'd assumed that it's built into vim.

**Comment by bew** [comment]
See `:h <plug>`, it's a vim key name, unrelated to the plugin package manager.

**Comment by ssipos90** [comment]
@L3MON4D3 @bew I am not sure and I assumed it was Plug related. My bad, I'll test and get back to you.

Thanks!
