### ISSUE TITLE
Any way I can tell if I am expand snip or I am in visual mode

### ISSUE THREAD

**Issue by ray-x** [L3MON4D3/LuaSnip#224]
When I integrate with `Hop` which allow me to extend visual select area, I have key `s` mapped in visual mode. But when I expand the function arguments, and argument start with `s` it will trigger hop.

Is there a way I can tell I am replace snip with real argument or I am `hopping` to other locations

**Comment by L3MON4D3** [comment]
You can map keys for visual+select or for either one ([xmap for visual](http://vimdoc.sourceforge.net/htmldoc/map.html#:map-modes)), can you set `hop`s map for VISUAL only? (Luasnip uses SELECT to highlight placeholders)

**Comment by ray-x** [comment]
If you have `s` vmap to `hop`, in select mode it will still pickup `s` mapping because xmap is a subset of vmap.

**Comment by L3MON4D3** [comment]
Are you sure about that? The docs state very explicitly that `xmap` shouldn't apply in SELECT.

**Comment by ray-x** [comment]
A quick test:

```
vmap s <cmd>lua print('s pressed')<cr>
```

Run test:

```
xmap s
```
Output
```
v s <cmd>lua print('a')<cr>
```

**Comment by L3MON4D3** [comment]
I just tried it, if you map using `xmap s <cmd>lua print("s")<Cr>` it prints only when `s` is pressed in VISUAL, in SELECT `'s'` is inserted

**Comment by ray-x** [comment]
Yes. xmap solve the problem for `hop`, thanks!
