### ISSUE TITLE
The '.' key (repeat last command) doesn't work correctly with LuaSnip

### ISSUE THREAD

**Issue by IndianBoy42** [L3MON4D3/LuaSnip#225]
For example, typing `ahello<ESC>` would insert hello after the cursor. I can then move to somewhere else and hit `.` to insert hello after the cursor wherever I am.

However it doesn't work if I type `ahell<CR><ESC>`, where when I hit enter I am selecting some snippet from the cmp menu (expanded by luasnip). The action I would expect to be repeated is 'insert <whatever> after the cursor'. For other completions from `nvim-cmp` the correct thing happens, but for snippets it doesn't. 

What happens is that the cursor just moves to the left by one space, which is pretty weird. This is probably not exactly a bug but just because noone has put the effort to make it work with '.'

I just want to put it out there that I think it would be a useful feature.

**Comment by L3MON4D3** [comment]
Not a bad idea, but I don't know if it's possible/how to do it :sweat_smile:
We could implement repeating the last expanded snippet manually, but that would have to be mapped to a different key :/

**Comment by leiserfg** [comment]
It is doable, just integrate luasnip with tpope/repeat if installed @L3MON4D3

**Comment by L3MON4D3** [comment]
Ahh right, I'll look into how to do that👍👍

**Comment by kdheepak** [comment]
Integrating with vim-repeat appears to be as simple as adding a single line. However, I attempted to add `vim.cmd('silent! call repeat#set("<Plug>luasnip-expand-or-jump", 1)')` in various parts of the codebase but wasn't able to resolve this. Any suggestions for where to do this would be appreciated. It would be awesome to get dot repeat to work with luasnip.

**Comment by L3MON4D3** [comment]
I think the problem with that is that expand-or-jump is context-sensitive. If there is no trigger before the cursor, no snippet will expand.
What would need to be tracked are calls to `luasnip. expand_snippet` and the last snippet that was expanded (I havent yet looked into vim-repeat, is it able to just call a lua-function?)

**Comment by L3MON4D3** [comment]
I though about it some more, by directing all calls to `snip_expand` through a `<Plug>`-mapping, it's possible to integrate with vim-repeat (right now it only works on `repeat-testing` because `ls.snip_expand` has to be overridden, and that's not possible without some small changes to luasnip.)
```lua
local ls = require("luasnip")
_G.expand_func = ls.snip_expand

-- snip_expand is used to expand all snippets; overriding it will 
-- make every expansion use our function.
ls.snip_expand = function(snip, expand_params)
	_G.expand_snip = snip
	_G.expand_opts = expand_params
	vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>repeatable-snip-expand', true, true, true), '')
end

_G.repeatable_expand = function()
	print("here!!!")
	-- actually expands the snippet.
	_G.expand_func(_G.expand_snip, _G.expand_opts)

	-- prevent clearing text on repeated calls.
	_G.expand_opts.clear_region = nil
	_G.expand_opts.pos = nil
end

vim.cmd[[
        -- setup mappings for all modes (I think)
	noremap <silent> <Plug>repeatable-snip-expand <cmd>lua _G.repeatable_expand()<Cr>
	noremap! <silent> <Plug>repeatable-snip-expand <cmd>lua _G.repeatable_expand()<Cr>

	silent! call repeat#set("\<Plug>repeatable-snip-expand", v:count)
]]
```
Somehow it only works one time, and even then only if the cursor isn't moved after expanding.

**Comment by L3MON4D3** [comment]
I've looked into repeat some more, turns out I completely misunderstood how it works.
I thought that it hooks into the mappings via some vim-hack, turns out `repeat#set` has to be called after each action that should be repeatable, making it pretty simple.
I edited the above to work correctly, but this should be pretty simple to properly implement.

**Comment by augustocdias** [comment]
I'm having issues with this... If I manually call the `expand_repeat` as you created in your commit, it works partially: it recreates the text that triggered the snippet but not what was set in each substitution from the snippet, it also leaves me in insert mode to make the substitutions from the snippet. I'm not sure if this is the intended behavior... I was expecting it would basically redo the whole thing.
When I press `.` it doesn't work... It actually repeats what I typed as the last substitution from the snippet.

At first I thought it was cmp, but when there's no substitutions to trigger luasnip, it works as expected... I'm having issues only when there are snippets.

**Comment by L3MON4D3** [comment]
I'm not sure how vim-repeat works under the hood, but I agree that it'd be expected that the entire snippet is recreated, alas I don't know how to achieve that. (Okay I would have some rough ideas for hacking that together in luasnip, but I'd expect that vim-repeat also repeat the keystrokes after expanding the snippet, thereby filling it...... no idea how to achieve that though)

**Comment by arsham** [comment]
I hope [this](https://github.com/arsham/archer.nvim/blob/bd710709048105c041fbfa01dc81483ec2cc729b/lua/archer/mappings.lua#L86..L88) shed some lights on how to implement the "repeat" operator without using the vim-repeat plugin.

The important part is the `opfunc` value: this is the callback when you hit `.`.

Note that the `l` in the `"g@l"` returned value was necessary in this usage because it had a side effect that would **enter** after the initiation, but you probably should return `"g@<CR>"`.

**Comment by leiserfg** [comment]
In any of the two cases (using vim-repeat or setting `opfunc` and calling `g@`) requires storing a closure  in a module or in `G` because this re-do is stateful.

**Comment by L3MON4D3** [comment]
> I hope [this](https://github.com/arsham/archer.nvim/blob/bd710709048105c041fbfa01dc81483ec2cc729b/lua/archer/mappings.lua#L86..L88) shed some lights on how to implement the "repeat" operator without using the vim-repeat plugin.
> 
> The important part is the `opfunc` value: this is the callback when you hit `.`.
> 
> Note that the `l` (normal **l**, goes right) in the `"g@l"` returned value was necessary in this usage because it had a side effect that would **enter** after the initiation, but you probably should return `"g@<CR>"`.

Ahh, thank you for that example :+1:
I dislike the more indirect call to expand we'd have to do for that, but if that approach also repeats text, sooo good trade off I guess

> In any of the two cases (using vim-repeat or setting opfunc and calling g@) requires storing a closure in a module or in G because this re-do is stateful.

Yup, though we already almost do as much, we have to store the parameters used for the `snip_expand`-call for the `vim-repeat`-integration.
