### ISSUE TITLE
Adding snippets

### ISSUE THREAD

**Issue by bryant-the-coder** [L3MON4D3/LuaSnip#230]
helloooo, is it available to add own custom snippets??

**Comment by L3MON4D3** [comment]
...Yes? :D
See [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vscode-snippets-loader) or [here](https://github.com/L3MON4D3/LuaSnip#add-snippets)

**Comment by bryant-the-coder** [comment]
Where can i create the file that holds those snippet?

**Comment by L3MON4D3** [comment]
Depends. If you want to load snippets defined in lua, you can put the file anywhere, but you'll have to source it (probably in your `init.vim`) during startup.
For lsp-style, best read `DOC.md`, I could only rephrase what's said there :D

**Comment by bryant-the-coder** [comment]
So i need to put a file in my config folder for my snippets? that is what i understand from what you said. Sorry if i am annoying :( cuz i m a 14 year old kid

**Comment by bryant-the-coder** [comment]
It is tooo overwhelmed..... AHHHHHHHHHHHHH

**Comment by L3MON4D3** [comment]
Oh, no worries then :D
> So i need to put a file in my config folder for my snippets?
Yeah, pretty much. You could check out a tutorial on setting up neovim using lua, that should help

**Comment by bryant-the-coder** [comment]
https://neovim.discourse.group/t/whe-can-i-add-new-luasnip-snippets/1376

is it like this one?

**Comment by L3MON4D3** [comment]
Yes, that's one way of doing it 👍

**Comment by bryant-the-coder** [comment]
OKIE. I am so hype in the wait of neovim 0.6

**Comment by bryant-the-coder** [comment]
Sorry boss for interrupting your wonderful day. 
```
require("luasnip/loaders/from_vscode").lazy_load({
  paths = {
    vim.fn.stdpath('config') .. '/snippets',
  }
})
```
This line of code the luasnip/loaders/from_vscode where should i add it? or can explain to me?

**Comment by bryant-the-coder** [comment]
https://github.com/bryant-the-coder/nvim
my repo for nvim

**Comment by bryant-the-coder** [comment]
Can make a pr? I blur

**Comment by L3MON4D3** [comment]
> https://github.com/bryant-the-coder/nvim my repo for nvim

Looks like you should add eg. luasnip.lua to lua/plugins/ and put all luasnip-specific code there.
To also load that file on startup, you'd need a `require("plugins.luasnip")` in init.lua.

**Comment by L3MON4D3** [comment]
> Can make a pr? I blur

Oh ofc!

**Comment by bryant-the-coder** [comment]
thx

**Comment by bryant-the-coder** [comment]
https://github.com/bryant-the-coder/NvHack
Updated link

**Comment by bryant-the-coder** [comment]
Interrupting your wonderful day again... I havve tried but doesnt work. I think a pr is a better approach... :P

**Comment by L3MON4D3** [comment]
> I think a pr is a better approach.

Ohh, that's what you meant :facepalm: 
Honestly, it's going to be better if you know how to do it yourself :D
Have you pushed what you tried so far?

**Comment by bryant-the-coder** [comment]
😂🤣🤣🤣🤣 Ya i will try again. I eill create a snippets/html.json as a test. Then for the what is in the json i know what to do cause uhhhh i use vscode. But for the lua in the snippets.lua in my repo that i dont know what to do... *sigh*

**Comment by L3MON4D3** [comment]
For starters, you can copy `Examples/snippets.lua` into your repo and load it, that way you have a point for starting out.

**Comment by bryant-the-coder** [comment]
Roger that sir
