### ISSUE TITLE
How to close the choice node floating window?

### ISSUE THREAD

**Issue by IndianBoy42** [L3MON4D3/LuaSnip#231]
It seems it only goes away after I jump to the next node, which is annoying because it can cover up the stuff I am trying to write in the current node.

**Comment by L3MON4D3** [comment]
You can call `choice_popup_close()` manually (eg. via a keybind)

**Comment by L3MON4D3** [comment]
(Assuming you use the choice-popup from the wiki)

**Comment by IndianBoy42** [comment]
Thanks, yeah I forgot I used the code from the wiki and it isn't actually a builtin

**Comment by gennaro-tedesco** [comment]
Surfing for this old issue as I have been looking for the same. Using the instructions as in the wiki and executing the `choice_popup_close()` does indeed close the choice node popup, however at next invocation I get the following exception:
```
 attempt to index upvalue 'current_win' (a nil value)

stack traceback:
	... in function 'choice_popup_close'
	... in function </Users/g.tedesco/.config/nvim/lua/plugins/snip_ui.lua:97>
	[C]: in function 'nvim_exec_autocmds'
	...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/node.lua:297: in function 'event'
	...share/nvim/lazy/LuaSnip/lua/luasnip/nodes/choiceNode.lua:159: in function 'input_leave'
	...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:110: in function <...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:96>
```
have you managed to have it work as intended in your case?

P. S. Moreover though the popup window closes, the virtual text
```		
[types.choiceNode] = {
  active = {
    virt_text = { { "●", "Special" } },
    },
  },
```
stays in the buffer.
