### ISSUE TITLE
Investigate possibility to restore position inside restore_node between choices

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#232]
A new restore node is introduced in #228. Sometimes it may be quite useful to have a choice_node with similar (or even the same) input_nodes, but with different surrounding nodes (for example a different design of the snippet). In that case it may be convenient to preserve current active node (or even cursor position) between choices. In theory (https://github.com/L3MON4D3/LuaSnip/issues/227#issuecomment-981593630)

> if you're inside a restoreNode while changing choice and that restoreNode also exists in the new choice, the cursor-position could be restored because we know that the text you were typing still exists.

It would allow changing choices of such snippets without losing current cursor position. It probably should be optional (choice_node-level or user-level or even both?).

**Comment by L3MON4D3** [comment]
Right, thanks for opening.
I could imagine wanting to adjust that behaviour per-choice, so definitely there. If one really doesn't like that behaviour, it's also simple to use a intermediate function to create `choiceNodes`:
```lua
local function no_autojump_choice(pos, choices, opts)
    if opts then opts.autojump = false end
    return c(pos, choices, opts)
end
```

**Comment by L3MON4D3** [comment]
Ah, closing this since #233 is merged
