### ISSUE TITLE
Investigate performance of restore_nodes

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#234]
I notices, that restore_nodes are relatively slow when restored (for example when making a choice). For a small number of nodes it is not noticeable, but for large number of nodes switching choices between them is quite slow.

I prepared a snippet set for testing it:

```lua
local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local d = ls.dynamic_node
local r = ls.restore_node

vim.cmd([[
inoremap <C-L> <Cmd>lua local uv = require("luv"); local time = uv.hrtime(); require('luasnip').change_choice(1); vim.notify(tostring((uv.hrtime() - time)/1000000).."ms")<CR>
nnoremap <C-L> <Cmd>lua local uv = require("luv"); local time = uv.hrtime(); require('luasnip').change_choice(1); vim.notify(tostring((uv.hrtime() - time)/1000000).."ms")<CR>
snoremap <C-L> <Cmd>lua local uv = require("luv"); local time = uv.hrtime(); require('luasnip').change_choice(1); vim.notify(tostring((uv.hrtime() - time)/1000000).."ms")<CR>
]])

local function gen_nodes(count, node_type, start)
  local uv = require("luv")
  local time = uv.hrtime()
  count = count or 50
  start = start or 1
  local nodes = {}
  for j = start, count - start + 1 do
    nodes[j * 3 - 2] = t("Node" .. j .. " = ")
    if not node_type or node_type == 0 then
      nodes[j * 3 - 1] = i(j, "value" .. j)
    elseif node_type == 1 then
      nodes[j * 3 - 1] = r(j, j, i(1, "value" .. j))
    elseif node_type == 2 then
      nodes[j * 3 - 1] = sn(j, { i(1, "value" .. j) })
    else
    end
    nodes[j * 3] = t({ "", "" })
  end
  nodes[#nodes + 1] = t("Generation time: " .. tostring(uv.hrtime() - time) .. "ns")
  return nodes
end

local function gen_dynamic()
  return {
    t("Type (0 - input, 1 - restore, 2 - snippet): "),
    i(1, "1"),
    t(" Number of nodes: "),
    i(2, "20"),
    t({ "", "" }),
    d(3, function(args)
      local type = tonumber(args[1][1])
      local count = tonumber(args[2][1])
      local nodes
      if type and count then
        nodes = gen_nodes(count, type)
      else
        nodes = { t("Error.") }
      end
      return sn(nil, nodes)
    end, { 1, 2 }),
  }
end

ls.snippets = {
  all = {
    s("dynamic_node", {
      c(1, {
        gen_dynamic(),
        gen_dynamic(),
      }),
    }),
    s("dynamic_node_stored", {
      c(1, {
        {
          t({ "Choice 1", "" }),
          r(1, "nodes", sn(1, gen_dynamic())),
        },
        {
          t({ "Choice 2", "" }),
          r(1, "nodes"),
        },
      }),
    }),
    s("dynamic_node_no_choice", gen_dynamic()),
  },
}

for j = 5, 50, 5 do
  for type, name in ipairs({ "inputs", "restores", "snippets" }) do
    ls.snippets.all[#ls.snippets.all + 1] = s(string.format("choice_%s_%d", name, j), {
      c(1, {
        sn(nil, gen_nodes(j, type - 1)),
        sn(nil, gen_nodes(j, type - 1)),
      }),
    })
  end
end
```

It generates a couple of snippets like `choice_input_<i>/choice_restores_<i>/choice_snippets_<i>`, where i — number of nodes. After expanding a snippet press `<C-L>` (or remap to something else) to make a choice. Then with `:messages` command you can get timings. For my PC after 15-20 restore_nodes timing is not instant (>30 ms). There is no this problem for snippet/input nodes (<10 ms even for 50 nodes). Also there is `dynamic_node` snippet and stored variant `dynamic_node_stored`. They allow to dynamically set a number of nodes and test switching speed.

**Comment by stasjok** [comment]
I've updated my comment with dynamic_nodes for completeness.

**Comment by L3MON4D3** [comment]
I did a quick profile with plenary, 75% of the time is spend copying nodes. Pretty sure we can cut that down by a lot as it is just a very basic recursive copy.
[profile.log](https://github.com/L3MON4D3/LuaSnip/files/7642201/profile.log)

**Comment by stasjok** [comment]
Is there a links to `stored` in restore_nodes itself? It can add up the amount of contents to copy. It would explain multiplication. If that makes sense..

As a side note, in 0.6 `vim.deepcopy` can copy metatables. I think it's basically the same as copy3 now. Too bad it's early to drop compatibility for 0.5.

**Comment by L3MON4D3** [comment]
The problem with `restoreNode` is that there could be multiple instances of this node present in the displayed snippet (eg. seen at the same time), so we have to copy the one stored in the snippet each time it's put into the snippet (each time the choice is changed).

We could provide a setting to disable the copy (or rather enable, the default should be to not copy IMO) and document that the node may only show up once at a time if `multi_restore` (maybe? but not intuitive to be sure..) is not set.

**Comment by L3MON4D3** [comment]
[profile without copy](https://github.com/L3MON4D3/LuaSnip/files/7642957/profile.log)

**Comment by L3MON4D3** [comment]
> As a side note, in 0.6 `vim.deepcopy` can copy metatables. I think it's basically the same as copy3 now. Too bad it's early to drop compatibility for 0.5.

That's pretty nice, we could [handle it like the new `json.decode`](https://github.com/L3MON4D3/LuaSnip/blob/0be29b526ac3dd31c497708a44b1d3be734fdeae/lua/luasnip/util/util.lua#L491-L499)

**Comment by L3MON4D3** [comment]
Could you check out `no_copy_restoreNode` to see if it is also better on your side?

**Comment by stasjok** [comment]
> Could you check out `no_copy_restoreNode` to see if it is also better on your side?

Yes, it is much faster.

> That's pretty nice, we could [handle it like the new `json.decode`](https://github.com/L3MON4D3/LuaSnip/blob/0be29b526ac3dd31c497708a44b1d3be734fdeae/lua/luasnip/util/util.lua#L491-L499)

I don't think it's that easy, because vim.deepcopy existed before, but couldn't handle metatables.

> The problem with `restoreNode` is that there could be multiple instances of this node present in the displayed snippet (eg. seen at the same time), so we have to copy the one stored in the snippet each time it's put into the snippet (each time the choice is changed).

Does it even make sense to put multiple of them in the same view? My original idea with only text stored does, also in my visualization if two nodes present in the same view, user can edit any of them and text updated seamlessly in both of them. But right now they are nodes and they are not synchronized (user can edit them separately, but only one of them would be saved, probably last, after switching or recreation of dynamic node). So with current implementation it is much more sense to use repeat in the same view. Is it?

**Comment by L3MON4D3** [comment]
> I don't think it's that easy, because vim.deepcopy existed before, but couldn't handle metatables.

True, not that easy. We could check against version and use `copy3` or the builtin.

> Does it even make sense to put multiple of them in the same view?

No, not really, I used the copy because it is _possible_ to put two `restoreNode`s so they are visible at the same time, and if that happened (without copy), `restoreNode` fails spectacularly.
Putting a comment into the Docs to not do that should suffice, I don't think there's any loss of functionality.

**Comment by stasjok** [comment]
> if that happened (without copy), `restoreNode` fails spectacularly

At least looks like it's failing without errors (one time works, second time nodes become empty).

> Putting a comment into the Docs to not do that should suffice, I don't think there's any loss of functionality.

I agree with that.

With dymanic_nodes it can happen for unsuspecting users more often I think due to non-obvious errors.

**Comment by L3MON4D3** [comment]
> At least looks like it's failing without errors (one time works, second time nodes become empty).

Ah, I would've expected the extmarks to mess up, but that's nice too.
