### ISSUE TITLE
Is there a safe was to get what's before the snippet?

### ISSUE THREAD

**Issue by jandamm** [L3MON4D3/LuaSnip#240]
I'm trying to get what's before the cursor before expanding the snippet. In this specific case I'm trying to get what's before the keyword. But I think the context `before`, `trigger` and `after` could be of interest.

This would allow to create context aware snippets. As an example check #238 for such an example (a lua function snippet which doesn't insert `local` when there is something before the cursor).

Currently I use this code but I'm not very happy with it:
```lua
function before(snippet)
	return snippet.env.TM_CURRENT_LINE:match('^(.*)' .. snippet.dscr[1], 1)
end
```
- Regex matching is used
- Can `dscr` be empty?
- Can `dscr` contain more than one string?

Is there a better way to do this currently?

What do you think about adding a `snippet.context`?

**Comment by L3MON4D3** [comment]
You can just use `snippet.trigger`, it is updated with the actual string that triggered the snippet.
```lua
local before = snippet.env.TM_CURRENT_LINE:sub(1, -(#snippet.trigger+1))
```
should get you the line without the trigger.
`dscr` contains an optional description of the snippet, it just defaults to `trig` and may have multiple lines.

**Comment by jandamm** [comment]
`snippet.trigger` sounds much better - will use that instead of `dscr` 👍

The `sub` however will only work if the snippet is triggered at the end of the line. Not if there is text after the trigger.
With `match` it should work unless the trigger is twice in the current line.

**Comment by L3MON4D3** [comment]
Ahhh true, hadn't considered that.
Making it completely foolproof would require getting the line up to the point where the snippet begins directly after expansion, but `match` should always work  :ok_hand:
I'll add a note on `trig` in `DOC.md`, I'm not sure it's mentioned anywhere (except this issue, now :D)

**Comment by jandamm** [comment]
`match` wouldn't work for this line `trigger trigger` since it's unclear which trigger was expanded when using match.
But this case is probably neglectable 👍
