### ISSUE TITLE
javascript.json snippets from friendly-snippets stop work in .ts and .tsx files

### ISSUE THREAD

**Issue by timsofteng** [L3MON4D3/LuaSnip#241]
Hello. I've noticed that javascript snippets stop work in typescript files with .ts and .tsx extension.
It works before.

**Comment by L3MON4D3** [comment]
Yes, that was a change in `friendly-snippet`, see [here](https://github.com/rafamadriz/friendly-snippets/issues/88) for a discussion.

The TLDR is that you need to call
```lua
require("luasnip").filetype_extend("typescript", {"javascript"})
```
somewhere in your config.

**Comment by timsofteng** [comment]
Thanks!
