### ISSUE TITLE
Bug: illegal operation on a directory

### ISSUE THREAD

**Issue by cathaysia** [L3MON4D3/LuaSnip#243]
Today, I update my nvim plugins, then it go error. It throw some error every I open nvim:

![图片](https://user-images.githubusercontent.com/42114817/146487298-4f3047e6-30d4-40ba-828c-441e4b419a94.png)

Disable luasnip can solve this bug.

And now I know back to 09e3bc6da5376aa87a29fde222f321f518e6c120 can solve this also.

**Comment by GPN211314** [comment]
+1

**Comment by uga-rosa** [comment]
Can you show me the setting and the directory structure around snippets? It looks like the folder path is in the place where the file path should be.

**Comment by wjllm** [comment]
+1

**Comment by tiagovla** [comment]
Same here. The bad commit is 1de3d81adf79693d7dff6eba4edf16f9295ac30b.

**Comment by cathaysia** [comment]
packer:
```lua
    use {'L3MON4D3/LuaSnip',
        config = require('plugins.luaSnip'),

    }
```
luasnip:
```lua
return function ()
    local luasnip = require('luasnip')
    local types = require("luasnip.util.types")
    luasnip.config.set_config({
        history = true,
        updateevents = 'TextChanged,TextChangedI',
        ext_opts = {
            [types.choiceNode] = {
                activate = {
                    virt_text = {{'choiceNode', 'Comment'}}
                }
            }
        },
        ext_base_prio = 300,
        ext_prio_increase = 1,
        enable_autosnippets = true
    })
    -- 加载 vsnip
    require('luasnip.loaders.from_vscode').load({
        paths = {
            '~/.local/share/nvim/site/pack/packer/start/friendly-snippets',
            vim.fn.stdpath('config')..'/snippets'
        }
    })
end
```

dir structure is:

![图片](https://user-images.githubusercontent.com/42114817/146509177-41ba238f-bca8-4b79-951d-4a74a899dc82.png)

**Comment by cathaysia** [comment]
> Same here. The bad commit is [1de3d81](https://github.com/L3MON4D3/LuaSnip/commit/1de3d81adf79693d7dff6eba4edf16f9295ac30b).

yes, he is right.

**Comment by uga-rosa** [comment]
Ok, I figured it out, because when I organized the rtp process, I made it so that the package.json path was specified. I will issue a PR to fix it.

**Comment by lambtho12** [comment]
Same issue here as well.
