### ISSUE TITLE
Foldexpr is incorrectly used in UltiSnips .snippet files

### ISSUE THREAD

**Issue by smjonas** [L3MON4D3/LuaSnip#246]
In [776eceb](https://github.com/L3MON4D3/LuaSnip/commit/776ecebe7015e504d84c3273780e8ea0c312b83c) a syntax file was added for .snippet files that makes my UltiSnips definition files look like this:

![luasnip](https://user-images.githubusercontent.com/40792180/146580442-ce95423e-f49f-4bd3-86de-17e70584efd9.png)

First of all, I know there probably won't be that many users that open UltiSnips files while using Luasnip. However I am not sure if we need folds here? Especially for short snippet definitions this does not add much value in my opinion. Would you be okay with removing that or at least check for the keyword `endsnippet` in the file which will avoid incorrectly marking vim-snippet files as UltiSnips files?

I'll ping @uga-rosa here as well.

**Comment by L3MON4D3** [comment]
I'm alright with removing the foldexpr, if @uga-rosa agrees we can just do that

**Comment by uga-rosa** [comment]
Oh, I didn't know it had this side effect.
I agree 👍
