### ISSUE TITLE
"captures" extra node?

### ISSUE THREAD

**Issue by thorlucas** [L3MON4D3/LuaSnip#247]
I may be missing something, but are we missing the obvious `cap` node?

```lua
local cap = function(i)
	return f(function(_, snip) return snip.captures[i] end, {})
end
```

I can PR this real quick if this is the case, just wondering cause I didnt see it in the extras folder.

**Comment by L3MON4D3** [comment]
Yep, that isn't included yet, I'd welcome a PR :D
(If you do, better change `snip.captures` to `snip.snippet.captures`, `snip.captures` may be `nil` eg. if the `cap` is not a direct child of the surrounding snippet (inside a `dynamicNode`, for example))

**Comment by thorlucas** [comment]
Right, sounds good!

I'm also playing around with a few other ideas, I'll see where they take me before PR in case I come up with a few more general utils.

**Comment by bew** [comment]
@L3MON4D3 you're closing this because it has been implemented? Or because there's no interest?

**Comment by L3MON4D3** [comment]
Oh, no interest. I'd accept a PR, but it isn't that vital.
