### ISSUE TITLE
Live updating

### ISSUE THREAD

**Issue by thorlucas** [L3MON4D3/LuaSnip#248]
I understand that there is clearly a performance impact, but live updating would be a fantastic feature for function nodes and repeat nodes for better visual feedback. Is this at all possible with the engine the way it currently is? If so, maybe it could be a setting of the plugin or even a setting of a particular node itself?

**Comment by L3MON4D3** [comment]
It's possible to trigger the update on any event, by setting [`updateevents`](https://github.com/L3MON4D3/LuaSnip#config).
You'll probably want `TextChangedI`
