### ISSUE TITLE
Consultation on new parser

### ISSUE THREAD

**Issue by uga-rosa** [L3MON4D3/LuaSnip#251]
Hi @L3MON4D3.

It's not an issue, but I don't know any other way to contact you, so please excuse me here.

I've been writing a PR this past week to add a powerful parser for VSCode/SnipMate, and I need some advice.
The syntax of the VSCode snippet looks like this (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar), but it's not practical to fully support JS regular expressions. I think using vim regex for transform is a realistic way to reproduce the same thing. However, this is not a good way to use existing assets.

What do you think?

**Comment by uga-rosa** [comment]
Note that even vsnip does not support anything other than `(.*)` are not supported. I think it would be more useful to be able to use vim's regular expressions completely rather than such a half-hearted support.

**Comment by L3MON4D3** [comment]
Don't worry about opening an issue about it, that's alright :D

Concerning a new parser, the current "plan" is to use the one provided by neovim (`require"vim.lsp._snippets".parse` or something like that), the rationale being that if it is improved, everyone gets a better parser.
I think it also supports parsing transformations, it's just up to us to implement them.
When it comes to doing the transformations, I agree that using vimscript isn't perfect. I think @kmarius made some effort on making js-regex available to lua (I think it is done, actually, but I wasn't really that interested in implementing the transformations😅), so we could use that and, if unavailable, fall back to vimscript.

What do you think about doing it that way?

**Comment by uga-rosa** [comment]
I took a look at vim.lsp._snippet and it doesn't seem to do anything special about converting js-regex. (It seems to be a lua rewrite of the vsnip parser, but it's really well done).

If we use this parser, it would be better to give up eval using backtick and add ${VIM} like vsnip.

**Comment by L3MON4D3** [comment]
> I took a look at vim.lsp._snippet and it doesn't seem to do anything special about converting js-regex. (It seems to be a lua rewrite of the vsnip parser, but it's really well done).

Yep, it only makes it available in the ast I think.

> If we use this parser, it would be better to give up eval using backtick and add ${VIM} like vsnip.

I don't think we have to, we can parse the text before and after the backticks using the parser and merge the ASTs with the `functionNode` for backticks between them.

**Comment by uga-rosa** [comment]
I wouldn't mind adding parser for backtick, but I don't think it's that important... This way is easier to extend, because we can use variable node of AST.
Wouldn't it be nice if users could configure things like embedding python code in ${PYTHON}?

**Comment by kmarius** [comment]
@L3MON4D3 I was going to revisit the transformations once the new parser landed but didn't really follow the issue. I did eventually implement the transformations (which is the only thing the module does for now, it doesn't provide actual bindings to `js-regex`). What does not work is transformations on unicode characters (it does work in the QuickJs interpreter so I'm just doing something wrong).

The code is here: https://github.com/kmarius/jsregexp

**Comment by L3MON4D3** [comment]
> I wouldn't mind adding parser for backtick, but I don't think it's that important... This way is easier to extend, because we can use variable node of AST.

I'm not sure whether the parser handles everything that could be put into variable fine, one transformation could end up in different children of the AST, or the parser could just not parse the snippet completely

> Wouldn't it be nice if users could configure things like embedding python code in ${PYTHON}? (I'm going to put in a mechanism where you can add variables and their corresponding functions.)

That sounds good, check out `until.environment`, that's where the values for variables come from right now.

**Comment by L3MON4D3** [comment]
> @L3MON4D3 I was going to revisit the transformations once the new parser landed but didn't really follow the issue. I did eventually implement the transformations (which is the only thing the module does for now, it doesn't provide actual bindings to `js-regex`). What does not work is transformations on unicode characters (it does work in the QuickJs interpreter so I'm just doing something wrong).
> 
> The code is here: https://github.com/kmarius/jsregexp

Nice, I'll definitely look into it👍

**Comment by uga-rosa** [comment]
For now, let's actually write a parser using the ast returned by vim.lsp._snippet.parse.
I'll come back to ask if there are any more problems.

**Comment by L3MON4D3** [comment]
Sounds Good :+1:

**Comment by leiserfg** [comment]
Converting jsregex to vim regex is a no go, I tried before and there are several things that can't be translated, and it won't make sense to have it if it doesn't work well. We decided to use the c lib that @kmarius ended wrapping for lua, but we haven't work in that regard since then.

**Comment by uga-rosa** [comment]
https://github.com/L3MON4D3/LuaSnip/blob/5cc313528e5e5b71508e799a037f255f26febd7c/lua/luasnip/util/environ.lua#L39
Do I need this `rawset`? Lazy shouldn't be cached, right?

**Comment by L3MON4D3** [comment]
I don't think so, just setting it should be alright.

**Comment by uga-rosa** [comment]
(Does that mean rawset is necessary? Sorry, my English is not good.)
Because I have __index set up, I can't access this rawset data without using rawget, but I couldn't find rawget, so I asked. Are you using it for something other than var in util.functions?

**Comment by L3MON4D3** [comment]
It's alright to do `self[key]=var` :D
(But having -__index shouldn't prevent you from accessing a key that was rawset, __index is only called for keys that don't exist in the table yet). 



> Are you using it for something other than var in util.functions?

Do you mean env? If so, Yes, that's populated in every snippet, check `trigger_expand` and `fake_expand` in `nodes/snippet.lua`

**Comment by uga-rosa** [comment]
Oh, I'm sorry. __index is only called when there is no key in the original table.

I was thinking that if it is cached with the value of the first call, I can't make snippets like ${VIM:$1} that I want to re-evaluate every time.

Changing this would have a huge impact. Should I avoid...

**Comment by L3MON4D3** [comment]
You could also just not set it in `__index`, that way it could be reevaluated each time.
Or use a different function for `$VIM`

**Comment by uga-rosa** [comment]
That's right. I think I can manage that. Thank you.
