### ISSUE TITLE
Selection always miss the last character

### ISSUE THREAD

**Issue by AgentCosmic** [L3MON4D3/LuaSnip#252]
For example:

```
for (let index = 0; index < array.length; index++) {
	const element = array[index];
	
}
```

My first selection will be `inde`, but not `index`. Then I jump to next position `arra`, again missing the `y`.
I'm using it with nvim-cmp. Neovim 0.6 Windows.

**Comment by L3MON4D3** [comment]
Cannot reproduce on Linux, but it's possible that some bahaviour differs on Windows.
Could you post the output of `:lua require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].parent.snippet:dump()`?

**Comment by AgentCosmic** [comment]
```
1
false false
6 1
6 10
2
false true
6 10
6 15
3
true false
6 15
6 21
4
false false
6 21
6 26
5
false false
6 26
6 29
6
false false
6 29
6 34
7
false false
6 34
6 43
8
false false
6 43
6 48
9
false false
6 48
7 8
10
false false
7 8
7 15
11
false false
7 15
7 18
12
false false
7 18
7 23
13
false false
7 23
7 24
14
false false
7 24
7 29
15
false false
7 29
8 2
16
false false
8 2
8 2
17
false false
8 2
9 2
```

**Comment by L3MON4D3** [comment]
Can you confirm that, with `b, e = require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].mark:pos_begin_end()`, 
- `require("luasnip.util.util").normal_move_on(b)` moves the cursor on top of the `i` of `index` and
- `require("luasnip.util.util").normal_move_before(e)` moves the cursor on the `x`.

**Comment by AgentCosmic** [comment]
So I run `b, e = require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].mark:pos_begin_end()` then:
`require("luasnip.util.util").normal_move_on(b)` landed on `i`
`require("luasnip.util.util").normal_move_before(e)` landed on `x`

**Comment by L3MON4D3** [comment]
Hm, everything works correctly so far.
This is the actual code that selects the text, does that work still? (You could paste it into a file and `:luafile %` after expanding the snippet in a comment for example)
```lua
local mark_begin_pos, mark_end_pos = require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].mark:pos_begin_end()
local util = require("luasnip.util.util")


util.normal_move_on(mark_begin_pos)
vim.api.nvim_feedkeys(
	vim.api.nvim_replace_termcodes("v", true, false, true),
	"n",
	true
)
util.normal_move_before(mark_end_pos)
vim.api.nvim_feedkeys(
	vim.api.nvim_replace_termcodes("o<C-G>", true, false, true),
	"n",
	true
)
```

**Comment by AgentCosmic** [comment]
Here's the file I used to run:

```lua
-- local varName = value

local mark_begin_pos, mark_end_pos = require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].mark:pos_begin_end()
local util = require("luasnip.util.util")


util.normal_move_on(mark_begin_pos)
vim.api.nvim_feedkeys(
	vim.api.nvim_replace_termcodes("v", true, false, true),
	"n",
	true
)
util.normal_move_before(mark_end_pos)
vim.api.nvim_feedkeys(
	vim.api.nvim_replace_termcodes("o<C-G>", true, false, true),
	"n",
	true
)
```

Only `varNam` got selected when I ran `:w` and `:luafile %`.

**Comment by AgentCosmic** [comment]
I'm not sure if setting the mark is done correctly but here's by observation given this string `varName`.

```
varName
      ^ set mark "a when cursor is here
^ move cursor here then: v"a
varName
^    ^ selection is now here, but cursor moves correctly to "a
varName
      ^ I press escape to exit selection and cursor is on "e" which is correct behaviour

varName
       ^ correct place to set end mark
```

So I'm assuming there's something wrong with getting the mark from `pos_begin_end` because the end mark is giving -1.

**Comment by L3MON4D3** [comment]
> Here's the file I used to run:
> 
> ```lua
> -- local varName = value
> 
> local mark_begin_pos, mark_end_pos = require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].mark:pos_begin_end()
> local util = require("luasnip.util.util")
> 
> 
> util.normal_move_on(mark_begin_pos)
> vim.api.nvim_feedkeys(
> 	vim.api.nvim_replace_termcodes("v", true, false, true),
> 	"n",
> 	true
> )
> util.normal_move_before(mark_end_pos)
> vim.api.nvim_feedkeys(
> 	vim.api.nvim_replace_termcodes("o<C-G>", true, false, true),
> 	"n",
> 	true
> )
> ```
> 
> Only `varNam` got selected when I ran `:w` and `:luafile %`.

Ohhhhh du you maybe have `selection` set to `exclusive`? I was so focused on Windows, i completely ignored some other cause and asking you to do it with a clean config🤦‍♂️

**Comment by AgentCosmic** [comment]
Yea it's set to exclusive, although not explicitly. Setting it to inclusive seems to solve the issue.

**Comment by L3MON4D3** [comment]
Alright, I'll add some checks to take that setting into account when selecting
