### ISSUE TITLE
Clarity to readme

### ISSUE THREAD

**Issue by RayZ0rr** [L3MON4D3/LuaSnip#254]
I have been trying to get a working combination of [nvim-cmp ](https://github.com/hrsh7th/nvim-cmp), [friendly snippets](https://github.com/rafamadriz/friendly-snippets) and luasnip working. Nothing was working as `LuaSnip ListAvailable` returned :  

```lua
{
  all = {},
  cpp = {}
}
```
for all filetypes.

Finally this issue #157 helped me solve it. I am so happy now,  but I hope there should be a mention in the readme on how to work with friendly snippets

**Comment by L3MON4D3** [comment]
Ahh, yeah that's fair. I added links to the example-code in the readme, it should be more visible there.
Thank you for opening an issue about this :+1:
