### ISSUE TITLE
Shouldn't going to normal mode cancel the "session"?

### ISSUE THREAD

**Issue by augustocdias** [L3MON4D3/LuaSnip#258]
I've noticed that if I expand a snippet, go to normal mode without jumping into the snippet replacements, going back to insert and pressing tab is causing it to jump to the previous snippet. I was reading the LuaSnip code and I understood that you create a "session" for each snippet that is expanded. Shouldn't going to normal mode erase this session? This is causing some weird issues on my setup when I press Esc and go to edit somewhere else, press tab and the cursor jumps back to where I was before instead of indenting.

I'm using luasnip as the snippets source for nvim-cmp and I believe it uses luasnip not only for snippets but for other stuff such as expanding functions. I usually "finish" all the sessions for actual snippets but not for other kinds of expansions such as functions for ex. 

For example in a rust file if I type `let var: Option<` the lsp will suggest `Option<...>` and I get that it makes what's between the `<>` a snippet. If I don't cycle through the "snippet" with Tab, go to normal mode, go somewhere else, insert and press tab the cursor will move to somewhere else. In this scenario it doesn't go back to the `Option` but somewhere else, if it is an actual snippet then it goes back to the snippet. 

Perhaps there's something I can change in my config to avoid this issue. Here's how I configured cmp+luasnip:

```lua
cmp.setup({
    sources = {
        { name = 'nvim_lsp', priority = 99 },
        { name = 'luasnip', priority = 90 },
        { name = 'nvim_lua', priority = 80 },
        { name = 'cmp_tabnine', priority = 80 },
        { name = 'path', priority = 10 },
        { name = 'buffer', priority = 0 },
    },
    snippet = {
        expand = function(args)
            luasnip.lsp_expand(args.body)
        end,
    },
    mapping = {
        ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
        ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
        ['<C-f>'] = cmp.mapping.scroll_docs(-4),
        ['<C-b>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<Esc>'] = cmp.mapping.close(),
        ['<Tab>'] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
            elseif luasnip.expand_or_jumpable() then
                luasnip.expand_or_jump()
            elseif has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end, { 'i', 's' }),
        ['<S-Tab>'] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_prev_item({ behavior = cmp.SelectBehavior.Insert })
            elseif luasnip.jumpable(-1) then
                luasnip.jump(-1)
            else
                fallback()
            end
        end, { 'i', 's' }),
       ['<CR>'] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
        }),
    },
})
```

**Comment by L3MON4D3** [comment]
Almost: Session is global and stores which snippet (or node, to be precise) is currently active.
Despite that, it's possible to leave the active snippet when leaving insert by registering (untested, but should work)
```vim
autocmd InsertLeave * lua if require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()] then require("luasnip").unlink_current() end
```
(`unlink_current` prints a warning when it's called while there is no active snippet, so prevent that)

**Comment by augustocdias** [comment]
Sorry for the long time to reply. I hadn't access to my computer in the latest days. While this solved the problem I posted it created another... Jumping through the snippets parameters stopped working for some reason...

**Comment by L3MON4D3** [comment]
Ouh, ofc, Luasnip leaves insert temporarily while jumping :|
I'll fix that, in the meantime using another event instead of `InsertLeave` should work (`CursorHold`?)

**Comment by L3MON4D3** [comment]
Okay, I made `jump_active` (which is set while luasnip is jumping around) accessible via `ls.session`, could you try if
```lua
-- don't leave the snippet if luasnip caused the InsertLeave.
autocmd InsertLeave * lua if require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()] and not require("luasnip").session.jump_active then require("luasnip").unlink_current() end
```

**Comment by augustocdias** [comment]
I came up with the following and it works:

```lua
function leave_snippet()
    if
        ((vim.v.event.old_mode == 's' and vim.v.event.new_mode == 'n') or vim.v.event.old_mode == 'i')
        and require('luasnip').session.current_nodes[vim.api.nvim_get_current_buf()]
        and not require('luasnip').session.jump_active
    then
        require('luasnip').unlink_current()
    end
end

-- stop snippets when you leave to normal mode
vim.api.nvim_command([[
    autocmd ModeChanged * lua leave_snippet()
]])
```

**Comment by feekApp** [comment]
thnx @augustocdias you made my day!

**Comment by Strongleong** [comment]
I think there is must be some setting to turn this off.

**Comment by lawrence-laz** [comment]
> I came up with the following and it works:
> 
> ```lua
> function leave_snippet()
>     if
>         ((vim.v.event.old_mode == 's' and vim.v.event.new_mode == 'n') or vim.v.event.old_mode == 'i')
>         and require('luasnip').session.current_nodes[vim.api.nvim_get_current_buf()]
>         and not require('luasnip').session.jump_active
>     then
>         require('luasnip').unlink_current()
>     end
> end
> 
> -- stop snippets when you leave to normal mode
> vim.api.nvim_command([[
>     autocmd ModeChanged * lua leave_snippet()
> ]])
> ```

Thank you, thank you, thank you! Oh my... This was soo annoying and I had no idea why this is happening

**Comment by pogopaule** [comment]
> I came up with the following and it works:
> 
> ```lua
> function leave_snippet()
>     if
>         ((vim.v.event.old_mode == 's' and vim.v.event.new_mode == 'n') or vim.v.event.old_mode == 'i')
>         and require('luasnip').session.current_nodes[vim.api.nvim_get_current_buf()]
>         and not require('luasnip').session.jump_active
>     then
>         require('luasnip').unlink_current()
>     end
> end
> 
> -- stop snippets when you leave to normal mode
> vim.api.nvim_command([[
>     autocmd ModeChanged * lua leave_snippet()
> ]])
> ```


If anyone is interested, this is @augustocdias solution using the nvim_create_autocmd method:
```lua
vim.api.nvim_create_autocmd('ModeChanged', {
  pattern = '*',
  callback = function()
    if ((vim.v.event.old_mode == 's' and vim.v.event.new_mode == 'n') or vim.v.event.old_mode == 'i')
        and require('luasnip').session.current_nodes[vim.api.nvim_get_current_buf()]
        and not require('luasnip').session.jump_active
    then
      require('luasnip').unlink_current()
    end
  end
})
```

**Comment by keks** [comment]
@L3MON4D3 Maybe I am missing something, but shouldn't this be the default?
