### ISSUE TITLE
Just want to say thanks :)

### ISSUE THREAD

**Issue by runiq** [L3MON4D3/LuaSnip#26]
This morning, when I decided to see what's new in nvim-compe these days, I did a double-take when I found that it supported a new snippets plugin. "LuaSnip?", I thought, "Huh. Gotta check that one out."

And lo and behold, it was glorious. With select mode and extmarks, the presentation is really simple and non-surprising—exactly as I like it. The snippets syntax is a bit bewildering at first, but pretty ingenious overall.

When I realized that I wasn't shackled to my previous snippets plugins anymore, a single tear rolled down my face.

Thank you, @L3MON4D3. I feel at home.

:eggplant:

**Comment by L3MON4D3** [comment]
Dude, thank you, it makes me very happy to hear this :D

**Comment by runiq** [comment]
No, thank *you*. Feel free to close :)
