### ISSUE TITLE
Filename as initial text for insert node

### ISSUE THREAD

**Issue by sven-strothoff** [L3MON4D3/LuaSnip#260]
### Summary
I am trying to create a snippet where the initial text of an insert node is the current file's name. Using the filename directly as the second parameter of an insert node seems to be evaluated only once when the snippet is first expanded. I also tried several variants using function nodes and `TM_FILENAME`, but never got it working correctly.

I could not find any snippet, example or documentation for this. Any help or pointers in the right direction would be appreciated.

### Some more details of what I am trying to do
I am trying to create an "include guard" snippet for C/C++:
```
#ifndef FILENAME_H
#define FILENAME_H

$0

#endif // FILENAME_H
```
I want the macro name to be an insert node, but have it initialised with the current filename.

The closest thing I got was this:
```
    s('once', {
      t('#ifndef '),
      i(1, string.upper(string.gsub(vim.fn.expand('%:t'), '%.', '_'))),
      t({'', '#define '}),
      f(function(args) return args[1][1] end, {1}),
      t({'', '', ''}),
      i(0),
      t({'', '', '#endif // end of include guard: '}),
      f(function(args) return args[1][1] end, {1}),
    })
```
However, this seems to be evaluated only once and inserts the name of the file where the snippet was first expanded.

**Comment by L3MON4D3** [comment]
You're almost there, generate the `insertNode` that contains the filename using a `dynamicNode` and it should work.
FunctionNodes are almost correct, the problem is that you aren't able to change the inserted text.
A different approach is using [`dynamicLambda`](https://github.com/L3MON4D3/LuaSnip/blob/79662d8bb61bbee6af88bf559d9ed41c28eb5b88/Examples/snippets.lua#L417): `dl(1, l.TM_FILENAME, {})` (functionally equivalent to the dynamicNode, but a bit more concise in this case)

**Comment by sven-strothoff** [comment]
Thank you for your quick reply and your support!
So, there kinda was an example for this after all… sorry. 😅 

I was not able to get it working using a `dynamicNode`. I ended up with the correct filename (by returning an `insertNode`) but I was unable to jump into the `insertNode`. Maybe my jump indices were wrong. I was unsure which numbers to assign to the `dynamicNode` and the `insertNode`.

However, the suggested `dynamicLambda` works fine.
I will attach the working solution, in case anyone stumbles across this issue in the future:
```
s('once', {
  t('#ifndef '),
  dl(1, l.TM_FILENAME:upper():gsub('%.', '_'), {}),
  t({'', '#define '}),
  f(function(args) return args[1][1] end, {1}),
  t({'', '', ''}),
  i(0),
  t({'', '', '#endif // end of include guard: '}),
  f(function(args) return args[1][1] end, {1}),
})
```

**Comment by sven-strothoff** [comment]
I was curious and looked at the implementation of `dynamicLambda`. I did not understand everything but the same jump index is used for the `dynamicNode` and the `insertNode`. That possibility somehow did not occur to me.

Using the same index it also works with a `dynamicNode`:
```
d(1, function(args, snip) return i(1, snip.env.TM_FILENAME:upper():gsub('%.', '_')) end, {}),
```

Just in case anyone else was wondering. 😉

I'm sticking to the more concise `dynamicLambda` version, though.

**Comment by L3MON4D3** [comment]
Both having the same jump-index doesn't really matter, the `i(1, ...)` is important if the `insertNode` is wrapped inside a `snippetNode` (which is usually the case, kind of suprised that returning something other than a `snippetNode` works without issues), because then the positions restart at 1 (contrary to other snippet-definitions, eg. textmate).

**Comment by sven-strothoff** [comment]
I tried it with and without the `snippetNode` as I was unsure if it is necessary when returning exactly one other node. Seems to work fine. 🙃 
Thank you for the explanation regarding the jump index!

**Comment by L3MON4D3** [comment]
> I tried it with and without the `snippetNode` as I was unsure if it is necessary when returning exactly one other node. Seems to work fine. :upside_down_face:

Okay, that's pretty nice

> Thank you for the explanation regarding the jump index!

You're welcome :D
