### ISSUE TITLE
[Question] Will <Plug>luasnip-next-choice trigger InsertLeave? 

### ISSUE THREAD

**Issue by rockyzhang24** [L3MON4D3/LuaSnip#261]
Hello, 

I set `update_in_insert` in `vim.diagnostic` to `false`, i.e., the diagnostics will be updated via `InsertLeave`.  So after entering insert mode, all the diagnostics will be hidden, and they will show up when I go back to the normal mode. 

For ChoiceNode, when I use `<Plug>luasnip-next-choice` (binding to `<C-l>`) to select choices, the diagnostics will appear and then disappear, i.e., flashing, which is very distracting. So I am wondering whether it will trigger `InsertLeave` event to make the diagnostics to be updated and shown up? And is that normal? 

The test snippet I use: 
```
  s("test", {
    t("Hello World"),
    c(1, {
      t("choice1"),
      t("choice2"),
    }),
  }),
```

Short video to demo:

https://user-images.githubusercontent.com/11582667/149247807-c5559665-3e7e-4213-8f19-d0d257f2ecd5.mov

Thank you very much.

**Comment by L3MON4D3** [comment]
Ah, yes it does, and it is normal.
It used to be necessary to leave INSERT because we may jump from SELECT and iirc the mode wasn't always reported correctly.
I'm not sure if all of that still applies, if it doesn't this might be an easy fix.

**Comment by yanzhang0219** [comment]
Okay I see. Thanks.

Do you have any ideas to improve this "diagnostic information flashing"? 

In addition, will this cause performance issue in a large file? `vim.diagnostic` will keep monitoring `InsertLeave` event to update the diagnostics. If each time pressing `<C-l>` will trigger this event, it means the diagnostics will be updated quite frequently. 

So is it possible to make `luasnip-next-choice` and `luasnip-prev-choice` not trigger the diagnostics update? 

Thank you very much.

**Comment by L3MON4D3** [comment]
With aac0f43, jumping between two empty `insertNode`s (or changing choice in your case) will not switch to NORMAL, but SELECTing text still requires the switch.
You could check if luasnip is currently performing any jumps (`require("luasnip.session").jump_active` will be set) and not update the diagnostics in that case (I didn't open with that recommendation because I thought I'd be able to completely remove leaving INSERT from the jump-process).

**Comment by L3MON4D3** [comment]
Looking at `:h vim.diagnostic`, this might not be as straightforward as I thought :|
As a last resort you could override the handler to not display them, but they would still be queried I think.

**Comment by L3MON4D3** [comment]
Looks like the autocmd for diagnostics is registered [here](https://github.com/neovim/neovim/blob/596c55756a6a25e8a6d587610292f3e2ca0940b7/runtime/lua/vim/diagnostic.lua#L342), maybe you can extend that

**Comment by yanzhang0219** [comment]
Sorry for the late reply. I updated luasnip and this is a big improvement. Changing choice won't trigger `InsertLeave` event so the diagnostics won't be updated each time when I keep selecting choices. 

Thank you very much for providing me these reference and suggestions. 😄

**Comment by L3MON4D3** [comment]
You're welcome :D
