### ISSUE TITLE
GOTO is not working because Gentoo is still using Lua 5.1

### ISSUE THREAD

**Issue by a-angelov-ca** [L3MON4D3/LuaSnip#263]
Hi,

I have an issue with LuaSnip/lua/luasnip/loaders/from_vscode.lua in Neovim using Gentoo and it is because the package there is still using Lua 5.1
The error is in line 72: goto continue

Is there a way to rewrite this part to not use GOTO?!

Thank you.

**Comment by leiserfg** [comment]
As per https://packages.gentoo.org/packages/app-editors/neovim  you can use luajit in gentoo.

**Comment by a-angelov-ca** [comment]
Switching to luajit fixed the issue.

Thank you.
