### ISSUE TITLE
coupling the whole code in a document after inserting a snip and formatting it

### ISSUE THREAD

**Issue by hemedani** [L3MON4D3/LuaSnip#265]
I'm copying and editing a snip from [your example](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua) and creating this one :  
```lua
		s(
			"llog",
			fmt(
				[[
            //Parameters: {2}
            console.info({1}, " ------- ");
			]],
				{
					i(1),
					rep(1),
				}
			)
		),
```
but when I used this snip in any document it's crashed and coupled the whole code after formatting the document.
for example, convert this code
```javascript
function sum(number1, number2) {
  return number1 + number2;
}

const mySum = sum(2, 5);

console.log(mySum);

const newSum = (num1, num2) => num1 + num2;

const resultNewSum = newSum(2, 7);

```

to this code :
```javascript
function sum(number1, number2) {
  return number1 + number2;
}

const mySum = sum(2, 5);

console.log(mySum);

const newSum = (num1, num2) => num1 + num2;

const resultNewSum = newSum(2, 7);

//Parameters: resultNewSum
function sum(number1, number2) {
  return number1 + number2;
}

const mySum = sum(2, 5);

console.log(mySum);

const newSum = (num1, num2) => num1 + num2;

const resultNewSum = newSum(2, 7);

//Parameters: resultNewSum
console.info(resultNewSum, ' ------- ');
```

**Comment by L3MON4D3** [comment]
Yeah, that's a known limitation :/

Luasnip tracks node-positions via extmarks, these get pushed around when formatting overwrites the entire buffer.
The only solution is to disable formatting or find a way to apply formatting only to changed regions of the buffer.

I'm going to close this as this issue is already tracked in #174 and #218.

**Comment by buschco** [comment]
Can I somehow tell LuaSnip to stop tracking anything?

**Comment by L3MON4D3** [comment]
Not really, if you want it to work :D
What do you want to achieve? Prevent this issue?

**Comment by buschco** [comment]
Maybe I am not understanding this issue. I achieved my desired behavior with this autocmd:

```
vim.api.nvim_create_autocmd({"InsertLeave"}, {
  pattern = {"*"},
  command = ":LuaSnipUnlinkCurrent"
})
```

My snippets only have one argument anyway, which will be copied to one or more places.
E.g.:
```
  s("action", {
    t("function "), 
    i(1),
    t({
      " ():ThunkAction {",
      "return (dispatch, getState) => {",
      "",
      "}",
      "}"
    })
  }),
```

I type `action`, select the suggestion from nvim-cmp and my cursor will be pushed to the `i(1)` position. I type something, leave insert and I am finished with the snippet workflow, able to save and format my buffer.

**Comment by L3MON4D3** [comment]
Oh, yeah that might also go some way to prevent these issues👍
They also can't (according to my understanding of the issue) occur in snippets without functionNodes
