### ISSUE TITLE
Getting `LuaSnip/lua/luasnip/util/environ.lua:16: attempt to index local 'pos' (a nil value)` after upgrading LuaSnip to latest version

### ISSUE THREAD

**Issue by dmbfm** [L3MON4D3/LuaSnip#269]
Hi!

I have a snippet that pastes the current file name:
```
    local function fname(_, _)
        return snip.env.TM_FILENAME
    end

    require("luasnip").snippets = {
        all = {
            s("fname", {
                f(fname, {}),
            }),
        },

       ....

```

After upgrading LuaSnip to the latest version I get this error whenever I try to use this snippet:
```
LuaSnip/lua/luasnip/util/environ.lua:16: attempt to index local 'pos' (a nil value)
```

I looked trough the breaking changes issue but I could not identify which breaking change is related to this error.

**Comment by L3MON4D3** [comment]
Hello!

For me it works with 
```lua
    local function fname(_, snip)
        return snip.env.TM_FILENAME
    end
```
(I'm stumped that it worked without passing `snip`, no idea what was going on there :D)

**Comment by dmbfm** [comment]
In fact, if I replace `fname` for something like 
```lua
local function fname(_, snip)
        return "some string"
    end

```
I still get the error. So I think it has something to do with 
```lua
 s("fname", {
                f(fname, {}),
            })
```

**Comment by L3MON4D3** [comment]
> Any Idea where this error could originate?

Tbh no, I'm not getting it at all :/

> Could it be related to this change? #81 (comment)

I don't think so, you're not using the condition-function.

Could you give me the exact steps that lead to the error?

**Comment by dmbfm** [comment]
> Could you give me the exact steps that lead to the error?

There isn't much more than that in my case. I just have this snippet that used to work and stopped working after running `:PackerUpdate`. I tried to create a minimal config file but I could not find an easy way to do that. I don't really know what I can do to give more information on how to reproduce this. My full configuration can be found here: https://git.sr.ht/~dfortes/nvim

**Comment by L3MON4D3** [comment]
> Could it be caused by the completion plugin? I still use [nvim-compe](https://github.com/hrsh7th/nvim-compe).

Ahhh yep, that's it :D

**Comment by dmbfm** [comment]
It could only be that :)

I was putting it out moving to another plugin but I will now.

Thanks!

**Comment by L3MON4D3** [comment]
You're welcome!
