### ISSUE TITLE
windows/dos line endings

### ISSUE THREAD

**Issue by marcusatiliusregulus** [L3MON4D3/LuaSnip#270]
**os:** windows 11
**nvim:** 0.6.1
**using**: honza/vim-snippets, hrsh7th/nvim-cmp, saadparwaiz1/cmp_luasnip

## reproduce:
on windows open a .dart file and write in insert mode `im<tab or whatever expands your snippets>`

## behaviour:
expanding a multiline snippet ends the lines with a visual `^M`
while manually inserted lines dont have this

## expected behaviour:
Either respect "fileformat" setting,
give a config option to specify which line endings to use when expanding a snippet
or somehow else determine the current behaviour of manual line-endings and mimic it.

</br>
If I missed how to do this, please comment...

**Comment by L3MON4D3** [comment]
Hmm, could you try if it also occurs when creating snippets in lua?
```lua
ls.snippets.all = {
	s("trig", {
		t({"line1", "line2"})
	})
}
```
(internally, multiline-strings are represented as tables, it'd be good to know if the incorrect termination comes from parsing or expanding)

**Comment by leiserfg** [comment]
I guess it's because we are always expanding with `\n` while when in  ff= `dos` we should use `\r\n`.

**Comment by L3MON4D3** [comment]
At least with `t({"line1", "line2"})` we don't touch the lines at all, they are just passed through to `nvim_buf_set_text()` afaict ([constructor](https://github.com/L3MON4D3/LuaSnip/blob/aac0f43cc90a8c493373a89549e8e0fade59aa3e/lua/luasnip/nodes/textNode.lua#L8-L14), [put_initial for textNode](https://github.com/L3MON4D3/LuaSnip/blob/229c0e70afd4b7f129366431f99baf427a1520db/lua/luasnip/nodes/node.lua#L52-L57), [put](https://github.com/L3MON4D3/LuaSnip/blob/aac0f43cc90a8c493373a89549e8e0fade59aa3e/lua/luasnip/util/util.lua#L225-L231)).
I suspect that it happens while parsing (the snipmate-parser [splits lines on `\n`](https://github.com/L3MON4D3/LuaSnip/blob/cfc0dc230475ee7c3cb45c4db1d5bafc85833cc2/lua/luasnip/loaders/from_snipmate.lua#L13), leaving a trailing `\r` on each line).

**Comment by marcusatiliusregulus** [comment]
@L3MON4D3 i've tried your example: it works without any problem

**Comment by leiserfg** [comment]
Then a solution should be to use "[\r\n]+" for the split instead.

**Comment by L3MON4D3** [comment]
Ah nice, yes that should do it :+1:

**Comment by marcusatiliusregulus** [comment]
@L3MON4D3 `dos-newline-fix` works. thanks so much!

**Comment by marcusatiliusregulus** [comment]
@L3MON4D3 ok, we celebrated too early: the problem now is the following: if you have a snippet which wants to add several newlines, then all of them are stripped. the problem is the regex used: it just takes everything that looks like a newline and removes it...

**Comment by L3MON4D3** [comment]
Ohhhh, ofc

**Comment by L3MON4D3** [comment]
We can probably get away with just clearing all of the `\r`s in the file?

**Comment by leiserfg** [comment]
No, because in ff="mac" the separator is '\r'  instead of '\n'

**Comment by L3MON4D3** [comment]
Damn okay, I'll add a function that just splits lines on `\r`, `\r\n`, `\n`.

**Comment by leiserfg** [comment]
Another option, replace "\r\n" with "\n" and then "\r" with "\n"

**Comment by L3MON4D3** [comment]
Yeah, that could work, too.
Another problem, IIRC windows also has no newline at the end of file (always?), meaning that [this](https://github.com/L3MON4D3/LuaSnip/blob/fdc1ebe4a58a08a0bb138274417b3f66171526cb/lua/luasnip/loaders/from_snipmate.lua#L14) (originally added to remove the trailing empty line on unix) is also problematic.

**Comment by leiserfg** [comment]
@L3MON4D3  EOL (^Z)   is  `26`, removing it instead of blindly removing the last character should do the work, I just don't have a snipmate file to test.

**Comment by L3MON4D3** [comment]
Okay, so find out what the line separator is, if it's `\r\n`, do nothing, if it's `\n` (or `\r`  too, probably, but I couldn't find anything confirming that) remove trailing `\n` (`\r`).

**Comment by L3MON4D3** [comment]
@marcusatiliusregulus it should work now, could you pull and try again?

**Comment by marcusatiliusregulus** [comment]
it gives this error:
```
Error executing vim.schedule lua callback: ...cker\start\LuaSnip/lua/luasnip/loaders/from_snipmate.lua:13: attempt to call field 'split_lines' (a nil value)
stack traceback:
        ...cker\start\LuaSnip/lua/luasnip/loaders/from_snipmate.lua:13: in function 'parse_snipmate'
        ...cker\start\LuaSnip/lua/luasnip/loaders/from_snipmate.lua:77: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by L3MON4D3** [comment]
Whoops, yes you're right. Should be fixed now.

**Comment by marcusatiliusregulus** [comment]
seems to work now! great work, thanks
