### ISSUE TITLE
Default text is cleared at jump

### ISSUE THREAD

**Issue by Nocturne-K** [L3MON4D3/LuaSnip#272]
Hi, this plugin works perfect, but when jumping without anything typed it clears the default text, which is kind of inconvenient. I often literally want "size_t" to be the type of loop variable and "i" to be its name. Is it an expected behavior or a bug to clear the default text?
I'm using this with nvim-cmp and friendly-snippets.

**Comment by L3MON4D3** [comment]
Hm, I cannot reproduce with the `forr` c-snippet from `friendly-snippets`. Could you give me more details?

**Comment by Nocturne-K** [comment]
The most related file is need_install/.config/nvim/lua/completion.lua . I guess there are some mistakes in it.

**Comment by L3MON4D3** [comment]
I don't personally use cmp to set the luasnip-keybinds, could you try if the text is also cleared if jump, expand are set separately?
```vim
imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>' 
inoremap <silent> <S-Tab> <cmd>lua require'luasnip'.jump(-1)<Cr>

snoremap <silent> <Tab> <cmd>lua require('luasnip').jump(1)<Cr>
snoremap <silent> <S-Tab> <cmd>lua require('luasnip').jump(-1)<Cr>
```

**Comment by Nocturne-K** [comment]
It turns out that I only mapped <CR> in insert mode but not in select mode. As a result, when I press the enter key, neovim thinks that I want to replace the text. Then it switches to insert mode, and find out that <CR> in insert mode should trigger `luasnip.expand_or_jump()` , which leads to the weird behavior. I just added select-mode key mapping and the problem is solved. Sorry for bothering.

**Comment by L3MON4D3** [comment]
Ahh ofc

> Sorry for bothering

No problem, that's what issues are for :D
The next time someone has a similar problem they might find the solution here
