### ISSUE TITLE
Lost dollar sign with self-defined snippet

### ISSUE THREAD

**Issue by kuang22** [L3MON4D3/LuaSnip#273]
I wrote a snippet definition, and something weird happened.
```
  "Math inline":{
    "prefix": "$",
    "body": [
      "$ $1 $$0"
    ],
    "description": "Math inline"
  },
```
When I put the body with '$' as the first char, the first dollar sign disappears when the snippet is triggered, and when I put a <Space> before the first dollar in the definition, then it works fine. I guess this might related to Luasnip.

https://user-images.githubusercontent.com/42860568/150651507-20d98535-0e05-4c3e-8ba8-96fe7f97a8f4.mp4

**Comment by L3MON4D3** [comment]
The parser is supposed to parse snippets as defined [here](https://microsoft.github.io/language-server-protocol/specification#snippet_syntax), my understanding is that `$` should generally be escaped if it isn't part of a placeholder.
Does it work as `\$ $1 \$$0`?

**Comment by kuang22** [comment]
> The parser is supposed to parse snippets as defined [here](https://microsoft.github.io/language-server-protocol/specification#snippet_syntax), my understanding is that `$` should generally be escaped if it isn't part of a placeholder. Does it work as `\$ $1 \$$0`?

Sure I have tried with escape, but it doesn't work anyway. 
BTW, the definition in friendly-snippets/snippets/latex/vscode-latex-snippets.json has similar definitions like
```json
    "Inline Math": {
        "prefix": ["mathinline", "\\mathinline"],
        "body": [
            "$ $1 $$0"
        ],
        "description": "Insert inline Math Environment."
    },
    "Centered Math": {
        "prefix": ["mathcentered", "\\mathcentered"],
        "body": [
            "$$ $0 $$"
        ],
        "description": "Insert centered Math Environment."
    },
```
This has exactly same problem just as my self-defined snippet starts with a '$'.

**Comment by kuang22** [comment]
After more tests, I think the problem occurs whenever the string starts with a dollar BUT NOT followed by a number.
I think it might be that this dollar as the first char NOT followed by a number is discarded, and when this dollar is not the first char, then the problem won't occur.

Thus, I think it might be a bug in the interpreter code.

https://user-images.githubusercontent.com/42860568/150670625-8efd4274-d012-41ee-b8af-83550a9c4d9c.mp4

**Comment by L3MON4D3** [comment]
As I said, the parser was written with the assumption that `$` is escaped or part of a placeholder, so anything might go wrong there (whether that assumption is correct is another matter of course).
`ls.lsp_expand("\\$ $1 \\$")` works correctly (for me), could you show your attempts with the escaped `$`?

(The parser will be replaced soon-ish by the one built into neovim, which is why I'd rather not spend too much time changing stuff around there)

**Comment by kuang22** [comment]
> As I said, the parser was written with the assumption that `$` is escaped or part of a placeholder, so anything might go wrong if `$` isn't escaped (whether that assumption is correct is another matter of course). `ls.lsp_expand("\\$ $1 \\$")` works correctly (for me), could you show your attempts with the escaped `$`?
> 
> (The parser will be replaced soon-ish by the one built into neovim, which is why I'd rather not spend too much time changing stuff around there)

"\\$ $1 \\$" works for me, thx, befor I use "\$ $1 \$", I guess I did not figure out the difference between one backslash and two backslashes before. Thx again and sorry to botter :)

**Comment by L3MON4D3** [comment]
Ahh I see, no worries :)
