### ISSUE TITLE
Cannot Get setTimeout snippet to work

### ISSUE THREAD

**Issue by jrock2004** [L3MON4D3/LuaSnip#274]
Trying to write a snippet for `setTimeout` in JS and getting errors.

```
s(
	"setTimeout",
	fmt(
		[[
                setTimeout(() => {
                    {1}
                 }, {2})
                ]],
	         rep(1), rep(2) }
	)
),
```

Here is the error when I start Neovim

```
Error detected while processing /Users/jcostanzo/.dotfiles/files/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:148: ...
ite/pack/packer/start/LuaSnip/lua/luasnip/extras/fmt.lua:137: Found unescaped { inside placeholder; format
[18:22]="{
  {"
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/impatient.nvim/lua/impatient/profile.lua:148: in function 'require'
        /Users/jcostanzo/.config/nvim/init.lua:24: in main chunk
```

**Comment by L3MON4D3** [comment]
There's a few small mistakes in that snippet:
* by default any occurence of `{some_text}` is replaced by a node. It complains about the unescaped `{` in `"setTimeout (() => {` and first `}` in `"}, {2})"`
* fmt's prototype is `fmt(format: string, nodes: table)`, all nodes passed to it have to be wrapped into a table.
* `rep(n)` mirrors/repeats the `n`th jumpable node, but there are no nodes to mirror.

```lua
s(
	"setTimeout",
	fmt(
		[[
		setTimeout(() => {{
			{1}
		}}, {2})
		]], {
			i(1), i(2)
		}
	)
)
```
, where `i` is `ls.insertNode`, should work.

**Comment by jrock2004** [comment]
Thanks. Still trying to grasp the documentation. Thank you
