### ISSUE TITLE
How to nest choice nodes (sub-choices) ?

### ISSUE THREAD

**Issue by johnmathews** [L3MON4D3/LuaSnip#275]
I'd like to make the options for a choice node dependent on what was chosen for a previously selected choice node in the same snippet.

For example, I'm trying to select a category (Big or small) and a subcategory (blue and green are in big, red and yellow are in small).

What's the best way to do this? I'm aware there are other types of node, which I suspect is what is required, but I can't understand from the documentation how to approach this problem. 

If I've selected the "big" category, I only want the "blue" or "green" choices to be available, and if I've selected the "small" category, I only want the "red" or "yellow" categories to be available.

**Comment by leiserfg** [comment]
A dynamic node surrounding the second choice should do the job.

**Comment by johnmathews** [comment]
Thanks @leiserfg, could you link me to an example?

**Comment by L3MON4D3** [comment]
I'd recommend reading through the documentation for [`functionNode`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#functionnode) and [`dynamicNode`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#dynamicnode), that should make it clearer.

**Comment by L3MON4D3** [comment]
(Using a dynamicNode is better only if there's lots of stuff that doesn't depend on the choice from the first choiceNode. If there's little to duplicate, simply nesting (as you say in the title) would be more straighforward.
Nesting choiceNodes works without issues, you only might have to insert an additional (for example) insertNode to be able to change the outer choice, which might otherwise be superseded by the inner choice when changing choices.)

**Comment by johnmathews** [comment]
Thank you both! After rereading the dynamicNode and functionNode documentation it made more sense. This is the complete snippet I was working on - meta data generation for blog articles written in markdown:

```lua
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node

local date = function()
	return { os.date("%Y-%m-%d %H:%M:%S") }
end

local slugify = function(args, _)
	local text = args[1][1]
	text = string.lower(text)
	text = string.gsub(text, "[%p%c]", "")
	text = string.gsub(text, "^%s*(.-)%s*$", "%1")
	text = string.gsub(text, "[%s]", "-")
	return text
end

local catChooser = function(args, snip, table)
  if args[1][1] == "Technical/" then
    return c(3, {
      t("Developer Tools"),
      t("Data"),
      t("Web"),
      t("Other"),
      t("Cryptocurrencies"),
      t("Engineering"),
    })
  else
    return c(3, {
      t("Photographs"),
      t("Entrepreneurship"),
      t("Journal"),
      t("Learning"),
      t("Social"),
      t("Other"),
    })
  end
end

luasnip.snippets = {
  all = {},
  markdown = {
	s("meta", {
		t({ "Title: " }),
		i(1),
		t({ "", "Slug: " }),
		f(slugify, { 1 }),
		t({ "", "Date: " }),
		f(date, {}),
		t({ "", "Category: " }),
		c(2, {
			t("Technical/"),
			t("Non-technical/"),
		}),
		d(3, catChooser, {2}),
		t({ "", "Tags: " }),
		i(0),
		t({ "", "", "" }),
	}),
  }
}
```

**Comment by L3MON4D3** [comment]
Oh, nice :+1:
Just for reference, that snippet could also be written as
```lua
s("meta", {
		t({ "Title: " }),
		i(1),
		t({ "", "Slug: " }),
		f(slugify, { 1 }),
		t({ "", "Date: " }),
		f(date, {}),
		t({ "", "Category: " }),
		c(2, {
			{
				-- put an insertNode here so it's possible
				-- to change the outer choice.
				-- (without it, the cursor would always jump
				-- directly into the inner choiceNode).
				i(1), t("Technical/"), c(2, {
					t("Developer Tools"),
					t("Data"),
					t("Web"),
					t("Other"),
					t("Cryptocurrencies"),
					t("Engineering"),
				})
			},
			{
				i(1), t("Non-technical/"), c(2, {
					t("Photographs"),
					t("Entrepreneurship"),
					t("Journal"),
					t("Learning"),
					t("Social"),
					t("Other"),
				})
			}
		}),
		t({ "", "Tags: " }),
		i(0),
		t({ "", "", "" }),
	}),
```
