### ISSUE TITLE
Loading external snippets closes folds

### ISSUE THREAD

**Issue by cyhyraethz** [L3MON4D3/LuaSnip#278]
I use fold markers for some of my dotfiles and have a bash function that searches a string in those files and opens folds with `zv` so that the searched string is visible, the relevant line of which being `nvim +/"$*" +"normal! zvzz" +":nohl" $file`.

Since I added friendly-snippets to my luasnip setup this no longer works. Or rather, it still works, but the fold is then immediately closed, and I have to `zvzz` again to reopen the fold and center the text.

I have narrowed it down to [this line](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/init.lua#L531) `vim.cmd([[doautocmd User LuasnipSnippetsAdded]])` in the `refresh_notify` function. If I comment that line out the problem no longer occurs, but friendly-snippets are still loaded and available for use.

**Comment by L3MON4D3** [comment]
That line is for signaling other plugins which cache information on snippets (eg. `cmp_luasnip`) that their cache might be out of date.
I just did a quick check, for me the folds still open, even with loading/lazy-loading the snippets from `friendly-snippets` :/

https://user-images.githubusercontent.com/41961280/151658458-b881398d-d754-443e-956f-f36cbdcc14cd.mp4

Could you try creating a minimal config that reproduces the error?

**Comment by cyhyraethz** [comment]
This config should be able to reproduce the error.

```lua
local luasnip_status, luasnip = pcall(require, 'luasnip')
if luasnip_status then
  require('luasnip.loaders.from_vscode').load({
    paths = { vim.fn.stdpath('data') .. '/site/pack/packer/start/friendly-snippets' },
  })
end

local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
local install_url = 'https://github.com/wbthomason/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  packer_bootstrap = vim.fn.system({ 'git', 'clone', '--depth', '1', install_url, install_path })
  vim.cmd('packadd packer.nvim')
end

local packer_status, packer = pcall(require, 'packer')
if packer_status then
  return packer.startup({
    function(use)
      use('wbthomason/packer.nvim')
      use('hrsh7th/nvim-cmp')
      use('l3mon4d3/luasnip')
      use('saadparwaiz1/cmp_luasnip')
      use('rafamadriz/friendly-snippets')
      if packer_bootstrap then
        packer.sync()
      end
    end,
  })
end
```

**Comment by cyhyraethz** [comment]
The problem seems to go away when the friendly-snippets code block is moved to the bottom of the config file (after the packer.startup code block).

This surprised me as I have those in separate files in my own config, and the file where friendly-snippets is loaded is required _after_ the file with packer.startup.

**Comment by L3MON4D3** [comment]
Very weird, I still cannot reproduce, the folds open perfectly fine.
What version of neovim are you on? My tests were done on `NVIM v0.7.0-dev+970-g525a8afe28` (could be relevant as triggering an autocommand really _shouldn't_ affect folds (I think) there might have been some fixes if you experienced the issue on an older version.

https://user-images.githubusercontent.com/41961280/151678620-ffa45dd8-a147-4f13-8e5c-af20f57e23ad.mp4

**Comment by L3MON4D3** [comment]
> The problem seems to go away when the friendly-snippets code block is moved to the bottom of the config file (after the packer.startup code block).

Now that you mention it, (and I'm no expert in how the neovim startup works, but ) shouldn't the plugins only be `require`d after packer has loaded them (added their paths to rtp)?

**Comment by cyhyraethz** [comment]
I'm using  `NVIM v0.6.1`.

The attached config also reproduces the problem and is more similar to my own config, with friendly-snippets loaded from `setting.lua`, which is `require`d _after_ `plugin.lua` (which containers the `packer.startup` code) from `init.lua`.

[nvim.zip](https://github.com/L3MON4D3/LuaSnip/files/7964895/nvim.zip)

https://user-images.githubusercontent.com/45051951/151680048-66e95ec7-6906-461a-a395-dbb759e319f7.mp4

**Comment by cyhyraethz** [comment]
I'm able to prevent the problem by loading friendly-snippets at the bottom of `plugin.lua`, but I would prefer to be able to keep it with all the rest of my plugin settings in `setting.lua` if possible.

I don't understand why it makes a difference either. It seems like having it at the bottom of `plugin.lua` should be the same as having it in `setting.lua`, which is `require`d after `plugin.lua`.

**Comment by L3MON4D3** [comment]
> I'm able to prevent the problem by loading friendly-snippets at the bottom of `plugin.lua`, but I would prefer to be able to keep it with all the rest of my plugin settings in `setting.lua` if possible.
> 
> I don't understand why it makes a difference either. It seems like having it at the bottom of `plugin.lua` should be the same as having it in `setting.lua`, which is `require`d after `plugin.lua`.

Totally get that, could you try if the issue still occurs when buildin neovim from source? Maybe that's a bug that has been fixed between 0.6.1 and current master...

**Comment by cyhyraethz** [comment]
The issue still occurs with `NVIM v0.7.0-dev+976-g9aaf7a2b4`

**Comment by L3MON4D3** [comment]
Mhmm :/
How about removing `cmp_luasnip`? It's the only (IIRC) place that listens to the `LuasnipSnippetsAdded`-event, and I'd be surprised if the `doautocmd` itself opens the folds.

**Comment by cyhyraethz** [comment]
The problem does not occur after removing `cmp_luasnip`.

I think it's [these lines](https://github.com/saadparwaiz1/cmp_luasnip/commit/c792dd153652c3fcddbdc9bf77ccd0e96ecaddf2?diff=unified) that are causing the problem; it does not occur after removing [this line](https://github.com/saadparwaiz1/cmp_luasnip/blob/master/after/plugin/cmp_luasnip.lua#L8), which triggers [this function](https://github.com/saadparwaiz1/cmp_luasnip/blob/master/lua/cmp_luasnip/init.lua#L27-L31).

**Comment by L3MON4D3** [comment]
Is it possible that an error occurs in that function? Could you wrap the call in a `pcall` and see if that fixes it?

**Comment by L3MON4D3** [comment]
I could see the `latest_load_ft` being `nil`, maybe add some check for that...

**Comment by cyhyraethz** [comment]
The file I'm testing this on is a `sh` file. When I add a print statement the value of the `ft` (assigned the value of `latest_load_ft`) is usually `yaml`, but sometimes `eruby`, `gdscript`, `java`, etc.

I tried adding some checks and wrapping the require statements with `pcall` and the problem persists.

![Screenshot from 2022-01-30 03-35-28](https://user-images.githubusercontent.com/45051951/151698040-e474a194-4b7e-4c44-9fa5-4ec58e841267.png)

![Screenshot from 2022-01-30 03-35-45](https://user-images.githubusercontent.com/45051951/151698041-1172ce91-8204-4062-8b22-1de090832643.png)

**Comment by L3MON4D3** [comment]
> The file I'm testing this on is a `sh` file. When I add a print statement the value of the `ft` (assigned the value of `latest_load_ft`) is usually `yaml`, but sometimes `eruby`, `gdscript`, `java`, etc.

I think that's to be expected, all different snippet-files provided by `friendly-snippets` are loaded in non-deterministic order (using `libuv`-callbacks) (there might be a bit of an error on luasnips part here, but unrelated to this problem: if autocommands aren't executed immediately (not sure whether they are), some filetypes would never get reloaded)

> I tried adding some checks and wrapping the require statements with `pcall` and the problem persists.
> 
> ![Screenshot from 2022-01-30 03-35-28](https://user-images.githubusercontent.com/45051951/151698040-e474a194-4b7e-4c44-9fa5-4ec58e841267.png)
> 
> ![Screenshot from 2022-01-30 03-35-45](https://user-images.githubusercontent.com/45051951/151698041-1172ce91-8204-4062-8b22-1de090832643.png)

Okay, I've no more ideas where the bug could be coming from.

You could open an issue in neovim (I don't think luasnip is doing anything particularly wrong here), maybe try creating a smaller config which doesn't rely on `luasnip`/`cmp_luasnip`, but still reproduces the bug, that should help with tracking it down.

**Comment by cyhyraethz** [comment]
I figured out why you weren't able to reproduce the problem with my config. The `a.cpp` test file you were using didn't have the `// vim:foldmethod=marker:foldlevel=0` modeline at the top of the file.

It seems that removing `:foldlevel=0` from the modeline solves the problem, even if I leave `// vim:foldmethod=marker` (which is the important part anyway).

I stlil don't understand what's happening here, but I'm going to remove `:foldlevel=0` from the files that I've been experiencing the problem with and close the issue.

Thank you for all your time and effort helping me troubleshoot and resolve this issue, especially since it may not have even been caused by your plugin (which is great btw; seriously, love LuaSnip).

**Comment by L3MON4D3** [comment]
> I figured out why you weren't able to reproduce the problem with my config. The `a.cpp` test file you were using didn't have the `// vim:foldmethod=marker:foldlevel=0` modeline at the top of the file.
> 
> It seems that removing `:foldlevel=0` from the modeline solves the problem, even if I leave `// vim:foldmethod=marker` (which is the important part anyway).
>
> I stlil don't understand what's happening here, but I'm going to remove `:foldlevel=0` from the files that I've been experiencing the problem with and close the issue.

Ah, nice, at least it works for now :+1:

> Thank you for all your time and effort helping me troubleshoot and resolve this issue, especially since it may not have even been caused by your plugin (which is great btw; seriously, love LuaSnip).

You're welcome, and thanks for the kind words :D
