### ISSUE TITLE
[bug] luasnip not loading snippets on restart

### ISSUE THREAD

**Issue by IamAfnanMalik** [L3MON4D3/LuaSnip#279]
Hey I have some issue with luasnip when i add `require("luasnip.loaders.from_vscode").load()` to my luasnip config and restart neovim then luasnip does not load the snippets and when i source my luasnip config file with `:so %` then loads all the snippets

**Comment by IamAfnanMalik** [comment]
[My config](https://github.com/Iamafnan/my-nvimrc)

**Comment by L3MON4D3** [comment]
Sounds like `luasnips.lua` isn't sourced during startup, could you try putting some `print`s or similar to check that the `load` is actually executed?
You can check if any snippets are loaded via `:LuaSnipListAvailable`, maybe try that to make sure that there are actually no snippets loaded.

**Comment by IamAfnanMalik** [comment]
Hey there was some issue with sourcing now I have added `config` parameter to the use function in my `plugins.lua` and now it's print the string but luasnip is not loading the snippets

**Comment by IamAfnanMalik** [comment]
I have updated the repository if you wanna see my changes you can see that

**Comment by L3MON4D3** [comment]
AFAICT the file _should_ have been sourced earlier as well, with the `require("afnan.luasnips")`.
Does luasnip load snippets at all with that `load`-call?
The directory-layout for snippets [you had earlier](https://github.com/Iamafnan/my-nvimrc/tree/fc9e708446de1213d5c9dab7c91dba08cce3e4d2/snippets) doesn't work with luasnip, luasnip needs a `package.json` to find the snippet-files (you can try copying and adapting [the structure from `friendly-snippets`](https://github.com/rafamadriz/friendly-snippets) if you haven't yet)

**Comment by Iamafnan** [comment]
Oh thanks i forgot that 😅

**Comment by IamAfnanMalik** [comment]
Oh sorry i forgot that 😅
