### ISSUE TITLE
Snipet aint showing up

### ISSUE THREAD

**Issue by bryant-the-coder** [L3MON4D3/LuaSnip#280]
https://github.com/bryant-the-coder/NvHack/blob/aa808790e000ca15f45b218595e8322d7c622b43/lua/plugins/snippets.lua#L80

this is the line where i place the snippets. Html works but it doesnt work for lua, js and git. Is there something i did wrong?

**Comment by bryant-the-coder** [comment]
and i use friendly snippets. but i cant seem to see it working

**Comment by L3MON4D3** [comment]
Does it work if `load()` is called after the lua-definitions?

**Comment by bryant-the-coder** [comment]
no. luasnip also behave very weirdly. when i tab to complete. it tab to other line of code. besides it also auto escape when i type `hi`. when i wanna type `i` it auto escape like it is the escape key. it doesnt occur on vsnip. idk if this is luasnip or nvim cmp ¯\_(ツ)_/¯

**Comment by bryant-the-coder** [comment]
currenly i switch back to vsnip. i will switch back to luasnip after this prob is solve. idk if it is my setup is wrong or what. but i follow people's conf which they have no issue with it. i m on windows btw

**Comment by L3MON4D3** [comment]
> no. 

Weird, looks like everything is configured correctly, but I cannot reproduce, for me everything loads correctly.

> luasnip also behave very weirdly. when i tab to complete. it tab to other line of code.

Luasnip will not automatically exit snippets when INSERT is exited, but it's possible to change that via settings (check at the bottom of the readme).

> besides it also auto escape when i type `hi`. when i wanna type `i` it auto escape like it is the escape key. it doesnt occur on vsnip. idk if this is luasnip or nvim cmp ¯_(ツ)_/¯

That's weird, but I cannot reproduce :/

> currenly i switch back to vsnip.

vsnip is a fine choice if you don't need the more advanced capabilities luasnip offers :+1:
You might also want to check out nvim-snippy, it's much like vsnip (more plug-and-play than luasnip) and uses the more readable (IMO) snipmate-format for autoring snippets

**Comment by bryant-the-coder** [comment]
hey can u tell me bout the benefits of using luasnip? i see many people using it¯\_(ツ)_/¯

**Comment by bryant-the-coder** [comment]
i mean idk what is the meaning of `s`, `t` etc...

**Comment by L3MON4D3** [comment]
> hey @L3MON4D3 can u tell me bout the benefits of using luasnip? i see many people using it ¯_(ツ)_/¯

The biggest benefit is that it's possible to generate part of the snippets (text as well as interactive placeholders) based on user input, eg.

https://user-images.githubusercontent.com/41961280/122515860-5179fa00-d00e-11eb-91f7-331893f61fbf.mp4

or

![](https://user-images.githubusercontent.com/41961280/145810589-f68259a1-a1a6-4e39-87ab-4ab4d7112cc5.gif)

The downside is that some familiarity with lua is (pretty much) necessary when writing these snippets.

`DOC.md` and `Examples/snippets.lua` are good places to get into writing snippets in lua.

**Comment by bryant-the-coder** [comment]
i hv refer to the doc... but i m not really know what is going on lmaoo... mayb explain a lil? i can count myself as a intermediate lua user i guess?

**Comment by bryant-the-coder** [comment]
the s, t l, node stuff

**Comment by L3MON4D3** [comment]
I improved the docs a bit, is the [basics](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#basics)-section more understandable now?

**Comment by bryant-the-coder** [comment]
will read tmr and let u know.. currenly 12 am lmaoo good night

**Comment by bryant-the-coder** [comment]
idk the stuff starting from here

`${1:First jump} :: ${2: ${3:Second jump} : ${4:Third jump}}`

**Comment by L3MON4D3** [comment]
:D
Ahh yeah, they're rather complicated.
Did you understand what's going on in the first example? If not, I'd recommend looking at `functionNode` again, the `args` and `parent` are explained there in some more detail.

**Comment by bryant-the-coder** [comment]
btw insertnode and testnode looks the same imo

**Comment by L3MON4D3** [comment]
Oh, `insertNode` is for inserting text that should be edited, `textNode` is for text that won't change. I'll put that in the first sentence for `insertNode`, right now it only says something about jumping...

**Comment by bryant-the-coder** [comment]
i will read more and try to understand. is there any better place to contact u besides here?

**Comment by L3MON4D3** [comment]
Oh, you can message the matrix-room for luasnip, anything I explain there is also more visible, so that'd be a plus :D

**Comment by bryant-the-coder** [comment]
i asked some ques... sometimes it is ignored⊙﹏⊙

**Comment by L3MON4D3** [comment]
Ask in the luasnip-room, I try to answer every question there :)

**Comment by bryant-the-coder** [comment]
ok :)

**Comment by bryant-the-coder** [comment]
https://user-images.githubusercontent.com/92417638/152707176-9c28f46f-3035-450b-b2d9-48fd1e7f4503.mp4

@L3MON4D3 this is what i m talking about. i hv everything setup right. but it doesnt work as expected. idk if this is a bug or my prob 
¯_(ツ)_/¯

**Comment by bryant-the-coder** [comment]
https://user-images.githubusercontent.com/92417638/152707496-ee55af26-7a67-4d78-911c-6e74854384e6.mp4



@L3MON4D3 this is what i m talking about. i hv everything setup right. but it doesnt work as expected. idk if this is a bug or my prob 
¯_(ツ)_/¯

**Comment by bryant-the-coder** [comment]
After some tweaks, it was neogen problem. I will keep in touch with you :)

**Comment by bryant-the-coder** [comment]
https://user-images.githubusercontent.com/92417638/152935814-3ed60975-bbaf-493e-8ded-68a97bfda4cc.mp4


https://user-images.githubusercontent.com/92417638/152935827-5ece5549-c37e-4b42-b5f6-124d1254dbde.mp4
