### ISSUE TITLE
vim-snippets snipmate like snippets does not expand iterpolation

### ISSUE THREAD

**Issue by voyeg3r** [L3MON4D3/LuaSnip#283]
I was able to set the path to the vim-snippets and load them like this:

```
require("luasnip.loaders.from_snipmate").load({
  paths = {
    vim.fn.stdpath('config') .. '/snippets',
  }
})
```

But the snippet "date", wich is:

```
snippet date
	`strftime("%Y-%m-%d")`
```

does not expand the date. What I am doing wrong?

If is not a feature yet, could it be someday?

**Comment by L3MON4D3** [comment]
You're doing nothing wrong, it just isn't supported yet.

> If is not a feature yet, could it be someday?

definitely :D

**Comment by L3MON4D3** [comment]
soooooooooooooooooooooo, with the current master it should work automatically for snippets loaded via `loaders.from_snipmate`. `ls.parser.parse_snipmate` can be used otherwise.
