### ISSUE TITLE
[New User] Cant get luaSnip to work

### ISSUE THREAD

**Issue by LamprosPitsillos** [L3MON4D3/LuaSnip#289]
@tjdevries just made an amazing video on Luasnip and i wanted to try it for my self.
I just *copied his config , changed some keys ,but nothing happens when i press the keybind to jump.

```lua
local ls = require "luasnip"
local types = require "luasnip.util.types"
ls.config.set_config {
  history = true,
  updateevents = "TextChanged,TextChangedI",
  enable_autosnippets = true,
  ext_opts = {
    [types.choiceNode] = {
      active = {
        virt_text = { { "<-", "Error" } },
      },
    },
  },
}
vim.keymap.set({ "i", "s" }, "<C-l>", function()
  if ls.expand_or_jumpable() then
    ls.expand_or_jump()
  end
end, { silent = true })

vim.keymap.set({ "i", "s" }, "<C-h>", function()
  if ls.jumpable(-1) then
    ls.jump(-1)
  end
end, { silent = true })

vim.keymap.set("i", "<c-L>", function()
  if ls.choice_active() then
    ls.change_choice(1)
  end
end)
```

Neovim Ver : NVIM v0.7.0-dev+923-gecec95712

**Comment by L3MON4D3** [comment]
Hey, glad to have you.
Did you add any snippets (eg. `ls.snippets = {...}`)?
You can list available snippets via `:LuaSnipListAvailable`

**Comment by LamprosPitsillos** [comment]
I don't know what i changed but it works now, sorry for this empty issue, maybe while trying to configure it i broke something by accident. Thanks for the quick reply anw!
