### ISSUE TITLE
Logic of visual selection in insert mode

### ISSUE THREAD

**Issue by danymat** [L3MON4D3/LuaSnip#290]
Hello ! 

As a user of your plugin since nvim-compe, I cannot express my enough my gratitude.
I'm the creator of Neogen plugin, and I would want to use a similar feature that you implemented, which is doing visual selection on  insert mode.
I think that the code responsible for it is:

https://github.com/L3MON4D3/LuaSnip/blob/5a6a1503fc6b005737fc823e1cb90ce86249c2a0/lua/luasnip/nodes/insertNode.lua#L97-L133

Can you confirm if so? What are the benefits and drawbacks of the method ?
It's a bit sad that the vim api does not provide a function for it

**Comment by L3MON4D3** [comment]
> As a user of your plugin since nvim-compe, I cannot express my enough my gratitude.

Ay, that's nice to hear :)

Yes, that's the code resposible for visual selection (and yes, it'd be much nicer to do directly).
A slight annoyance is that `selection` affects where the selection ends, so there needs to be a check for that :/
There's also that the `feedkeys` won't execute the keys right away, so if you need to do checks like `mode() == "v"` immediately after `feedkeys`, those could return wrong results, but apart from those two it works pretty well.

Another topic, are you still interested in integrating Luasnip in Neogen (even just optionally, maybe by exposing a function that is responsible for expanding/inserting the result from the generator)? It's now possible to expand a snippet at any position in the buffer, not just the cursor.

**Comment by danymat** [comment]
> Yes, that's the code resposible for visual selection (and yes, it'd be much nicer to do directly).
A slight annoyance is that selection affects where the selection ends, so there needs to be a check for that :/
There's also that the feedkeys won't execute the keys right away, so if you need to do checks like mode() == "v" immediately after feedkeys, those could return wrong results, but apart from those two it works pretty well.

Oh nice, I will try to take that into account, and provide a similar feature

> Another topic, are you still interested in integrating Luasnip in Neogen (even just optionally, maybe by exposing a function that is responsible for expanding/inserting the result from the generator)? It's now possible to expand a snippet at any position in the buffer, not just the cursor.

I think it can be a great addition in fact, and I think it'll allow users to choose if they want the "native" jump or luasnip one. I don't want to make it default, as I don't want users to have an other requirement than nvim-treesitter. But integrating luasnip as a optional replacement for jumps is a great idea.
Do you have any reference how I could use luasnip for creating a snippet for a position in the buffer ?

**Comment by L3MON4D3** [comment]
> I don't want to make it default, as I don't want users to have an other requirement than nvim-treesitter.

Completely agree :+1:

> Do you have any reference how I could use luasnip for creating a snippet for a position in the buffer?

Can't link the exact line, but look for `snip_expand` (or `lsp_expand`) in [this Section](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#api-reference).
The gist is
```lua
ls.lsp_expand(
	"some text${1:a placeholder}",
	{
		-- line, col (`col` in bytes, not displaycolumns)
		pos = {0,0}
	}
)

-- or alternatively
ls.snip_expand(
	-- doesn't need a trigger, will be expanded directly
	s("", {
		t("some text"),
		i(1, "a placeholder")
	}),
	{
		-- in bytes, not columns
		pos = {0,0}
	}
)
```

**Comment by danymat** [comment]
Thanks very much ! I will try to come up with a Luasnip embed after I manage the default visual selection

**Comment by L3MON4D3** [comment]
Sounds great :+1:
Let me know if you run into any issues, I'll be happy to help :)

**Comment by L3MON4D3** [comment]
FYI I just reworked the [select-code](https://github.com/L3MON4D3/LuaSnip/blob/8f2480d7a8c23c164429f2e4b487f28fc9a72d4b/lua/luasnip/util/util.lua#L117-L175), the previous versions cannot really deal with langmaps and similar settings.
