### ISSUE TITLE
ext_opt virtual text doesn't get removed

### ISSUE THREAD

**Issue by shadmansaleh** [L3MON4D3/LuaSnip#298]
### Problem

I have exp_opts set to show virtual text on choice nodes like following
```lua
  ext_opts = {
    [types.choiceNode] = {
      active = {
        virt_text = { { "ChoiceNode", "Comment" } },
      },
    },
  },
```
It shows ChoiceNode as virtual text when I'm on a choice node . It works as expected if I go fill out the snippet node by node and removes the virtural text when snippet has been completely filled out.

But if I `<esc>` out of the snippet without completely filling it out. The virtual text remains . Then if I delete the line/s of the partially filled snippet the vertual text just jumps previous line :/

### How to reproduce
1. enable virtual text on choice node (most likely same issue on other nodes ext_opt too I'm not sure how to set other nodes yet :D)
2. Get a simple snippet with choice node . You can use the one I was using
```lua
ls.snippets = {
  lua = {
    s({trig='req'}, {c(1, {
        fmt("require('{}')", { r(1, 'module') }),
        fmt("local {} = require('{}')", { rep(1), r(1, 'module') })}
        )}, {stored={module = i(1, "module")}})
  }
}
```
3. trigger the snippet .
4. press `<esc>` to exit the snippet .
5. delete the snippet created line `dd`

### Thanks
Thanks for luasnip .  I'm still exploring it's capabilities and it seems great . This virtual text issue just been a minor annoyance .

**Comment by L3MON4D3** [comment]
Could you check if the fix from #297 works for you as well? :D

**Comment by shadmansaleh** [comment]
> And since after <esc> luasnip.jump no longer works after `<esc>` I assume I'm out of the snippet ?

Actually one more thing on that note, I have history enabled . If I complete the snippet I can go back to it with `luasnip.jump(-1)` but if I `<esc>` while in middle of a snippet `luasnip.jump(-1)` no longer does anything . Is this expected behavior or a bug ?

**Comment by shadmansaleh** [comment]
Huh . It seems to not happen after a neovim restart . Sorry again . I think I'm fine as long as snippet clear also clears the virtual text . You should consider having `TextChanged` as default value of `delete_check_events` .

**Comment by L3MON4D3** [comment]
`delete_check_events` isn't set by default mainly because it's a bit of work each `TextChanged`, and I'd like to keep luasnip as light as possible by default.
I'll think about it :+1:
