### ISSUE TITLE
Question: Would you be willing to use a lua formatter?

### ISSUE THREAD

**Issue by tjdevries** [L3MON4D3/LuaSnip#30]
Would you be open to using https://github.com/JohnnyMorganz/StyLua on this project? I want to contribute some stuff, but your lua style is like the opposite of what I have set up for all my other lua projects, so it makes it hard to write it the right way for this project :laughing: 

Stylua supports using tabs and all that, so if you want to keep doing that, that's totally fine with me, you (or I in a PR) could just add a `stylua.toml` file in the base of the repo and then I don't have to worry about messing up your style haha

**Comment by L3MON4D3** [comment]
Sounds like a great idea! I'll see what its opinions on lua style are and get back to you :D

**Comment by L3MON4D3** [comment]
Looks pretty nice, thanks for your input. I'll push the formatted files+config momentarily.
