### ISSUE TITLE
Strange behavior with nvim-cmp, gopls and virtualedit=all

### ISSUE THREAD

**Issue by mbenford** [L3MON4D3/LuaSnip#302]
I have recently migrated from vim-snip to LuaSnip (paired with nvim-cmp) and I noticed a strange behavior when completing suggestions from `gopls` with `virtualedit=all`. I guess ~an image~ a gif is worth a thousand words:

![luasnip-1](https://user-images.githubusercontent.com/446867/153723525-581aedc7-49af-43dc-9ba3-6078eda01df4.gif)

That doesn't happen with other language servers, as far as I can tell (I've tested it with `tsserver` and `sumneko`).

The behavior shown in the gif above can be reproduced with the following configuration:

```lua
vim.opt.signcolumn = 'no'
vim.opt.number = true
vim.opt.completeopt = { 'menu', 'menuone', 'noinsert' }
vim.opt.virtualedit = 'all'

vim.cmd('packadd packer.nvim')
require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use {'williamboman/nvim-lsp-installer',
    config = function()
      local installer = require('nvim-lsp-installer')
      installer.on_server_ready(function(server)
        server:setup({
          capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
        })
      end)
    end
  }
  use {'hrsh7th/nvim-cmp',
    config = function()
      local cmp = require('cmp')
      require('cmp').setup({
        sources = cmp.config.sources({
          { name = 'nvim_lsp' },
          { name = 'luasnip '},
        }),
        mapping = {
         ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
         ['<CR>'] = cmp.mapping.confirm({ select = true }),
        },
        snippet = {
          expand = function(args)
            require('luasnip').lsp_expand(args.body)
          end,
        },
      })
    end
  }
  use {'hrsh7th/cmp-nvim-lsp'}
  use {'L3MON4D3/LuaSnip'}
  use {'saadparwaiz1/cmp_luasnip'}
end)
```
I'm not sure whether this is a bug in LuaSnip or nvim-cmp, but since it works correctly when using vim-snip, I think it might be something with LuaSnip.

**Comment by mbenford** [comment]
OK, I did more testing and realized it has nothing to do with `gopls`: it's the file indentation that causes the problem. It stops happening when I disable `expandtab` so spaces are used instead of tabs.

I also noticed that by changing `tabstop` (with `expandtab` off) to different values the cursor is placed at different positions after a suggestion is selected.

**Comment by L3MON4D3** [comment]
I think I see what's going wrong, `virtualedit` makes it so every individual column of a tab has to be moved over, the one `<right>` we do for the entire tab isn't enough.
I'll definitely look into that one, thank you for opening this👍
