### ISSUE TITLE
Error when typing end of text.

### ISSUE THREAD

**Issue by TornaxO7** [L3MON4D3/LuaSnip#303]
Hi! I've the following content of a snippet-file:

```lua
local ls = require "luasnip"
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local d = ls.dynamic_node

table.insert(ls.snippets.tex,
    s("beg", {
        t("\\begin{"), i(1), t({"}", ""}),
        i(0),
        d(2, function(args)
                return t({"", "\\end{" .. args[1][1] .. "}"})
            end,
            {1})
        }
    )
)
```

all it should do, is just creating the following:

```tex
\begin{}
\end{}
```

if I type `beg`. Now the problem is, that I get an error, if I leave insert mode, after entering `i(0)`:

![image](https://user-images.githubusercontent.com/50843046/153729891-12468c76-da4a-4a14-8877-5462201f9df8.png)

I don't understand what I'm doing wrong. Here is the order of my keys, which I hit, after expanding the snippet above:

1. `environment-name`
2. `<tab>`
3. `<esc>`

then the error pops up.

## Second small question
I don't see the text in the dynamic node while I write my stuff in the `i(1)` node. It appears after moving on to the next entry-point. Is that normal?

# Demo

<details>

https://user-images.githubusercontent.com/50843046/153730289-9e1650a5-dd4c-4661-a8ff-d8d3def56fba.mp4

</details>

**Comment by L3MON4D3** [comment]
Ahh, the textNode should be wrapped in a snippetNode, then it should work.
(also, you don't _need_ a dynamicNode for generating text, a functionNode would be enough :) )

**Comment by TornaxO7** [comment]
Great! I changed it to this snippet now:

```lua
table.insert(ls.snippets.tex,
    s("beg", {
        t("\\begin{"), i(1), t({"}", ""}),
        i(0),
        f(function(args, snip)
                return {"", "\\end{" .. args[1][1] .. "}"}
            end,
            {1}
        )
    })
)
```
and I don't get any errors anymore. Thank you!
