### ISSUE TITLE
Easy support for vim.ui.select for choice nodes

### ISSUE THREAD

**Issue by weilbith** [L3MON4D3/LuaSnip#308]
Hey, 👋🏾 

I would love to get a pop-up menu where I can select from the possible options of a choice-node. To me this feels like a must-have for snippet choices and is also implemented like that in other editors.

I've seen the wiki which kind-of tries to do this. But despite it is not an actual menu (not too much of a problem per se) it is tons of code to maintain by every user of this plugin. Rather than asking you to provide this solution in-built with the plugin (which probably just comes with tons of new issues for customization), I would ask if it isn't possible to simply provide support for `vim.ui.select` here? It sounds like a perfect use-case. And users do already started to customize their `vim.ui.select`, there are plugins for it and it works cross plugin. Would be very amazing if that would be possible! Also for you it should be quite feasibly to support this abstract but standardized interface and that's it.

Looking forward to receive some feedback on this.

**Comment by L3MON4D3** [comment]
Hi :)
I can definitely see where you're coming from, `vim.ui.select` should be _the_ interface to go through when it comes to displaying a choice to the user, and I think it shouldn't be too much work to integrate.

I'll definitely look into utilizing it, thank you for the suggestion :+1:

PS: You also raise a good point about maintaining the code from the wiki as a user, some parts (vscode-style nested placeholders, dynamicNode with external input, splitting snippet up by filetype) could (probably, I'll need to look into them completely) indeed be added to `luasnip.extras`, the additional size should be negligible and save users of these pieces of code from some hassle on breaking changes.

**Comment by weilbith** [comment]
> PS: You also raise a good point about maintaining the code from the wiki as a user, some parts (vscode-style nested placeholders, dynamicNode with external input, splitting snippet up by filetype) could (probably, I'll need to look into them completely) indeed be added to luasnip.extras, the additional size should be negligible and save users of these pieces of code from some hassle on breaking changes.

I can see how that would make many users happy. From the perspective of a project maintainer it is always a challenge to balance which features to put in and what not. The wiki proofs that the plugin is open for extensions and can be customized. Every feature that makes it into the project must be maintained, users ask for adaptions, the plugins core might become less flexible due to own dependencies etc pp. So do this decision with care. I think your current approach to maintain a stable core with only few extras is good, but still giving the user the interfaces to extend the plugin. In best case there evolve plugins that extend your plugin. 
In this particular case I just see it as an improvement of your existing interface towards and evolving standard in the NeoVim world. That's it. Thank you very much!
