### ISSUE TITLE
Error - Attempt to index field 'mark' (a nil value)

### ISSUE THREAD

**Issue by weilbith** [L3MON4D3/LuaSnip#309]
Hey, 👋🏾 

I started to play around with the plugin and write my first snippets. Now I stumbled over an error and really don't know what is happening here. The issue title isn't very expressive, but it is the message of the error so other users might find this issue is they run into the same error.

I hope the below example isn't too complex for an issue, but this is what I have:

```lua
local snippet = require('luasnip').snippet
local format = require('luasnip.extras.fmt').fmt
local text_node = require('luasnip').text_node
local insert_node = require('luasnip').insert_node
local function_node = require('luasnip').function_node

local trigger_name_node = function_node(
  function(_, snip)
    return snip.trigger
  end,
  {}
)

local named_function_snippet_node = format(
  '{keyword}{name}({parameter})\n  {body}\nend',
  {
    -- keyword = text_node('function '), -- <== WORKS
    keyword = trigger_name_node, -- <== DOESN'T WORK
    name = insert_node(1, 'name'),
    parameter = insert_node(2),
    body = insert_node(3, '-- TODO'),
  }
)

local anonymous_function_snippet_node = format(
  '{keyword}{parameter})\n  {body}\nend',
  {
    keyword = trigger_name_node,
    parameter = insert_node(1),
    body = insert_node(2, '-- TODO'),
  }
)

require('luasnip').autosnippets = {
  lua = {
    snippet(' function ', named_function_snippet_node),
    snippet({ trig = '^function ', regTrig = true }, named_function_snippet_node),
    snippet({ trig = '[= ]function%(', regTrig = true }, anonymous_function_snippet_node),
  },
}
```

The problem is the `trigger_name_node`. The awkward thing is that is works great for the `anonymous_function_snippet_node`. So if I type the following, the snippet expands automatically and works as expected:

```lua
local foo = function( -- <== snippet gets expanded
local bar=function( -- <== again, just works
```

But if I try to do the same with the `named_function_snippet_node`, I get an error. No matter which of both triggers I use (note that I had to use two `autosnippet` entries as Lua patterns don't allow to match both at once).

```lua
function -- <== snippet tries to expand but fails
```

The error and its complete stack trace looks like the following:

```vim
Error detected while processing TextChangedI Autocommands for "*":
E5108: Error executing lua ...te/pack/packer/opt/LuaSnip/lua/luasnip/nodes/snippet.lua:460: attempt to index field 'm
ark' (a nil value)
stack traceback:
        ...te/pack/packer/opt/LuaSnip/lua/luasnip/nodes/snippet.lua:460: in function 'enter_node'
        ...ack/packer/opt/LuaSnip/lua/luasnip/nodes/dynamicNode.lua:143: in function 'update'
        ...te/pack/packer/opt/LuaSnip/lua/luasnip/nodes/snippet.lua:691: in function 'update'
        ...te/pack/packer/opt/LuaSnip/lua/luasnip/nodes/snippet.lua:375: in function 'trigger_expand'
        ...m_test_site/pack/packer/opt/LuaSnip/lua/luasnip/init.lua:166: in function 'snip_expand'
        ...m_test_site/pack/packer/opt/LuaSnip/lua/luasnip/init.lua:262: in function 'expand_auto'
        [string ":lua"]:1: in main chunk
```

As already included in the snippet source code above, if I exchange the `trigger_name_node` in the `named_function_snippet_node` with a plain `text_node` it just works. Though this doesn't do the correct job... So I'm a bit confused. I'm starring at both function snippet node definitions and can't see why one is working and the other one not. I took a quick look into the source code where the error points to. But at this point in time the plugin is too complex for me and I'm not familiar with the code base (yet).

Thank you very much for your help!

**Comment by L3MON4D3** [comment]
Ah, It's possible that there's something going wrong because two snippets share one set of nodes.
You can still get the deduplication by copying `named_function_snippet_node` for one of the snippets (achievable with any copy-routine that copies metatables and preserves references to the same table ([copy3](https://gist.github.com/tylerneylon/81333721109155b2d244)) or by wrapping `n_s_f_n` into a `snippetNode` (`format` only produces a table of nodes, not a `snippetNode`) and `:copy()`ing that).
It's a bit unfortunate (red herring) that it worked with the `textNode`, but that is probably because they are a bit simpler, so there's less to go wrong.

I'll put a warning into the doc, "luasnip assumes that each snippet has a unique set of nodes, anything can happen if that assumption isn't satisfied"

> (note that I had to use two autosnippet entries as Lua patterns don't allow to match both at once)

It might make sense to allow multiple triggers for a snippet, that would be the cleaner solution in this specific case.

**Comment by weilbith** [comment]
Thanks for you very fast reply!!

That makes sense. But I'm not able to fix it. I'm trying to wrap everything into `snippet_node` and use `vim.deepcopy`. But now I just get a variety of other errors. I also tried to put the `trigger_name_node` into a function that gets called in the other nodes.
May I ask you to adjust the above code so that it works for you? That would be amazing.

**Comment by L3MON4D3** [comment]
You're very welcome :)
`vim.deepcopy` (which now seems to do the same as copy3) seems to work for me. I know that it was a more simple, metatable-ignoring function in the past, maybe it comes down to different nvim-versions... Anyway, here are the versions I got to work:

```lua
local trigger_name_node = f(
  function(_, snip)
    return snip.trigger
  end,
  {}
)

local named_function_snippet_node = fmt(
  '{keyword}{name}({parameter})\n  {body}\nend',
  {
    keyword = trigger_name_node,
    name = i(1, 'name'),
    parameter = i(2),
    body = i(3, '-- TODO'),
  }
)

...

s(' function ', named_function_snippet_node),
s(' function2 ', vim.deepcopy(named_function_snippet_node)),
```

or

```lua
local trigger_name_node = f(
  function(_, snip)
    return snip.trigger
  end,
  {}
)

-- pass position 1!
local named_function_snippet_node = sn(1, fmt(
  '{keyword}{name}({parameter})\n  {body}\nend',
  {
    keyword = trigger_name_node,
    name = i(1, 'name'),
    parameter = i(2),
    body = i(3, '-- TODO'),
  }
))

...

s(' function ', named_function_snippet_node),
s(' function2 ', named_function_snippet_node:copy()),
```

**Comment by weilbith** [comment]
Ah, I got my mistake. I was copying the `trigger_name_node`, not the `*_function_snippet_node`. Now it works. Very nice! 👌🏾 
Thank you very much for you quick help!! 🙏🏾

**Comment by L3MON4D3** [comment]
Ahh alright.

> Thank you very much for you quick help!! 🙏🏾

You're welcome :D
