### ISSUE TITLE
How to deal with auto-closing parentheses in snippet triggers

### ISSUE THREAD

**Issue by weilbith** [L3MON4D3/LuaSnip#310]
Hello,

I'm not sure if this is a super rare edge-case not worth to discuss/solve. But I'm using a plugin to automatically insert and balance parentheses (, brackets, curly braces, ...). In my case it is [delimitMate](https://github.com/Raimondi/delimitMate) but assume the problem is the same for any of these plugins. Now I have a snippet with a trigger that ends with an opening parentheses. The result is that (no matte if autotriggered or manually), the above mentioned plugin will automatically insert the closing character. But the snippet only replaces the trigger up to the opening character ofc. In result you always end up with a syntax error and must clean it up manually. Which is kinda the opposite of what you want to achieve with snippets (being fast).
I rack my brains but I can't figure out a solution approach to solve this. Am I the only one? Should I just get rid of the opening character in the trigger and work around it. Is there already a discussion thread (with a solution?), but I haven't found it? 

Here some example code:

```lua
local snippet = require('luasnip').snippet
local format = require('luasnip.extras.fmt').fmt
local insert_node = require('luasnip').insert_node

local function_snippet_node =  format(
  'function({})\n  {}\nend',
  { insert_node(1), insert_node(2, '--TODO') }
)

require('luasnips').snippets({
  lua = {
    snippet('function(', function_snippet_node),
  }
})
```

If I trigger this snippet (automatically) I get the following result:

```lua
local foo = function()
  -- TODO
end) -- <== here is the automatically inserted closing character
```

I'm glad for any input here. Thank you very much!

**Comment by L3MON4D3** [comment]
I think the easiest solution is getting rid of the `(` in the trigger.

Apart from that, luasnip has `enter/leave` events which could be extended to include `expand` (or a more general `put` for other nodes). With that, there's a function that is called right after expansion, so the parenthesis behind the snippet could be removed in it.

**Comment by weilbith** [comment]
Here is my working solution. Note the `FIXME` that marks that this doesn't work 100% in all cases. The practice will show how urgent it is to fix that.

```lua
local function get_character_under_cursor()
  local cursor = vim.api.nvim_win_get_cursor(0)
  local line_index = cursor[1] - 1 -- :help api-indexing
  local character_index = cursor[2] -- :help api-indexing
  local line_content = vim.api.nvim_buf_get_lines(
    0, line_index, line_index + 1, false
  )[1]
  local character = line_content:sub(character_index, character_index)
  return character
end

local function is_closing_character(character)
  return character:find('[%)%]}>]') and true or false
end

local function delete_character_under_cursor()
  local cursor = vim.api.nvim_win_get_cursor(0)
  local line_index = cursor[1] - 1 -- :help api-indexing
  local character_index = cursor[2] -- :help api-indexing
  vim.api.nvim_buf_set_text(
    0, line_index, character_index - 1, line_index, character_index, {''}
  )
end

-- FIXME:
-- This doesn't work if there is more text in the line after the snippet trigger
-- except the unwanted closing character. That is because the cursor will always
-- be at the very end of the last line after the completed snippet.
local function remove_automatically_inserted_closing_character_after_snippet_trigger()
  local character = get_character_under_cursor()

  if is_closing_character(character) then
    delete_character_under_cursor()
  end
end

-- This tackles the problem if a snippets its trigger ends with a opening
-- character (e.g. `(`, `[`, ...) and another plugin is automatically inserting
-- the matching closing character. In result the closing character will end up
-- at the end of the inserted snippets content. This leads to invalid syntax and
-- needs to be removed manually every time.
-- Add this callback definition to a snippet with such a trigger to fix this
-- automatically.
local callbacks_to_fix_auto_closing_characters = {
  [-1] = {
    [events.enter] = remove_automatically_inserted_closing_character_after_snippet_trigger,
  },
}

require('luasnip').autosnippets = {
  lua = {
    snippet({ trig = '^function ', regTrig = true }, named_function_snippet_node),
    snippet(' function ', named_function_snippet_node),
    snippet(
      'trigger with opening character like --> (',
      your_snippet_node,
      { callbacks = callbacks_to_fix_auto_closing_characters }
    ),
  },
}
```

**Comment by L3MON4D3** [comment]
I'm sorry about the edits, I meant to quote :sweat_smile: 


> What I already recognized that if I have a callback for the `[-1] = { [events.enter] = function() ... end }`, the snippet is already inserted. 

True, `enter` is triggered pretty late during snippet-expansion. I'll keep that in the back of my head, to add a `pre_expand`-function for snippets specifically.

Concerning the `FIXME`: you can get the position of the snippet via 

```lua
[events.enter] = function(snippet)
	pos = snippet.mark:pos_begin_end_raw[2] -- {{row,col}, {row_col}}, for begin,end
	...
end
```
with that it should be possible to remove the character behind the snippet reliably.

**Comment by weilbith** [comment]
Thank you very much! That was very helpful! I updated my posted solution above. It now works as expected. 🚀
