### ISSUE TITLE
How to use choices with input nodes

### ISSUE THREAD

**Issue by weilbith** [L3MON4D3/LuaSnip#311]
Hey 👋🏾 

it's me again. During the development of more complex snippets, I tried to use choice nodes here and there. But quite often they do not work for me properly. Now I tried to construct a minimal snippet where I can replicate it to understand the problem. Here is what I found:

```lua
local snippet = require('luasnip').snippet
local text_node = require('luasnip').text_node
local insert_node = require('luasnip').insert_node
local choice_node = require('luasnip').choice_node

require('luasnip').snippets = {
  all = {
    snippet('test', { 
      choice_node(1, {
        text_node('foo'),
        text_node('bar'),
        insert_node(nil, 'alice'),
        insert_node(nil, 'bob'),
      })
    )
  }
}
```

When I type `test` and expand the snippet, I can cycle through the choice nodes until I reach the first insert node. Now I'm "within" the insert node and can't continue to cycle from `alice` to `bob`.
I'm not sure if this is intended, but to me it seems like a bug. I can see the challenge here, but I would say this feature is very important.
I think with solutions like #308 this could be mitigated because the user would not cycle through the choice nodes but directly select one. Though I would say this should not be the final solution.

Am I totally off here? Am I doing something wrong? I tried to wrap the insert node into snippet nodes etc. But always the same problem. Actually I came from there and shimmed it down to this minimal snippet.
Thanks for you help in advance!

**Comment by L3MON4D3** [comment]
Heyhey :D

The Snippet looks correct, are you perchance just missing the `SELECT`-keybind for changing choices?

**Comment by weilbith** [comment]
Aaaaah, damn. I got my mistake. I only had the keybinding to change the choice in insert mode, but not select mode. :face_palm:
Now also my "advanced" choices work.
I'm very sorry to open such a stupid issue. 🙈

**Comment by L3MON4D3** [comment]
😄
Maybe it'll also save someone else, I'm sure you're not the last to just miss some keybinding :D

**Comment by theairbend3r** [comment]
I have a similar issue. I'm not sure how to iterate of the choices. My snippet:

```
s(
    "trig",
    c(1, {
        t("foo"),
        t("bar"),
    })
)
```
When I enter `trig`, I only see "foo" as the output. 

> The Snippet looks correct, are you perchance just missing the `SELECT`-keybind for changing choices?

By `select` keybind, do we mean `{ "i", "s" }` tacked on at the end in `cmp.mapping`?

```
["<Tab>"] = cmp.mapping(function(fallback)
    if cmp.visible() then
        cmp.select_next_item()
    elseif luasnip.expandable() then
        luasnip.expand()
    elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
    else
        fallback()                                                  
    end                                                             
end, {
    "i",
    "s",
})  
```

**Comment by L3MON4D3** [comment]
Ah, no, there's a separate action, `change_choice`, which you'd have to bind in INSERT and SELECT. There's an example in the Readme :)

**Comment by theairbend3r** [comment]
Thanks! :smile_cat:
