### ISSUE TITLE
`extends` directive does not work in .snippets (snipmate format)

### ISSUE THREAD

**Issue by dlee** [L3MON4D3/LuaSnip#314]
Snippets should be able to extend other filetypes, but it doesn't seem to be working.

For example, I have a typescript.snippets and typescriptreact.snippets in my `~/.config/nvim/snippets` directory.
My typescriptreact.snippets starts with:
```
extends typescript
...
```
But it doesn't load any of the snippets defined in typescript.snippets.

**Comment by L3MON4D3** [comment]
Yeah I think that isn't implemented yet.
@uga-rosa would you be interested in adding it?

For now, you can use `ls.filetype_extend("typescriptreact", {"typescript"})`, which has the added benefit (imo) that not only snipmate-snippet are extended, but also lua or vscode-ones.

**Comment by uga-rosa** [comment]
Hi, I thought the extends syntax was supported, so it's a bug. I don't use this feature, so I guess I didn't test it well enough. I will look into it.

**Comment by L3MON4D3** [comment]
`extends` should work now, thanks to @uga-rosa :ok_hand:
