### ISSUE TITLE
Completion during insert node seems to break lua snippet

### ISSUE THREAD

**Issue by leamingrad** [L3MON4D3/LuaSnip#316]
### Summary

When I insert the result of a completion (from `nvim-cmp`) into a placeholder for a lua snippet, it seems to break `Luasnip`: the placeholder is not inserted into the rest of the snippet, and jumping takes the cursor to the start of the line.

Apologies in advance if this is a known issue - I had a look but could not find anything similar in either this repository or the `nvim-cmp` one.

### Minimum Working Example

I was able to reproduce the issue with the following minimal neovim config:

```vim
" Install plugin manager (if missing)
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install Plugins
call plug#begin(stdpath('data') . '/plugged')

" Sensible Defaults
Plug 'tpope/vim-sensible'

" Autocompletion
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/nvim-cmp'

" Snippets
Plug 'L3MON4D3/LuaSnip'

call plug#end()

lua <<EOF
    -- Set completeopt to have a better completion experience
    vim.o.completeopt = 'menuone,noselect'

    -- nvim-cmp setup
    local cmp = require('cmp')
    local ls = require("luasnip")

    ls.snippets = {
        all = {
            -- This snippet should just copy the first insert
            -- group into two brackets
            ls.snippet("brackets", {
                ls.text_node("("),
                ls.insert_node(1),
                ls.text_node(") {"),
                require("luasnip.extras").rep(1),
                ls.text_node("}"),
            }),
        }
    }
    -- This is needed to pick up the custom snippet above.
    ls.refresh_notify("all")

    cmp.setup {
      snippet = {
        expand = function(args)
          ls.lsp_expand(args.body)
        end,
      },
      mapping={
        ['<Tab>'] = cmp.mapping(
            function(fallback)
              if cmp.visible() then
                print("Next")
                cmp.select_next_item()
              elseif ls.expandable() then
                print("Expand")
                ls.expand()
              elseif ls.jumpable(1) then
                print("Jump")
                ls.jump(1)
              else
                print("Fallback")
                fallback()
              end
            end,
            { 'i', 's' }
        ),
        ['<S-Tab>'] = cmp.mapping(
            function(fallback)
              if cmp.visible() then
                cmp.select_prev_item()
              elseif ls.jumpable(-1) then
                ls.jump(-1)
              else
                fallback()
              end
            end,
            { 'i', 's' }
        ),
      },
      sources = cmp.config.sources({
        -- Add the buffer source so we have something to complete with
        { name = 'buffer' },
      }),
    }
EOF
```

This then has the following effect:

[![asciicast](https://asciinema.org/a/YG21BPTg3waA6EXn8dfupz2lk.svg)](https://asciinema.org/a/YG21BPTg3waA6EXn8dfupz2lk)

I'm happy to give more information if required, but I have no idea what is going on here.

My best guess is that when `nvim-cmp` inserts the completion result, it causes `Luasnip` to decide that it is no longer inside a snippet, but that wouldn't explain why pressing `<Tab>` causes me to jump to the start of the line.

**Comment by L3MON4D3** [comment]
Thanks for the detailed issue👍
The problem is that luasnip uses extmarks to remember jump-positions, and it seems like `nvim-cmp` does a `nvim_buf_set_line`, which moves extmarks to the beginning/end of the line. You can run `:lua require("luasnip").session.current_nodes[vim.api.nvim_get_current_buf()].parent:dump()` (prints position of the extmarks) to verify that.
Iirc this used to work correctly, it might be a regression in `cmp` :/

**Comment by L3MON4D3** [comment]
Although I cannot reproduce the issue, at least not with the lsp-source.

**Comment by leamingrad** [comment]
Thanks for the quick reply - from a look at the output of the command, that definitely seems to be the case. I'll have a go at trying different versions of `nvim-cmp` to see if there is an obvious regression.

> Although I cannot reproduce the issue, at least not with the lsp-source.

Interestingly, I also cannot reproduce the issue with LSP snippets: it only seems to be a problem with lua ones that I define in my `init.vim` - is there anything strange in the example snippet that might cause this?

**Comment by leamingrad** [comment]
Actually I think this is a false alarm - I've just updated all of my plugins and my version of neovim and it's started working, so I guess i just had an incompatible combination before. Thanks for the help anyway.
