### ISSUE TITLE
Question: How to setup html snippets for htmldjango filetype?

### ISSUE THREAD

**Issue by arthur-s** [L3MON4D3/LuaSnip#317]
Possibly I didn't see it in the docs, or maybe it's not implemented: I can't make snippets to work on documents of htmldjango file type. How can it be solved? Now I switch filetype from html to htmldjango back and forth, it's little unconvinient.

**Comment by L3MON4D3** [comment]
You can
* set snippets for a specific filetype by adding them to `ls.snippets.<filetype>` or `snippets/<filetype>.snippets`
* see the filetype luasnip looks into for the current file by doing `:lua print(vim.inspect(require("luasnip.util.util").get_snippet_filetypes()))`

I hope this helps!

**Comment by arthur-s** [comment]
Thank you! Yes, it helped.

**Comment by im-n1** [comment]
Or you can simple call `require("luasnip").filetype_extend("htmldjango", { "html" })` in your config function.
