### ISSUE TITLE
Snippets that start with \ don't show up in luasnip

### ISSUE THREAD

**Issue by theairbend3r** [L3MON4D3/LuaSnip#318]
Hi, I've created a snippet as follows:

```
s({ trig = "\\section" }, {
    t("\\section{"),
    i(1),
    t({ "}", "  " }),
    i(0),
}) 
```

But while typing, `\section` (from 0 to all characters), the snippet does not get shown in the luasnip window (only the Lsp stuff comes up). 

But if I type it without the `\` as `section` (from 0 to all characters), then I see my snippet displayed. 

I was wondering why is this the case?

**Comment by L3MON4D3** [comment]
Ah, that's because when `wordTrig` is set (which it is by default), we only check whether the word ([w_]+) before the cursor matches the trigger, but if the trigger itself contains a non-word character, it will never match.
Could you use `{trig="\section", wordTrig=false}` and see if that works?

**Comment by theairbend3r** [comment]
It didn't work. My snippet:

```
s({ trig = "\\section", wordTrig = false }, {
    t("\\section{"),
    i(1),
    t({ "}", "  " }),                                 
    i(0),
}),
```

When I type `\sec...`

![Screenshot from 2022-02-24 16-24-49](https://user-images.githubusercontent.com/60727948/155511313-8ce34ffb-8160-4a62-bbb9-7d549c8d6abb.png)


When I type `sec...`

![Screenshot from 2022-02-24 16-24-38](https://user-images.githubusercontent.com/60727948/155511331-c79bd5e7-92fd-4fbc-b2c3-b0e38bb741f7.png)



But it's not an issue. I find typing `sec..` to be less cumbersome than `\sec..` now haha. :smile_cat:

**Comment by L3MON4D3** [comment]
Oh, there's a difference between a snippet showing up in the completion menu and being able to trigger it, just fyi.

> But it's not an issue. I find typing sec.. to be less cumbersome than \sec.. now haha. 😸

Yeah, for sure! I guess that's why it hasn't come up yet :D

**Comment by theairbend3r** [comment]
> Oh, there's a difference between a snippet showing up in the completion menu and being able to trigger it, just fyi.

Ah, I didn't know that. Thank you! Kudos on making this amazing plugin! :smile:
