### ISSUE TITLE
Indent size: use buffer option

### ISSUE THREAD

**Issue by aspeddro** [L3MON4D3/LuaSnip#319]
snippets with tab `\t` add a tab even when the buffers options for the filetype use space.

Example: lua

- shiftwidth: 2,
- tabstop: 2,
- expandtab: false,

```lua
for index, value in ipairs(t) do
	print("here")
end
```

It is possible to inherit the buffer options (`vim.bo`)?

**Comment by L3MON4D3** [comment]
We only check `vim.o` right now, but there's no real reason for that I think. I'll look into adding the check for `vim.bo`.
