### ISSUE TITLE
Ability to list available snippets

### ISSUE THREAD

**Issue by thepenguinthatwants** [L3MON4D3/LuaSnip#32]
Hi,
I've started to use LuaSnip and I am wondering if there is a way to list all available snippets for current file?

Also wondering if there could be example for using bash command output as a snippet?

**Comment by L3MON4D3** [comment]
Listing+Selecting and expanding snippets is possible with [nvim-compe](https://github.com/hrsh7th/nvim-compe), you'd need to set luasnip as a source. If that isn't exactly what you're after, please elaborate :D
As far as bash-interpolation is concerned, that's pretty doable using a functionNode:
```lua
local function bash(_, command)
	local file = io.popen(command, "r")
	local res = {}
	for line in file:lines() do
		table.insert(res, line)
	end
	print(vim.inspect(res))
	return res
end

-- Snippet definition:
s({trig = "trig"}, {
	f(bash, {}, "echo lel"), i(0)
})
```
Great suggestion, I'll definitely add it to examples!

**Comment by clason** [comment]
An alternative would be writing a telescope extension for this, like one of the ones in https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions.

**Comment by L3MON4D3** [comment]
Yeah, that would work, although I don't really see much benefit compared to `nvim-compe`.

**Comment by clason** [comment]
Depends on the workflow (and the language); I for example don't want (self-defined) snippets in my completion results (and I don't use -- and don't want to use -- `nvim-compe`). 

And to be honest, I am much more often in the situation that I forgot that a snippet exists (or what precisely the trigger is) than that I want to save the two or three keystrokes for finishing the rest of my snippet ;)

But, sure, not saying it's better -- just saying that it could _also_ be useful if someone else is interested.

**Comment by L3MON4D3** [comment]
Of course, options and all that :D
A function to print all snippets (just the table containing `trig` and optionally `name` and `description` should be enough) makes sense, I'll get to that.

**Comment by L3MON4D3** [comment]
I added `LuaSnipListAvailable`, which is rather crude but as it's mainly for debugging-purposes that's excusable I think :D
What do you guys think?

**Comment by clason** [comment]
To be honest, I'd probably just make it return the snippets as a table (at least for the Lua function); then people can format how they want it (or postprocess via telescope). You can still do
```lua
:lua print(vim.inspect(luasnip.list_available()))
```

**Comment by L3MON4D3** [comment]
Oh yeah, that's a better approach.

**Comment by L3MON4D3** [comment]
Okay, I updated the function, it now returns:
```lua
{
	all = {
		snippet,
		...,
		snippet
	},
	java = {
		snippet,
		...,
		snippet
	}
}
```
with `java` being whichever the current filetype is.
I'm not entirely sure if this separation into `ft` and `all` is better than putting `ft`/`all` into the snippet-table and having all snippets directly in the table.

**Comment by clason** [comment]
For the function, I'd just return a flat table (this being the primary convenience over just printing `require'LuaSnip'.snippets`)?

**Comment by L3MON4D3** [comment]
Well, `ls.snippets` contains much more than just name, trigger,... for each snippet.
I'll probably write the flat version as well, `available_flat` or something, as just merging `all` and `ft` would lead to losing information on which filetype the snippet belongs to.

**Comment by clason** [comment]
True. Either way is fine; I don't have a strong preference. For my sake, it's not necessary to have two functions.

**Comment by L3MON4D3** [comment]
👍

**Comment by thepenguinthatwants** [comment]
So I added the trig for ls

```
ls.snippets = {
	all = {
		s({trig="("}, { t({"("}), i(1), t({")"}), i(0) }, neg, char_count_same, '%(', '%)'),
		s({trig="{"}, { t({"{"}), i(1), t({"}"}), i(0) }, neg, char_count_same, '%{', '%}'),
		s({trig="["}, { t({"["}), i(1), t({"testing]"}), i(0) }, neg, char_count_same, '%[', '%ik]') ,
		s({trig="<"}, { t({"<"}), i(1), t({">"}), i(0) }, neg, char_count_same, '<', '>'),
		s({trig="'"}, { t({"'"}), i(1), t({"'"}), i(0) }, neg, even_count, '\''),
		s({trig="\""}, { t({"\""}), i(1), t({"\""}), i(0) }, neg, even_count, '"'),
		s({trig="{;"}, { t({"{","\t"}), i(1), t({"", "}"}), i(0) }),
        s({trig = "trig"}, { f(bash, {}, "ls"), i(0) }),
	},
```

when trying to trigger it I get

`E5108: Error executing lua .../packer/start/LuaSnip/lua/luasnip/nodes/functionNode.lua:33: attempt to call field 'fn' (a nil value)`

**Comment by thepenguinthatwants** [comment]
Oh had to add the

_local function bash(_, command)
	local file = io.popen(command, "r")
	local res = {}
	for line in file:lines() do
		table.insert(res, line)
	end
	return res
end_

and it works. Cool!!!

**Comment by gitaarik** [comment]
There is a nvim-telescope extension for this now: [telescope-luasnip](https://github.com/benfowler/telescope-luasnip.nvim). It works pretty nice :)

![telescope-luasnip5](https://github.com/L3MON4D3/LuaSnip/assets/2470302/b0b125b7-5d75-4861-b330-571c54f9dd23)
