### ISSUE TITLE
Cursor at the end of choices in choiceNode

### ISSUE THREAD

**Issue by theairbend3r** [L3MON4D3/LuaSnip#321]
Hi, I followed the docs to setup a choiceNode. When I cycled through the choices, I realised the cursor is always at the start of the sentence - 

Here's the snippet-
```
 s("trig", c(1, {
 	t("Ugh boring, a text node"),
 	i(nil, "At least I can edit something now..."),
 	f(function(args) return "Still only counts as text!!" end, {})
 }))
```

Here's the output.   
`|` = cursor
```
|Ugh boring, a text node 
|At least I can edit something now...  
|Still only counts as text!!
```

I tried putting an `i(0)` to see if I could get my cursor at the end but it did not work.
```
      s(    
             "trig",    
             c(1, {    
                 t("Ugh boring, a text node"),    
                 i(nil, "At least I can edit something now..."),    
                 f(function(args)   
                     return "Still only counts as text!!"    
                 end, {}),    
             }),    
             i(0)    
         ),    
```

Is there a way to always put the cursor at the end of the choice (except probably in insert node because we write from left to right)?

```
Ugh boring, a text node| 
| At least I can edit something now...  
Still only counts as text!!|
```

 This will make it easy to continue typing after cycling though and selecting a choice.

**Comment by L3MON4D3** [comment]
Interesting.. One problem would be that luasnip only expects new text (and snippet expansions! You won't be able to jump back into snippets expanded while inside a textNode) inside insertNodes, so if you want everything to work correctly, you'd need to jump one more time after choosing your choice.
And at that point, there's little difference if the origin of the jump is at the beginning or end of some text, I think.

**Comment by theairbend3r** [comment]
That makes sense, thanks! :smile:
