### ISSUE TITLE
[Question] Lua defined snippets repo

### ISSUE THREAD

**Issue by rgnkn** [L3MON4D3/LuaSnip#326]
I have a question with regards to lua defined snippets.

Is there any repo like [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) for vscode like snippets that you could refer me to? ... maybe mentioning it on the [README.md](https://github.com/L3MON4D3/LuaSnip/blob/master/README.md)?

If you don't know of any: Wouldn't it be a nice idea to open such a repo?

**Comment by L3MON4D3** [comment]
There's [this](https://github.com/molleweide/LuaSnip-snippets.nvim), but it doesn't have many snippets yet. Still, it's something to get started with

**Comment by rgnkn** [comment]
Yes, I saw that. But as you mentioned it's a bit in a sad state (just look at the sole rust snippet).

Maybe it would help to guide others to that repo via your `README.md` with the hope that it might get more useful.

**Comment by L3MON4D3** [comment]
Ah, yeah that's a good idea; I'm not at my PC right now, could you do a quick PR to add it? Maybe in the same section as friendly-snippets, in the lua-part?

> BTW: Thumbs up for this plugin.

Ty! :)

**Comment by rgnkn** [comment]
Same this end. I'm on phone. I'll do it later, but it might take some hours.
