### ISSUE TITLE
error while loading luasnip

### ISSUE THREAD

**Issue by Gako358** [L3MON4D3/LuaSnip#327]
Getting an error I cannot seem to understand, while trying to require luasnip.
`
E5113: Error while calling lua chunk: vim.lua:64: ...user/.config/nvim/plugged/LuaSnip/lua/luasnip/loaders/from_vscode.lua:67: '=' expected near 'continue'  
`

In my completion.lua config file i have;
`
require("luasnip/loaders/from_vscode").load()
`

**Comment by L3MON4D3** [comment]
Yeah, sorry about that, the loaders are kind of broken right now, but it'll be fixed later today. Best roll back to one or two commits before, I'll update here once it works again.

**Comment by leiserfg** [comment]
It does not happen to me, are you using lua instead of luajit?

**Comment by L3MON4D3** [comment]
Oh interesting, but I'm pretty sure I'm on luajit too. Could also be a config-thing.

**Comment by leiserfg** [comment]
```sh
echo "goto continue" | lua5.1 -                                           !
lua5.1: stdin:1: '=' expected near 'continue'
```

**Comment by leiserfg** [comment]
Lua 5.1 does not have `goto` :smile:

**Comment by L3MON4D3** [comment]
Ah I'm sorry I though you were commenting on the PR with my issue 😅
You're correct of course, that issue is with lua vs luajit.

**Comment by Gako358** [comment]
I have both installed, how to I make sure it uses luajit?

**Comment by L3MON4D3** [comment]
I think that's configured at build-time. How did you install neovim?

**Comment by Gako358** [comment]
Yeah, I have to rebuild it with luajit, thanks. Can prop close this
