### ISSUE TITLE
Example for init.lua keybinding?

### ISSUE THREAD

**Issue by thepenguinthatwants** [L3MON4D3/LuaSnip#33]
Hi,
Can you also include a lua based example on how to map this plugin?

For now I've gotten it like this but I think this is not the best way.

cmd([[
imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>' 
inoremap <silent> <S-Tab> <cmd>lua require'luasnip'.jump(-1)<Cr>

snoremap <silent> <Tab> <cmd>lua require('luasnip').jump(1)<Cr>
snoremap <silent> <S-Tab> <cmd>lua require('luasnip').jump(-1)<Cr>

imap <silent><expr> <C-E> luasnip#choice_active() ? '<Plug>luasnip-next-choice' : '<C-E>'
smap <silent><expr> <C-E> luasnip#choice_active() ? '<Plug>luasnip-next-choice' : '<C-E>'
]])

**Comment by L3MON4D3** [comment]
You could try `vim.api.nvim_set_keymap('i', '<Tab>', 'luasnip#expand_or_jumpable() ? "<Plug>luasnip-expand-or-jump" : "<Tab>"', {expr = true, silent = true})`, which is equal to
`imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>'`.
`noremap` can be set like `expr` and `silent`.
I don't use lua to define my mappings, could you post yours once they work? I'll probably just link those in the README if that's alright.

**Comment by leiserfg** [comment]
@thepenguinthatwants   you are actually not using lua but vimscript embedded in a cmd call, but anyway, the posted code is wrong as it's not setting the keys used to map. 
If you wanna use `<Tab>` with `nvim_set_keymap` you will have to escape it with `vim.api.nvim_replace_termcodes` as  `nvim_set_keymap` does not do it automatically.

**Comment by L3MON4D3** [comment]
Are you certain? I just checked and `<Tab>`, alone worked just fine. Maybe the API changed?

**Comment by clason** [comment]
Note the use of `[[...]]` which denotes a _literal_ string in Lua.

**Comment by leiserfg** [comment]
> Are you certain? I just checked and `<Tab>` alone worked just fine. Maybe the API changed?

Yes, you are right, seems like it uses `nvim_replace_termcodes` now, it was not like this, actually, it still documented as I said in https://github.com/nanotee/nvim-lua-guide#tips-4

**Comment by leiserfg** [comment]
> Note the use of `[[...]]` which denotes a _literal_ string in Lua. It's not just a fancy way of writing `'...'`.

'...'  is also a literal form, the only difference between those is that with double brackets you don't use scape sequences but I was talking about escaping vim keys  (like `<Tab>`) which is unrelated to lua strings.

**Comment by thepenguinthatwants** [comment]
Yup u r right the one that I posted didn't work. I didn't seem to get error earlier but now its just nope.


`vim.api.nvim_set_keymap('i', '<Tab>', 'luasnip#expand_or_jumpable() ? "<Plug>luasnip-expand-or-jump" : "<Tab>"', {expr = true, silent = true})`
I didn't get this to work. But I'll post my version when I get it to work.

**Comment by thepenguinthatwants** [comment]
I ended up using this vim-compe and lua.


```
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif vim.fn.call("luasnip#available", {1}) == 1 then
        return t "<Plug>(luasnip-expand-or-jump)"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn['compe#complete']()
    end
end
_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
        return t "<Plug>(vsnip-jump-prev)"
    else
        return t "<S-Tab>"
    end
end

vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})

```

As tab and c-j/k works for navigation I changed 

`vim.api.nvim_set_keymap('i', '<c-l>', 'luasnip#expand_or_jumpable() ? "<Plug>luasnip-expand-or-jump" : "<Tab>"', {expr = true, silent = true})`

ctrl-l to expand.


I just want to thank you a lot for this plugin. Its really working very well compared to others I've tried.

**Comment by L3MON4D3** [comment]
Looks good, although make sure to also add mappings for switching choices.
