### ISSUE TITLE
[Question] Adding tree-sitter based expansion conditions

### ISSUE THREAD

**Issue by yilinwei** [L3MON4D3/LuaSnip#339]
Hi,

First of all, thanks for the awesome package; it's been really fun to play around with so far.

Would it be possible to upstream some more functions for tree-sitter based expansions e.g. expand only when found inside a node block? I've found them to be quite useful for autosnippets.

**Comment by L3MON4D3** [comment]
Yeah those are pretty nice, and more would be great. I don't have much experience writing queries, if you already have some, feel free to open a PR :)

**Comment by max397574** [comment]
that doesn't require queries
It's about node types
An example for this can be found here:
https://github.com/nvim-treesitter/nvim-treesitter/issues/1184#issuecomment-830388856
I think this could be done with a function snippet

**Comment by L3MON4D3** [comment]
*"much experience with treesitter", as is evident at least now :D
That link looks promising, we could use a function that takes that table of node-names and returns the condition-function, which returns if the cursor is inside any of these nodes.

**Comment by max397574** [comment]
you could do that
or just put it in the wiki and let users to it themselfs

**Comment by molleweide** [comment]
Another tip on ts is to follow 'refactor.nvim'

**Comment by L3MON4D3** [comment]
> you could do that or just put it in the wiki and let users to it themselfs

I think this is something I'd actually put in the repo, sounds flexible+useful enough. We also have a few conditions in `extras` already.

**Comment by L3MON4D3** [comment]
> Another tip on ts is to follow 'refactor.nvim'. They have written nice helpers for ts that one can learn from.

Could you post a link? Couldn't find them :/

**Comment by dvdsk** [comment]
> Could you post a link? Couldn't find them :/

I think he means https://github.com/ThePrimeagen/refactoring.nvim/blob/master/lua/refactoring/treesitter/treesitter.lua

**Comment by molleweide** [comment]
Sorry, yeah the link provided by dvdsk is the correct one!

**Comment by yilinwei** [comment]
> ... we could use a function that takes that table of node-names and returns the condition-function, which returns if the cursor is inside any of these nodes.

Yes, that's how I'm doing i currently. It works fairly well, but _is_ dependent on how good the grammar is for the target language.

**Comment by dvdsk** [comment]
TJ has a youtube series on luasnip, he explains a treesitter snippet here: https://youtu.be/KtQZRAkgLqo?t=1350 and he mentions his next video will look at hem in detail. Maybe he has some useful insights?

**Comment by molleweide** [comment]
> TJ has a youtube series on luasnip, he explains a treesitter snippet here: https://youtu.be/KtQZRAkgLqo?t=1350 and he mentions his next video will look at hem in detail. Maybe he has some useful insights?
> 
> 
> 
> He also seems to have some useful helper functions for using tree-sitter with luasnip. Those might be great to include in an eventual PR.

Thanks for adding this video.

**Comment by max397574** [comment]
do u have a link to helper functions @dvdsk ?

**Comment by yilinwei** [comment]
I've added an initial PR so discussion can continue there.

**Comment by dvdsk** [comment]
> do u have a link to helper functions @dvdsk ?

My mistake I mistook an import, though the [example](https://github.com/tjdevries/config_manager/blob/master/xdg_config/nvim/lua/tj/snips/ft/go.lua) in which I spotted them is useful on its own.

**Comment by tjdevries** [comment]
I was asked to post some stuff relating to my snippets, so here's where I'm doing some fun stuff with treesitter atm

https://github.com/tjdevries/config_manager/blob/master/xdg_config/nvim/lua/tj/snips/ft/go.lua

I don't know how generalizable they are (and not sure it really even makes sense to reside in the main repo). Why not add a `luasnip-treesitter` repo to maintain and manage tree-sitter related extensions and queries (so that @L3MON4D3 does not have to maintain those in the same place all the other amazing work is happening). It doesn't seem like it's an integrated piece to LuaSnip as a whole, but rather a really cool extension.
