### ISSUE TITLE
[question] about insert node in choice node 

### ISSUE THREAD

**Issue by AlePon123** [L3MON4D3/LuaSnip#342]
is there any way to create choice node if the line contains some characters or if it dont just go to the next insert node
like 
![image](https://user-images.githubusercontent.com/72556979/158868594-d0d2d36e-2adb-4731-98de-4b7758ab3094.png)

**Comment by L3MON4D3** [comment]
Mhm, that should be possible via `dynamicNode`.
What do you want to achieve, specifically?

**Comment by AlePon123** [comment]
> Mhm, that should be possible via `dynamicNode`. What do you want to achieve, specifically?
if choice node is "->" make new insert node like 
```rust
  fn <firts insert node>  -> <here new insert node> {
    <another insert node>
  }
```

**Comment by AlePon123** [comment]
i do this but after second insert node is going on last insert node
![image](https://user-images.githubusercontent.com/72556979/158874033-28e597b9-c5b4-4191-b1d7-9b3bfeccd6b9.png)

**Comment by L3MON4D3** [comment]
Oh yeah, that's almost correct, you only have to change i(3) to i(1). The jump-positions restart inside nested snippets.

**Comment by AlePon123** [comment]
thanks
