### ISSUE TITLE
history issues

### ISSUE THREAD

**Issue by gleich** [L3MON4D3/LuaSnip#345]
Hello! Hopefully, this isn't a dumb question but I'm a bit confused about how `history` actually works. So right now I have `history` set to false but the following happens when I leave a snippet:

https://user-images.githubusercontent.com/43759105/158940636-17590669-19c0-4fd0-b0e2-316158739df7.mov

Because I set this value to false I'm expecting not to go the second tab stop on the itemize snippet. These snippets are loading using a vscode snippets file and here is my config:

```lua
require('luasnip').config.set_config({
    history = false,
    updateevents = "TextChanged, TextChangedI",
})
```

Is this not what history is for? It seems like that by the wording in the README and the helppage. Thanks for making this amazing neovim plugin! Saves me a ton of time while doing my homework :)

**Comment by L3MON4D3** [comment]
Hi!
No worries, not a dumb question :D
Here luasnip differs from eg. ultisnips: a snippet is only considered left once you've jumped to the last placeholder (`i(0)`), not once the cursor moves outside it.
It's possible to emulate ultisnips behaviour by setting `region_check_events` to eg. `"CursorMoved"`, in the config.

**Comment by gleich** [comment]
awesome, that seemed to do the trick. thank you :)

**Comment by avonmoll** [comment]
I am using the latest version of LuaSnip and am wanting to have the same kind of behavior this post is describing but adding `region_check_events = "CursorMoved"` doesn't seem to work anymore. Also is there an event for exiting Insert mode?

**Comment by L3MON4D3** [comment]
`region_check_events` should still work, as far as I'm aware.
What behaviour are you expecting?
Event for exiting insert mode is `InsertLeave`, those can be found in `:h events` i think

**Comment by avonmoll** [comment]
Basically, if I exit insert mode and/or move around elsewhere in the buffer I don't want to jump back into a snippet that I was in previously. I have the following setup function

```lua
require("Luasnip").config.setup({
    enable_autosnippets = true,
    history = false,
    region_check_events = "CursorMoved, InsertLeave",
    update_events = "TextChanged, TextChangedI",
})
```

This call lives in the `after/plugin` folder. Actually, after tinkering with the history stuff I realized that I'm pretty sure the `update_events` setting isn't working for me either. My understanding is that with `TextChanged, TextChangedI` that `rep` nodes, e.g., should update as you type (which they are not for me). Is it because of where I have my `setup` function call?

**Comment by L3MON4D3** [comment]
> Edit: the `update_events` does indeed work, but not with a space after the comma :wink:
Edit2: this combination is giving me what I want: `region_check_events = "InsertEnter,CursorMoved"` :tada:

Nice, glad you figured it out :+1:
We should probably sanitize the strings passed to `*_events`/assert that they don't contain spaces/allow `string[]`
