### ISSUE TITLE
Question: can I use my collection of personal json snippets with this plugin

### ISSUE THREAD

**Issue by akinsho** [L3MON4D3/LuaSnip#35]
Hi 👋🏾 ,

I'm curious about potentially using this plugin but having done a migration from ultisnips based snippets, to json based snippets. I'd rather not/won't (😆 ) do yet another migration/conversion to lua based snippets and leave everything I've created behind. I see there's some functionality for parsing json based snippets from `friendly-snippets` but I can't tell how I would do this with a custom set of json snippets I've created and have in my dotfiles.

For vim-vsnip and ultisnips they both accept a directory option which is used to source personal snippets of their particular format, all namespaced by filetype. Now, with that pre-amble over, my question is can I do something like that with this plugin?

**Comment by L3MON4D3** [comment]
I think that should be doable by mimicking friendly-snippets' layout and [package.json](https://github.com/rafamadriz/friendly-snippets/blob/main/package.json):
- Add the snippet-directory to your `runtimepath` (`:set runtimepath+=snipdir`)
- Modify the `package.json` to match your layout and put it into `snipdir`'s root

**Comment by akinsho** [comment]
Cool, thanks for clarifying. Since this was just a question to figure out if/how it could be done I'll close this now.
