### ISSUE TITLE
Error when trying to use Lua snippet loader

### ISSUE THREAD

**Issue by ckafi** [L3MON4D3/LuaSnip#350]
I just installed LuaSnip, but when I call `require("luasnip.loaders.from_lua").load()`, I get the following error:

    Error detected while processing BufWinEnter Autocommands for "*":
    E5108: Error executing lua ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:541: invalid type
    name: table: 0x7ff7e8503800
    stack traceback:
            [C]: in function 'error'
            vim/shared.lua:608: in function 'validate'
            ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:541: in function 'refresh_notify'
            ...ck/packer/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:66: in function 'load_files'
            ...ck/packer/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:99: in function '_load_lazy_loaded'
            [string ":lua"]:1: in main chunk

**Comment by L3MON4D3** [comment]
Mhmmm, that's weird.
Could you apply this patch and post the output?
```diff
diff --git a/lua/luasnip/loaders/from_lua.lua b/lua/luasnip/loaders/from_lua.lua
index 284b3fc..6998672 100644
--- a/lua/luasnip/loaders/from_lua.lua
+++ b/lua/luasnip/loaders/from_lua.lua
@@ -93,6 +93,7 @@ end
 
 function M._load_lazy_loaded()
 	local fts = util.get_snippet_filetypes()
+	print(vim.inspect(fts))
 	for _, ft in ipairs(fts) do
 		if not cache.lazy_loaded_ft[ft] then
 			cache.lazy_loaded_ft[ft] = true

```

**Comment by L3MON4D3** [comment]
Alternatively the output of `print(vim.inspect(require("luasnip.util.util").get_snippet_filetypes()))`

**Comment by ckafi** [comment]
For the patch:

    { "", "all" }
    Error detected while processing BufWinEnter Autocommands for "*":
    E5108: Error executing lua ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:541: invalid type name: table: 0x7f81d51e4f70
    stack traceback:
            [C]: in function 'error'
            vim/shared.lua:608: in function 'validate'
            ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:541: in function 'refresh_notify'
            ...ck/packer/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:66: in function 'load_files'
            ...ck/packer/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:100: in function '_load_lazy_loaded'
            [string ":lua"]:1: in main chunk

The `:lua` command prints `{ "", "all" }`

**Comment by L3MON4D3** [comment]
Weird, that's all correct..
Could you apply this patch and post the output?
```diff
diff --git a/lua/luasnip/init.lua b/lua/luasnip/init.lua
index 157f620..1df3cf1 100644
--- a/lua/luasnip/init.lua
+++ b/lua/luasnip/init.lua
@@ -538,6 +538,7 @@ local function cleanup()
 end
 
 local function refresh_notify(ft)
+	print(vim.inspect(ft))
 	vim.validate({
 		filetype = { ft, { "string", "nil" } },
 	})
```

**Comment by ckafi** [comment]
Prints `"all"`, then throws the same error.

**Comment by L3MON4D3** [comment]
What version of nvim are you on? Maybe that call, `validate`, was changed some time ago.

**Comment by phha** [comment]
I'm getting a similar error with v0.6.1

**Comment by ckafi** [comment]
It's 0.6.1, from the arch repos

    NVIM v0.6.1
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compiled by builduser
    
    Features: +acl +iconv +tui

**Comment by L3MON4D3** [comment]
Mhm, that's fairly recent.
To be sure that's not it, does `vim.validate(foo={"bar", {"string", "nil"}})` error?

**Comment by L3MON4D3** [comment]
Hah, okay, I might've accidentally added some code that isn't yet in any point-release.
You can install `neovim-git` from the aur to fix this right away, I'll add a proper fix for this soon.

**Comment by ckafi** [comment]
Thanks, that's appreciated.
