### ISSUE TITLE
Can't change choice if insert mode has default text

### ISSUE THREAD

**Issue by anguye21** [L3MON4D3/LuaSnip#360]
When using an insert node with a default value inside a choice node `ls.change_choice` does not do anything until something is typed after which you can then proceed to change choices. 

Here's an an example of a snippet where this issue occurs:

```lua
s("try", fmt([[
      try:
          {}
      except {}{}:
          {}
  ]],
  {
      i(1, "pass"),
      i(2, "Exception"),
      c(3, {
          fmt(" as {}", { i(1, "e") }, { dedent = false }),
          t("")
      }),
      i(0, "pass")
  })
))
```

**Comment by L3MON4D3** [comment]
#311 :P
