### ISSUE TITLE
Snippet won't expand after LuaSnip update

### ISSUE THREAD

**Issue by s1n7ax** [L3MON4D3/LuaSnip#362]
Expand works in be92398271b50d82536c10f5d0a4518fed6f85d3 but not 276bcc674614b05ac74dfbfdc515dd3e6411a02f. I don't know how in the word two doc files breaks it but it is broken.

https://user-images.githubusercontent.com/18459807/160679523-c3573945-1cb8-486c-b37d-2a5a574e2385.mp4

Note: I'm not hard coding the snippets. Instead I'm adding them when the plugin is initialized but everything worked all this time until I :PackerSync ed
[nvim/plugins/luasnip/snippet_manager.lua](https://github.com/s1n7ax/dotnvim/blob/6dd89f015875f223eafd053e61b10223b18192e2/lua/nvim/plugins/luasnip/snippet_manager.lua)
```
-- M:add_snippet adds a new snippet
function M:add_snippet(snippet)
    if not ls.snippets[self.language] then
        ls.snippets[self.language] = {}
    end

    table.insert(ls.snippets[self.language], snippet)
end
```

**Comment by leiserfg** [comment]
Since https://github.com/L3MON4D3/LuaSnip/commit/aeea587385d7504956259e1d9e6aaeaf23b2aeb2 was merged you are not supposed to access `ls.snippets` by hand. Check the doc about `add_snippets`.
