### ISSUE TITLE
Choice Node selection but only once and after typing?

### ISSUE THREAD

**Issue by hahuang65** [L3MON4D3/LuaSnip#363]
I've got a snippet configured like so:

```
  s("def",
    fmt(
      [[
        def {}
          {}
        end
      ]],
      {
        c(1, {
          i(1, "method_name"),
          sn(1, {
            i(1, "method_name"),
            t("("),
            i(2, "args"),
            t(")")
          })
        }),
        i(0)
      }
    )
  )
```

The intent is to be able to toggle between

```
def method_name
  {}
end
```

and

```
def method_name(args)
  {}
end
```

where `method_name` and `args` are both insert nodes, and landing the user at the `{}` in the end.

However, when I trigger this snippet, I'm unable to toggle between `method_name` and `method_name(args)` until I start typing to change `method_name`, at which point, I am able to toggle to `method_name(args)`, but unable to toggle back to `method_name`.

I must be doing something wrong, please let me know!

**Comment by L3MON4D3** [comment]
Pretty sure this is another case of #311

**Comment by hahuang65** [comment]
@L3MON4D3 I've got that mapped here though...

https://github.com/hahuang65/nvim-config/blob/3332e68214b88bafc25dc743f36657329cb29239/lua/keymaps.lua#L180

Perhaps for some reason `ls.choice_active` is returning false for me cuz of how I wrote the snippet?

**Comment by hahuang65** [comment]
Oh is it because I've only bound it in insert mode?

**Comment by L3MON4D3** [comment]
Yep, that's it
