### ISSUE TITLE
Cannot detect my customized snippets when use lazy_load(), but friendly-snippets can be detected

### ISSUE THREAD

**Issue by milanglacier** [L3MON4D3/LuaSnip#364]
My snippets folder are put in `~/.config/nvim`,
it's like:
```
nvim/
├─ snippets/
│  ├─ package.json
│  ├─ python.json
```
my package.json looks like this:
```
{
    "name": "snippets",
    "engines": {
      "vscode": "^1.11.0"
    },
    "contributes": {
      "snippets": [
 
        {
          "language": "python",
          "path": "./python.json"
        }

      ]
    }
  }
```
my `config.luasnip` is
`require("luasnip.loaders.from_vscode").lazy_load()`,
But if I change `config.luasnip` to
`require("luasnip.loaders.from_vscode").lazy_load({paths = {"~/.config/nvim/snippets"}})`
then I can load my customized snippets but I cannot load friendly-snippets.
so I don't know what I am doing wrong here.

I am using nvim-cmp, and the related config is:
```
    snippet = {
        -- REQUIRED - you must specify a snippet engine
        expand = function(args)
            require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        end,
    },

```

How can I load them both?
Thanks for your help!
`nvim --version`
```
NVIM v0.7.0-dev+1356-g75ff156d9
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by northyear@Encroachments.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-75ff156/share/nvim"

Run :checkhealth for more info
```
`luasnip` is at commit `9017e57925eecedbbd530dd4f913ee8135611d25`

**Comment by milanglacier** [comment]
> You should be able to call the two:
> 
> ```lua
> require("luasnip.loaders.from_vscode").lazy_load()   -- this will load the default paths
> require("luasnip.loaders.from_vscode").lazy_load({paths = {"~/.config/nvim/snippets"}})  --this will load yours
> ```
> 
> internally lazy_load takes care of not loading the same path twice.

This works! Thank you!

**Comment by melkster** [comment]
I had an issue with my custom snippets no longer loading since a couple months back and I finally looked into it, and it seems as if

```lua
luasnip.filetype_extend('all', {'global'})
```

isn't respected if I use `lazy_load()`. If I switch in your code above from `lazy_load()` to `load()` it works however.

This is what `~/.config/nvim/snippets/package.json` looks like:

```json
{
  "name": "snippets",
  "engines": {
    "vscode": "^1.11.0"
  },
  "contributes": {
    "snippets": [
      {
        "language": [ "global" ],
        "path": "./global.json"
      }
    ]
  }
}
```

Is this a bug?
