### ISSUE TITLE
Cannot load snippets in nvim 0.6.1

### ISSUE THREAD

**Issue by dennisfrostlander** [L3MON4D3/LuaSnip#365]
Encountered a strange error in neovim 0.6.1 on Linux when loading Lua snippets from file.

It all boils down to the fact that `vim.loop.fs_read` cannot be called with 2 arguments:

```
:lua vim.loop.fs_read(1, 1)
```

```
Error executing lua [string ":lua"]:1: bad argument #3 to 'fs_read' (number expected, got no value)
stack traceback:
        [C]: in function 'fs_read'
        [string ":lua"]:1: in main chunk
```

This same error occurs [here](https://github.com/L3MON4D3/LuaSnip/blob/b00180096afd2ff42c59456dc71e36aa02409a8d/lua/luasnip/loaders/from_lua.lua#L24) in `from_lua` loader.

Adding a 3rd argument (0) fixes the issue:
```lua
local func_string = vim.loop.fs_read(fd, size, 0)
```

Cannot find much documentation for `vim.loop.fs_read`, but I guess the fix above seems reasonable?

More info:

```
nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Simple repro:
```lua
  require("luasnip.loaders.from_lua").load({
    paths = {
      "/my-dir"
    }
  })
```

**Comment by leiserfg** [comment]
That's really unexpected as that's how the luvit API is documented to work, and that's how they use  the api in the [tests ](https://github.com/luvit/luv/blob/b85b9ef7b4c0abb2b507632ad3b885c965ccc0c4/tests/test-fs.lua#L20)

**Comment by L3MON4D3** [comment]
Beat me to it :D
I'd be open to adding the `0` if there is no other fix, could you check which version of luv neovim is using?

**Comment by L3MON4D3** [comment]
Looks like neovim 0.6.1 requires only [luv 1.30](https://github.com/neovim/neovim/blob/v0.6.1/CMakeLists.txt#L390), which is 3 years old at this point

**Comment by L3MON4D3** [comment]
`offset` was mandatory in [`luv 1.36.0`](https://github.com/luvit/luv/blob/1.36.0-0/docs.md#uvfs_readfd-size-offset-callback), so that's probably it.

As this won't break with newer versions of luv we can just add the 0 I think.
