### ISSUE TITLE
Question on adding custom json files as snippets.

### ISSUE THREAD

**Issue by thepenguinthatwants** [L3MON4D3/LuaSnip#37]
Hi,
I've being trying to get friendly-snippets to work or figure out how to. 
Although my aim is to actually alter them for my own needs.

Seems like there have being few mentions found, but I still couldn't get it to work.

https://old.reddit.com/r/neovim/comments/o66q3d/which_snippet_plugin_do_you_prefer_moving_out/h2x7enh/?context=10000
https://github.com/L3MON4D3/LuaSnip/issues/35

From Folke's comment.
You need to add the below in your config to load friendly snippets:
`lua require("luasnip/loaders/from_vscode").load()`

I actually took and use
https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua

So its included.

I also have  friendly-snippets installed using packer.
`use 'rafamadriz/friendly-snippets'`

Regarding the runtimepath

The plugins are and snippets seems to be here.
~/.local/share/nvim/site/pack/packer/start/friendly-snippets/snippets

So I copied them to here 
~/.config/nvim/lua/friendly-snippets

Not really sure how to continue.

I guess the missing part is the setting of runtimepath, but I dont fully grasp this.
```
Add the snippet-directory to your runtimepath (:set runtimepath+=snipdir)
Modify the package.json to match your layout and put it into snipdir's root
```

**Comment by L3MON4D3** [comment]
I think you're pretty much there, just `runtimepath+=~/.config/nvim/lua/friendly-snippets` (before `from_vscode.load()`) should get you there.
If it doesn't, could you show the layout of `~/.config/nvim/lua/friendly-snippets`?

**Comment by thepenguinthatwants** [comment]
I think I just need to set it into lua way than like this.
```
runtimepath+=~/.config/nvim/lua/friendly-snippets
require("luasnip/loaders/from_vscode").load()

```
As there was error.
`E5113: Error while calling lua chunk: vim.lua:63: /home/penguin/.config/nvim/lua/nvim-luasnip/init.lua:209: '=' expected near '+'`

**Comment by L3MON4D3** [comment]
Ah yeah, I'm not sure how to set that in lua directly, but `vim.cmd('runtimepath+=...')` should work then.

**Comment by thepenguinthatwants** [comment]
Yeah 
vim.o.runtimepath seems to be the correct one as it doesnt give error anymore.
In my python file its still not giving any of the snippets.

~/.config/nvim/lua/friendly-snippets contains the repository of this

https://github.com/rafamadriz/friendly-snippets

**Comment by leiserfg** [comment]
You don't have to use "friendly-snippets" you can use any folder in the `runtimepath`  will work, just do  `set runtimepath` and you will see them,  for instance, `~/.config/nvim`  so you can just add the  `package.json` like this one `https://github.com/rafamadriz/friendly-snippets/blob/main/package.json`  pointing yo your snippets files.

**Comment by thepenguinthatwants** [comment]
For now in my configs I have this.
```
vim.o.runtimepath = vim.o.runtimepath..'~/.config/nvim/lua/friendly-snippets'
require("luasnip/loaders/from_vscode").load()
```

~/.config/nvim/lua/friendly-snippets
in this directory it consists  package.json file, but it still doesnt seem to take it on effect.

**Comment by leiserfg** [comment]
I guess you are missing a `,`  in the `runtimepath`, it's a comma-separated-list string.

**Comment by thepenguinthatwants** [comment]
Do you mean like  

`vim.o.runtimepath = vim.o.runtimepath..'~/.config/nvim/lua/friendly-snippets,'`   ?
It didn't seem to make a difference.

**Comment by L3MON4D3** [comment]
Your runtimepath should be `...,~/.config/nvim/lua/friendly-snippets,`, depending on your config you may have to add a comma before `~/.config/nvim/lua/friendly-snippets,`. If it doesn't work after that, best post the output of `tree ~/.config/nvim/lua/friendly-snippets`

**Comment by thepenguinthatwants** [comment]
I've tried with, but still doesnt work.

`vim.o.runtimepath = vim.o.runtimepath..',~/.config/nvim/lua/friendly-snippets,'`

From output of `tree ~/.config/nvim/lua/friendly-snippets
`

````
/home/penguin/.config/nvim/lua/friendly-snippets
├── LICENSE
├── media
│   ├── html.gif
│   └── js.gif
├── package.json
├── README.md
└── snippets
    ├── c.json
    ├── cpp.json
    ├── css.json
    ├── ejs.json
    ├── erb.json
    ├── fennel.json
    ├── fortran.json
    ├── global.json
    ├── go.json
    ├── haskell.json
    ├── html.json
    ├── java.json
    ├── javascript
    │   ├── apollo.json
    │   ├── javascript.json
    │   ├── react.json
    │   ├── react-ts.json
    │   └── typescript.json
    ├── latex.json
    ├── lua.json
    ├── markdown.json
    ├── php.json
    ├── python
    │   ├── base.json
    │   ├── comprehension.json
    │   ├── debug.json
    │   ├── python.json
    │   ├── tkinter.json
    │   └── unittest.json
    ├── rails.json
    ├── ruby.json
    ├── rust.json
    ├── shell.json
    ├── sql.json
    ├── swift.json
    └── vue
        ├── html.json
        ├── javascript.json
        ├── pug.json
        └── vue.json

5 directories, 42 files

```

**Comment by L3MON4D3** [comment]
Looks fine...
Weirdly enough, `:set runtimepath+=...` works, but `:lua vim.o.runtimepath = ...` doesn't, could you try if that is the case for you too?

**Comment by L3MON4D3** [comment]
Ofc it's something stupid, vim automatically expands `~` to your home dir when set via `:set runtimepath`, which doesn't happen in lua. So far it makes sense, but when printed via `:set runtimepath?` `/home/someone` gets shortened to `~`, which means that you can't differentiate between the valid `/home/someone/...` and the invalid `~/...`.
Setting `vim.o.runtimepath = vim.o.runtimepath .. ',/home/penguin/.config/nvim/lua/friendly-snippets'` shoud fix it.

**Comment by thepenguinthatwants** [comment]
That  was it :D :+1:  

vim.o.runtimepath = vim.o.runtimepath .. '/home/penguin/.config/nvim/lua/friendly-snippets,'
and it works fine. Thanks very much. It was also foolish of me not trying the full paths earlier.

**Comment by thepenguinthatwants** [comment]
I think this should maybe add to as example. As many might not dare to use luasnip as it doesn't have much examples yet.

**Comment by L3MON4D3** [comment]
Glad it works :D
Yeah I will, I wasn't aware that many people use custom json snippets, though it makes complete sense 😅

**Comment by leiserfg** [comment]
vim.o.runtimepath = vim.o.runtimepath..',~/.config/nvim/lua/friendly-snippets'

**Comment by leiserfg** [comment]
> Glad it works :D
> Yeah I will, I wasn't aware that many people use custom json snippets, though it makes complete sense sweat_smile

@L3MON4D3 I'm extending the loader to add paths by hand and to filter (in and out) languages (so it does not load all the snippets if is not required).
Will make a PR when I finish with it today.

**Comment by leiserfg** [comment]
> I think this should maybe add to as example. As many might not dare to use luasnip as it doesn't have much examples yet.

vim.o.runtimepath = vim.o.runtimepath..',~/.config/nvim/lua/friendly-snippets'

**Comment by L3MON4D3** [comment]
> > Glad it works :D
> > Yeah I will, I wasn't aware that many people use custom json snippets, though it makes complete sense sweat_smile
> 
> @L3MON4D3 I'm extending the loader to add paths by hand and to filter (in and out) languages (so it does not load all the snippets if is not required).
> Will make a PR when I finish with it today.
> 
> After the extention it will be posible to call `load()` as now but also `load({paths={'~/.config/my-snippets'}})`

Great Idea! Especially the filter👌

**Comment by matrixersp** [comment]
> Setting `vim.o.runtimepath = vim.o.runtimepath .. ',/home/penguin/.config/nvim/lua/friendly-snippets,'` shoud fix it.

Couldn't get it to work on `*.js` files
snippets directory path: `~/.config/nvim/lua/friendly-snippets`
my config:
```lua
vim.o.runtimepath = vim.o.runtimepath .. ',' .. os.getenv('HOME') .. '/.config/nvim/lua/friendly-snippets,'
require("luasnip/loaders/from_vscode").load()
```

**Comment by DrkCoater** [comment]
> > Setting `vim.o.runtimepath = vim.o.runtimepath .. ',/home/penguin/.config/nvim/lua/friendly-snippets,'` shoud fix it.
> 
> Couldn't get it to use react snippets in `*.js` files snippets directory path: `~/.config/nvim/lua/friendly-snippets` my config:
> 
> ```lua
> vim.o.runtimepath = vim.o.runtimepath .. ',' .. os.getenv('HOME') .. '/.config/nvim/lua/friendly-snippets,'
> require("luasnip/loaders/from_vscode").load()
> ```
This is because friendly-snippets configure *.jsx to use react snippets.
You need to add:
```lua
            luasnip.filetype_extend("javascriptreact", { "js" })
```
