### ISSUE TITLE
Add autotrigger to loaders/from_snipmate

### ISSUE THREAD

**Issue by nullchilly** [L3MON4D3/LuaSnip#372]
[loaders/from_vscode](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/loaders/from_vscode.lua) supports autotrigger. 

[loaders/from_snipmate](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/loaders/from_snipmate.lua) does not. Can we adopt [UltiSnips.txt#Autotrigger](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1732)?

I can't find any documentation on this? It would be nice to see actual examples about autosnippets in Examples/

Pardon me for my ignorance!

**Comment by L3MON4D3** [comment]
Yep, there is no Autotrigger-support for snipmate snippets.
It'd be nice to have, I agree, but directly using the ultisnips-format, eg postfix a, won't be possible because there we have the docstrings, which isn't enclosed in `""`.

Not sure how to best pass options, maybe specific keywords that only affect the next snippet?

**Comment by tuwuna** [comment]
> Not sure how to best pass options, maybe specific keywords that only affect the next snippet?

Maybe this wouldn't hurt?

```
if vim.startswith(line, "snippet") then
	_parse()
elseif vim.startswith(line, "autosnippet") then
	_parse(1)
```

Maybe consider  `loaders/from_ultisnips` in the future with condition support

**Comment by L3MON4D3** [comment]
Oh yeah, that looks pretty nice.

Conditions may be doable, I'll think about it.

Loading ultisnips-snippets would be pretty nice, but we won't be able to do the python-stuff (not without great effort, at least).
There also is https://github.com/smjonas/snippet-converter.nvim for converting snippets between different formats.

**Comment by tuwuna** [comment]
I tried to do add this but it seems like I have to add the auto_snippets table everywhere I go, also not exactly sure how the cache works.

Low on time so I am using `ls.add_snippets(ft, snippets, { type = "autosnippets"})` instead...

@uga-rosa would you like to take a look? Sorry for my impatient but I think it would be easier for you to add this 😅

**Comment by uga-rosa** [comment]
Sorry, I'm not feeling well right now and will be delayed in responding.

**Comment by leiserfg** [comment]
> Sorry, I'm not feeling well right now and will be delayed in responding.

Hope it's nothing serious.

**Comment by L3MON4D3** [comment]
> @leiserfg Thank you, I haven't had a fever of 39 ℃ for a long time.
> 
> I will try to implement it in the next week or so. After all, I just moved and don't even have WiFi at home yet.

Oh yikes, hope you're better now.

I have a bit of time, I'll see if I can get somewhere.

**Comment by L3MON4D3** [comment]
#390 implements autosnippets, go check it out

**Comment by nullchilly** [comment]
It works, thanks you so much :D 

I will keep testing for some potential bugs 🗡️

**Comment by L3MON4D3** [comment]
Finally got to merging this, it's on master now :)
