### ISSUE TITLE
`require("luasnip.loaders.from_vscode").lazy_load()` doesn't work

### ISSUE THREAD

**Issue by wizard-28** [L3MON4D3/LuaSnip#374]
## Problem

```lua
require("luasnip.loaders.from_vscode").lazy_load()
``` 

Doesn't load the snippets from `friendly-snippets` plugin.

However it works when I manually load it by running

```lua
:lua require("luasnip.loaders.from_vscode").load({ include = { "python" } })
```

## Config files

* [packer config](https://sourceb.in/Gzq56GQD6n)
* [nvim-cmp config](https://sourceb.in/r3nHOdiFbv)

***NOTE:*** *I write my config files in fennel, the above links are to the compiled lua output, so it looks unconventional.*

**Comment by wizard-28** [comment]
> Looks (? I'm not that sure when it comes to packer's features) like you're adding luasnip and friendly-snippets on some event, could you check if the problem persists if they are loaded directly, eg on startup?

I'll check it out tomorrow, sorry for the delay.

**Comment by L3MON4D3** [comment]
No problem, it's still working for me, so not a general issue I think

**Comment by wizard-28** [comment]
Yeah, loading it on startup works. Thanks.
