### ISSUE TITLE
Is there a way to simulate Ultisnip's `${1}, ${2:$1}` snippet

### ISSUE THREAD

**Issue by vlad-tymoshchyk** [L3MON4D3/LuaSnip#375]
In Ultilsnips when you use `${2:$1}` in your snippet, it copies the text from the first input and also enters visual mode with whole input text selected.

In LuaSnip I know how to make one input copy text from another input, but when I jump to it, it is not visually selected and I need to clear it manually if I want to change it.

**Comment by L3MON4D3** [comment]
You can pass the text from the $1 to a dynamic instead of functionNode, that way you can generate an insertNode with the preset-text from the first insertNode.

```lua
s("trig", {
	i(1, "some text"),
	d(2, function(args) return sn(nil, t(args[1])) end, {1})
})
```
should do it I think.

**Comment by vlad-tymoshchyk** [comment]
@L3MON4D3, thank you for your response, 
The result is still a bit different from what I meant,
I the second node to contain the content of the first node and to be visually selected so I can either jump forward and leave it as it is or just start typing and old content is automatically cleared.

Here is the snippet I tried:
```
s("clg", {
  t("console.log('"),
  i(1),
  t("', "),
  d(2, function(args) return sn(nil, t(args[1])) end, {1}),
  t(");")
})
```
And here is how it's different from what I want:
(In the second snippet I jump just to the end of snippet, the `name` is not highlighted)
![snippet_full](https://user-images.githubusercontent.com/25420932/162439863-d50c647f-81df-4367-a2a5-c20cb907bc8d.gif)

**Comment by L3MON4D3** [comment]
Ah, my bad, substitute `t(args[1])` (static text) with `i(args[1])` (insertNode with preset-text), then it should be highlighted.
As a shorthand you can also use `dynamicLambda` (`dl`): `{i(1, "text"), dl(2, l._1, {})}`

**Comment by vlad-tymoshchyk** [comment]
It works now, thank you.

There seems to be another issue, is there a problem with passing `0` index to dynamic node?

When expending the following snippet I'm getting the error `attempt to get length of local 'position_so_far' (a nil value)`

```
  s("clg", {
    t("console.log('"),
    i(1),
    t("', "),
    d(0, function(args) return sn(nil, { i(1), i(1, args[1]) }) end, {1}),
    t(");"),
  })
```
(the problem is that I want the second jump to be the last one, but instead there is another jump-position at the end of the line)

**Comment by L3MON4D3** [comment]
That's not possible :/
For luasnip, the 0th placeholder has to be just the exit-point of the snippet, eg. where your cursor ends up after jumping through the entire thing, unlike ultisnips.

**Comment by hiberabyss** [comment]
Could this supported the snipmate snippets?

**Comment by hiberabyss** [comment]
It should be the nested tabstop feature, as the snipmate document:

https://github.com/garbas/vim-snipmate/blob/master/doc/SnipMate.txt#L363

**Comment by L3MON4D3** [comment]
It's supported (in a way): instead of the Visually selected nested placeholder, you get a choiceNode that contains the nested snippet, and an empty `insertNode`.
So, to clear the Selected text, you'll just have to jump to the next choice once.

This behaviour can actually be customized though, check [here](https://github.com/L3MON4D3/LuaSnip/wiki/Nice-Configs/_edit#imitate-vscodes-behaviour-for-nested-placeholders) for changing it to what you'd rather have, probably.

**Comment by hiberabyss** [comment]
it's too complicated to configure.

**Comment by L3MON4D3** [comment]
You can just paste it into your config :P
But I can see what you're getting at, I'll consider including it in `luasnip.extras`
