### ISSUE TITLE
Placeholders have previous placeholders as default values

### ISSUE THREAD

**Issue by jackfranklin** [L3MON4D3/LuaSnip#382]
Hello,

Firstly: please excuse me if I've missed this, but from reading all the docs I can't figure it out.

Is it possible to define a snippet that has a placeholder whose default value is a prior placeholder?

e.g.:

```
import $1 from '$2:$1';
```

So here `$2` would default to `$1` but would still be jumpable to to make edits. I tried this but it doesn't seem to work so I'm unsure if it's unsupported or if I'm not using it right.

Thanks!

**Comment by L3MON4D3** [comment]
#375 should do it I think
