### ISSUE TITLE
Can't call get_snippets, nil value

### ISSUE THREAD

**Issue by danielo515** [L3MON4D3/LuaSnip#386]
Hello.
There is a mention on the docs about a function `get_snippets`, but when I try to call it I get an error saying it is a nil value.
Was this function removed from the API?

**Comment by L3MON4D3** [comment]
Weird..
It works for me with `require("luansip").get_snippets()`, is your luasnip up to date?

**Comment by danielo515** [comment]
I think it does. I'm using lunarvim and they claim to use an up to date version, but I have to use available method instead.

**Comment by L3MON4D3** [comment]
[You're right](https://github.com/LunarVim/LunarVim/blob/rolling/snapshots/default.json#L12), something else must've gone wrong in your case, I can't figure out how this could be `nil`.
AFAICT lunarvim also just uses Packer, could you find the directory luasnip is installed on your machine and verify that you're actually on 5d3b468 (and that there are no other installations, maybe add a `print("foo")` at the top of `lua/luasnip/init.lua` to make sure it's actually being sourced)?

**Comment by danielo515** [comment]
yes, sure, I'll try that out

**Comment by danielo515** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/2270425/163657411-56496845-fe86-4e0b-a928-b9736e0a3f16.png">
Seems that I am not on the right commit. The file you linked is from rolling version of lunarvim, which I think is not the stable one?

**Comment by L3MON4D3** [comment]
Ah, that's right, I found it on their `master`.
Wow, you're exactly one commit before e1bb499, which makes `get_snippets` available xD

Not sure how you'd like to proceed, just be aware that there are [Breaking Changes to adding snippets](https://github.com/L3MON4D3/LuaSnip/issues/81#issuecomment-1073301357) between your commit and now (or lunarvims rolling version)

**Comment by danielo515** [comment]
I think I will wait for the latest version of lunar vim to become the stable one, I already have a workaround in place.
Does that braking changes affect how snip mate or vscode snippets are loaded? Because if not, then I'm Ok

**Comment by L3MON4D3** [comment]
Oh, the loaders continue to work just fine, only the manual `ls.snippets = {...}` is affected
