### ISSUE TITLE
require("luasnip.loaders.from_vscode").load failed to load snippets

### ISSUE THREAD

**Issue by neevek** [L3MON4D3/LuaSnip#388]
With the following commands to load `snipmate` snippets, I can see my snippets are loaded:
```lua
:lua require("luasnip.loaders.from_snipmate").load({ paths = "~/.config/nvim/lua/custom/sm_snippets" })
:lua print(vim.inspect(require('luasnip.loaders._caches')))
```
With the following commands to load `rafamadriz/friendly-snippets`, the caches are empty:
```lua
:lua require("luasnip.loaders.from_vscode").load({ paths = "~/dev/github/friendly-snippets" })
:lua print(vim.inspect(require('luasnip.loaders._caches')))
```

**Comment by L3MON4D3** [comment]
That's to be expected, the vscode-loader only uses the cache when lazy_loading.
You can try `:LuaSnipListAvailable` to show which snippets are available in your current file.

**Comment by neevek** [comment]
My bad, the snippets are not seen in the caches, but are actually loaded, I can use them after calling `load()`.
The root cause of the problem is that I didn't get it right on the vscode snippets format (JSON format), I added a comma at the last field of a JSON object.
