### ISSUE TITLE
Modifying an insert node based on its contents

### ISSUE THREAD

**Issue by markhuge** [L3MON4D3/LuaSnip#391]
Hi, I have an insert node `i(1)` that I would like to surround in parenthesis if it contains more than one comma separated value. Example `foo` vs `(foo, bar)`.

I'm not sure at which point `i(1)` is expanded and can be evaluated. My naive first attempt was:

```lua
local function expand_return(position)
        return d(position, function()
        local nodes = { i(1) }
        local rtrn = vim.split(nodes[1],",", true)

        if #rtrn > 1 then
                table.insert(nodes, 1, t "(")
                table.insert(nodes, 3, t ")")
        end

                return sn(nil, nodes)

        end, {})
end
```

Is a dynamic node even the right thing to use here? I tried several permutations with function nodes but I always seemed to run into this chicken/egg problem with the insert node. (I also don't know lua, so may just be doing something dumb).

**Comment by leiserfg** [comment]
It's easier to use a couple of `match` :

```lua
local m = require("luasnip.extras").m

......
s(
  "return",
  fmt("return  {leftp}{val}{rightp}", {
    val = i(1, "username"),
    leftp = m(1, ",", "("),
    rightp = m(1, ",", ")"),
  })
),
```

**Comment by markhuge** [comment]
@leiserfg that's nice, and I will definitely use that, thank you!

For the sake of my edification, if I wanted to dynamically update an insert node based on its value, is that something I'd be able to do? If so, when would it get expanded, and would the dynamic node be the right tool for the job?

**Comment by L3MON4D3** [comment]
That isn't possible I'm afraid, for that the dynamicNode would have to depend on itself, which isn't implemented.

So far I couldn't think of a usecase that isn't achievable otherwise.

**Comment by markhuge** [comment]
Gotcha! Totally makes sense, just wanted to make sure I wasn't missing something there. 

Thanks!
