### ISSUE TITLE
Invoke snippets vim-native way (<C-x><C-...>)

### ISSUE THREAD

**Issue by timsofteng** [L3MON4D3/LuaSnip#392]
Hello. I use luasnip with cmp autocompletion and it works awesome.
But can I somehowe invoke only snippets source with or without cmp?

**Comment by L3MON4D3** [comment]
I don't know of any completion-source that provides luasnip-snippets to omnicompletion if that's what you're asking :/

**Comment by timsofteng** [comment]
> I don't know of any completion-source that provides luasnip-snippets to omnicompletion if that's what you're asking :/

Thanks
I've solved my issue with cmp.


Have another question.
Is it any possible way to have circle luasnip.jump? I mean jumping to first element after last one.

**Comment by L3MON4D3** [comment]
Mhmm no, would that be useful? One immediate problem I can make out is that it somewhat clashes with history, there you are able to jump back/forward into entirely different snippets, that wouldn't be possible if a jump from the end brings you back to the start.
