### ISSUE TITLE
using env.SELECT_ multiple lines, only first line is indented as expected

### ISSUE THREAD

**Issue by Frydac** [L3MON4D3/LuaSnip#395]
Hi,

Not sure if I'm doing something wrong, or this is not supported well, or I should just deal with it myself.

Say I add the snippet (useful for the unittest framework I use), which wraps the visual selection in a curly bracket block (C++), where I would like the visual selection to be indented 1 more level (4 spaces in my case)
```
    ls.add_snippets("cpp", {
        s("S", fmt([[
            SECTION("{}")
            {{
                {}
            }}
        ]], { i(1, "default"), f(function (_, snip) return snip.env.SELECT_DEDENT end, {}) })),
    })
```

When I now try to wrap multiple lines of code with this SECTION snippet, e.g. I have these lines of code
```
std::vector<int> vec;
vec.push_back(1);
```
I visually select these lines, use my `store_selection_keys` and use/expand the above snippet.
This results in the following, where the first line is indented as I would like, but any subsequent lines are not:
```
SECTION("default")
{
    std::vector<int> vec;
vec.push_back(1);
}
```

This is very quickly fixed with triggering my formatter, but still.. would be nice if the other lines have the same indentation as the first line.

FYI: Similar behavior for SELECT_RAW.

While writing this, I thought maybe it was a `local fmt = require('luasnip.extras.fmt')` thing, but it also happens when using the following snippet:
```
    ls.add_snippets("cpp", {
        s("S", {
            t("SECTION(\""), i(1, "default"), t("\")"),
            t({"", "{"}),
            t({"", "    "}), f(function (_, snip) return snip.env.SELECT_DEDENT end, {}),
            t({"", "}"})
        })
```

I guess I could loop over all the lines in the selection and add a
`t({"", "    "}), f(function () return line end, {})`
for each line, but yeah, would be nice if I didn't have to :)

**Comment by L3MON4D3** [comment]
Oh, I don't think this is explicitly explained anywhere, you can use the indentSnippetNode (`require("luasnip.").indent_snippet_node`) to get this effect:

```lua
ls.add_snippets("cpp", {
s("S", {
	t("SECTION(\""), i(1, "default"), t("\")"),
	t({"", "{"}),
	-- isn only applies indent at newlines, so a `    ` is still needed to indent the first line.
	t({"", "    "}), isn(2,
		f(function (_, snip) return snip.env.SELECT_DEDENT end, {}),
		-- indent with four spaces.
		"$PARENT_INDENT    "),
	t({"", "}"})
})
```

Needing to add the indent for the first line every time can be a bit annoying, you could do something like this:

```lua
local function indent(pos, nodes, indent)
	table.insert(nodes, 1, t(indent:gsub("$PARENT_INDENT", "")))
	return isn(pos, nodes, indent)
end
```

**Comment by Frydac** [comment]
Thanks for the help.

However, it seems that the second argument `snip` of the `function (_, snip)` in the function node doesn't get passed the correct table.

**Comment by L3MON4D3** [comment]
Right!
The function signature is a bit unexpected: it doesn't get the surrounding snippet (which has `env` and the like), but the immediate parent, in this case the `indentSnippetNode` (this isn't communicated very clearly I'm afraid, especially since in most examples the immediate parent is the snippet).
The solution is pretty simple though:
```lua
function(args, parent)
    snip=parent.snippet
    ... 
end
```
You can also change this behaviour kind of globally:
[This](https://github.com/L3MON4D3/Dotfiles/blob/1214ff2bbb567fa8bdd04a21976a1a64ae931330/.config/nvim/lua/plugins/luasnip/helpers.lua#L8) is a function that simply wraps a `functionNode` and passes it the snippet instead of the immediate parent.
