### ISSUE TITLE
lua loader not work

### ISSUE THREAD

**Issue by iujakchu** [L3MON4D3/LuaSnip#397]
Hi,
I got
 ```Error in packer_compiled: [string "require("luasnip").setup_snip_env() return {..."]:34: attempt to call global 'ins_generate' (a nil value)```
in
```lua
require("luasnip.loaders.from_lua").load {}
```
I've placed a lua.lua file in `.config/nvim/luasnippets` according to README.And add_snippets actually worked.
How can I fix this problem?

**Comment by L3MON4D3** [comment]
Did you copy the snippet-file from my config? :D
I have some additional globals, see [here](https://github.com/L3MON4D3/Dotfiles/blob/master/.config/nvim/lua/plugins/luasnip/init.lua#L21-L69).
Setting those in `setup` should make it work I think.

**Comment by iujakchu** [comment]
> Did you copy the snippet-file from my config? :D I have some additional globals, see [here](https://github.com/L3MON4D3/Dotfiles/blob/master/.config/nvim/lua/plugins/luasnip/init.lua#L21-L69). Setting those in `setup` should make it work I think.

Yes,I copied from your repo :D
And I works now,Thanks for you help!!

**Comment by L3MON4D3** [comment]
You're welcome :)
