### ISSUE TITLE
`get_static_text` doesn't work for snippet node

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#400]
In order to reproduce source this file:
```lua
local sn = require("luasnip").snippet_node
local snippet = sn(1, {})
print(snippet:get_static_text())
```
I get an error:
```
E5108: Error executing lua ...m/site/pack/nix/start/luasnip/lua/luasnip/nodes/node.lua:294: attempt to index local 'dic
t' (a nil value)
stack traceback:
        ...m/site/pack/nix/start/luasnip/lua/luasnip/nodes/node.lua:294: in function 'set_argnodes'
        ...ite/pack/nix/start/luasnip/lua/luasnip/nodes/snippet.lua:1079: in function 'set_argnodes'
        ...ite/pack/nix/start/luasnip/lua/luasnip/nodes/snippet.lua:687: in function 'fake_expand'
        ...ite/pack/nix/start/luasnip/lua/luasnip/nodes/snippet.lua:705: in function 'get_static_text'
        [string ":source (no file)"]:3: in main chunk
```
I noticed it, because I'm using `snip:get_static_text()` in `parser_nested_assembler`. It was working a couple of months before.

Also looks like https://github.com/L3MON4D3/LuaSnip/wiki/Nice-Configs#imitate-vscodes-behaviour-for-nested-placeholders doesn't work properly in current version of luasnip.

**Comment by L3MON4D3** [comment]
Oh right, I forgot changing that.
It's now necessary to [`fake_expand`](https://github.com/L3MON4D3/LuaSnip/blob/007a0af6d0fd412dfbb31953bb1b81eaf8fbd6fd/lua/luasnip/util/parser.lua#L167) the snippet beforehand, in the example the snippetNode is copied into a new snippet so the actual one isn't changed by `fake_expand`.
This was necessary with the introduction of `absolute_indexer`, since now the nodes inside the snippetNode may depend on nodes outside it. This means we'll have to construct the entire snippet to get the static text from one snippetNode inside it (suboptimal I know, but I can't think of a different solution)

**Comment by stasjok** [comment]
> Oh right, I forgot changing that. It's now necessary to [`fake_expand`](https://github.com/L3MON4D3/LuaSnip/blob/007a0af6d0fd412dfbb31953bb1b81eaf8fbd6fd/lua/luasnip/util/parser.lua#L167) the snippet beforehand, in the example the snippetNode is copied into a new snippet so the actual one isn't changed by `fake_expand`. This was necessary with the introduction of `absolute_indexer`, since now the nodes inside the snippetNode may depend on nodes outside it. This means we'll have to construct the entire snippet to get the static text from one snippetNode inside it (suboptimal I know, but I can't think of a different solution)

So, I have to create temporary full snippet, right? Because snippet_node itself won't work without `fake_expand` of parent snippet? I changed
```lua
local snip_text = snip:get_static_text()
```
to
```lua
local snippet = s("", { snip:copy() })
local snip_text = snippet:get_static_text()
```
and it's now working. It's not necessary to `fake_expand` myself, because `get_static_text` is already [doing](https://github.com/L3MON4D3/LuaSnip/blob/007a0af6d0fd412dfbb31953bb1b81eaf8fbd6fd/lua/luasnip/nodes/snippet.lua#L702-L705) it, right?

**Comment by L3MON4D3** [comment]
Right, that's correct👍
In the example I posted the snippet is only `fake_expand`ed manually because we need to pass `env` (important for eg `TM_SELECTED_TEXT`).

**Comment by stasjok** [comment]
Thank you!
