### ISSUE TITLE
Prevent overwriting registers(clipboard) when using InsertNode

### ISSUE THREAD

**Issue by yutkat** [L3MON4D3/LuaSnip#403]
I would like to disable overwriting the clipboard value with the default value when using InsertNode in select mode.
I know this problem will solve by `feedkeys("\<C-r>_")` at the correct timing.

## Reproduce steps

1. `:set clipboard=unnamedplus,unnamed`
2. Trigger snippet including InsertNode.
3. Paste from Clipboard or Primary Selection.
4. Then the clipboard value is overwritten.

https://user-images.githubusercontent.com/8683947/165282400-3c40b0d9-d2bb-4964-940a-c4a64e131b4d.mp4

## Related issue

https://github.com/vim/vim/pull/9531

Adding this autocmd to init.lua would fix it, but it would be nice If this problem can be fixed on the LuaSnip side.

```lua
vim.api.nvim_create_autocmd({ "ModeChanged" }, {
	group = "vimrc_autocmd",
	pattern = "*",
	callback = function()
		if vim.fn.mode() == "s" then
			local key = vim.api.nvim_replace_termcodes("<C-r>_", true, false, true)
			vim.api.nvim_feedkeys(key, "s", false)
		end
	end,
	once = false,
})
```

**Comment by L3MON4D3** [comment]
I see, thank you for lining that discussion, I wouldn't have had the slightest clue what you were talking about without it 😅
Seems easy enough to fix, I'll get to it soon-ish
