### ISSUE TITLE
Automatically expand snippets

### ISSUE THREAD

**Issue by beune** [L3MON4D3/LuaSnip#404]
I want to expand snippets automatically, without pressing expand key, on a per snippet basis. I know this has been requested before (#77), but I think the solution proposed there is ugly (e.g., `imap <silent> ( (<plug>luasnip-expand-or-jump`). This is because I don't want to have to create an extra mapping for every snippet I want to expand automatically.

Is there an extra option to add to specific snippets to make them expand automatically?

**Comment by leiserfg** [comment]
Autosnippets exists already, https://github.com/L3MON4D3/LuaSnip/blob/007a0af6d0fd412dfbb31953bb1b81eaf8fbd6fd/doc/luasnip.txt#L1525

**Comment by leiserfg** [comment]
Check in the doc and in the example file, maybe it needs more visibility.

**Comment by beune** [comment]
Will check this out, thanks!

**Comment by beune** [comment]
Is it also possible to set autosnippets from `json`-style snippets, such as `friendly-snippets`?

**Comment by beune** [comment]
I cannot find anything useful about `autotrigger` in the luasnip docs, do you just add the field with `true`?

![2022-04-26_23-00](https://user-images.githubusercontent.com/47817451/165391602-01ba50e3-4e0a-450a-a47b-96b368b39767.png)

**Comment by leiserfg** [comment]
Yes, that's should do the work.

**Comment by beune** [comment]
Hmm, does not seem to be working for me :sob:

I have `enable_autosnippets = true` in my LuaSnip config, do I need anything else?

**Comment by leiserfg** [comment]
Try to define normal (non vscode) autosnippets if that works vscode ones should work likewise.

**Comment by L3MON4D3** [comment]
> I cannot find anything useful about `autotrigger` in the luasnip docs, do you just add the field with `true`?
> 
> ![2022-04-26_23-00](https://user-images.githubusercontent.com/47817451/165391602-01ba50e3-4e0a-450a-a47b-96b368b39767.png)

I think we look in `snippet->luasnip->autotrigger`, so
```json
"display math" : {
	"prefix" : "dm",
	"luasnip" : {
		"autotrigger" : true
	}
	...
}
```
should do it
