### ISSUE TITLE
ext_opt Additional Table For Unvisited Nodes

### ISSUE THREAD

**Issue by p0da** [L3MON4D3/LuaSnip#410]
Would you consider adding adding a ext_opt table for nodes which are unvisited? There does not  seem to be a way to specify the application of a highlight group to exclusively unvisited nodes with the currently available tables: passive, active, and snippet_passive. Therefore it would be helpful if there was an additional table which applied attributes exclusively to nodes that have not yet been jumped to. Thanks!

**Comment by L3MON4D3** [comment]
Oh that's a nice idea, I'm definitely not opposed.
Should also be rather easy to implement :+1:

**Comment by L3MON4D3** [comment]
One problem: with `active`, `passive`, `snippet_passive` it's very clear when any of these highlights should be applied. Should `unvisited` only show while the snippet is active?
Eg. `snippet_passive` ->(snippet is jumped into) `unvisited` -> (snippet is exited again) `snippet_passive` or `unvisited`?
IMO it should be `snippet_passive`, but that isn't communicated directly by `unvisited`

**Comment by p0da** [comment]
I'd consider it most intuitive if unvisited was applied only when the snippet is active. But yeah the name "unvisited" doesn't really communicate that, maybe something like "active_unvisited"? Really anything you choose would be fine with me.

**Comment by L3MON4D3** [comment]
Okay, that's good, I wanted to make sure you didn't have some niche usecase that wouldn't play well with what I had in mind.

![ext_opts_hierarchy](https://user-images.githubusercontent.com/41961280/166138092-b9be3f22-eb4b-41fa-8361-2e6b75ade37f.svg)
I'm thinking of adding `visited` as well, then we could have the above inheritance for `ext_opts` and, during runtime, use either `visited` or `unvisited` for a given node (feels cleaner than `passive` and `unvisited`).

**Comment by p0da** [comment]
Looks good. Can't wait to use it.

**Comment by L3MON4D3** [comment]
Finally got to it, check #440 :)

**Comment by L3MON4D3** [comment]
Oh, it's merged now, closing this.

**Comment by p0da** [comment]
Looks good, thanks for your work.
