### ISSUE TITLE
docs: what does fmt stands for?

### ISSUE THREAD

**Issue by pedro757** [L3MON4D3/LuaSnip#412]
There is not documentation about this in `:h luasnip.txt`, what can I do with it?

```lua
local fmt = require("luasnip.extras.fmt").fmt
```

**Comment by p0da** [comment]
fmt is format, docs on it are [here](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua)

**Comment by L3MON4D3** [comment]
Yup, those should be added :sweat_smile:
