### ISSUE TITLE
Hot Reload not working in subfolders*

### ISSUE THREAD

**Issue by ziontee113** [L3MON4D3/LuaSnip#413]
Hi, Hot Reload currently works fine with:
- No subfolders
- Files in subfolders, with their names = subfolder name. (Example: subfolder "all" with "all.lua" file)

If in the "all" folder, I create another snippet file, called anything else than "all.lua":
- Hot Reload will not be available.
- Snippets will work after restarting Nvim.
- Snippets won't update after file change.
- If I edit the "all/all.lua" file, all the snippets in the other "all/*.lua" files will stop working.

I think this issue is not too complicated to fix :)
The point is if you have a lot of snippets / or multiple complicated snippets, one might want to separate them for easy management.
Thank you! 😄

**Comment by L3MON4D3** [comment]
Very easy indeed, we just incorrectly resolved the filetype.
Thanks for bringing it to my attention :+1:
