### ISSUE TITLE
Lua pattern match edge case

### ISSUE THREAD

**Issue by MetriC-DT** [L3MON4D3/LuaSnip#414]
The snippet in question should expand, but doesn't on inputs with parenthesis
```lua
local function captured(args, snip)
  return snip.captures[1]
end

s({trig='([^%s])sr', name='squared', regTrig=true},
  fmt([[{}^2]], {f(captured, {})}))
```
Specifically, I was trying to get it to expand on:
```tex
(a+b+c)sr --> (a+b+c)^2 (doesn't work)
a+b+csr --> a+b+c^2 (works)
```

**Comment by leiserfg** [comment]
You need to scape the `()`, in lua it should be something as `%(([^%s])%)sr`,   have a look at  https://gitspartv.github.io/lua-patterns/?pattern=%25((%5B%5E%25s%5D)%25)sr

**Comment by MetriC-DT** [comment]
Shouldn't the `([^%s])` already capture the closing parenthesis `)` since it is not considered a whitespace character? I've tested this out in lua and it seems to match this properly.

**Comment by L3MON4D3** [comment]
`[^%s]` matches only a single non-whitespace character, for me `([^%s]+)sr` works just fine.
```vim
:lua print(string.match("(a+b+c)sr", "([^%s]+)sr"))
```
