### ISSUE TITLE
`PackerCompile` causing multiple `:LuaSnipEdit` paths

### ISSUE THREAD

**Issue by axieax** [L3MON4D3/LuaSnip#415]
Defining `LuaSnipEdit` as provided by the docs and selecting the desired filetype should usually take me to the file defining my snippets for that filetype. However, it seems like running `PackerCompile` (packer.nvim) seems to reload this each time, causing multiple of the same paths to appear. Perhaps it's possible to make this selection unique, or prevent multiple registrations of the same thing.

![image](https://user-images.githubusercontent.com/62098008/166236858-634ca886-aead-4177-b773-64fa3344dc79.png)

**Comment by L3MON4D3** [comment]
Could you show the part of your config where you `load()` the lua-snippets? I also use packer and don't have this problem (at least not when just calling `:PackerCompile`)

**Comment by L3MON4D3** [comment]
Does it make a difference if `load()` is only called in the config-callback? I'm a bit confused why I don't get the duplicated paths.

**Comment by leiserfg** [comment]
Not sure about what's happening cause as far  as I remember async loaders dedup the list of  paths (not sure if the lua_snippet format loader is doing it too) in any case I avoid  doing something as   `config = require("axie.lsp.snippets").setup,`  and prefer to do   `config = "require("axie.lsp.snippets").setup()"` instead, so the import (or any other code) only happens after loading the plugin.

**Comment by L3MON4D3** [comment]
> not sure if the lua_snippet format loader is doing it too

No :sweat_smile:
Well, the async-load-list is deduped, but this is [a different one, specifically for files-by-filetype](https://github.com/L3MON4D3/LuaSnip/blob/a39063d7aad4edec5e3515493cf20d0d67f9af9e/lua/luasnip/loaders/from_lua.lua#L116-L118) where paths are just blindly appended (not sure if it's worth changing, loading the same collection twice should be avoided anyway and fixing the root-cause of that seems more worthwhile).

Does packer have different behaviour for string and function?? I would've expected the above two examples to both "run" the config after loading the plugin, but if that isn't the case it's definitely worth being aware of :+1:

**Comment by axieax** [comment]
`config = require("axie.lsp.snippets").setup` and `config = 'require("axie.lsp.snippets").setup()'` seem to both cause the same issue. I'm not sure if it's a Packer issue though, since any callback config function is expected to be run on start and `PackerCompile` events, at least for my configuration. Preventing duplicate paths when this happens doesn't seem like it'll cause much downsides tho, but that's just my opinion :D

**Comment by leiserfg** [comment]
> Does packer have different behaviour for string and function?? I would've expected the above two examples to both "run" the config after loading the plugin, but if that isn't the case it's definitely worth being aware of 👍

Packer stringifies the config, if the config is a closure it can get damaged in the process, so it is always safer to pass a string.

**Comment by L3MON4D3** [comment]
> I'm not sure if it's a Packer issue though, since any callback config function is expected to be run on start and PackerCompile events, at least for my configuration.

I'm just a bit confused, I also load my luasnip-config in the config-callback and it doesn't happen for me..
Is `:PackerCompile` all you do to trigger the duplication?

> Preventing duplicate paths when this happens doesn't seem like it'll cause much downsides tho

Yess of course, but there are other problems that can arise when calling `load` twice, for example duplicate snippets when you start using one of the other loaders.
I'll see what I can do though :)

> Packer stringifies the config, if the config is a closure it can get damaged in the process, so it is always safer to pass a string.

Okay that makes sense, ty 👍

**Comment by axieax** [comment]
> I'm just a bit confused, I also load my luasnip-config in the config-callback and it doesn't happen for me..
Is :PackerCompile all you do to trigger the duplication?

Yep! I did something similar to your setup with the config field defining an anonymous function requiring `axie.lsp.snippets` which has been redefined as just a lua file (not returning anything). This doesn't cause the issue. However, I guess callback functions work a bit differently. Not sure why this behaviour is different, but the config does not get rerun for `PackerCompile`. For the sake of consistency for different configs, perhaps it might be nice to consider the duplicate stuff.

Regarding the duplicate snippets, I had that issue before when defining custom snippets in my setup function with `ls.add_snippets`, but separating my snippets into the different filetypes seemed to fix that.

**Comment by L3MON4D3** [comment]
> Regarding the duplicate snippets, I had that issue before when defining custom snippets in my setup function with `ls.add_snippets`

Oh I guess you didn't use `key`, it's an optional argument you can pass to `add_snippets`. If it's defined, snippets previously added with that same key are removed when the new ones are loaded.

> For the sake of consistency for different configs, perhaps it might be nice to consider the duplicate stuff still :))

True, just be aware that there might be more problems down that road. But I'll add it, there's no reason not to, really :)
Oh alternatively, we do have `ls.cleanup()` which doesn't work 100% right now, but if that was fixed you could just call it before the rest of your config (if nothing is loaded it's basically a nop) to re-setup cleanly.
Maybe that's really what we should fix :D

**Comment by axieax** [comment]
> Oh I guess you didn't use key

Ahh no wonder!

> `ls.cleanup()`

Oo that doesn't sound like too bad of an idea. Idm adding an extra line to my config to solve future related problems as well :D

**Comment by L3MON4D3** [comment]
@axieax Could you switch to `fix_cleanup`(#418) and see whether calling `ls.cleanup()` at the beginning of your config fixes the duplicate paths?

**Comment by axieax** [comment]
That resolves the problem now. Thank you so much!

**Comment by L3MON4D3** [comment]
Nice, I'll do some more tests and merge soon :)

**Comment by L3MON4D3** [comment]
Merged. (cc00863)
