### ISSUE TITLE
The snippet cmp is falsely triggered by a symbol

### ISSUE THREAD

**Issue by winkee01** [L3MON4D3/LuaSnip#416]
Usually, snippet cmp was triggered by several prefix words, but If a snippet contains a symbol (eg. `,` or `;` etc), the snippet cmp was triggered as long as I type the symbol, for example

<img width="292" alt="CleanShot 2022-05-02 at 21 59 05@2x" src="https://user-images.githubusercontent.com/49930785/166246896-56e0cc04-7b82-436f-b9d2-bbd4a9efd250.png">

the symbol is in the middle of the snippet definition, but it was triggered immediately after I type it, this is very annoying.

The expected behavior should be that only when I typed the whole snippet keyword should it be triggered.

the snippet definition is

```
snippet pri, "print! with format param"
	print!("${1}{${2}}", ${3});

snippet pln, "println! with format param"
	println!("${1}{${2}}", ${3});
```

**Comment by L3MON4D3** [comment]
Phuh, there's not much we can do about that here, if it only started happening recently I'd recommend looking into recent changes in cmp.
I think cmp also has some way to control the matching, maybe you can find some settings to tweak there.

**Comment by winkee01** [comment]
Sure, I will close the issue, it's cmp engine do the fuzzying search, their problem.
