### ISSUE TITLE
Global / all filetype is not supported for VSCode snippets

### ISSUE THREAD

**Issue by smjonas** [L3MON4D3/LuaSnip#419]
I just noticed this while working on my plugin: friendly-snippets contains a `global.json` file for snippets that should be available for all filetypes (UltiSnips has `all.snippets`). However, LuaSnip does not seem to handle that (the snippets from that file are not available). I tried renaming it to `all.json` (in `package.json` as well) but it didn't work. There is this section in the docs:
```
Snippets that should be accessible globally (in all filetypes) have to be added to the special filetype `all`.
```
So is this only supported for Lua snippets currently?

**Comment by L3MON4D3** [comment]
Could you show the modified `package.json`? This:
```json
"snippets": [
  {
    "language": [
      "all"
    ],
    "path": "anyfile.json"
  },
```
should work.
Alternatively you could instruct luasnip to draw global snippets from filetypes other than `all` (in addition to `all`):
```lua
ls.filetype_extend("all", {"global"})
```

**Comment by smjonas** [comment]
Yes thank you, adding `all` to the languages list fixed it - I'll create a PR on the friendly-snippets repo :)
