### ISSUE TITLE
Update docs for vs code snippets

### ISSUE THREAD

**Issue by ritwikvd** [L3MON4D3/LuaSnip#421]
Hello and thanks to all contributors for their work on this!

I would just like to point out that the docs seem out of date/ incomplete when it comes to the vs code snippets. I was under the impression from the text on the main readme that all that was required was calling load/lazy_load.

After much trial and error, scouring thru the docs and then ultimately the closed issues, I managed to get it working with the below config, and I almost gave up several times along the way due to frustration.

```
require("luasnip").filetype_extend("javascript", {"html"})
require("luasnip").filetype_extend("typescript", {"html","javascript"})
require("luasnip").filetype_extend("javascriptreact", {"html","javascript"})
require("luasnip").filetype_extend("typescriptreact", {"html","javascript"})

require("luasnip.loaders.from_vscode").load()
```

It might have been difficult for me because im just starting out with vim/nvim.

If the docs could be updated to reflect the way it's required to be done, it'd be a big help to fellow newcomers like me.

Thanks again for everything :)

**Comment by L3MON4D3** [comment]
Ohhh yes I get your sentiment..
Although this depends on the setup the user has, we can probably add a Troubleshooting-section that mentions these issues
