### ISSUE TITLE
Problem with Github Copilot

### ISSUE THREAD

**Issue by ruanyouxing** [L3MON4D3/LuaSnip#422]
I want to use both LuaSnip and Copilot suggestions at the same time, but the snippets didn't show up when i enable Copilot, until I disable it again, snippets came back. And yup, i changed the key bindings to ensure that they aren't using a same key

Any ideas to solve this?

**Comment by L3MON4D3** [comment]
Do you use snippets and copilot via `nvim-cmp`? If so, I don't think luasnip can do anything about it..
AFAIK it's possible to change source-ordering (and maybe even completely disable some source if another has items), but I don't really know how that works.
You might have more success asking in eg. the neovim matrix room or in cmps issues/discussions.

**Comment by ruanyouxing** [comment]
thanks
