### ISSUE TITLE
Autotrigger full example

### ISSUE THREAD

**Issue by atticus-sullivan** [L3MON4D3/LuaSnip#423]
Hi, sorry for opening an issue for this, but I can't find a complete example how to set up an autotrigger snippet. Everything on autotrigger in the manual is about the json parsing (I'm adding snippets in a lua style).

Maybe someone could provide a small (but complete) example (which should be added somewhere in the Readme/Doc in my opinion).

**Comment by L3MON4D3** [comment]
Yeah, comprehensive examples are sorely lacking :sweat_smile:
All you have to do is call
```lua
add_snippets(filetype, snippets, {type = "autosnippets"})
```
There's a short mention of that [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#api-reference), but it should probably be included in the first section of the doc (Basics).

There's also some stuff in the [Examples](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua#L508-L516)

**Comment by atticus-sullivan** [comment]
Hm is it not working or have I misunderstood autotrigger?

My config + snippets:
```lua
ls.config.set_config {
    history = true,
    enable_autosnippet=true,
}
-- from example page
-- set type to "autosnippets" for adding autotriggered snippets.
ls.add_snippets("all", {
    s("autotrigger", {
        t("autosnippet"),
    }),
}, {
    type = "autosnippets",
    key = "all_auto",
})

-- own test
ls.add_snippets("all", {
    s("testing", fmt([[hello world]], {}), {type="autosnippets"})
})

```
Produces:
![Peek 2022-05-08 21-38](https://user-images.githubusercontent.com/60581958/167312868-afc67db0-779c-4b1d-9ba7-cd8cf8fdc817.gif)
Snippet from the example is not working (not sure if `type="autosnippets"` is right as an argument to `add_snippets`), and my testing snippet (`type="autosnippets"` as an argument to `s()`) should autoexpand (as far as I understand it), but still needs `tab` to get expanded.

**Comment by L3MON4D3** [comment]
Ahh, just a typo: `enable_autosnippet`->`enable_autosnippets`

**Comment by atticus-sullivan** [comment]
Hm, behavior doesn't change (still no completion for `autotrigger` and `tab` is still needed for `testing`). Not quite sure what I'm doing wrong.  Does the example run on your side? (if no the error should be somewhere in my config I guess)

**Comment by L3MON4D3** [comment]
Just so we're on the same page, I just tested this, and it works:
```lua
ls.config.set_config {
    history = true,
    enable_autosnippets=true,
}

-- from example page
-- set type to "autosnippets" for adding autotriggered snippets.
ls.add_snippets("all", {
    ls.s("autotrigger", {
        ls.t("autosnippet"),
    }),
}, {
    type = "autosnippets",
    key = "all_auto",
})

```

**Comment by atticus-sullivan** [comment]
> Just so we're on the same page
Could you maybe make a video/gif of the behavior you get with this? (maybe I just understand autotrigger false (or otherwise I'll need to check config and start removing plugins to get a minimal config))

**Comment by L3MON4D3** [comment]
Yeah, ofc:

https://user-images.githubusercontent.com/41961280/167564972-92f9d9d4-a191-4992-bfc3-40b71e048667.mp4

You can make sure the option `enable_autosnippets=true` works by checking the output of `au InsertCharPre`. It should show one autocommand from group "luasnip".

**Comment by L3MON4D3** [comment]
Sounds good :+1:
You can also check the snippet is indeed registered via `:lua print(#ls.get_snippets("all", {type = "autosnippets"}))` (check the doc if it doesn't work exactly, but I think this should be it. Also make sure the queried filetype matches the one you're adding snippets to)

**Comment by atticus-sullivan** [comment]
> Also make sure the queried filetype matches the one you're adding snippets to)
Already used `all` for that reason.

Well just noticed it works now. I think I only tested my `testing` snippet where the `autotrigger` type is set at the wrong position after correcting `enable_autosnippet` to `enable_autosnippets` (or I had a simple typo when testing the trigger) :see_no_evil:

Thanks for your help (sorry for the mistake creating confusion in the end) :+1:

**Comment by L3MON4D3** [comment]
Aaahhh alright xD
You're welcome :D

**Comment by atticus-sullivan** [comment]
Hi, one small follow up: Any possibility to set the `autotrigger` optoion when loading snippets with the lua-loader (specified for the specific snippets)? (shouldn't become a full discussion in this dead/closed issue, if necessary, I'll make a new one)

**Comment by L3MON4D3** [comment]
Take a look [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lua), you'll need to return autosnippets in a second table.
There's an issue for adding an `autotrigger` to the snippet-options, #482, but it'll be a while till I get to that

**Comment by atticus-sullivan** [comment]
Ah right thanks :+1:
