### ISSUE TITLE
Permission to use modified version of `Path.scandir`

### ISSUE THREAD

**Issue by smjonas** [L3MON4D3/LuaSnip#424]
I would like to use a modified version of the `scandir` function defined here:
 https://github.com/L3MON4D3/LuaSnip/blob/cc0086390c6cd2eaebae1834b115c891649ec95f/lua/luasnip/util/path.lua#L77 

Is it enough if I include you in the credits of my plugin? Just wanted to let you know before blindly copying your code ^^

With the plugin almost released, LuaSnip now indirectly supports loading UltiSnips snippets :D

**Comment by L3MON4D3** [comment]
@uga-rosa authored that IIRC, if it's alright with them feel free to :D

> With the plugin almost released, LuaSnip now indirectly supports loading UltiSnips snippets :D

Ouh nice! `snippet-converter`, or is that a different one?

**Comment by smjonas** [comment]
Perfect :D yes, exactly that's the one I'll be releasing soon :) By the way, are there any other (possibly undocumented) keys within VSCode snippets that LuaSnip supports (apart from `autotrigger` which I saw in the docs)? I want to retain as much information as possible while converting a snippet ^^

**Comment by L3MON4D3** [comment]
Not yet, but I'll add another, `priority` (the same `priority` that can be passed to `s`), soon (follow #409 if you want to be in the know/play with it, but there'll be lots of unrelated stuff added too)

**Comment by uga-rosa** [comment]
You can use it.
I think it's an awesome plugin!
