### ISSUE TITLE
How to set nvim_buf_set_extmark opts?

### ISSUE THREAD

**Issue by crusj** [L3MON4D3/LuaSnip#427]
Now can only set virt_text, but it's guibg is strange when cursorline, how can solve this? 
<img width="744" alt="图片" src="https://user-images.githubusercontent.com/20185895/167895299-7fa63361-0300-4900-8a45-3cff275260fc.png">

**Comment by L3MON4D3** [comment]
Check `:h nvim_buf_set_extmark`, anything in `opts` can be passed here.
Could you show what you have right now?

**Comment by crusj** [comment]
> Check `:h nvim_buf_set_extmark`, anything in `opts` can be passed here. Could you show what you have right now?

Thanks, I added hl_model = "combine", it works
