### ISSUE TITLE
using vscode loader makes package.json mandatory or the extension will crash

### ISSUE THREAD

**Issue by danielo515** [L3MON4D3/LuaSnip#428]
Hello.
I use LunarVim and they recently added the option to load snippets form snipmate and vscode. I only use snipmate in my local configuration, but friendlysnippets is installed, so I guess that executing both loaders is mandatory.
However, if I create some snippets in a runtime path called snippets to provide snipmate snippets, the extension expects a package.json file and if it does not find it ti crashes.
I think some checks should be performed before blindly trying to load a file that may not exist.

**Comment by L3MON4D3** [comment]
Oh this isn't expected to happen, I also have snipmate and vscode-snippets for testing, and haven't encountered crashes because of that before.
Could you show more of your setup?

**Comment by L3MON4D3** [comment]
Is it alright if this is closed? IMO it's okay if luasnip just throws an error if an incorrect path is passed.

**Comment by danielo515** [comment]
the thing is that the path to the folder it's correct, it's the assumption that there is a json file in there what it is incorrect and causing the error. What about checking for the existence first and just ignore it if not present? Throwing an error will stop the process of loading other extensions and will leave neovim in an inconsistent state

**Comment by L3MON4D3** [comment]
Wasn't the problem that the wrong directory is passed to the vscode-loader?
Oh, maybe you're not aware: we cannot just load the `.json`-files, we need the `package.json`, it's part of the vscode-package "spec" (see friendly-snippets for an example).
So passing a directory that (potentially) doesn't contain a `package.json` to the vscode-loader is incorrect.

The snipmate-loader, on the other hand, takes a plain `snippets`-directory which contains `.snippets`-files.

Just ignoring the directory would be counterproductive IMO (the reason for some snippets not loading would not be communicated at all)

**Comment by danielo515** [comment]
> Just ignoring the directory would be counterproductive IMO (the reason for some snippets not loading would not be communicated at all)

you can always issue a warning. Still think that making it crash is the worst option because it can render the editor unusable until you fix the problem or deactivate the extension, and having other extensions not working because this one crashed can be even more confusing, IMO

**Comment by L3MON4D3** [comment]
Oh, I tried it earlier and loading without `package.json` did not cause a crash, only an error.
If it actually crashes neovim entirely that's a different matter, we can add a check to prevent that

**Comment by L3MON4D3** [comment]
Is there any error-message upon crashing?
I'm not quite sure where the crash comes from, normally it should be caught by [`assert(uv.fs_open(...))`](https://github.com/L3MON4D3/LuaSnip/blob/b33aebaa895d2a7f3c54ccba6d30eef29a20d906/lua/luasnip/util/path.lua#L45), which we use exactly like recommended in `luv-documentation`(https://github.com/luvit/luv/blob/master/docs.md#file-system-operations).

**Comment by danielo515** [comment]
Yes, I get an error message that says it can not open a file that does not exists, then some of my settings are not loaded, which makes me think either packer crashes or something else crashes. I'll try to reproduce it later and put the exact error messages

**Comment by L3MON4D3** [comment]
AFAICT it's fixed in lunarvim now, I'll close this too
