### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by bryant-the-coder** [L3MON4D3/LuaSnip#431]
![image](https://user-images.githubusercontent.com/92417638/168504445-eeff9475-2a73-412b-82c9-d647fcbbbb51.png)

**Comment by L3MON4D3** [comment]
Ouh, could you run `git status` in the plugin-directory?

**Comment by bryant-the-coder** [comment]
after removing luaasnip and installing again. it worked. ig its packer issue :kek:

**Comment by L3MON4D3** [comment]
Ahh, not really, stuff like that mostly happens if there are unrelated histories when pulling.
I don't recall rebasing master, but I did some stuff pretty late yesterday, so I'm not so sure😬😬😬

**Comment by bryant-the-coder** [comment]
😂🤣 no worries. its working now
