### ISSUE TITLE
from_vscode: invalid value (nil) at index 1 in table for 'concat'

### ISSUE THREAD

**Issue by Diaoul** [L3MON4D3/LuaSnip#44]
Updating to latest version I now have this error:
![image](https://user-images.githubusercontent.com/319220/123482368-630e6380-d605-11eb-8f06-732fb4d2adf4.png)

Here is my simple config (based off stripped down version of the example) that used to work a few commits ago:
```lua
    local luasnip = require('luasnip')

    luasnip.config.set_config({
        history = true,
        updateevents = 'TextChanged,TextChangedI',
    })

    require('luasnip/loaders/from_vscode').load()
```

I've tried playing with opts and add an include but I think the issue is with handling the path. Sadly I can't help much more than this bug report as my lua and neovim is still pretty limited.

**Comment by L3MON4D3** [comment]
Oh no, @leiserfg could you also take a look?

**Comment by L3MON4D3** [comment]
Thanks for reporting this so quickly

**Comment by leiserfg** [comment]
I'm on it.

**Comment by L3MON4D3** [comment]
So far I've got this, to actually get the split paths.
```lua
-- list of paths to crawl for loading (could be a table or a comma-separated-list)
-- opts.paths = (
-- 	type(opts.paths) == "table" and values(opts.paths)
-- 	or (opts.paths or vim.o.runtimepath):gmatch("([^,]+)")
-- )
if type(opts.paths) == "table" then
	opts.paths = values(opts.paths)
else
	local split_paths = {}
	for path in (opts.paths or vim.o.runtimepath):gmatch("([^,]+)") do
		table.insert(split_paths, path)
	end
	opts.paths = split_paths
end
```

**Comment by L3MON4D3** [comment]
Though we could also just use `vim.split` for that :sweat_smile:

**Comment by leiserfg** [comment]
True, will you do it?

**Comment by L3MON4D3** [comment]
That's only part of the issue, after that I still get a `nil` from somewhere.

**Comment by leiserfg** [comment]
Then I will do it.

**Comment by L3MON4D3** [comment]
TY!

**Comment by leiserfg** [comment]
I see, the function to optain the absoluted paths in nvim gives nil if the path does not exists

**Comment by Diaoul** [comment]
Thanks for delivering the fix so quickly! :tada:
Feel free to close this issue.
