### ISSUE TITLE
Unable to insert to TAB in snippet region

### ISSUE THREAD

**Issue by mortezadadgar** [L3MON4D3/LuaSnip#442]
Hey,
I use TAB to expand snippets, is it possible to insert a "real" TAB in snippets region if there's not another region to jump in?
like in this snippet I can't insert a \t because I'm in the last region
![image](https://user-images.githubusercontent.com/27911493/170285478-63a05727-3ce3-4925-8e07-0fc0cdd8c448.png)

**Comment by L3MON4D3** [comment]
You can check if it's currently possible to jump forward via `ls.jumpable(1)` and use an `expr`-mapping to insert a Tab in this case:
```vim
imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>'
```
(that's from the README, you could adapt it)

**Comment by L3MON4D3** [comment]
`expand_or_locally_jumpable` is useful if tab is overloaded for jump+expand, although you might want to omit the locally (explanation in DOC.md, bottom).
If you're using the cmp-mapping, I think you can just return `"<Tab>"`, I think that's also in the Readme (although collapsed by default).

**Comment by L3MON4D3** [comment]
Right, there were some changes, I'll look into that
