### ISSUE TITLE
If currently in snippet, send a character to buffer

### ISSUE THREAD

**Issue by ziombo** [L3MON4D3/LuaSnip#450]
I had trouble coming up with a title, so I'm assuming it's not very descriptive. 

I have a problem with [one plugin](https://github.com/phaazon/hop.nvim) which is interfering with LuaSnip snippets. It's a motion plugin that allows me to jump to words/lines etc. with generated shortcuts. The problem is that when I enter a plugin and want to start naming one of the elements, the plugin runs for if one of it's keymaps is pressed. 

I came up with a workaround, which check's if I'm currently in snippet and if not it runs the command, however if I'm in snippet I don't know how to forward the pressed key as normal user input so I can start editing the name of current node.

```
 if require('luasnip').in_snippet() then        
  -- send a character to buffer at cursor as if mapping didn't exist
 else                                           
  vim.api.nvim_cmd({ cmd = command }, {})      
 end   
```         

Scenario: 
'f' is a keymap to jump to word

I want to rename _index_ to something starting with 'f', but after pressing 'f' nothing changes as the motion plugin is executed (and then cancelled by LuaSnip I assume). Using other characters works fine.

                                
![image](https://user-images.githubusercontent.com/15613606/171689286-672ec8ec-6446-4157-9295-7587a4557f46.png)

**Comment by L3MON4D3** [comment]
Mhmm do you need the plugin's keymaps in SELECT-mode?
If not, the easiest fix might be to set them exclusively for normal mode (`:h map-modes`)

**Comment by ziombo** [comment]
From what I'm reading mapping for visual (which I also need) also maps for select mode. I currently have my mapping set like this: 

`vim.api.nvim_set_keymap('v', 'f', '<cmd>HopWord<cr>', {})  `

which still is executed when I'm in a snippet

**Comment by ziombo** [comment]
Okay, I managed to make it work, by setting these keymaps for select mode:

```
vim.api.nvim_set_keymap('s', 'f', 'f', {})
vim.api.nvim_set_keymap('s', 'F', 'F', {})
vim.api.nvim_set_keymap('s', 't', 't', {})
vim.api.nvim_set_keymap('s', 'T', 'T', {})
```

Should I add such settings for other select modes as well? If I'm not mistaken there are three:

```
s        Select by character
S        Select by line
CTRL-S   Select blockwise
```

**Comment by L3MON4D3** [comment]
Nice, that also works :+1:
I think mappings via `s` affect all select-modes, you should be set with clearing those (but luasnip only uses charwise, so you're good either way :D).

One more alternative: you can (I think, and according to `:h map-table`) use `x` for mapping select-only, that might be cleaner :)
