### ISSUE TITLE
Dynamic lambda caching?

### ISSUE THREAD

**Issue by ranebrown** [L3MON4D3/LuaSnip#454]
Does the dynamic lambda do some sort of caching? This results in the same "random" string every time. Works as a function node but then isn't selected or over writable.

```lua
local charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
math.randomseed(os.clock())
local function randomString(length)
    local ret = {}
    local r
    for _ = 1, length do
        r = math.random(1, #charset)
        table.insert(ret, charset:sub(r, r))
    end
    return table.concat(ret)
end

dl(1, l.TM_FILENAME:upper():gsub("%.", "_") .. "_" .. randomString(6), {}),
```

**Comment by leiserfg** [comment]
The variables in the snippet environment (like `TM_IFILENAME`) keep the value for the snippet expansion, so maybe you could use `l.RANDOM_HEX`

**Comment by ranebrown** [comment]
`l.RANDOM_HEX` does work. Is there a way to reset the variables and allow a function call to work each time?

**Comment by ranebrown** [comment]
This also works but isn't as clean.
```lua
d(1, function(args, snip)
    return sn(
        nil,
        {
            i(
                1,
                snip.env.TM_FILENAME:upper():gsub("%.", "_")
                    .. "_"
                    .. randomString(6)
            ),
        }
    )
end, {}),

```

**Comment by L3MON4D3** [comment]
> `l.RANDOM_HEX` does work. Is there a way to reset the variables and allow a function call to work each time?

Although this is a bit convoluted, you could override the `__concat`-metamethod on some table and pass that:
```lua
local charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
math.randomseed(os.clock())
local function randomString(length)
    local ret = {}
    local r
    for _ = 1, length do
        r = math.random(1, #charset)
        table.insert(ret, charset:sub(r, r))
    end
    return table.concat(ret)
end

local o = setmetatable({}, {
	__concat = function(x)
		return x .. randomString(6)
	end
})

ls.setup_snip_env()

ls.snip_expand(s("", {
	dl(2, l._1 .. o, 1), i(1), t"texttext"
}))
```

I think adding functions to (dynamic)lambda is a bit unnecessary, at that point one might just as well use regular dynamic/functionNode.
