### ISSUE TITLE
`:LuaSnipListAvailable` returning empty tables even if snippets defined

### ISSUE THREAD

**Issue by hood** [L3MON4D3/LuaSnip#459]
Hi, I'm trying to setup luasnip for the first time here, following is my barebones setup from my `init.vim` config file (I've kept it minimal to minimize human errors for now):
```lua
  local LuaSnip = require'luasnip'

  LuaSnip.config.set_config{
    history = true,
    updateevents = "TextChanged,TextChangedI",
    enable_autosnippets = true,
  }

  vim.keymap.set({ "i", "s" }, "<c-m>", function() 
    if LuaSnip.expand_or_jumpable() then
      LuaSnip.expand_or_jump()
    end
  end, { silent = true })

  LuaSnip.snippets = {
    all = {
      LuaSnip.parser.parse_snippet("__test", "Test OK!"),
    }
  }
```

For some reason, though, I can't seem to get my snippets working at all, and running `:LuaSnipListAvailable` shows that I have no registered snippets for whatever reason. 

-- 
UPDATE:
I've found out that defining my own snippets like this works:
```lua
  LuaSnip.add_snippets("all",
    {
      LuaSnip.parser.parse_snippet("__test", "Test OK!"),
      }
  )
```
, while setting them like this doesn't:
```lua
  LuaSnip.snippets = {
    all = {
      LuaSnip.parser.parse_snippet("__test", "Test OK!"),
    }
  }
```

**Comment by L3MON4D3** [comment]
Yup, the latter was deprecated+removed some time ago, but there are still lots of resources that show the old way because it was changed a bit too late😅
