### ISSUE TITLE
Crash with on_the_fly parser if after `$` character is not a word character

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#461]
If register contains a string where after `$` character is not a word character, then neovim uses 100% CPU and eventually OOM-killed.

**Comment by L3MON4D3** [comment]
Ouh no :|
I can reproduce, #462 fixes the problem for me, can you confirm?

**Comment by stasjok** [comment]
Yes, it fixes it. Also with the patch we can use empty placeholders without preselected text.

**Comment by leiserfg** [comment]
Sorry for the bug @stasjok  I never thought about that use-case if the fix works,  it makes sense to have like this, let it be @L3MON4D3

**Comment by L3MON4D3** [comment]
It's been'd :+1:
