### ISSUE TITLE
snipmate snippets: My ${TM_FILENAME} does not expand anymore for snipmate snippets

### ISSUE THREAD

**Issue by voyeg3r** [L3MON4D3/LuaSnip#468]
I use luasnip and nvim-cmp + friendly-snippets and I have the following snippet:

```
snippet lc "Insert last change"
	-- Filename: ${TM_FILENAME}
	-- Last Change: ${CURRENT_DAY_NAME_SHORT}, ${CURRENT_DATE} ${CURRENT_MONTH_NAME_SHORT} ${CURRENT_YEAR} - ${CURRENT_HOUR}:${CURRENT_MINUTE}
```

Those environment variables are not been parsed into my snippet, until some days ago they where. How can I track or debug to figure out what I am doing wrong? I have used this snippet a bunch of times and it has expanded properly.

As I am a lua beginner I keep trying, but I have used the silversearches over the LuaSnip folder this way:

```
ag 'TM_FILENAME'
```

And I received

```
lua/luasnip/util/environ.lua
46:function lazy_vars.TM_FILENAME()
50:function lazy_vars.TM_FILENAME_BASE()
```

The definition of TM_FILENAME is this:
```lua
-- Inherited from TextMate
function lazy_vars.TM_FILENAME()
	return vim.fn.expand("%:t")
end
```

Now I will start reading to, possible, figure it out. 
If someone could help me in this task I would appreciate your effort!

By the way I already have added the path on my cmp.lua
```
require("luasnip/loaders/from_vscode").lazy_load({ paths = {"~/.config/nvim/luasnip_snippets"}})
require("luasnip/loaders/from_snipmate").lazy_load({ paths = {"~/.config/nvim/snippets"}})
```

I would like to know how to debug this. Thanks in advance!

**Comment by voyeg3r** [comment]
It seems like the lsp server was messing things up, because now It is working again!

**Comment by L3MON4D3** [comment]
Ah, right, that bug was fixed a few hours ago, I accidentially introduced it in #464 :|
