### ISSUE TITLE
How to include environment variable in a snippet definition

### ISSUE THREAD

**Issue by jimcornmell** [L3MON4D3/LuaSnip#476]
### Discussed in https://github.com/L3MON4D3/LuaSnip/discussions/475

<div type='discussions-op-text'>

<sup>Originally posted by **jimcornmell** July  5, 2022</sup>
Allow the ability to include any environment variable in a snippet definition json file eg `$HOME`:

For example:
```json
{
  "A Description": {
    "prefix": "home",
    "body": [
         "$HOME",
    ],
....
}
```
</div>

**Comment by leiserfg** [comment]
Will it make sense to use a prefix for that so we avoid collisions with the built-in variables? I'm thinking of something like $ENV_HOME.

**Comment by L3MON4D3** [comment]
Oh yes, `ENV_SOMEVAR` seems alright.
Also not without precedent, `TM_SOMETHING`.

**Comment by leiserfg** [comment]
Yes, I think the same way, giving that they are not lsp-standard it could be less confusing just to inject them in the setup and maybe resolve unknown environment variables (those not defined by the user or default ones) to `""` (not sure what is vscode doing in that case).

**Comment by leiserfg** [comment]
like 
```lua
ls.config.set_config{
...
extra_environ={
    HOME = os.getenv'HOME',
    MY_RANDOM = function(){return math.random();}  ## lazy env that is executed once per snippet
}
}
```

**Comment by L3MON4D3** [comment]
What do you think of
```lua
ls.add_env_resolver(fn(string) -> (table of string|string))
```
we could maintain a list of those `fn`s, call all in turn on `Environ.__index`, accept on non-nil return.

**Comment by L3MON4D3** [comment]
> like
> 
> ```lua
> ls.config.set_config{
> ...
>    extra_environ={
>        HOME = os.getenv'HOME',
>        MY_RANDOM = function(){return math.random();}  -- lazy env that is executed once per snippet
>    }
> }
> ```

`+` very easy to use+readable, metatable should be no problem as well, so that's nice
`-` a plugin that provides snippets to luasnip might have their own env-variables, adding those in setup wouldn't be as nice I think (could be ugly, especially if multiple do so)

**Comment by leiserfg** [comment]
> > like
> > ```lua
> > ls.config.set_config{
> > ...
> >    extra_environ={
> >        HOME = os.getenv'HOME',
> >        MY_RANDOM = function(){return math.random();}  -- lazy env that is executed once per snippet
> >    }
> > }
> > ```
> 
> `+` very easy to use+readable, metatable should be no problem as well, so that's nice `-` a plugin that provides snippets to luasnip might have their own env-variables, adding those in setup wouldn't be as nice I think (could be ugly, especially if multiple do so)

I was thinking about the same :smile:, although given that each snippet has his own Environ instance, could not we add an `extra_envirom` there too?

**Comment by leiserfg** [comment]
So authors of snippets sets don't pollute the global Environ :thinking:

**Comment by L3MON4D3** [comment]
> I was thinking about the same :smile:

:D

`extra_environ` should work for lua-snippets, but vscode/snipmate ones would miss out then.
(+some stuff really makes more sense to define on a global level, like `ENV_SOMEVAR`)

>So authors of snippets sets don't pollute the global Environ ￼

Hmm yeah, that's a point.. it might be enough to put some big warning to use "namespaces" (I agree though, a safe mechanism would be better).
(snippet namespaces? give additional properties based on namespace? not sure if there's anything beside this that could be used for)

**Comment by leiserfg** [comment]
wtyt about this one?
```lua
-- No namespace, for regular users
 
ls.extend_env {
       HOME = os.getenv'HOME',
       RANDOM = function(){return math.random();}  -- lazy env that is executed once per snippet
}


-- With namespace for snippets-sets devs 
-- has to be used as $MY_HOME 

ls.extend_env("MY", {
       HOME = os.getenv'HOME',
       RANDOM = function(){return math.random();}  -- lazy env that is executed once per snippet
})
-- Maybe?
ls.remove_env_namespace("MY") 
```

**Comment by L3MON4D3** [comment]
Oh, using a table is more readable, that's nicer than a function with a big ifelse.
Not completely convinced by the optional namespace, plugins could also just call the function meant for personal use.
Making the namespace required could be annoying too, I can see that... Maybe disable the required namespace by passing a special value, like `THIS_IS_FOR_MY_PERSONAL_USE_AND_NOT_A_PLUGIN`? xD

**Comment by leiserfg** [comment]
True, in any case, users can just use a very short namespace for "local" ones and a longer one for shared snippets sets (to avoid collitions)

**Comment by L3MON4D3** [comment]
Should be alright :+1: 
Are you interested in adding this?

**Comment by leiserfg** [comment]
I can work on it this weekend.

**Comment by L3MON4D3** [comment]
Sweet, looking forward to it

**Comment by L3MON4D3** [comment]
Just explicit steps for this:
Add
```lua
ls.env_namespace("SYS", {vars = os.getenv})
```
to your config, then you can access any environment-variable as `$SYS_VARNAME`, eg `$SYS_HOME`
