### ISSUE TITLE
Changing completion item icon

### ISSUE THREAD

**Issue by siduck76** [L3MON4D3/LuaSnip#48]
Hi there , is there any way I could change the "[Snippets]" here to only an icon?

![image](https://user-images.githubusercontent.com/59060246/123513102-d6b57c80-d6a8-11eb-9b37-697ef55e7ab0.png)

I do the same for buffer completion and it worked with vsnip too but I dont use vsnip anymore , tried it with luasnip but doesnt work 

![image](https://user-images.githubusercontent.com/59060246/123513126-efbe2d80-d6a8-11eb-82e5-ac75a782ec63.png)

![image](https://user-images.githubusercontent.com/59060246/123513262-d4075700-d6a9-11eb-884f-02bfa3694d2e.png)

**Comment by niceloaf** [comment]
Have you found a solution to this problem?

**Comment by siduck76** [comment]
sorry to close this issue without submitting the solution! And this is a compe thing 

![image](https://user-images.githubusercontent.com/59060246/124417664-472e5e80-dd77-11eb-86a4-fd08af8eaa68.png)

we need to add the menu option , menu = "icon'

![image](https://user-images.githubusercontent.com/59060246/124417699-5dd4b580-dd77-11eb-8d2a-ca4cdf061580.png)

**Comment by gegoune** [comment]
You don't need `true` in there when setting source to table. It should be enabled then, unless some option within the table disables it.
