### ISSUE TITLE
errors when pressing <Tab> in insert mode with nvim-cmp

### ISSUE THREAD

**Issue by tonymugen** [L3MON4D3/LuaSnip#483]
I get the following error

`E5108: Error executing lua [string ":lua"]:44: attempt to call global 'has_words_before' (a nil value)
stack traceback:
        [string ":lua"]:44: in function 'on_keymap'
        ...onyg/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:146: in function 'callback'
        ...cal/share/nvim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:118: in function <...cal/share/nvim/plugged/nvim-cmp/lua/cmp/ut
ils/keymap.lua:112>
        ...cal/share/nvim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:248: in function <...cal/share/nvim/plugged/nvim-cmp/lua/cmp/ut
ils/keymap.lua:247>`

when I press <Tab> in insert mode without any text (e.g., at the beginning of a line). This happens only when I attempt nvim-cmp integration. The minimal init.vim is
```
set completeopt=menu,menuone,noselect
let mapleader="-"
let maplocalleader="\\"
call plug#begin(stdpath('data') . '/plugged')
Plug 'hrsh7th/nvim-cmp'                                      " Autocomplete
Plug 'hrsh7th/cmp-buffer'                                    " Autocomplete
Plug 'hrsh7th/cmp-path'                                      " Autocomplete
Plug 'saadparwaiz1/cmp_luasnip'                              " Add LuaSnip to autocomplete
Plug 'L3MON4D3/LuaSnip'                                      " Snippets
call plug#end()
"#################################
"
" lua-based set-ups
lua <<EOF
-- LuaSnip set-up
require("luasnip.loaders.from_lua").lazy_load()
local keymap = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
keymap("i", "<c-n>", "<cmd>lua require'luasnip'.jump(1)<CR>", opts)
keymap("s", "<c-n>", "<cmd>lua require'luasnip'.jump(1)<CR>", opts)
keymap("i", "<c-p>", "<cmd>lua require'luasnip'.jump(-1)<CR>", opts)
keymap("s", "<c-p>", "<cmd>lua require'luasnip'.jump(-1)<CR>", opts)
-- nvim-cmp
local cmp = require('cmp')
local luasnip = require('luasnip')

cmp.setup({
	snippet = {
		-- REQUIRED - you must specify a snippet engine
		expand = function(args)
			if not luasnip then
				return
			end
			luasnip.lsp_expand(args.body)
	end,
	},
	mapping = {
		["<CR>"] = cmp.mapping.confirm { select = true },
		["<Tab>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_next_item()
			elseif luasnip.expand_or_jumpable() then
				luasnip.expand_or_jump()
			elseif has_words_before() then
				cmp.complete()
			else
				fallback()
			end
		end, { "i", "s" }),
		["<S-Tab>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_prev_item()
			elseif luasnip.jumpable(-1) then
				luasnip.jump(-1)
			else
				fallback()
			end
		end, { "i", "s" }),
	},
	sources = cmp.config.sources({
		{ name = 'buffer' },
		{ name = 'luasnip' },
		{ name = 'path' }
	})
})
EOF
" enable scrolling in terminal
set mouse=a
" Color scheme
set termguicolors
syntax on
set cindent
```
Deleting nvim-cmp fixes the issue.

Thanks for your help!

**Comment by L3MON4D3** [comment]
I think you're just missing that function, `has_words_before`, are you sure you copied the entire example?

**Comment by tonymugen** [comment]
Bingo! I am an idiot, forgot to check the example given by nvim-cmp. Thank you very much!

Great plug-in, by the way. I've been using UltiSnips for years, but it always had some small issues regardless of the completion engine etc. LuaSnip so far no problems, other than the self-infilcted one here. Thanks for your work!
