### ISSUE TITLE
LSP + LuaSnip / Friendly-Snippets multiple popups

### ISSUE THREAD

**Issue by feekApp** [L3MON4D3/LuaSnip#484]
Hi,
I stumbled upon the following issue, using [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), [LuaSnip](https://github.com/L3MON4D3/LuaSnip) and [friendly snippets](https://github.com/rafamadriz/friendly-snippets).

For scss and using for example 'dis' for 'display' [snippet], and letting expand the friendliest snippet I get the following popup:
![img](https://feek.d.pr/oXOo7D/nKvxbPUjae.jpg). As you can see, there is a 'cmp' popup as well a LSP popup.  The snip popup is generated by [this code](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#choicenode-popup).

![img](https://feek.d.pr/pOzo0e/UKiOLHygyT.gif)

As you can see in the gif above, after pressing <C> first the LuaSnip PopUp appears and shortly after that, the LSP PopUp overlaps the LuaSnip PopUP.

How do I prevent the LSP popup and only use the Lua Snip selection popup on pressing <CR>?

== Feek

**Comment by L3MON4D3** [comment]
Hey :) 
Sounds like you'll have to dynamically turn off cmp's autocompletion, take a look at cmps github, maybe there already are instructions on how to do this.

**Comment by feekApp** [comment]
HI @L3MON4D3,
I already expected some lite that, but on searching no results so far....

It happens also for a  Lua Snippet:
```lua
ls.parser.parse_snippet(
  {trig = "nice"},
  "nice: ${1|test1,test2,test3,test4,test5|} ${2:edit}"
),
```
but you only want to disable cmp lsp for an option, like `${1|...}`  but for `${2}` (as "inset mode") you definitely want to keep LSP insertions active (for setting variables).

**Comment by feekApp** [comment]
hi

Maybe something like this:

```
enabled = function()
  if luasnip.jumpable() then
    return false
  else
    return true
  end
end
```

[see](https://github.com/hrsh7th/nvim-cmp/wiki/Advanced-techniques#disabling-completion-in-certain-contexts-such-as-comments).  But I'am not sure what condition of luasnip I should use `luasnip.expand_or_jumpable()` ?   `luasnip.expand_or_jump()`

**Comment by feekApp** [comment]
Hi,
when using the following code:
```
enabled = function()
  if ( luasnip.expand_or_jumpable() and luasnip.choice_active() ) then
    return false
  else
    return true
  end
end
```
the expanding is almost going as expected. But it seems like `choice_active()` is only true when the choice is expanded as popup not when the cursor is on the current choice position (before pressing tab to expand the choice).

So is there a condition combinations that's return true for entering the choice position?

**Comment by L3MON4D3** [comment]
Ahh, you could just set some global boolean when the choice-window is opened (set in `choice_popup`, unset in `choice_popup_close`) and check it in `enabled`

**Comment by feekApp** [comment]
Hi @L3MON4D3 , thnx again for the prompt reply..... I'am quite new in the vim and lua world, so sorry for being a 'noob' .

No I do not think so, that will do the trick because the LSP is triggered before the choice popup is opened. I'am looking for a kind of "on_choice"  (before activate choice).
