### ISSUE TITLE
E5108 index out of range in util.mark bytecol_to_utfcol

### ISSUE THREAD

**Issue by aikow** [L3MON4D3/LuaSnip#485]
Pressing `<tab>` when not in a snippet with `expand_or_locally_jumpable()` throws an error due to an out of range index in `util/mark.lua`. This only happens occasionally, and I haven't been able to find a hard and fast rule yet when it happens. Actually triggering and expanding a snippet fixes the issue at least temporarily.

```text
E5108: Error executing lua: ...m/site/pack/packer/opt/luasnip/lua/luasnip/util/mark.lua:36: index out of range
stack traceback:
        [C]: in function 'str_utfindex'
        ...m/site/pack/packer/opt/luasnip/lua/luasnip/util/mark.lua:36: in function 'bytecol_to_utfcol'
        ...m/site/pack/packer/opt/luasnip/lua/luasnip/util/mark.lua:49: in function 'pos_begin_end'
        ...e/nvim/site/pack/packer/opt/luasnip/lua/luasnip/init.lua:143: in function 'in_snippet'
        ...e/nvim/site/pack/packer/opt/luasnip/lua/luasnip/init.lua:151: in function 'expand_or_locally_jumpable'
        .../aikow/.config/nvim/lua/aiko/plugins/configs/luasnip.lua:52: in function <.../aikow/.config/nvim/lua/aiko/plugins/configs/luasnip.lua:51>
```

## My Configuration

I've made sure that nothing else was influencing this, by creating a clean `init.lua`, only requiring packer and luasnip, and adding the following keybinding.

```lua
vim.keymap.set(
  { "i" },
  "<Tab>",
  function()
    if require("luasnip").expand_or_locally_jumpable() then
      ls.expand_or_jump()
    else
      feedkeys("<tab>")
    end
  end,
  { silent = true }
)
```

**Comment by L3MON4D3** [comment]
Oh that sucks, I thought that code was rock-solid by now :/
I played around with it a bit, but also can't reproduce it.

It's possible that such errors are caused by leftover marks ("leftover" as in the snippets text is deleted, but its extmarks are still around), what is your regular config? Do you have `delete_check_events` (responsible for cleaning up snippets whose text is deleted) set to eg. `"TextChanged"`?

**Comment by aikow** [comment]
I've been testing that with your suggestions and haven't had any of the issues since.

**Comment by L3MON4D3** [comment]
Nice, I'll implement a fix tomorrow
