### ISSUE TITLE
Cannot create snippets for nested filetype ("type1.type2")

### ISSUE THREAD

**Issue by Irubataru** [L3MON4D3/LuaSnip#486]
For my ansible configuration files I use the filetype `yaml.ansible` because that is the filetype the ansible language server attaches to. I tried to create some snippets for that filetype using

```lua
luasnip.add_snippets("yaml.ansible", {
  luasnip.snippet("hello", {luasnip.text_node("Hello")})
})
```

These are not picked up in the file itself. It will find snippets both registered to `yaml` and `ansible`, but not ones for the specific combination. As `.ansible` isn't a filetype I use elsewhere I could simply register them there, I just wanted to ask whether this is a bug or intended behaviour?

Thanks for the awesome plugin :heart:

**Comment by L3MON4D3** [comment]
> I just wanted to ask whether this is a bug or intended behaviour?

Yup, that's intended, if `&fileteype` is `something.anotherthing` it means that the current buffer has the filetypes `something` and `anotherthing`.
It's also pretty easy to modify the default-behaviour of luasnip in this case, look for `ft_func` in the readme, if you're interested in that :D

> Thanks for the awesome plugin :heart:

:)
