### ISSUE TITLE
[Question]Best way to delete a input snip node on a match?

### ISSUE THREAD

**Issue by ray-x** [L3MON4D3/LuaSnip#487]
Thanks for the great snip engine.

My requirement :
Similar to autocomplete
Triger:  `ml`, input:  two to three characters, e.g `ae`,  output choice node, and all the text elements with snake case or camel case words start with input, e.g. `a` and `e`. But I need to delete the input node on choice complete.

e.g.    `ml` ->(input)  `ak` ->  choice{'abc_kef_1', 'abc_kml_2', ...} -> (select 1st final text) final text `abc_kef_1`
 `ml` ->(input)  `dm` ->  choice{'dbc_mef_4', 'dbc_mll_6', ...} -> (select 1st final text) final text  `dbc_mef_1`
 `ml` ->(input)  `dm1` ->  textnode{'dbc_mef_1'}

What is the simplest way to do that?  My idea is use [node_ext_opts](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#ext_opts)  and `env` `current_line`. But I think this might be a common usage and already has some best practices to delete one or more input nodes on choice confirmed.  is there a helper function to delete nodes on leave?

**Comment by L3MON4D3** [comment]
Deleting nodes is not really supported right now (it's possible by jumping forward or backward on enter, but that might be rather unstable) :/

How about using `regTrig` for this instead?
You could trigger on "ml(...?)" and, in the dynamicNode which generates the choiceNode, check which two/three characters were captured via `parent.snip.captures[1]`.

**Comment by ray-x** [comment]
regTrig is another option, I will give it a try.
