### ISSUE TITLE
[FeatureRequest] Provide additional options for conditionally loading snippets

### ISSUE THREAD

**Issue by charleslambert** [L3MON4D3/LuaSnip#489]
Request:
Provide a mechanism to check additional conditions that do not directly relate to file type when snippets are loaded.

Example:
Check if the current file has the word "Test" in it's name and load testing specific snippets for that file type.

**Comment by L3MON4D3** [comment]
Mhmm, you could use an autocommand to extend the filetype of these files to `originalfiletype.testing` and register these snippets for the filetype testing, that would be pretty simple
