### ISSUE TITLE
Snipmate style snippets not automatically reloading.

### ISSUE THREAD

**Issue by ptrhvns** [L3MON4D3/LuaSnip#490]
I am currently using the snipmate style of snippets. If I change a snippets file (e.g. `python.snippets`), the changes are not available immediately. If I restart nvim, then the changes are available. Is there a way to auto-reload snippets on a change? Thanks.

**Comment by L3MON4D3** [comment]
If you're loading them with the loader (`require("luasnip.loaders.from_snipmate").(lazy_)load`) they should reload on edit (`BufPostWrite`).
Ah, the snippets are only reloaded in the neovim instance they're edited in, is that the issue?

**Comment by ptrhvns** [comment]
@L3MON4D3:

I'm sorry. I may totally misunderstand something, but anyway ...

Let's say I'm editing a Python file. If, in the same instance/session of Neovim, I open a new tab and edit my Python snippets file, add a snippet, and then write the snippets file, I'm unable to use that new snippet in my Python file (that would not be the case in `vim-snipmate` plugin as far as I understand). If I `source $MYVIMRC`, which contains the line `require("luasnip.loaders.from_snipmate").lazy_load()` in it, I'm still unable to use the new snippet in the Python file. Does that make sense? Do I need to re-edit the Python file (e.g. with `:edit example.py`)?

**Comment by L3MON4D3** [comment]
Ok, you're not totally misunderstanding something, the edited snippets should be available in the python-buffer.

>  Do I need to re-edit the Python file (e.g. with :edit example.py)?

No, that's not necessary.

Could you run `:au luasnip_watch_reload BufWritePost` and make sure that whatever source-file you're editing shows up? Maybe also register a new autocommand (on `BufWritePost`) with the filename listed there, and check if it's run after writing the file.
Another idea: run the function-call reported by the command manually.

It's working just fine for me btw, so at least the reload-mechanism isn't broken completely :D

**Comment by ptrhvns** [comment]
@L3MON4D3: okay, now it just seems to be working. I'm not sure what happened. I probably did something silly. Anyway, thanks for the help!
