### ISSUE TITLE
Doesn't seem to break Copilot

### ISSUE THREAD

**Issue by abenz1267** [L3MON4D3/LuaSnip#492]
Hi,

i think Luasnip is breaking Copilot after the first expansion. Quick example i'd reproduce with Go:

1. blank main.go
2. package main
3. start typing `func ` copilot will suggest a whole main function -> tab to expand
4. go above new main func
5. start typing `type` -> normally Copilot would suggest `type Person struct {` ... when Luasnip is installed, it doesn't.
6. Copilot seems to stop working.

Regards

**Comment by L3MON4D3** [comment]
Phuhh, I have no idea how luasnip might break copilot... Maybe open an issue on the plugins github, they might have more ideas how to troubleshoot this.

**Comment by abenz1267** [comment]
Hm,

one instance it also broke for me was when expanding via tab (mapped in nvim-cmp). It then literally returned the snippet and not the pre-filled (?) snippet copilot send. Not sure how the internals work ofc. Was just something i wanted to note XD.

Yeah, at first i thought it's some setting, but i removed all luasnip related settings from my config and it still broke. Only after uninstalling Luasnip it worked again.

Regards

**Comment by abenz1267** [comment]
i figured out it also breaks using vsnip. must be indeed a problem with the copilot plugin i guess.
