### ISSUE TITLE
postfix snippet example not working

### ISSUE THREAD

**Issue by pogopaule** [L3MON4D3/LuaSnip#493]
I tried to follow the examples in `:h luasnip.txt`

My LuaSnip config looks like this:

```
local ls = require"luasnip"
local s = ls.snippet
local sn = ls.snippet_node

local isn = ls.indent_snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
local r = ls.restore_node
local events = require("luasnip.util.events")
local ai = require("luasnip.nodes.absolute_indexer")
local fmt = require("luasnip.extras.fmt").fmt
local m = require("luasnip.extras").m
local lambda = require("luasnip.extras").l
local postfix = require("luasnip.extras.postfix").postfix

ls.add_snippets("all", {
  s("ternary", {
    -- equivalent to "${1:cond} ? ${2:then} : ${3:else}"
    i(1, "cond"), t(" ? "), i(2, "then"), t(" : "), i(3, "else"),
  }),
  postfix(".foo", {
    f(function(_, parent)
      return "[" .. parent.snippet.env.POSTFIX_MATCH .. "]"
    end, {}),
  })
})
```

The `ternary` snippet works as expected. But if I type e.g. `sometext.foo` the `.foo` postfix template is not shown.
I am using LuaSnip with nvim-cmp.

BTW: Thank you so much for adding them!! Missed them a lot coming from Intellij.

**Comment by L3MON4D3** [comment]
Mhmm weird, they show up for me:

https://user-images.githubusercontent.com/41961280/179809304-9c81bdd1-5ed7-4911-aa2c-ccc184816350.mp4

Not sure what could be going wrong here, do you have any noteworthy `nvim-cmp` settings?

**Comment by pogopaule** [comment]
> do you have any noteworthy nvim-cmp settings?

I'd say no.

```
local cmp = require'cmp'
local lspkind = require('lspkind')
local luasnip = require("luasnip")

cmp.setup({
  formatting = {
    format = lspkind.cmp_format({
      mode = 'symbol_text',
      maxwidth = 50,
    })
  },
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
  }),
  sources = { -- the order below defines the order in the completion popup
    { name = 'luasnip' },
    { name = 'nvim_lsp' },
    { name = 'buffer' },
    { name = 'tmux' },
    { name = 'path' },
  },
  window = {
    documentation = cmp.config.window.bordered(),
  }
})

-- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline('/', {
  sources = {
    { name = 'buffer' }
  },
  mapping = cmp.mapping.preset.cmdline({}),
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
cmp.setup.cmdline(':', {
  sources = cmp.config.sources({
    { name = 'path' }
  }, {
    { name = 'cmdline' }
  }),
  mapping = cmp.mapping.preset.cmdline({}),
})

```

**Comment by pogopaule** [comment]
Ok, I don't know what was stuck, but after restarting my tmux session the postfix snippet works. I am very sure I saved everything correctly beforehand because I also made changes to the ternary snippet to make sure the LuaSnip config got loaded as I expected. :shrug:

**Comment by L3MON4D3** [comment]
Ye olde turn off and on again :+1:

**Comment by pogopaule** [comment]
@L3MON4D3
Actually it was working all the time. I figured out what the actual problem is. There seems to be an issue between LuaSnip, postfix snippets and nvim-cmp.

Sometimes the postfix snippet is shown as the only cmp result for a split second. You only see it if you watch carefully. Then it is gone an all the other cmp results are shown.
Sometimes only the postfix snippet is shown and no other cmp results are shown.

Expansion works in either case.

Is this worth a ticket?

**Comment by L3MON4D3** [comment]
Probably yes, at least so the issue is known + potential solutions easy to find.
Open it in `cmp_luasnip`? I doubt `nvim-cmp` itself is at fault.

**Comment by pogopaule** [comment]
Done https://github.com/saadparwaiz1/cmp_luasnip/issues/47
