### ISSUE TITLE
Jump instead of expand when trigger is present on the snippet

### ISSUE THREAD

**Issue by rubenmate** [L3MON4D3/LuaSnip#494]
I have been experimenting writing my own snippets for commit messages (so I can learn lua snippets mostly) but I have found a problem that I can't find a proper solution.

I have this snippet:
`
s(
{ trig = "feat", name = "feature", dscr = "add new feature to the user" },
fmt("feat{}: {}", { c(1, { t "", fmt("({})", i(1, "scope")) }), i(2) })
),
`

I expand it with feat and then I have feat|: (| is the cursor), and If I try to jump to the second node it will expand the snippet again since feat is the snippet trigger.

Is there a workaround?, I can change the trigger to something else but I would like to keep it like it is.

**Comment by L3MON4D3** [comment]
I've had this problem myself, I think the best solution is to get used to distinct jump and expand-keys.
You could try adding some heuristic to determine whether to jump or expand, but I don't think anything there can work in all scenarios.

**Comment by rubenmate** [comment]
> I've had this problem myself, I think the best solution is to get used to distinct jump and expand-keys. You could try adding some heuristic to determine whether to jump or expand, but I don't think anything there can work in all scenarios.

Thanks for your answer.
I've ended with this, which works apparently fine for my specific needs in this snippet.
`
local isNested = false
return {
    -- Feature commit
    s(
        { trig = "feat", name = "feature", dscr = "add new feature" },
        fmt("feat{}: {}", { c(1, { t "", fmt("({})", i(1, "scope")) }), i(2) }),
        {
        condition = function()
            if isNested == true then
                return false
            end
            return true
        end,
        callbacks = {
            [1] = {
                [events.enter] = function(node, _event_args)
                    isNested = true
                end,
            },
        },
    }
    ),
...
`

I may consider switching to the separate jump/expand keys, but for me it's too much right now (previously I used Tab to almost everything -cmp, snippets-)

**Comment by L3MON4D3** [comment]
Ahh, you'll just have to reset `isNested` on leave.
So
```lua
callbacks = {
    -- -1 refers to the snippet itself    
    [-1] = { events.enter = set, events.leave = reset}
}
```
I think that should do it, you could extract it into a function for quickly creating snippets which you know won't be nested.

**Comment by L3MON4D3** [comment]
You're welcome :)
