### ISSUE TITLE
format node not passing args to function node

### ISSUE THREAD

**Issue by eduardoarandah** [L3MON4D3/LuaSnip#495]
Format nodes are great. I'd like to use them to apply functions to other args. 

However, format node doesn't get any args. This fails:

```
	s(
		"hello",
		fmt("your name {1} Hello {2}", {
			i(1, "ed"),
			f(function(args)
				return args[1][1]
			end),
		})
	),

```

when I do `:messages` I get nothing
```
	s(
		"hello",
		fmt("your name {1} Hello {2}", {
			i(1, "ed"),
			f(function(args)
				print(vim.inspect(args))
                                 return "??"
			end),
		})
	),

```

**Comment by L3MON4D3** [comment]
Oh, the functionNode is just missing the table where its' argnodes ([doc here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#functionnode)) are declared, `f(function ... end, {1})` should do it
