### ISSUE TITLE
Snippet freezes nvim and makes it use 100% CPU

### ISSUE THREAD

**Issue by lukas-reineke** [L3MON4D3/LuaSnip#496]
I used this snippet for some time. It should replace whitespace before a `*` when it is at the beginning of the line.
`　　*` would become `*`
This used to work.
Not exactly sure when it broke, but now when it triggers, it freezes nvim and makes it use 100% CPU.

```lua
s({ trig = "%s*%*", regTrig = true }, t "*", { condition = conds.line_begin })
```

**Comment by L3MON4D3** [comment]
What nvim are you on? For me it still works, I'm using master from a week or so ago (`5e53740350` seems to be the commit)

https://user-images.githubusercontent.com/41961280/180617929-a879c659-24b6-4866-911b-136ca1de7929.mp4

**Comment by lukas-reineke** [comment]
I am on the latest master `ea13dce3b`

I looked into it more, and it seems to only happen when history is on.

Here is a video:

https://user-images.githubusercontent.com/12900252/180631517-3a56e910-d5b0-4910-9ce8-ca2aa654f2e7.mp4

The full config to reproduce should be

```lua
-- main config
require("luasnip.loaders.from_lua").load { paths = "~/dotfiles/vim/lua/luasnippets" }

require("luasnip").config.set_config { history = true }
```

```lua
-- snippets for org mode
local regular = {}

local auto = {
    s({ trig = "%s*%*", regTrig = true }, t "*", { condition = conds.line_begin }),
}

return regular, auto
```

**Comment by L3MON4D3** [comment]
Interesting, only when history == `true` is unexpected.. Could you try the same trigger but a different snippet-body? The same snippet-body but a different trigger?

**Comment by L3MON4D3** [comment]
Trying newest master, I cannot reproduce it :/ (using this: ) 
```lua
ls = require("luasnip")

ls.config.set_config { history = true }

ls.setup_snip_env()
local conds = require("luasnip.extras.expand_conditions")

local snipp = s({ trig = "%s*%*", regTrig = true }, t "*", { condition = conds.line_begin })

ls.add_snippets("all", {
	snipp
}, {
	key = "asdfadsfaf"
})
```

**Comment by lukas-reineke** [comment]
Sorry, I think this is not even caused by LuaSnip. It's just that triggering the snippet causes something else to break.
I managed to reproduce it without LuaSnip as well.
I'll close the issue here

**Comment by L3MON4D3** [comment]
Okay :+1:
Hope you find the issue :)
