### ISSUE TITLE
Deleting insert node text with <bs> causes nvim to enter normal mode

### ISSUE THREAD

**Issue by Doltonius** [L3MON4D3/LuaSnip#499]
As in the title. When I am on an insert node `i(1, "some text")` and `some text` is selected, if I press `<bs>`, `some text` is deleted, but nvim also enters normal mode. Other inputs, such as `<space>`, `<cr>`, and alphanumerics, work as expected, i.e., replacing `some text` with the inputs.

Is this the expected behavior? Or is this a bug? I would like to think that it is a bug, since I certainly would not want to leave insert mode right after I press `<bs>`.

N.B. if I input some other character than `<bs>`, and then press `<bs>` to delete it, nvim stays in insert mode.

I am using `luasnip` with `nvim-cmp` .

**Comment by L3MON4D3** [comment]
luasnip uses just SELECT-mode to highlight placeholder-text, you can set a keybind to make `<Bs>` delete+enter insert:

```vim
" <C-G> changes to VISUAL, s clears and enters INSERT
snoremap <BS> <C-G>s
```

**Comment by Doltonius** [comment]
Thank you! That works.
