### ISSUE TITLE
How to use function nodes propertly? [QUESTION]

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#5]
I'm trying to migrate my snippets but I don't understand well how I'm supposed to use the `f` node
```lua
all = {
    s({trig = "date", wordTrig = true},
        {f(function() os.date() end, {})}
     ),

    s({trig = "date1", wordTrig = true},
        {f(function() t{os.date()} end, {})}
     ),
 }

```
None of those work so no idea what should I do.

**Comment by L3MON4D3** [comment]
Function expects text as a table where each entry is a line. 
So you're almost there, putting os.date() inside a table (`{os.date()}`) should do the trick.

**Comment by L3MON4D3** [comment]
Oh, and make sure to actually return the table from your function :D

**Comment by leiserfg** [comment]
I played that much with the nodes that ended deleting my return by accident :facepalm: Thanks a lot. It will be nice if you add a bit of doc about how to use the nodes,  at least function and dynamic.

**Comment by L3MON4D3** [comment]
Oof, I feel that.
There is some stuff in [here](https://github.com/L3MON4D3/LuaSnip/blob/a8784865da8fcb094e214673870667bb131212f5/Examples/snippets.lua) but you're right, there is much to add.
