### ISSUE TITLE
M1 Docker environment build nvim LuaSnip Error (ARM64 ubuntu)

### ISSUE THREAD

**Issue by goldyard** [L3MON4D3/LuaSnip#500]
I'm working with arm64 ubuntu to build docker, and the LuaSnip fired a error like when I start nvim:

```
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...ot/.local/share/nvim/plugged/LuaSnip/lua/luasnip/loaders/from_vscode.lua:21: '=' expected near 'continue'
stack traceback:
        [C]: in function 'error'
        ?: in function <?:18>
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

my nvim.vim like this, and other plugin work fine:
```

if has("nvim")
  let g:plug_home = stdpath('data') . '/plugged'
endif

call plug#begin()

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'

if has("nvim")
  Plug 'hoob3rt/lualine.nvim'
  Plug 'kristijanhusak/defx-git'
  Plug 'kristijanhusak/defx-icons'
  Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'neovim/nvim-lspconfig'
  Plug 'williamboman/nvim-lsp-installer'
  Plug 'tami5/lspsaga.nvim'
  Plug 'folke/lsp-colors.nvim'
  Plug 'L3MON4D3/LuaSnip'
  Plug 'hrsh7th/cmp-nvim-lsp'
  Plug 'hrsh7th/cmp-buffer'
  Plug 'hrsh7th/nvim-cmp'
  Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
  Plug 'kyazdani42/nvim-web-devicons'
  Plug 'onsails/lspkind-nvim'
  Plug 'nvim-lua/popup.nvim'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-telescope/telescope.nvim'
  Plug 'windwp/nvim-autopairs'
  Plug 'windwp/nvim-ts-autotag'
endif

Plug 'groenewege/vim-less', { 'for': 'less' }
Plug 'kchmck/vim-coffee-script', { 'for': 'coffee' }

call plug#end()
```

**Comment by goldyard** [comment]
Environment:
Dockerfile under Macos M1, Ubuntu 22.04 docker:

```
RUN apt-get update && apt-get --no-install-recommends install -y tmux fish luajit python3-neovim \
  software-properties-common gpg-agent nodejs npm \
  && add-apt-repository -y ppa:neovim-ppa/stable \
  && apt-get update \
  && apt-get --no-install-recommends install -y neovim gcc libc6-dev g++ \
  && rm -rf /var/lib/apt/lists/*
RUN sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
ADD dotfiles/.tmux.* /root/
ADD dotfiles/.config /root/.config/
ADD dotfiles/tree-sitter-0.20.6-1-aarch64.pkg.tar.xz /
```

**Comment by L3MON4D3** [comment]
Could you show the output of `nvim -v`?
I suspect nvim is linked agains lua, and not luajit, which causes an error because we use `goto`, which is only supported in luajit.

**Comment by goldyard** [comment]
nvim -v                                                                                                                          ✔  root@a7adaf2093b8
NVIM v0.7.2
Build type: Release
Lua 5.1
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by goldyard** [comment]
> Could you show the output of `nvim -v`? I suspect nvim is linked agains lua, and not luajit, which causes an error because we use `goto`, which is only supported in luajit.

Maybe you are right, after I execute "apt-get remove lua5.1", and the neovim is gone too......
and I compare with a docker instance under x64 cpu, the result is linke to LuaJIT, so how to link the nvim back to LuaJIT?:
```
nvim -v                                                                                                                                     ✔  root@ubuntu-ssh  18:05:54
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by L3MON4D3** [comment]
Okay, just removed the goto, I thought luajit is required for neovim and anything else is a misconfiguration, but that's not the case.
luasnip should also work with regular lua, with the latest master.

**Comment by leiserfg** [comment]
I was keeping it there as a flag to identify users not using luajit :smiling_face_with_tear: , the rest of the code should work without it but it hits the performance / disallows potential optimizations.

**Comment by leiserfg** [comment]
BTW, you can force docker in the M1 to use amd64  with `docker --platform linux/amd64` in amd64  ubuntu links nvim to `luajit`

**Comment by L3MON4D3** [comment]
> I was keeping it there as a flag to identify users not using luajit :smiling_face_with_tear:

xD

Yea, it's a bit unfortunate, I also quite like using goto when appropriate, but neovim apparently also officially supports building with just lua, so we better get rid of that :/

**Comment by goldyard** [comment]
After the day after, I found that this problem was fixed and neovim worked greate, even with lua5.1 (not luajit). So thanks a lot.
