### ISSUE TITLE
snippets issue

### ISSUE THREAD

**Issue by spelb** [L3MON4D3/LuaSnip#501]
Hi, I installed luasnip and friendly snippets from rafamadriz and added the  setup file shown in the readme but its not working and I did not get suggestions while I type.
![65](https://user-images.githubusercontent.com/108426549/181291210-05a43cc2-2463-4880-81db-89d6a3f755f0.png)

**Comment by L3MON4D3** [comment]
You'll need `cmp_luasnip`, otherwise this looks correct :+1:

**Comment by spelb** [comment]
> You'll need `cmp_luasnip`, otherwise this looks correct +1

I don't like language servers . However I used it with ramadariz/friendly-snippets. So it won't work with it?

**Comment by leiserfg** [comment]
`cmp_luasnip` is not only for lsp and yes, LuaSnip does work without it but it won't complete, you can still type the snippets and expand them by hand.

**Comment by spelb** [comment]
@leiserfg can you recommend me a snippets plugin for my neovim? I don't want to use language protocols. I want something without protocols for python, html,javascript,php,css,lua

**Comment by leiserfg** [comment]
You can use cmp without lsp.

**Comment by spelb** [comment]
> You can use cmp without lsp.

how? Please guide me a little

**Comment by spelb** [comment]
> > You can use cmp without lsp.
> 
> how? Please guide me a little
@leiserfg

**Comment by leiserfg** [comment]
Check the [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) documentation cmp-nvim-lsp is just a backend it has several more (including `cmp_luasnip`)  just add the ones you need and not the ones you don't. The doc is well written in that regard.

I think this is not a LuaSnip issue and can be closed as such.
