### ISSUE TITLE
[Feature-Request] Show autotrigger snippets in completion

### ISSUE THREAD

**Issue by atticus-sullivan** [L3MON4D3/LuaSnip#504]
Hi,
sometimes I forget about autotriggered snippets so it would be nice to be able to display autotriggered snippets in the completion menu of the completion engine as well by introducing a new option for that in the setup or maybe an explicit `show` option for the snippets function (contrary to the `hide` option).

**Comment by L3MON4D3** [comment]
There's [this PR](https://github.com/saadparwaiz1/cmp_luasnip/pull/27) (though it's outdated for current master) for showing autosnippets, I think the best way would be to set an option in `cmp_luasnip.setup()`

**Comment by atticus-sullivan** [comment]
Ah of course. As this is only related to displaying, this should be done in the "adapters" to the completion engines. I'm gonna look into this (in a few weeks). But this changes look a bit complicated (at least at first sight) (have to dig through all the code related to caching first).

**Comment by L3MON4D3** [comment]
Yeaaah, the caching makes the otherwise pretty straightforward job of turning a list of snippets into a list of completion-items a bit more messy :/
Luckily we cache entire filetypes at once, so it's not horribly complicated

**Comment by atticus-sullivan** [comment]
Not sure since when but at least for my limited amount of autosnippets, I get them listed in the completion menu of `cmp`. Thus this issue is solved for me.
