### ISSUE TITLE
luarocks setup

### ISSUE THREAD

**Issue by atticus-sullivan** [L3MON4D3/LuaSnip#508]
Hi,
I'm currently trying to set things up to contribute to this project.
Done so far:
- create the fork
- cloned

Failed:
- try to run `make test` (are the tests from `/tests/` run on this command, not sure since it starts with compiling nvim from scratch)

As I use lua outside of nvim as well for coding, `luarocks` is already set up for my normal system (`LUA_PATH` and `LUA_CPATH` set). At first I got some error when during compiling nvim dependencies from my normal setup (other lua-version, no luajit) were tried to included, which obviously failed.
After that I thought, hm just unset these to environment variables and the nvim compiling stuff should have no idea that luarocks is already up and running (thus sets up its things on its own, in the `/deps` folder). Now it seams that it cannot find the e.g. `lpeg` module (which previously was installed as I saw). The error message indicates that the search path is now empty (`/usr/bin/lua: module 'lpeg' not found: no file ''`) and the modules aren't found anymore (well, I unset these environment variables after all).

What is your `luarocks` setup when running `make test`, in particular to what values are the variables `LUA_PATH` and `LUA_CPATH` set?

See [make.txt](https://github.com/L3MON4D3/LuaSnip/files/9275206/make.txt) for the output of `make test`. The interesting lines should be 1442 (`lpeg` is getting installed in `/deps`) and 1558 (`cmake` nvim starts, and lpeg isn't getting found). Most likely cmake doesn't find `lpeg` because the env-vars are wrong (but I wonder how this works in your environments)

EDIT: Hm, I see in the [pipeline](https://pipelines.actions.githubusercontent.com/serviceHosts/d2af9689-726e-4824-8a89-a78f0db1d5fb/_apis/pipelines/1/runs/916/signedlogcontent/2?urlExpires=2022-08-06T14%3A05%3A13.9038860Z&urlSigningMethod=HMACV1&urlSignature=nb4eNiuJu3s0CEmN77NY3QlnJyduZk7j7Oql8nJG6Wc%3D) things are simply installed by the normal packet manager

**Comment by leiserfg** [comment]
@L3MON4D3  I think we need a docker image for running the tests :thinking:

**Comment by L3MON4D3** [comment]
Ahh, that's unfortunate, I was hoping it would just work :sweat_smile:
Did you unset or set LUA_PATH to the empty string? The latter would explain the `no file ''`-error (see there -> https://www.lua.org/pil/8.1.html)

> @L3MON4D3 I think we need a docker image for running the tests :thinking:

Yeeeaaah, I start fearing as much, though I'd rather not require docker, I'm not really comfortable with it (read: I have no experience with it -> dislike)
If there's no other way I'll familiarize myself with the basics and we can use it in our build.
(what do you think about doing this with nix? I have more interest in it than docker, is it feasible for us to use it?)

**Comment by atticus-sullivan** [comment]
> Did you unset or set LUA_PATH to the empty string? 
Well that's embarrassing for me, I didnÄt remember `unset` and just set it to `""`. With `unset` it runs now, thanks.

Not quite sure what to learn from this, should we add this unsetting to the `Makefile`? But this would let the way the github action is doing it (installing via packet manager) fail I guess, so probably we should keep it the way it is.
Question is how to prevent this to happen for others? (I have no real idea as I'm not that familiar with other setups that work with the current way and how to detect which setup it is)

**Comment by leiserfg** [comment]
> Ahh, that's unfortunate, I was hoping it would just work 😅 Did you unset or set LUA_PATH to the empty string? The latter would explain the `no file ''`-error (see there -> https://www.lua.org/pil/8.1.html)
> 
> > @L3MON4D3 I think we need a docker image for running the tests 🤔
> 
> Yeeeaaah, I start fearing as much, though I'd rather not require docker, I'm not really comfortable with it (read: I have no experience with it -> dislike) If there's no other way I'll familiarize myself with the basics and we can use it in our build. (what do you think about doing this with nix? I have more interest in it than docker, is it feasible for us to use it?)

The problem with using nix is forcing potential contributors to use it.

**Comment by L3MON4D3** [comment]
> > Did you unset or set LUA_PATH to the empty string?
> Well that's embarrassing for me, I didnÄt remember `unset` and just set it to `""`. With `unset` it runs now, thanks.

Nice, okay that's great

> Not quite sure what to learn from this, should we add this unsetting to the `Makefile`? But this would let the way the github action is doing it (installing via packet manager) fail I guess, so probably we should keep it the way it is. Question is how to prevent this to happen for others? (I have no real idea as I'm not that familiar with other setups that work with the current way and how to detect which setup it is)

I'll see if it works with CI, if it does it should be alright to add to the makefile.



> > Ahh, that's unfortunate, I was hoping it would just work sweat_smile Did you unset or set LUA_PATH to the empty string? The latter would explain the `no file ''`-error (see there -> https://www.lua.org/pil/8.1.html)
> > > @L3MON4D3 I think we need a docker image for running the tests thinking
> > 
> > 
> > Yeeeaaah, I start fearing as much, though I'd rather not require docker, I'm not really comfortable with it (read: I have no experience with it -> dislike) If there's no other way I'll familiarize myself with the basics and we can use it in our build. (what do you think about doing this with nix? I have more interest in it than docker, is it feasible for us to use it?)
> 
> The problem with using nix is forcing potential contributors to use it.

That's true :/
Let's see if we can get away with that fix for now, if not we'll have to think about this again

**Comment by L3MON4D3** [comment]
Looks like CI also handles unsetting `LUA_{C,}PATH`, so we should be gtg for now :)
