### ISSUE TITLE
Hot reloading: handle symlinks?

### ISSUE THREAD

**Issue by helixbass** [L3MON4D3/LuaSnip#518]
Hi, I just figured out (with the help of https://github.com/L3MON4D3/LuaSnip/issues/490#issuecomment-1186827332, thanks) that why hot reloading of a Lua snippets file wasn't working for me is that I was editing the snippets file via a symlink'd parent directory (specifically I symlink `~/.config/nvim` to a subfolder of my dotfiles repo ie `~/prj/dot/nvim`). It worked when instead I opened the snippets file specifying its "true" (non-symlink'd) file path

To be specific, in my config where I specify loading the snippets file I'm providing the symlink'd path, not the true path:
```
require('luasnip.loaders.from_lua').load({paths = '~/.config/nvim/snippets'})
```

So I wonder if it's possible to handle detecting editing of snippets files even if opened via a symlink'd file path?

**Comment by L3MON4D3** [comment]
Ouhh I see, I guess the autocommand `BufWritePost` is only fired for exactly the name of the buffer..
So we have
1. load real directory
2. Add autocommand on BufWritePost for real path
3. Edit symlinked file
4. BufWritePost fires for symlinked, but not the real path

I'm afraid we can't do anything about that, we don't know the name of the symlinks to that file :/
We might have to switch to some other way to register snippetfile-changes(not sure if there are other autocommands for this) to correctly handle this case.
For now, you could use `:LuaSnipEdit` (search for that command in the DOC if it doesn't tell you anything😅) to edit the snippet-files.

**Comment by L3MON4D3** [comment]
Mhmm, perhaps we should, instead of registering autocommands, collect all interesting files in some central table.
We could then have one autocommand, which, on BufWritePost, resolves the real path of the written buffer and then updates the snippets if it was a snippet-file

That would also remove some other rather brittle parts of the current procedure.. tempting :D

**Comment by leiserfg** [comment]
I just read the code o the auto-reload, and yes it should be a single `autocmd` per loader instead of one per file, registering autocmds is very slow.

**Comment by L3MON4D3** [comment]
Ouh, I did not know that.
Do you think it would make more sense to store the reload-function as a closure (simpler, a bit more uniform, maybe slower) or just as a loader-specific tuple of parameters to that function (easier to debug, since the parameters are right there)?

**Comment by leiserfg** [comment]
I don't think they're very different in speed but storing only the data will take less space and will be easier to debug.

**Comment by L3MON4D3** [comment]
Perfect👍
I think this can be done rather quickly, I'll look into it soon.

**Comment by L3MON4D3** [comment]
Pushed a solution in `loader_handle_symlinks`, could you make sure it works for you @helixbass?
