### ISSUE TITLE
Attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by ram02z** [L3MON4D3/LuaSnip#52]
Preface:
This error only occurs when `bdelete` is used. When `bwipeout` is used, the error doesn't occur.

First error:
![image](https://user-images.githubusercontent.com/59267627/124022699-0df79680-d9e5-11eb-856b-a24f39f77d07.png)

Steps to reproduce:
1) Open two buffers
2) Insert a snippet in one of the buffers
3) Save and `bdelete` the buffer
4) Reopen the file

Second error:
![image](https://user-images.githubusercontent.com/59267627/124023682-1e5c4100-d9e6-11eb-9296-ebe020439e3d.png)

Steps to reproduce:
1) Reproduce first error
2) Execute `<Plug>luasnip-expand-or-jump` bind on the same line as the snippet till error pops up

LuaSnip Configuration:
```lua
local function char_count_same(c1, c2)
  local line = vim.api.nvim_get_current_line()
  local _, ct1 = string.gsub(line, c1, '')
  local _, ct2 = string.gsub(line, c2, '')
  return ct1 == ct2
end

local function even_count(c)
  local line = vim.api.nvim_get_current_line()
  local _, ct = string.gsub(line, c, '')
  return ct % 2 == 0
end

local function neg(fn, ...)
  return not fn(...)
end

local ls = require'luasnip'
local s = ls.s
local t = ls.t
local i = ls.i

ls.snippets = {
  all = {
    s({trig="("}, { t({"("}), i(1), t({")"}), i(0) }, neg, char_count_same, '%(', '%)'),
    s({trig="{"}, { t({"{"}), i(1), t({"}"}), i(0) }, neg, char_count_same, '%{', '%}'),
    s({trig="["}, { t({"["}), i(1), t({"]"}), i(0) }, neg, char_count_same, '%[', '%]') ,
    s({trig="<"}, { t({"<"}), i(1), t({">"}), i(0) }, neg, char_count_same, '<', '>'),
    s({trig="'"}, { t({"'"}), i(1), t({"'"}), i(0) }, neg, even_count, '\''),
    s({trig="\""}, { t({"\""}), i(1), t({"\""}), i(0) }, neg, even_count, '"'),
    s({trig="{;"}, { t({"{","\t"}), i(1), t({"", "}"}), i(0) }),
  },
}
```
P.S. Stole the snippets from your configuration and they work nicely! Thanks.

**Comment by L3MON4D3** [comment]
Ohh, makes total sense; luasnip stores its active node for buffer `n` in `Luasnip_current_nodes[n]`. It seems that nvim deletes extmarks on `bdelete`, so when loading the buffer again, Luasnip expects extmarks that aren't there anymore. As a quick fix, you can `:lua Luasnip_current_nodes[`[id of deleted buffer]`]=nil` (or just `:lua Luasnip_current_nodes = {}`, if you don't care about snippet-history in other buffers).
Thanks for reporting, hadn't thought about that :D

**Comment by L3MON4D3** [comment]
I added an autocommand to automatically `nil` the node of the deleted buffer, please reopen if I missed something.
