### ISSUE TITLE
Question: How can I make a completion for filetype A  available for different filetype B? 

### ISSUE THREAD

**Issue by shivanth** [L3MON4D3/LuaSnip#524]
[Telekasten](https://github.com/renerocksai/telekasten.nvim) uses markdown files, but has its own fileteype and hence the markdown snippets are unavailable. How can i make snippets for md available for telekaten filetype ?

**Comment by L3MON4D3** [comment]
You can use `ls.filetype_extend`, in your case probably `ls.filetype_extend("telekasten_filetype", {"markdown"})`
