### ISSUE TITLE
[question] multiline postfix?

### ISSUE THREAD

**Issue by alex-popov-tech** [L3MON4D3/LuaSnip#529]
Hello!

I want to achieve something like
```
-- before
kek.if_
-- press <tab>
if ( kek ) {
  _
}
```

so far i did something like 
```
        postfix('.if', {l({'if (', l.POSTFIX_MATCH, ') {'})}),
```
but it puts everything on one line.... can somebody please point me where im missing something?

**Comment by L3MON4D3** [comment]
Hi!
That snippet is just missing a newline and an insertNode:
```lua
	postfix(".of", fmt([[
		if({}) {{
			{}
		}}
	]], {
		l(l.POSTFIX_MATCH),
		i(1)
	}))
```
(I'm using `fmt` here, makes the snippets more readable)

**Comment by alex-popov-tech** [comment]
thanks @L3MON4D3 <3

**Comment by Samasaur1** [comment]
for anyone curious how to do this without using `fmt`:
```lua
    require("luasnip.extras.postfix").postfix(".ef", {
        t("if ("),
        l(l.POSTFIX_MATCH),
        t({") {", "\t"}),
        i(1),
        t({"", "}", ""}),
        i(0)
    }),
```
