### ISSUE TITLE
Match indentation?

### ISSUE THREAD

**Issue by aoswalt** [L3MON4D3/LuaSnip#53]
Is there any way to match the current indentation for multi-line snippets?

For example, with snippets.nvim, I have a few snippets similar to this:

```lua
    def = U.match_indentation [[
def ${1:function}($2) do
  $0
end]];
```

When inserted, each line is prepended with the current indentation of the trigger.

Is there a way to do this, or even more generally, operate on each line of the snippet's result to be able to do things like add a comment prefix, line numbers, etc. to be able to build the match indent functionality in user space?

Thank you!

**Comment by L3MON4D3** [comment]
Intendation should be added automatically, does it not work anymore? :grimacing:

**Comment by aoswalt** [comment]
Nevermind. I had a mis-keybind that was using the wrong snippet. Works like a charm! 😁
