### ISSUE TITLE
Error E5108 raised by calling field  _load_lazy_loadded

### ISSUE THREAD

**Issue by jfmoulin** [L3MON4D3/LuaSnip#541]
Hello,

after upgrading neovim to 0.7.2, I get this problem with luasnip: 
```
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...pack/paqs/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:97: attempt to call field 'get_load_fts' (a nil value)
stack traceback:
        ...pack/paqs/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:97: in function '_load_lazy_loaded'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua [string ":lua"]:1: attempt to call field '_load_lazy_loaded' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
E5108: Error executing lua [string ":lua"]:1: attempt to call field '_load_lazy_loaded' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk

```

Any help much appreciated

**Comment by leiserfg** [comment]
That line does not matches what is currently on our code, are you using an old version? If not, are you using a lua cache (impatient, hotpot)?

**Comment by jfmoulin** [comment]
This is what I find about the version using :help luasnip

`*luasnip.txt*            For NVIM v0.5.0            Last change: 2022 March 13`

I am using paq as manager and have ran updates.

Not sure about the lua cache you mention. Neither Impatrient nor hotpot are in my lua.init
The only reference to caching is about x-clipboad caching. I guess this is not related.

**Comment by leiserfg** [comment]
Yes, your LuaSnip is several months old, the latest changes in the main branch are from a couple of days ago.

**Comment by jfmoulin** [comment]
so... how should I update it? should it not work from paq?
I did not clone the git repo by hand, just included it in my config.lua:

`require "paq"{"L3MON4D3/LuaSnip"}`

sorry for the naive question...

**Comment by jfmoulin** [comment]
I searched for the install and looked at the status

```
~/.local/share/nvim/site/pack/paqs/start/LuaSnip$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
Either I am not looking at the right place or do not point at the good repo...?
This seems pretty fresh:
```
~/.local/share/nvim/site/pack/paqs/start/LuaSnip$ git log
commit faa525713e1244551877a4d89646a10f3c3fa31e (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: L3MON4D3 <41961280+L3MON4D3@users.noreply.github.com>
Date:   Thu Aug 18 20:50:46 2022 +0200

    Merge pull request #540 from jrowlingson/patch-3
    
    doc: doc.md alternate function node example

```

**Comment by L3MON4D3** [comment]
> That line does not match what is currently on our code, are you using an old version? If not, are you using a lua cache (impatient, hotpot)?

Wait are you sure? For me, `master:from_lua:97` is exactly that call

> Yes, your LuaSnip is several months old, the latest changes in the main branch are from a couple of days ago.

I think `:h` may not be automatically updated, but this could also be an older version..

It's weird that `luasnip.loaders.util` is not found, could you check if there is some other version of luasnip in your runtimepath?
(you can go through the dirs in `:set rtp`, take care to look into globbed ones)

**Comment by leiserfg** [comment]
> Wait are you sure? For me, `master:from_lua:97` is exactly that call

:facepalm:  I was looking for the other function in that line. That does not explain why it can't load functions from utils, nor why the wrong date is in the documentation. 
Showing the output of 
`:lua= require"luasnip.util.util"`
may help in the debugging

**Comment by L3MON4D3** [comment]
Wait wth, since when can one just use `=` to inspect-print some values?????

> That does not explain why it can't load functions from utils, nor why the wrong date is in the documentation

Ahh, I was thinking of `:helptags` for generating the tags, makes sense that the help itself is always up-to-date.

**Comment by leiserfg** [comment]
> Wait wth, since when can one just use `=` to inspect-print some values?????

I think since `vim.pretty_print()` was added.

**Comment by jfmoulin** [comment]
I will check the paths as soon as I have a moment, in the meantime here is the requested output of `:lua= require"luasnip.util.util"`

```
{                                                                                                                                                                  
  any_select = <function 1>,
  buffer_comment_chars = <function 2>,
  bytecol_to_utfcol = <function 3>,
  dedent = <function 4>,
  deduplicate = <function 5>,
  expand_tabs = <function 6>,
  find_outer_snippet = <function 7>,
  get_current_line_to_cursor = <function 8>,
  get_cursor_0ind = <function 9>,
  get_selection = <function 10>,
  get_snippet_filetypes = <function 11>,
  indent = <function 12>,
  insert_move_on = <function 13>,
  json_decode = <function 14>,
  json_encode = <function 15>,
  key_sorted_pairs = <function 16>,
  line_chars_before = <function 17>,
  mark_pos_equal = <function 18>,
  move_to_mark = <function 19>,
  multiline_equal = <function 20>,
  no_region_check_wrap = <function 21>,
  normal_move_on_insert = <function 22>,
  pop_front = <function 23>,
  pos_add = <function 24>,
  pos_equal = <function 25>,
  pos_sub = <function 26>,
  put = <function 27>,
  remove_n_before_cur = <function 28>,
  set_cursor_0ind = <function 29>,
  store_selection = <function 30>,
  string_wrap = <function 31>,
  tab_width = <function 32>,
  to_line_table = <function 33>,
  word_under_cursor = <function 34>,
  wrap_nodes = <function 35>,
  wrap_value = <function 36>
}

```

**Comment by jfmoulin** [comment]
Hmmmm, seems I found something old:
```
jfmoulin@jfm17:~/.local/share/nvim/site/pack/packer/start/LuaSnip$ git log
commit f12b147d3d9cb6bd16417ae0adb2191a36148691 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: L3MON4D3 <41961280+L3MON4D3@users.noreply.github.com>
Date:   Sun Mar 13 10:21:20 2022 +0100

    Merge pull request #333 from leiserfg/panvimdoc
    
    Replace md2vim with panvimdoc

```

I have not yet had the time to look at the whole rtp, it is loooong.
How should I deal with conflicting locations, how can I know which one has precedence? (Ist the first one found in rtp the active one?)

**Comment by jfmoulin** [comment]
Updating (git pull) in the above directory solved the error, nevertheless I'd like to cleanup theinstall to be sure my paqckage manager works properly. Tips?

**Comment by L3MON4D3** [comment]
> I think since `vim.pretty_print()` was added.

Sweeet, no more wrapping in `print(vim.inspect(...))`

> Hmmmm, seems I found something old:

Yup, that seems to be it.
Can you just remove/move it? Can imagine that doing it :D

**Comment by leiserfg** [comment]
Seems like you moved from one package manager to another, if that's the  case remove the full `~/.local/share/nvim/site/pack/packer/` folder or you will face the same issue with other plugins.

**Comment by jfmoulin** [comment]
I now did 
```
jfmoulin@jfm17:~$ mv ~/.local/share/nvim/site/pack/packer/start/LuaSnip ~/.local/share/nvim/site/pack/packer/start/LuaSnip~
```
and neovim starts without complaining. 
Your comment makes perfect sense, I'll try and cleanup.

How can I find the source code being used by a running plugin, is there any generic command ?

Thanks a lot for your reactivity !

**Comment by leiserfg** [comment]
If you know a public function of the plugin you can do something as:
```
:lua= debug.getinfo(require('luasnip').config.set_config).source 
```
