### ISSUE TITLE
[Feature Request] add disable file type for add_snippets

### ISSUE THREAD

**Issue by XXiaoA** [L3MON4D3/LuaSnip#554]
for example, the following code means add the snippets for all file type, except lua file
```lua
require("luasnip").add_snippets("-lua", todo_comment_snippets, { type = "snippets", key = "todo_comments" })
```

**Comment by L3MON4D3** [comment]
Interesting, but I can't see what this could be useful for.
Could you give an usecase?

**Comment by XXiaoA** [comment]
> Interesting, but I can't see what this could be useful for. Could you give an usecase?

Follow the [Wiki](https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#all---todo-commentsnvim-snippets), i created many todo snippet can be triggered like "fix". Alse, I created some git commit [snippets](https://github.com/XXiaoA/nvimrc/blob/main/snippets/gitcommit.lua) can alse be triggered by "fix. Sometimes, I choosed the wrong one. Therefore, I think add this feature can avoid this problem

**Comment by L3MON4D3** [comment]
Ah, I see..
Adding the git-commit-snippets a higher priority would also solve this, eg.
```lua
-- default-priority is 1000
add_snippets("all", {...}, {override_priority = 999})
```
Rereading your comment though, you say "choose", I guess you're selecting the snippet via `nvim-cmp`? In that case priority would not fix the problem.

I think the cleanest solution might be registering the todo-comment-snippets under their own filetype, something like "commentable", and then extending the filetypes of buffers if they are commentable:
```lua
add_snippet("commentable", todo_comment_snippets, key = "todo_comments")
-- BufEnter can be replaced with anything before BufWinEnter.
-- (lazy_load-snippets are loaded on BufWinEnter, so at that point the filetype_extends have to be correct (TODO: maybe trigger load_lazy_loaded on `ls.filetype_extend`..))
vim.api.nvim_create_autocmd("BufEnter", {
	pattern = "*",
	callback = function(arg)
		local bufnr = arg.buf

		--determine whether buffer is commentable or not.
		local buf_ft = vim.api.nvim_buf_get_option(bufrn, "filetype")
		if buf_ft == "gitcommit"
			return
		end

		-- if the buffer is commentable, extend filetype:
                -- (this might actually lead to duplicates right now, we don't check if the filetype has
                -- already been extended. I'll push a fix to that in a bit)
		ls.filetype_extend(buf_ft, {"commentable"})
	end
})
```
The way you can even use more complex checks. I can see that this is quite a bit more code, Might be nice to include it in luasnip directly, as a kind of `dynamic_extend(function(bufnr) -> filetypes)`

**Comment by XXiaoA** [comment]
Ok, I got it. It does be a good idea.Thx
