### ISSUE TITLE
Help tags are not unique

### ISSUE THREAD

**Issue by nifoc** [L3MON4D3/LuaSnip#556]
The `luasnip-snipmate` tag is generated twice, which causes the following error:

```
E154: Duplicate tag "luasnip-snipmate" in file /nix/store/h5m4sfpyig65wbkr9jmp35ki2a4ii4sa-vimplugin-LuaSnip-2022-08-27/./doc/luasnip.txtFailed to build help tags!
```

I tried to fix this in #555, but was unaware the the file is auto-generated using panvimdoc. I'm not sure how to supply tags using panvimdoc and not have them be auto-generated.

**Comment by L3MON4D3** [comment]
Ouuhhh, yeah that's not good
I think to prevent the error for now I'll quickly change the titles to remove the collision, a proper solution would be a change in panvimdoc (used to auto-generate the help).
(subheading-tags are not prefixed with the heading, so 
```markdown
#a
## b
# c
## b
```
generates the tag `luasnip-b` twice)

**Comment by nifoc** [comment]
Fixed with the latest commit. Thank you @leiserfg!
