### ISSUE TITLE
TexLab Language Server: snippet not working properly

### ISSUE THREAD

**Issue by saadparwaiz1** [L3MON4D3/LuaSnip#56]
I'm not sure if this is an issue with the texlab language server or LuaSnip. Let me know and I'll close this issue and create one on their repo. 

Here's the v:completed_item dictionary if that might be helpful

```viml
{'word': 'begin{', 'menu': '[LSP]', 'user_data': {'compe': {'completion_item': {'label': 'begin', 'data': 
'commandSnippet', 'preselect': v:false, 'sortText': '00', 'kind': 15, 'detail': 'built-in', 'insertText': 
'begin{$1}^@^I$0^@\end{$1}', 'insertTextFormat': 2}, 'request_position': {'character': 1, 'line': 4}}}, 'info': '', 'kind': '', 'abbr': 'begin~'}   
```

**Comment by L3MON4D3** [comment]
I also used to have issues with the texlab lsp, however it works for me right now. What versions of nvim, compe, texlab are you on? I have `NVIM v0.5.0-dev+1459-g384f9870f`, most recent compe and texlab 2.2.2.

**Comment by saadparwaiz1** [comment]
Currently on stable neovim v0.5.0 (stable) and texlab 3.2.0; I'll try downgrading texlab to see if the issue gets fixed

**Comment by L3MON4D3** [comment]
Could you show the output of `:lua Luasnip_current_nodes[vim.api.nvim_get_current_buf()].parent:dump()` directly after expanding?
I haven't seen anything like that before, but maybe the extmarks get messed up in some spectacular way

**Comment by L3MON4D3** [comment]
Another possibility could be some lsp-weirdness (and maybe compe?). My `texlab`-config:
```lua
nvim_lsp.texlab.setup{
	cmd = { "texlab" },
    filetypes = { "tex", "bib" },
    settings = {
      bibtex = {
        formatting = {
          lineLength = 120
        }
      },
      latex = {
        build = {
          args = { "-pdf", "-interaction=nonstopmode", "-synctex=1", "%f" },
          executable = "latexmk",
          onSave = true,
          onChange = true
        },
        forwardSearch = {
          args = {},
          onSave = false
        },
        lint = {
          onChange = false,
          onSave = true
        }
      }
    },
	on_attach = lsp_attach,
	capabilities = capabilities
}
maybe try setting it to the same?
```

**Comment by saadparwaiz1** [comment]
Here's my lspconfig which is pretty similar to yours:

```lua
local lspconfig = require('lspconfig')
local util = require('s.util')

lspconfig.texlab.setup {
  on_attach = util.lsp.on_attach,
  capabilities = util.lsp.capabilities,
  texlab = {
    latexFormatter = 'latexindent',
    latexindent = {
      ['local'] = nil,
      modifyLineBreaks = false;
    }
  },
  settings = {
    latex = {
      forwardSearch = {
        args = {"%l", "%p", "%f"},
        executable = "/Applications/Skim.app/Contents/SharedSupport/displayline",
        onSave = false,
      },
      build = {
        args = {
          "-pdf",
          "-interaction=nonstopmode",
          "-synctex=1",
          "-shell-escape",
          "-pvc",
          "%f"
        },
        executable = "latexmk";
        onSave = false;
      },
    }
  }
}
```

Here's the output for
 `:lua Luasnip_current_nodes[vim.api.nvim_get_current_buf()].parent:dump()`

<img width="640" alt="Screenshot 2021-07-02 at 22 21 57" src="https://user-images.githubusercontent.com/73385353/124329906-3bc71180-db84-11eb-850b-bcdf59925fad.png">

**Comment by L3MON4D3** [comment]
Extmarks look fine, maybe the `latex-formatter` messes something up?
Try `:lua ls.snippets = {all = {ls.parser.parse_snippet({trig = 'beg'}, "\\begin{$1}\n\t$0\n\\end{$1}")}}` and then expand that using `beg`. That should tell us whether it's the formatting or something else.

**Comment by saadparwaiz1** [comment]
The above snippets works fine I also tried disabling the formatter and the issue still persists. Thank you so much for helping out with this issue!

**Comment by L3MON4D3** [comment]
Yeah, of course. If you do figure out what went wrong, please update here :D

**Comment by saadparwaiz1** [comment]
will do!

**Comment by saadparwaiz1** [comment]
The issues doesn't seem to occur with snippets.nvim; Is there any way I can test this without comps? I just want to rule out it's not compe causing the issue. Thanks again for a great plugin and all the help!

**Comment by L3MON4D3** [comment]
Apart from just parsing and expanding the snippet manually, no :/

**Comment by L3MON4D3** [comment]
Nevermind that, I think it's possible to expand lsp-snippets using omnifunc, I think I saw a PR on the neovim-github, maybe check that out.

**Comment by saadparwaiz1** [comment]
Ah thanks will try it out. Thank you so much!

**Comment by saadparwaiz1** [comment]
This issue is fixed in latest master now!

**Comment by L3MON4D3** [comment]
Hah, nice!
