### ISSUE TITLE
Support Global Snippets (Snipmate-like)

### ISSUE THREAD

**Issue by amarakon** [L3MON4D3/LuaSnip#560]
I use the [vim-snippets](https://github.com/honza/vim-snippets) repository for a set of default snippets for each file type. But they also have a file called `_.snippets` which contains global snippets which means they should work on all file types. On nvim-snippy, these global snippets work. On LuaSnip though, they do not.

**Comment by leiserfg** [comment]
We use 'all' for that

**Comment by amarakon** [comment]
> We use 'all' for that

Thanks, it works.

**Comment by L3MON4D3** [comment]
Note that you can use `ls.filetype_extend("all", {"_"})` to make `_`-snippets global

**Comment by hiberabyss** [comment]
> Note that you can use `ls.filetype_extend("all", {"_"})` to make `_`-snippets global

In my case, the global snippets did not loaded with the setting. The result of `require("luasnip").get_snippet_filetypes()` is

```
{ "cpp", "all", "_" }
```
