### ISSUE TITLE
[Feature Request] Way to directly jump to $0

### ISSUE THREAD

**Issue by hiberabyss** [L3MON4D3/LuaSnip#562]
Sometimes, I want to keep all things as default and jump to the $0 position directly. Is this possible?

**Comment by leiserfg** [comment]
You can use 
```lua
function() while ls.jumpable(1) do ls.jump(1) end end
```
in a mapping.

**Comment by L3MON4D3** [comment]
Alternatively: expand snippets via
```lua
ls.snip_expand(snippet, {
	jump_into_func = function(snip)
		-- callback has to return the new current node.
		return snip.insert_nodes[0]
	end })
```

I'll extend `ls.expand` so options like this can be passed to `ls.snip_expand`

**Comment by L3MON4D3** [comment]
Ah, nvm that, you'll have to not just return the node, but also jump into it:
```lua
local util = require("luasnip.util.util")

jump_into_func = function(snip)
	izero = snip.insert_nodes[0]
	return util.no_region_check_wrap(izero.jump_into, izero, 1)
end
```
(Take this with a grain of salt, it depends on internal stuff I can't promise won't change (though it's unlikely))

**Comment by hiberabyss** [comment]
> 

This did not work if there is multiple snippets in same file. Won't end at current snip.

**Comment by hiberabyss** [comment]
> Alternatively: expand snippets via
> 
> ```lua
> ls.snip_expand(snippet, {
> 	jump_into_func = function(snip)
> 		-- callback has to return the new current node.
> 		return snip.insert_nodes[0]
> 	end })
> ```

@L3MON4D3 This seems only work when do the expand, how could I accomplish this after expanding?

**Comment by L3MON4D3** [comment]
Oh, you mean press a key -> jump completely to the end of the snippet?
Hmm, should be possible with an approach similar to @leiserfg's proposal, you'll just have to check if the currently active node is == `snip.insert_nodes[0]`

We do something like that [here](https://github.com/L3MON4D3/LuaSnip/blob/f893f4bc86dbc97e95a5506dcaad36a5328e0b37/lua/luasnip/init.lua#L539-L553).

What exactly is your usecase? Just jumping to the end of a snippet?
I'd like to understand the Why, because it would probably be better to include this in luasnip as implementing it properly depends on some internals.

**Comment by hiberabyss** [comment]
Yes, that's the case. Just with key to jump to snippet end.

Some snips have multiple tabstops, in some cases, will keep all tabstops as default, and jump to end to edit.

e.g. snip:

```
snippet for "My for with correct $0"
	for (int ${2:i} = 0; $2 < ${1:count}; $2${3:++}) {
		$0
	}
```

**Comment by hiberabyss** [comment]
Seems could be done with following lua function:

```
function snip_jump_end()
  local session = require("luasnip.session")
	local current = session.current_nodes[vim.api.nvim_get_current_buf()]
  local snip = current and current.parent.snippet or nil
  local end_node = snip.insert_nodes[0]

  while end_node and ls.jumpable(1) do
    local current = session.current_nodes[vim.api.nvim_get_current_buf()]
    if current == end_node then
      break
    end
    ls.jump(1)
  end
end
```

**Comment by L3MON4D3** [comment]
Oh nice, that doesn't even need as many internals as I thought, just the `insert_nodes[0]`, but that's very unlikely to be changed
