### ISSUE TITLE
Jumping from choice node to another node?

### ISSUE THREAD

**Issue by matteha** [L3MON4D3/LuaSnip#568]
I can't seem to jump from a choice node to the next node, only to the 2nd-next node.

I'd like to choose here between 'public/private' and then jump on to "TYPE" and continue typing there, and so on, but it doesn't seem to work unfortunately:

```
s("class2", {
			c(1, {
				t("public "),
				t("private "),
			}),
			t("class "),
			i(2, "TYPE"),
			t(" "),
		}),
```

Cycling in the choice node works fine with

```
lvim.builtin.cmp.mapping["<C-/>"] = cmp.mapping(function(fallback)
  if luasnip.choice_active() then
    -- "<Plug>luasnip-next-choice"
    luasnip.change_choice(1)
  end
  end, {
    "i",
    "s",
  })
```

and jumping between nodes works fine with

```
lvim.builtin.cmp.mapping["<Tab>"] = cmp.mapping(function(fallback)
  if jumpable(1) then
    luasnip.jump(1)
```

But I can't jump to the next node after cycling it.

It also won't let me 'jump back' to the choice node if I change the 'i' order. 

I've tried different keybindings but it doesn't seem to help. 

When I put it as this, however, I can jump to TYPE but it will skip the second choice node (or any other type of second node), not sure why this would be the case, but this is my hacky workaround for now.

```
s("class2", {
			-- Choice: Switch between two different Nodes, first parameter is its position, second a list of nodes.
			c(1, {
				t("public "),
				t("private "),
			}),
			t("class "),
			c(2, {
				t(""),
				t(""),
			}),
			i(3, "TYPE"),
			t(" ",""),
			i(4, "TYPE"),
			t(" "),
		}),
```

Thank you for all the work, this is an amazing plugin!

**Comment by L3MON4D3** [comment]
Mhmmmm, those work just fine for me :/
[here](https://github.com/L3MON4D3/Dotfiles/blob/b974253b38a53768f5a89e965b4f3b6744f65e5c/.config/nvim/lua/plugins/luasnip/init.lua#L87-L100) are my keymappings, maybe try if using them solves the problem for you

**Comment by matteha** [comment]
Thank you.

It actually has to do with how LunarVim (re)defines 'jumpable' in:

https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/core/cmp.lua

If I change 

```
if jumpable(1) then
    luasnip.jump(1)
```

into 

```
if luasnip. jumpable(1) then
    luasnip.jump(1)
```

It works normally

**Comment by L3MON4D3** [comment]
Ahh, okay :+1:
