### ISSUE TITLE
Limit when snippets are available (& compe preview)

### ISSUE THREAD

**Issue by gegoune** [L3MON4D3/LuaSnip#57]
Amazing plugin, thanks!

Is it possible to make snippet available only if triggered from the beginning of the line? I have tried:

```lua
ps({ name = "Conventional: build", trig = "^build", regTrig = true }, "build(${1:scope}): ${2:subject}")

```

But it does not seem to do what I want.

Also, is compe suppose to expand snippets in preview window? I only get to see this:
<img width="529" alt="Screenshot 2021-07-02 at 23 16 21" src="https://user-images.githubusercontent.com/69750637/124324379-85ffc100-db8b-11eb-8540-23f4eb32d6bf.png">

**Comment by leiserfg** [comment]
The snippet is listed by compe as its treating the trigger as a string not as a regex, to fix it the fix has to be on compe_luasnip (part of compe).
The preview does not render the snippet (keep in mind it can be a complex function) maybe we can add a flag to mark a snippet as safe and in that case use that to generate the definition automatically, but I'm not sure how good is that idea.

**Comment by gegoune** [comment]
For my use cases prerendering is very safe and vsnip was doing it so having that as an option would be nice.

**Comment by L3MON4D3** [comment]
> Is it possible to make snippet available only if triggered from the beginning of the line?

That should be possible by utilising the expand condition (which isn't available on lsp-parsed snippets, I'll look into adding that).
Take a look at [this snippet](https://github.com/L3MON4D3/Dotfiles/blob/master/.config/nvim/lua/snips.lua#L107), the first parameter after the nodes is a function, all parameters after that are passed to this function. Should be possible to change that up a little and get the snippet to only expand at the beginning of the line.
An alternative would be to set `wordtrig=true`, which at least prohibits expanding inside a word.

**Comment by L3MON4D3** [comment]
> The preview does not render the snippet (keep in mind it can be a complex function) maybe we can _add a flag to mark a snippet as safe_ and in that case use that to generate the definition automatically, but I'm not sure how good is that idea.

We could add a variable, maybe `rendered`, to the trig-table and read the rendered string from there. For lsp-snippets it could be set automatically when parsing, for lua snippets it'd have to be set manually until functionality to really render snippets is implemented.

**Comment by gegoune** [comment]
Ah, I guess I wasn't clear enough. Not only I would not want to expand those snippets unless trigger starts at the first character of the line, but would also not want to see them in compe in that case. Do you think that would be possible at all?

**Comment by leiserfg** [comment]
> Ah, I guess I wasn't clear enough. Not only I would not want to expand those snippets unless trigger starts at the first character of the line, but would also not want to see them in compe in that case. Do you think that would be possible at all?

It has to be done in compe, not here as it's the one filtering the snippets.

**Comment by L3MON4D3** [comment]
Ohhh interesting. If compe gets a new table on each completion-request that may be possible.

**Comment by L3MON4D3** [comment]
> > Ah, I guess I wasn't clear enough. Not only I would not want to expand those snippets unless trigger starts at the first character of the line, but would also not want to see them in compe in that case. Do you think that would be possible at all?
> 
> It has to be done in compe, not here as it's the one filtering the snippets.
True!

**Comment by L3MON4D3** [comment]
I'll look into it, but it may take a while as I'm a bit busy right now. But feel free to take a stab at this yourself, `Snippet:matches` contains the logic for checking if the user-condition is fulfilled, you'd have to modify the matching/filtering of snippets in compes' luasnip source.

**Comment by leiserfg** [comment]
Actually, I'm not sure if that's a good idea, because the idea of compe is to do a fuzzy search on the list of potential items, and if we use  `Snippet:matches`  it will only show snippets completely matching the current text. So it will be a good idea how other providers supporting regex  (if any) deal with that issue.

**Comment by L3MON4D3** [comment]
You're right, I was thinking about the small part that checks whether the condition-function is met, should've specified that :D
I'm a bit impartial about doing any filtering at all, the idea behind restricting when a snippet applies, for me, is to not expand it by chance. When using something like compe I'm, on purpose, selecting a snippet and expanding that (at least the way I use compe).
However as this filtering works(?) with vsnip and compe, maybe it's worth looking into.

**Comment by leiserfg** [comment]
I use it the same way, I only use regex triggers to make "smart snippets" (snippets with arguments) as I can always rely on compe to select the snippet I want.
@L3MON4D3  should we have a matrix/gitter/telegram... channel where we can talk instead of spamming github comments :smile: ?

**Comment by L3MON4D3** [comment]
Oh yeah, good idea :D
I created [a matrix room](https://matrix.to/#/%23luasnip:matrix.org)

**Comment by L3MON4D3** [comment]
> For my use cases prerendering is very safe and vsnip was doing it so having that as an option would be nice.

Check out #121, for now the docstring isn't available in compe, but you can give feedback on eg. the current textual representation if you like :)

**Comment by gegoune** [comment]
Oh, awesome, thanks! Will check when it's supported by cmp. :)
