### ISSUE TITLE
Is there any ways to remove `~` in snippet completion window?

### ISSUE THREAD

**Issue by NEX-S** [L3MON4D3/LuaSnip#570]
![image](https://user-images.githubusercontent.com/97107165/188034241-2b075740-c86a-4b95-9d09-aaa4e1b969dc.png)
I dont know if this it luasnip or cmp's problem, but I'm wondering how to remove the `~` in the completion window like `for ~` to `for`

**Comment by L3MON4D3** [comment]
That `for` seems to be a completion-item from `cmp-nvim-lsp` (the lsp source for cmp, I think that's what it's called).. better look around there, or test if it comes from the language-server (by testing different ones)
