### ISSUE TITLE
Problem with autosnippet cursor position

### ISSUE THREAD

**Issue by matthewsia98** [L3MON4D3/LuaSnip#573]
Running into a weird issue with this snippet.
```
s('sout', fmt([[
    System.out.println({});{}
    ]],
    {
        i(1, ''),
        i(0),
    })
 ),
```
Everything works properly if I change ```i(1, '') to i(1, ' ')```.

As you can see from the video, visually the cursor is in the wrong position, but anything I type is inserted in the correct position.

https://user-images.githubusercontent.com/71731492/188258204-e60d35fc-36e7-4c71-beb1-686507c0f464.mp4

**Comment by L3MON4D3** [comment]
Hmm that's weird, I have never encountered this before
Just for reference, on my end everything works just fine

https://user-images.githubusercontent.com/41961280/188260904-50673348-a122-48c4-9717-8777c8d70ba3.mp4

It's probably some timing-issue :|
Can you give me any more info, like
* When has this first happened (commit would be awesome)
* Does it happen with other snippets

**Comment by matthewsia98** [comment]
I just created this particular snippet right before opening the issue.
This doesn't happen with other snippets. Seems to only happen when the default input node text is an empty string.

Take this one for example:
```
s('test', fmt([[
    System.out.println({}!);{}
    ]],
    {
        i(1, ''),
        i(0),
    })
),
```

https://user-images.githubusercontent.com/71731492/188261276-16bf824f-f16e-4114-9bb7-9115555a9aff.mp4

**Comment by L3MON4D3** [comment]
> I just created this particular snippet right before opening the issue. This doesn't happen with other snippets. Seems to only happen when the input node default is an empty string and there isn't any text immediately after the input node?

Okay, mhmmmmmm
Could you show other autocommands registered on `TextChangedI` or `TextChangedP` (`:au TextChangedI/P`)? Maybe something else interferes..

**Comment by matthewsia98** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/71731492/188262750-138ad8da-58a3-483f-8bb3-51f4c0907616.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/71731492/188262767-9aa74292-7e72-4d3b-82ad-92c4ff536454.png">

**Comment by L3MON4D3** [comment]
Could you remove those (eg. cmp and indentBlankLine, the plugins), and see if it works then?

**Comment by matthewsia98** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/71731492/188279369-b58acd48-1cde-4582-ba81-5740fdd897e8.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/71731492/188279388-f1d12ab6-a2f9-45f8-8ca8-de155cf7e693.png">

That didn't do it.

https://user-images.githubusercontent.com/71731492/188279436-8f665ed1-bbfd-4ba6-9882-a5ab8288dff2.mp4

**Comment by L3MON4D3** [comment]
Okay, that was my last immediate idea.
Could you produce a MWE?

**Comment by matthewsia98** [comment]
I managed to find out the problem.
The problem only occurs when ```vim.o.concealcursor``` contains 'i' but I'm not sure why that is.

**Comment by L3MON4D3** [comment]
Oh yeah, that's it, good work :+1:
I guess some of the rendering-code in nvim changes when concealcursor contains `i`. I'll start looking for workarounds

**Comment by L3MON4D3** [comment]
Check `concealcursor_i_workaround`, it works on my end :D

**Comment by matthewsia98** [comment]
Yup that fixed it!

**Comment by L3MON4D3** [comment]
Nice
