### ISSUE TITLE
Custom snippets not working

### ISSUE THREAD

**Issue by Rekwass** [L3MON4D3/LuaSnip#574]
I copy pasted the snippets from the wiki, but it seems that I cannot select custom snippets.

Snippets imported from [rafamadriz/friendly-snippets](https://github.com/rafamadriz/friendly-snippets) works fine but not custom ones.

I don't have any error messages so either it loads them but they don't appear or it just simply ignores them.

I need your help, thank you

<img width="1440" alt="Screenshot 2022-09-04 at 11 55 44" src="https://user-images.githubusercontent.com/72019227/188307870-231573af-ae73-406e-8664-2dfbfd6ef45e.png">

OS: macOS Monterey 12.5.1
NVIM: v0.7.2

**Comment by L3MON4D3** [comment]
Mhm, that looks correct, how do you verify the snippets don't exist?
`:LuaSnipListAvailable` should show an up-to-date list of snippets available in the current buffer, loading and calling that in a `lua`-buffer should show the custom snippets

**Comment by Rekwass** [comment]
Entering the command shows the snippets but they are empty :/

<img width="1440" alt="Screenshot 2022-09-04 at 15 18 18" src="https://user-images.githubusercontent.com/72019227/188315610-44f4e084-e2f2-443b-87f0-5bafab235f65.png">

**Comment by leiserfg** [comment]
I think the `all.json` file is invalid, try removing the las `,`

**Comment by Rekwass** [comment]
Indeed it was the comma that made the all.json file invalid, Thank you, have a good day :)

**Comment by L3MON4D3** [comment]
I'll add logging to detect such errors, any day now :clown_face:

**Comment by MitaiDart** [comment]
I have a similar problem, can I describe it here or do I need to open a separate issue?
