### ISSUE TITLE
Snippets selection mode improvement issue

### ISSUE THREAD

**Issue by NEX-S** [L3MON4D3/LuaSnip#576]
I've been using LuaSnip for a while and got an idea for snippets selection mode

Use python snippets for example:
```c
# after we expand a for snippets, we got this ( [ ] is selected):
for [xxx_1] in [xxx]:
    ...
# now luasnip is selected in [xxx_1]
# if we press x, s, c, ... in selected [xxx_1] we will get x, s, c in that position, which is the expected behavior.
# if we press d, it will delete [xxx_1] and wont go into insert mode
# if we press <space>, nothing would happen, I think user will wish to insert a space in that place
```
it's little uncomfortable when we need to press d or <space> or other stuff in snippet, especially in this case
```c
for ( ; i < 10; i++ ) {            <--------------- we need space in first place holder
    ...
}

for ( distance = 0; distance < 10; distance ++) {                  <------------------- we need to press di to insert
    ....
}
```

after futher test, I found that is my mapping cause this
```lua
vim.keymap.set('v', 'd', '"dd', { noremap = true, silent = true})
vim.keymap.set('v', '<SPACE>', ';', { noremap = true, silent = true })
```

But I dont want to change my v mapping, so I'm wondering if luasnip can add a feature that will unmap all visual mode mapping when in the snippets.

Best wishes!

**Comment by leiserfg** [comment]
Try mapping to `s` mode instead of `v` so you don't clutter/mess up  your visual mode shortcuts.
