### ISSUE TITLE
Incorrect behavior with editing multiple sections at the same time

### ISSUE THREAD

**Issue by jrwrigh** [L3MON4D3/LuaSnip#582]
I'm not sure how exactly to describe the behavior, so here's a gif:
![neovim_latex_duplicatestuff](https://user-images.githubusercontent.com/20801821/188928098-72c1afd1-bf42-42dd-8645-e5a35a4b1f32.gif)

Narrating, I create a latex environment via an LSP snippet, create another environment inside that one. I then cut the inner environment, paste it again, and when trying to edit the outer environment, I get this weird duplication thing. This example is a bit contrived, but I've run into similar issues _constantly_ and the only way to break out of whatever bug is to exit out of it.

The example is using `mason`, `lspconfig`, `texlab`, `cmp`, and `LuaSnip`/`vsnip` (MWE config at the bottom of the issue).

I've narrowed it down to be a luasnip issue as if I swap over to using vsnip, I get this instead:
![neovim_latex_duplicatestuff_vsnip](https://user-images.githubusercontent.com/20801821/188929049-a6a32426-405f-4fb3-b19b-67a939582c06.gif)

Here's my (admittedly) large MWE config (partially stolen from telecope):

<details>
<summary>default.init.lua</summary>

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      { 'neovim/nvim-lspconfig', config = function()

        local capabilities = vim.lsp.protocol.make_client_capabilities()
        capabilities.textDocument.completion.completionItem.snippetSupport = true
        require('lspconfig')['texlab'].setup{
            capabilities = capabilities,
        }
      end
      },
      { "williamboman/mason-lspconfig.nvim" },
      { "williamboman/mason.nvim",
      config = function()
          require('mason').setup{}
        end,
      },
      { 'L3MON4D3/LuaSnip' },
      { 'hrsh7th/vim-vsnip' },
      { 'hrsh7th/cmp-nvim-lsp'},
      { 'hrsh7th/nvim-cmp', config = function()
        local cmp = require "cmp"
        cmp.setup {
          snippet = {
            expand = function(args)
              vim.fn["vsnip#anonymous"](args.body)
            end,
            -- expand = function(args)
            --   require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
            -- end,
          },

          mapping = {
            ['<CR>']  = cmp.mapping.confirm({ select = true }),
            ['<C-n>'] = cmp.mapping.select_next_item(),
            ['<C-p>'] = cmp.mapping.select_prev_item(),
          },

          sources = cmp.config.sources({
            { name = "nvim_lsp" },
            { name = "buffer" },
          }),
        }

      end},
    },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

vim.o.completeopt = 'menu,menuone,noselect'

```

</details>

**Comment by L3MON4D3** [comment]
Ah, try setting `delete_check_events`, it's described a bit in the README.
Basically, luasnip does not automatically remove snippets when they're deleted, but this option can be set to autocommands on which checks for deletion will be performed (and the snippet properly removed)

(the reason for the duplication is that (after deletion!) the region of the to-be-copied placeholder spans the entire latex-environment, and anything inside this region is copied, sooo we end up with... that :sweat_smile:)

**Comment by jrwrigh** [comment]
Yep, that worked. Thanks!

Any reason that's not set by default?

**Comment by jrwrigh** [comment]
Actually, that doesn't completely solve the behaviors I'm seeing. I'll try and catch myself next time I run into it to see what I do to cause it. But this (possibly) different pathology has the side affect that I can't undo (`u`) out of it. In fact, pressing `u` just increases:
![neovim_latex_duplicatestuff_undo](https://user-images.githubusercontent.com/20801821/189023075-48a38da7-187a-4a3a-8219-ef0338bf270c.gif)

Here I'm pressing `u`, but the action counter only goes up and nothing changes.

**Comment by L3MON4D3** [comment]
> Yep, that worked. Thanks!
> 
> Any reason that's not set by default?

Originally because I thought having some not-trivial function run every `TextChanged`(which is the minimum required to have this work at all) would be annoying, but this issue is not uncommon, so it might be time to reevaluate that

**Comment by L3MON4D3** [comment]
> Actually, that doesn't completely solve the behaviors I'm seeing. I'll try and catch myself next time I run into it to see what I do to cause it. But this (possibly) different pathology has the side affect that I can't undo (`u`) out of it. In fact, pressing `u` just increases: ![neovim_latex_duplicatestuff_undo](https://user-images.githubusercontent.com/20801821/189023075-48a38da7-187a-4a3a-8219-ef0338bf270c.gif) [ ![neovim_latex_duplicatestuff_undo](https://user-images.githubusercontent.com/20801821/189023075-48a38da7-187a-4a3a-8219-ef0338bf270c.gif) ](https://user-images.githubusercontent.com/20801821/189023075-48a38da7-187a-4a3a-8219-ef0338bf270c.gif) [ ](https://user-images.githubusercontent.com/20801821/189023075-48a38da7-187a-4a3a-8219-ef0338bf270c.gif)
> 
> Here I'm pressing `u`, but the action counter only goes up and nothing changes.

Okay that one I've never seen before, could you open a new issue if you can reproduce it?

**Comment by L3MON4D3** [comment]
> > Originally because I thought having some not-trivial function run every `TextChanged`(which is the minimum required to have this work at all) would be annoying, but this issue is not uncommon, so it might be time to reevaluate that
> 
> I'm not super familiar with nvim backend stuff, but you could always have the function run async for every `TextChanged` event, with it blocking any luasnip command until it checks for deleted snippets..

Mhmmm, that's a nice approack for optimizing this.. Do you know of some way to get mutexes in lua? (I guess those would be necessary to reliably block other commands)

**Comment by jrwrigh** [comment]
> Do you know of some way to get mutexes in lua?

Nope. haha. I'm just familiar with parallel programming, nothing neovim specific (other than I know it can launch tasks asynchronously).
