### ISSUE TITLE
VSCode choice snippet not showing choices

### ISSUE THREAD

**Issue by tinny-blueleo** [L3MON4D3/LuaSnip#585]
Hey friends!

I have a VSCode snippet that should toggle between a local and global function in typescript:

` "function": {
        "prefix": [
            "fn"
        ],
        "body": [
            "${1|const,export const|} $2 = ($3)$4 => {",
            "\t$5",
            "}\n$0"
        ]
    },
`
However when I expand the snippet only the first choice is used and there's no dropdown to toggle between the choices.  Anyone know how to work around this with VSCode snippets?

**Comment by tinny-blueleo** [comment]
Works great, thank you!

**Comment by L3MON4D3** [comment]
Nice, you're welcome :)
