### ISSUE TITLE
[Question] Getting error

### ISSUE THREAD

**Issue by TornaxO7** [L3MON4D3/LuaSnip#590]
Hello! I'd like to use [`toggletasks.nvim`](https://github.com/jedrzejboczar/toggletasks.nvim) which always needs a `toggltasks.json` with the same pattern to write tasks:

```json
{
    "tasks": [
        {
            "name": "task name",
            "cmd": "the command which has to be executed"
        }
    ]
}
```

Now I have the following snippet file:
```lua
local ls = require "luasnip"
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
local r = ls.restore_node
local events = require("luasnip.util.events")
local ai = require("luasnip.nodes.absolute_indexer")

local add_task = function(prefix)
    return {
        t({
            prefix .. '{',
            prefix .. '\t"name": "',
        }),
        i(1),
        t({
            '",',
            prefix .. '\t"cmd": "',
        }),
        i(0),
        t({
            '"',
            prefix .. '}'
        })
    }
end


return {
    s("de", {
        t({
            '{',
            '\t"tasks": [',
        }),
        add_task("\t\t"),
        t({
            '\t]',
            '}'
        }),
    }),
    s("t", add_task("")),
}
```

My `t` snippet works fine, I'm getting the expected
```json
{
    "name": "",
    "cmd": ""
}
```
snippet, but if I execute the `de` (which should mean `default`) snippet, I'm
getting the following error:
```
Error executing vim.schedule lua callback: .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:824: attempt to call method 'indent' (a nil value)
stack traceback:
	.../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:824: in function 'indent'
	.../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:711: in function 'fake_expand'
	.../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:775: in function 'get_docstring'
	...e/pack/packer/start/cmp_luasnip/lua/cmp_luasnip/init.lua:35: in function 'get_documentation'
	...e/pack/packer/start/cmp_luasnip/lua/cmp_luasnip/init.lua:119: in function 'resolve'
	.../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:363: in function 'resolve'
	...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:484: in function 'resolve'
	...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/view.lua:234: in function 'fn'
	.../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:55: in function <.../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:53>
```
do you have an idea what I'm doing wrong?

**Comment by L3MON4D3** [comment]
Lol, just checked my mail xD

Ah, the problem is that `add_task` just returns a table of nodes, which is not allowed at that point (`s` expects just a flat list/table of nodes).
I'd recommend wrapping `add_task`'s nodes in a snippetNode before returning, downside is that the `i(0)` will be ignored (`i(0)` have to be children of the outer snippet itself).
Another solution: merge the three tables (nodes before add_task, nodes from add_task, nodes after add_task) into one list before passing it to `s`.

**Comment by TornaxO7** [comment]
> Lol, just checked my mail xD

<https://www.youtube.com/watch?v=Oxqcoqf8Whs>

> Ah, the problem is that add_task just returns a table of nodes, which is not allowed at that point (s expects just a flat list/table of nodes).

Ah, ok. Thank you for the information!

> Another solution: merge the three tables (nodes before add_task, nodes from add_task, nodes after add_task) into one list before passing it to s.

I think I'll go with this one. Thank you for your (very fast) help! c(^-^)c

**Comment by L3MON4D3** [comment]
> https://www.youtube.com/watch?v=Oxqcoqf8Whs

Hah! :D

> I think I'll go with this one. Thank you for your (very fast) help! c(^-^)c

You're welcome :D
