### ISSUE TITLE
Pass lua snip nodes to parse

### ISSUE THREAD

**Issue by cnut1648** [L3MON4D3/LuaSnip#598]
Hi, I'd like to try out your plugin but faced some difficulties.
The doc mentioned LuaSnip snippets are made of nodes, but I couldn't find an example of loading those snippets.
I have the following in my `tex.lua`:

```lua
local rec_ls
rec_ls = function()
	return sn(nil, {
		c(1, {
			-- important!! Having the sn(...) as the first choice will cause infinite recursion.
			t({""}),
			-- The same dynamicNode as in the snippet (also note: self reference).
			sn(nil, {t({"", "\t\\item "}), i(1), d(2, rec_ls, {})}),
		}),
	});
end


return {
  parse("item",
    s("ls", {
      t({"\\begin{itemize}",
      "\t\\item "}), i(1), d(2, rec_ls, {}),
      t({"", "\\end{itemize}"}), i(0)
    })
  ),
}
```
But this gets an error saying 
```
vim/shared.lua.0: s: expected string, got table
```
The doc says `parse` is [this function](https://github.com/L3MON4D3/LuaSnip/blob/69cb81cf7490666890545fef905d31a414edc15b/lua/luasnip/config.lua#L102) but I couldn't figure out how to correctly use it.

Thanks!

**Comment by zjp-CN** [comment]
I think the syntax for parse is `parse("trigger text", "expansion")`, not  `parse("trigger text", node)`. And the `expansion` is
* `"plain text"`
* or interpolation e.g. `"$1 is ${2|hard,easy,challenging|}"`

And to return a node, just assign it to a variable and add to the table returned. So you should write:
```lua
-- you don't need to import s, i, d, etc.
local ls = s("ls", {
      t({"\\begin{itemize}",
      "\t\\item "}), i(1), d(2, rec_ls, {}),
      t({"", "\\end{itemize}"}), i(0)
})

return { ls }
```

**Comment by L3MON4D3** [comment]
Oh, about parsing, check [the doc](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lsp-snippets), adding snippets is described a bit in the [Readme](https://github.com/L3MON4D3/LuaSnip#add-snippets)

**Comment by cnut1648** [comment]
Thanks! @L3MON4D3 @zjp-CN !!
