### ISSUE TITLE
Provide a way for accessing the  captures of the  trigger  from inside of the snippet

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#6]
That will allow, for instance, to implement  a snippet like 
lorem ->   full lorem ipsum
lorem20 -> first 20 chars of lorem ipsum

It could be the result of regex.match as a table if it's a regex snippet or  {trigger}  if it's not.

**Comment by L3MON4D3** [comment]
Snippet.trigger is actually replaced with the trigger-text upon expanding, but until now there was no way to actually get that text from inside a function-node :sweat_smile:.
With the latest commit, the snippet is appended to the first table passed to the user-function, example [here](https://github.com/L3MON4D3/LuaSnip/blob/238b0db5c0a7691793a0993e439c393803f768b6/Examples/snippets.lua#L148)

**Comment by leiserfg** [comment]
IMHO if the trigger is a regex, then Snippet.trigger should be the match and not just the raw trigger, so one can use the captures.

**Comment by leiserfg** [comment]
This is what I'm trying to replicate
https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L62-L68

**Comment by L3MON4D3** [comment]
Ahh, I see, my idea was that you can get the trigger-text and then match it again inside the function to get the captures you need.
But I see that that is quite cumbersome and your suggested approach would also be more in line with other snippet-plugins, I'll get on implementing that.

**Comment by L3MON4D3** [comment]
Okay, take a look [here](https://github.com/L3MON4D3/LuaSnip/blob/37a4767c568df797d9761dcf975f37b99251ff93/Examples/snippets.lua#L154-L158), it should work now.
