### ISSUE TITLE
Is this plugin as feature rich as UltiSnips?

### ISSUE THREAD

**Issue by paniash** [L3MON4D3/LuaSnip#60]
Hi! 

Thanks for making a lua snippet engine for neovim! I was wondering if this plugin is as feature rich as UltiSnips. 

Thanks!

**Comment by L3MON4D3** [comment]
I think most stuff you'd want to do with UltiSnips is also doable in LuaSnip.
Do you have any specific featured in mind?

**Comment by paniash** [comment]
@L3MON4D3 Thanks for the quick response! I currently use UltiSnips and wondering if I would get some kind of feature or performance boost on switching to LuaSnip.

**Comment by L3MON4D3** [comment]
Well, performance for sure (at least it was for me), LuaSnip has history (going back into left snippets with them staying interactive) and choices (but any node instead of just text, you could eg. collapse entire snippets including tabstops).
So more 'power-user' features mostly, we're a bit lacking when it comes to compatibility with completion engines, if you want to complete lsp-snippets `nvim-compe` is the only option.

**Comment by leiserfg** [comment]
The only feature I know from ultisnip, not present here is the post-rendering hook (I forgot the real name), that allows you to change the full snippet once it is completed ( when one goes to the input 0).

**Comment by L3MON4D3** [comment]
Oh yeah, any idea what they were intended for? I think I used them to expand anonymous snippets after the fact...

**Comment by leiserfg** [comment]
I have only seen it used to implement emmet as a snippet (which I'm planning to do with luasnip) so it will be a "nice to have".

**Comment by L3MON4D3** [comment]
Interesting, at a first glance that seems doable, at least the 'getting snippet from abbreviation'-part (as long as emmet uses the same syntax as lsp)

**Comment by leiserfg** [comment]
it can be easily done without that feature if one just uses the emmet text as a trigger and replaces it with the output as a vscode snippet. But the idea of using the "rendered snippet hook" was to be able to make the expression editable, for instance.

My fully imagined usecase:

I register a  snippet with trigger let's say `ee`  mapping to  
```lua
{t"<--!", i{1}, t{" -->", "" }, d(emmet_logic, {1}), {0} }
```
There `emmet_logic` should be a function that generates the snippet matching `i{1}`, so one can go back and change it during the edition, once the user jumps to {0} the first 3 nodes are removed so only the emmet result stays.

I guess it can be implemented by having a  function that can modify the result of the render as a table just after it gets converted into text once the snippet finishes.

**Comment by leiserfg** [comment]
I revisited the `post_jump` doc of ultisnips and it's not similar to my proposal, it happens after the complete rendering, so it does not modify the pre-rendered snippet, but it can do whatever it wants including modifying the buffer or expanding a new anonymous snippet. I'm not sure which of the two approaches could be more useful as the expansion thingy can be easily replaced with a dynamic node, so the only use-case I have is modifying the buffer (or the snippet content) afterward.

**Comment by L3MON4D3** [comment]
> ```lua
> {t"<--!", i{1}, t{" -->", "" }, d(emmet_logic, {1}), {0} }
> ```
That's also what I was thinking of, I'm not sure if I would even put the '<--' and '-->', just an empty insertNode and then parse whatever is put in there on the first jump and delete the content of the i(0).
Of course the dynamicNode may be reset if one reenters the i(1), but it's possible to work around that as-is, it would be cleaner to have the option to just not replace the active snippet (eg. return nil from the dynNode-function).

**Comment by L3MON4D3** [comment]
That would be something nice to put in the `luasnip.functions`-table, it's waaayy to empty right now :D

**Comment by leiserfg** [comment]
The idea of adding the comment is to  make it valid HTML so it gets correctly highlighted, beside that until the post-hook gets implemented we can keep the comment there  :smile:

**Comment by L3MON4D3** [comment]
Ahh okay, makes sense :D

**Comment by surmish** [comment]
@L3MON4D3 Has anyone written C++ snippets in the format you have specified? I looked at friendly snippets but they're in a format used by some other manager. I couldn't navigate placeholders in the pasted snippet. Thanks for the plugin.

If there isn't a snippet repo, I'd love to maintain one for C/C++ and a couple of other languages.

**Comment by L3MON4D3** [comment]
I think having friendly snippets in your runtimepath (by eg. installing it) and calling some variation of the vscode load function should work fine.

**Comment by surmish** [comment]
I used the variation but end up getting a snippet which is not complete. Also it doesn't let me navigate through the placeholders. 

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <NL>        * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close('<C-E>')`)
  - OK: `compe#scroll` is mapped: (`i  <C-D>       * compe#scroll({ 'delta': -4 })`)
```

Consider this snippet
```json
  "class": {
    "prefix": "class",
    "body": [
      "class ${MyClass} {",
      "public:",
      "  ${MyClass}();",
      "  ${MyClass}(${MyClass} &&) = default;",
      "  ${MyClass}(const ${MyClass} &) = default;",
      "  ${MyClass} &operator=(${MyClass} &&) = default;",
      "  ${MyClass} &operator=(const ${MyClass} &) = default;",
      "  ~${MyClass}();",
      "",
      "private:",
      "  $1",
      "};",
      "",
      "${MyClass}::${MyClass}()",
      "{",
      "}",
      "",
      "${MyClass}::~${MyClass}()",
      "{",
      "}"
    ],
    "description": "Code snippet for class"
  },
```    
I end up getting this code inserted:
```cpp

class  {
public:
  ();
  ( &&) = default;
  (const  &) = default;
   &operator=( &&) = default;
   &operator=(const  &) = default;
  ~();

private:
  
};

::() {
}

::~() {
}
```
#### To Reproduce
```lua
  use 'L3MON4D3/LuaSnip' -- snippet-engine
  use 'rafamadriz/friendly-snippets'
  use 'hrsh7th/nvim-compe'
  require("luasnip/loaders/from_vscode").lazy_load({ paths = { "~/.local/share/nvim/site/pack/packer/start/friendly-snippets/snippets" } })  
```

What am I doing wrong here?

**Comment by L3MON4D3** [comment]
Luasnip implements lsp-snippets according to https://github.com/microsoft/language-server-protocol/blob/main/snippetSyntax.md, afaict there is no `MyClass` variable. You could change the first placeholder to `${1:MyClass}` and all subsequent ones to `$1`, I think that should be more like what you'd expect.

**Comment by leiserfg** [comment]
For your use case 
`require("luasnip/loaders/from_vscode").lazy_load()` has to work as well.

**Comment by surmish** [comment]
@L3MON4D3 Thanks. It seems friendly-snippets don't follow that format and are maybe meant to be used with vsnips (which I tried and it works almost correctly there, except for placeholder navigation)

Ultisnips had a forward and backward trigger to navigate the pasted snippet, what is the trigger key binding for LuaSnips? I couldn't find one in the documents though the word 'trigger' is mentioned a few times.

**Comment by leiserfg** [comment]
> Ultisnips had a forward and backward trigger to navigate the pasted snippet, what is the trigger key binding for LuaSnips? I couldn't find one in the documents though the word 'trigger' is mentioned a few times.

You have to set them, check the readme or my [dots](https://github.com/leiserfg/dots/blob/master/.config/nvim/lua/my/plugins/LuaSnip.lua) if and pick the one you prefer.




> Also, what format do you recommend the snippets be written in, for being fully compatible with LuaSnips? The format you developed or the VSCode one? Is there some github repo where I can find either of those snippets (C/C++)? I don't mind creating a repo, but don't want to repeat effort which others may have done.

It depends on how complex are the snippets you want, for simple one use vscode style, for those with logic you need to do it using lua.

**Comment by leiserfg** [comment]
If you only want c++ snippets try   with
```lua
use "kkonghao/snippet-dog"
```
instead of friendly snippets (seems like they are not that friendly :smile: )

**Comment by L3MON4D3** [comment]
> @L3MON4D3 Thanks. It seems friendly-snippets don't follow that format and are maybe meant to be used with vsnips (which I tried and it works almost correctly there, except for placeholder navigation)

Perhaps vsnip inserts an unknown variable by name, that would explain navigation not working.

**Comment by medwatt** [comment]
@L3MON4D3, is it possible to do automatic snippet triggering like in ultisnips ?

**Comment by L3MON4D3** [comment]
Oh, no not yet, but It's a good idea. Would you open an issue to track that?

**Comment by leiserfg** [comment]
Well, it is possible, just call the expansion on a custom event :smile:

**Comment by L3MON4D3** [comment]
Could make that into a benchmark, expand a snippet where the cursor ends up behind the (unchanged)trigger and keep triggering. 'Expansions/second' xD

**Comment by timoleistner** [comment]
Is there any way to support UltiSnips format? I presume not as they often contain python code...
Still it would be nice as I currently have a 1000 lines latex snippets file which I would have to rewrite :frowning:..

**Comment by L3MON4D3** [comment]
Ouf, yeah I get that, but full compatibility won't be possible/will require a lot of work.
As far as I remember the overlap between lsps' and ultisnips' syntax is pretty big, you could try doing some `sed`-magic to convert the ultisnips-files to the vscode-package-format (see [here](https://github.com/rafamadriz/friendly-snippets)) and then manually fix the ones with python-interpolation. That would save you at least a bit of effort with the simple snippets.
