### ISSUE TITLE
carriage return symbol in jdtls lsp snippets

### ISSUE THREAD

**Issue by hi-euu** [L3MON4D3/LuaSnip#602]
when i'm using luasnip to expand java jdtls snippets on windows 11, it keep showing carriage return symbol ^M
![image](https://user-images.githubusercontent.com/94734700/190842290-e3af4be8-1841-4cd5-84ea-c8dd6f8de6ef.png)
![image](https://user-images.githubusercontent.com/94734700/190842311-6d74de62-c787-4f3e-8fcd-2098be406816.png)

i try `set ff=unix` , this fixed, but i have to create auto command to set java filetype to unix.
when i add `body = body:gsub('\r\n', '\n')` to line 34 luasnip/util/parser/init.lua, this 'maybe' fixed

**Comment by L3MON4D3** [comment]
Ahh I see :/
Do any other language-servers also send `\r\n`?

Could you make sure branch `windows-😐` works?

**Comment by hi-euu** [comment]
😊 it works.
maybe only jdtls send \r\n
even it's hover float text still have ^M symbol :v
[https://github.com/neovim/neovim/issues/18293](url)
