### ISSUE TITLE
Question: Repeat snippet unknown number of times

### ISSUE THREAD

**Issue by levouh** [L3MON4D3/LuaSnip#605]
Looking to do something like the following (asked a similar question in the past but never really got it working):

```lua
  s("trig", {
    t("print('DBGSTR => "),
    f(function(args, parent, usr)
      return args[1][1] .. "=%s"
    end, { 1 }),
    t("', "),
    i(1),
    t(")"),
  }),
```

where I can do exactly what this snippet does, but many times over. E.g. I can start a snippet, and have:

```lua
print('DBGSTR => ', |)
```

(where `|` is the cursor position). Then I can type `one`, and get:

```lua
print('DBGSTR => one=%s', one, |)
```

then press something like `<C-l>` (which does something like `require("luasnip").expand_or_jumpable()`) and then get a "new iteration" of the same snippet(s) again, so I can type `two` and get:

```lua
print('DBGSTR => one=%s two=%s', one, two, |)
```

and then something else to "stop" the snippet repeating when I am done.

---

Took a look through `DOC.md` a few times and don't see anything that would help with this as everything like `dynamic` nodes, etc. are all given a specific "index" (i.e. cannot be repeated).

**Comment by L3MON4D3** [comment]
Sounds like a good fit for [external update-dynamicNode](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#dynamicnode-with-user-input), they build on dynamicNode, but allow input besides insertNode-text.
You could use two actions, one to decrease the number of arguments, and another to increase it.

Actually, you could also just parse the text from `i(1)`, extract arguments (`one`, `two`) and use those to generate the format-string.

**Comment by levouh** [comment]
> Sounds like a good fit for [external update-dynamicNode](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#dynamicnode-with-user-input), they build on dynamicNode, but allow input besides insertNode-text.
> You could use two actions, one to decrease the number of arguments, and another to increase it.
> 
> Actually, you could also just parse the text from `i(1)`, extract arguments (`one`, `two`) and use those to generate the format-string.

The main problem with using an `insert` node is that I then have to parse the text to know what is what. In some cases, I might want to format in the output of `one, foo(two, three)`. Definitely something that can be done with treesitter, but it seems easier to just have keys to be explicit about it.

I will look at your suggestion @L3MON4D3 unless you have any more input based on my clarifications.

**Comment by levouh** [comment]
My use-case seems no where near as complicated as the example you linked, but what I have so far is:

```lua
local ls = require("luasnip")
local d = ls.dynamic_node
local f = ls.function_node
local i = ls.insert_node
local p = require("luasnip.extras").partial
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local fmt = require("luasnip.extras.fmt").fmt
local r = ls.restore_node

local node_count = 1
_G.change_node_count = function(val)
  node_count = math.max(node_count + val, 1)
end

local fmt_str = function(args, snip)
  -- TODO: Need to index at the right "current node" value rather than [1] here
  return sn(nil, { t(args[1][1] .. "=%s") })
end

local fmt_vals = function(args, snip)
  local insert_nodes = {}
  for num = 1, node_count do
    table.insert(insert_nodes, i(num))
  end
  return sn(nil, insert_nodes)
end

s(
  "dbg",
  fmt([[printf("DBGSTR => {}", {});]], {
    d(1, fmt_str, { 2 }, {}),
    d(2, fmt_vals, {}, {}),
  })
)

vim.api.nvim_set_keymap("i", "<C-e>", "<cmd>lua _G.change_node_count(1)<Cr>", { noremap = true })
vim.api.nvim_set_keymap("s", "<C-e>", "<cmd>lua _G.change_node_count(1)<Cr>", { noremap = true })

vim.api.nvim_set_keymap("i", "<C-g>", "<cmd>lua _G.change_node_count(-1)<Cr>", { noremap = true })
vim.api.nvim_set_keymap("s", "<C-g>", "<cmd>lua _G.change_node_count(-1)<Cr>", { noremap = true })
```

which works fine for the first value, however I'm not sure how to make my mappings (`<C-e>`, and `<C-g>`) call `_G.change_node_count` and then update the number of insert nodes returned by the 2nd dynamic node. Is there a way to do this @L3MON4D3?

There is also a `TODO` above as in the first dynamic node I am always returning the text of the first portion of the dependent dynamic node, however I can fix this once I get the aforementioned part working.

**Comment by levouh** [comment]
Ended up here:

```lua
local ls = require("luasnip")
local d = ls.dynamic_node
local f = ls.function_node
local i = ls.insert_node
local p = require("luasnip.extras").partial
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local fmt = require("luasnip.extras.fmt").fmt
local r = ls.restore_node
local node_util = require("luasnip.nodes.util")

local function find_dynamic_node(node)
  -- the dynamicNode-key is set on snippets generated by a dynamicNode only (its'
  -- actual use is to refer to the dynamicNode that generated the snippet).
  while not node.dynamicNode do
    node = node.parent
  end

  return node.dynamicNode
end

local node_count = 1
_G.change_node_count = function(val)
  node_count = math.max(node_count + val, 1)

  local current_node = ls.session.current_nodes[vim.api.nvim_get_current_buf()]
  local dynamic_node = find_dynamic_node(current_node)

  dynamic_node.last_args = nil
  dynamic_node:update()
end

local fmt_str = function(args, snip)
  -- TODO: Need to index at the right "current node" value rather than [1] here
  return sn(nil, { t(args[1][1] .. "=%s") })
end

local insert_nodes = {}
local fmt_vals = function(args, snip)
  -- TODO: Handle removing nodes at some point once adding works
  for num = #insert_nodes + 1, node_count do
    table.insert(insert_nodes, i(num))
  end

  return sn(nil, insert_nodes)
end

s(
  "dbg",
  fmt([[printf("DBGSTR => {}", {});]], {
    d(1, fmt_str, { 2 }, {}),
    d(2, fmt_vals, {}, {}),
  })
)

vim.api.nvim_set_keymap("i", "<C-e>", "<cmd>lua _G.change_node_count(1)<Cr>", { noremap = true })
vim.api.nvim_set_keymap("s", "<C-e>", "<cmd>lua _G.change_node_count(1)<Cr>", { noremap = true })

vim.api.nvim_set_keymap("i", "<C-g>", "<cmd>lua _G.change_node_count(-1)<Cr>", { noremap = true })
vim.api.nvim_set_keymap("s", "<C-g>", "<cmd>lua _G.change_node_count(-1)<Cr>", { noremap = true })
```

which does not really do much beyond the previous version. It does iterate in that it _seems_ like at least a new `insertNode` is being added, as I now get:

```
E5108: Error executing lua ...pack/packer/opt/luasnip/lua/luasnip/nodes/insertNode.lua:208: attempt to index field 'mark' (a nil value)                                                                                                        
stack traceback:                                                                                                                                                                                                                               
        ...pack/packer/opt/luasnip/lua/luasnip/nodes/insertNode.lua:208: in function 'exit'                                                                                                                                                    
        ...te/pack/packer/opt/luasnip/lua/luasnip/nodes/snippet.lua:926: in function 'exit'                                                                                                                                                    
        ...ack/packer/opt/luasnip/lua/luasnip/nodes/dynamicNode.lua:124: in function 'update'                                                                                                                                                  
        ...ier/.config/nvim/lua/user/pack/config/luasnip/ft/all.lua:33: in function 'change_node_count'                                                                                                                                        
        [string ":lua"]:1: in main
```

**Comment by levouh** [comment]
Looks like stuff on !328 might be somewhat related/usable as well. Will research what was done there too.

**Comment by atticus-sullivan** [comment]
Yes we discussed various approaches on this (quite similar topic) (so there is a lot to read in that issue).
I ended up working with choice nodes to decide if I want to add another entry (I didn't want to bind any new keys).
Just checked the snippet out once again (didn't work that much with python recently). Seams to be broken apparently due to some changes in luasnip I guess. I'll have to check this out the next days (and should update the snippet on the wiki)

**Comment by levouh** [comment]
I see the problem, at least with my attempts versus what is on #328.

What I'm trying to do here involves keeping old insert nodes (to keep the values input by the user), whereas the solution you mentioned @L3MON4D3 on the aforementioned issue always return a new set of nodes.

Is there any way to maintain the content of a previous insert node, such that when I hit `<C-t>` to increase the count, but not lose edits to already existing insert nodes?

**Comment by L3MON4D3** [comment]
> Is there any way to maintain the content of a previous insert node, such that when I hit <C-t> to increase the count, but not lose edits to already existing insert nodes?

Yeah!! `RestoreNode` :D
Best check the [doc](https://github.com/L3MON4D3/LuaSnip/blob/fmt_doc_improve/DOC.md#restorenode) (linking the better, not-yet-merged version of the doc), it has some examples+explaination

(You can also look at the table-snippet in the wiki, it has all the bells and whistles)

**Comment by L3MON4D3** [comment]
> I ended up working with choice nodes to decide if I want to add another entry (I didn't want to bind any new keys).

Yeah, choiceNodes also work for this usecase.

Generating new nodes on jump would be very comfortable, the downside is ofc. that we'd have a notion of `jump out` (as opposed to `jump next`) only for this one node.
On second thought, a general `jump out` might actually be useful, for example to quickly get out of deeply nested snippets... :thinking::thinking:

**Comment by L3MON4D3** [comment]
> Ended up here:
> 
> ```lua
> local ls = require("luasnip")
> local d = ls.dynamic_node
> local f = ls.function_node
> local i = ls.insert_node
> local p = require("luasnip.extras").partial
> local s = ls.snippet
> local sn = ls.snippet_node
> local t = ls.text_node
> local fmt = require("luasnip.extras.fmt").fmt
> local r = ls.restore_node
> local node_util = require("luasnip.nodes.util")
> 
> local function find_dynamic_node(node)
>   -- the dynamicNode-key is set on snippets generated by a dynamicNode only (its'
>   -- actual use is to refer to the dynamicNode that generated the snippet).
>   while not node.dynamicNode do
>     node = node.parent
>   end
> 
>   return node.dynamicNode
> end
> 
> local node_count = 1
> _G.change_node_count = function(val)
>   node_count = math.max(node_count + val, 1)
> 
>   local current_node = ls.session.current_nodes[vim.api.nvim_get_current_buf()]
>   local dynamic_node = find_dynamic_node(current_node)
> 
>   dynamic_node.last_args = nil
>   dynamic_node:update()
> end
> 
> local fmt_str = function(args, snip)
>   -- TODO: Need to index at the right "current node" value rather than [1] here
>   return sn(nil, { t(args[1][1] .. "=%s") })
> end
> 
> local insert_nodes = {}
> local fmt_vals = function(args, snip)
>   -- TODO: Handle removing nodes at some point once adding works
>   for num = #insert_nodes + 1, node_count do
>     table.insert(insert_nodes, i(num))
>   end
> 
>   return sn(nil, insert_nodes)
> end
> 
> s(
>   "dbg",
>   fmt([[printf("DBGSTR => {}", {});]], {
>     d(1, fmt_str, { 2 }, {}),
>     d(2, fmt_vals, {}, {}),
>   })
> )
> 
> vim.api.nvim_set_keymap("i", "<C-e>", "<cmd>lua _G.change_node_count(1)<Cr>", { noremap = true })
> vim.api.nvim_set_keymap("s", "<C-e>", "<cmd>lua _G.change_node_count(1)<Cr>", { noremap = true })
> 
> vim.api.nvim_set_keymap("i", "<C-g>", "<cmd>lua _G.change_node_count(-1)<Cr>", { noremap = true })
> vim.api.nvim_set_keymap("s", "<C-g>", "<cmd>lua _G.change_node_count(-1)<Cr>", { noremap = true })
> ```
> 
> which does not really do much beyond the previous version. It does iterate in that it _seems_ like at least a new `insertNode` is being added, as I now get:
> 
> ```
> E5108: Error executing lua ...pack/packer/opt/luasnip/lua/luasnip/nodes/insertNode.lua:208: attempt to index field 'mark' (a nil value)                                                                                                        
> stack traceback:                                                                                                                                                                                                                               
>         ...pack/packer/opt/luasnip/lua/luasnip/nodes/insertNode.lua:208: in function 'exit'                                                                                                                                                    
>         ...te/pack/packer/opt/luasnip/lua/luasnip/nodes/snippet.lua:926: in function 'exit'                                                                                                                                                    
>         ...ack/packer/opt/luasnip/lua/luasnip/nodes/dynamicNode.lua:124: in function 'update'                                                                                                                                                  
>         ...ier/.config/nvim/lua/user/pack/config/luasnip/ft/all.lua:33: in function 'change_node_count'                                                                                                                                        
>         [string ":lua"]:1: in main
> ```

Just looke through that, best don't change the `dynamic_node_external_update`-function: `store` is required for restoreNode to work (wait, why don't we do that in `dynamicNode`? I'll have a look, seems a bit weird), and it has some niceties (for example, it'll restore your cursor-position/selection after changing the number of nodes)

**Comment by L3MON4D3** [comment]
(looked at that `:store`, it can be removed from `dynamic_node_external_update` since  restoreNodes are stored in their `:exit`.
It ended up in that function because I copied large chunks of it from choiceNode, and _there_ the store is required, since exactly the same nodes may appear later(shouldn't (:P) happen with newly-generated dynamicNode-snippet), again, and we want to preserve entered text etc.)

**Comment by levouh** [comment]
Alright, I believe I _finally_ go it working like I want, dumping below as a reference for anyone interested in doing something similar:

```lua
local ls = require("luasnip")

local d = ls.dynamic_node
local fmt = require("luasnip.extras.fmt").fmt
local i = ls.insert_node
local node_util = require("luasnip.nodes.util")
local p = require("luasnip.extras").partial
local r = ls.restore_node
local rep = require("luasnip.extras").rep
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local util = require("luasnip.util.util")

local function find_dynamic_node(node)
  -- the dynamicNode-key is set on snippets generated by a dynamicNode only (its'
  -- actual use is to refer to the dynamicNode that generated the snippet).
  while not node.dynamicNode do
    node = node.parent
  end

  return node.dynamicNode
end

local external_update_id = 0
_G.dynamic_node_external_update = function(func_indx)
  local current_node = ls.session.current_nodes[vim.api.nvim_get_current_buf()]
  local dynamic_node = find_dynamic_node(current_node)

  external_update_id = external_update_id + 1
  current_node.external_update_id = external_update_id

  local insert_pre_call = vim.fn.mode() == "i"
  local cursor_pos_pre_relative = util.pos_sub(util.get_cursor_0ind(), current_node.mark:pos_begin_raw())

  node_util.leave_nodes_between(dynamic_node.snip, current_node)

  local func = dynamic_node.user_args[func_indx]
  if func then
    func(dynamic_node.parent.snippet)
  end

  dynamic_node.last_args = nil
  dynamic_node:update()

  local target_node = dynamic_node:find_node(function(test_node)
    return test_node.external_update_id == external_update_id
  end)

  if target_node then
    node_util.enter_nodes_between(dynamic_node, target_node)

    if insert_pre_call then
      util.set_cursor_0ind(util.pos_add(target_node.mark:pos_begin_raw(), cursor_pos_pre_relative))
    else
      node_util.select_node(target_node)
    end

    ls.session.current_nodes[vim.api.nvim_get_current_buf()] = target_node
  else
    ls.session.current_nodes[vim.api.nvim_get_current_buf()] = dynamic_node.snip:jump_into(1)
  end
end

local dbg = function(_, parent)
  local argc = parent.argc
  if not argc then
    parent.argc = 1
    argc = 1
  end

  local nodes = {}

  for j = 1, argc do
    vim.list_extend(nodes, { rep(j), t("=%s ") })
  end

  table.insert(nodes, t([[", ]]))

  for j = 1, argc do
    if j > 1 then
      table.insert(nodes, t(", "))
    end

    table.insert(nodes, r(j, "dyn" .. j, i(nil, "arg" .. j)))
  end

  table.insert(nodes, t(")"))

  return sn(nil, nodes)
end

s(
  "dbg",
  fmt([[print("DBGSTR => {}]], {
    d(1, dbg, {}, {
      user_args = {
        function(parent)
          parent.argc = parent.argc + 1
        end,
        function(parent)
          parent.argc = math.max(parent.argc - 1, 1)
        end,
      },
    }),
  })
)
```

---

https://user-images.githubusercontent.com/31262046/192066539-39af1acd-af55-4ce9-9981-bbebcdd77750.mp4

---

Thanks for the help, as always @L3MON4D3 :D
