### ISSUE TITLE
I created a script to have a somewhat better output for the LuaSnipListAvailable command

### ISSUE THREAD

**Issue by lefuturiste** [L3MON4D3/LuaSnip#607]
This is not a bug, it's a feature request. I just want to know if this change would be accepted as a pull request.

I'm using this awesome plugin but something was missing, when I use the command `:LuaSnipListAvailable` it just print the result to the screen and it's not really navigable (it's not a proper buffer).
I'm suggesting that instead of just printing the list, we could open a new buffer and put the list of snippet available here.
The advantages of a buffer are : syntax highlighting, navigation, normal mode...

I developed a little script to do that.

```lua
vim.api.nvim_create_user_command('SnipList', function ()
    -- Will create a read only buffer and show the description of all the snippets
    local res = vim.inspect(require'luasnip'.available())
    
    if win and vim.api.nvim_win_is_valid(win) then
        vim.api.nvim_set_current_win(win)
    else
        -- We open a new buffer
        vim.api.nvim_command('botright vnew')

        win = vim.api.nvim_get_current_win()
        buf = vim.api.nvim_get_current_buf()

        vim.api.nvim_buf_set_name(buf, "SnipList")

        vim.api.nvim_buf_set_option(buf, 'buftype', 'nofile')
        vim.api.nvim_buf_set_option(buf, 'swapfile', false)
        vim.api.nvim_buf_set_option(buf, 'bufhidden', 'wipe')

        vim.api.nvim_buf_set_option(buf, 'modifiable', true)
        vim.api.nvim_buf_set_option(buf, 'filetype', 'lua')
        -- Uncomment to disable numbers
        -- vim.api.nvim_set_option_value('number', false, { scope = "local" })
        -- vim.api.nvim_set_option_value('relativenumber', false, { scope = "local" })

        -- We set the buffer content
        vim.api.nvim_buf_set_lines(buf, 0, -1, false, mysplit(res, "\n"))
        vim.api.nvim_buf_set_option(buf, 'modifiable', false)
    end

end, {})
```

Since I'm never created a plugin and I'm new to neovim, I'm looking for feedback. If you want, I can create a PR.

**Comment by L3MON4D3** [comment]
Oh that's a great idea, very cool :+1:

Few thoughts:
* put in `luasnip.extras` (not sure if we want to completely replace the more simplistic `:LuaSnipListAvailable`, it _is_ rather useful for quickly checking whether snippets are available at all..)
* show docstrings?
* collapse filetypes/autosnippets?

PR very welcome :)

**Comment by lefuturiste** [comment]
Thanks for the feedback, I will work on the PR then. :grinning: 
I think the collapse by filetypes/autosnippets would be cool.
So I would create a new function in luasnip.extras probably named `open_snippets()` idk, but I would not necessarily call the available() function as I would need to separate by snippet/autosnippet type and  add others information like the `docstring`.

**Comment by lyonelz96** [comment]
@lefuturiste  @L3MON4D3 
Yo I actually just ran into this use case where I was looking for a the shortcut to a certain snippet but couldn't search it in the --More-- prompt haha. 

Since there hasn't been activity for about a month on this issue I would love to tackle this throughout this week and see if I can come up with something. Just going to wait for a response to see if there has been any progress.

Just in case can I ask you to clarify what do you mean by 

> show docstrings?
and 
> collapse filetypes/autosnippets?

**Comment by L3MON4D3** [comment]
Oh nice!
I agree, let's wait for @lefuturiste to give an update :D

"show docstrings" refers to listing a docstring (/textual approximation of the expanded snippet? Basically `s("trig", {i(1, "test"), t" test"})` -> `"${1:test} test"`) of each snippet. You can see an example of that if you use `cmp_luasnip`, and enable documentation.

"collapse filetypes/autosnippets" would be the idea to group snippets in categories snippet-type (regular vs autosnippets) and filetype, and then being able to collapse entire groups, for example all python-snippets.

**Comment by lefuturiste** [comment]
@lyonelz96 Well, you can go ahead and submit your code, I least my issue it may inspired it. :smile:

**Comment by lyonelz96** [comment]
@lefuturiste Sounds good, I might be a little busy this weekend but I'll give myself 1-2 weeks and see if I can come up with something

**Comment by lyonelz96** [comment]
@lefuturiste Just to let you know this was implemented in #652. You can probably close this issue now @L3MON4D3.

**Comment by L3MON4D3** [comment]
Yes, right!

**Comment by lefuturiste** [comment]
Thanks
