### ISSUE TITLE
Conditional snippets that don't satisfy conditions still appear in cmp menu

### ISSUE THREAD

**Issue by evesdropper** [L3MON4D3/LuaSnip#608]
Wanted to see if there was some VimTeX syntax issue I was missing when setting environment snippets, turns out I found something interesting with LuaSnip.

From this [VimTeX issue](https://github.com/lervag/vimtex/issues/2501) we have the following code which successfully produces a contextual snippet.
```lua
-- File: nvim/LuaSnip/tex.lua
-- Loaded using the LuaSnip Lua loader (`:help luasnip-lua`)

local tex = {}
tex.in_tikz = function()
  local is_inside = vim.fn['vimtex#env#is_inside']("tikzpicture")
  -- perhaps using both tests is redundant and only the is_inside[1] is needed?
  return (is_inside[1] > 0 and is_inside[2] > 0)
end
-- Not needed in the context of this question but perhaps useful
tex.in_mathzone = function() return vim.fn['vimtex#syntax#in_mathzone']() == 1 end
tex.in_text = function() return not tex.in_mathzone() end

-- Return snippets
return
{
  s({trig="tikztest"},
    {
      t("Works!"),
    },
    {condition = tex.in_tikz}
  ),
}
```
![image](https://user-images.githubusercontent.com/82856360/192484869-f17d168e-c9e5-4f7a-bf44-77ecf0ed00a6.png)

However, on completion menu the trigger still appears despite not fitting the condition, which confused me at first:
![image](https://user-images.githubusercontent.com/82856360/192484450-463d4717-247e-49b0-8392-91bc98e6f9d6.png)
![image](https://user-images.githubusercontent.com/82856360/192484470-c3e6254e-d937-42b6-a857-b96d3a826058.png)

Is there a way to fix this?

**Comment by L3MON4D3** [comment]
Ah, `condition` is only queried on manual expansion (via tab, for example).
To hide the snippets in cmps menu, you can use `show_condition` :)
(you can pass functions written as `show_condition` to `condition;, but not the other way round (cmp doesn't have the data for `condition` readily available, and would have to compute it first, which doesn't seem worth it, hence the separation))

**Comment by gennaro-tedesco** [comment]
I am running into a somewhat similar problem but I cannot manage to get the syntax right for `show_condition`: in particular I am trying to write a condition that only shows the snippet if a line is empty (simulating the beginning of line):
```lua
show_condition = function()
  return vim.api.nvim_get_current_line() ~= ""
end,
``` 
doesn't seem to work, and the documentation for it indicates:

> - `show_condition`: `f(line_to_cursor) -> bool`.

where it's unclear if `f` refers to a function node alias or to a function definition.

What would be the correct grammar to write a `show_condition` for empty lines?

**Comment by L3MON4D3** [comment]
Oh, the doc bit misleading, true: it should be a function, not a functionNode.
What isn't working about you example? Looks correct to me

**Comment by gennaro-tedesco** [comment]
> What isn't working about you example? 

The condition isn't being evaluated and applied; interestingly, even [the built-in](https://github.com/L3MON4D3/LuaSnip/blob/94f192cf5f0a1931b3035c2d8affdebec460968c/lua/luasnip/extras/conditions/show.lua#L7) doesn't seem to have effect. Must one specify `show_condition` together with `condition` or is the former sufficient? I tried to browse the examples file but couldn't find any relevant example.

**Comment by L3MON4D3** [comment]
Could you open a new issue and upload a video there?

**Comment by gennaro-tedesco** [comment]
I will do: I will double check that all the rest in my configuration is fine and prepare a minimally reproducible example.
