### ISSUE TITLE
[Conflict with smap keys] visual selected text not replaced if there exists smap keys

### ISSUE THREAD

**Issue by hiberabyss** [L3MON4D3/LuaSnip#611]
For the following example, I have `map f ...` mapping, when press `f`, the `void` text will still be there.

![image](https://user-images.githubusercontent.com/2898670/192948865-36c88f60-0de4-466b-a92d-0e00c8183c59.png)

**Comment by L3MON4D3** [comment]
Mhmm, you'll have to remove the `f`-mapping in SELECT-mode: 
* Either exclude the Select-mapping by using `map`s other than `map` (see `:h map-table`) or
* `sunmap` `f` explicitly (this seems cleaner)
