### ISSUE TITLE
Loading other snippet plugin

### ISSUE THREAD

**Issue by mosheavni** [L3MON4D3/LuaSnip#614]
There's this awesome source for snippets, how can I use it with LuaSnip?
https://github.com/phenomenes/ansible-snippets

Thanks.

**Comment by leiserfg** [comment]
They seem to be snipmate snippets so they could (in theory) be used.

**Comment by mosheavni** [comment]
This did the trick:

```lua
require('luasnip.loaders.from_snipmate').lazy_load()
```

Thanks!
