### ISSUE TITLE
lua lazy_load not working

### ISSUE THREAD

**Issue by petobens** [L3MON4D3/LuaSnip#617]
Consider the following minimal.lua file:
```lua
local fn = vim.fn

-- Ignore default config and plugins and define new dirs
local test_dir = '/tmp/nvim-minimal'
vim.opt.runtimepath:remove(fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(fn.expand('~/.local/share/nvim/site'))
vim.opt.runtimepath:append(fn.expand(test_dir))
vim.opt.packpath:append(fn.expand(test_dir))

-- Install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    packer_bootstrap = fn.system({
        'git',
        'clone',
        '--depth',
        '1',
        'https://github.com/wbthomason/packer.nvim',
        install_path,
    })
    vim.cmd([[packadd packer.nvim]])
end

-- Setup packer
local packer = require('packer')
packer.init({
    package_root = test_dir .. '/pack',
    compile_path = test_dir .. '/plugin/packer_compiled.lua',
})
packer.startup(function(use)
    use('wbthomason/packer.nvim')
    use({
        'L3MON4D3/LuaSnip',
        config = function()
            require('luasnip.loaders.from_lua').lazy_load({
                paths = { vim.fn.stdpath('config') .. '/snippets/' },
            })
        end,
    })
    if packer_bootstrap then
        packer.sync()
    end
end)
```
where  `vim.fn.stdpath('config') .. '/snippets/' ` is `/home/pedro/.config/nvim/snippets/` and contains a `python.lua` snippet file with:
```lua
local ls = require('luasnip')
local s = ls.snippet
local t = ls.text_node

s('trigger', { t('Wow! Text!') })
```

Now, as in the GIF, do
1. Open nvim loading this minimal.lua file
2. Open a python file such as `:e ~/Desktop/foo.py`
3. Run `:LuaSnipListAvailable` -> no python snippets are avaiable
4. Run `:lua require('luasnip.loaders.from_lua').edit_snippet_files()` -> a python snippet file is parsed

So for some reason my snippets (in python.lua file) are not being parsed/seen by LuaSnip despite being registed by `edit_snippet_files`. Any pointers are greatly appreciated.

![luasnip](https://user-images.githubusercontent.com/2583971/194595551-20501c55-9bcf-4865-982a-545bcd0f268f.gif)

**Comment by L3MON4D3** [comment]
Could you switch to the branch `logging`, call `require("luasnip.util.log").set_loglevel("warn")` and follow the content of `vim.fn.stdpath("log") .. "/luasnip.log"`? (to verify logging works, there should be a short message on startup)

**Comment by petobens** [comment]
Hi! Thanks for the quick reply. I've modified the packer part of the minimal.lua file  like so:
```lua
    use({
        'L3MON4D3/LuaSnip',
        branch = 'logging',
        config = function()
            require('luasnip.util.log').set_loglevel('warn')
            require('luasnip.loaders.from_lua').lazy_load({
                paths = { vim.fn.stdpath('config') .. '/snippets/' },
            })
        end,
    })
```
but `/home/pedro/.local/state/nvim/luasnip.log` only shows the following:
```
INFO  | New session: Sun 09 Oct 2022 09:30:03 AM -03
```
Snippets are correctly loaded for you with my minimal.lua file? (i.e you cannot reproduce my issue?)

**Comment by petobens** [comment]
I should've read this bit more closely https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lua

Writing now my snippets like so
```lua
local ls = require('luasnip')
local s = ls.snippet
local t = ls.text_node

return {
    s('a_snippet', { t('Test') }),
}, {}
```
Makes everything work as expected. Closing. Thanks for the help

**Comment by L3MON4D3** [comment]
Ohh haha, I didn't even look at the file, I think I misunderstood what you meant with "it showed".
Glad it works :+1:
