### ISSUE TITLE
please What is the difference between the fmt function and the add_snippet function 

### ISSUE THREAD

**Issue by yyy33** [L3MON4D3/LuaSnip#619]
and which one should I use to write my snippet. It looks like fmt is easier to use, does he have all the features of the latter?  tankyou

**Comment by L3MON4D3** [comment]
Oh, they are entirely different: `add_snippet(ft, snippets, opts)` adds a snippet to luasnip, `fmt` creates a table of nodes via interpolation (in a way).
I won't go into any detail here, I'd only reiterate what is much better explained in `DOC.md` (search for both `fmt` and `add_snippets`).
BUT! I'd recommend some other resource to get started with luasnip, there are some nice videos by tjdevries on youtube for example, the README contains some pointers

**Comment by yyy33** [comment]
> (nvm, readme doesn't have any resources, but look for "Resources" in [this comment](https://github.com/L3MON4D3/LuaSnip/discussions/545#discussioncomment-3439982))

thankyou

**Comment by hinell** [comment]
@L3MON4D3 Please, put this explanation to the docs under `API.md` file. Thanks.

**Comment by L3MON4D3** [comment]
I don't think we need a new file for those, maybe a `Overview` section in DOC.md would fit this better
