### ISSUE TITLE
Backspace / Delete exit insert mode

### ISSUE THREAD

**Issue by naquad** [L3MON4D3/LuaSnip#622]
NVIM v0.8.0
LuaJIT 2.1.0-beta3
LuaSnip: 80df2824d89f3c9c45d3b06494c7e89ca4e0c70e (master latest)

While in the placeholder, pressing the backspace or delete keys removes the text (expected) and leaves the insert mode (unexpected).  No messages or errors are displayed or logged.

Demo:
[![asciicast](https://asciinema.org/a/wrIpNNEOInDpD5AW4w1J0mibV.svg)](https://asciinema.org/a/wrIpNNEOInDpD5AW4w1J0mibV)

**Comment by L3MON4D3** [comment]
Weird, could you make sure you don't have any smap, vmap or map that include backspace?

**Comment by naquad** [comment]
> Weird, could you make sure you don't have any smap, vmap or map that include backspace?

That was my first thought, no there are no bindings containing `<bs>` or `<delete>`.
Does it reproduce on your setup?

**Comment by L3MON4D3** [comment]
Oh sorry, yeah that's the (unintuitive) default (see `:h select`).
However, a simple `snoremap <BS> <C-O>s` will make `<BS>` cut the SELECTed text (`<C-O>`: change to visual for one command)

**Comment by naquad** [comment]
Thank you, that has fixed the issue.
