### ISSUE TITLE
Multi line insert node?

### ISSUE THREAD

**Issue by rwblokzijl** [L3MON4D3/LuaSnip#626]
Right now, if i have a function node dynamically dependeny on an insert node it stops updating when i press enter. Is there a way (or is it possible to implement) to have an insert nodes accept newlines?

**Comment by L3MON4D3** [comment]
Oh, that should not happen, insertNodes can (should be able to) handle newlines..
Could you share the snippet this occurs with+a recording of what's going on on your side?

**Comment by rwblokzijl** [comment]
I did not test this in a fresh env. Let me know if you can't reproduce.
```lua
local ls  = require"luasnip"
local sn = ls.snippet_node
local ins = ls.insert_node
local fun = ls.function_node
local dyn = ls.dynamic_node

local fmt = require("luasnip.extras.fmt").fmt

local function expand()
  ls.snip_expand(
    ls.snippet(
      "box",
      dyn(1, function ()
        return sn("", fmt(
          "# Placeholder: {}\n" ..
          "# < {} >\n" ..
          ""
          ,
          {
            ins(1, "TEMP"),
            fun(duplicate, {1}),
          }
        ))
      end
      )
    )
  )
end

vim.keymap.set({'n', 'i'}, "<space><space>", function ()
  expand()
end, {noremap = true})
```

**Comment by L3MON4D3** [comment]
ahhh could you show `duplicate`? It's possible you're only copying the first line of the first argnode, and not the entire first argnode

I at least get the correct behaviour with
```lua
local function duplicate(args)
	return args[1]
end
```

**Comment by rwblokzijl** [comment]
ah, you're right. I didn't realize that would be split by lines. It works for me too now. Sorry for the inconvenience.

**Comment by L3MON4D3** [comment]
No worries! :)
