### ISSUE TITLE
About indent

### ISSUE THREAD

**Issue by yyy33** [L3MON4D3/LuaSnip#632]
hello L3MON4D3, I've been studying the source code of luasnip recently and have a question about indent,at `nodes/snippet.lua`
```
	local indentstring = util.line_chars_before(pos):match("^%s*")
	if vim.bo.expandtab then
		self:expand_tabs(util.tab_width(), #indentstring)
	end
	self:indent(indentstring)

```

Shouldn't it be changed to this? as the indentstring may also contain tabs
```
	local indentstring = util.line_chars_before(pos):match("^%s*")
	self:indent(indentstring)
	if vim.bo.expandtab then
		self:expand_tabs(util.tab_width(), #indentstring)
	end


```

**Comment by L3MON4D3** [comment]
Oh, good question:
`indentstring` is extracted from the buffer, so it already contains expanded tabs, and if they're not expanded, there's probably a reason for it (not sure what that reason could be though, if `expandtab` is on, there probably won't be any tabs in the buffer (?))

(at least `indentstring` in that function, there's a similar situation in the [`indentSnippetNode`](https://github.com/L3MON4D3/LuaSnip/blob/8fcf7357d245ae50260e5a7d94e08d1633727fb8/lua/luasnip/nodes/snippet.lua#L306-L326), where we have to be careful to selectively expand tabs in the passed `indent_text`, but not in the `parent_indent`, which is extracted from the buffer (or constructed by an outer/previous `indentSnippetNode`))
