### ISSUE TITLE
Always open the filetype snippet file when editing snippets

### ISSUE THREAD

**Issue by petobens** [L3MON4D3/LuaSnip#635]
Hi! I have the following mapping to edit snippets files:
```lua
u.keymap('n', '<Leader>es', function()
    require('luasnip.loaders').edit_snippet_files({
        edit = function(file)
            local split = 'split '
            if vim.fn.winwidth(0) > 2 * (vim.go.textwidth or 80) then
                split = 'vsplit '
            end
            vim.cmd(split .. file)
        end,
    })
end)
```
If  I use such mapping on a `.lua` file then I get  a dialog to select between `all` snippets and `lua` specific snippets:
```
Select filetype:
1: lua
2: all
Type number and <Enter> or click with the mouse (q or empty cancels):
```
Is there a way to always select by default the "filetype" file (in this case `lua`)? I want to avoid the dialog. 
Thanks in advance!

**Comment by L3MON4D3** [comment]
Oh, not yet possible, but should be a simple extension (`filter_filetypes` seems like a general approach) [here](https://github.com/L3MON4D3/LuaSnip/blob/61238b9e0efb315ceebe579dbcb6729a6b602e9f/lua/luasnip/loaders/init.lua#L22-L84)
Would you be interested in implementing that?

**Comment by petobens** [comment]
> Would you be interested in implementing that?

Unfortunately my lua skills are not quite up for the challenge. I wrote a simple function that fulfills my use-case (but is probably not general enough for others):
```lua
u.keymap('n', '<Leader>es', function()
    local snippet_file = vim.bo.filetype .. '.lua'
    if vim.bo.filetype == 'tex' then
        snippet_file = 'tex/' .. snippet_file
    end
    local split = 'split '
    if vim.fn.winwidth(0) > 2 * (vim.go.textwidth or 80) then
        split = 'vsplit '
    end
    vim.cmd(split .. snippets_dir .. snippet_file)
end)
```

**Comment by t4t5** [comment]
Here's what I'm using to quickly jump to the corresponding snippet file (based on my config path):

```lua
function openLuaSnipFile()
  local snippet_file = vim.bo.filetype .. '.snippets'
  local path = '~/dotfiles/config/lvim/luasnippets/' .. snippet_file
  vim.api.nvim_command("vsplit " .. path)
end
```
