### ISSUE TITLE
Partial match snippet triggering

### ISSUE THREAD

**Issue by petobens** [L3MON4D3/LuaSnip#636]
Suppose I have the following snippet
```lua
    s({ trig = 'snip' }, {
        t('snippet'),
        i(0),
    }),
```
and have set the following mapping to expand snippets:
```lua
u.keymap({ 'i', 's' }, '<C-s>', function()
    if luasnip.expandable() then
        luasnip.expand({})
    end
end)
```
If I type `snip` and then press `<C-s>` then the snippet indeed get expanded but if I type `sni` and press `<C-s>` there is no expansion. 
I was therefore wondering whether it's possible to expand the snippet when we partially match the snippet trigger. Thanks in advance!

**Comment by L3MON4D3** [comment]
Ouh, I don't think we want that, generally.
But for this case you could work with `regTrig` and create a pattern-trigger ("snip?")

**Comment by petobens** [comment]
Thank you! Makes sense
