### ISSUE TITLE
How do I use this plugin with ` hrsh7th/nvim-compe` and `rafamadriz/friendly-snippets`?

### ISSUE THREAD

**Issue by surmish** [L3MON4D3/LuaSnip#64]
Is there any step by step guide on how to set up LuaSnip. I just see one line in the README where it says `Snippets have to be added to the require'luasnip'.snippets-table.`, but couldn't make any progress with that.

**Comment by L3MON4D3** [comment]
Could you post your setup so far? Should be easier to help you that way :D

**Comment by surmish** [comment]
I copied the last line there

```lua
require("luasnip/loaders/from_vscode").lazy_load()
```

But see an error in luasnip when I navigate to the snipped in the list that shows up.

```
Error executing vim.schedule lua callback: .../pack/packer/start/nvim-compe/lua/compe_luasnip/init.lua:27: attempt to concatenate a table value
```

I also tried this (same nvim-compe error):
```lua
require("luasnip/loaders/from_vscode").lazy_load({ paths = { "~/.local/share/nvim/site/pack/packer/start/friendly-snippets" } })                                                                                                                   
```

**Comment by L3MON4D3** [comment]
Oh, I think that is the same as #63, so you could try my fork of nvim-compe until the PR is merged.

**Comment by surmish** [comment]
looks like this is the resolution: https://github.com/hrsh7th/nvim-compe/pull/457

**Comment by surmish** [comment]
I still can't select the snippet

![image](https://user-images.githubusercontent.com/33273194/124965294-d1c0c900-dfd6-11eb-8e2b-7607b45c7ef8.png)

I am not sure how to confirm the selection. Ctrl J, Y or any other key doesn't work. I tried arrow keys, shift, tab, they only complete the keyword, not the snippet associated with it.

**Comment by L3MON4D3** [comment]
Whoops, accidentially answered in friendly-snippets' [version of this issue](https://github.com/rafamadriz/friendly-snippets/issues/33)
