### ISSUE TITLE
How to avoid LSP errors

### ISSUE THREAD

**Issue by Integralist** [L3MON4D3/LuaSnip#640]
👋🏻 

Currently I see these warnings which are so noisey:

<img width="570" alt="Screenshot 2022-10-25 at 11 04 45" src="https://user-images.githubusercontent.com/180050/197745396-cfc831eb-c8fe-4119-b5b0-72674e5dd00c.png">

If I try to load the relevant code that provides these functions, I'll actually get an error loading the file:

<img width="591" alt="Screenshot 2022-10-25 at 11 04 25" src="https://user-images.githubusercontent.com/180050/197745516-1aa79032-027e-4ce0-b9f2-ebe65128dd95.png">

**Comment by leiserfg** [comment]
You can either import them by hand or tell sumneko they are global.

**Comment by L3MON4D3** [comment]
Exactly👍
Check [here](https://github.com/L3MON4D3/Dotfiles/blob/d00100eeae4459b8a76b0330dcc92b84716f4bea/.config/nvim/lua/plugins/lspconfig.lua#L172) for marking globals, you might also find some older discussions with other solution here or in the matrix-channel

**Comment by Integralist** [comment]
Aha, ok I figured it out...

```lua
local session = require("luasnip.session")

local env = session.config.snip_env
local s = env["s"]
local t = env["t"]
local i = env["i"]
local parse = env["parse"]

return {
  s({ trig = "co", name = "Constant", dscr = "Insert a constant" }, {
    t "const ", i(1, "name"), t " = ", i(2, "value")
  }),

  parse("pfmt", "fmt.Printf(\"%+v\\n\", )"),
}
```
