### ISSUE TITLE
`snip_env` does not include postfix by default

### ISSUE THREAD

**Issue by Samasaur1** [L3MON4D3/LuaSnip#643]
`DOC.md` assumes the following:
```lua
local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local isn = ls.indent_snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
local r = ls.restore_node
local events = require("luasnip.util.events")
local ai = require("luasnip.nodes.absolute_indexer")
local fmt = require("luasnip.extras.fmt").fmt
local extras = require("luasnip.extras")
local m = extras.m
local l = extras.l
local rep = extras.rep
local postfix = require("luasnip.extras.postfix").postfix
```
However, the actual default configuration of these shorthand vars is as follows:

https://github.com/L3MON4D3/LuaSnip/blob/69cb81cf7490666890545fef905d31a414edc15b/lua/luasnip/config.lua#L82-L104

It looks like everything is there except `postfix`, `extras`, and `isn`. Is there any reason why they have been left out? I think it would be easier to have the default configuration match the assumed configuration in the docs.

**Comment by L3MON4D3** [comment]
Oh, those matching (or at least being a superset of) the doc sounds like a good idea (I think? Can't really see downsides at least :D).
Feel free to do a PR to amend them (don't think #567 is going anywhere)
