### ISSUE TITLE
How to `Create new snippet with current selected text`

### ISSUE THREAD

**Issue by you-n-g** [L3MON4D3/LuaSnip#646]
Hi,
LuaSnip is really a great plugin.
Previously, I use  [coc-snippets](https://github.com/neoclide/coc-snippets#key-mappings)  based on `coc.nvim`.

But I didn't find the feature corresponds to  `<Plug>(coc-convert-snippet) Create new snippet with current selected text, visual mode only.`  

Could you please give me any guidance how to config to enable that feature?
Thanks.

**Comment by L3MON4D3** [comment]
Well, you can yank visually selected text into the `LS_SELECT_RAW` and `LS_SELECT_DEDENT`-variables by setting

```lua
require("luasnip").config.setup({store_selection_keys="<Tab>"})
```
and pressing tab when some text is selected, is that what you'd like to do?

Oh, nvm, I think I get what you mean: you can create a snippet from visually selected text via [On The Fly-snippets](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#on-the-fly-snippets). They support a slightly different syntax (less powerful, but more compact/faster to write), but it shouldn't be hard to adapt this (change `M._txt_to_snip` to `ls.parser.parse_snippet` [here](https://github.com/L3MON4D3/LuaSnip/blob/d56013c218deaf9c258f55e63847d24ad29bf643/lua/luasnip/extras/otf.lua#L79-L87))

**Comment by leiserfg** [comment]
When I created otf-snippets I thought about making them optionally generate a `fmt` that could be pasted, starting from the intermediate ast it should be easy to do.

**Comment by L3MON4D3** [comment]
Ouh, that's a cool idea, not sure if it's useful since `parse` takes care of authoring textmate-snippet with very little overhead, but cool :D

**Comment by you-n-g** [comment]
Thanks for your rapid response.
`coc-convert-snippet`  is not creating snippets on-the-fly.
It is just a shortcut to save the selected content to your   snippets **file** .
For example,  it appends the current selected content to files like `python.lua`/`python.json`/etc.

**Comment by L3MON4D3** [comment]
Ouh, okay that's a bit more complicated for luasnip.
The current way to quickly add a snippet would be `:LuaSnipEdit` (look for it in DOC.md, it can be used to open a dialog for editing sources for the current buffer) and then just appending the snippet. We support hot reload, so if you edit some snippet-file, its snippets will be updated in that neovim-instance

**Comment by you-n-g** [comment]
Finally, I use a  combination of operators to implement  "convert to snippet" for myself
https://github.com/you-n-g/deploy/blob/e53ef4bd066ee49a2dde879cf523f505ec8cff30/configs/nvim/lua/yx/plugs/which_key_conf.lua#L242

**Comment by L3MON4D3** [comment]
If it works it works👍👍
