### ISSUE TITLE
how do i load snippets from the current working dir

### ISSUE THREAD

**Issue by Senpai-10** [L3MON4D3/LuaSnip#649]
Some times i want custom snippets but i don't want them to load any where else
(project specific snippets )
i want to load them from `current working directory`

how do i do that?

**Comment by L3MON4D3** [comment]
Oh, you can, for example, call `require("luasnip.loaders.from_{lua,vscode,snipmate}").load({paths = {vim.fn.getcwd() .. "/.luasnippets"}})` on startup, or in some project-specific script.
