### ISSUE TITLE
A way to choice_node and function_node?

### ISSUE THREAD

**Issue by uga-rosa** [L3MON4D3/LuaSnip#65]
I want to choice as follows.
```
\left(  \right)
↓
\left\{  \right\}
↓
\left[  \right]
↓
```
So, I defined the following snippet.
```
    s("brackets", {
      t("\\left"),
      c(1, {t("("), t("\\{"), t("["),}),
      i(0),
      t("\\right"),
      f(close_bracket, 1),
    }),
```
The function close_bracket to get the corresponding parentheses, but I don't know how to write it...

**Comment by L3MON4D3** [comment]
`close_bracket` gets a table of tables of strings as its first argument, in your example it may be
```lua 
{{"("}} 
```
From there it should be easy to pick the closing parenthesis, eg. this table 
```
local open2closed = {["("] = ")",... }
local closing = open2closed["("]
```
should do it.

In function nodes, the outer table is for separating different nodes (in your case only the choiceNode), the inner strings are each a line (in most cases it's just one).

**Comment by uga-rosa** [comment]
Is `args[1]` the string to choice? The following didn't work...
```
local function close_bracket(args)
  local open2closed = {["("] = ")", ["["] = "]", ["\\{"] = "\\}"}
  return open2closed[args[1]]
end
```
return
```
.../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:379: bad argument #1 to 'ipairs' (table expected, got nil)\left(\right
```

**Comment by L3MON4D3** [comment]
`args[1]` is a table, not a string. `args[1][1]` should do it I think.

**Comment by uga-rosa** [comment]
It work fine!!!
Thanks for the great plugin.

**Comment by L3MON4D3** [comment]
:D
