### ISSUE TITLE
context-aware snippets don't work

### ISSUE THREAD

**Issue by xxCheatCodes** [L3MON4D3/LuaSnip#650]
I just created my math snippets for latex following the [wiki](https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#latex---context-aware-snippets). Snippets could be expanded in latex files as expected, but they expanded both in and out of math environments, which is not what I expected. It seems the context-aware snippets that the wiki mentions didn't work for me.

![image](https://user-images.githubusercontent.com/93426764/199743158-9fd5dc84-3edf-4938-9f7d-0b634caafa03.png)
![image](https://user-images.githubusercontent.com/93426764/199743627-5a1f6589-56ab-4094-a898-86059aef24ce.png)

```lua
local tex = {}
tex.in_mathzone = function ()
	return vim.fn['vimtex#syntax#in_mathzone']() == 1
end

tex.in_text = function ()
	return not tex.in_mathzone()
end
ls.add_snippets("tex",{

	s("sq", {
		t("\\sqrt"),
		t("{"),
		i(1),
		t("}"),
	}, { condition = tex.in_mathzone }),

	s("inf", {
		t("\\infty")
	}, { condition = tex.in_mathzone }),

	s("ti", {
		t("\\times")
	}, { condition = tex.in_mathzone }),

	s("lim", {
		t("\\lim \\limits_"),
		t("{"),
		i(1),
		t("}"),
	}, { condition = tex.in_mathzone }),
})
```
`vimtex#syntax#in_mathzone` worked properly in the latex files, it returned 1 in a math environment and 0 outside as expected.

Sorry for my poor English and unclear description since this is my first issue on github.

**Comment by leiserfg** [comment]
The `condition` won't stop it from appearing in the completion, it just stops it from being expanded, you wanna use `show_condition`

**Comment by xxCheatCodes** [comment]
> The `condition` won't stop it from appearing in the completion, it just stops it from being expanded. You wanna use `show_condition`.

The `condition` didn't stops it from being expanded neither

**Comment by xxCheatCodes** [comment]
I just replaced `condition` with `show_condition`, and it then worked properly. Thanks for your reply.
