### ISSUE TITLE
Regex in Snipmate format

### ISSUE THREAD

**Issue by alexanderflink** [L3MON4D3/LuaSnip#651]
Hello!

I use the Snipmate format to write my snippets. Is there a way to use a previous value but transform it with regex to make it uppercase? This is what I've tried so far, it seems the regex is simply discarded.

```snipmate
snippet rus "React useState"
  const [${1:state}, set${1/\w+/\u$0/g}] = React.useState($2)`
```

I'd like to avoid using the lua syntax if possible. Any way to use regex inside of a snipmate style snippet? Thanks!

**Comment by L3MON4D3** [comment]
Take a look [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#transformations), should do it

**Comment by alexanderflink** [comment]
Thanks! For visibility, I solved it by installing jsregexp manually using `luarocks --lua-version 5.1 install jsregexp` and moving `jsregexp.so` into my `~/.config/nvim/lua` directory.

**Comment by zzzachzzz** [comment]
@alexanderflink Would you mind sharing the final snippet that worked for you? Running yours, I get the output:
```
const [state, set\u] = React.useState()`
```

@L3MON4D3 I'm pretty sure I have jsregexp installed correctly. Using `use { "L3MON4D3/LuaSnip", run = "make install_jsregexp" }`, it seems to have worked since there was an output `LuaSnip/deps/jsregexp/jsregexp.so`. For good measure, I also symlinked that file to `~/.config/nvim/lua/jsregexp.so`.

**Comment by alexanderflink** [comment]
> @alexanderflink Would you mind sharing the final snippet that worked for you? Running yours, I get the output:
> 
> ```
> const [state, set\u] = React.useState()`
> ```
> 
> @L3MON4D3 I'm pretty sure I have jsregexp installed correctly. Using `use { "L3MON4D3/LuaSnip", run = "make install_jsregexp" }`, it seems to have worked since there was an output `LuaSnip/deps/jsregexp/jsregexp.so`. For good measure, I also symlinked that file to `~/.config/nvim/lua/jsregexp.so`.

Hey! Sorry for the late reply. Here is the final snippet that is working for me:

```
snippet rus "React useState"
  const [$1, set${1/(\w+)/${1:/capitalize}/}] = React.useState($2)
```
