### ISSUE TITLE
Snippets suddenly stopped working

### ISSUE THREAD

**Issue by rohitsrao** [L3MON4D3/LuaSnip#655]
My snippets were working fine until they suddenly stopped working. I have been unable to find any error messages and am at a loss to figure out what is going wrong.

It basically doesn't show up in my completion.

Here is my nvim [config](https://github.com/rohitsrao/nvim)

Could someone please help me out with this ?!

**Comment by L3MON4D3** [comment]
Hmm, that's tough, just stopped working without any changes? AFAICT you're only using loaded snippets, you could try the branch `logging` (for usage see #578) and see if that gives some hint

**Comment by L3MON4D3** [comment]
Oh no worries: log is located at `:lua =vim.fn.stdpath("log") .. "/luasnip.log"`, and best call `require("luasnip.util.log").set_loglevel("info")` to get most granularity

**Comment by rohitsrao** [comment]
Thanks. I did what you shared and found the log file. Doesn't seem to have recorded any error. 

Here is the output of `cat luasnip.log`

`
INFO  | New session: Wed 16 Nov 08:27:33 2022
INFO  | New session: Wed 16 Nov 08:28:27 2022
INFO  | New session: Wed 16 Nov 08:28:58 2022
INFO  | New session: Wed 16 Nov 08:29:27 2022
`

I tried the same flow with the dart file as I mentioned in my previous comment.

**Comment by rohitsrao** [comment]
Finally found my error. 

The log file showed a WARN - could not parse json in package.json

Was a missing comma in my package.json and an extra comma in html.json -.- 

Thanks a LOT for your time and apologies for the silly error. Feel free to delete the issue if you want.

**Comment by L3MON4D3** [comment]
Oh wow :facepalm: xD
Yeah, that's a classic, had it a few times myself (actually suspected it and took a look at your snippet-files, but didn't spot it :/ )

> Feel free to delete the issue if you want.

Hell no, I'm sure others will also encounter this exact issue, and in this case this will be very helpful.
