### ISSUE TITLE
Autosnippets not expanding automatically

### ISSUE THREAD

**Issue by Hneuschmidt** [L3MON4D3/LuaSnip#659]
I am setting up LuaSnip for my workflow and I can not get autosnippets to actually
expand automatically. Expanding by hand works fine.
I am probably looking at a silly mistake, where I overlooked something, but maybe you can help me.

This is the `init.lua`, inspired by [this article](https://www.ejmastnak.com/tutorials/vim-latex/luasnip.html): used to test this issue:

```
require("luasnip").config.setup({
    enable_autosnippets=true,
})

require("luasnip.loaders.from_lua").load({paths="~/.config/nvim/test_snippets/"})

-- setting up keys for expansion
vim.cmd([[
" Expand snippets in insert mode with Tab
imap <silent><expr> <Tab> luasnip#expandable() ? '<Plug>luasnip-expand-snippet' : '<Tab>'

" Jump forward in through tabstops in insert and visual mode with Control-f
imap <silent><expr> <C-f> luasnip#jumpable(1) ? '<Plug>luasnip-jump-next' : '<C-f>'
smap <silent><expr> <C-f> luasnip#jumpable(1) ? '<Plug>luasnip-jump-next' : '<C-f>'
" Jump backward through snippet tabstops with Shift-Tab (for example)
imap <silent><expr> <S-Tab> luasnip#jumpable(-1) ? '<Plug>luasnip-jump-prev' : '<S-Tab>'
smap <silent><expr> <S-Tab> luasnip#jumpable(-1) ? '<Plug>luasnip-jump-prev' : '<S-Tab>'
]])
```

and a single snippet in the snippet file `all.lua`:

```
return {
	s({trig="test", snippetType="autosnippet"},
		{t("just a test"),
		}
	)
}
```

which expands only when explicitly triggered with `<Tab>`.
What am I doing wrong?

**Comment by L3MON4D3** [comment]
Mhm, all of that looks correct..
Is your luasnip up-to-date?
Could you try returning the snippet as the second table, eg. `return {}, {s(...)}`? (that's the one originally for autosnippets, so this would remove snippetType being somehow wrong from this setup)

**Comment by Hneuschmidt** [comment]
Thank you for the response. Your comment enabled me to fix the issue, because
returning the snippet as second snippet did indeed work.

The silly mistake I overlooked was the following one:
While I made sure to have packer update my packages before, I had LuaSnip
fixed to a specific commit so it wouldn't update.
With the updated version my setup works.

Thank you for your help!

**Comment by L3MON4D3** [comment]
Ah, nice :+1:
You're welcome :D
