### ISSUE TITLE
Add "repeat" node with optional transform

### ISSUE THREAD

**Issue by clason** [L3MON4D3/LuaSnip#66]
One very common task in snippets is to insert the typed input in multiple places (possibly with a transformation), for example replacing whitespace with underscores to add a label or header guard. This can be done with a function or dynamic node, of course, but it's so common that I feel having this built-in would reduce boilerplate and make writing snippets much more convenient.

So my proposal would be to add a new node type "repeat node" that would look like 
```
r(1, {match = "[^.]+$", upper = true, gsub = {"%s+", "_"}})
```
to insert the current value of the input node 1, with everything after the first `.` stripped, converted to upper case, then with whitespace replaced by underscore. (Maybe that's not the best interface; comments welcome :))

**Comment by L3MON4D3** [comment]
Great suggestion, as discussed :D
What do you think of eg. 
```lua
r(1, {"match", "[^.]+$"}, "toupper", {"gsub", "%s+", "_"}, {"gsub", "_", ","})
```
That way we could have multiple transforms (of the same kind) and the order would be clear.

**Comment by L3MON4D3** [comment]
We'd have some more complexity because of the special strings eg. "toupper", but that's acceptable I think.

**Comment by clason** [comment]
That also works, of course. Whatever is easiest to implement ;)

**Comment by L3MON4D3** [comment]
:+1:
Any more suggestions for special strings?

**Comment by clason** [comment]
"tolower", of course ;)

Maybe look at http://lua-users.org/wiki/StringRecipes for inspiration?

**Comment by L3MON4D3** [comment]
Oh, I didn't know about `string.upper/lower`, that's pretty nice :D
rep also sounds usable.

**Comment by leiserfg** [comment]
I use `rep` for my  
```
╔════════════╗
║box snippets║
╚════════════╝
````

**Comment by L3MON4D3** [comment]
Ah, the dreaded unicode-box-snippets :P
Those should also get cleaner, eg `r(1, {"gsub", ".", "═"})`

**Comment by L3MON4D3** [comment]
> But I think that instead of adding more nodes we should provide more functions in `luasnip.util.functions` and document them.

Yeah exactly, that's the plan. There was some discussion in the matrix group, should've mentioned the results here too :sweat_smile:

**Comment by clason** [comment]
That as well, but I _do_ think that adding an actual node for this would be good.

**Comment by L3MON4D3** [comment]
Well we don't really need a new node to implement the expected behaviour as function nodes are very generic. Could you elaborate on what you dislike about just using function nodes?

**Comment by clason** [comment]
As I said, to make snippets less verbose and reduce boilerplate. It's such a common operation, it should be builtin so not (most) everyone has to set them up themselves.

**Comment by L3MON4D3** [comment]
Oh yeah, builtin isn't the question, it'll be added to `luasnip.util.functions`, it would the be usable via eg. `local r = require'luasnip.util.functions'.r`

**Comment by leiserfg** [comment]
What do you think of using this API?
```lua
f( t:match('[^.]+$'):toupper():gsub("%s+", "_"), {1})
```

**Comment by L3MON4D3** [comment]
> ```lua
> f( t:match('[^.]+$'):toupper():gsub("%s+", "_"), {1})
> ```

Very nice, but how is it possible get the functions and arguments from that?

**Comment by L3MON4D3** [comment]
Ohh, and `t` would be a table with all string functions that then insert themselves, in a way?

**Comment by clason** [comment]
> Oh yeah, builtin isn't the question, it'll be added to `luasnip.util.functions`, it would then be usable via eg. `local r = require'luasnip.util.functions'.r`

To be honest, I couldn't care less whether I need to do 

```lua
local r = ls.repeat_node
```
or 
```lua
local r = ls.util.functions.r
```
(although I'd second what somewhat recommended earlier: I'd stick to more explicit, self-explaining, names for the exported functions)

**Comment by L3MON4D3** [comment]
> (although I'd second what somewhat recommended earlier: I'd stick to more explicit, self-explaining, names for the exported functions)

Yeah, ofc, 'transform_string'?

**Comment by clason** [comment]
so you want to separate the transform and the repeat into two different functions?

**Comment by leiserfg** [comment]
> Ohh, and `t` would be a table with all string functions that then insert themselves, in a way?
t is a factory, each "method"  returns a new factory and at the end if you call it it does what was defined, just taking inspiration from how lambdas used to be done in C++ in the old days.

**Comment by L3MON4D3** [comment]
Phuh, that would be quite a lot, I was thinking of something generic that can accept all string functions.

**Comment by L3MON4D3** [comment]
On the other hand, these should be about readability, which your proposal has..

**Comment by L3MON4D3** [comment]
My current implementation is this 
```lua
local function r(node_indx, ...)
	return f(function(args, ...)
		local transforms = {...}
		local str = args[1][1]
		for indx = 1, #transforms do
			local transform = transforms[indx]
			args = vim.list_slice(transform, 2, #transform)
			print(vim.inspect(args))
			print(unpack(args))
			str = string[transform[1]](str, unpack(vim.list_slice(transform, 2, #transform)))
		end
		return str
	end, node_indx, ...)
end
```
which would accept everything except the special strings, but should be enough for an overview.

**Comment by L3MON4D3** [comment]
> so you want to separate the transform and the repeat into two different functions?

repeat can also be done with the transforms(`string.gsub("text", "(.*)", "%1%1")`)

**Comment by clason** [comment]
Sorry, that was ambiguous. I didn't mean the `string.rep` function but the top-level "repeat this node". But your current implementation tells me that the answer to that is "no", so carry on :)

**Comment by L3MON4D3** [comment]
Oh, repeat still works with just supplying no other args, eg. `r(1)`

**Comment by leiserfg** [comment]
These guys took the same inspiration as me (boost.lambda), I'll try with adding strings functions there.
https://github.com/lunarmodules/Penlight/blob/master/lua/pl/func.lua

**Comment by L3MON4D3** [comment]
So `t` would be a table that, whenever a string-function is called, appends to some internal function-list that can then be executed by `r()`?

**Comment by leiserfg** [comment]
if we add a new node to handle it or extend `f ` internals to convert the generated expression to a proper function (is just a call) we can use 
```
f( _1:match('[^.]+$'):upper():gsub("%s+", "_"), {1})
```
I'm already doing the pr for it.
As you see in this case it's `_1` but one can actually use more than one, for instance, if one needs to have a function that depends on several inputs.

**Comment by L3MON4D3** [comment]
Okay, I think I get what's going on.
Penlight would have to be installed then, right?

**Comment by clason** [comment]
Or just vendor the part of it you need...

**Comment by leiserfg** [comment]
No, I borrowed that part, is just a file from there, I'm testing it right now to see if I found any issue.

**Comment by L3MON4D3** [comment]
Ah yeah, makes more sense.

**Comment by L3MON4D3** [comment]
#67 covers the transforms, `repeat()` should be added separately to `util.functions` I think?

**Comment by leiserfg** [comment]
You can use `rep` too, like  `_1:rep(3)`

**Comment by L3MON4D3** [comment]
Ah, repeat as in 'repeat this node' (we provide copy but only to be used in an functionNode, not as eg. `r(1)`, which would be cleaner)

**Comment by leiserfg** [comment]
I guess I better move the implementation of the lambda thingy out the function node to a new helper node, maybe `l` for lambda that wraps `f` and does the magic, so we don't penalize users loading that part of the code if it's not required.

**Comment by L3MON4D3** [comment]
Good point, I don't think we'd need a new node, just eg.
```lua
function l(fn, indx)
	return f(function(args, fn)
		expr = lambda.instantiate(fn)
		-- maybe merging+splitting here.
		return expr(args[1][1])
	end, indx, fn)
end
```
in `util.functions`.
Well okay, we'd still have to load `util.lambda` in `util.functions`, but I dislike adding something that can be achieved via functionNode as a new node.

**Comment by clason** [comment]
Just a drive-by comment since I originally requested a new type of node: I was thinking from the point of view of the snippet using `i`, `r`, `t`, etc. I completely understand if you don't want to introduce a new "fundamental" node that is actually just a special case of an already existing node. What I am looking for is a sort of "intermediate level" DSL between LSP snippets (too restrictive) and the "native" definition (too verbose). Whether these live in the top-level `luasnip` scope, `luasnip.utils`, or a new `luasnip.functions` (as in, pre-defined function nodes) is beside the point.

**Comment by L3MON4D3** [comment]
Okay, I think with 3278450 and @leiserfgs' great work on #67 and this issue can be closed?

**Comment by clason** [comment]
I think so; just to make it clearer: How would I do something like
```lua
    ['chap'] = "\\chapter{$1}\\label{chap:${2:${1|S.v:lower():gsub('%s+', '_')}}}\n",
```
which would expand to (for `$1=A Chapter` and the default for `$2`)
```tex
\chapter{A Chapter}\label{chap:a_chapter}
```
or
```lua
    ['local'] = [[local ${2:${1|S.v:match"[^.]+$"}} = ${1}]],
```
which would expand to (for `$1=plenary.jobs` and the default for `$2`)
```lua
local jobs  = plenary.jobs
```
?

(Also, I think the Examples would be even more helpful if they also showed the expanded snippet!)

**Comment by L3MON4D3** [comment]
```lua
s("chap", {
	t"\\chapter{", i(1), t"}\\label{chap:", l(l._1:lower():gsub("%s+", "_"), 1), t{"}", ""},
})
```
I just noticed a mistake with functionNodes inside choices, so for now that would be the way to go

**Comment by clason** [comment]
Also, I assume that the lambdas would allow me to insert conditional text, right? So I could have a snippet for
```tex
\usepackage[$2]{$1}
```
where if `$2` is left empty, the surrounding `[` `]` are removed?

**Comment by L3MON4D3** [comment]
> (Also, I think the Examples would be even more helpful if they also showed the expanded snippet!)

Well, the Examples are there to just `:luafile %` them, one can then try them out easily.
But you have a point, I'll need to  extend the docs.

**Comment by clason** [comment]
That makes sense, thank you. But (not strictly related to the transform): My snippet had the lambda as the default for _another_ placeholder -- is that not supported?

**Comment by L3MON4D3** [comment]
> Also, I assume that the lambdas would allow me to insert conditional text, right? So I could have a snippet for
> 
> ```
> \usepackage[$2]{$1}
> ```
> 
> where if `$2` is left empty, the surrounding `[` `]` are removed?

eg. `gsub(".+", "[")` I think.

**Comment by clason** [comment]
> Well, the Examples are there to just `:luafile %` them, one can then try them out easily.

Sure; but at least I looked at the examples to see whether I wanted to install and setup LuaSnips in the first place, so having the expected output in a comment would be helpful.

> But you have a point, I'll need to extend the docs.

Well, it's clearly early days for LuaSnips, and you want to focus on the functionality before polishing the docs; that's very understandable. I just mentioned it while I was thinking of it.

**Comment by L3MON4D3** [comment]
> That makes sense, thank you. But (not strictly related to the transform): My snippet had the lambda as the default for _another_ placeholder -- is that not supported?

Not right now, but that is due to the error I mentioned earlier, It'll be supported :)

**Comment by clason** [comment]
> eg. `gsub(".+", "[")` I think.

Do you think this would be useful to add as a convenience function to `util.functions`? E.g., as `cond("[",2)`?

**Comment by L3MON4D3** [comment]
> > Well, the Examples are there to just `:luafile %` them, one can then try them out easily.
> 
> Sure; but at least I looked at the examples to see whether I wanted to install and setup LuaSnips in the first place, so having the expected output in a comment would be helpful.
> 
> > But you have a point, I'll need to extend the docs.
> 
> Well, it's clearly early days for LuaSnips, and you want to focus on the functionality before polishing the docs; that's very understandable. I just mentioned it while I was thinking of it.

Yeah okay, when looking at them in github that doesn't work, right.

**Comment by L3MON4D3** [comment]
> > eg. `gsub(".+", "[")` I think.
> 
> Do you think this would be useful to add as a convenience function to `util.functions`? E.g., as `cond("[",2)`?

Maybe `notempty(node, string-if-not-empty)`, yeah, I could see that being useful.

**Comment by L3MON4D3** [comment]
Okay, I fixed that error (32cc9ca), 
```lua
s("chap", {
	t"\\chapter{", i(1), t"}\\label{chap:", c(2, {
		l(l._1:lower():gsub("%s+", "_"), 1),
		i(nil)
	}), t{"}", ""}
})
```
should work now.

**Comment by clason** [comment]
Then the only thing left from the original request is the more more high-level combined "repeat with transformation" node, `r(1, {gsub = {"%s+", "_"}})` -- unless you don't want to support that. (It is a bit more convenient to type than the lower-level `lambda` node, but not by much.)

**Comment by leiserfg** [comment]
@L3MON4D3  this also works 
```lua
    s({ trig = "csv", wordTrig = true }, {
      i(1, { "content" }),
      t{"", "separator", ""} ,
      i(2, { "|" }),
      t{"", ">>", ""} ,
      l( l._1:gsub(",", l._2), {1,2}),

    }),
```
Notice the usage of two placeholders in the lambda.

**Comment by L3MON4D3** [comment]
Yeah, I put some snippets into Examples, one utilizing two placeholders as that functionality really should be highlighted.

**Comment by clason** [comment]
Another thing I noticed is that the `rep` node does _not_ live update if I set `updateevents` to `TextChanged{I}`. Is that to be expected (or hard to do)?

**Comment by L3MON4D3** [comment]
Oh, no it should, let me check if I also get that error..

**Comment by L3MON4D3** [comment]
```lua
s("repeat", { i(1, "text"), t({ "", "" }), r(1) })
```
(from Examples) works just fine with `TextChanged,TextChangedI`

**Comment by clason** [comment]
Just to make clear, I mean **live** updating (not just copying once I exit the node)?

**Comment by L3MON4D3** [comment]
Is the Node you want to repeat a `choiceNode`, by any chance?

**Comment by clason** [comment]
I'm using 
```lua
tex = {
      s('beg', {
        t [[\begin{]],
        i(1),
        t { '}', '\t' },
        i(0),
        t { '', [[\end{]] },
        r(1),
        t { '}', '' },
      }),
    },
    ```

**Comment by L3MON4D3** [comment]
Works just fine for me, are you certain you have set the config correctly?

**Comment by clason** [comment]
(see last comment; sorry, edits don't notify)

**Comment by clason** [comment]
It _does_ update when I leave insert mode.

**Comment by L3MON4D3** [comment]
Ohh, it's possible that the autocommand is added before the changed config is 'there', InsertLeave is the default.

**Comment by L3MON4D3** [comment]
Okay, closed? :D

**Comment by clason** [comment]
If you don't want to implement a combined "repeat with transformation" node,`r(1, {gsub = {"%s+", "_"}})` (which I personally think would be nice, but matter of taste), yes -- feel free to close.

**Comment by L3MON4D3** [comment]
Ah yeah, no I don't think that's really necessary as `l(_1:gsub("%s+", "_"), 1)` does basically the same. What would be your reasoning behind having the version with the table?

**Comment by clason** [comment]
Same as always: more concise snippets (you only need to import a single type of "convenience node" unless you need full control over the order, and `r(1, gsub{'foo', 'bar'})` is easier to type and remember than the version with underscores) :)

As I said, a matter of taste, and up to you.

**Comment by L3MON4D3** [comment]
Okay, I won't include it I think, srry.
However, thanks for the first suggestions, they should go a long way in making the rather obscure lua-format more user-friendly :D

**Comment by clason** [comment]
No worries, as I said, your choice!
