### ISSUE TITLE
Apply condition to whole filetype

### ISSUE THREAD

**Issue by apmyplol** [L3MON4D3/LuaSnip#663]
Hey,
I was wondering if it is possible to apply a snippet condition to a whole filetype at once.
For example I have Latex snippets for `tex` and `md` files that do math stuff but I want them only to expand, if my cursor is inside a math-block.
I could do this by adding the condition function to each snippet but I was wondering if there is an option to apply a condition to a whole filetype or set of snippets.
Thanks for the awesome plugin!!!

**Comment by L3MON4D3** [comment]
Oh, no the condition is per-snippet, we could introduce functions for applying conditions to many snippets at once, but I think [`extend_decorator`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#extend_decorator) is a better way to deal with this:
```lua
-- create decorated snippet-constructor, which extends passed options with `in_math_block`-condition
local s_mathonly = ls.extend_decorator.apply(s, {}, {condition = in_math_block})
s_mathonly("a", {t"\\alpha"})
```

**Comment by apmyplol** [comment]
Oh I didnt konw there was the `extend_decorator` functions, this looks very powerful!
Thank you very much, that is indeed a very good solution.

**Comment by L3MON4D3** [comment]
Nice!
Yeah, `extend_decorator` is awesome, I try to show it off as much as possible :D

**Comment by apmyplol** [comment]
I just noticed I also load snippets from a `json` file using `loaders.from_vscode`. Is it possible to apply some sort of extend decorator to these snippets as well or is there even a way to make them only expand on certain conditions?

**Comment by L3MON4D3** [comment]
Hmm, no, that's not possible. We could extend the json-format to allow a `condition`-key for json-snippets (value would have to be some key that is resolved to a function, so pretty involved), but honestly, the lua-loader is much more flexible, and can handle the same format (lsp-snippets) via `parse`, so I'd very much recommend that.
