### ISSUE TITLE
Get warning after packrer update

### ISSUE THREAD

**Issue by lobanov4real** [L3MON4D3/LuaSnip#669]
I add for installation:  

> use({ "L3MON4D3/LuaSnip", tag = "v<CurrentMajor>.*" }) 

 
but after updating get warning:
![image](https://user-images.githubusercontent.com/110660329/203735611-e9c3026c-3e25-4b49-a049-02417a252d0c.png)

**Comment by L3MON4D3** [comment]
Oh, it should be `v*` (or better yet, `v1.*` :D)

**Comment by lobanov4real** [comment]
Yep, works correct 😁

**Comment by L3MON4D3** [comment]
Nice!
