### ISSUE TITLE
No Transformations despite installed jsregexp

### ISSUE THREAD

**Issue by zzzachzzz** [L3MON4D3/LuaSnip#670]
Transformations don't seem to be applying for me. I have tried a variety of installation methods for jsregexp, and verified installation with the following lua code:
```lua
local jsregexp_ok, jsregexp = pcall(require, "luasnip-jsregexp")
print(jsregexp_ok)
if not jsregexp_ok then
	jsregexp_ok, jsregexp = pcall(require, "jsregexp")
end
print(jsregexp_ok)
```
Running with `:luafile %` outputs:
```
false
true
```
...for my current installation method via luarocks, as recommended [here](https://github.com/L3MON4D3/LuaSnip/issues/651#issuecomment-1307814499).

With the following example snippet, it's expected that every character captured by `$1` will be replaced by `_`:
```
snippet mysnip
  hello ${1/.*/_/g};$2
```
Instead, no transformation is applied. I'm following the syntax described [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms), and I understand not all of it is fully supported.

Version info:
```
$ nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

$ pacman -Qi luajit
Name            : luajit
Version         : 2.1.0.beta3.r449.gdad04f17-1
Description     : Just-in-time compiler and drop-in replacement for Lua 5.1
```

Also note that I did not previously have Lua 5.1. I performed the following installs:
```
sudo pacman -S lua51
sudo luarocks --lua-version 5.1 install jsregexp
```

**Comment by L3MON4D3** [comment]
According to the output, `jsregexp` should be available to luasnip..
AFAICT the snippet you showed is missing the source for the transformed string, could you try `hello $1 ${1/./_/g}; $2`?

**Comment by zzzachzzz** [comment]
Thanks for the quick response. Indeed, the snippet you supplied works.

I had been testing more complex snippets and was having trouble with the syntax, porting them from UltiSnips.

Before (not working)
```
snippet r.us "React.useState"
  const [${1}, set${1/\w+/\u${0}/}] = React.useState(${3:''});${0}
```

After (working!)
```
snippet r.us "React.useState"
  const [$1, set${1/(.*)/${1:/capitalize}/}] = React.useState(${3:''});${0}
```

It seemed using parenthesis for a capture group was also necessary for the `:/capitalize` transform to work. Thank you again

**Comment by L3MON4D3** [comment]
Ahh, yeah it's possible ultisnips is doing something different there, probably closer to vim-regex.
You're welcome! :)
