### ISSUE TITLE
I can't input ikj when the lua-snip visible when I mapping ikj for moving

### ISSUE THREAD

**Issue by JuanZoran** [L3MON4D3/LuaSnip#672]
for my neovim keymaps, I perfer to map 'i-j-k-l' for moving cursor
buf I found that it doesn't work for luasni
sorry for my poor English, and I make a video for explain what I meaning, But I get 'Something went really wrong, and we can't process that file' about that, I don't know how to fixed that ......

**Comment by JuanZoran** [comment]
[Luasnip.zip](https://github.com/L3MON4D3/LuaSnip/files/10097410/Luasnip.zip)
I can' upload this video directly....

**Comment by L3MON4D3** [comment]
Could you upload another video, I can't find the issue in the first one (it seems a bit broken for me :/)
It would be great if you could convert the video to mp4 (or make it possible to watch in github in some other way), that makes it easier to watch it.
But besides that, are you sure this issue originates with Luasnip?

**Comment by JuanZoran** [comment]
Sorry about that, I have found the result of that!
It's just because I do some mappings with 'v' mode 
> like 'i' mapped  to 'k'   

and the 'v' mode means the 'x' and 's' modes
I guess you guys set select mode so that we can press any key to change the visual select section,  so I change some mappings then it works well!

**Comment by L3MON4D3** [comment]
Ahh of course :facepalm:
Glad you figured it out :+1:
