### ISSUE TITLE
How to add multiple JSON files (directory) in package.json?

### ISSUE THREAD

**Issue by Andrew15-5** [L3MON4D3/LuaSnip#677]
I want to divide snippets for one language into several files. But can I somehow import multiple files under one { snippet } in `package.json`? Or I have to separately include each file for the same language? (Feels too bulky for project that wants to cut number of typed characters.)

```json
{
  "name": "my-snippets",
  "contributes": {
    "snippets": [{
      "language": ["<my language>"],
      "path": ["foo.json", "bar.json"],
      "path": "/path/to/dir"
    }]
  }
}
```

P.S. I'm just starting to get used to Lua and LuaSnip (previously used [`vim-vsnip`](https://github.com/hrsh7th/vim-vsnip) in Vimscript configuration).

**Comment by L3MON4D3** [comment]
Ah, I don't think we support that for vscode-snippets (not sure if it's even supported in vscode)

In any case, snipmate supports this, and is much more sane, so I'd recommend you use that instead :D
(conversion can be done using [`snippet-converter.nvim`](https://github.com/smjonas/snippet-converter.nvim))

**Comment by leiserfg** [comment]
You have to add another entry to the snippets list.

**Comment by Andrew15-5** [comment]
@L3MON4D3, can you confirm, that [`snippet-converter.nvim`](https://github.com/smjonas/snippet-converter.nvim) can work with LuaSnip snippets (that are in `.lua` files)? Because it is said that it works with VS Code format (I think that only `.json` files of LuaSnip are supported). It's just that today I've written my first pretty complex snippet in Lua and if at any moment I can convert that to some other snippet format, then I will definitely try to switch to LuaSnip 100% (no need for snipmate).

**Comment by Andrew15-5** [comment]
I'd like to thank everybody for answering the question.

**Comment by L3MON4D3** [comment]
> @L3MON4D3, can you confirm, that [`snippet-converter.nvim`](https://github.com/smjonas/snippet-converter.nvim) can work with LuaSnip snippets (that are in `.lua` files)? Because it is said that it works with VS Code format (I think that only `.json` files of LuaSnip are supported). It's just that today I've written my first pretty complex snippet in Lua and if at any moment I can convert that to some other snippet format, then I will definitely try to switch to LuaSnip 100% (no need for snipmate).

Ouh, that I cannot, srry :D

But you can mix-and-match the two approaches, define as many snippets as possible in snipmate/textmate-format, and the ones that really need lua in lua

**Comment by L3MON4D3** [comment]
> You have to add another entry to the snippets list.

Oh, yeah that's another option, though it will bloat your number of typed characters :P
