### ISSUE TITLE
useless diagnostics errors upon completions

### ISSUE THREAD

**Issue by mortezadadgar** [L3MON4D3/LuaSnip#68]
I don't how this relates to this plugin but if I try to fmt.Pr| and select Print from completion menu somehow this plugin causes cursor to be moved to (|) and virtualbox show a useless error like so
![image](https://user-images.githubusercontent.com/27911493/125186594-c067fe80-e21a-11eb-93d2-c3dc5468d8d4.png)

without this plugin
![image](https://user-images.githubusercontent.com/27911493/125186577-957daa80-e21a-11eb-8c10-d385fdf374a9.png)

It's weird bc I don't even select a snippet from completion menu

```
use {
	"L3MON4D3/LuaSnip",
	requires = {
		{
		        "rafamadriz/friendly-snippets",
		}
	},
	config = function()
		require"luasnip/loaders/from_vscode".lazy_load()
	end
}
```

**Comment by L3MON4D3** [comment]
Does the Error diagnostic disappear after eg. reloading the buffer? I think it's possible that, without Luasnip, fmt.Print is just a completion and then directly updates the diagnostics, whereas with Luasnip, fmt.Print is a snippet and the diagnostics aren't directly updated after completion.
Some language servers can update(send changes and then receive new diagnostics) on insert, maybe check if that can be set, that way the diagnostics should update after expanding the snippet.

**Comment by mortezadadgar** [comment]
@L3MON4D3 yeah diagnostic disappear after exiting insert which is too late imo

> Some language servers can update(send changes and then receive new diagnostics) on insert, maybe check if that can be set, that way the diagnostics should update after expanding the snippet.
where I can find that option I couldn't find anything on gopls documentations

**Comment by L3MON4D3** [comment]
Perhaps the option doesn't exist for gopls.
You could disable lsp-snippets altogether by modifying the capabilities sent to the language server to disable snippets.
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = false;

require'lspconfig'.gopls.setup{
	capabilities = capabilities
}
```

**Comment by mortezadadgar** [comment]
@L3MON4D3 disabling lsp snippet solved the problem thanks!

**Comment by L3MON4D3** [comment]
:point_left: :point_left:
