### ISSUE TITLE
Change text to the right of the cursor when expanding a snippet

### ISSUE THREAD

**Issue by Andrew15-5** [L3MON4D3/LuaSnip#684]
I have a plugin that automatically adds any closing bracket. So I was wondering If I can change this:
```latex
${|}$ % | = cursor
```
to this:
```latex
$\{|\}$
% or this
$\left\{|\right\}$ % even wrap both in choice node with restore node (just something I have in mind)
```
and after that, jump to:
```latex
$\{\}|$
% or this
$\left\{\right\}|$
```

And this of course should also apply to `[]` and `()`.

I know that you can change text which is before cursor (with pattern or postfix snippet) and that you can check the whole line
in expansion's condition function (but it's only condition). The more general question is can you change the whole current line when an expansion pattern was found?

**Comment by L3MON4D3** [comment]
I'm not completely sure what you're after, but I've got the following snippet
```lua
local texpairs = {
	{"(", ")"},
	{"\\left(", "\\right)"},
	{"\\big(", "\\big)"},
	{"\\Big(", "\\Big)"},
	{"\\bigg(", "\\bigg)"},
	{"\\Bigg(", "\\Bigg)"},
}

local function choices_from_pairlist(ji, list)
	local choices = {}
	for _, pair in ipairs(list) do
		table.insert(choices, {
			t(pair[1]), r(1, "inside_pairs", dl(1, l.LS_SELECT_DEDENT)), t(pair[2])
		})
	end
	return c(ji, choices)
end

-- `s_add` just constructs and adds the snippet immediately
s_add({trig = "(", wordTrig=false}, {
	choices_from_pairlist(1, texpairs)
})
```
which implements the restorenode-stuff you mention, but I'm not sure how a plugin adding closing brackets, and changing the entire line factors into this, could you expand on that?

**Comment by Andrew15-5** [comment]
Well, just try [it](https://github.com/jiangmiao/auto-pairs) out with your snippets and see for yourself (Alt+p is plugin toggle).

**Comment by L3MON4D3** [comment]
Phh okay, afaict the easiest solution is disabling the autopairs-plugin for those pairs you have snippets of, there's no way to "superimpose" a snippet on top of existing text.
Alternatively, store position of `(,)`, delete the line, and expand a snippet using `ls.snip_expand`

**Comment by Andrew15-5** [comment]
Mhh, that's a great idea. But just trying to remove the right parenthesis is even better. But either way, I would have to use more of a Vimscript than LuaSnip, right? Because I assume LuaSnip can't: store position of chars, delete whole line, delete char with specific position in buffer. This would mean that I will have to somehow alternate this `imap`:
```vim
imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<Plug>luasnip-expand-or-jump' : '<Tab>'
```

I hope something like this would work:

```vim
function! Remove_right_bracket()
  " Get current position
  " Get char to the right
  " If it is )}] then remove it
endfunction
imap <silent><expr> <Tab> luasnip#expand_or_jumpable() ? '<C-O>:call Remove_right_bracket()<CR><Plug>luasnip-expand-or-jump' : '<Tab>'
```

**Comment by Andrew15-5** [comment]
@L3MON4D3, can you tell why I get this error:
![image](https://user-images.githubusercontent.com/37143421/206306620-2900f629-911b-40cf-9c31-4c74dd9945a6.png)

I also tried `lua snip_expand("{",{pos={1,7}})`. I do have `{` snippet.

**Comment by L3MON4D3** [comment]
Oh, you don't have to use vimscript here, you could use lua, see `nvim_buf_set_text` and `nvim_buf_get_text`.
Your pseudocode looks like it should work, if you can make it work using vimscript, by all means go for it
`snip_expand` takes a snippet, not the trigger of one (see doc for more info)
But if your cursor is already behind the `{`, you can also call `ls.expand()` (which is exactly like typing `<Tab>` yourself)
