### ISSUE TITLE
[Question]How to reload luasnippets

### ISSUE THREAD

**Issue by fecet** [L3MON4D3/LuaSnip#685]
How to reload luasnips without restart neovim, I'm find alternative for 

```
:call UltiSnips#RefreshSnippets()
```

**Comment by L3MON4D3** [comment]
It should happen automatically when saving the buffer contributing snippets, you can trigger it manually by calling `:lua require("luasnip.loaders.reload_snippets(<absolute_path_to_the_snippet_file>)")`
