### ISSUE TITLE
snippet not working

### ISSUE THREAD

**Issue by pierce-c** [L3MON4D3/LuaSnip#687]
`s("temp",fmta([[

	\documentclass[<>]{<>}

	\usepackage{ulem}

	\ULforem

	\usepackage{amssymb,amsmath}

	<>

	\begin{document}

		\title{<>}

		\author{<>}

		\date{<>}

		\maketitle

		<>

	\end{document}

		]],{i(1),i({2,"article"}),i(3),i(4),i(5),i({6,"\\today"}),i(7)})),`

**Comment by pierce-c** [comment]
the code does not work and i would like some help as to why. It is inside a return statement in one of those thingys and it works properly with other snippets but this one raises and error after i add the 4th or 5th insertnode

**Comment by L3MON4D3** [comment]
Can't spot the error right away.. Could you share the error-message?

**Comment by pierce-c** [comment]
nvm i fixed it they changed the syntax for the insert node default text again

**Comment by pierce-c** [comment]
u don't have to use a dictionary inside of insert node declaration for having default text
