### ISSUE TITLE
Retrieving buffer's comment string within a snippet returns wrong option value

### ISSUE THREAD

**Issue by jtws** [L3MON4D3/LuaSnip#692]
This is a question, not a bug report (I think).

Context: Lua snippet using a Lua function to populate a `fmt` node placeholder. Latest LuaSnip version with nvim-cmp.

Code at the bottom.

## Problem summary

When retrieving `vim.opt.comments`  and using a function to parse a repeatable comment string out of it for a `fmt` node the value is always `//` indicating the default value or C buffer, not the comment string for the calling buffer. When the parsing function is invoked directly from a buffer it works fine. It only returns `//` when invoked from within a snippet.

Expectation is that it would return the `vim.opt.comments` option value for the buffer in which the snippet is used.

I tried `vim.bo.comments`, `vim.bo.comment_string` and `vim.api.nvim_buf_get_option(bufnr, "comments")` with the same result.

## Use case

I want to have a license snippet which will return the license text commented if `vim.opt.comments` has a repeatable comment definition.

If there's no suitable comment string defined in `vim.opt.comment` the snippet should return the license without comments. I.e., the function returns `""`.

This is so that I don't have to repeat the snippet for all languages but have a single snippet catering to all languages.

## Problem details

I've a Lua function (see below) for retrieving the repeatable comment string from `vim.opt.comments` and it works fine in Luapad. The license snippet (see below) has a single `fmt` node, each line prefixed with a `{c_str}` placeholder  and `c_str = my_func()`. 

When I insert the snippet each line is always prefixed with `//`, e.g., for a Python buffer. which has `vim.bo.comments = "b:#,fb:-"` so it should prefix each line with `#` instead. Also the preview shows `//`.

As said, I tried `vim.bo.comment_string` and also `vim.api.nvim_buf_get_option(bufnr, "comments")` passing bufnr but it still returns `//`` from the function and I don't understand why. What buffer is the function executing in? I thought maybe this is happening because the function is invoked within the snippet definition. if I call the function from the buffer I'm inserting the snippet it it returns the correct comment string.

I've no idea how to debug this. I'm using LuaSnip with nvim-cmp and otherwise it works fine.

### Snippet

Here `{c_str}` substitutes to `//` regardless of which buffer the snippet is called from:

<details><summary>Snippet definition</summary>

```lua
	s(
		{
			trig = "MIT-commented",
			name = "MIT license commented",
			dscr = "MIT license with lines prefixed with buffer's comment string",
		},
		fmt(
			[=[
			{c_str}Copyright (c) {year} {holder}
			{c_str}
			{c_str}Permission is hereby granted, free of charge, to any person obtaining a copy
			{c_str}of this software and associated documentation files (the "Software"), to deal
			{c_str}in the Software without restriction, including without limitation the rights
			{c_str}to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
			{c_str}copies of the Software, and to permit persons to whom the Software is
			{c_str}furnished to do so, subject to the following conditions:
			{c_str}
			{c_str}The above copyright notice and this permission notice shall be included in all
			{c_str}copies or substantial portions of the Software.
			{c_str}
			{c_str}THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
			{c_str}IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
			{c_str}FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
			{c_str}AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
			{c_str}LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
			{c_str}OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
			{c_str}SOFTWARE.
			{empty_line}
			]=],
			{
				year = p(os.date, "%Y "),
				holder = i(1, [[license holder]]),
				c_str = util.get_buf_comment_str(),
				empty_line = t(""), -- Hack for trailing empty line, Luasnip ...
			}
		)
	),
```
</details>

### Comment string function

This resides in my `util` module but this version is ready to be pasted to Luapad to verify it works.

<details><summary>get_buf_comment_str function (Luapad paste ready)</summary>

```lua
local function get_buf_comment_str(opts)
	local opts = opts or {}
	local add_space = opts.add_space or true

	-- Non-repeatable comment def flags we need to skip
	local bad_flags = { "f", "s", "m", "e" }
	local c_defs = vim.opt.comments:get()

	if c_defs == nil or c_defs == {} then
		return ""
	end

	for _, c_def in pairs(c_defs) do
		-- Parse flags
		-- b flag means comment string must be followed by a blank
		local b_flag = false
		local flags = c_def:gsub(":.*", "")
		for _, bad_flag in pairs(bad_flags) do
			if flags:find(bad_flag) then
				goto next_c_def
			end
			if flags:find("b") then
				b_flag = true
			end
		end

		local c_str_start = c_def:find(":")
		if c_str_start == nil then
			-- Shouldn't happen, malformed definition
			goto next_c_def
		end

		-- Get comment string
		local c_str = c_def:sub(c_str_start + 1)
		if type(c_str) == "string" and c_str ~= "" then
			if b_flag or add_space then
				c_str = c_str .. " "
			end
			return c_str
		else
			return ""
		end
		::next_c_def::
	end
	return ""
end

print(get_buf_comment_str()) -- `--` for Lua
```

**Comment by L3MON4D3** [comment]
Ah, I think the problem might be that `c_str` is evaluated in the context of loading the snippet, and not in that of the buffer where it is expanded.
You could replace the simple string with a functionNode, which will then be evaluated on expansion of the snippet (see DOC.md)

Also, take care that `fmt` only accepts nodes (it's possible strings also work depending on your version, but that will change) (maybe use `[=[ ... ]=]:format(...)` instead)

**Comment by jtws** [comment]
> Ah, I think the problem might be that `c_str` is evaluated in the context of loading the snippet, and not in that of the buffer where it is expanded. You could replace the simple string with a functionNode, which will then be evaluated on expansion of the snippet (see DOC.md)
> 
> Also, take care that `fmt` only accepts nodes (it's possible strings also work depending on your version, but that will change) (maybe use `[=[ ... ]=]:format(...)` instead)

Thanks! Got it working with a function node. Closing this one as the issue is solved. Thanks again for the quick reply!

**Comment by L3MON4D3** [comment]
You're welcome :)
