### ISSUE TITLE
giving error on startup of nvim

### ISSUE THREAD

**Issue by pierce-c** [L3MON4D3/LuaSnip#693]
when i open nvim on the command line by typin nvim, it opens with a barrage of errors, first saying some sort of assertion failed on line 104 in file `LuaSnip/lua/luasnip/util/log.lua` inside the vim api function `vim.loop.fs_write`, where apparently `luasnip_log_fd` was `nil`. Everything after that said it was due to a previous error. I recently updated with packer, and am confused why it isn't working now since the latest commits said it was for autogenerating docs. can someone please help?

**Comment by L3MON4D3** [comment]
Could you show the output of
```vim
:lua =vim.fn.stdpath("log")
```
and
```vim
:lua =vim.fn.stdpath("cache")
```
and check if those directories exist?

**Comment by pierce-c** [comment]
stdpath log isn't defined and stdpath cache is ~/.cache/nvim and exists. If you mean log to be ~/.cache/nvim/log then yes that file exists. Also, I am on neovim 0.6.1.

**Comment by L3MON4D3** [comment]
Oh, not defined? Does it error or return `nil`?

**Comment by pierce-c** [comment]
typing `:lua print(vim.fn.stdpath("log"))` gives an error, it is not a valid stdpath.

**Comment by pierce-c** [comment]
vim.fn.stdpath("log") is only defined in later versions of neovim, your source code says. The issue is that it is giving an error when calling vim.loop.fs_write()

**Comment by pierce-c** [comment]
in `lua/luasnip/util/log.lua` on line 42, add a second argument to `vim.loop.fs_write`, being `-1`

**Comment by pierce-c** [comment]
i think, i am not very knowledgable on these nvim packegees

**Comment by L3MON4D3** [comment]
Could you elaborate? Afaict there are two arguments to that call, first the file-descriptor of the logfile, and second the string we want to write

**Comment by pierce-c** [comment]
i realized the issue: i forgot to define the get_visual function in one of my files.

**Comment by pierce-c** [comment]
oh sorry, i ddnt see the comma there, the third arg should be -1

**Comment by pierce-c** [comment]
i think

**Comment by L3MON4D3** [comment]
> i realized the issue: i forgot to define the get_visual function in one of my files.

Does it work if this function is defined??

You can find the doc for `fs_write` [here](https://github.com/luvit/luv/blob/master/docs.md#uvfs_writefd-data-offset-callback), though you might have a different version installed, maybe check with your systems package manager.

The issue is almost certainly that the fd is nil, which it should not be. Could you add some `print`-statements to figure out why that nil is generated?

**Comment by pierce-c** [comment]
nvm the error was gone. I reccomend u add some more checks in ur code to make sure things aren't null.

**Comment by L3MON4D3** [comment]
Alright, thanks for the input
