### ISSUE TITLE
How to create golang struct tag snippet

### ISSUE THREAD

**Issue by supengchuan** [L3MON4D3/LuaSnip#694]
Hi, 
    I want to create a snippet for goalng struct tag. If current tag is the first tag, use backquote to surround the tag like \`json:"value"\`.
If current tag is not the first tag, e.g. 
```golang
type Exampe struct{
    Name string `json:"name" use snippet here`
}
```
just print snippet like -->json:"value"

I have used choice Node implement that function, but I should choose  the snippet every time.

Then I create a function to judge current line has backquote or not
```lua
M.in_tag_define = function()
        local current_line = vim.api.nvim_get_current_line()
        local last_char = string.sub(current_line, -1)
        if last_char == "`" then
                return true
        else
                return false
        end
end
```

But I donot know how to use this judge result to gen different snippet. 

I need help, anyone can help me? Thank you very much!

**Comment by L3MON4D3** [comment]
Hi!
You can use dynamicNode for that (see DOC.md, or one of the videos in the readme if you haven't looked into it yet), basically call `in_tag_define`, and return a different snippet for each case

**Comment by supengchuan** [comment]
Thanks for you reply. I will try it.
