### ISSUE TITLE
Rep node, please, BEHAVE!

### ISSUE THREAD

**Issue by gabinci** [L3MON4D3/LuaSnip#697]
For some reason i can't get out of rep nodes and it keeps on going and going forever until it crashes my terminal.

https://user-images.githubusercontent.com/77574658/207962835-8b7ade62-54a5-41a8-a4d3-112ed548b037.mp4

my code:
```lua
return {
	s(
		{
			trig = "pcall",
			desc = "pcall funciton",
		},
		fmta(
			[[
      local status, <> = pcall(require, "<>") 
      if not status then
        require("core.log").log_error("<>")
        return
      end
    ]],
			{
				i(1),
				rep(1),
				rep(1),
			}
		)
	),
```
sorry for poor video quality, github wont allow me to upload a video larger than 10 mb

**Comment by L3MON4D3** [comment]
Great title xD
Unfortunately, it's a known issue, without a real solution :/
Workaround: turn off formatting
Related: #675 is the most recent issue on it, there are many others

**Comment by MarcusXavierr** [comment]
@L3MON4D3 you've mentioned that this could prevent the problem

"This can be prevented by always jumping through the snippet(most comfortable via region_check_events, it jumps to the i(0) once the cursor is outside the region of the snippet)"

Does this solution still work?

I'm using snippets in Go, and the problem occurs when I try to extract a function from a snippet that has a rep(). I don't have problems with go auto formating

The code before extracting
<img width="742" alt="image" src="https://user-images.githubusercontent.com/59923581/216963625-a1bbc3a3-0161-4e90-9ca0-5015b32409c7.png">


the code after extracting 
![image](https://user-images.githubusercontent.com/59923581/216963674-4f600db5-4b48-4e9e-b97d-57f69ccec92b.png)

**Comment by L3MON4D3** [comment]
Ah that might not have been entirely correct, at least I can't think of the connection right now
The only surefire way to prevent this is to disable autoformatting, or to delete the snippet once you're done with it (history=false, or leave the snippet on insert Leave (you can find examples for that in other issues, don't have them on hand right now))
