### ISSUE TITLE
Better lazy-loading

### ISSUE THREAD

**Issue by clason** [L3MON4D3/LuaSnip#698]
Luasnip is one of the heavier plugins in my config, since `plugin/luasnip.vim` requires `'luasnip.config'`, which pulls in a large range of submodules including `'luasnip.nodes'` and `luasnip.util.parser`.

I think it would be worthwhile to either disentangle that so the amount of submodules is minimized or to try to defer calling `_setup` until either `setup` is called or (if using Luasnip without explicit `setup` is supported), the main `luasnip` module is required when a mapping is called.

(A lower-hanging fruit would be to convert the vimscript commands to Lua `vim.api` calls so they can be cached by `impatient`.)

---

Here's a `--startuptime` log without any explicit calls to `luasnip` (to be read bottom to top):
```
051.647  000.067  000.067: require('luasnip.util.types')
051.716  000.067  000.067: require('luasnip.util.ext_opts')
052.175  000.458  000.458: require('luasnip.extras.filetype_functions')
052.237  000.061  000.061: require('luasnip.session')
052.446  000.078  000.078: require('luasnip.util.util')
052.505  000.058  000.058: require('luasnip.nodes.util')
052.558  000.052  000.052: require('luasnip.util.events')
052.565  000.263  000.076: require('luasnip.nodes.node')
052.657  000.058  000.058: require('luasnip.util.extend_decorator')
052.660  000.423  000.101: require('luasnip.nodes.insertNode')
052.802  000.061  000.061: require('luasnip.util.mark')
053.068  000.075  000.075: require('luasnip.nodes.textNode')
053.346  000.218  000.218: require('luasnip.util._builtin_vars')
053.427  000.357  000.139: require('luasnip.util.environ')
053.489  000.060  000.060: require('luasnip.util.pattern_tokenizer')
053.538  000.048  000.048: require('luasnip.util.dict')
053.594  000.056  000.056: require('luasnip.session.snippet_collection')
053.639  000.835  000.239: require('luasnip.nodes.snippet')
053.644  000.982  000.085: require('luasnip.nodes.choiceNode')
053.718  000.067  000.067: require('luasnip.nodes.functionNode')
053.794  000.074  000.074: require('luasnip.nodes.dynamicNode')
053.865  000.070  000.070: require('luasnip.nodes.restoreNode')
053.914  000.048  000.048: require('luasnip.nodes.absolute_indexer')
053.970  000.055  000.055: require('luasnip.extras')
054.077  000.053  000.053: require('luasnip.util.str')
054.080  000.107  000.054: require('luasnip.extras.fmt')
054.224  000.050  000.050: require('luasnip.extras.conditions')
054.272  000.047  000.047: require('luasnip.extras.conditions.show')
054.317  000.189  000.093: require('luasnip.extras.conditions.expand')
054.318  000.237  000.048: require('luasnip.extras.expand_conditions')
054.374  000.055  000.055: require('luasnip.extras.postfix')
054.541  000.057  000.057: require('luasnip.util.parser.neovim_ast')
054.950  000.053  000.053: require('luasnip.util.directed_graph')
054.954  000.528  000.418: require('luasnip.util.parser.ast_utils')
055.060  000.049  000.049: require('luasnip.util.functions')
055.063  000.108  000.059: require('luasnip.util.parser.ast_parser')
055.148  000.084  000.084: require('luasnip.util.parser.neovim_parser')
055.151  000.776  000.055: require('luasnip.util.parser')
055.332  003.860  000.314: require('luasnip.config')
055.370  003.995  000.135: sourcing /Users/clason/.local/share/nvim/site/pack/packer/start/luasnip/plugin/luasnip.vim
```

**Comment by L3MON4D3** [comment]
Oh, yeah that's a lot of stuff for the initial load (though 4ms still seems pretty quick, or am I reading the log wrong?)
I guess the biggest offender is the [default `snip_env`](https://github.com/L3MON4D3/LuaSnip/blob/e8932ee0dcf283aa2ff84e6f0c4fe8cea3cf0356/lua/luasnip/config.lua#L123-L146), lazy-loading its entries should go a long way.
`vim.api` instead of vimscript sounds pretty cool, if impatient can speed that up :+1:

**Comment by clason** [comment]
> (though 4ms still seems pretty quick, or am I reading the log wrong?)

It all depends on the baseline :) (This is on a <30ms total startuptime.) 

> I guess the biggest offender is the [default snip_env](https://github.com/L3MON4D3/LuaSnip/blob/e8932ee0dcf283aa2ff84e6f0c4fe8cea3cf0356/lua/luasnip/config.lua#L123-L146), lazy-loading its entries should go a long way.

Oh, yeah, I agree! Standard approach is wrap it in a `function()...end` that is evaluated when needed.

**Comment by L3MON4D3** [comment]
> It all depends on the baseline :) (This is on a <30ms total startuptime.)

ofc, just wanted to make sure I'm not missing anything :D

> Oh, yeah, I agree! Standard approach is wrap it in a `function()...end` that is evaluated when needed.

So create one table `snipe_env-key -> function`, and replace the current `snip_env` with essentially an `__index` which evaluates the function and sets its value in the table?

**Comment by clason** [comment]
Yes, that could work!

**Comment by L3MON4D3** [comment]
Okay nice, I'll look into implementing that
Thanks for bringing it up :+1:

**Comment by clason** [comment]
Fixed now, thanks! 🎉
