### ISSUE TITLE
Tab as expand/jump tirgger

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#699]
I want to use `<Tab>` as my expand plus trigger for luasnip. I have this in my config:

```lua 
vim.keymap.set({"i", "s"}, "<Tab>",
function()
    if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
    end
end,  
{silent = true})
```

This works fairly well but I can't use `<Tab>` for it's true purpose. i.e. now tab does not insert indentations. What can I change in my function/mapping that fixes this?

**Comment by L3MON4D3** [comment]
You could add essentially `else return "<Tab>"` (not sure it'd work verbatim :sweat_smile:), that way if luasnip can't jump/expand you just get a tab.

But I'd like to at least mention using a key other than tab for expansion, I've switched a few months ago (to `<C-J,K,L>` for jump back, expand, jump respectively) and haven't looked back

**Comment by nikinbaidar** [comment]
> You could add essentially `else return "<Tab>"`

Simply returning `<Tab>` does not work. I had to add `vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Tab>", true, false, true), "n", false)` in the else branch.

>But I'd like to at least mention using a key other than tab for expansion, I've switched a few months ago (to <C-J,K,L> for jump back, expand, jump respectively) and haven't looked back

I'm just recently migrated to luasnip and I'm really used to `<Tab>` and  `<S-Tab>` from what I was using previously. Plus I have `C-J,K` bound to something else. But I'll keep your advice for the future. Thank you.
