### ISSUE TITLE
Input node using  the wrong  range

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#7]
I have this snippet 
```lua
local function replace_each(replacer)
    return function(args)
        local len = #args[1][1]
        return {replacer:rep(len)}
    end
end

ls.snippets = {
 all = {
s({trig = "bbox", wordTrig=true},
    {
        t{"╔"}, f(replace_each("═"), {1}), t{"╗", "║"},
        i(1, {"content"}),  t{"║", "╚"},
        f(replace_each("═"), {1}),
        t{"╝"},
        i(0)}
 )

 }
}
```
When it renders the first time instead of selecting `content` it selects co`ntent`.
I tested with different characters for the corners and sides of the box ( `*`, "|" and "-") and it works fine, so I guess is something related to unicode runes counting.

**Comment by L3MON4D3** [comment]
Tbh I haven't really spent much thought on specifically supporting Unicode, but I think I know where the problem is. I'll look into fixing this.

**Comment by L3MON4D3** [comment]
Okay, latest commit should fix this issue.
