### ISSUE TITLE
Context specific expansion 

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#700]
I'm loading snipmate style snippets and also beginning to write certain snippets in luasnip syntax itself.  

How can I import or load snippets such that I get context specific expansion? For example, I want to be able to trigger CSS snippets within `<style></style>` tag in HTML files or trigger HTML snippets in JSX files.

**Comment by L3MON4D3** [comment]
Oh, those are pretty different in luasnip:
"html snippets in jsx files" is possible via `ls.filetype_extend` ([look here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#api-reference)), `condition` (or `show_condition`) can be used to selectively disable (don't expand, or don't show in completion engines) an available snippet based on the position in the file. There's an entry in [the doc](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets), which goes into some detail, I think there are also examples in `examples/snippets.lua`.
And `conditions` are not available in snipmate-syntax, only lua

**Comment by nikinbaidar** [comment]
`ls.filetype_extend` provides a way to completely import snippets for a certain filetype, which isn't always desired. Perhaps I put it a bit wrongly but what I'm looking for is to be able to expand the snippets in only certain parts of the file. Like I want to expand CSS snippets only when I am in `<style>..</style>`.  Reading the docs a bit more I found [`from_cursor_pos`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#filetype_functions) which sort of explains what I'm looking for i.e. treesitter parsing and snippet expansion in "injected regions". But I couldn't find implementation examples, the only luck I had is [this](https://github.com/L3MON4D3/LuaSnip/blob/master/Examples/snippets.lua#L57). So I tired putting
```lua
ft_func = function() 
    return require("luasnip.extras.filetype_functions").from_cursor
end
```
which didn't work. Then I tried `ft_func = require("luasnip.extras.filetype_functions").from_cursor`, which didn't work . It would be really kind of you if you could tell me what I should set my `ft_func` in my setup to so that luasnip uses treesitter to determine the filetype at the cursor.

**Comment by L3MON4D3** [comment]
Ahh, alright:
You almost had it, `ft_func = require("luasnip.extras.filetype_functions").from_cursor_pos` (or `from_pos_or_filetype`, which is a bit safer since it falls back to just the filetype if treesitter doesn't return anything)

**Comment by nikinbaidar** [comment]
Yes `from_pos_or_filetype` seems more sensible to me so settling for that right now. Thanks alot for your time.
