### ISSUE TITLE
Modular snippets

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#702]
Migrating from Ultisnips, I want to store my snippets separate for each file. How can I load snippets from `/lua/snippets/filename.lua` instead of the defining all the snippets in a single file? Suppose I  have this directory tree:

```
lua/
├── core/
│   ├── ...
└── luasnip/
    └── init.lua
    └── snippets/
        ├── c.lua
        ├── css.lua
          ...
    
```

I have this function in my `luasnip/init.lua`

```lua
local snippet_table = {}

local snip_dir = "./snippets"

local function get_fname(file) 
    return file:match "(.+)%..+$"
end

-- Pseudo code for what I want to achieve:

for file in snip_dir do
    local f_name = get_fname(file)
    local snippets = require(snip_dir .. f_name)
    snippet_table[f_name] = snippets[f_name]
end

luasnip.add_snippets(nil, snippets_table)
```

Each snippet file is returning a table as such:

```lua
return  {
     c = {
           -- snippets for c
    }
}
```

**Comment by L3MON4D3** [comment]
Oh check DOC.md, there's an extensive section on the lua-loader, it can handle files exactly like you want

**Comment by nikinbaidar** [comment]
> Oh check DOC.md, there's an extensive section on the lua-loader, it can handle files exactly like you want

Found exactly what I was looking for. The only downside I found was I had to define those short hands withing every file for the snippets to work properly.

**Comment by L3MON4D3** [comment]
It's possible to define shorthands which will be inserted into the global environment of those files, see `snip_env` (in the readme though :sweat_smile:, maybe some mentions in the doc too).
You might get warnings from your lsp though (it doesn't know we insert some global variables), but they can be [prevented](https://github.com/L3MON4D3/Dotfiles/blob/82e1df9a814c12a12e48b9b52bce3a1ff0e81225/.config/nvim/lua/plugins/lspconfig.lua#L169-L198)
