### ISSUE TITLE
Nested choices: How to use conditions within snippets

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#704]
I'm trying to create a snippet with two choice nodes and I want the second choice node to present me options based on what I chose in the first choice node. 

```lua
local famnam

famnam = function(index)
    return f(function(input)
        local prev_entry = input[1][1]
        if prev_entry == "John" 
        then
            return "Cena" -- Instead of a string return a choice node
        else
            return "No name"
        end
    end, {index})
end
```

My snippet definition looks as follows:
```lua

snippet("test", fmt("Given name: {}, Family name: {}", {
    c(1, {
        t "John",
        t "Michael"
    }), 
    famnam(1),
})),
```

Instead of a single returning a string from the  function_node I want to be able to return a list of choices through a choice node.:

```lua
return c(1, {
    t "Cena",
    t "Lenon",
    t "Bon Jovi",
```
How can I return a choice node instead of a single string?

**Comment by L3MON4D3** [comment]
Check out dynamicNode, it can return entire snippetNodes instead of text

**Comment by nikinbaidar** [comment]
> Check out dynamicNode, it can return entire snippetNodes instead of text

I tried using dynamic node, but I couldn't get the previous entry `prev_entry` like above.

**Comment by nikinbaidar** [comment]
> Check out dynamicNode, it can return entire snippetNodes instead of text

I tried using dynamic node, but I couldn't get the previous entry `prev_entry` like above.

**Comment by L3MON4D3** [comment]
Mhmm, that should work the same though.. Try inserting one of the examples in the wiki instead and work backwards from there. `print(vim.inspect(input))` might also help
