### ISSUE TITLE
Add conditional text node

### ISSUE THREAD

**Issue by clason** [L3MON4D3/LuaSnip#71]
Continuing in my quest for more "convenience nodes" to make writing snippets in LuaSnip's powerful syntax more convenient and concise, I'd like to suggest adding a "conditional text" that add text if and only if a placeholder is non-empty, so you could do something like
```
t"\usepackage", cond("[",2), i(2), cond("]",2), t"{", i(1), t"}"
```
which would expand to `\usepackage[bar]{foo}` in general but `\usepackage{bar}` if `$2` was left empty.

(One could generalize this with an arbitrary regex that is matched against the insert node, but this might be overkill?)

**Comment by L3MON4D3** [comment]
Ouh, regex/pattern sounds good! More general and all that :D
Yeah, I'll definitely add that :+1:

**Comment by clason** [comment]
With default "empty" so I don't have to remember that regex all the time :)

**Comment by L3MON4D3** [comment]
`match_insert(insert, pattern, invert)` with pattern default "^$", invert (insert if the pattern doesn't match) default false?

**Comment by clason** [comment]
So in my example, I'd have `m(2,"[")`?

**Comment by L3MON4D3** [comment]
> (Your signature is missing the node on which to match.)

Whoops, `match_insert(node_indx, insert, pattern, invert)` it is.
> So in my example, I'd have `m(2,"[")`?
> 
Yeah, that'd be it.

**Comment by clason** [comment]
Perfect.

**Comment by L3MON4D3** [comment]
I'm thinking, perhaps lambdas would be a good fit for this function. It would look a bit more convoluted (`m(_1:match("^$"), 2, "[")`, insert if the lambda does/not return nil), but we could add a simple match as a special case so we'd still cover simple cases. That would enable us to also do transforms beforehand and compensate a bit for the rather simple patterns of lua ie. by applying `match()` more than once.

**Comment by clason** [comment]
Again, my goal is to make the 90%-case as easy and concise as possible to write without having to remember regexes.

I know it's a bit more work (and, from what I gather from these discussions, doesn't appeal to you aesthetically), but you could think of adding _another_ layer on top of these for the simplest, most common case (kinda like you did for `rep` on top of `lambda`).

**Comment by clason** [comment]
Can lambda nodes be nested? So I could have conditional text that is generated from another insert node? Or is that something that is starting to strain the mould and should better be done using function or dynamic nodes?

**Comment by L3MON4D3** [comment]
> I know it's a bit more work (and, from what I gather from these discussions, doesn't appeal to you aesthetically), but you could think of adding _another_ layer on top of these for the simplest, most common case (kinda like you did for `rep` on top of `lambda`).

I'm not sure I get what you mean here, could you elaborate? (btw. I put `rep` into functions, no lambdas, just because it's _that_ simple)

**Comment by clason** [comment]
Something like (fuzzy on the exact syntax)
```
{i(1), m(2,{"{", l(_1:sub(3),1), ":"}), i(2), t"}"}
```
(And right, I forgot that `rep` is just `copy` renamed ;))

**Comment by leiserfg** [comment]
So `m` is not a functionNode but a dynamicNode?

**Comment by L3MON4D3** [comment]
> Can lambda nodes be nested? So I could have conditional text that is generated from another insert node? Or is that something that is starting to strain the mould and should better be done using function or dynamic nodes?

_Yes!_ Very much possible, even useful, though I have no good idea how to unite the syntaxes.

**Comment by clason** [comment]
To be honest, I don't fully understand the difference between the two -- I was just idly wondering how to write snippets using it and that came to mind. It may be just a distraction here -- best to focus on the common simple case for now.

**Comment by leiserfg** [comment]
functionsNodes  return  text,  dynamicNodes return  other nodes.

**Comment by L3MON4D3** [comment]
> Something like (fuzzy on the exact syntax)
> 
> ```
> {i(1), m(2,{"{", l(_1:sub(3),1), ":"}), i(2), t"}"}
> ```
> 
> (And right, I forgot that `rep` is just `copy` renamed ;))

What would this snippet do? Can't quite tell :sweat_smile:

**Comment by clason** [comment]
OK, I didn't want to derail the issue, but here's what I'm _really_ trying to set up:
```tex
\begin{<insert node 1>}\label{<first three letters of node 1>:<insert node 2>}
    <insert node 0>
\end{<repeat node 1>}
```
which, if <insert node 2> is left empty, reduces to
```tex
\begin{<insert node 1>}
    <insert node 0>
\end{<repeat node 1>}
```

**Comment by clason** [comment]
Oh, and maybe `o` for `optional` would be a good name?

**Comment by leiserfg** [comment]
One api could be
m(index,  match,  when_true:Option,  when_fasly:Option)
where  Option could be a function, a lambda or a text
if it's a function run it over the input, 
if it's a text, return it,
 if it's a lambda, compile it and run it over the text.

**Comment by L3MON4D3** [comment]
Sounds good, I would change match to also accept strings and turn those into `match`-lambdas on the first arg.

**Comment by clason** [comment]
Yes, that looks good! One suggestion, though: if you make it instead
```
m(index, when_true:Option, when_falsy:Option, match)
```
then you can make the last two optional (default to `""` and `"^$"`, respectively) and allow the ultra-short
```
m(2,"foo")
```
I originally suggested ;)

**Comment by L3MON4D3** [comment]
> `m(index, when_true:Option, when_falsy:Option, match)`

I don't really like that, if one would like to change the match but keep the default false eg. "" (which would be more common (I think) than the other way around), one would have to explicitly give that "".
I'd prefer `m(index, when_true:Option, match = "^$", when_fasly:Option = "")`, eg. having the parameters more likely to change earlier.
The `insert_if_empty(index, text)` can also be added, so you get your ultra-short version :wink:
(That wouldn't necessarily need lambdas, probably just drop it in `functions`)
(This really derailed quite a bit from the original, simple feature :D)

**Comment by clason** [comment]
Yeah, messing with the ordering to have "easy defaults" is not a good idea; there is better ways (such as adding a "simple" closure on top of it). And you are right that this should be treated as two requests in one:

1. Add a conditional text node with the full signature (I think it makes sense to go with full regex generality to allow doing more stuff) -- that could live in `extra`, like the lambdas.
2. If that is implemented, add a simple `match(index, text_if_index_is_nonempty)` closure -- that could live in `functions`, like the `rep` and `partial`.

**Comment by L3MON4D3** [comment]
Sounds reasonable, I wouldn't implement the simple `nonempty` using lambdas, but apart from that :+1:

(Sidenote: Assigning those functions based on implementation details (using lambdas or no?), as I've done before is pretty stupid, we have nodes in `functions` and nodes in `extras`, whereas a clearer separation would be to put _all_ (pseudo)nodes into extras and leave functions in `functions` (another breaking change :D))

**Comment by clason** [comment]
No, I didn't mean "lambda" as in the current `lambda`s, just a simple
```
nonempty = function(index, text)
return m(index, text, "^$", "")
end
```
And yes, no need to subdivide too much. My thinking was that you'd have (likely more as time progresses)
1. basic nodes like `t` and `f`,
2. "pseudonodes" like `lambda` and `match`,
3. "simplified nodes" like `rep` and `nonempty` that are just special cases of these,
so people could decide on the level of detail they want when importing.  But the only real benefit I guess is the additional namespace (so `simple.match` and `pseudo.match` could both have natural names).

And agreed on keeping (internal) functions and (pseudo)nodes separate.

**Comment by L3MON4D3** [comment]
> No, I didn't mean "lambda" as in the current `lambda`s, just a simple
> 
> ```
> nonempty = function(index, text)
>     return m(index, text, "^$", "")
> end
> ```

Ah, I wasn't quite clear, I would've implemented `nonempty` not using `m` (which may utilise lambdas), but as a simple pseudonode that doesn't require anything else. (eg. functionNode that checks for emtpy string and the returns supplied text.)

I don't really see the difference between 2. and 3., especially since the current `match` would work with both strings and lambdas.

**Comment by clason** [comment]
Yep, that makes sense, too. And if there's no real difference, then there's indeed no point in introducing one. I shouldn't have moved into implementation/design details with my request -- just ignore that part; you know best ;)

**Comment by L3MON4D3** [comment]
Okay, after #84 and 0c5ff48 this issue can be closed, right?

**Comment by clason** [comment]
Yes indeed, thank you! That looks like a very nice and powerful design. Now I can do (`stylua` is wasteful with space...)
```lua
    s('eq', {
        t '\\begin{equation',
        m(1, '^$', '*', ''),
        t '}',
        n(1, '\\label{eq:'),
        i(1),
        n(1, '}'),
        t { '', '\t' },
        i(0),
        t { '', '\\end{equation' },
        m(1, '^$', '*', ''),
        t { '}', '' },
      }),
```

**Comment by clason** [comment]
(which can possibly be simplified using the `match` node)

**Comment by clason** [comment]
Yep:
```lua
s('eq', {
  m(1, '^$', '\\begin{equation*}', '\\begin{equation}\\label{eq:'),
  i(1),
  n(1, '}'),
  t { '', '\t' },
  i(0),
  m(1, '^$', '\n\\end{equation*}', '\n\\end{equation}'),
}),
```
