### ISSUE TITLE
Help jumping upwards and then laterally between nested Fmt/Choice nodes

### ISSUE THREAD

**Issue by jtws** [L3MON4D3/LuaSnip#715]
This isn't a bug report but a feature/usage question. I have a use case I don't know how to implement. I have a half-working solution and I feel like I'm doing this wrong or missing something basic here. See below for the use case, problem description, example code, and summary.

I'm running LuaSnip from master as it has the new logging feature and enabled debug logs but didn't find anything helpful there. I also have my own log function I'm using to inspect func node args and parent snippet, etc. and have taken a look at the LuaSnip API which I think could solve my problem if I queried nodes via the API and implemented some custom bindings or something. But I'd imagine that's not necessary for this use case which I assume is rather common.

## Use-case

I want a node for all Lua types, and all annotations sumneko_lua LSP supports. Basic types, list, table, fun, union, etc.
I'm writing snippets for EmmyLua annotations like `---@param <name> <type> <desc>` and want `<type>` to be a node allowing me to browse through all possible types. Ideally, I'd be able to nest arbitrarily deep and always have the full range of types available as choices for a `<type>` field. Think of a func taking a table with func values returning lists of dicts with table values, etc. I tried implementing this with small composable functions returning nodes but it's not working. The problem description is below and the example code follows that.

## Problem

I can kinda hack it with functions returning a specific complex type node implemented as an `fmt` node with embedded `ChoiceNodes` for type fields, and by having an "all types" function which returns a choice node with an insert node (to stop LuaSnip from entering the embedded `ChoiceNodes`, and then a list of `FmtNodes` for complex types each embedding `ChoiceNodes`. I can enter the choice picker at the `InsertNode` and choose any of the `FmtNodes` to input say a `fun` or `table<>` type. Each `FmtNode` includes `ChoiceNodes` for `<type>` fields and `InsertNodes` for descriptions.

All is kinda well so far. But once I enter one of the `FmtNodes` implementing a complex type like `fun(<param>: <type>, ...): <type>` I can't back up to the level with all the other `FmtNodes` to choose a different complex type, say `table<<type>, <type>>`. If I jump `-1` it takes me out of the snippet, not to the `InsertNode` I started at, if I re-enter the snippet I end up in the same `FmtNode` and its `<type>` field `ChoiceNode` with no way to back up a level.

I tried `expand_or_jump`, `jump`, `locally_jumpable` and all combinations, different bindings for jumps and expanding, etc. but nothing lets me get back to a higher level within the snippet hierarchy. Once you're at the bottom you're stuck there in that `FmtNode` and can only move laterally.

## Minimal code example

<details><summary>Example of a nested type snip nodes</summary>

```lua
-- The core of the implementation, a ChoiceNode with basic types and configurable jump index.
function c_type(jump_index)
    jump_index = jump_index or 1
    return c(jump_index, {
        i(nil, "string"),
        i(nil, "number"),
        i(nil, "function"),
        i(nil, "table"),
        i(nil, "boolean"),
        i(nil, "nil"),
        i(nil, "any"),
        i(nil, "integer"),
        i(nil, "thread"),
        i(nil, "userdata"),
        i(nil, "lightuserdata"),
    })
end

-- FmtNode wrapping c_type's ChoiceNode
function fmt_type_basic()
    return fmt("{}", {
        c_type(1),
    })
end

-- FmtNode for a dict annotation using c_type for two fields
function fmt_type_dict()
    return fmta("{ [<>]: <> }", {
        c_type(1),
        c_type(2),
    })
end

-- FmtNode for a table annotation using c_type for two fields
function fmt_type_table()
    return fmt("table<{k}, {v}>", {
        k = c_type(1),
        v = c_type(2),
    })
end

-- FmtNode for a function using c_type and another nested ChoiceNode for cycling return type/no return
function fmt_type_fun()
    return fmt("fun({param}: {type}){maybe_return}", {
        param = i(1, "param"),
        type = c_type(2),
        maybe_return = c(3, {
            fmt(": {}", {
                c_type(1),
            }),
            t(""),
        }),
    })
end

-- These are like the ones above
--fmt_type_union() ...
--fmt_type_list()...

-- Returns a ChoiceNode supposed to let me pick any complex or basic type and switch between them.
-- The InsertNode is first as otherwise, LuaSnip enters the first FmtNode when entering this ChoiceNode
-- and the problem is I can't get back up to this level from the FmtNode (with nested ChoiceNodes).
-- I can use the choice picker at the InsertNode to choose any of the complex types which work fine,
-- but once I select a FmtNode choice and enter it I don't know how to get back to this "level 1" ChoiceNode
-- to choose a different type should I change my mind.
--
-- I want to seamlessly jump between all node types up and down, left and right and have no idea how.
-- I can only jump laterally inside the selected FmtNode. History is enabled and activation on TextChanged,
-- TextChangedI. I also tried deletion on TextChanged as suggested in the docs but it made no difference.
function c_type_all(jump_index)
    jump_index = jump_index or 1
    return c(jump_index, {
        i(1, "[<C-F> select type]"), -- choice picker key, let's me choose between the fmt nodes, otherwise I enter one instantly
        fmt_type_basic(), -- if I enter here I end up in the `ChoiceNode` within this `FmtNode` and can't get back to this level
        fmt_type_table(), -- if I change my mind, I want to jump from fmt_type_basic to this node and input a table type
        fmt_type_dict(), -- or change my mind yet again and insert a dict instead
        fmt_type_fun(), -- or a fun ...
        --fmt_type_union(),
        --fmt_type_list(),
    })
end

-- Example snippet using c_type_all
    s(
        { trig = "dalias", name = "---@alias line", dscr = "---@alias <name> <type>" },
        fmt("---@alias {} {}", {
            i(1, "name"),
            c_type_all(2), -- once I enter this I'm at the "[<C-F> select type]" insert node, if I choose a type FmtNode I'm stuck there
                                    -- and can't get out to choose a different complex type.
        })
    ),
```
</details>

Ideally in all snippets `<type>` field would be `c_type_all()` so that I can nest a `table<<t>, <t>>` in a `fun(<p>: <t>): <t>`. Right now I can only input basic types within the complex type nodes.

But the main problem is not being able to move "up" in the snippet hierarchy even with history enabled. I can only move laterally and exit/re-enter the same snippet but can't figure out how to jump upwards.

Maybe my implementation is the problem, but I tried wrapping complex types in `SnippetNodes` which made no difference. My goal is to create small composable functions to create composable snippets and nodes and keep my snippet code DRY. How do you think I should approach and implement this since the current approach clearly isn't working? I need a way to move between choice nodes at the same index.

Overall I feel I'm missing something basic here. I've been using LuaSnip for a while and find `FunctionNodes` and `Lambdas`/`DynamicLambdas` really helpful, but haven't found a use for them in this use-case which is more about nested (preferably recursive) choices. Ideally, I'd like to choose a `fun(<p>: <T>): <T>` snippet, insert a `table<<T>, <T>>` as its param type, set the second table `<T>` to a dict `{ [k]: <T> }` and use a basic type picker for that `<T>`. All while staying in the snippet and just moving between `ChoiceNodes` and `FmtNodes` and cycling choices or using the picker.

Any tips and guidance are welcome and do tell me if I'm misusing LuaSnip features or missing something basic.

**Comment by L3MON4D3** [comment]
Oh very cool!
Okay, I think the main issue is just that you have to add some more insertNodes in eg. `fmt_type_basic`, since there's currently no isnertNode on that "level".
You might also want to take a look at the recursive dynamicNode in the wiki (first example in "cool snippets" iirc), that could enable your usecase.

**Comment by jtws** [comment]
> Oh very cool! Okay, I think the main issue is just that you have to add some more insertNodes in eg. `fmt_type_basic`, since there's currently no isnertNode on that "level".
I tried setting fmt `strict = false` and adding insert nodes but that made no difference. Also the first node in the fmt wrapping function type is an insert node for param name, and in "type_all" the first node is an insert node, and I still can't ump from the function type fmt node up to the "all type" insert node I started at. Or did you mean to add insert nodes on same level as fmt nodes. In that case they should be wrapped in `SnippetNodes` if returned from a func, right?

> You might also want to take a look at the recursive dynamicNode in the wiki (first example in "cool snippets" iirc), that could enable your usecase.

Thanks, I have it in my library but used it just for lists. Need to have a closer look, there's also a note next to it the wiki that the [external update DynamicNode](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#dynamicnode-with-user-input) is more capable, Not sure how but will need to look into it as well.

**Comment by L3MON4D3** [comment]
> I tried setting fmt strict = false and adding insert nodes but that made no difference.

`strict=false` should not be necessary, did you get errors with it enabled?

> Also the first node in the fmt wrapping function type is an insert node for param name, and in "type_all" the first node is an insert node, and I still can't jump from the function type fmt node up to the "all type" insert node I started at.

true, that should work.. Generally, you'd have to make sure that every choice of a choiceNode has an insertNode immediately inside it, only then can you jump back into it, and change the choice.

**Comment by L3MON4D3** [comment]
> Thanks, I have it in my library but used it just for lists. Need to have a closer look, there's also a note next to it the wiki that the external update DynamicNode is more capable, Not sure how but will need to look into it as well.

ah, nice :+1:
Yeah the external update dynamicNode is more capable, but it's features only really help if one wants to repeat certain nodes an unlimited number of times, here, with different nodes, choiceNodes combined with dynamicNodes should work very well.
