### ISSUE TITLE
Add "simple" function node

### ISSUE THREAD

**Issue by clason** [L3MON4D3/LuaSnip#72]
This one is more borderline in usefulness, but may be nice to have: A "simple" function node that just inserts the output of a Lua statement, e.g.,
```
a(os.date('%Y-%m-%d'))
```
as syntactic sugar for 
```
f(function() return os.date '%Y-%m-%d' end, {})
```

**Comment by leiserfg** [comment]
That does not work, one can delay the execution of the function, if that's not important to you, then just use a text node.
`t{os.date( '%Y-%m-%d')}`

**Comment by leiserfg** [comment]
Another way could be to use the lambdas to do that, I can add more functions to the lambda module.

**Comment by gegoune** [comment]
Is above `os.date` evaluated at the time of running snippet or initialising luasnip? So if I open nvim today and will try to use that snippet tomorrow, will I get today's or tomorrow's date?

**Comment by leiserfg** [comment]
Remember to restart the editor at midnight :smile:

**Comment by clason** [comment]
Oh, I didn't know text nodes could do that! (Maybe add that to the examples?)

Just to make sure: by "can't delay execution" you mean that the `os.date` is evaluated when the snippet is set up, not when it is executed?

Yes, a `lambda` for that would also work, of course.

**Comment by L3MON4D3** [comment]
How about `a(os.date, "%Y-%m-%d")`? Just put all args after the first into the function, should be straightforward.

**Comment by L3MON4D3** [comment]
> Oh, I didn't know text nodes could do that! (Maybe add that to the examples?)
> 
> Just to make sure: by "can't delay execution" you mean that the `os.date` is evaluated when the snippet is set up, not when it is executed?
> 
> Yes, a `lambda` for that would also work, of course.

Yup, when it's set up

**Comment by clason** [comment]
To be clear, the execution at expansion time (which the "long" function node does, right?) is the salient point here.

**Comment by L3MON4D3** [comment]
> Another way could be to use the lambdas to do that, I can add more functions to the lambda module.

I feel like that's overkill, isn't it? Would it have benefits over the simple approach I suggested?

**Comment by L3MON4D3** [comment]
> To be clear, the execution at expansion time (which the "long" function node does, right?) is the salient point here.

Yeah, I feel like evaluating at "compile time" is not what users would expect from that function.

**Comment by clason** [comment]
Especially since the text node already supports that with as nice a syntax as you could hope for :)

**Comment by leiserfg** [comment]
> > Another way could be to use the lambdas to do that, I can add more functions to the lambda module.
> 
> I feel like that's overkill, isn't it? Would it have benefits over the simple approach I suggested?

Lambda has already a way of adding extra functions, I'm not saying is better than your approach, just bringing some options.

**Comment by clason** [comment]
FWIW, as long as there's no noticeable performance difference, leveraging the lambda module for more features sounds like a reasonable goal.

**Comment by L3MON4D3** [comment]
Ah okay, gotcha. What would the syntax look like with lambda? Just `l(_1:date("..."))`

**Comment by L3MON4D3** [comment]
Then again, is it possible to use users local functions in lambdas?

**Comment by clason** [comment]
Don't forget, the original request was for "simple" functions ;)

**Comment by leiserfg** [comment]
with lambdas one can do
```lua
local date  = l.register(os.date)
l(date(_1), {})
```

**Comment by L3MON4D3** [comment]
Okay, I think I'd rather implement the simple approach with argument forwarding, seems more direct to me.

**Comment by leiserfg** [comment]
How should we call it? `partial`?

**Comment by L3MON4D3** [comment]
I was thinking `direct_function`, users can always abbreviate to `a` or something.

**Comment by leiserfg** [comment]
I said partial a that's technically the same as creating a partial function and pass it to a function node, so the naming matches the implementation :smile: and it can be abbreviated as `p`, but we should not t start a poll for that :smile:

**Comment by L3MON4D3** [comment]
Damn, we're running out of letters xD
Okay, I can see that, let's go with `partial`, `d` is taken after all :D
