### ISSUE TITLE
Error when completing: `attempt to call local 'snip_info' (a number value)`

### ISSUE THREAD

**Issue by oncomouse** [L3MON4D3/LuaSnip#720]
I updated to the last version of LuaSnip and am now getting the following error when I finish completion  (I got it first when using dictionary completion with `<C-X><C-K>`):

~~~
Error detected while processing CompleteDone Autocommands for "*":
Error executing lua callback: ...packer.nvim/pack/packer/opt/LuaSnip/lua/luasnip/ini
t.lua:75: attempt to call local 'snip_info' (a number value)
stack traceback:
        ...packer.nvim/pack/packer/opt/LuaSnip/lua/luasnip/init.lua:75: in function
'available'
        [string "..."]: in function <[string "..."]:0>
~~~

Not sure why it's happening, but it seems related to the [open_snippet_list](https://github.com/L3MON4D3/LuaSnip/commit/ded828ba29fc22ad7b94ed79319489ad9f24ee58#diff-3b6e8ac5efb8bcebe79ef60c53103336dc47a302e8b97d3343ebbd56a3917282) feature that was just merged.

**Comment by L3MON4D3** [comment]
Oh, okay: we added an option to `ls.available`, it now accepts an optional function instead of no arguments.
I was not aware ppl were calling it with superfluous arguments (a number in your case, IIUC).
Could you confirm that this is the case, or share the source-code of your autocompletion?

**Comment by L3MON4D3** [comment]
(oh, and the fix is to not pass any arguments, the default should work just fine)

**Comment by oncomouse** [comment]
Ah! Sorry, I didn't realize this was coming from my code, not something that changed in the plugin. I have the following in my LuaSnip config:

~~~
	vim.api.nvim_create_autocmd("CompleteDone", {
		group = augroup,
		callback = function()
			if ls.available(1) then
				ls.expand()
			end
		end,
	})
~~~

I don't remember where I got that from (possibly the wiki a while ago), but removing the `1` fixes the error I was seeing.

**Comment by L3MON4D3** [comment]
Very subtle, unfortunately :sweat_smile:
I won't make it a breaking change retroactively, but I'll have to keep in mind that there's nothing wrong with calling a function with more arguments than it currently has
