### ISSUE TITLE
Error loading LuaSnip

### ISSUE THREAD

**Issue by LyzeOfKiel** [L3MON4D3/LuaSnip#725]
After loading LuaSnip (used by [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim)) neovim throws errors if it is started in non-sudo mode. While, running it with sudo, e.g. `sudo nvim .`, it functions normally. Provided example errors below.
Error after loading neovim:
```
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua ...ck/packer/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:29: loop or previous error loading module 'luasnip'
stack traceback:
        [C]: in function 'require'
        ...ck/packer/start/LuaSnip/lua/luasnip/loaders/from_lua.lua:29: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua ...cker/start/LuaSnip/lua/luasnip/loaders/from_snipmate.lua:1: loop or previous error loading module 'luasnip'
stack traceback:
        [C]: in function 'require'
        ...cker/start/LuaSnip/lua/luasnip/loaders/from_snipmate.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:1: loop or previous error loading module 'luasnip'
stack traceback:
        [C]: in function 'require'
        ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:1: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```
Error after using telescope keys:
```
Error detected while processing BufWipeout Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'luasnip'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_delete'
        ...pack/packer/start/telescope.nvim/lua/telescope/utils.lua:322: in function 'buf_delete'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:345: in function '_teardown_func'
        ...rt/telescope.nvim/lua/telescope/previewers/previewer.lua:78: in function 'teardown'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1474: in function 'on_close_prompt'
        ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:134: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:338: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

System: `MacOS Ventura 13.1`
Nvim version: `v0.8.2`

**Comment by L3MON4D3** [comment]
Since sudo makes the difference, luasnip might be installed in a wrong/unexpected/incompatible location.
Could you post the output of `:lua =package.path` in both sudo and non-sudo mode? (prints the paths lua searches for a `require`d package)

**Comment by L3MON4D3** [comment]
True, they're equal..
Could you show `:lua = vim.o.runtimepath` in both scenarios?

**Comment by L3MON4D3** [comment]
(`lua`-directories in `runtimepath` are also searched while `require`ing IIRC, so any difference there could also indicate an issue)

**Comment by LyzeOfKiel** [comment]
@L3MON4D3 
These two also look identical
Without sudo:
```
/Users/leonidtyurin/.config/nvim,/usr/local/etc/xdg/nvim,/etc/xdg/nvim,/Users/leonidtyurin/.local/share/nvim/site,/Users/leonidtyurin/.local/share/nvim/site/pack/packer/start/packer.nvim,/Users/leonidtyurin/
.local/share/nvim/site/pack/*/start/*,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/0.8.2/share/nvim/runtime,/usr/local/Cellar/neovim/0.8.2/share/nvim/runtime/pack/dist/opt/matchit,
/usr/local/Cellar/neovim/0.8.2/lib/nvim,/Users/leonidtyurin/.local/share/nvim/site/pack/*/start/*/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/Users/leonidtyurin/.local/share/nvim/site/a
fter,/etc/xdg/nvim/after,/usr/local/etc/xdg/nvim/after,/Users/leonidtyurin/.config/nvim/after
```

With sudo:
```
/Users/leonidtyurin/.config/nvim,/usr/local/etc/xdg/nvim,/etc/xdg/nvim,/Users/leonidtyurin/.local/share/nvim/site,/Users/leonidtyurin/.local/share/nvim/site/pack/packer/start/packer.nvim,/Users/leonidtyurin/
.local/share/nvim/site/pack/*/start/*,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/0.8.2/share/nvim/runtime,/usr/local/Cellar/neovim/0.8.2/share/nvim/runtime/pack/dist/opt/matchit,
/usr/local/Cellar/neovim/0.8.2/lib/nvim,/Users/leonidtyurin/.local/share/nvim/site/pack/*/start/*/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/Users/leonidtyurin/.local/share/nvim/site/a
fter,/etc/xdg/nvim/after,/usr/local/etc/xdg/nvim/after,/Users/leonidtyurin/.config/nvim/after
```

**Comment by L3MON4D3** [comment]
Okay, those were my ideas for this :sweat_smile:
I don't think this is an issue with luasnip itself, so you might find a way to fix this in other repos.

Oh, one last: maybe permissions are/ownership is messed up somehow? If luasnip was installed with sudo, perhaps your regular user cannot access its directories?

**Comment by LyzeOfKiel** [comment]
@L3MON4D3 after some debugging I found the issue. Don't know if it is related to LuaSnip itself or it is my system's problem.
The problem was that this [file descriptor](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/util/log.lua#L16) at `log.lua` was `nill`. Then, I checked permissions of this file and it was read-only in user mode. After I added write permission for user everything works fine without sudo. Wdyt?
<img width="434" alt="Screenshot 2023-01-16 at 11 07 50" src="https://user-images.githubusercontent.com/24493591/212617957-f0925d66-09be-45da-ae35-b5f1b18adfae.png">

**Comment by LyzeOfKiel** [comment]
A little more details:
After I deleted `luasnip.log` and restarted nvim in non-sudo mode, then everything worked fine. This file was re-created with the same permissions as it was initially (`.rw-r--r--`) and there were no errors on startup 🪄.

**Comment by L3MON4D3** [comment]
Ahhhh, that makes sense, nice job :+1:
I think I'll have `log.lua` print a warning if it can't open `luasnip.log`, that should make issues like obvious (failing silently if the log doesn't work seems worse)

**Comment by belakm** [comment]
I had the same errror just now. I get LuaSnip via AstroVim and the issue resolved after reinstalling LuaSnip when updating AstroVim.
