### ISSUE TITLE
[question] Same trigger different behavior depending on location?

### ISSUE THREAD

**Issue by frankli998** [L3MON4D3/LuaSnip#729]
As a newbie I don't know if it's possible to trigger different nodes using same trigger, and a previous issue called "dynamic trigger" may be also refering to this.

Below is a usecase, If I am not sure how many people will come to my party, but now I want to write an invitation. What I want to accomplish is when I press a common trigger(maybe enter), if I am in greeting area, repeat template1, else if I am in greeting area, repeat template2.

The benefits is obvious, I don't have to create snippets for those two template and memorizing their triggers, it's handdy to extend content using common trigger.

>This is greeting:
>Hello, [insert_node: somebody]!             (<-template1)
>
>This is good bye:
>Goodbye,[insert_node: somebody]!        (<-template2)

I have tried to use case_node inside case node to try to achieve this somehow, but it seems invalid and throws errors.

Any clue how to done this? Thanks in advance.

**Comment by L3MON4D3** [comment]
Alternatively (to the ideas in `luasnip-tutorial`), use [`condition`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets) to mutually exclude snippets with the same trigger.

**Comment by frankli998** [comment]
```lua  
  local input = s(
    {trig = "(input .*,)", regTrig = true },{
    d(1, function(_, snip)
        return sn(1,   fmt([[
{}
input [{} - 1:0] {}]],{t(snip.captures[1]), i(1,"WIDTH"), i(2,"SIGNAL")}))
    end)
  }
  )
  table.insert(autosnippets, input)

  local output = s(
    {trig = "(output .*,)", regTrig = true },{
    d(1, function(_, snip)
        return sn(1,   fmt([[
{}
output [{} - 1:0] {}]],{t(snip.captures[1]), i(1,"WIDTH"), i(2,"SIGNAL")}))
    end)
  }
  )
  table.insert(autosnippets, output)
```

A sampe I did to replicate lines that starts with input and ends with ","
The concept is add two types of new lines are all triggered by typing ",", but actually use regTrig to make them differ from each other. I hope this helps somebody.
