### ISSUE TITLE
Bug report: Luasnip_current_nodes (nil value)

### ISSUE THREAD

**Issue by NTBBloodbath** [L3MON4D3/LuaSnip#73]
Hey, I've been getting some bug reports regarding to errors triggered by `LuaSnip` when running commands like `Telescope` or `PackerSync`. After debugging for a while I've found that `LuaSnip` was working fine until the commit `c1ed401f8281925f5cc842e29767656e5c8e7735` was pushed and the line that is causing this error is [L#26](https://github.com/L3MON4D3/LuaSnip/blob/c1ed401f8281925f5cc842e29767656e5c8e7735/lua/luasnip/config.lua#L26).

Hope that information can help to debug and fix this behavior. Thanks in advance!

**Comment by L3MON4D3** [comment]
Oh, thanks for reporting.
That weird though, `Luasnip_current_nodes` is global, I wonder what causes it to be `nil`.

**Comment by L3MON4D3** [comment]
When does the Error occur with telescope? Just `:Telescope find_files` works for me.

**Comment by L3MON4D3** [comment]
I pushed a fix that should prevent this _particular_ error, but I'm not sure where exactly it comes from.

**Comment by NTBBloodbath** [comment]
> When does the Error occur with telescope? Just `:Telescope find_files` works for me.

It was happening with just `:Telescope`, `:Telescope oldfiles` and some others like `:Telescope man_pages`. Strangely `:Telescope colorscheme` and `:Telescope find_files` do work :thinking:

**Comment by NTBBloodbath** [comment]
> I pushed a fix that should prevent this _particular_ error, but I'm not sure where exactly it comes from.

Alright, let me give it a try and I'll be back to you!

**Comment by NTBBloodbath** [comment]
Working like a charm now, thank you so much for the quick fix!

**Comment by L3MON4D3** [comment]
> > When does the Error occur with telescope? Just `:Telescope find_files` works for me.
> 
> It was happening with just `:Telescope`, `:Telescope oldfiles` and some others like `:Telescope man_pages`. Strangely `:Telescope colorscheme` and `:Telescope find_files` do work

Weird, those work alright for me as well. I don't use `packer`, maybe it loads plugins differently from `vim-plug`, though I'd expect global lua tables to stay global.

**Comment by L3MON4D3** [comment]
> Working like a charm now, thank you so much for the quick fix!

NP :D
