### ISSUE TITLE
postfix snippets not appearing as completions if there's lsp or overwritten (`luasnip`, `nvim-cmp`, `lsp-zero`)

### ISSUE THREAD

**Issue by mnpqraven** [L3MON4D3/LuaSnip#731]
I've been trying to make postfix snippets work but right now they're not appearing as I imagine if the LSP source is loaded, then the lsp source will overwrite the snippets and I can't select the my postfix snippets

Here are 2 screencasts with the snippets, in the Typescript one I can see my snippet (`.val`) if i just write it raw on a new line and can see it along with other completions from lsp, but it doesn't appear when I type `.` after a variable which is the actual intended usage. 

https://user-images.githubusercontent.com/8957788/213252160-e235cc53-43cb-40f2-8212-96875258dd11.mp4

In this Rust screencast I tried to do the same and still get my snippets when I write it alone but since the rust lsp is slower(??) than tsserver I managed to see all my postfix snippet when i type `.` after a variable but then the window is overwritten by the LSP completions.

https://user-images.githubusercontent.com/8957788/213252179-0672f09e-61ec-4029-9b0a-6599e8fb939f.mp4

**Comment by mnpqraven** [comment]
I've managed to reproduce this with a minimal configuration below with the screencast. The LuaSnip snippets will flicker for a moment before getting overwritten by the LSP window if i delete a `.` after writing `find..`. This will happen if I set both sources to have the same `keyword_length` in the cmp setup.
Is this generally considered bad practices that should be avoided or unintended behavior ? I can still temporarily still see both completions if i have luasnip's `keyword_length` at 1 and the lsp at 2 but then I can't see any result from the lsp after typing exactly one character after `.`

https://user-images.githubusercontent.com/8957788/213341962-b654ed85-b159-440b-bdc4-08c0f5d1c9e7.mp4


```lua
vim.g.mapleader = " "
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)


require("lazy").setup({
  "folke/which-key.nvim",
  {
  'VonHeikemen/lsp-zero.nvim',
  dependencies = {
    {'neovim/nvim-lspconfig'},
    {'williamboman/mason.nvim'},
    {'williamboman/mason-lspconfig.nvim'},
    {'hrsh7th/nvim-cmp'},
    {'hrsh7th/cmp-nvim-lsp'},
    {'hrsh7th/cmp-buffer'},
    {'hrsh7th/cmp-path'},
    {'saadparwaiz1/cmp_luasnip'},
    {'hrsh7th/cmp-nvim-lua'},
    {'L3MON4D3/LuaSnip'}, },
  },
  {
    "windwp/nvim-autopairs",
    config = function()
      require("nvim-autopairs").setup()
    end
  },
})

-- LSP CONFIG
local lsp = require('lsp-zero')
lsp.preset('recommended')
lsp.ensure_installed({
  'tsserver',
  'rust_analyzer',
})
lsp.setup()

-- CMP CONFIG
local cmp = require('cmp')
local cmp_config = lsp.defaults.cmp_config({
  sources = {
    { name =  'luasnip', keyword_length = 1 },
    { name = 'nvim_lsp', keyword_length = 1 },
  }, {
    { name = 'buffer' },
  },
})
cmp.setup(cmp_config)

-- LUASNIP CONFIG
local ls = require("luasnip")
local postfix = require("luasnip.extras.postfix").postfix
local f = ls.function_node

ls.add_snippets('all', {
	postfix(".val", {
	f(function(_, parent)
		return "Vec<" .. parent.snippet.env.POSTFIX_MATCH .. ">"
	end, {})})
})

```

**Comment by L3MON4D3** [comment]
It's a bit strange that this only happens with postfix-snippets (does it?), but I'm afraid this issue would have a better chance of getting a solution in `nvim-cmp`, or `cmp_luasnip`, though I don't think the source is at fault.
