### ISSUE TITLE
[Question] LaTeX matrices snippet. May I ask for a little help modifying an already working snippet.

### ISSUE THREAD

**Issue by JxJxxJxJ** [L3MON4D3/LuaSnip#733]
I found this snippet which is very hacky to my understanding 

```lua
 -- LaTeX: Matrices
  s({ trig = "([pbv])mat_(%d)(%d)", regTrig = true }, {
    d(1, function(_, snip)
      local type = snip.captures[1] .. "matrix"
      local rows, cols = snip.captures[2], snip.captures[3]
      local nodes = {}
      local ts = 1
      table.insert(nodes, t("\\begin{" .. type .. "}"))
      for _ = 1, rows, 1 do
        table.insert(nodes, t({ "", "\t" }))
        for _ = 1, cols, 1 do
          table.insert(nodes, i(ts))
          table.insert(nodes, t(" & "))
          ts = ts + 1
        end
        table.remove(nodes, #nodes)
        table.insert(nodes, t(" \\\\"))
      end
      table.remove(nodes, #nodes)
      table.insert(nodes, t({ "", "\\end{" .. type .. "}" }))
      return sn(1, nodes)
    end),
  }, { condition = in_mathzone }),
```
Which to ilustrate works like this 
![Peek 19-01-2023 23-47](https://user-images.githubusercontent.com/103049321/213607321-59e0939a-6cbd-4843-abe8-9602c82a19a4.gif)

But I have a little patch that lets you align columns in matrices like this
```tex
\begin{bmatrix}[rrr|c]
& & & \\
& & & \\
& & & \\
\end{bmatrix}
```
 which is an augmented matrix with the last column centered and all the rest right aligned. This is to work with negative numbers for example:
![image](https://user-images.githubusercontent.com/103049321/213607592-cc1dc56e-df5d-4d60-b3bf-c049fd88bd97.png)

So my question is, how could I modify the snippet above so it appends `[rr...r]` to `\begin{bmatrix}` for each column?

**Comment by L3MON4D3** [comment]
Okay I would
1. extract begin and end out of the dynamicNode, add a choiceNode with the possible matrix-types inside begin, and copy the content of that choiceNode in end
2. Add a few textNodes and an insertNode for the column-types

Are you familiar with `fmt`? It makes writing snippets much more comfortable (and the result much more readable!!).
[An example, just with a different dynamicNode](https://github.com/L3MON4D3/Dotfiles/blob/d00100eeae4459b8a76b0330dcc92b84716f4bea/.config/nvim/luasnippets/tex.lua#L106)

**Comment by JxJxxJxJ** [comment]
I ended up doing ```lua
s({ trig = "([bpv])mat_(%d)(%d)", regTrig = true, snippetType = "autosnippet" }, {
  d(1, function(_, snip)
    local type = snip.captures[1] .. "matrix"
    local rows, cols = snip.captures[2], snip.captures[3]
    local nodes = {}
    local ts = 1
    local col_spec = string.rep("r", cols)
    table.insert(nodes, t("\\begin{" .. type .. "}[{" .. col_spec .. "}]"))
    for _ = 1, rows, 1 do
      table.insert(nodes, t({ "", "\t" }))
      for _ = 1, cols, 1 do
        table.insert(nodes, i(ts))
        table.insert(nodes, t(" & "))
        ts = ts + 1
      end
      table.remove(nodes, #nodes)
      table.insert(nodes, t(" \\\\"))
    end
    table.remove(nodes, #nodes)
    table.insert(nodes, t({ "", "\\end{" .. type .. "}" }))
    return sn(1, nodes)
  end),
}, { condition = in_mathzone })
```
