### ISSUE TITLE
[Question] Async Functions

### ISSUE THREAD

**Issue by sanchit1053** [L3MON4D3/LuaSnip#736]
Is is possible in luasnip to run the function node asynchronously to the text in another insert node,
Currently the text is updated only on moving on from the node

**Comment by leiserfg** [comment]
https://github.com/L3MON4D3/LuaSnip#config
> `update_events`: Choose which events trigger an update of the active nodes' dependents. Default is just 'InsertLeave', 'TextChanged,TextChangedI' would update on every change.
