### ISSUE TITLE
Cannot regexp edit vscode snippet

### ISSUE THREAD

**Issue by otavioschwanck** [L3MON4D3/LuaSnip#739]
i have the following snippet:
```json
{
    "New Rails RSPEC clean file": {
        "prefix": "template_test",
        "description": "Rails new rspec clean file with less codes",
        "body": [
            "# frozen_string_literal: true",
            "",
            "require 'rails_helper'",
            "",
            "RSpec.describe ${TM_FILENAME_BASE/((^[a-z])|_([a-z]))/${2:/upcase}${3:/upcase}/g}, type: $1 do",
            "",
            "\t$0",
            "",
            "end",
            ""
        ]
    }
}
```

the file_name, instead of going camelCase like myClassHere.  It keeps being snake case like my_class_here.

How can i do this with LuaSnip?

**Comment by L3MON4D3** [comment]
We're on the verge of having the `/camelcase`-transformation, see #735 :D
Until then, I think the capture group containing the two inner capture groups is unnecessary, and does it work in vscode?

**Comment by otavioschwanck** [comment]
> We're on the verge of having the `/camelcase`-transformation, see #735 :D Until then, I think the capture group containing the two inner capture groups is unnecessary, and does it work in vscode?

it works.

After the merge, i tried:

```json
{
    "New Rails RSPEC clean file": {
        "prefix": "template_test",
        "description": "Rails new rspec clean file with less codes",
        "body": [
            "# frozen_string_literal: true",
            "",
            "require 'rails_helper'",
            "",
            "RSpec.describe ${TM_FILENAME_BASE/(.*)$/camelCase/}, type: $1 do",
            "",
            "\t$0",
            "",
            "end",
            ""
        ]
    }
}
```

but still not converts

**Comment by L3MON4D3** [comment]
Oh, do you have `jsregexp` installed? If not, `DOC.md` has a short guide

**Comment by otavioschwanck** [comment]
> Oh, do you have `jsregexp` installed? If not, `DOC.md` has a short guide

@L3MON4D3 it worked!  Thanks.

A tip here is to put the run by default on the README.

Thanks for your help!

**Comment by L3MON4D3** [comment]
Nice!
Ah, yeah putting it right there would make it more visible.. I'll consider it

**Comment by L3MON4D3** [comment]
Added them (94f192c), thanks for the idea :)
