### ISSUE TITLE
$MYVIMRC nil value

### ISSUE THREAD

**Issue by danielnehrig** [L3MON4D3/LuaSnip#74]
apparently $MYVIMRC is not set which throws at
LuaSnip/lua/luasnip/loaders/from_vscode.lua:168

:h $MYVIMRC
```
						*VIMINIT* *EXINIT* *$MYVIMRC*
     b. Locations searched for initializations, in order of preference:
	-  $VIMINIT environment variable (Ex command line).
	-  User |config|: $XDG_CONFIG_HOME/nvim/init.vim.
	-  Other config: {dir}/nvim/init.vim where {dir} is any directory
	   in $XDG_CONFIG_DIRS.
	-  $EXINIT environment variable (Ex command line).
	|$MYVIMRC| is set to the first valid location unless it was already
	set or when using $VIMINIT.

```

also i try to lazy load like this

```lua
require("luasnip/loaders/from_vscode").lazy_load(
    {paths = {"~/.local/share/nvim/site/pack/packer/start/friendly-snippets"}}
)
```

i use init.lua as cfg

nvim version
```
NVIM v0.5.0-dev+1375-gca802046b
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/dnehrig/.cache/yay/neovim-git/src/build/config -I/home/dnehrig/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/dnehrig/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/dnehrig/.cache/yay/neovim-git/src/build/include
Compiled by dnehrig

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by leiserfg** [comment]
MYVIMRC is always set, to use friendly-snippets you don't have to pass the paths, just call `lazy_load()` without args.

**Comment by leiserfg** [comment]
If the error continues, try to come up with a minimal config that we can try to reproduce it.

**Comment by danielnehrig** [comment]
> If the error continues, try to come up with a minimal config that we can try to reproduce it.

i don't think it's a config issue
but rather a setup ENV issue

on mac it works just fine i guess the env var i set there
on arch it seems to be not set for me

i could set the env var in my shell config though i don't know to where to set it to

**Comment by leiserfg** [comment]
$MYVIMRC is set by nvim, not by the system.

**Comment by NTBBloodbath** [comment]
@danielnehrig have you tried with other Neovim binary? I was having issues with the `$MYVIMRC` being nil in the past. Installed Neovim from other source (e.g. instead of using a COPR repository on Fedora I have tried with the official release in the Neovim [releases](https://github.com/neovim/neovim/releases)) and that solved it.

**Comment by L3MON4D3** [comment]
> i could set the env var in my shell config though i don't know to where to set it to

Temporarily setting it to the location of your vim config (ie. `.config/nvim/init.vim`) should at least silence the errors. 
If it really comes down to binaries(different version maybe? Seems more likely) there's little we can do except provide defaults I think.

**Comment by leiserfg** [comment]
Do  `:echom $MYVIMRC` and share what does it print.

**Comment by danielnehrig** [comment]
ok its referenced to my init.lua now
not too sure what i did to make it work but it works now

i refactored some of my cfg
installed a new nvim version

and now all is good

**Comment by leiserfg** [comment]
If you manage to replicate it again, please share that, maybe it's a bug on that nvim.

**Comment by danielnehrig** [comment]
i had the same bug on my work vm which went away after upgrading my neovim verison
thats how i solved it for people that will encounter the same issue
