### ISSUE TITLE
Ctrl-I broken when using LuaSnip

### ISSUE THREAD

**Issue by woodspock** [L3MON4D3/LuaSnip#742]
Everything used to work ok, but since today, ctrl-I(for navigating jumplist) does not work anymore.
LuaSnip seems to be the culprit since it works again when I disable it. 
I also tried a fresh config of Neovim without any plugin : Ctrl-I works. Then I add LuaSnip and it does not work anymore : nothing happens when hitting <ctrl+i>
Executing ':verbose map <C-i>' shows no conflicting mapping.
And plugin has been updated.

NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by L3MON4D3** [comment]
Hmmm, no idea what that might be :/
For me this is working correctly, though.. Could you make a MWE?

**Comment by woodspock** [comment]
With a fresh install of Neovim and only Lazy.nvim and Luasnip.nvim, I narrowed the problem : it happens if I assign keyboard shortcuts to`<tab>`

```lua
local ls = require("luasnip")

vim.keymap.set({ "i", "n"}, "<tab>", function()
  if ls.expand_or_jumpable() then
    ls.expand_or_jump()
  end
end, { silent = true })
```

If i change <tab> to `<s-tab>` or `<c-j> `then I can navigate jumps again with `<c-i>`.
One solution would be to use other keys to navigate placeholders, but I am very used to doing it with `<tab>`

**Comment by leiserfg** [comment]
It's not an luasnip issue, for apps running in a terminal  `tab` and `c-i` are the same.
In insert mode type `c-v` to enable raw insert, then type `c-i` and you will see a tab inserted.

**Comment by leiserfg** [comment]
If you wanna make it work you need to move to a terminal supporting `CSI u`  like kitty or wezterm.

**Comment by leiserfg** [comment]
@L3MON4D3  I think this can be closed

**Comment by L3MON4D3** [comment]
Yes, right! Thanks :+1:
