### ISSUE TITLE
`luasnip.jump(-1)` selects more region than it should

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#744]
`luasnip.jump(-1)` selects more region than it should.

**luasnip config:**

```lua
  local ls = require('luasnip')
  ls.setup({
    history = true,
    region_check_events = 'CursorMoved',
    delete_check_events = 'TextChangedI',
    updateevents = 'TextChanged,TextChangedI,InsertLeave',
    enable_autosnippets = true,
    store_selection_keys = '<Tab>',
  })
```

**Snippet that cause the problem (a snippet for markdown inline math env):**

```lua
local ls = require('luasnip')
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

local function not_in_mathzone()
    return vim.api.nvim_eval('vimtex#syntax#in_mathzone()') == 0
end

 ls.add_snippets('markdown', s({ trig = 'm' } , { t '$', i(1), t '$' }, condition = not_in_mathzone), {})
```

**To reproduce:**

1. Ensure [vimtex](https://github.com/lervag/vimtex) and [vim-markdown](https://github.com/preservim/vim-markdown) is installed for the condition function to work
1. Add the snippet described for 'markdown' or 'all'
3. Enter a markdown file.
4. Hit `m`, then expand the snippet. `m|` -> `$|$`
5. Type **combinations of numbers** inside the dollars `$|$` -> `$1|$`
6. Jump out of the snippet `$1|$` -> `$1$|`
7. Call `ls.jump(-1)`
8. LuaSnip selects `$1` instead of `1` alone

It is worth noting that this only happens when the contents in between `$` are numbers.

**Short video demo of the issue:**

https://user-images.githubusercontent.com/76579810/214176580-5717ac76-ebe2-4e00-b729-fa8b1b4445b6.mp4

**Comment by L3MON4D3** [comment]
Oh no xD
I can't reproduce it just yet (although I've omitted the mathzone-stuff, is it integral to this problem?), could you look through your other settings and see if changing anything there makes it work correctly?
For example, we had an issue with `selection`, with similar symptoms, maybe something similar is going on on your end.

https://user-images.githubusercontent.com/41961280/214237920-cd0882f6-e06f-4380-aacd-28906a26677a.mp4

**Comment by Bekaboo** [comment]
Hi, thank you for your reply. I find that after uninstalling `vimtex` and `vim-markdown`, the problem is gone. Pretty weird, though.

**Comment by L3MON4D3** [comment]
Maybe vimtex is doing some formatting?

**Comment by Bekaboo** [comment]
Very likely to be the case.

Here's another snippet I find having problem when `vimtex` is on:

```lua
s({ trig = '$$' } , { t '$', i(1), t '$' })
```

without `vimtex` it works as expected -- putting your cursor in between the dollars when you insert two dollar symbols, but with `vimtex` installed it does not trigger at all.

I'll try to investigate in this problem and let you know if I have any progress.

**Comment by Bekaboo** [comment]
Close this issue because it no longer happens. Seems like that there's an update on VimTeX.

**Comment by L3MON4D3** [comment]
Okay, cool :+1:
