### ISSUE TITLE
Variable transformation is acting weird

### ISSUE THREAD

**Issue by budimanjojo** [L3MON4D3/LuaSnip#746]
Hello, I have `jsregexp` installed and variable transformation is not working like it should. Not sure what can I do to debug this. I have a placeholder that is like this: `${2:mydomain.com}` and I want to have another placeholder with the same value but with `.` (dot) replaced with `-` so I create the second placeholder like this: `${2/[\\.]/-/g}`.
The resulted string in the second placeholder is now `ydomain-com` instead of `mydomain-com`. I also tried the example from VSCode doc here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples and the first letter is always gone.

**Comment by L3MON4D3** [comment]
Thank you for making an issue for this :)
Let's hope you were just the first to encounter it xD

**Comment by budimanjojo** [comment]
Thanks for the quick fix!

**Comment by L3MON4D3** [comment]
> Thanks for the quick fix! Should I use the latest commit or wait for a new patch release?

Feels a bit weird to not do a release for like 3 months and then do two on successive days xD
But it's an issue that could occur very easily, so I'll do a patch, thanks for prompting it :D
