### ISSUE TITLE
[Bug?] Wrongly paste when enter "p" into insert node

### ISSUE THREAD

**Issue by frankli998** [L3MON4D3/LuaSnip#748]
Hi, I encountered a problem, when I press "p" in insert node, neovim paste something for me and returns into normal mode, but what I try to do is to just put a literal p there. I have not seen any discussion yet(or just I couldn't find it), how to solve it? Is there a way to disable paste in visual select mode? Or it is a bug? If not, how to insert literal p properly into beginning of insert node?

**Comment by frankli998** [comment]
keymap("v", "p", '"_dP', opts)

This is culprit.
I use a keymap by others, if you too have this line, comment it out.

**Comment by celsobenedetti** [comment]
> keymap("v", "p", '"_dP', opts)
> 
> This is culprit. I use a keymap by others, if you also have this line, comment it out.

The mentioned keymap is pretty useful still. Here is kind of a workaround hack to mitigate this:

```lua
vim.keymap.set("v", "p", function()
  if require("luasnip").in_snippet() then
    vim.api.nvim_feedkeys("p", "n", false) 
  else
    vim.api.nvim_feedkeys('"_dP', "n", false)
  end
end, opts)
```
