### ISSUE TITLE
How to create snippet that expands when SELECT_RAW is not empty only

### ISSUE THREAD

**Issue by Entoryvekum** [L3MON4D3/LuaSnip#749]
In some cases, I want the snippet to expand after selecting text and not to be triggered in normal editing. Besides, it's also useful that a snippet is automatic when text is selected and require manual expand in other cases. But, the SELECT_RAW seems can't be used outside a function node or a dynamic node. So how to setup such snippet?

**Comment by leiserfg** [comment]
Well, you can use a dynamic node returning and empty snippet if there is nothing in SELECT_RAW isn't it?

**Comment by Entoryvekum** [comment]
> Well, you can use a dynamic node returning and empty snippet if there is nothing in SELECT_RAW isn't it?

My idea was to use SELECT_RAW in condition function, rather than pretend the snippet isn't triggered. Creating a snippet that return the same text will cause the tab key immediatly after the trigger to fail, but it's not a big deal anyway. 

It's a workable solution, although it didn't meet my expectation. Thank you for your reply!

**Comment by L3MON4D3** [comment]
Alternatively, we could add api for retrieving the current text stored for `SELECT_RAW`, and then your first idea would just require #420.

**Comment by leiserfg** [comment]
Well, In that case then just document  `b:LUASNIP_SELECT_RAW` and family we don't need to add more API for that :smile: and I don't think we wanna change the implementation either.

**Comment by Entoryvekum** [comment]
Although I don't familar with the development of such complecated project, I don't think passing stored text using `vim.b.LUASNIP_SELECT_RAW` match the existing style. But I believe it's a good makeshift.

**Comment by L3MON4D3** [comment]
> Well, In that case then just document `vim.b.LUASNIP_SELECT_RAW` and family, we don't need to add more API for that smile and I don't think we wanna change the implementation either.

True, that would be enough.. I'll do a small api, just to err on the side of caution

> Although I don't familar with the development of such complecated project, I don't think passing stored text using vim.b.LUASNIP_SELECT_RAW match the existing style. But I believe it's a good makeshift.

We already store the selected text in a buffer-variable, so this would only require documenting the current implementation, so it has that going for it :D

**Comment by Entoryvekum** [comment]
> > Well, In that case then just document `vim.b.LUASNIP_SELECT_RAW` and family, we don't need to add more API for that smile and I don't think we wanna change the implementation either.
> 
> True, that would be enough.. I'll do a small api, just to err on the side of caution
> 
> > Although I don't familar with the development of such complecated project, I don't think passing stored text using vim.b.LUASNIP_SELECT_RAW match the existing style. But I believe it's a good makeshift.
> 
> We already store the selected text in a buffer-variable, so this would only require documenting the current implementation, so it has that going for it :D

Got it. Thanks!
