### ISSUE TITLE
Can I delete snippet history on InsertLeave?

### ISSUE THREAD

**Issue by uga-rosa** [L3MON4D3/LuaSnip#75]
In my case, once I leave insert mode, I don't jump to a previous history. It's my fault for leaving without jumping to the end...

**Comment by L3MON4D3** [comment]
You could add an autocommand to set `Luasnip_current_nodes[buffer_number]` to nil.

**Comment by uga-rosa** [comment]
After setting it on InsertLeave, jumping itself is completely disabled. Is it also triggered on expanding?
Should I map to <esc>?

**Comment by L3MON4D3** [comment]
Yeah, right, we leave insert on jumping, ofc.
You could try mapping to Esc, then it would depend on how neovim processes input given via `feedkeys()`

**Comment by uga-rosa** [comment]
I'm sorry for asking such an elementary question due to my lack of understanding of the principle :_(

I tried it and it worked well, so I think I'll stick with it. Thanks!

**Comment by L3MON4D3** [comment]
Oh DW, I think it's of general interest, won't hurt to have it here :)
