### ISSUE TITLE
The parsing of the package.json is too strict

### ISSUE THREAD

**Issue by obayit** [L3MON4D3/LuaSnip#751]
If there is a trailing comma after the last item on a list it causes the parse to fail, for example:
```json
    "snippets": [
      {
        "language": [
          "python",
        ],
        "path": "./my-python.json"
      },
```
The comma after python causes the issue,
`ERROR | vscode-loader: Json in /home/username/.config/nvim/snippets/package.json could not be parsed`

Can't the json parsing be more lenient?

**Comment by leiserfg** [comment]
With a comma there it's not valid JSON, so the library we use (the native json parser builtin in nvim) can't read it. The only way to make that possible is to write our own "almost-JSON" parser and that will make the loading slower so I think it's better just to write the JSON file correctly :wink:
