### ISSUE TITLE
Multiple `extends` directives for snipmate snippets not included

### ISSUE THREAD

**Issue by hanschen** [L3MON4D3/LuaSnip#753]
Is it possible to include multiple `extends` directives in .snippets files (snipmate style)?
For example, if I put

```
extends texbeamer
extends texmath
```

in `tex.snippets`, then only the snippets from `texmath.snippets` are included (along with the snippets in `tex.snippets`).

If I change the order to have `extends texbeamer` last, then the snippets from `texbeamer.snippets` are included instead of the ones from `texmath.snippets`.

I load `LuaSnip` using: `require("luasnip.loaders.from_snipmate").lazy_load({ paths = { "./snippets" } })`

**Comment by L3MON4D3** [comment]
Could you try `extends texbeamer texmath`?
That should work according to our code. Can't find whether this is completely correct according to the snipmate-standard right now :/

**Comment by L3MON4D3** [comment]
Nice!
Not sure if it's actually specified anywhere, if there are issues with it we can extend it :D
