### ISSUE TITLE
Trigger snippet only when word is first word of line or is preceded with whitespace

### ISSUE THREAD

**Issue by olivervogel** [L3MON4D3/LuaSnip#756]
First of all, thanks for building this engine. I'm coming from UltiSnip and I'm wondering how to customize the trigger behavior, since there seem to be differences.

UltiSnip by default only expands a snippet ["if the tab trigger is the first word on the line or is preceded by one or more whitespace characters."](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L676), which can be customized though. This means the snippet by default will not be expanded if the cursor is in between two parentheses for example.

As far is I can tell, with LuaSnip the snippet would be expanded from the example. At least in default settings. This is something I would like to customize for myself as a global setting and for each snippet individually.

Is there any way to do this? And what would be best practice?

I think I could implement this with Regex Pattern but then I would have to reinsert the matched whitespace characters, which sounds rather hacky.

```lua
s({trig = "^(%s*)trigger", regTrig = true}, {
  -- re-insert captured whitespace :(
})
```
 Is there a another solution which would be better.

Thank you very much.

**Comment by L3MON4D3** [comment]
Hi :)
I think the best way to implement this is to add a [`condition`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets) to the snippet: it can dynamically (i.e. based on the current context) prevent expansion.
This can't be set on all snippets globally, but you can use [`extend_decorator`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#extend_decorator) to create a new snippet-constructor which adds this condition by default.
If you're using the lua-loader, you can make this new snippet-constructor available to files evaluated in its context by adding it in the [`snip_env`](https://github.com/L3MON4D3/LuaSnip#config)-setup-option.

**Comment by L3MON4D3** [comment]
Beatiful :+1: :D
