### ISSUE TITLE
Loading the following snippet (Snipmate-like) breaks the engine

### ISSUE THREAD

**Issue by Nan-Do** [L3MON4D3/LuaSnip#757]
Some extra details that may be useful:
I'm using it as a custom snippet for markdown files
I have installed friendly-snippets
I use the snippets via nvim-cmp
I load the custom snippets via 

`require("luasnip.loaders.from_snipmate").lazy_load({ paths = { "./custom-snippets" } })`

This is the snippet that makes it fail:
```
snippet bno  "Code block without pygments"
    ``` { use_pygments=false }
    ${0}
    ```
```
This is the error:
```
E5108: Error executing lua ...pack/packer/start/LuaSnip/lua/luasnip/util/functions.lua:39: Vim(echo):E121: Undefined variable: use_pygments
stack traceback:
        [C]: in function 'nvim_exec'
        ...pack/packer/start/LuaSnip/lua/luasnip/util/functions.lua:39: in function 'fn'
        ...k/packer/start/LuaSnip/lua/luasnip/nodes/dynamicNode.lua:134: in function 'update'
        .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:813: in function 'update'
        .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:504: in function 'trigger_expand'
        ...nvim/site/pack/packer/start/LuaSnip/lua/luasnip/init.lua:233: in function 'snip_expand'
        ...e/pack/packer/start/cmp_luasnip/lua/cmp_luasnip/init.lua:143: in function 'execute'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:390: in function 'execute'
        ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:478: in function 'execute'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:487: in function <...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:486>
        ...te/pack/packer/start/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function <...te/pack/packer/start/nvim-cmp/lua/cmp/utils/feedkeys.lua:45>
```

**Comment by L3MON4D3** [comment]
Oh, wow, that's a first xD
Hmm, seems like the problem is just that ``` `` ``` are normally meant to delimit a vimscript-expression. Would you add a backslash before each `` ` ``?

**Comment by Nan-Do** [comment]
I've tried the following snippet but it still produces the same error.
```
snippet bno  "Code block without pygments"
    \`\`\` { use_pygments=false }
    ${0}
    \`\`\`
```

**Comment by L3MON4D3** [comment]
Srry, this snippet is working on my end.
Both via 
```lua
ls.snip_expand(ls.parser.parse_snipmate("", "\\`\\`\\` { use_pygments=false }\n${0}\n\\`\\`\\`"))
```
and when loading it with the snipmate-loader.
Could you test it again? Maybe the old version was still in there or something

**Comment by Nan-Do** [comment]
Sorry, you were right the single backslash worked properly I'm using vimwiki to handle markdown files and I forgot to update vimwiki.snippets.

**Comment by L3MON4D3** [comment]
Ahh okay, nice👍
I'll extend the doc with a note about this, there might not be one
