### ISSUE TITLE
Is it possible to create a snippet for languages with no parser?

### ISSUE THREAD

**Issue by haikyuu** [L3MON4D3/LuaSnip#758]
I'm writing a tree-sitter grammar, and the tests are written in txt files.
I've created a `txt.snippets` file, but it doesn't work.

Is there a way to enable snippets there? or should I create a parser first

**Comment by L3MON4D3** [comment]
The filetype used for snippets is resolved by `ft_func` in `setup`. What are you using there? We provide, in extras, one function with pure treesitter, and one with fallback to `&filetype`, ie. the filetype of the buffer. Using the latter should work

**Comment by haikyuu** [comment]
It works, thanks. The file extension is `txt` but the file type is actually `text` so I needed to rename the snippet to `text.snippets`.
Thank you @L3MON4D3

**Comment by L3MON4D3** [comment]
Ahh ofc :D
You're welcome :)
