### ISSUE TITLE
[Question] Auto-complete Latex (LuaSnip - Compe - friendly-snippets)

### ISSUE THREAD

**Issue by pcapiod** [L3MON4D3/LuaSnip#76]
Hi,

I am very new with LuaSnip, been used to UltiSnips but wanted to switch to full Lua.
Is there a way to have auto-complete with LuaSnip on only certain snippets? 

Let's say I want to enter math mode with 'mk' (or whatever the snippet), I am not sure how I would define an auto-trigger/auto-complete to enter math-mode in Latex. 
Besides that, in-line math mode in Latex is '$YOUR MATH HERE$', how do you define a snippet to include those '$'?

Thanks for your help!

**Comment by L3MON4D3** [comment]
> Is there a way to have auto-complete with LuaSnip on only certain snippets?

No, not really, all available snippets are shown in compe (is that what you meant?). What's your usecase, I assumed one wants to see all possible completions, including snippets.

> Let's say I want to enter math mode with 'mk' (or whatever the snippet), I am not sure how I would define an auto-trigger/auto-complete to enter math-mode in Latex.

That isn't possible (yet, it'll be added), right now all snippets have to be triggered manually.

> Besides that, in-line math mode in Latex is '$YOUR MATH HERE$', how do you define a snippet to include those '$'?

If you parse it as a lsp-snippet you'll have to escape the '$' (`"\\$"` or `[\$]`), if the snippet is defined using the lua functions the '$' can just be put inside the `textNode`.

**Comment by pcapiod** [comment]
> That isn't possible (yet, it'll be added), right now all snippets have to be triggered manually.

Alright, thanks for this!

> If you parse it as a lsp-snippet you'll have to escape the '$' ("\\$" or [\$]), if the snippet is defined using the lua functions the '$' can just be put inside the textNode.

Perfect, thanks a lot for your answer!

**Comment by leiserfg** [comment]
Automatically triggering a snippet is not that hard to do, just have to map an `abbr` to a snippet.

**Comment by L3MON4D3** [comment]
Can't abbrev just expand to text?

**Comment by leiserfg** [comment]
You can use an `abbr <expr>` and do lua stuff on it, is a hack but that does not mean it's impossible :smile:

**Comment by leiserfg** [comment]
Check this @L3MON4D3   I can clean it up and make a pr for it
```lua
_G.snippets_abbr = {}

function _G.expand_snp(trigger)
    snip = _G.snippets_abbr[trigger]
		if snip then
    vim.defer_fn(function()
			snip:trigger_expand(
				Luasnip_current_nodes[vim.api.nvim_get_current_buf()]
			)
    end, 0)
		end
    return trigger:sub(1, -2) -- Replace the trigger by a string with once charcter less
end

function autosnip (snip)
  -- print(vim.inspect(vim.tbl_keys(snip)))
  _G.snippets_abbr[snip.trigger] = snip

  vim.cmd("abbr <expr>" .. snip.trigger .. [[ luaeval("_G.expand_snp(']] .. snip.trigger .. [[')")]])
  return snip
end

autosnip(
s({ trig = "lay", wordTrig = true }, { t { "layout " }, i(1, { "python" }), i(0) })
)


```

**Comment by L3MON4D3** [comment]
This would work for non-regex wordTrig's only, correct? I think, at least for an 'official' implementation, it'd be better to create a separate table for autotriggered snippets (as little work on each keystroke as possible) and run it through the usual `match_snippet(line)`-function (so that regex and similar are still supported) on `TextChangedI`(best case would be to only run on adding text, but don't know any events for that).
Haven't tried expanding in an autocmd yet, so no idea if it works or not.

**Comment by leiserfg** [comment]
Another simpler option could be to add the necessary  to do:
```vim  
imap <silent><expr> <Space> luasnip#auto_expandable() ? '<Plug>luasnip-auto-expand' : '<Space>'
```

**Comment by leiserfg** [comment]
I guess that will be less clunky and will add less overhead.

**Comment by L3MON4D3** [comment]
Yeah okay, but you'd still need to press space to trigger, it isn't really autotrigger I think.

**Comment by leiserfg** [comment]
If you don't do it that way then you can regret typing a trigger and also you can't use regexes that end with an optional/repeatable part as they will match as soon as you type the shorter version.

**Comment by L3MON4D3** [comment]
Tbh, I think both these are expected behavior when using autotriggered snippets(or at least that's how I'm used to them from eg. UltiSnips).

**Comment by L3MON4D3** [comment]
Completely overlooked this issue when implementing a first version of autotriggered snippets earlier, srry 😅 
Could you comment on the changes [here](https://github.com/L3MON4D3/LuaSnip/issues/77#issuecomment-890313939)

**Comment by L3MON4D3** [comment]
I'll close this, but feel free to reopen should you have issues with autotrigger :)
