### ISSUE TITLE
Difference between `snip_expand`, `lsp_expand`, and `expand`

### ISSUE THREAD

**Issue by hinell** [L3MON4D3/LuaSnip#760]
```
luasnip.snip_expand()
luasnip.lsp_expand()
luasnip.expand()
```
Hi. Can you please explain the difference between these functions? I'm using nvim-cmp and I want to configure to be able to use luasnip. There is no info on them in `DOC.md`. Thanks.

**Comment by L3MON4D3** [comment]
You can find documentation for them waaaayyy at the bottom of `DOC.md`
