### ISSUE TITLE
luasnip-here in docs

### ISSUE THREAD

**Issue by s1n7ax** [L3MON4D3/LuaSnip#764]
Looks like `node_opts` has referenced to `|luasnip-here|` which does not exists. Could you point me to `node_opts`?

**Comment by L3MON4D3** [comment]
Oh wow, this has gone unnoticed for some time.. Maybe panvimdoc has never been able to properly parse these :/
Anyway, you can check the online-documentation on github instead,` DOC.md` in the repo-root, I'll look into what's going wrong with the helpfile-generation

**Comment by leiserfg** [comment]
@L3MON4D3 Check here, is unfortunate but intentional   
https://github.com/kdheepak/panvimdoc/blob/edeefb362ed38da61c6e404e367345b455c489e9/doc/panvimdoc.md#markdown-links

**Comment by L3MON4D3** [comment]
Ah, okay I can kind-of see the sense in that..
Guess we'll have to rephrase those parts such that it works, seems like the path of least resistance
