### ISSUE TITLE
Adding the \n character

### ISSUE THREAD

**Issue by dix75** [L3MON4D3/LuaSnip#766]
Hi All!
Is it possible to add a \n character to the return string from the function

Simply using the function and concatenation does not work 

For example:
```
local function copy(args)
	return args[1][1] .. ";\n"
end

ls.add_snippets('cpp', {
  s('n', {
      i(1), t({'name', ''}),
      f(copy, 1), t({'', ''}),
     i(0),
	}),
});
```

**Comment by L3MON4D3** [comment]
For a linebreak, you can return `{"line1", "line2"}`, a literal `"\n"` should work with `"\\n"`

**Comment by dix75** [comment]
Thanks, but
I need to return two or more lines from function

For example
`x, y, z`

I need to get
```
void x;
void y;
void z; 
```

**Comment by L3MON4D3** [comment]
Yeah, okay, then you need to return them as a table,`{"void x;", "void y;", "void z;"}`

**Comment by dix75** [comment]
Thanks
