### ISSUE TITLE
Locally jumpable has strange behaviour

### ISSUE THREAD

**Issue by mlthlschr** [L3MON4D3/LuaSnip#770]
Hi, i have the following problem:

I have a snippet where `pat`, `expr` and `unimplemented` are all insert nodes:

```
for pat in expr {
    unimplemented!();
}
```
if I expand the snippet, skip the jumps, go to somewhere else in the code and expand another (not necessarily the same) snippet, I will jump back into the first snippet after completing all jumps in the second snippet. I try to prevent that using  `locally_jumpable`, but thats not working.

Example where `v n` marks the jump position with "index"
```
// first snippet, just expanded, no jumps
           v 5
for pat in expr {
    unimplemented!();
}

// second snippet, expanded and start point for jumps
    v 1  v 2
for pat in expr {
    v 3
    unimplemented!();
v 4
}
```
do i misunderstand the `locally_jumpable`? I expect that I can only jump within the snippet which I just expanded. Not that I jump back into some "incomplete" snippet I wrote some lines before.

If thats the correct behavior, how can I prevent jumping back into old snippets I have not finished completely? Is there e.g. a way to invalidate old snippets as soon as leaving them?

The minimum working config is:
```
local cmp = require('cmp')
local luasnip = require('luasnip')

require('luasnip.loaders.from_vscode').lazy_load()

cmp.setup({
  preselect = cmp.PreselectMode.Item,
  completion = {
    completeopt = 'menu,menuone,noinsert',
  },
  mapping = {
    ['<Tab>'] = cmp.mapping(function(fallback)
      if luasnip.expand_or_locally_jumpable() then
        luasnip.jump(1)
      end
    end, { 's', 'i' }),
    ['<CR>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.confirm({ select = true })
      else
        fallback()
      end
    end, { 'i', 's' }),
  },
  snippet = {
    expand = function(args) require('luasnip').lsp_expand(args.body) end,
  },
  sources = cmp.config.sources({
    { name = 'nvim_lsp', priority = 5, max_item_count = 10 },
    { name = 'luasnip',  priority = 1, max_item_count = 10 },
  }, {
    { name = 'buffer' },
  }),
})
```

**Comment by L3MON4D3** [comment]
> if I expand the snippet, skip the jumps, go to somewhere else in the code and expand another (not necessarily the same) snippet, I will jump back into the first snippet after completing all jumps in the second snippet. 

That sounds like you might not have exhausted all the jumps in the first snippet. Luasnip automatically inserts a `i(0)` at the end of the snippet if it does not already contain one, so my guess is that you jumped back into that (?)

**Comment by mlthlschr** [comment]
Yes, looks like they are not exhausted. Is there a way to abandon them?

**Comment by L3MON4D3** [comment]
Yes, there is [`region_check_events`](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#config-reference), which can periodically (on an autocommand) check whether the cursor is still inside the snippet, if it isn't, the `i(0)` of the snippet is set current (ie. the snippet is jumped through)

**Comment by mlthlschr** [comment]
Yeah, now it is better. Not perfect, but not as bad as before.
