### ISSUE TITLE
Esc doesn't go to normal mode, instead it jumps backwards

### ISSUE THREAD

**Issue by daalfox** [L3MON4D3/LuaSnip#772]
this is my jump keymaps for luasnip
```
vim.keymap.set({ "i", "s" }, "<C-]>", function()
    if luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
    end
end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-[>", function()
    if luasnip.jumpable( -1) then
        luasnip.jump( -1)
    end
end, { silent = true })

```
but when I press esc, I go back to previous insertNode
it is driving me insane

**Comment by leiserfg** [comment]
That's because in most terminals `<C-[>` is the same as `ESC`, use a modern one implementing *extended keyboard protocol* (as far as  I know: kitty, wezterm, and foot) and you will get the issue solved auto-magically.

**Comment by daalfox** [comment]
aha so that's why...
Thank you!
