### ISSUE TITLE
new autocommand api

### ISSUE THREAD

**Issue by max397574** [L3MON4D3/LuaSnip#776]
with neovim 0.7 there was an api for autocommands added
you should use this api so you could get rid of this mess (no offense, it wasn't possible to do it much better before):
https://github.com/L3MON4D3/LuaSnip/blob/58fbfc627a93281a77f7d161d4ff702e639677b1/lua/luasnip/config.lua#L220-L249

but why I initially looked at this code was because it wasn't possible to pass a table with events to the config values like `update_events` which could quite easily be done with the new api

I could also open a pr for this if you don't have time

**Comment by max397574** [comment]
expect a pr soon

**Comment by L3MON4D3** [comment]
Fixed by #777
