### ISSUE TITLE
jump to saved snippet location only if I'm inside the body of that snippet

### ISSUE THREAD

**Issue by dajohans** [L3MON4D3/LuaSnip#78]
Currently, the behaviour I have is that if there exists a saved location(do these have a name in snippet lingo? tabstop?) and if I press a key which I have mapped to `<plug>luasnip-expand-or-jump` then my cursor is moved to the next saved location regardless of how far away from that saved location I may have been. This has happened quite a few times when I have snippets with saved locations that I don't necessarily have to touch. Then instead of jumping through all the locations I may just enter normal mode and exit the snippet that way. But then the snippet jump locations are not removed and I jump to them the next time I want to insert a new line, because I have `<cr>` bound with a condition to first complete with compe, then LuaSnip and then insert a new line.

I wonder, is it possible to make it so that I only jump to a saved location if I am within the start and end points of the code that was inserted by the snippet?

If this is not possible, is this a feature you think makes sense for the plugin to have? The plugin works with nested snippets and I think it might be important to note that this shouldn't interfere with that, since in a nested snippet you are still within the body of the outer snippet.

**Comment by dajohans** [comment]
After some more thinking, I have realized that I probably want something slightly different than what I described above. Above, I say that I want to be able to only jump to saved locations within the snippets that I am current inside. But this still means that I can have invisible jump locations for snippets spread out over my document. Then I never know if I am currently standing inside a snippet which has some old unused save location still in it and then I don't know what my `<tab>` key is going to do. If there's a jump location, `<tab>` will jump and if there is not then it will insert a tab-character. I don't like this seemingly random behaviour.

So I think that what I actually want is the ability to _remove_ all saved jump locations for snippets whose bodies I am not currently inside. If there would be something like `<plug>luasnip-remove-unused-jump-locations` then I could possibly do something like
```viml
imap <silent><expr> <tab> luasnip#jumpable(1) ? '<plug>luasnip-remove-unused-jump-locations<plug>luasnip-jump-next' : '<tab>'
```
I'm not sure if this is how you chain two diffent `<plug>` commands. But I think it should be clear what I want to have happen. I would really like to have something like this.

**Comment by L3MON4D3** [comment]
> I wonder, is it possible to make it so that I only jump to a saved location if I am within the start and end points of the code that was inserted by the snippet?
> 
> If this is not possible, is this a feature you think makes sense for the plugin to have? The plugin works with nested snippets and I think it might be important to note that this shouldn't interfere with that, since in a nested snippet you are still within the body of the outer snippet.

That's a good idea, could be the default if history is not set (at least that's how UltiSnips handles things).

> Then I never know if I am currently standing inside a snippet which has some old unused save location still in it and then I don't know what my `<tab>` key is going to do. If there's a jump location, `<tab>` will jump and if there is not then it will insert a tab-character. I don't like this seemingly random behaviour.

The simple solution would be to not have eg. `<tab>` as a key for jumping, that would remove the 'seemingly random behaviour' (which is, to be precise, fully deterministic; if there is a next tabstop, it jumps there, if not it (depending on the setup) inserts `<tab>`. I acknoledge, however, it isn't clearly communicated whether the user is inside a snippet, but I have no idea how to nicely do that (highlight maybe??))

> So I think that what I actually want is the ability to remove all saved jump locations for snippets whose bodies I am not currently inside.

Which 'inside' do you mean? :D
As far as luasnip is concerned, you're still inside the snippet (node) you were in when you 'left' to edit some other part of the code.
If you mean 'textually' inside, and your goal would be deleting snippets you're not inside, that should be doable, but I think, that more clearly communicating to the user that 'Hey!! You're still inside this snippet!!' would be cleaner.

(take a look at #75, maybe that's close to your desired behaviour?)

**Comment by L3MON4D3** [comment]
(At first I misread your title and thought you wanted to 'mark' tabstops and be able to jump to them from anywhere. That would be a pretty sick (and unique AFAIK) feature, I'll have to experiment with that)

**Comment by L3MON4D3** [comment]
I finally came around to adding that (or at least similar) functionality: Setting `region_check_events` to eg. `'CursorMoved'` (or if that's to obstrusive, `'CursorHold'` with a low `updatetime`) will automatically jump to the end of a snippet if you've left it (or, with `history=false`, completely leave it).
