### ISSUE TITLE
latex snippet in snipmate style doesn't work

### ISSUE THREAD

**Issue by TroySigX** [L3MON4D3/LuaSnip#788]
I have created a tex.snippets file and wrote some snippets, but when I typed the triggering phrase and pressed <Tab>, it does nothing. My other snippet filetypes like cpp and python works fine.

**Comment by L3MON4D3** [comment]
Mhmm, I can think of checking:
* logs (`:h luasnip-logging`) will tell you if loading failed somehow
* is the filetype actually `tex` and not `latex`? `:set ft=tex` to make sure

**Comment by leiserfg** [comment]
I think the filetype for `.tex` files is `plaintex`

**Comment by JxJxxJxJ** [comment]
For `.tex` files I believe LuaSnips recognizes 2 ways of specifying snippets

- `luasnippets/<filytype>.lua` so `luasnippets/<tex>.lua`

- `luasnippets/<filetype>/<anything>.lua` so `luasnippets/tex/<anything>.lua`

![image](https://user-images.githubusercontent.com/103049321/221162570-fe62c688-0b8d-4afa-979a-d463f31b3e8f.png)

I'm not sure if it's LunarVim-specific though. But anyways, this would mean that doing `tex.snippets` is incorrect.

**Comment by leiserfg** [comment]
`filetype` and `extension` are not the same, try running  `nvim /tmp/asdf.tex`  and then  `:set ft`  and you will see the `filetype`.

**Comment by JxJxxJxJ** [comment]
`:set ft` in my `.tex` file returns the following
![image](https://user-images.githubusercontent.com/103049321/221164505-892d1e0a-e158-4837-a8c7-b26645ad9be2.png)

**Comment by TroySigX** [comment]
I see what's going on, so instead of letting the latex's filetype is tex, I just set it as plaintex, and it worked well. Thank you so much!
