### ISSUE TITLE
function node values don't show up in vim.ui.select

### ISSUE THREAD

**Issue by matthewsia98** [L3MON4D3/LuaSnip#789]
I am testing the last snippet
![image](https://user-images.githubusercontent.com/71731492/221073873-cc9f9d99-d45c-4658-984e-d64983360eb1.png)

**Comment by L3MON4D3** [comment]
Oh, I can confirm, it does not work :/
I think it used to, lemme take a look

**Comment by L3MON4D3** [comment]
Whoops, no, it never worked :sweat_smile:
It definitely should though, but will take longer to add than a fix for a regression
