### ISSUE TITLE
Does something like <plug>luasnip-expand exist?

### ISSUE THREAD

**Issue by dajohans** [L3MON4D3/LuaSnip#79]
I currently have two types of keybinds for LuaSnip. One keybind expands or jumps, this is `<cr>` for me, and I have one type of keybind that only jumps, like `<tab>` and `shift + <tab>`. What I actually want is for `<cr>` to only allow expansion of snippets, not jump in snippets.

What sometimes happens is that I'm inside a snippet and want to add a new line. But in order to do that I first have to remove all snippet jump locations. One way to resolve this would be to expand snippets with `<tab>` instead of `<cr>` but I really don't want to move snippet expansion to `<tab>`, because I view snippet expansion as a type of completion and I like having all completions on `<cr>`. So I don't like that way of resolving this.

Is there currently a way to bind `<cr>` to only expand and not jump? If yes, is there also some kind of function like  `luasnip#expandable()`? I tried looking through the source code and I don't think I found anything that looks like what I want.

**Comment by leiserfg** [comment]
Both are missing but are pretty easy to implement.

**Comment by L3MON4D3** [comment]
Hah, yeah they're pretty useful and easy, I'll add them :sweat_smile:

**Comment by L3MON4D3** [comment]
Okay, I added them as `luasnip#expandable` and `<Plug>luasnip-expand-snippet` (would've used `<Plug>luasnip-expand`, but I ignored proper style for those bindings and now that would collide with `<Plug>luasnip-expand-or-jump`, if there are more, similarly named bindings I'll do some breaking changes.)
