### ISSUE TITLE
jsregexp and lazy.nvim setup

### ISSUE THREAD

**Issue by blakedietz** [L3MON4D3/LuaSnip#791]
I originally posted this [question on the neovim subreddit](https://www.reddit.com/r/neovim/comments/11bvp0v/comment/ja04qa8/?context=3). But after further sleuthing and some pointers from someone else, I ran into this section of the documentation.

> If this fails, first open an issue :P, and then try installing the jsregexp-luarock. This is also possible via packer.nvim, although actual usage may require a small workaround, see https://github.com/wbthomason/packer.nvim/issues/593 or https://github.com/wbthomason/packer.nvim/issues/358.
> 
> Alternatively, jsregexp can be cloned locally, maked, and the resulting jsregexp.so placed in some place where nvim can find it (probably ~/.config/nvim/lua/).
> 
> If jsregexp is not available, transformations are replaced by a simple copy.

I was wondering if you happen to have recommendations for installing jsregexp with [LazyVim](https://github.com/LazyVim/LazyVim).

## Problem

I'm using [LuaSnip](https://github.com/L3MON4D3/LuaSnip) with some [VSCode snippets I wrote](https://marketplace.visualstudio.com/items?itemName=phoenix-liveview-snippets.phoenix-liveview-snippets). Expanding snippets works except for usages of [VSCode variable transforms](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms).

The snippets with pascal case transforms work fine in VSCode, but not in neovim, so I'm guessing there are three potential causes. 

### Potential root causes

- Assume my configurations somehow break LuaSnip in some way. I do have SuperTab configured via Lazy.nvim

It's always best to assume it's you before you assume it's something else.

### Expected

When using one of my snippets with variable transforms for pascal case, the correct parts of the snippet are converted to pascal case.

### Actual

When using one of my snippets with variable transforms for pascal case the snippet expands correctly, but does not convert variables to pascal case where specified.

## Assumptions

- [LuaSnip has 1:1 support for VS Code snippets](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vscode)

## Configuration

I use a [custom flavor of lazy.nvim starter](https://github.com/blakedietz/dotfiles-lazyvim-nvim/tree/blakedietz).

There are two areas that impact configurations that I'm aware of.

### SuperTab

I'm using [some SuperTab](https://github.com/blakedietz/dotfiles-lazyvim-nvim/blob/eef89a344413a81feea90ee41e2037370f4f7058/lua/plugins/supertab.lua#L6) configurations that are ripped directly from `example.lua` here. This impacts both LuaSnip and SuperTab.

### LuaSnip

Then I configure LuaSnip to use the snippets I have on my local machine [here](https://github.com/blakedietz/dotfiles-lazyvim-nvim/blob/774868c73e61b3b005462c796efb9d042d7284c0/lua/plugins/elixir.lua#L52).

As far as the actual file that's being used by LuaSnip, that's [here](https://github.com/blakedietz/vscode-snippets-liveview/blob/main/snippets.json).

I don't expect you to read the generated JSON as it is, so I wrote the smallest reproducible snippet below.

#### Example

```json
{
  "Phoenix: Context change": {
    "body": ["$1", "${1/(.*)/${1:/upcase}/}"],
    "description": "prefixes: plvs,pctx,pctxch",
    "prefix": ["plvs", "pctx", "pctxch"],
    "scope": "elixir,phoenix-heex,html"
  }
}
```

##### Output for VSCode

```
foo_bar
FooBar
```

##### Output for neovim

```
foo_bar
foo_bar
```

**Comment by leiserfg** [comment]
Are you using adding  `build = "make install_jsregexp"` to your lazy config?

**Comment by blakedietz** [comment]
Yes.

Here's what the config looks like: https://github.com/blakedietz/dotfiles-lazyvim-nvim/blob/e7f18f3fd10d699cd012d7becdaebc24c5238d86/lua/plugins/elixir.lua#L51.

**Comment by leiserfg** [comment]
Check [here](https://github.com/L3MON4D3/LuaSnip#install)

**Comment by blakedietz** [comment]
After fighting with some issues I ended up getting it working! Thanks for the recommendations. A couple of questions and thoughts.

## Questions

### Major version

Is version supposed to literally be copied and pasted? If so, it doesn't seem to work. I was getting an error.

```
{
  "L3MON4D3/LuaSnip",
  -- follow latest release.
  version = "<CurrentMajor>.*",
  -- install jsregexp (optional!).
  build = "make install_jsregexp"
}
```

## Some steps to remedy

I was having some issues after setting the value for version as above literally (without replacing). After running LazyVim install I had to go into my ~/.local/share/nvim/lazy directory and delete a handful of LuaSnip plugin and related plugin directories by hand in order to get everything to work again.

Thank you for the help. I've opened [a pr against LazyVim](https://github.com/LazyVim/starter/pull/19) to include this by default, as it feels like something that should be the default instead of the exception.

**Comment by blakedietz** [comment]
Closing as this fixed the issue.
