### ISSUE TITLE
Variable Placeholder-transformations not working 

### ISSUE THREAD

**Issue by sangramsingha** [L3MON4D3/LuaSnip#792]
Hi,

Packer config is 
``` lua
.....
{
    'L3MON4D3/LuaSnip',
    tag = "v1.2.*",
    run = "make install_jsregexp" -- luasnip get installed and not jsregexp
}
.......
```
![image](https://user-images.githubusercontent.com/30252302/221413673-72623356-c106-4408-b72c-807dfeaa068a.png)

Also tried this
> Alternatively, jsregexp can be cloned locally, maked, and the resulting jsregexp.so placed in some place where nvim can find it (probably ~/.config/nvim/lua/).

but transform is not working

output of `ldd $(which nvim)`
![image](https://user-images.githubusercontent.com/30252302/221414507-c8a97417-1daa-415d-b8a8-073ce4ff06e7.png)

example transform
```
${TM_DIRECTORY/.+java\\/|([^\\/]+)|(\\/)/$1${2:+.}/g}
```

File path : `/home/foo/Projects/p1/src/main/java/bar/baz`
Result Transform : `/home/foo/Projects/p1/src/main/java/bar/baz` 
Expected Transform : `bar.baz`

Am i missing something over here

**Comment by L3MON4D3** [comment]
Could you
* navigate to wherever packer installed luasnip for you (maybe `$HOME/.local/share/nvim/site/pack/packer/start/luasnip`) and run `make install_jsregexp` manullay, and post the output?
* show the result of `:lua require("jsregexp")`, and if it errors, double-check that `jsregexp.so` is in `.config/nvim/lua` (or, more generally, in a directory `lua`, which is inside any directory in `runtimepath`)

**Comment by sangramsingha** [comment]
Thanks for giving me the hint.
Requires lua5.1 while my machine has lua5.3 and dependencies
Got it working.
Please  include the following info in the readme as well
```
sudo apt install libluajit-5.1-dev luajit lua5.1 liblua5.1-dev

```

addtional for luarock for neovim
```
go  to https://luarocks.org/
wget https://luarocks.org/releases/luarocks-3.X.X.tar.gz
tar zxpf luarocks-3.X.X.tar.gz
cd luarocks-3.X.X
./configure && make && sudo make install
```

**Comment by L3MON4D3** [comment]
Oh, okay;
Could you figure out which lua-version neovim uses? `ldd $(which nvim) | grep lua` (or with some variation of `lua`, like `LuaJIT` or `Lua`)
I'd assumed that some version of lua is already installed, if `neovim` is

**Comment by sangramsingha** [comment]
`ldd $(which nvim) | grep lua` didn't gave anything..

without grep this is what i got

![image](https://user-images.githubusercontent.com/30252302/221420808-17e07d34-943d-4e39-b7dc-91adf908d519.png)

To install neovim i used the deb package from the release

**Comment by leiserfg** [comment]
Can you run also `nvim --version` ?

**Comment by sangramsingha** [comment]
sure, 
![image](https://user-images.githubusercontent.com/30252302/221427428-eb23a55c-6caa-435e-a202-235899124cbf.png)

**Comment by leiserfg** [comment]
So is Debian using almost all the libraries statically linked (no only luajit but also treesitter, libterm, ....) ?? Very suspicious.

**Comment by sangramsingha** [comment]
seems to be.. idk

**Comment by L3MON4D3** [comment]
> `ldd $(which nvim) | grep lua` didn't gave anything..
> 
> without grep this is what i got
> 
> ![image](https://user-images.githubusercontent.com/30252302/221420808-17e07d34-943d-4e39-b7dc-91adf908d519.png)

Ah, okay that was everything already. Kind of assumed there was some stuff cut off in the picture, my bad (less likely to happen with the full text-output wink wink nudge nudge)

Well, if some repos statically link neovim I guess we'd better add some hints about the required headers+libraries in the documentation
