### ISSUE TITLE
Backspace should just delete selected, but is bugging snippet

### ISSUE THREAD

**Issue by otavioschwanck** [L3MON4D3/LuaSnip#793]
if i try to press backspace to delete the part of snippet, the luasnip just bugs and insert some weird texts.  Using lsp-zero here.

![snippet](https://user-images.githubusercontent.com/9551316/221424047-db42f882-6dc9-4f31-a81a-1930d1552b30.gif)

Snippet:

```
  "letm": {
    "prefix": "letm",
    "body": "let(:${1:model}) { create(:$1${2:, }) }$0",
    "description": "let(:model) { create(:model, ...) }"
  }
```

**Comment by L3MON4D3** [comment]
We don't do anything fancy to make backspace delete the selection in SELECT-mode, you'll have to add this keybind yourself
(Not sure where that text is coming from though, maybe check `:smap`)

**Comment by otavioschwanck** [comment]
> We don't do anything fancy to make backspace delete the selection in SELECT-mode, you'll have to add this keybind yourself (Not sure where that text is coming from though, maybe check `:smap`)

i fixed on my mappings doing this:

```
  ['<BS>'] = cmp.mapping(function(fallback)
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Del>", true, true, true), "x")
    luasnip.jump(1)
  end, { "s" }),
```

Luasnip has something to do it?

**Comment by L3MON4D3** [comment]
What do you mean, did you have this mapping and it caused the strange behaviour, or adding this fixes the behavior?
I guess this mapping makes you jump backwards on backspace, if it's an issue remove it?

**Comment by otavioschwanck** [comment]
> What do you mean, did you have this mapping and it caused the strange behaviour, or adding this fixes the behavior? I guess this mapping makes you jump backwards on backspace, if it's an issue remove it?

Adding this fixes the problem

**Comment by otavioschwanck** [comment]
full map:

```
local cmp_mappings = lsp.defaults.cmp_mappings({
  -- Uncomment to input on select in autocomplete
  -- ['<Tab>'] = cmp.mapping.select_next_item({ select = true }),
  -- ['<S-Tab>'] = cmp.mapping.select_prev_item({ select = true }),
  ['<C-n>'] = cmp.mapping(function(fallback)
    if luasnip.jumpable() then
      luasnip.jump(1)
    elseif luasnip.expandable() then
      luasnip.expand()
    end
  end, { 'i', 's' }),
  ['<BS>'] = cmp.mapping(function(fallback)
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Del>", true, true, true), "x")
    luasnip.jump(1)
  end, { "s" }),
  ['<C-d>'] = cmp.mapping.scroll_docs(-4),
  ['<C-u>'] = cmp.mapping.scroll_docs(4),
})

```

**Comment by shellRaining** [comment]
I just want to delete selected text, and keep in insert mode, so I have these mapping

```lua
function M.backspace()
    return M.cmp.mapping(function()
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Del>", true, true, true), "x")
        vim.fn.feedkeys("i", "n")
    end, { "s" })
end
```

I have used a similar mapping before (but not work), not know what lead to failure...

```lua
{
    mode = { "x" },
    lhs = "<bs>",
    rhs = "<bs>i",
    options = { silent = true },
    description = "Delete the selected text and enter insert mode",
}
```
