### ISSUE TITLE
jsx snippets 

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#794]
I want to expand html snippets defined in `html.lua` in a `.js` file. I want to sort of import this `html.lua` in my `javascript.lua`, but `require 'html' does not work. 

1. I have treesitter.
2. I can expand js snippets inside `<script></script>` tag in html files.
3. I want to expand html snippets inside JavaScript (react) files but context specific expansion doesn't work.
4. I don't want to copy snippets defined in html.lua to javascript.lua

What are some ways I can achieve 3 w/o doing 4?

**Comment by leiserfg** [comment]
Maybe you wanna have a look at https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#filetype_functions

**Comment by nikinbaidar** [comment]
> Maybe you wanna have a look at https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#filetype_functions

Yes this is sort of what I've been trying to achieve. In my config I have
 
```lua
local luasnip = require("luasnip")
local filetype_functions = require('luasnip.extras.filetype_functions')

luasnip.setup({
    ...
    ft_func = filetype_functions.from_cursor_pos,
    load_ft_func = filetype_functions.extend_load_ft({
         javascript = {"markdown"} 
    }),
    ...
})

require("luasnip.loaders.from_lua").load({paths = rt_path .. "/lua/snippets"})
```

but html snippets don't load in js files.

**Comment by nikinbaidar** [comment]
After a bit more research I saw a reference to this in `snippets.lua`. 
Adding `luasnip.filetype_extend("javascript", { "html" })` fixes it.
