### ISSUE TITLE
Access the whole cursor line (including chars after cursor) when executing snippet's `condition` function

### ISSUE THREAD

**Issue by Andrew15-5** [L3MON4D3/LuaSnip#796]
From [documentation](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets):
> `condition`: `fn(line_to_cursor, matched_trigger, captures) -> bool`

I want to create a basic LaTeX check (more robust will be too complicated): don't expand "math mode" if current line has more than 1 `$` char*. But I only have `line_to_cursor` and that is of course not enough. I need to access the chars after the cursor.

Can a new parameter (maybe `cursor_line`) be added to `condition` Or maybe a new "`condition`" parameter with similar name? Or perhaps there is some way to get the current line or more preferably the whole buffer through Lua file with snippets (which is loaded by LuaSnip)?

I don't use Lua for Neovim (yet). Do LuaSnip's Lua snippet files have access to some sort of Neovim's built-in Lua object (table)?

*:

```lua
local function prevent_math_second_expansion(line_to_cursor, matched_trigger)
  local _, count = line_to_cursor:gsub("%$", "")
  return count < 2
end
```

**Comment by L3MON4D3** [comment]
We just pass `line_to_cursor` because it's readily available when `condition` is evaluated.
You can use `vim.api.nvim_get_current_line()` to get the whole line (whole buffer see `nvim_buf_get_lines/text`)

**Comment by Andrew15-5** [comment]
Alriiight, for now this works perfectly:

```lua
local function prevent_math_second_expansion() -- I can omit this: (line_to_cursor, matched_trigger)
  local _, count = vim.api.nvim_get_current_line():gsub("%$", "")
  return count < 2
end
```

Thank you!
