### ISSUE TITLE
`parse_string` list parsing

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#8]
I'm trying to integrate the plugin with <https://github.com/rafamadriz/friendly-snippets> basically by doing the same magic that vsnipet does (iterating over runtimepath looking for packages.json pointing to snippet files). That part is done, but then I discovered that vscode snippets can be ( and most of the time are) defined as a list of strings instead of a single one. If `parse_snippet` were able to read those it will be easy pie to proceed and I could even contribute the code for the snippets loading upstream.

**Comment by leiserfg** [comment]
Seems like it's enough to  join the lines witch `\n`

**Comment by L3MON4D3** [comment]
Jup, AFAICT that's all.
Feel free to open a PR :D

**Comment by carlitux** [comment]
> Seems like it's enough to join the lines witch \n

Yes, I created a python script to load json (vs code) files and create lua file. 

What could be the better approach? to integrate with many snippet formats?

**Comment by L3MON4D3** [comment]
As long as performace is good, parsing json to Luasnip-format sounds alright.

**Comment by leiserfg** [comment]
vsnip is in viml (should be slower) and does the same, so that should not be an issue.

**Comment by L3MON4D3** [comment]
Sweet :+1:
