### ISSUE TITLE
Snippets with empty lines

### ISSUE THREAD

**Issue by clason** [L3MON4D3/LuaSnip#80]
I have a problem with empty lines apparently terminating a snippet definition. Consider the following simple snippet:
```
    s('foo', {t('bar'','','baz')}),
```
which should expand to
```
bar

baz|
```
(with `|` the cursor). But what happens is 
```
bar|
```

**Comment by leiserfg** [comment]
seems like is a problem with passing several strings to `t`  it works fine with 
```lua
       s('foo', {t({'bar','','baz'})}),

```

**Comment by clason** [comment]
Oh, I see, that isn't supported! Knowing that, the examples _do_ only talk about the table syntax. 🤦🏻 

(It's really hard going back and forth between the two -- equally valid -- styles of omitting parentheses around table arguments or not... You wouldn't happen to want to use neovim's `stylua` presets? :])

**Comment by L3MON4D3** [comment]
Oh, could you link those? I can't find them in neovim/neovim

**Comment by clason** [comment]
Still under discussion in core (https://github.com/neovim/neovim/pull/14987) but many related plugins have already made similar settings. (The autoparenthesis setting is still a bit controversial as long as stylua insists on "all or nothing".)
