### ISSUE TITLE
Visual mode keybinding are called when snippet text is selected

### ISSUE THREAD

**Issue by otavioschwanck** [L3MON4D3/LuaSnip#800]
I've mapped J and K to visual mode (drag stuff up/down).  On Snippet text selected, if i try to insert J or K it calls those function instead of just inserting the text.

  vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv")
  vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv")

**Comment by leiserfg** [comment]
Don't use `v` use `x`, `v` is the same as ` {"x", "s"} `

**Comment by otavioschwanck** [comment]
> Don't use `v` use `x`, 'cause `v` is the same as `{"x", "s"}` and snippets selection use `s` mode.

Worked, thanks!
