### ISSUE TITLE
Function node is not being re-evaluated on dependent node text change

### ISSUE THREAD

**Issue by s1n7ax** [L3MON4D3/LuaSnip#801]
I have following test snippet that generate a upper cased value of the variable name using a function node. However the functional node only evaluated on events such as `ls.jump(1)`  or upon entering the normal mode. What am I doing wrong. I tried on `v1.2.1` and currently latest commit https://github.com/L3MON4D3/LuaSnip/commit/f7c845749aba6096f041a73a26ba64f3817bab99

```lua
local ls = require('luasnip')

local fmt = require('luasnip.extras.fmt').fmt
local s = ls.snippet
local i = ls.insert_node
local f = ls.function_node

ls.add_snippets('lua', {
	s(
		'ii',
		fmt('local {} = "{}"', {
			i(1),
			f(function(values)
				vim.pretty_print(values)
				local input_value = values[1][1]
				return { input_value:upper() }
			end, { 1 }),
		})
	),
})
```

Following is the configuration I have

```lua
require('luasnip').config.setup({
	updateevents = 'TextChanged,TextChangedI',
})
```

**Comment by s1n7ax** [comment]
Closing. `updateevents = 'TextChanged,TextChangedI',` fixed it. May be the cache messed up the first time.

**Comment by s1n7ax** [comment]
Re opening (I swear this is the last time). This is an issue in the master branch. `1.2.1` re-evaluates the function node but not in the master branch. At the moment the latest commit is https://github.com/L3MON4D3/LuaSnip/commit/f7c845749aba6096f041a73a26ba64f3817bab99

**Comment by L3MON4D3** [comment]
Oh dammit, looks like that's due to https://github.com/L3MON4D3/LuaSnip/commit/9c659c3239b0ea83e904cc66746a0ebf6c2873c5 :(
I'd assumed `nvim_create_autocmd` can handle event-strings like `event1,event2`, should've tested for it :|
I'll whip up a quick fix, thanks for reporting it :+1:
