### ISSUE TITLE
config.lua unexpected event

### ISSUE THREAD

**Issue by I-Own-You** [L3MON4D3/LuaSnip#802]
I updated today the packages from packer.
It updated your plugin.
After i tried to enter neovim, it started acting weird, stoped working and gave me this error(scrrenshot)

I checked your commits, 12 hours ago you commited some changes, and there are keywords related to my error in the scrrenshot.

![1111](https://user-images.githubusercontent.com/91146968/222569263-c2b4c240-bb10-46ad-b62a-c57ede21173a.png)

**Comment by jemag** [comment]
Same with Lazy.nvim. No error if using commit f7c845749aba6096f041a73a26ba64f3817bab99

**Comment by rockyzhang24** [comment]
Same here. It's introduced by the new commit 5a48c7e22f2c56aa7d8412e1b327d054c917286d.

**Comment by L3MON4D3** [comment]
Whooops, sorry about that. I failed to consider that spaces are in fact allowed in strings xD
Should work again in a bit.

**Comment by L3MON4D3** [comment]
Fixed with 14cb88c825f93604acd846411964938387bc7a87
