### ISSUE TITLE
How to change the load order (priority) of snippets from within the same snippet collection (friendly-snippets)?

### ISSUE THREAD

**Issue by kohane27** [L3MON4D3/LuaSnip#803]
Hello there. Hope you're doing well. Thank you for creating LuaSnip! It makes using snippets in nvim so much more convenient and customizable.

## Scenario

I use [`friendly-snippets`](https://github.com/rafamadriz/friendly-snippets). In the `jsx` file, when I type `map`, the first option is from `html` (`<map></map>`), the second option is `map` iterator for `js`:

First option:
![2023-03-03-10-11-36](https://user-images.githubusercontent.com/57322459/222620359-c3262658-b308-4f51-99ad-6194b4488c42.png)

Second option:
![2023-03-03-10-11-42](https://user-images.githubusercontent.com/57322459/222620373-0b4e5fb8-9a62-4745-bac7-9595fce3bf56.png)

I use the `map` iterator much more than the `html` tag, so I'm trying to change their order (priority) such that the `js` snippets come first than `html` snippets.

## What I've tried

1. I looked into [LOADERS](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#loaders). The option `{override,default}_priority` seems to only deal with the priority of multiple collections, not _within_ the same collection.

### Current workaround

I re-ordered the `/.local/share/nvim/lazy/friendly-snippets/package.json` such that js snippets load first.

From:

```json
    "contributes": {
        "snippets": [
          { "language": [ "html", "javascriptreact"], "path": "./snippets/html.json" },
          { "language": [ "javascript", "javascriptreact"], "path": "./snippets/javascript/javascript.json" },   
```

To:

```json
    "contributes": {
        "snippets": [
          { "language": [ "javascript", "javascriptreact"], "path": "./snippets/javascript/javascript.json" },
          { "language": [ "html", "javascriptreact"], "path": "./snippets/html.json" },
```

But this changes the `friendly-snippets` src folder and will break any new updates.

## Config

```
  -- Autocomplete engine
  {
    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-nvim-lsp",
      "hrsh7th/cmp-nvim-lua",
    },
  },

  -- snippets
  {
    "L3MON4D3/LuaSnip", -- snippet engine
    dependencies = {
      "rafamadriz/friendly-snippets",
      "saadparwaiz1/cmp_luasnip",
    },
  },
```

Any input is much appreciated. Thank you:)

**Comment by L3MON4D3** [comment]
Hi!
Custom priority is actually one of the few properties that can be set from within snipmate, see [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snipmate)

**Comment by L3MON4D3** [comment]
Ha, wait, wrong loader xD
But the vscode-loader also supports priority, [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#vscode)

**Comment by kohane27** [comment]
Thank you for pointing me towards the right doc. Apologies that I didn't check the docs thoroughly enough.
