### ISSUE TITLE
Regex captures in lambda nodes?

### ISSUE THREAD

**Issue by IndianBoy42** [L3MON4D3/LuaSnip#804]
Is it possible or could it be added to be able to access the capture groups of a regex triggered snippet from a lambda node? I often find myself simply needing to substitute in the capture groups from the regex/pattern into various places. and afaict right now I have to make a whole function node just to return it, seems like the exact use case of a lambda/dynamic-lambda

**Comment by leiserfg** [comment]
Try with l.LS_CAPTURE_n (where n is the index of the capture).

**Comment by IndianBoy42** [comment]
Oh yeah that works, I didn't realize that those variables are also available in lambdas.  A bit verbose but definitely better
