### ISSUE TITLE
Bug in nested noded

### ISSUE THREAD

**Issue by hinell** [L3MON4D3/LuaSnip#805]
```json
{
  
  "nested": {
    "prefix": "nested",
    "description": "Nested nodes?",
    "body": [
      "TEST: ${3:[${4:$CURRENT_MONTH_NAME $CURRENT_DATE, $CURRENT_YEAR}]} ${2:Foo}"
    ]
  }
}
```
With the above VSCode/LSP snippet expanded (note nested nodes) I get the following error:

```shell

Error executing vim.schedule lua callback: .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:770: attempt to 
index local 'node_text' (a nil value)
stack traceback:
        .../pack/packer/start/LuaSnip/lua/luasnip/nodes/snippet.lua:770: in function 'get_static_text'
        ...start/cmp-luasnip-choice/lua/cmp_luasnip_choice/init.lua:61: in function 'complete'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:325: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:289: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:77: in function 'complete'
        ...start/cmp-luasnip-choice/lua/cmp_luasnip_choice/init.lua:23: in function <...start/cmp-luasnip-choice/lua/cm
p_luasnip_choice/init.lua:22>

```

### Context
I'm using LuaSnip via
* `NVIM v0.9.0-dev-d3355ad`
* `nvim-cmp`

**Comment by L3MON4D3** [comment]
Oh, that seems to be an issue with `cmp-luasnip-choice`, there are some wrong assumptions in their code.
Open an issue there, I'll look into improving the API for what they want to do so it's possible without relying on internals

**Comment by hinell** [comment]
@L3MON4D3 Please, direct me at the specific file/place where to look at. I'm going to link it into a new issue. Thank you.

**Comment by L3MON4D3** [comment]
It's basically just replacing [these lines, responsible for getting the text of the choices](https://github.com/doxnit/cmp-luasnip-choice/blob/97a367851bc17984b56164b5427a53919aed873a/lua/cmp_luasnip_choice/init.lua#L55-L63) with `ls.get_current_choices()`.
I'll change my opinion, a quick PR would probably be better than an issue.
If you're comfortable with lua, making the change yourself would be pretty nice, if not, I can take care of that :)

**Comment by L3MON4D3** [comment]
Did it! I'm going to close this, with the PR as continuation of the discussion
