### ISSUE TITLE
Go to next placeholder

### ISSUE THREAD

**Issue by leana8959** [L3MON4D3/LuaSnip#806]
Hello,

Is it possible to go to the next placeholder with a shortcut?

I have set up my configuration files as indicated in the readme.  
I use `LuaSnip` (vscode-format snippets) with `nvim-cmp`, and my configuration is as follows
```lua
local cmp = require("cmp")
local luasnip = require("luasnip")

require "luasnip.loaders.from_vscode".lazy_load({ paths = { "./snippets" } })

vim.keymap.set('s', "<Tab>", function() require "luasnip".jump(1) end, { noremap = true, silent = true })
vim.keymap.set('s', "<S-Tab>", function() require "luasnip".jump( -1) end, { noremap = true, silent = true })

cmp.setup({
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert {
    ['<C-d>'] = cmp.mapping.scroll_docs( -4),
    ['<C-u>'] = cmp.mapping.scroll_docs(4),
    -- ['<C-Space>'] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    },
    ['<Tab>'] = cmp.mapping.select_next_item(),
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
  },
  sources = {
    { name = "nvim_lsp" },
    { name = "luasnip" },
  },
})
```
However, it doesn't seem to work, when I have multiple placeholders, hitting <kbd>Tab</kbd> would only insert a tab character.

Thank you :)

**Comment by evesdropper** [comment]
I think you might want to try a ["super-tab" setup](https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#luasnip), where if there's a luasnip snippet, then it goes to the next placeholder, else next item, else tab.

**Comment by leana8959** [comment]
That worked like a charm, thank you so much!
