### ISSUE TITLE
checkout failed error while updating luasnip

### ISSUE THREAD

**Issue by Oyinbra** [L3MON4D3/LuaSnip#807]
i always get this checkout fail error message whenever i update my plugins. 
~/local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/git.lua:58: attempt to index local 'range' (a nil value)

and when i checked the line, it says
``
if v and range:matches(v) then
   v.tag = tag
   table.insert(versions, v)
end
``
i'm using lazy setup.

My current installation looks like this
``
return {
  "L3MON4D3/LuaSnip",
  -- follow latest release.
  version = "<CurrentMajor>.*",
  -- install jsregexp (optional!).
  build = "make install_jsregexp",
}
``

**Comment by L3MON4D3** [comment]
Ah, you have to replace  `<CurrentMajor>` with the current major version of Luasnip ie. `1`

**Comment by Oyinbra** [comment]
It was a success. Thank you.
