### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by pierce-c** [L3MON4D3/LuaSnip#809]
when starting neovim 0.6.1, it gives the following error message:

Error detected while processing /home/username/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...m/pack/packer/start/LuaSnip/lua/luasnip/loaders/init.lua:108: attempt to call field 'nvim_create_augroup' (a nil value)
traceback stuff
also
E5113: Error while calling lua chunk: ...config/nvim/pack/packer/start/LuaSnip/plugin/luasnip.lua:1: attempt to index field 'filetype' (nil value)
traceback stuff

i checked :lua print(vim.inspect(package.loaded)) command and those two commands are not part of the vim interface for this version. Perhaps there is a workaround?

**Comment by leiserfg** [comment]
In order to use luasnip from the  master branch, you need to use the latest stable release of nvim.

**Comment by leiserfg** [comment]
> which is that, and can i get it with apt?

Well, answering that depends on your distro, you can find the latest version here

In any case you can find it here

 https://github.com/neovim/neovim/releases/tag/stable

**Comment by leiserfg** [comment]
You better ask in a place where users of your distro could help (reddit/r/neovim for instance),  I don't use debian (or ubuntu, not sure what you use) and therefore can't help you recover if something breaks.

**Comment by pierce-c** [comment]
i updated it to latest version by uninstalling and reinstalling nvim, and it still wont work but for different reason, also it isn't loading colorschemes.

**Comment by pierce-c** [comment]
error calling chunk "LuaSnip/lua/luasnip/loaders/from_lua.lua:67: Failed to execute {snippet filename}"
"Luasnip/lua/luasnip/extras/fmt.lua:91: Missing key `<>` in format arguments: "`\textrm{<>}`
stack traceback:
in function error in LuaSnip/lua/luasnip/loaders/from_lua.lua:67: in funtion load_files
LuaSnip/lua/luasnip/loaders/from_lua.lua: in function load
from init.lua

**Comment by leiserfg** [comment]
Well, that's something else, seems like your snippet is incorrect.

**Comment by pierce-c** [comment]
its not
it worked before
the backslash is escaped and  everything
its having this issue for similar snippets

**Comment by L3MON4D3** [comment]
We changed some error-reporting, not that recently, but maybe it was included in your update
Could you show one of the snippet causing this issue?

**Comment by pierce-c** [comment]
sure
s("rm",fmta("\\textrm{<>}",{i(1)})),

**Comment by L3MON4D3** [comment]
Works fine for me :/

```lua
ls.setup_snip_env()

ls.snip_expand(s("rm",
	fmta("\\textrm{<>}", {i(1)})
))
```

Could you produce a minimal example where the errors occur? Preferably a single file I could just run
(or share your config, I could take a look and see if anything catches my eye)

**Comment by pierce-c** [comment]
`require("luasnip.loaders.from_lua").load({paths = "/home/pierce/.config/nvim/lua/snips/"})`
is the line in my config
`return {
	s("rm",fmta("\\textrm{<>}",{i(1)})),
}`
is the minimum of the snippet that used to work, but now doesn't

**Comment by L3MON4D3** [comment]
Okay, taking a closer look at the original error, it looks like your fmta is actually fmt. Do you have a `ls.setup(...)` somewhere? If, would you share it?

**Comment by L3MON4D3** [comment]
Mhm, that shouldn't cause any issues.
Could you explicitly add `local fmta = require("luasnip.extras.fmt").fmta` before using it?

**Comment by pierce-c** [comment]
that worked

**Comment by L3MON4D3** [comment]
Nice!
Still, it shouldn't be necessary, maybe check your luasnip-version, or if something is conflicting
