### ISSUE TITLE
Can transform in insert node?

### ISSUE THREAD

**Issue by nguyen-quang-phu** [L3MON4D3/LuaSnip#817]
Hi L3MON4D3, i a newbie in vim, and i want to write my own snippet. This plugin is so cool, but i can't find how to transform insert node. When i enter text and i want transform it from camelCase to snake_case. Can you help me how to write it? Have a nice day.

**Comment by no-vici** [comment]
Why don't you use neovim? Have out read the [docs](https://github.com/L3MON4D3/LuaSnip/tree/master/doc) thoroughly? Changing cases can be triggered with  the "~" key in normal mode without the need of LuaSnip.

I think what you want to achieve can be done with  Choice Nodes. Don't bother the main author, he has tons of work to do, I can work along with you to achieve what you wanted.

**Comment by nguyen-quang-phu** [comment]
Thank you for comment. I read docs but I can't find solution. Because if i use function node or restore node,i must have 1 insert node and after cannot replace it like below video(this video is how i want the snippet to work).And i don't understand how to use choice node to write it.
I use ruby for backend and react for frontend, so i think use camelCase for all. Sorry if that bothers you and author. Have a nice day.

https://user-images.githubusercontent.com/43996827/224561970-5191c770-2b77-4783-b219-011c747455ba.mov

**Comment by no-vici** [comment]
>  Because if i use function node or restore node,i must have 1 insert node and after cannot replace it like below video(this video is how i want the snippet to work).And i don't understand how to use choice node to write it. 

Talking about the choice node, [this tutorial](https://www.youtube.com/watch?v=vLb6k5cfJ-g) might help.

Sometimes, we may need to utilise the combination of choice node, function node, snippet node and dynamic node to achieve what we want, and here is another helpful [beginner guide](https://evesdropper.dev/files/luasnip/choice-dynamic/).

Below is an example snippet the uses the combination mentioned above.

```
-- start-stop version 1
	s({
		trig = "start",        
		name = "start and stop environments",
		dscr = "enclosing env based on input text",
	}, {
		-- f(function(_, snip)
		-- 	return snip.captures[1]
		-- end, {}),
		t({ "\\start" }),
		c(1, {
			i(nil, "type_here"),
			t("chapter"),
            t("columns"),
            t("formula"),
			t("itemize"),
            t("matrix"),
            t("placefloat"),
			t("placefigure"),
			t("section"),
			t("subsection"),
            t("table"),
            t("text"),
            t("TEXpage"),
            t("theorem"),
		}),
		d(2, function(args)
			-- The function inside dynamicNode always return a snippetNode.
			-- If you ask it to return strings, you are in trouble!
			-- args[1][1] is the input text from i(1)
			local ipt = args[1][1] -- 'ipt' is input text
			if ipt == "chapter" or  ipt == "theorem" or ipt == "section" or ipt == "subsection" then
				return sn(nil, { t({ "[title={" }), i(1), t({ "}]" }), t({ "", "", "" }), i(2, "input text") })
            elseif ipt == "columns" then
                return sn(nil, { t("["), i(1, "n=2,separator=rule"), t("]"), t({ "", "", "\t" }), i(2, "--columns_content") })
			elseif ipt == "itemize" then
				return sn(nil, { t("["), i(1, "a"), t("]"), t({ "", "", "\\item " }), i(2, "your item") })
            elseif ipt == "matrix" then -- [left={\left(},right={\right)}]
                return sn(nil, { t("[left={\\left"), i(1, "("), t("},right={\\right"), i(2, ")"), t("}]"), t({ "", "", "\t" }), i(3, "--code") })
			elseif ipt == "placefigure" then
				return sn(
					nil,
					{ t({ "", "", "\t\\externalfigure[" }), i(1, "fig"), t({ "][" }), i(2, "opt"), t({ "]" }) }
				)
            elseif ipt == "table" then
                return sn(nil, { t("["), i(1,"|c|c|"), t("]"), t({ "", "", "\t" }), i(2, "--table_content") })
            elseif ipt == "TEXpage" then
                return sn(nil, { t("["), i(1, "options(align=middle...)"), t("]"), t({ "", "", "\t" }), i(2, "--TEXpage_content") })
			else
				return sn(nil, { t({ "", "", "" }), i(1, "input text") })
			end
		end, { 1 }),

		t({ "", "", "\\stop" }),
		rep(1),
	}, {
        condition = line_begin
    }),
```
Hope that will help you fine-tune your snippet for the camelCase. Could you provide a sample code and explain what you'd like to get, then we can work it out together.

**Comment by no-vici** [comment]
> I'm thinking you can take a different approach and use a postfix snippet for this. Assuming that everything follows camelCase exactly, you can create a snippet that replaces any occasion of an upper case letter with `_<>`, where `<>` represents the letter in lowercase.

That is very clever and seems to be the best and simplest approach though.

**Comment by nguyen-quang-phu** [comment]
> > Because if i use function node or restore node,i must have 1 insert node and after cannot replace it like below video(this video is how i want the snippet to work).And i don't understand how to use choice node to write it.
> 
> Talking about the choice node, [this tutorial](https://www.youtube.com/watch?v=vLb6k5cfJ-g) might help.
> 
> Sometimes, we may need to utilise the combination of choice node, function node, snippet node and dynamic node to achieve what we want, and here is another helpful [beginner guide](https://evesdropper.dev/files/luasnip/choice-dynamic/).
> 
> Below is an example snippet the uses the combination mentioned above.
> 
> ```
> 	
> 	-- start-stop version 1
> 	s({
> 		
> 		trig = "start",
> 		
> 		name = "start and stop environments",
> 		dscr = "enclosing env based on input text",
> 	}, {
> 		
> 		t({ "\\start" }),
> 		c(1, {
> 			i(nil, "type_here"),
> 			t("chapter"),
> 			t("columns"),
> 			t("formula"),
> 			t("itemize"),
> 			t("matrix"),
> 			t("placefloat"),
> 			t("placefigure"),
> 			t("section"),
> 			t("subsection"),
> 			t("table"),
> 			t("text"),
> 			t("TEXpage"),
> 			t("theorem"),
> 		}),
> 		d(2, function(args)
> 			-- The function inside dynamicNode always return a snippetNode.
> 			-- If you ask it to return strings, you are in trouble!
> 			-- args[1][1] is the input text from i(1)
> 			local ipt = args[1][1] -- 'ipt' is input text
> 			if ipt == "chapter" or ipt == "theorem" or ipt == "section" or ipt == "subsection" then
> 				return sn(nil, { t({ "[title={" }), i(1), t({ "}]" }), t({ "", "", "" }), i(2, "input text") })
> 			elseif ipt == "columns" then
> 				return sn(
> 					nil,
> 					{ t("["), i(1, "n=2,separator=rule"), t("]"), t({ "", "", "\t" }), i(2, "--columns_content") }
> 				)
> 			elseif ipt == "itemize" then
> 				return sn(nil, { t("["), i(1, "a"), t("]"), t({ "", "", "\\item " }), i(2, "your item") })
> 			elseif ipt == "matrix" then -- [left={\left(},right={\right)}]
> 				return sn(
> 					nil,
> 					{
> 						t("[left={\\left"),
> 						i(1, "("),
> 						t("},right={\\right"),
> 						i(2, ")"),
> 						t("}]"),
> 						t({ "", "", "\t" }),
> 						i(3, "--code"),
> 					}
> 				)
> 			elseif ipt == "placefigure" then
> 				return sn(
> 					nil,
> 					{ t({ "", "", "\t\\externalfigure[" }), i(1, "fig"), t({ "][" }), i(2, "opt"), t({ "]" }) }
> 				)
> 			elseif ipt == "table" then
> 				return sn(nil, { t("["), i(1, "|c|c|"), t("]"), t({ "", "", "\t" }), i(2, "--table_content") })
> 			elseif ipt == "TEXpage" then
> 				return sn(
> 					nil,
> 					{ t("["), i(1, "options(align=middle...)"), t("]"), t({ "", "", "\t" }), i(2, "--TEXpage_content") }
> 				)
> 			else
> 				return sn(nil, { t({ "", "", "" }), i(1, "input text") })
> 			end
> 		end, { 1 }),
> 
> 		t({ "", "", "\\stop" }),
> 		rep(1),
> 	}, {
> 		condition = line_begin,
> 	}),
> ```
> 
> Hope that will help you fine-tune your snippet for the camelCase. Could you provide a sample code and explain what you'd like to get, then we can work it out together.

Thank you,  but i want to code without remember language convention. That's an important thing. In vscode, i write like that
"Declare Assign": {
    "prefix": [
      "da",
      "Declare Assign"
    ],
    "scope": "ruby",
    "body": [
      "${1/([a-z]+)(?=[A-Z])|([A-Z])(?=[A-Z])|([A-Z][a-z]+)(?=$)|([A-Z][a-z]+)|([a-z]+)(?=$)/${1:/downcase}${1:+_}$2${2:+_}${3:/downcase}${4:/downcase}${4:+_}${5:/downcase}/g} = ${2}",
    ],
    "description": "Declare Assign"
  },
  "Declare Intance Method": {
    "prefix": ["dim","Declare Intance Method"],
    "scope": "ruby",
    "body": [
      "def ${1/([a-z]+)(?=[A-Z])|([A-Z])(?=[A-Z])|([A-Z][a-z]+)(?=$)|([A-Z][a-z]+)|([a-z]+)(?=$)/${1:/downcase}${1:+_}$2${2:+_}${3:/downcase}${4:/downcase}${4:+_}${5:/downcase}/g}($2)",
      "\t$3",
      "end"
    ],
    "description": "Declare Intance Method"
  }

You can read more in https://github.com/nguyen-quang-phu/harvey-snippets/blob/main/snippets/Ruby.code-snippets .
I want create a set of snippets for ruby and js, maybe others language. And it convert to language convention and i don't remember this language use camelCase or snake_case,...

**Comment by nguyen-quang-phu** [comment]
> I'm thinking you can take a different approach and use a postfix snippet for this. Assuming that everything follows camelCase exactly, you can create a snippet that replaces any occasion of an upper case letter with `_<>`, where `<>` represents the letter in lowercase.
> 
> Here's an implementation I whipped up:
> 
> ```lua
> postfix(".cc", {l(l.POSTFIX_MATCH:gsub("(%u)", "_%1"):lower())}) -- feel free to modify the trigger
> ```
> 
> ![camelcase-transform](https://user-images.githubusercontent.com/82856360/224642628-1875e9cb-9a13-48b3-8757-84af4c215b97.gif) [ ](https://user-images.githubusercontent.com/82856360/224642628-1875e9cb-9a13-48b3-8757-84af4c215b97.gif) ![camelcase-transform](https://user-images.githubusercontent.com/82856360/224642628-1875e9cb-9a13-48b3-8757-84af4c215b97.gif) [ ](https://user-images.githubusercontent.com/82856360/224642628-1875e9cb-9a13-48b3-8757-84af4c215b97.gif)
> 
> Hope that helps!

Thank you, I've been thinking about it. But i don't want like that. Because i must manual change it to snake_case or camelCase. If so, maybe I'll find a plugin to do it instead of writing a snippet. Anyway thank you so much

**Comment by evesdropper** [comment]
Gotcha. Well you can also use VSCode loader alongside Lua loader for snippets, so your Ruby snippets won't be lost.
