### ISSUE TITLE
Add dynamic lambdas

### ISSUE THREAD

**Issue by clason** [L3MON4D3/LuaSnip#82]
The newly introduced lambdas are a convenient way of inserting transformed input into snippets. However, they produce text nodes and can therefore not be used as placeholder text in input nodes, which would be similarly convenient, e.g., for Lua snippets like
```lua
 s('local', {t 'local ', i(2, l(l._1:match("[^.]+$"), 1)), t' = ', i(1)});
 ```
(which doesn't work).

A working version (thanks to @kmarius9) is
```lua
s( 'local',
      { t 'local ', d(2, function(arg)
        return S(nil, { i(1, arg[1][1]:match '[^.]+$') })
      end, { 1 }), 
      t ' = ', i(1) }
  ),
```
but that's a bit unwieldy to write and is too close to cargo cult (hard to understand and therefore fix when things break).

It would therefore be nice if there were a "dynamic" version of lambdas that _could_ be used as default placeholder text with the same syntax, e.g., `i(2, dl(l._1:match("[^.]+$"), 1))`.

**Comment by L3MON4D3** [comment]
> `i(2, dl(l._1:match("[^.]+$"), 1))`

That would be rather hard to implement (give normal insertNodes functionality to get text from other nodes), how about doing it similar to lambdas themselves, eg.`dl(2, l._1:match("[^.]+$"), 1)`, but you get an insertNode instead of plain text?

**Comment by clason** [comment]
I have to admit I don't understand the architecture (yet), so I defer to you on the best way to achieve what I'm actually after: a reasonably concise (and discoverable/understandable) way of writing common tasks. 

"Flipping" by instead introducing a "dynamic insert" pseudonode `di(...)` with the signature you give would do just as nicely!

**Comment by L3MON4D3** [comment]
Okay, perfect.
How is updating handled in `snippets.nvim`? With the naive implementation it would update each time the text in the argument-node is changed, independent of text entered in the dynamicInsert.

**Comment by clason** [comment]
Ah, `snippets.nvim` "cheats" a bit by having this "floaty" inserter by default so you are basically limited to updating when jumping. 

What do you mean exactly (I have to learn the proper terminology.) If it "live updates" the default text while I type, that'd be fine with me.

**Comment by L3MON4D3** [comment]
With eg.
```lua
s( 'local',
      { t 'local ', d(2, function(arg)
        return S(nil, { i(1, arg[1][1]:match '[^.]+$') })
      end, { 1 }), 
      t ' = ', i(1) }
  )
```
If one would jump to `i1`, insert some text (`i2` updates), then jump to `i2`, change the text, then go back to `i1`. Up until now, `i2` still has the user-entered text, but if the user now changes the text in `i1`, `i2` would now also change.
I think that'd be the generally expected behaviour, just wanted to see if snippets.nvim has maybe done something special.

**Comment by L3MON4D3** [comment]
(Obviously updates depends on what is set in `updateevents`, if it's empty we also only update on jumping)

**Comment by clason** [comment]
Ah, good point -- I almost never jump back, only forward. (Sharks don't look back. Because sharks don't have necks.)

**Comment by clason** [comment]
My naive expectation would be once I type something overwriting the default text, that default is gone and _stays_ gone. But as long as it's deterministic and robust, the alternative (`i2` reverts to the -- updated -- default text) is also fine.

**Comment by L3MON4D3** [comment]
> Ah, good point -- I almost never jump back, only forward. (Sharks don't look back. Because sharks don't have necks.)

Nice one ;D

**Comment by L3MON4D3** [comment]
Check out 3e4ca29, looks good?

**Comment by clason** [comment]
Let's see if I understand this correctly: the snippet
```lua
s('local', { t 'local ', d(2, tail(1), { 1 }), t ' = ', i(1) })
```
(where `tail` produces the `d` node in your suggestion) becomes
```lua
s('local', { t 'local', dl(2, l._1:match('[^.]+$'), {1}), i(1) })
```
?

**Comment by L3MON4D3** [comment]
Except the missing ` = `, yes.
(You could even lose the `{`,`}` around 1, those are auto-inserted)

**Comment by clason** [comment]
Nice, then it looks great!

**Comment by L3MON4D3** [comment]
👌

**Comment by clason** [comment]
Hmm, that doesn't seem to quite work:
```lua
    s('local', { t 'local ', dl(2, l._1:match('[^.]+$'), 1), t ' = ', i(1), t { '', '' } }),
```
gives me 
```
E5108: Error executing lua vim/shared.lua:64: s: expected string, got nil
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        ...te/pack/packer/start/luasnip/lua/luasnip/extras/init.lua:118: in function 'fn'
        ...k/packer/start/luasnip/lua/luasnip/nodes/dynamicNode.lua:71: in function 'update'
        .../pack/packer/start/luasnip/lua/luasnip/nodes/snippet.lua:517: in function 'update'
        .../pack/packer/start/luasnip/lua/luasnip/nodes/snippet.lua:237: in function 'trigger_expand'
        ...nvim/site/pack/packer/start/luasnip/lua/luasnip/init.lua:87: in function 'expand'
        ...nvim/site/pack/packer/start/luasnip/lua/luasnip/init.lua:106: in function 'expand_or_jump'
        [string ":lua"]:1: in main chunk
```

**Comment by L3MON4D3** [comment]
Ah, yeah MB, that's probably because there's no error handling for nil from the lambda. Could you try `match("^.*([^. ]*)$")` or some variation to avoid not matching at all?

**Comment by L3MON4D3** [comment]
I'll add a default of `""` to avoid those errors.

**Comment by clason** [comment]
I could, but then I wouldn't understand the regex anymore ;)

The `d` node handles that fine, though?

**Comment by L3MON4D3** [comment]
Yes, the error happens before that (when `vim.split`ting that `nil` in `dynamic_lambda`).
dec9650 ?

**Comment by clason** [comment]
Yes, now it works fine 👍🏻 

Thank you!
