### ISSUE TITLE
Autosnippets don't auto-expand in markdown when `ft_func = ls_ft.from_cursor_pos` is set

### ISSUE THREAD

**Issue by kamalsacranie** [L3MON4D3/LuaSnip#823]
Hello. Firstly, thanks for creating and maintaining such a great plugin.

Basically, I use the [markdown treesitter parser](https://github.com/MDeiml/tree-sitter-markdown) when writing markdown because I can inject syntax highlighting into code blocks, use tree sitter queries to check for conditions for expansion, etc. In order to do this however, I need to have my `ft_func` set to `require("luasnip.extras.filetype_functions").from_cursor_pos` which allows the correct snippets based on the injected parser (an amazingly useful feature). When I set this option in a very minimal config with only luasnip and cmp, the auto snippets don't expand for markdown files but do for the other filetypes like python and JS. I have created a repo with a config to hopefully replicate the issue [here](https://github.com/kamalsacranie/luasnip-markdown-issue). Let me know if you need any other info.

```
$ nvim -v
NVIM v0.9.0-dev-2423+ge5f4394eb-dirty
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-e5f4394/share/nvim"

Run :checkhealth for more info
```

**Comment by L3MON4D3** [comment]
Wow, that's definitely the nicest MWE I've ever seen :ok_hand:

Is it possible you're just missing the mardown-parser, or treesitter can't talk to it for some reason? Once I installed it in your MWE, everything worked as expected

**Comment by kamalsacranie** [comment]
I don't' know what an MWE is but thank you 😌. So I think the problem arises from the fact that the [markdown treesitter parser](https://github.com/MDeiml/tree-sitter-markdown) used two separate parsers in tandem; `tree-sitter-markdown-inline` and `tree-sitter-markdown`. When I `TSInstall markdown` the auto snippets work but when I install both grammars required by the spec that's when auto snippets stop. When installed the parsers did you install both the regular markdown one and the inline one, or just the markdown one?

**Comment by L3MON4D3** [comment]
Mwe=minimal working example ;)

I only installed the regular one, seem like there's some kind of interference when both are used?
Not at my machine at the moment, you could modify your source of Luasnip and sprinkle some `print`s around `from_cursor_pos` (start with the returned value, should be `{"markdown"}`) to debug this

**Comment by kamalsacranie** [comment]
Ah the problem stems from the fact that the grammar's name returns as `markdown_inline` which of course isn't a native filetype. A quick fix is to `ls.filetype_extend("markdown_inline, {markdown})` in my config. Unless you could recommend a better way to patch this edge case?
