### ISSUE TITLE
Error: No such group or event: table [...] active_update_dependents()

### ISSUE THREAD

**Issue by ziutech** [L3MON4D3/LuaSnip#829]
### Description
After setting a setup option a error message is shown on nvim startup.

<details><summary>Error message</summary>
<p>

> Error detected while processing /home/krzysztof/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: ...of/.local/share/nvim/lazy/LuaSnip/lua/luasnip/
config.lua:177: Vim(autocmd):E216: No such group or event: table: 0x7fc72b19dc70 * lua
require("luasnip").active_update_dependents() stack traceback:
        [C]: in function 'cmd'
        ...of/.local/share/nvim/lazy/LuaSnip/lua/luasnip/config.lua:177: in function 'setup'
        ...of/.local/share/nvim/lazy/LuaSnip/lua/luasnip/config.lua:173: in function 'setup'
        /home/krzysztof/.config/nvim/lua/user/luasnip.lua:22: in main chunk
        [C]: in function 'require'
        /home/krzysztof/.config/nvim/lua/user/init.lua:12: in main chunk
        [C]: in function 'require'
        /home/krzysztof/.config/nvim/init.lua:18: in main chunk
</p>
</details>
This is how I setup LuaSnip

```lua
ls.setup({
        history = false,
	update_events = { "textchanged", "textchangedi" }, -- without this line no error is displayed
	enable_autosnippets = true,
	delete_check_events = "insertleave",
	region_check_events = "cursormoved",
})
```
I also use `nvim-cmp` and `cmp_luasnip`, if this changes anything.
I apologize for such a undescriptive bug report, but I'm not even sure how to debug this.

**Comment by L3MON4D3** [comment]
Oh, I think it's just that you're on a version of Luasnip which does not yet support specifying the event via lua-table.
Try `"TextChangedI,TextChanged"`
