### ISSUE TITLE
Is there a way to live-toggle LuaSnip and/or autosnippets?

### ISSUE THREAD

**Issue by RobinTruax** [L3MON4D3/LuaSnip#832]
Hi, new user here loading LuaSnip with lazy.nvim. I'd like to have the ability to toggle snippets and autosnippets on and off without restarting neovim -- though I expect that I won't want to do this often, cases will likely still arise (especially if I aggressively create snippets). I can't find anything on this in the documentation or other issues (though I may have missed something!). The closest I could find was the enable_autosnippets option for the setup, but it seems as if this is something that's only run once. Could I rerun setup to toggle autosnippets without restarting neovim? Is there a similar setting to toggle all snippets? Thanks, and apologies if I missed something obvious in the documentation.

**Comment by L3MON4D3** [comment]
Hi!
You haven't missed anything, toggling autosnippets alone is not "officially" possible.

> Could I rerun setup to toggle autosnippets without restarting neovim?

That should not cause any issues :+1:
However, I think we should consider adding a proper api for setting/toggling isolated options.

What you can do, "inofficially", is set `require("luasnip").expand_auto` to an empty function to disable it. (You'd also have to store the original if it should be possible to re-enable it)

---

Not sure what exactly your motivation for this feature is, but it sounds a bit like `condition` might be useful to you? (assuming you disable them in some specific context)

**Comment by RobinTruax** [comment]
That makes sense, thanks! One thing: you say that toggling autosnippets _alone_ is not officially supported (though your unofficial idea is a great suggestion and I will implement that in my config). Does that mean toggling snippets in _general_ is? I can't find a method for that, but I could've missed something. Or is the best strategy to use the "unofficial method" for that as well?

**Comment by L3MON4D3** [comment]
Ah, no, the alone was supposed to refer to only setting autosnippets as opposed to all config-values😅

> Or is the best strategy to use the "unofficial method" for that as well?

Yup, exactly
But you'd have to modify ls.snip_expand instead of expand_auto

**Comment by RobinTruax** [comment]
Awesome, makes sense. Much appreciated.
