### ISSUE TITLE
wierd bug doesn't let me choose

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#833]
I have this simple snippet:
```lua
    snippet("m", fmt([[
    {}.map({} => {{
        {}
        return {}
    }});
    ]] , {
        i(2, ""),
        c(1, {
            t "(item, index)",
            t "item"
        }),
        i(3),
        i(4),
    })),
```

I can't seem to change the text at the second node unless I chang `map({} ...` to `map( {} ...` in line 2. Why is this occurring and Is there a way to fix it because I don't want that extra space on my snippet and its completely throwing me off.

**Comment by nikinbaidar** [comment]
Okay so I had `<C-l>` bound to the function responsible for cycling the choices. Turns out I also had `<C-l>` bound to selecting completion options in my `nvim-cmp` config. Modifying nvim-cmp config is what solved the issue. Thank you for pointing it out that it was working for you!

**Comment by L3MON4D3** [comment]
Ahh, space -> no completion, ofc.
Glad it helped :)
