### ISSUE TITLE
Disable expansion of autosnippets if in comment

### ISSUE THREAD

**Issue by matthewsia98** [L3MON4D3/LuaSnip#837]
Is there a way to disable expansion of autosnippets if I am currently in a comment node?

Say I want to set up an autosnippet that triggers on the word `if` and expands to 
```lua
if $1 then
    $2
end
```

However, I do not want the snippet to get expanded if I type the word `if` in a comment like
```lua
-- Do this if x else do y
```

**Comment by L3MON4D3** [comment]
Check `condition` [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets), you'd just have to figure out how to check what (treesitter?-)node you're in

**Comment by matthewsia98** [comment]
Thanks.

**Comment by matthewsia98** [comment]
hmmm doesn't seem to work
seems like it has to do with the timing of when the function runs

with the snippet set up like below, after typing `-- if`, the function prints `chunk`
however if i manually run `:lua require("nvim-treesitter.ts_utils").get_node_at_cursor():type()` it prints out `comment`

```lua
  s(
      {
          trig = "if",
          snippetType = "autosnippet",
          condition = function()
              print(require("nvim-treesitter.ts_utils").get_node_at_cursor():type())
              -- return require("nvim-treesitter.ts_utils").get_node_at_cursor():type() ~= "comment"
          end,
      },
      fmt(
          [[
          if {} then
              {}
          end
          ]],
          {
              i(1, "condition"),
              i(2, "body"),
          }
      )
  ),
```

**Comment by L3MON4D3** [comment]
Maybe it's because when you're running manually the cursor is on `f`, while during snippet-evaluation it's behind the `f`? And `comment` only includes the `f`, but not whatever comes after?
Actually, an elegant solution would be to check what node the beginning of the trigger is inside, that should give consistent, or at least more consistent, results

**Comment by matthewsia98** [comment]
this seems to work from initial testing, but not sure how robust it is
open to other suggestions as well

```lua
{
    trig = "if",
    snippetType = "autosnippet",
    condition = function(line_to_cursor, matched_trigger, captures)
        local _, row, col, _, _ = unpack(vim.fn.getcurpos())
        local node = vim.treesitter.get_node({
            pos = { row - 1, col - #matched_trigger - 1 },
        })
        return node and node:type() ~= "comment"
    end,
},
```

**Comment by L3MON4D3** [comment]
Nice!
There's the 1,1 to 0,0-conversion,  subtraction of matched-trigger-length from the current cursor to get the column of the first character of the trigger, and I don't think there's any situation where the cursor is at a different place than just behind the trigger.. nothing to take away so I'd say that's perfect :+1: :)
