### ISSUE TITLE
Bad performance in deep nested dynamic nodes

### ISSUE THREAD

**Issue by Entoryvekum** [L3MON4D3/LuaSnip#839]
The code below implemented a snippet to help input matrix. It insert 2 spaces when `&` is detected and insert a new row when `\\` is detected.

```
local function Matrix1()
    --SimpleMatrix
    local generateElm
    generateElm=function()
        return sn(
            nil,{
                t{"  "},
                i(1),
                d(2,
                    function (arg,snip,oldState)
                        local str=arg[1][1]
                        local len=string.len(str)
                        if string.sub(str,len,len)=="&" then
                            return sn(nil,{d(1,generateElm,{})})
                        elseif string.sub(str,len-1,len)=="\\\\" then
                            return sn(nil,{t{"",""},d(1,generateElm,{})})
                        else
                            return sn(nil,{})
                        end
                    end,
                    {1}
                )
            }
        )
    end
    snip(
        s({trig="mat",hidden=true},{
            t{"\\begin{matrix}",""},
            d(1,
                function (arg,snip,oldState)
                    return sn(nil,{d(1,generateElm,{})})
                end
            ),
            t{"","\\end{matrix}"}
        },{condition=mathZone})
    )
end
Matrix1()
```

The `snip` function will insert the snippet to the table that will be returned to the loader.

However, as the matrix getting larger the performance decreases dramaticly.

![2023-03-23 20-47-08_3](https://user-images.githubusercontent.com/20198566/227217272-fe75269a-d3ea-428c-afb8-f9ec42b543c3.gif)

The gif show tht after I typed in the entire row, vim sponse very slow.

**Comment by L3MON4D3** [comment]
Phuh, yeah I haven't given much thought to performance yet, there are probably many points that could be optimized.
But also, try not to nest the snippet as deep 😬😬
Maybe hook `&` in insertNode up to update the external_update_dynamicnode, and generate all those insertNodes as children of one dynamicNode

**Comment by L3MON4D3** [comment]
Phuh, yeah I haven't given much thought to performance yet, there are probably many points that could be optimized.
But also, try not to nest the snippet that deep 😬😬
Maybe hook `&` in insertNode up to update the external_update_dynamicnode, and generate all those insertNodes as children of one dynamicNode

**Comment by L3MON4D3** [comment]
Did some work in #852, it's faster now :)
