### ISSUE TITLE
Load workspace setting snippets from .vscode dir

### ISSUE THREAD

**Issue by changangus** [L3MON4D3/LuaSnip#850]
Hi, 

First off thanks for the awesome project, it's much appreciated! I was wondering if there's a way to load snippets from a VScode workspace directory. Here's a screenshot of where the snippets are located:

![Screenshot 2023-03-29 at 3 36 45 PM](https://user-images.githubusercontent.com/63685366/228649567-9f08a604-3948-4766-8613-b181aad82698.png)

I saw that it's possible to add a path to custom snippets from my lua config, but I was hoping to not have to manage workspace specific snippets in there.

**Comment by leiserfg** [comment]
We are having a "[discussion](https://github.com/L3MON4D3/LuaSnip/pull/846#issuecomment-1489203626)" about it right now, check here and (as ex-vscode user) help us to define what you need there.

**Comment by changangus** [comment]
Hey @leiserfg, the need for me is to somehow load project specific .code-snippets files automatically. That way I can work across different repos without having to add all of those project specific snippets to my lua config. Let me know if there's anything else I can clear up, I did take a quick look at the comments in that PR and I think [this comment](https://github.com/L3MON4D3/LuaSnip/pull/846#issuecomment-1489307175) makes sense to me as a solution that would be able to accommodate my use case. Thanks again for all of y'alls hard work!

**Comment by hinell** [comment]
As a workaround you can pass absolute path to the `.code-snippets` to the `package.json` (which is specified by the `require("LuaSnip").load()` function. But be aware that LuaSnip may support a different mechanism to load these snippets in the future.

**Comment by evesdropper** [comment]
Adding on to this but not from a vscode perspective, is it possible to have something which loads a relative path (e.g. a `.luasnippets` directory for specific projects)?

**Comment by L3MON4D3** [comment]
Oh, that's possible already, call
```lua
require("luasnip.loaders.from_lua").load({paths = {vim.fn.getcwd() .. "/.luasnippets/"}})
```
(`getcwd` because `.` is interpreted as relative to config-directory)
