### ISSUE TITLE
[Feature] Is it possible to match text after cursor?

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#851]
First thanks for making this plugin, it works really fast and smooth and boosts
my speed in neovim, especially for latex files.

I want to make a snippet for quickly creating math environments. In latex there
there are inline maths and display maths:

Snippet for inline math is relatively simple:

```lua
s({ trig = '$$', snippetType = 'autosnippet' } , { t '$', i(0), t '$' })
```

In the snippet above, I can put my cursor in the middle of the dollars after
inserting two consecutive dollar signs.

However, for display math, things get tricky, what I want to achieve is:

1. I first type two consecutive dollar signs, the snippet for inline math is
   triggered:

   ```
   $|$
   ```

2. Then I press `$` again in between the two dollars, the snippet for display
   math is triggered:

   ```
   $$
        |
   $$
   ```

   This requires the snippet to be able to detect texts **after** the cursor
   and remove some of them after the snippet is expanded if needed.

   I looked at the documentation carefully, but I didn't find a way to do this.
   Is it possible to do this with the current version of the plugin?

Thanks in advance! :)

**Comment by L3MON4D3** [comment]
Whew, that's pretty specific, but also a cool idea :D

You could make use of [`external_update_dynamic_node`](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#dynamicnode-with-user-input), and initially insert the inline-math-snippet, and, on update, insert the display-math snippet.
You'd have to then somehow trigger update on `$` in INSERT, either via a binding (this is a bit unfortunate, since it requires either a global keybind (which inserts `$` if you're not inside the snippet) or you'd have to set/remove the keybind on enter/leave, which might end up a bit finnicky) or by including `TextChangedI` in your `update_events`, and just monitoring the inserted text for `$` (this would require #838, for finding the node whose text you want to query)

Not trivial, unfortunately :/

**Comment by Bekaboo** [comment]
Thanks for your suggestion, actually I have come up with an ugly but working solution during the time:

```lua
s({ trig = '$$', snippetType = 'autosnippet' } , {
  d(1, function()
    vim.opt.cmdheight = 4
    local line = api.nvim_get_current_line()
    local col = api.nvim_win_get_cursor(0)[2]
    if line:sub(col, col) == '$' then
      api.nvim_set_current_line(line:sub(1, col-1) .. line:sub(col+1))
      -- api.nvim_set_current_line('')
      vim.print('current line is ' .. vim.inspect(api.nvim_get_current_line()))
      return sn(nil, { t { '$$', '' }, i(1), t { '', '$$' } })
    else
      return sn(nil, { t '$', i(1), t '$' })
    end
  end),
})
```

I also want to report a but here that if I set the jump index of the snippet above to `0`, I get an error from LuaSnip saying:

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: ...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:24: attempt to get length of local 'position_so_far' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:24: in function 'init_insert_positions'
        ...hare/nvim/lazy/LuaSnip/lua/luasnip/nodes/dynamicNode.lua:175: in function 'update'
        ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:812: in function 'update'
        ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:503: in function 'trigger_expand'
        ...zeng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:243: in function 'snip_expand'
        ...zeng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:328: in function 'expand_auto'
        ...ng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/config.lua:264: in function <...ng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/config.lua:262>
```

the snippet that triggers the bug is (just change the jump index from `1` to `0`):

```lua
s({ trig = '$$', snippetType = 'autosnippet' } , {
  d(0, function()
    vim.opt.cmdheight = 4
    local line = api.nvim_get_current_line()
    local col = api.nvim_win_get_cursor(0)[2]
    if line:sub(col, col) == '$' then
      api.nvim_set_current_line(line:sub(1, col-1) .. line:sub(col+1))
      -- api.nvim_set_current_line('')
      vim.print('current line is ' .. vim.inspect(api.nvim_get_current_line()))
      return sn(nil, { t { '$$', '' }, i(0), t { '', '$$' } })
    else
      return sn(nil, { t '$', i(0), t '$' })
    end
  end),
})
```

Can you reproduce it?

**Comment by leiserfg** [comment]
For this specific case is not better to use a choice node alternating between and input and an input surrounded by two texts (with the `$` and the end of line)  ?

**Comment by Bekaboo** [comment]
@leiserfg That is a good idea too, thanks for your suggestion.

**Comment by leiserfg** [comment]
Something like this should work:

```lua
    s({ trig = "$$", snippetType = "autosnippet" }, {
      t "$",
      c(1, {
        i(1),
        sn(1, {
          t { "$", "" },
          i(1),
          t { "", "$" },
        }),
      }),
      t "$",
    }),
```

**Comment by Bekaboo** [comment]
@leiserfg Thanks for the snippet, but I think I prefer the way that does not use a choice node. If I use a choice node, for inserting a display math, I have press `$$<C-n>` instead of `$$$`, which feels more natural to me.

I problem here is that I cannot set the jump index of the dynamic node and the insert node inside it to `0`. Hopefully it can be fixed someday.

**Comment by L3MON4D3** [comment]
> For this specific case is not better to use a choice node alternating between an input and an input surrounded by two texts (with the `$` and the end of line) ?

Talk about not seeing the forest for the trees xD
This solution is much more elegant👍👍

**Comment by L3MON4D3** [comment]
> Thanks for your suggestion, actually I have come up with an ugly but working solution during the time:
> 
> ```lua
> s({ trig = '$$', snippetType = 'autosnippet' } , {
>   d(1, function()
>     local line = api.nvim_get_current_line()
>     local col = api.nvim_win_get_cursor(0)[2]
>     if line:sub(col, col) == '$' then
>       api.nvim_set_current_line(line:sub(1, col-1) .. line:sub(col+1))
>       return sn(nil, { t { '$$', '' }, i(1), t { '', '$$' } })
>     else
>       return sn(nil, { t '$', i(1), t '$' })
>     end
>   end),
> })
> ```
> 
> I also want to report a bug here that if I set the jump index of the snippet above to `0`, I get an error from LuaSnip saying:
> 
> ```
> Error detected while processing TextChangedI Autocommands for "*":
> Error executing lua callback: ...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:24: attempt to get length of local 'position_so_far' (a nil value)
> stack traceback:
>         ...local/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/util.lua:24: in function 'init_insert_positions'
>         ...hare/nvim/lazy/LuaSnip/lua/luasnip/nodes/dynamicNode.lua:175: in function 'update'
>         ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:812: in function 'update'
>         ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:503: in function 'trigger_expand'
>         ...zeng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:243: in function 'snip_expand'
>         ...zeng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:328: in function 'expand_auto'
>         ...ng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/config.lua:264: in function <...ng/.local/share/nvim/lazy/LuaSnip/lua/luasnip/config.lua:262>
> ```
> 
> the snippet that triggers the bug is (just change the jump index from `1` to `0`):
> 
> ```lua
> s({ trig = '$$', snippetType = 'autosnippet' } , {
>   d(0, function()
>     local line = api.nvim_get_current_line()
>     local col = api.nvim_win_get_cursor(0)[2]
>     if line:sub(col, col) == '$' then
>       api.nvim_set_current_line(line:sub(1, col-1) .. line:sub(col+1))
>       return sn(nil, { t { '$$', '' }, i(0), t { '', '$$' } })
>     else
>       return sn(nil, { t '$', i(0), t '$' })
>     end
>   end),
> })
> ```
> 
> Can you reproduce it?
> 
> EDIT: remove unrelated lines. EDIT: typo

Ah yeah the 0-jump-index can only be occupied by an insertNode, you'll have to live with that limitation, unfortunately :/

**Comment by Bekaboo** [comment]
@L3MON4D3 Oh I forget that only insert nodes can have jump index `0`, please forgive my ignorance!

For future readers that come across this issue, an ugly (but working) solution is:

```lua
    s({
      trig = '$',
      condition = function()
        local line = api.nvim_get_current_line()
        local col = api.nvim_win_get_cursor(0)[2]
        return line:sub(col + 1, col + 1) == '$'
      end,
    }, { t({ '$', '' }), ifn(1), i(0), t({ '', '$' }) })
    s(
      { trig = '$$', priority = 999 },
      { t('$'), i(0), t('$') }
    )
```

the snippet above will not put a final jump destination after expanding the snippet, which is exactly what I want.
