### ISSUE TITLE
Install failed with lazy nvim

### ISSUE THREAD

**Issue by devstefancho** [L3MON4D3/LuaSnip#853]
Hello!
I want some help for installing this plugin
everytime I install LuaSnip, It shows failed message
actually it is installed, but because of this, my lazy-lock file is everytime changed to latest commit
this is a little bit tiresome
Is there any way to fix it?

![image](https://user-images.githubusercontent.com/61320923/228702886-e9daf5b0-f6dc-4706-95bd-b0b767fddaf8.png)

## OS
MacOS

## Neovim version (nvim -v)
0.8.2

## LuaSnip commit
https://github.com/L3MON4D3/LuaSnip/commit/025886915e7a1442019f467e0ae2847a7cf6bf1a

## Terminal name/version
Alacritty/0.11.0

alextrastero reacted with thumbs up emoji

## My config
```
return {
  {
    "L3MON4D3/LuaSnip",
    -- follow latest release.
    version = "<CurrentMajor>.*",
    -- install jsregexp (optional!).
    build = "make install_jsregexp",
  }
}
```

**everytime it changes commit version (this is the problem)**

![image](https://user-images.githubusercontent.com/61320923/228703101-383b8e6d-2f95-438c-8fe3-886dbbdd4cb6.png)

**Comment by L3MON4D3** [comment]
You're meant to replace `<CurrentMajor>` with the current major version of Luasnip 😅😅
Not the first time this has come up, I think I'll just change that manually once we do a release

**Comment by devstefancho** [comment]
@L3MON4D3 Thanks!
I didn't realize `<CurrentMajor>` is just placeholder
I change it to major version, and now no error 
```lua
  {
    "L3MON4D3/LuaSnip",
    -- follow latest release.
    version = "1.*",
    -- install jsregexp (optional!).
    build = "make install_jsregexp",
  },
```

<img width="1752" alt="image" src="https://user-images.githubusercontent.com/61320923/229148599-0c282361-ee88-444e-a45a-caa626d49fa7.png">
