### ISSUE TITLE
Suggestion: Visually emphasize the availability of a choice

### ISSUE THREAD

**Issue by chrisgrieser** [L3MON4D3/LuaSnip#855]
Is is possible to somehow visually emphasize if there is a choice available? I often tend to forget that I have set up a choice and end up typing the whole thing.

I know that there is `require("luasnip").choice_active()` which in principle can be used to create a status bar item, I do not pay much attention to the status bar when typing in insert mode and tend to overlook it. Maybe something closer the active line, like a signcolumn icon or a virtual text indicator?

**Comment by evesdropper** [comment]
Maybe [this](https://github.com/L3MON4D3/LuaSnip/wiki/Nice-Configs#hint-node-type-with-virtual-text) will help?

**Comment by chrisgrieser** [comment]
oh my, indeed, that is exactly what I was looking for. I went through the docs twice, but seem to have overlooked this. Thanks you!
