### ISSUE TITLE
extend_load_ft stops working for unknown reason(s).

### ISSUE THREAD

**Issue by no-vici** [L3MON4D3/LuaSnip#856]
I have all my snippets stored in separate files under `~/.config/nvim/luasnippets`, and the following settings worked for me:
```
ls.setup({
	load_ft_func = require("luasnip.extras.filetype_functions").extend_load_ft({
		markdown = { "lua", "json" , "sil"},
		html = { "javascript" },
		sil = { "lua", "markdown" },
	}),
})
```
I load them with `require("luasnip.loaders.from_lua").lazy_load()
`.
Now, for some reasons, the above settings don't work any more.

Any ideas, LuaSnip experts?

**Comment by L3MON4D3** [comment]
Could you set the log level to `"info"` (`:h luasnip-logging`) and check/post the log for a session? It should have some hints as to what is/might be going wrong

**Comment by no-vici** [comment]
> h luasnip-logging

Thank you for your quick response as always.
I open the `luansip.log` with `ls.log.open()` and did not find anything useful, then I cleared the log file, shift "info" to the highest priority in `ls.log.set_loglevel("error"|"warn"|"debug"|"info")`, opened the log file again and saw nothing.

Probably, I was so dump :D), went back to the decentralised method ` require("luasnip").filetype_extend("sil", { "lua", "markdown" })` in my snippet file.

It seems to me that the author of LuaSnip has foreseen every practical scenario and everything was well documented.

**Comment by L3MON4D3** [comment]
> opened the log file again and saw nothing.

Oh that's a bit suspicious, there should be lots of output.. Are you setting the loglevel before calling lazy-load?

> It seems to me that the author of LuaSnip has foreseen every practical scenario and everything was well documented.

Haha, thank you :D

**Comment by no-vici** [comment]
> Oh that's a bit suspicious, there should be lots of output.. Are you setting the loglevel before calling lazy-load?

Ah, I didn't do that, so now it looks like this:

```
INFO  | lua-loader: Registering lazy-load-snippets:
      | {
      |   context = { "~/.config/nvim/luasnippets/context.lua" },
      |   lua = { "~/.config/nvim/luasnippets/lua.lua" },
      |   markdown = { "~/.config/nvim/luasnippets/markdown.lua" },
      |   python = { "~/.config/nvim/luasnippets/python.lua" },
      |   sh = { "~/.config/nvim/luasnippets/sh.lua" },
      |   sil = { "~/.config/nvim/luasnippets/sil.lua" }
      | }
INFO  | lua-loader: Loading lazy-load-snippets for filetype ``
INFO  | lua-loader: Loading lazy-load-snippets for filetype `lua`
INFO  | lua-loader: Adding 30 snippets and 0 autosnippets from ~/.config/nvim/luasnippets/lua.lua to ft `lua`
INFO  | snipmate-loader: Loading lazy-load-snippets for filetype `lua`
INFO  | vscode-loader: Loading lazy-load-snippets for filetype `lua`
INFO  | lua-loader: Loading lazy-load-snippets for filetype `WhichKey`
INFO  | snipmate-loader: Loading lazy-load-snippets for filetype `WhichKey`
INFO  | vscode-loader: Loading lazy-load-snippets for filetype `WhichKey`
INFO  | snipmate-loader: Loading lazy-load-snippets for filetype ``
INFO  | vscode-loader: Loading lazy-load-snippets for filetype ``
INFO  | lua-loader: Loading lazy-load-snippets for filetype `mru`
INFO  | snipmate-loader: Loading lazy-load-snippets for filetype `mru`
INFO  | vscode-loader: Loading lazy-load-snippets for filetype `mru`

```

Honestly, I don't know how to interpret the above log.

**Comment by L3MON4D3** [comment]
Nice :+1:
The first `info` is the `lazy_load`-call (for verifying that we actually found all the snippet files that should be loaded).
After that there just comes a lot of information on which filetypes are being lazy-loaded, and how many snippets each contributed.

If you re-add `extend_load_ft` to your config, and edit a markdown-file, you should (according to our specification at least :D) see the message for loading markdown-snippets, but also those for lua, json and sil.

**Comment by no-vici** [comment]
> Nice +1 The first `info` is the `lazy_load`-call (for verifying that we actually found all the snippet files that should be loaded). After that there just comes a lot of information on which filetypes are being lazy-loaded, and how many snippets each contributed.

That simply explains everything. Wow, lazy-load sorts the snippet filenames in order and counts the number of snippets loaded from each ft. 

> If you re-add `extend_load_ft` to your config, and edit a markdown-file, you should (according to our specification at least :D) see the message for loading markdown-snippets, but also those for lua, json and sil.

Yes, now I see the other intended snippet ft's loaded, nice!

You know that I've thanked you countess of times but still not enough, so thank you once more.

**Comment by L3MON4D3** [comment]
Glad it works, I'm happy I could help :)

**Comment by weilbith** [comment]
Hey 👋🏾 
I have the same issue. Looking at the log as suggested above (looks slightly different), I can see that it loads the associated filetypes. But they do not work. So for example I use the `extend_load_ft` with `vue = { 'typescript', 'javascript' }`. And I indeed can say when I add this that all three languages are loaded. But the snippets are not available. I have the same issue with other filetype associations. 🤷🏾

**Comment by timoleistner** [comment]
I have the same problem, having 
```Lua
    load_ft_func = require("luasnip.extras.filetype_functions").extend_load_ft({
        markdown = { "html" },
    })
```
in my config the html snippets are not available in markdown.

If I run `:lua require("luasnip").filetype_extend("markdown", {"html"})`, the snippets are available.

The log also doesnt show that it loaded html snippets for markdown files.

```
INFO  | lua-loader: Loading snippet-collection:
      | {
      |   all = { "~/.config/nvim/lua/snippets/all.lua" },
      |   html = { "~/.config/nvim/lua/snippets/html.lua" },
      |   lua = { "~/.config/nvim/lua/snippets/lua.lua" },
      |   markdown = { "~/.config/nvim/lua/snippets/markdown.lua" },
      |   rust = { "~/.config/nvim/lua/snippets/rust.lua" },
      |   tex = { "~/.config/nvim/lua/snippets/tex.lua" },
      |   zsh = { "~/.config/nvim/lua/snippets/zsh.lua" }
      | }
```
