### ISSUE TITLE
VS Code-style snippets with duplicate placeholders not processed correctly

### ISSUE THREAD

**Issue by mvolkmann** [L3MON4D3/LuaSnip#857]
Consider this VS Code-style snippet:

```ja
console.log('$TM_FILENAME $1: $2 =', $2);
```

When a value is entered for the first `$2` it should be repeated for the other one.
This works in VS Code, but not in LuaSnip.

**Comment by L3MON4D3** [comment]
What's your `update_events` set to? By default, the placeholder-copies are only updated once the source-placeholder is left/jumped from. By setting `update_events` to `"TextChangedI"`, or some other event, this can be done more often

**Comment by mvolkmann** [comment]
Thank you so much! That fixed it!
