### ISSUE TITLE
Can't remove LuaSnip due to .git directory existing

### ISSUE THREAD

**Issue by tylerheaton16** [L3MON4D3/LuaSnip#858]
I recently updated LuaSnip and have an issue that I can't resolve. I'm not sure if it is on the side of LuaSnip, but it seems during the update LuaSnip lost its git history. 

when I run :PackerSync and remove LuaSnip, it can't because it is not able to delete ``.local/share/nvim/site/pack/packer/opt/LuaSnip`` which only has a `.git` directory. There are no .nfs files or rogue files I can find. Also, when I run ``git status`` I now get ``fatal: not a git repository (or any of the parent directories): .git`` 

Is there a way to reverse this to get LuaSnip back up and running?

**Comment by leiserfg** [comment]
Sorry but the issue has nothing to do with luasnip, just delete the folder by hand.

**Comment by tylerheaton16** [comment]
I think this issue has to do with me being on an NFS. I can't delete the folder because it claims there are files inside of it still, but it is empty. `lsof` and `fuser` don't help, so it is currently stale. I'll keep looking at it, thanks.

**Comment by pierce-c** [comment]
if u go to the directory on the command line u can use `ls -la` to list the hidden files

**Comment by tylerheaton16** [comment]
Hey all. So I went through all of the normal means (including ls -la, lsof, fuser, etc). And it looks like it has to do with settings on the server I am on. 

sudo rm -Rf didn't have an affect. But, opening the GUI and just "send to trash" did the trick apparently. 

Closing.
