### ISSUE TITLE
Snippet not autoexpanding when trigger ends in '>'

### ISSUE THREAD

**Issue by ribru17** [L3MON4D3/LuaSnip#865]
Plugin works perfectly except for when the trigger ends in a `>` character. I have tried with multiple triggers and tried to fix this with `regTrig = true` but nothing seems to work. Is this is a special character? Any help is appreciated.
PS. 
```lua
return {}, {
 s({ trig = '>=', wordTrig = false, }, fmt([[\ge]], {}), {}) -- works!
 s({ trig = '=>', wordTrig = false, }, fmt([[\implies]], {}), {}) -- doesn't work
}
```
My config:
```lua
local ls = require('luasnip')
ls.config.set_config {
  enable_autosnippets = true,
}
```

**Comment by L3MON4D3** [comment]
Huh, that should work.. My guess would've been that wordTrig is set, but you've explicitly disabled that.
Could you try again? Maybe the snippet didn't re-load, there's an issue with that at the moment

**Comment by iurimateus** [comment]
fwiw, I have no problems with

 `ls.parser.parse_snippet({ trig = "=>", name = "implies" }, "\\implies")`

with `wordTrig` set to false

ref https://github.com/iurimateus/luasnip-latex-snippets.nvim/blob/main/lua/luasnip-latex-snippets/math_iA.lua#L126

**Comment by ribru17** [comment]
Thank you both for your help. I've realized it was caused by my autotag plugin https://github.com/windwp/nvim-ts-autotag. Removing it allowed everything to work properly so I think I will open an issue there instead. Thanks!
