### ISSUE TITLE
wildcard expansion did not found any tag for plugin

### ISSUE THREAD

**Issue by xclidongbo** [L3MON4D3/LuaSnip#867]
wildcard expansion did not found any tag for plugin

**Comment by L3MON4D3** [comment]
Did you replace `<CurrentMajor>` with the current major version number of Luasnip, ie `1`?

**Comment by xclidongbo** [comment]
`	use({ "L3MON4D3/LuaSnip", tag = "v<CurrentMajor>.*", run = "make install_jsregexp" }) `
change to
`	use({ "L3MON4D3/LuaSnip", tag = "v1.*", run = "make install_jsregexp" }) `
？

**Comment by L3MON4D3** [comment]
Yup👍
