### ISSUE TITLE
FunctionNode example in DOC.md occurs error (E5108: Error executing lua)

### ISSUE THREAD

**Issue by hrcHarry** [L3MON4D3/LuaSnip#873]
Hi, I'm a Windows user and my neovim version information is shown as follows:
&emsp;     NVIM v0.8.3
&emsp;     Build type: RelWithDebInfo
&emsp;     LuaJIT 2.1.0-beta3

The config path (`:echo stdpath("config")`) is  `~\AppData\Local\nvim`

This is my setup of Luasnip: (ignoring the stuffs unrelated to Luasnip)
- The _tree_ of the config directory: 
 `~\AppData\Local\nvim\lua`
├- packer_install
│&emsp;└- init.lua
├- plugins_config
│&emsp;└- luasnip
│&emsp;&emsp;&emsp;├- languages
│&emsp;&emsp;&emsp;│&emsp;&emsp;└- tex
│&emsp;&emsp;&emsp;│&emsp;&emsp;&emsp;&ensp;└- env.lua
│&emsp;&emsp;&emsp;└- init.lua
└- init.lua

- In  `~\AppData\Local\nvim\lua\init.lua`:
<pre><code>...
require('packer_install')
...
require('plugins_config.luasnip')
...</code></pre>

- In `~\AppData\Local\nvim\lua\plugins_config\luasnip\init.lua`
<pre><code>require("luasnip").config.set_config({ -- Setting LuaSnip config
  -- Enable autotriggered snippets
  enable_autosnippets = true,
  -- Use Tab (or some other key if you prefer) to trigger visual selection
  store_selection_keys = "<Tab>",
})

-- Lazy-load snippets, i.e. only load when required, e.g. for a given filetype
require("luasnip.loaders.from_lua").lazy_load({paths = "~/AppData/Local/nvim/lua/plugins_config/luasnip/languages"})

-- *** Refresh tex.lua without restart the .tex file ***
vim.keymap.set('n', '<Leader>L', '<Cmd>lua require("luasnip.loaders.from_lua").load({paths = "~/AppData/Local/nvim/lua/plugins_config/luasnip/languages/"})<CR>', {desc = 'Refresh LaTeX LuaSnip snippet'})
</code></pre>

- In `~\AppData\Local\nvim\lua\plugins_config\luasnip\languages\tex\env.lua`

<pre><code>return {
  s({trig="itmd", dscr="\\item", snippetType="autosnippet"},
    fmta(  -- fmta uses <> angle brackets as the default node placeholder
       [[\item <>]],
       { i(1) }
    )
  ),  -- (1) the snippet I set

  s({trig = "b(%d)", regTrig = true},
      f(function(args, snip) return
          "Captured Text: " .. snip.captures[1] .. "." end, {}
       )
  )  -- (2) the example in https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#FunctionNode
}</code></pre>

## The Problem ##
- For editing `.tex` files, the snippet (1) work fine but (2) doesn't work.
  When refreshing by `<Leader>L`, it occurs an error
<img src="https://upload.cc/i1/2023/04/24/uCMQZP.png" />

- If I delete/comment out (2) in `env.lua`, refreshing works fine and no error occurs.

---

Does any one know how to fix it? Thanks.

**Comment by L3MON4D3** [comment]
Mhmm, the error only occurring on refresh is very strange..
Could you update luasnip? I just pushed a fix for error-reporting for loading a file via lua, that should help with finding the origin of this bug

**Comment by L3MON4D3** [comment]
Sidenote: when a snippet-file is edited, its snippets will be updated automatically, you don't have to manually reload if you're editing in the instance you're using the snippet in

**Comment by hrcHarry** [comment]
Hi, after updating Luasnip, I got the same result: no error occurs while opening a `.tex` file, the example snippet doesn't trigger, and the error (E5108) occurs while refreshing.

![ ](https://upload.cc/i1/2023/04/24/f8xbEA.png)

**Comment by hrcHarry** [comment]
In addition, for the sidenote you mention, when I edit a snippet file (for `.tex`-file snippets), save it (`:w`), and go back to the `.tex` file/buffer currently opened, the new/modified snippet doesn't trigger. I have to use `<Leader>L` to refresh and then the new/modified snippet works.

My very first-time Luasnip setup follows [ejmastnak](https://www.ejmastnak.com/tutorials/vim-latex/luasnip/), and it provides the [refreshing way](https://www.ejmastnak.com/tutorials/vim-latex/luasnip/#refreshing-snippets-from-a-separate-vim-instance). I'm not sure if that is related to my problem.

**Comment by L3MON4D3** [comment]
> In addition, for the sidenote you mention, when I edit a snippet file (for `.tex`-file snippets), save it (`:w`), and go back to the `.tex` file/buffer currently opened, the new/modified snippet doesn't trigger. I have to use `<Leader>L` to refresh and then the new/modified snippet works.
> 
> My very first-time Luasnip setup follows [ejmastnak](https://www.ejmastnak.com/tutorials/vim-latex/luasnip/), and it provides the [refreshing way](https://www.ejmastnak.com/tutorials/vim-latex/luasnip/#refreshing-snippets-from-a-separate-vim-instance). I'm not sure if that is related to my problem.

The snippets should be updated, after saving, in the neovim-instance in which you edited the file, is that not the case for you?

**Comment by hrcHarry** [comment]
> Could you show the error-message? It should be more detailed now

No problem. 
For clarity's sake, I show the screenshots at each step. 
Of course that I've update Luasnip to the newest version.

1. The example snippet setting has already been set in `env.lua`. No error occurs while open `test.tex`.
![ ](https://upload.cc/i1/2023/04/24/ztYKqJ.png)

2. Refresh
![ ](https://upload.cc/i1/2023/04/24/OkPoes.png)

3. Error (E5108) occurs. It says `'}'` is expected at line 86 to close `'{'` at line 26
![ ](https://upload.cc/i1/2023/04/24/1uRbny.png)
(`'{'` at line 26)
![ ](https://upload.cc/i1/2023/04/24/CxQc7Y.png)
In fact, the closing `'}'` resides at line 200 which can be checked by <S-%> on `'{'` at line 26.
![ ](https://upload.cc/i1/2023/04/24/pjgUth.png)

4. Even though the error occurs after refreshing, the snippets still work (e.g. the snippets defined at line 86 and 97) except _the example snippet_.
![ ](https://upload.cc/i1/2023/04/24/ki1hF9.png)

**Comment by hrcHarry** [comment]
> The snippets should be updated, after saving, in the neovim-instance in which you edited the file, is that not the case for you?

Not sure if I do it wrong. The case I met is as follows:

1. Define a new snippet in, for example, `env.lua` and save it (`:w`).
![](https://upload.cc/i1/2023/04/24/YZGyqD.png)
![](https://upload.cc/i1/2023/04/24/6c0PFd.png)
2. Go back to `test.tex` and type in the trigger `hi`, no snippet info pops out.
![](https://upload.cc/i1/2023/04/24/zHhUR6.png)
3. So I refresh it.
![](https://upload.cc/i1/2023/04/24/PTpWeI.png)
4. Then trying to trigger it again, it shows the snippet info
![](https://upload.cc/i1/2023/04/24/zKIiU6.png)

**Comment by L3MON4D3** [comment]
> > Could you show the error-message? It should be more detailed now
> 
> No problem. For clarity's sake, I show the screenshots at each step. Of course that I've update Luasnip to the newest version.
> 
> 1. The example snippet setting has already been set in `env.lua`. No error occurs while open `test.tex`.
>    ![ ](https://camo.githubusercontent.com/c2bb1473812c43f7772fd19f466a080f7947300fcaa53900b77edc07d16de08c/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f7a74594b714a2e706e67)
> 2. Refresh
>    ![ ](https://camo.githubusercontent.com/59a9525acb1803f00a747d9faaac3c6c54047551e005c936efbd25ddb1d0e05d/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f4f6b506f65732e706e67)
> 3. Error (E5108) occurs. It says `'}'` is expected at line 86 to close `'{'` at line 26
>    ![ ](https://camo.githubusercontent.com/c9b2c5bd7d4c05a7b4ffd68b281fc9435872da7aa3fbc12ce2b882531932d420/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f317552626e792e706e67)
>    (`'{'` at line 26)
>    ![ ](https://camo.githubusercontent.com/9554cb9f0dd5179e9eb07d5a749e0e27a746fa21a0b646ed7908d568d3a327b7/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f4378516337592e706e67)
>    In fact, the closing `'}'` resides at line 200 which can be checked by <S-%> on `'{'` at line 26.
>    ![ ](https://camo.githubusercontent.com/1a4fbe56cd17b9ec628469cf4258a412b1082a44079c1a5f9e95f67e3a53cdd2/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f706a675574682e706e67)
> 4. Even though the error occurs after refreshing, the snippets still work (e.g. the snippets defined at line 86 and 97) except _the example snippet_.
>    ![ ](https://camo.githubusercontent.com/3135f3a2e3ef8deb67ca3a2de5f62fa0f4cfdbb19104337775f40fd15e27d859/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f6b69316846392e706e67)

I think there's just a comma missing🤦🤦
And the error-message from the non-reload maybe doesn't show because the file is executed in an autocommand (thats because of lazy_load), it's possible the error is just ignored somewhere

**Comment by L3MON4D3** [comment]
> > The snippets should be updated, after saving, in the neovim-instance in which you edited the file, is that not the case for you?
> 
> Not sure if I do it wrong. The case I met is as follows:
> 
> 1. Define a new snippet in, for example, `env.lua` and save it (`:w`).
>    ![](https://camo.githubusercontent.com/07e6a283ee804fb5504f5687cfb19c389aefca795f4b2c0515b7fecd425d02f6/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f595a477971442e706e67)
>    ![](https://camo.githubusercontent.com/ddada69cb3de78cbfe5e1217ac76778bdc4b68d3319c213563bbf8d129146833/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f3663305046642e706e67)
> 2. Go back to `test.tex` and type in the trigger `hi`, no snippet info pops out.
>    ![](https://camo.githubusercontent.com/a1ab437ef898b3b12363643f88e8b80ffc0ff133e1b2c9160439cdd73f3c4e6d/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f7a48685552362e706e67)
> 3. So I refresh it.
>    ![](https://camo.githubusercontent.com/1085decb4b4b10035677ff813695c278a2cb18e9314bab933a105124d23f59fa/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f5054705765492e706e67)
> 4. Then trying to trigger it again, it shows the snippet info
>    ![](https://camo.githubusercontent.com/330210288daa02160db2c3e45523d7a053b26289e27c7639180300d9f8f65b6e/68747470733a2f2f75706c6f61642e63632f69312f323032332f30342f32342f7a4b496955362e706e67)

Hmmm maybe cmp_luasnip just doesn't update when a reload happens (might be our fault😅), could you try actually triggering the snippet, and ignore the contents of the list cmp shows?

**Comment by hrcHarry** [comment]
> I think there's just a comma missing🤦🤦
And the error-message from the non-reload maybe doesn't show because the file is executed in an autocommand (thats because of lazy_load), it's possible the error is just ignored somewhere

After deleting all the comments in `env.lua`, the example snippet works somehow.😓
![](https://upload.cc/i1/2023/04/25/x7bLlQ.png)

So the problems now are
(If this should be treated as a new issue, please let me know and I will make a new issue for it)

1. > Sidenote: when a snippet-file is edited, its snippets will be updated automatically, you don't have to manually reload if you're editing in the instance you're using the snippet in

  This is still not working for me. 
  For example, if I add a new snippet ( `s(...)` ) in `env.lua` and save it, the `.tex` file still not catching the new snippet definition; I have to do reloading (`<Leader>L`) so that the `.tex` file can catch that new snippet.

2. I would like to use the _capture_ feature such as this `b(%d)` snippet to grab a number from that `(%d)`.
My idea is as follows:
<pre><code>s({trig="env(%d)itmd", dscr="\\begin{itemize} \\item \\end{itemize}", regTrig = true, snippetType="autosnippet"},
    fmta(  -- fmta uses <> angle brackets as the default node placeholder
       [[
         \begin{itemize}
         <>
         \end{itemize}
       ]],
       { f(function(args, snip)
             local items = ""
             local num = tonumber(snip.captures[1])             
             for i = 1, num do
                items = items .. "\\item \n"
             end

             return items
           end, { }),
       }
    )
  )</code></pre>
That is, the number from `(%d)` determines the number of `\item`.  For example, `env3itmd` is expected to be expanded as
<pre>
\begin{itemized}
\item
\item
\item
\end{itemize}
</pre>

But it gives me the error
![](https://upload.cc/i1/2023/04/25/8h4zbk.png)
  
Is there anything wrong with the code above?

**Comment by hrcHarry** [comment]
1. `:echo stdpath('log')` tells me that the directory and I found the file `luasnip.log` in there. 
![](https://upload.cc/i1/2023/04/25/hk7HNW.png)
> Regarding 1, could you turn up the log level to info (:h luasnip-logging) and post the log?

&emsp;&emsp;a. I'm not sure how to turn up the log level (do `:ls.set_loglevel("debug")` in neovim or something? 😓)
&emsp;&emsp;b. After setting the level, how to get the new log?

2. Thank you very much! This problem is fixed. 
    By the way, I should have read DOC.md carefully: "`fn` shall return a string, which will be inserted as is, or ***<font color="Blue">a table of strings for multiline strings</font>***". Thanks for your patience 😅.

**Comment by L3MON4D3** [comment]
Nice, glad that works👍 :D

For 1, could you
1. Enter neovim
2. Open a buffer with a tex-file
3. Edit the tex snippet-file and write it

And show the logmessages of those events?

**Comment by L3MON4D3** [comment]
Nice, glad that works👍 :D

For 1, could you
1. Enter neovim
2. Open a buffer with a tex-file
3. Edit the tex snippet-file and write it

And show the logmessages of those events?

**Comment by hrcHarry** [comment]
(I have upgraded log level to "debug" by executing, in neovim, `:lua require("luasnip").log.set_loglevel("debug")` and open the log file by `:lua require("luasnip").log.open()` . If these steps are wrong, please let me know. 😓)

Hi, I have two results.

1. Open two terminals (in Windows, that is **PowerShell**): one for tex snippet-file (say, in terminal ***A***) and the other for tex-file (say, in terminal ***B***). That is, one buffer for one terminal.
a. No matter how tex snippet-file in ***A*** is edited and written, the modified snippet triggers aren't applied on the tex-file in ***B*** 
   &emsp;The log is as follows (I execute `:lua require("luasnip").log.ping()` to check if the logging works)
   ![](https://upload.cc/i1/2023/04/26/dGbow3.png)
   ![](https://upload.cc/i1/2023/04/26/tafqmr.png)
   &emsp;After I do refreshing `<Leader>L`, the modified snippet works. The content of log which is after refreshing is the same as the one above.

2. Open only one terminal and open two buffer in neovim: tex snippet-file and tex-file.
   As you said, if the tex snippet-file buffer is edited and written, then the tex-file buffer (in the same terminal) can trigger the modified snippet without refreshing.
   ![](https://upload.cc/i1/2023/04/26/vJ9uGo.png)

   &emsp;The log, in this case, is the same.
   ![](https://upload.cc/i1/2023/04/26/BwdYLx.png)
   
---
### I am just wondering if it is possible to make case 1 working like case 2? 🤔

**Comment by L3MON4D3** [comment]
Ohhh okay xD
Mhmmm that would be possible, neovim does contain liibuv, which has a generic file-watcher (`:h uv.fs_event_start`)... it would be pretty nice to have

Would you open a new issue for this? It's not discoverable buried down here :sweat_smile:

**Comment by hrcHarry** [comment]
> Mhmmm that would be possible, neovim does contain liibuv, which has a generic (usable on windows and linux, afaict) file-watcher (:h uv.fs_event_start)...

Sure, I will make a new issue for this. 

And I think this (#873) issue can be closed.

**Comment by L3MON4D3** [comment]
Yeah, of course :)
