### ISSUE TITLE
Adding same snippet after reloading config file

### ISSUE THREAD

**Issue by ExtremOPS** [L3MON4D3/LuaSnip#875]
Hi there,

first of all a big thank you for creating this plugin. I have the following problem, that every time I reload my `luasnip.lua` with entries like:

```lua
require("luasnip").add_snippets(nil, {
    cpp = {
        snip({
          trig = "forit",
          namr = "forit",
          dscr = "for loop with custom iterator",
        }, {
            text("for("), insert(1, "IteratorClass"),
            text(" it="), insert(2, "IteratorBegin"), text(".begin();it<"),
            func(fn,{2}),text(".end();it++)"),
            text({" {", ""}),
            text("\t"),
            insert(0),
            text({ "", "}"})
        }),
    },
}
```

this snippet gets added to the completion list instead of being replaced. Is there a way to override instead?

**Comment by L3MON4D3** [comment]
Yes!
Check the documentation for `add_snippets`, you can provide a (unique) key, and snippets added by a previous `add_snippets` will be removed when new ones with the same key are added

**Comment by ExtremOPS** [comment]
Thank you @L3MON4D3 and sorry for the obvious question then!

**Comment by L3MON4D3** [comment]
Oh don't worry, I don't think there's an issue on this yet, so this usecase is now mentioned here as well :D
