### ISSUE TITLE
regTrig = true and wordTrig = false together with [%w+] result in deleting the character placed in front of the snippet

### ISSUE THREAD

**Issue by hrcHarry** [L3MON4D3/LuaSnip#877]
Hi, 

In the same tex-snippet file, 
<pre><code>return {
  s({trig="[%w+]__", dscr="_{}", regTrig = true, wordTrig= false, snippetType="autosnippet"},
    fmta(
       [[ _{<>} ]],
       { i(1) }
    )
  ),
}</code></pre>

For example, `a__` results in `_{}` which deletes `a` while `a_{}` is expected.

For now, the snippet is modified to be 
<pre><code>  s({trig="[_][_]", dscr="_{}", regTrig = true, wordTrig= false, snippetType="autosnippet"},  -- trig="[%_][%_]" also works
    fmta(
       [[ _{<>} ]],
       { i(1) }
    )
  ),</code></pre>
which will work as I expect.

Is there any point I got misunderstanding?

**Comment by atticus-sullivan** [comment]
This is a thing with regTrig and normal trig in general. See
>    - `wordTrig`: boolean, if true, the snippet is only expanded if the word
        (`[%w_]+`) before the cursor matches the trigger entirely.
        **True by default**.

So with using
```lua
s({trig="__", dscr="_{}", snippetType="autosnippet", wordTrig=false}, fmt(   -- snippet (1)
	[[ _{<first>} ]],
	{
		first = i(1)
	}))
```
it works for me.

**Comment by hrcHarry** [comment]
Awesome! Thanks for your recommendation and that works perfectly!

Besides, I am curious about that why it deletes the character placed in front of the Lua regex pattern. For example, my first trial snippet
<pre><code>return {
  s({trig="[%w+]__", dscr="_{}", regTrig = true, wordTrig= false, snippetType="autosnippet"},
    fmta(
       [[ _{<>} ]],
       { i(1) }
    )
  ),
}</code></pre>
will occurs that result. 

Do I miss or misunderstand something about Luasnip or Lua regex?

**Comment by L3MON4D3** [comment]
Oh, it's probably just the `[%w]` matching the character before the trigger proper

**Comment by hrcHarry** [comment]
> Oh, it's probably just the `[%w]` matching the character before the trigger proper

Ohhh... I think I know what's wrong with that. 😅

Thank you very much!
