### ISSUE TITLE
Have any plans to support coc.nvim?

### ISSUE THREAD

**Issue by uga-rosa** [L3MON4D3/LuaSnip#88]
Coc-snippets is good enough to use LSP snippets, but it has a fatal flaw that it cannot detect press holder changes.
Is it possible to make user-defined snippets of LuaSnip work with Coc.nvim completion?

**Comment by L3MON4D3** [comment]
Tbh no, hadn't thought about that yet. Could be trivial if they have some setting where users can provide their own functions for lsp-snippet expansion.
If no, do you have ideas on where to look for snippet expansion in coc?

**Comment by uga-rosa** [comment]
Here's a quote from F.A.Q
>Q: Some ultisnips snippet not works as expected.
>
>A: Reformat after change of placeholder feature can't be supported for now, andsome regex pattern can't be converted to javascript regex pattern, so the snippet can be failed to load.

I don't think it is necessary to support LSP snippets. It is enough to be able to pass user-defined snippets to coc as a completion source.

I'm sorry if my English was not good enough to understand your intentions.

**Comment by L3MON4D3** [comment]
Ahh, so you'd like to have Luasnips' snippets show up in (and expand from) cocs' completion menu?

**Comment by uga-rosa** [comment]
Yes! Sorry for the confusion.

**Comment by L3MON4D3** [comment]
Np, I also misunderstood your first message😅
I'll focus on built-in lsp and improving Luasnip in general right now, but I'll keep coc in mind and come back to your suggestion at a later date.

**Comment by dseeni** [comment]
How does one achieve this?

**Comment by L3MON4D3** [comment]
Basically do what `cmp_luasnip` does (`complete` and `execute`-functions [here](https://github.com/saadparwaiz1/cmp_luasnip/blob/6e3471da71568e75b87b305240fc47b22df6b0da/lua/cmp_luasnip/init.lua#L63-L154)), but for `coc.nvim`.
I don't know at all how their sources work though :/

**Comment by dseeni** [comment]
Hmmm....
Might be above my paygrade haha. I surrendered for now and switched to coc-snippets since my main issue was input lag with ultisnips.

For coc and ultisnips, I installed "Coc-Ultisnips" and that automatically adds snippets as a completion source, perhaps it could be just as easy to do with LuaSnips:
https://github.com/neoclide/coc-sources/blob/master/packages/ultisnips/index.js

**Comment by L3MON4D3** [comment]
Oh right, coc uses javascript... lua can be called through the api though, maybe one could even repurpose parts of `cmp_luasnip` (is there a general cmp-to-coc-source converter? Does not look impossible to implement)

**Comment by uga-rosa** [comment]
I tried to create coc-luasnip.
![image](https://user-images.githubusercontent.com/82267684/174616958-643c3a70-3051-480a-be33-abf15a2a58c1.png)

**Comment by L3MON4D3** [comment]
Oh sick! 🎉🎉

I guess there's some shared functionality with `cmp_luasnip`, do you think it would make sense to include some of it in luasnip?

**Comment by uga-rosa** [comment]
Yes, the lua portion is much covered since it looks like this.

<details>
<summary>code</summary>

```lua
local util = require("vim.lsp.util")

local M = {}

local snip_cache = {}
local doc_cache = {}

local function get_documentation(snip, ft)
	if doc_cache[ft] and doc_cache[ft][snip.id] then
		return doc_cache[ft][snip.id]
	end

	local header = (snip.name or "") .. " _ `[" .. ft .. "]`\n"
	local docstring = { "", "```" .. vim.bo.filetype, snip:get_docstring(), "```" }
	local documentation = { header .. "---", (snip.dscr or ""), docstring }
	documentation = util.convert_input_to_markdown_lines(documentation)
	documentation = table.concat(documentation, "\n")

	doc_cache[ft] = doc_cache[ft] or {}
	doc_cache[ft][snip.id] = documentation

	return documentation
end

function M.getCompletionItems()
	local filetypes = require("luasnip.util.util").get_snippet_filetypes()
	local items = {}

	for i = 1, #filetypes do
		local ft = filetypes[i]
		if not snip_cache[ft] then
			-- ft not yet in cache.
			local ft_items = {}
			local ft_table = require("luasnip").get_snippets(ft, { type = "snippets" })
			if ft_table then
				for _, snip in pairs(ft_table) do
					if not snip.hidden then
						table.insert(ft_items, {
							word = snip.trigger,
							info = get_documentation(snip, ft),
							menu = "[LuaSnip]",
							isSnippet = true,
						})
					end
				end
			end
			snip_cache[ft] = ft_items
		end
		vim.list_extend(items, snip_cache[ft])
	end

	return items
end

return M
```

</details>

**Comment by uga-rosa** [comment]
The problem is that I am a cmp user and just created this on a whim, so I am not sure if I can maintain it. I'll give it all away so someone can be the maintainer.

**Comment by L3MON4D3** [comment]
> The problem is that I am a cmp user and just created this on a whim, so I am not sure if I can maintain it. I'll give it all away so someone can be the maintainer.

That's understandable, what do you say @dseeni? :P

**Comment by L3MON4D3** [comment]
Okay, was worth a shot :D

**Comment by Andrew15-5** [comment]
I guess I'm a bit late to the party, but I just tried to use LuaSnip and after a little trouble adapting to lua and stuff it worked. But I use coc.nvim for Python, C/C++, JS/TS etc. So I tried adding [this](https://github.com/hrsh7th/nvim-cmp#recommended-configuration) this to my configuration, and it works. But when I'm using coc.nvim's autocompletion, it overrides entries that were introduced by nvim-cmp. And when I tried to fix it with [this plugin](https://github.com/uga-rosa/coc-luasnip), it just did nothing (nothing was showing up).

So I would like some help with my problem, if someone knows any solution (or maybe I should open a new issue). Thanks.

**Comment by L3MON4D3** [comment]
Ah, there's no support for coc-nvim except `coc-luasnip` (which is not maintained), sorry :/
You could try getting coc-luasnip up-to-date, I think you could basically start out with `cmp-luasnip` and just adapt it to `coc-nvim` (or look for some kind of compatibility-layer)

**Comment by Andrew15-5** [comment]
Ok, I guess, this is my homework now... Thank you.

P.S. If I achieve some progress on this integration, then I'll post about it here.

**Comment by uga-rosa** [comment]
It is not maintained, but was working at the time it was created. Minimal functionality, though.
So I think it would be a good way to fix coc-luasnip. I don't use coc anymore, so it's hard for me to help.

**Comment by Andrew15-5** [comment]
Understandable. If I will have time and motivation - I'll try and make it work.
