### ISSUE TITLE
Does it support selecting of nested placeholders?

### ISSUE THREAD

**Issue by stasjok** [L3MON4D3/LuaSnip#89]
I tried some of the vscode snippets, but it turned out that nested placeholders works not like usually. I can't just start typing to replace the entire chunk of nested placeholders. This feature is pretty important for me. After reading through examples, I found out, that I supposed to select next choice (which would be empty string), and then type. It's not very convenient, so I was wondering is it possible to make it work with snippets in lua format?
I tried a snippet node, because I thought that entire snippet node is like placeholder, that could be replaced during snippet expansion:
```lua
s("nested",
  sn(1, {
    i(1, "var"),
    t(" = "),
    i(2, "value")
  })),
```
but it doesn't stop at all at `sn(1)` position. So the only way is using choices like this and cycle between them?
```lua
s("nested",
  c(1, {
    sn(1, {
      i(1, "var"),
      t(" = "),
      i(2, "value")
    }),
    t(""),
  }
)),
```
Is it restriction of extmarks?

**Comment by L3MON4D3** [comment]
> So the only way is using choices like this and cycle between them?

Yes, exactly.

> Is it restriction of extmarks?

No, I'm just more comfortable with that behaviour: The simple alternative would be to first SELECT the entire placeholder, then, after jumping once, the next nested one (and perhaps the next nested one). But as placeholders are not directly coupled to text (they don't get removed when the text is removed), after typing new text in SELECT, the next (two) placeholders would still be jumped to (which would be unexpected).
Removing the placeholders on deletion would be a solution, but that would then have to only happen in lsp-snippets and require doing checks (and possibly removing nodes) each time text is removed, in short, it seems way more complicated than just dropping it into a choiceNode and having the user change the choice (which is not to say that it's necessarily better, being more in line with other snippet engines would be pretty nice).

**Comment by stasjok** [comment]
OK. Thank you for the answer. I will try more if I can get used to this behavior. Or maybe I will have to simplify/rework my snippets somewhat. I often created snippets with general placeholder and nested more granular placeholders (to overwrite only part of the snippet).

> Removing the placeholders on deletion would be a solution

Yes, it should work like that. My snippets was in ultisnips format and it's working like this.

Also it would be nice to have $VISUAL placeholder. It can be useful e.g. to wrap some code in if snippet.

**Comment by L3MON4D3** [comment]
> Also it would be nice to have $VISUAL placeholder. It can be useful e.g. to wrap some code in if snippet.

Thats actually possible, you can map eg. tab to yank into some register and then get that text in a functionNode. Luasnip will properly support visual, but that's a nice workaround until then.

**Comment by stasjok** [comment]
Also as a note if someone will read this thread.

I can rewrite the example from my first message like this:

```lua
s("nested",
  c(1, {
    i(1, "var = value"),
    sn(1, {
      i(1, "var"),
      t(" = "),
      i(2, "value")
    }),
  }
)),
```

This way after expanding this snippet I will get preselected line `var = value`. If I want to change only part of it, I first choice, then I instantly get selected only word `var` and can jump to word `value`. This is very close to behavior I used to. I think I will use it like this.

I wonder if it worth it making a parser of vscode snippets to create choice not of empty string and nested placeholders, but of: 1) one single Insert node with all the default text of nested placeholders and 2) separate normal placeholders. This way we can choice not between empty string and snippet, but between one or many insert nodes with the same text inside. Single insert node should be probably the first choice, because it works like that in other snippet engines. Or it can be configurable.

I will reopen it. Feel free to close if this suggestion is bad.

**Comment by L3MON4D3** [comment]
Hmm, I'll definitely think about your suggestion, maybe I'll implement it in a branch and collect some feedback about it.
Will take some time though, there's some stuff I'd like to get done before :D
Thank you!

**Comment by L3MON4D3** [comment]
Perhaps even make it configurable directly, that would probably be the best solution.

**Comment by leiserfg** [comment]
I'll work on the `$VISUAL` aka `$TM_SELECTION` placeholder this weekend probably.

**Comment by L3MON4D3** [comment]
Nice! I'll see if I get the dynamic lambdas #82 done till then, that would enable an elegant implementation on the lua side of things.

**Comment by wincent** [comment]
> I'll work on the `$VISUAL` aka `$TM_SELECTION` placeholder this weekend probably.

Is there an issue for this? (Couldn't find one, but would love to follow along.)

**Comment by L3MON4D3** [comment]
Whoops, completely glanced over your comment :sweat_smile:
Retroactively, you could check out #92-#94.

**Comment by L3MON4D3** [comment]
> Also as a note if someone will read this thread.
> 
> I can rewrite the example from my first message like this:
> 
> ```lua
> s("nested",
>   c(1, {
>     i(1, "var = value"),
>     sn(1, {
>       i(1, "var"),
>       t(" = "),
>       i(2, "value")
>     }),
>   }
> )),
> ```
> 
> This way after expanding this snippet I will get preselected line `var = value`. If I want to change only part of it, I first make a choice, then I instantly get only word `var` selected and I can jump to the word `value`. This is very close to a behavior I'm used to. I think I will use it like this.
> 
> I wonder if it's worth it changing a parser of vscode snippets to create choice not of empty string and nested placeholders, but of: 1) one single Insert node with all the default text of nested placeholders and 2) separate normal placeholders. This way we can choose not between a number of placeholders and an empty string, but between one or many insert nodes with the same text inside. A single insert node should be probably the first choice, because it works like that in other snippet engines. Or it can be configurable.
> 
> I will reopen it. Feel free to close if this suggestion is bad.

I thought about it, one problem I would see is that it's less clear that there actually is a choice/placeholder there, therefore I'd switch the order of the choices. Then, one would, after deciding to overwrite everything in the node by changing the choice, get all the text selected. That wouldn't necessarily be bad, but I wouldn't see the point in making that change, it doesn't really add anything IMO.
If you feel strongly about this, feel free to open another issue, keeping things organized and all that :D

**Comment by stasjok** [comment]
You are right about the part that "it's less clear that there actually is a choice/placeholder there". As I understand, in order to make it clear you even insert extra empty insert node. So it's an extra hotkey to press in every nested snippet. To be honest, I still don't like this behavior (though I doubt I will be changing snippets engine any time soon). But after your message saying that this is an intentional decision, I came with that idea, which I thought is a good compromise between classic snippet engines and current behavior (the point about less clear that there is choice is not really matter for me, because I usually use my own snippets, so most of the time I know where choice would be). OK, I completely understand that you don't want to change current solution. I can always create snippets in lua with my desired behavior. One thing that stops me is that lua snippets is not portable. If I ever would want to switch from luasnip or even from neovim I would like to bring my snippets with me and vscode snippets is pretty popular format. So I kind of want most simple snippets in vscode format and heavy scripted ones in lua (I never really got to that point yet, I still configure neovim, but I hope to create something cool in the future). Maybe I'll look at the snippet parser and will manage to change something.

One thing I'm not sure about is that LuaSnip doesn't remember choices. Sometimes I press the wrong button in nested snippet (to change choice instead of jump) and all my editing is gone. I can't switch back to the previous choice, because it resets to defaults. Can mirror node clone entire text from snippet node from another choice? I guess not.

**Comment by L3MON4D3** [comment]
> You are right about the part that "it's less clear that there actually is a choice/placeholder there". As I understand, in order to make it clear you even insert extra empty insert node. So it's an extra hotkey to press in every nested snippet. To be honest, I still don't like this behavior (though I doubt I will be changing snippets engine any time soon). But after your message saying that this is an intentional decision, I came with that idea, which I thought is a good compromise between classic snippet engines and current behavior (the point about less clear that there is choice is not really matter for me, because I usually use my own snippets, so most of the time I know where choice would be). OK, I completely understand that you don't want to change current solution. I can always create snippets in lua with my desired behavior. One thing that stops me is that lua snippets is not portable. If I ever would want to switch from luasnip or even from neovim I would like to bring my snippets with me and vscode snippets is pretty popular format. So I kind of want most simple snippets in vscode format and heavy scripted ones in lua (I never really got to that point yet, I still configure neovim, but I hope to create something cool in the future). Maybe I'll look at the snippet parser and will manage to change something.

As this is very much something that depends on ones' own taste (there are different trade-offs), perhaps the best solution would be to just provide a setting where the function that creates the snippet (for this particular case) can be set? It's like [3 lines](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/util/parser.lua#L172) (and pretty independent ones) that actually create the it, so eg. `tab_stops[pos] = user_provided_function(snippet)` could work.

**Comment by L3MON4D3** [comment]
> One thing I'm not sure about is that LuaSnip doesn't remember choices. Sometimes I press the wrong button in nested snippet (to change choice instead of jump) and all my editing is gone. I can't switch back to the previous choice, because it resets to defaults. Can mirror node clone entire text from snippet node from another choice? I guess not.

Sounds doable, open an issue :P

**Comment by L3MON4D3** [comment]
> As this is very much something that depends on ones' own taste (there are different trade-offs), perhaps the best solution would be to just provide a setting where the function that creates the snippet (for this particular case) can be set? It's like [3 lines](https://github.com/L3MON4D3/LuaSnip/blob/master/lua/luasnip/util/parser.lua#L172) (and pretty independent ones) that actually create the it, so eg. `tab_stops[pos] = user_provided_function(snippet)` could work.

The functionality is (since some time :sweat_smile:)implemented as [`parser_nested_assembler`](https://github.com/L3MON4D3/LuaSnip/issues/182)

**Comment by stasjok** [comment]
> The functionality is (since some time 😅)implemented as [`parser_nested_assembler`](https://github.com/L3MON4D3/LuaSnip#config)

Wow, I completely missed it.
I didn't test it thoroughly, but looks like I've got suggested by me behavior with:
```lua
parser_nested_assembler = function(pos, snip)
  local i = require("luasnip").insert_node
  local c = require("luasnip").choice_node
  local snip_text = snip:get_static_text()
  snip.pos = nil
  return c(pos, { i(nil, snip_text), snip })
end
```
Sure, I need to use it for sometime to see if it is indeed convenient.

**Comment by L3MON4D3** [comment]
I'll add another example to the wiki on how to make it work exactly like in vscode(-automatically skipping overwritten placeholders), for updates on that watch #184.
