### ISSUE TITLE
Replace `\t` when makes sence

### ISSUE THREAD

**Issue by leiserfg** [L3MON4D3/LuaSnip#9]
When rendering the snippet in the buffer, if `expandtab` is on `\t` should be replaced by the `tabstop` amount of spaces.

**Comment by L3MON4D3** [comment]
Tbh I always assumed that nvim_buf_set_text would do just that :grimacing:. I'll look into what to do here, probably wrap some function around it to replace all tabs.

**Comment by L3MON4D3** [comment]
Okay, when expandtab is set, tabs are now replaced with tabstop-many spaces. This also applies to text returned by functions.
