### ISSUE TITLE
Error when deleting line

### ISSUE THREAD

**Issue by JustSage** [L3MON4D3/LuaSnip#90]
When having both LSP & Lua up this error prompts after deleting a line using 'dd' combo.

```Error detected while processing TextChanged Autocommands for "*":```
```E5108: Error executing lua .../site/pack/packer/opt/LuaSnip/lua/luasnip/nodes/node.lua:99: attempt to get length of a nil value```

Will share configs on demand.

**Comment by clason** [comment]
You're probably in an active snippet, right? (Meaning, you haven't jumped to the exit node `i(0)` yet.)

If you mess with an active snippet, things get ugly fast.

**Comment by JustSage** [comment]
That's the thing, it occurs even when ending the snippet.
For example (in python):
def -> def {$1 function name} {$2 params} {pass}
even after getting out of the scope, using dd prompts this error.

On top of that for some reason I have multiple snippets that provides the same behavior.

**Comment by clason** [comment]
Then you should give a reproducible and minimal example that someone can copy and test.

**Comment by L3MON4D3** [comment]
Have you checked whether there's some formatting from the language server? That may mess up extmarks.
Anyway, @clason is right, a reproducible example would be great

**Comment by JustSage** [comment]
Changing `updateevents` to default `InsertLeave` solved the issue.
Is there a reproduction example structure to follow ? Tried to explain it in a previous post  but I assume it's not reproducible.

**Comment by L3MON4D3** [comment]
Could you try with your old `updateevents` and latest master?

**Comment by L3MON4D3** [comment]
> Is there a reproduction example structure to follow ?

Not really, just a short, deterministic description that leads to the error is fine

**Comment by JustSage** [comment]
> Could you try with your old `updateevents` and latest master?

Having an issue to update LuaSnip with packer. worked yesterday.

**Comment by L3MON4D3** [comment]
> Someone forced pushed to master

:grimacing::grimacing:

**Comment by L3MON4D3** [comment]
I'll assume this is fixed, feel free to reopen if not :)
