### ISSUE TITLE
can't load latex snippets from cursor position

### ISSUE THREAD

**Issue by nikinbaidar** [L3MON4D3/LuaSnip#903]
In my config when `ft_func` is set to `require('luasnip.extras.filetype_functions').from_pos_or_filetype` the tex snippets defined for latex files don't seem to work. If I remove this line both lua snippets as well as vim snippets are working fine. 

This, however, does work for other files. I've tested on html, c, javascript. Snippets are being loaded properly depending on the context. 

Here's my extended loaf ft_func:
```lua
load_ft_func = filetype_functions.extend_load_ft({
    html = { "javascript", "css" },
   latex = { "tex" }
}),
```

I've install the `latex` tree-sitter as well. I can't seem to get my head around this. Is there a way I can tell luasnip to load from filetype just for tex files?

**Comment by nikinbaidar** [comment]
Actually adding `luasnip.filetype_extend(" {"tex"})` solves the issue. But I want to know what's the functional difference between
```
 load_ft_func = filetype_functions.extend_load_ft({
    html = { "javascript", "css" },
   latex = { "tex" }
}),

```

and `luasnip.filetype_extend`

**Comment by L3MON4D3** [comment]
(assuming `ls.filetype_extend("latex", {"tex"})`)
The difference is that `load_ft_func` only influences which snippets are lazy_load, eg. "load tex when latex is loaded", whereas filetype_extend additionally says "when expanding, also look at tex-snippets if `ft_func` reports latex"
