### ISSUE TITLE
BUG: """ not recognized correctly

### ISSUE THREAD

**Issue by Zeioth** [L3MON4D3/LuaSnip#910]
LuaSnip fails to create an snippet containing """"

## Demo
![screenshot_2023-06-05_07-26-58_348854732](https://github.com/L3MON4D3/LuaSnip/assets/3357792/5cc9f83d-e5b3-452e-924e-38d0cfe72d3c)

After pressing ENTER, no option for guided auto completion is given, it just prints garbage directly.
![screenshot_2023-06-05_07-27-02_197504998](https://github.com/L3MON4D3/LuaSnip/assets/3357792/120adbc0-fbc1-4023-9ce0-56adb21ddba3)

After pressing u to undo once.
![screenshot_2023-06-05_07-27-06_077039750](https://github.com/L3MON4D3/LuaSnip/assets/3357792/b3e92859-6e29-40a9-98bb-8a9bc5a735e2)

**Comment by Zeioth** [comment]
If I remove the auto completion tag and I leave it like

```json
    "comment simple": {
        "prefix": "\"\"\"",
        "body": [
            "\"\"\"",
            "A one-line summary",
            "\"\"\""
        ],
        "description": "A simple Python docstring comment. Useful when you prefer to add the docstrings manually."
    },
```

It prints correctly

![screenshot_2023-06-05_07-33-09_717859048](https://github.com/L3MON4D3/LuaSnip/assets/3357792/d20a5197-b03d-45dc-8340-92aae31b2234)

**Comment by L3MON4D3** [comment]
Weird.. Does the same happen with manual expansion? (assuming what you've just shown is expansion via cmp)

**Comment by Zeioth** [comment]
Yes It is vía CMD. How can I test the manual expansión?

**Comment by L3MON4D3** [comment]
Bind some key to `ls.expand()`, press it to the right of the trigger
Or type `i"""<space><esc>:lua ls.expand()<Cr>`, that should work too

**Comment by Zeioth** [comment]
Thank you so much for your help. Either for a cmp update or for a change on my personal mappings. The issue is gone. Closing.
