### ISSUE TITLE
[Bug]: `fmta` nodes do not respect option `trim_empty` 

### ISSUE THREAD

**Issue by Bekaboo** [L3MON4D3/LuaSnip#920]
`fmta` nodes (`require("luasnip.extras.fmt").fmta`) do not respect the `trim_empty` option.

An example snippet:

```lua
s(
  { trig = 'test' },
  fmta(
    [[ <t>]],
    { t = t('something after a space') },
    { trim_empty = false }
  )
)
```

after expansion it should look like:

```
 something after a space
```

but the preceding space is missing.

**Comment by L3MON4D3** [comment]
`trim_empty` is responsible for removing completely empty lines, you'll want to set `dedent` to false

**Comment by Bekaboo** [comment]
Thanks, works like a charm!
