### ISSUE TITLE
Insert Node with default field exits snippet if default value is not modified

### ISSUE THREAD

**Issue by westernwontons** [L3MON4D3/LuaSnip#932]
Here's my setup:

```lua
return {
  "L3MON4D3/LuaSnip",
  config = function(plugin, opts)
    opts.region_check_events = "CursorHold,InsertLeave"
    opts.delete_check_events = "TextChanged,InsertEnter"

    require "plugins.configs.luasnip"(plugin, opts)
    require("luasnip.loaders.from_vscode").lazy_load { paths = { "./lua/user/snippets" } }
}
```

Here's the snippet:
```lua
    ls.add_snippets("rust", {
      s(
        "testmod",
        fmta(
          [[
          #[cfg(test)]
          mod tests {
              #[test]
              fn <>() {
                  <>
              }
          }
          ]],
          {
            i(1, "name"),
            i(2),
          }
        )
      ),
}
```

and here's the keybinding for insert mode:

```lua
    ["<C-x>"] = {
      function()
        local ls = require "luasnip"
        local cmp = require "cmp"

        if ls.expand_or_jumpable() then
          ls.expand_or_jump()
          -- when the completions hover is visible
          -- select the next item and expand it
        elseif cmp.visible() then
          cmp.select_next_item()
          vim.api.nvim_input "<return>"
        end
      end,
      desc = "Expand snippet or jump forwards in snippet",
    },

```

Here's a video of the current behaviour:

https://github.com/L3MON4D3/LuaSnip/assets/75550932/622a3825-02c2-4f26-b4e3-a1d3b5cee443

My expectation:

If the default value is not edited, jumping over that insert node should leave the default there and allow me to cycle through the nodes.

**Comment by L3MON4D3** [comment]
Hmm could you show the log? `:lua ls.log.open()`, there should be something like "Removing snippet ... due to error ..."
One other thing that seems weird: do you also have these mappings for SELECT-mode? That's the mode when the insertNode is highlighted, if there are no mappings at that time, jumping can't work

**Comment by westernwontons** [comment]
> Hmm could you show the log? `:lua ls.log.open()`, there should be something like "Removing snippet ... due to error ..." One other thing that seems weird: do you also have these mappings for SELECT-mode? That's the mode when the insertNode is highlighted, if there are no mappings at that time, jumping can't work

I only have 633 lines of this:

```
WARN  | vscode-loader: Package /Users/nagybotond/.local/share/nvim/lazy/nvim-ufo/package.json does not contribute any snippets, skipping it
```

The mappings are only in insert mode, although I managed to work around this by adding the `<C-x>` to normal mode as well. Tapping c-x twice let's me jump and back.

BUT your solution is much better! I was missing the keybind. I appreciate the help!

**Comment by L3MON4D3** [comment]
Nice, you're welcome :)
