### ISSUE TITLE
Highlights for unvisited placeholders

### ISSUE THREAD

**Issue by MariaSolOs** [L3MON4D3/LuaSnip#935]
I've read the docs and I've tried several variations in my `ext_opts` config, but I haven't been able to achieve something like this (ignoring the syntax error):

<img width="149" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/62502207/2b3f7592-529e-4f41-ba83-a8aef2c6f38c">

Mainly, I want to have some kind of indicator (such as the tiny cursor-like label in the function body above) of the locations in the snippet that I still haven't visited. In the example above, I would like something like (where `|` is the current cursor position):
```
fn |() {
  /* tiny highlight or indicator here */
}
```

**Comment by MariaSolOs** [comment]
Never mind, I was overwriting my setup when configuring `cmp` so that's why I was seeing nothing 😂 
I made it work though! I'm leaving this here for future reference:
```lua
ext_opts = {
  [types.insertNode] = {
    unvisited = {
      virt_text = { { '|', 'Conceal' } },
      virt_text_pos = 'inline',
    },
  },
}
```

**Comment by MariaSolOs** [comment]
Reopening this because the above code only highlights placeholders inside the snippet, but there's actually a final tabstop at the end of the snippet. Using the example from before, VS Code will create placeholders as follows:
<img width="163" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/62502207/883b81a9-66c5-470e-95ef-83814d21527f">

Versus the one I obtain in Neovim (I'm loading snippets from VS Code BTW):
<img width="172" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/62502207/3e171f14-44be-4eab-9406-a57a03ecdc1d">


@L3MON4D3 am I missing something? Why isn't the node inside the function highlighted...?

**Comment by L3MON4D3** [comment]
Ah, we differentiate between $0 and other placeholders (`exitNode` and `insertNode`) (at least for now, the difference is becoming smaller and smaller, actually)
I think if you apply the same configuration for `types.exitNode`, it should work as you want it to

**Comment by MariaSolOs** [comment]
@L3MON4D3 lovely, that worked! Thanks a lot :)

**Comment by L3MON4D3** [comment]
Nice👍
Yes they are, every snippet has a $0, and it can always be visited

**Comment by MariaSolOs** [comment]
@L3MON4D3 awesome. I'll update the code above to have this modification so that the placeholders truly match VS Code's (in fact, they're much better 😉).

Also THANK YOU for the amazing plugin and quick replies! I truly admire great project like this that are maintained by wonderful people ❤️

**Comment by L3MON4D3** [comment]
Thank you for the kind words :blush:

**Comment by xzbdmw** [comment]
Is it possible to add virtual text if there don't have a default placeholder, otherwise don't show the virtual text?
