### ISSUE TITLE
Not updating LuaSnip by lazy.nvim

### ISSUE THREAD

**Issue by apple115** [L3MON4D3/LuaSnip#940]
when I update the LuaSnip by lazy.nvim ,I git this 
```   ....local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/git.lua:58: attempt to index local 'range' (a nil value)  ```
I think the `range` was not declare loacl.
but I don't to repair this (my English maybe a bit poor)
Thank you

**Comment by L3MON4D3** [comment]
Mhmm, I don't think this error is from luasnip.
Could you show the code where you add luasnip to lazy.nvim?

**Comment by L3MON4D3** [comment]
Ah, it's `version`: replace `"<CurrentMajor>.*"` with `"v1.*"`, then it should work

**Comment by apple115** [comment]
yes ,it work
thank you very much
