### ISSUE TITLE
Respect indentation with visual selection function node snippet and TM_SELECTED_TEXT variable

### ISSUE THREAD

**Issue by petobens** [L3MON4D3/LuaSnip#944]
Consider the following snippet:
```lua
    s(
        { trig = 'ef', dscr = 'Empty function' },
        fmta(
            [[
                function(<>)
                    <><>
                end
            ]],
            {
                i(1),
                f(visual_selection),
                i(2),
            }
        )
    ),
```
where visual selection and f,i, etc are defined by:
```lua
local ls = require('luasnip')
local s = ls.snippet
local i = ls.insert_node
local f = ls.function_node
local fmta = require('luasnip.extras.fmt').fmta
local line_begin = require('luasnip.extras.expand_conditions').line_begin

local function visual_selection(_, snip)
    return snip.env.TM_SELECTED_TEXT or {}
end
```
Now, as in the GIF, do:
1. Open a lua file with the following 2 lines:
```lua
local z = 3
local k = 2
```
2. Visually select those 2 lines and trigger the `ef` snippet
3. The second line, `local k = 2`, is not correctly indented after snippet expansion (it should be indented at the same level as `local z = 3`).

So my question /feature-request is whether there is a way to get proper indentation when using `TM_SELECTED_TEXT` or `LS_SELECT_DEDENT` etc  

![indent](https://github.com/L3MON4D3/LuaSnip/assets/2583971/9627bd18-0416-49f6-817b-ab174cca50fd)

**Comment by L3MON4D3** [comment]
Ah, you can use `indentSnippetNode` for this (or manually add `\t`), and I'd recommend `LS_SELECT_DEDENT` (TM_SELECTED_TEXT is weird, I made it compatible with vscode)

**Comment by petobens** [comment]
Hi @L3MON4D3 thanks for the quick reply. I tried re writing the snippet like:
```lua
    s(
        { trig = 'ef', dscr = 'Empty function' },
        fmta(
            [[
                function(<>)
                    <><>
                end
            ]],
            {
                i(1),
                isn(2, f(visual_selection)),
                -- f(_G.LuaSnipConfig.visual_selection),
                i(2),
            }
```
But without success.. How should I combine `isn` and my `visual_selection` function node?

**Comment by L3MON4D3** [comment]
I think `isn` is just missing the string, so `isn(2, {...}, "$PARENT_INDENT\t")` should do it

**Comment by petobens** [comment]
Mmm I'm still getting:
```
E5108: Error executing lua: .../pedro/.config/nvim/lua/plugin-config/luasnip_config.lua:9: attempt to index field 'env' (a nil value)
stack traceback:
        .../pedro/.config/nvim/lua/plugin-config/luasnip_config.lua:9: in function 'fn'
        ...are/nvim/lazy/LuaSnip/lua/luasnip/nodes/functionNode.lua:47: in function 'update'
        ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:820: in function 'update'
        ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:820: in function 'update'
        ...al/share/nvim/lazy/LuaSnip/lua/luasnip/nodes/snippet.lua:589: in function 'trigger_expand'
        ...edro/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:243: in function 'snip_expand'
        ...edro/.local/share/nvim/lazy/LuaSnip/lua/luasnip/init.lua:306: in function 'expand'
        .../pedro/.config/nvim/lua/plugin-config/luasnip_config.lua:34: in function <.../pedro/.config/nvim/lua/plugin-config/luasnip_config.lua:32>
```

**Comment by L3MON4D3** [comment]
Ahhhh my bad, I didn't have a close-enough look at the functionNode:
`f` actually does not receive the snippet (which has the `env`-table), but the immediate parent. Often, this does no matter since they are the same, but here it does. If you change `snip.env` to `snip.snippet` (and maybe rename snip to parent, just so it seems a bit less nonsensical) it should work

**Comment by petobens** [comment]
So assuming I understood correctly I tried the following:
```lua
local function visual_selection(_, parent)
    return parent.snippet.LS_SELECT_DEDENT or {}
end
```
and then have the node as:
```lua
isn(2, { f(visual_selection) }, '$PARENT_INDENT\t'),
```
Now I don't get an error but the visually selected text is not selected/pasted.

**Comment by bhataktaBhai** [comment]
I believe you need `parent.snippet.env.LS_SELECT_DEDENT`.

Works on the latest master at least.

**Comment by L3MON4D3** [comment]
Yeah exactly, my bad :sweat_smile:

**Comment by petobens** [comment]
Great. Thanks!

**Comment by voyeg3r** [comment]
Could you share the final solution so I can copy?
