### ISSUE TITLE
Only latex not working

### ISSUE THREAD

**Issue by VolinM** [L3MON4D3/LuaSnip#954]
Hi,

I'm trying to configure all of my snippets. I have a dedicated lua file for each file type. "all.lua", "c.lua" and "python.lua" work as expected, but "tex.lua" doesn't. 

Am I doing anything wrong?

**Comment by L3MON4D3** [comment]
Maybe? :P
One likely mistake is that the filetype is not actually `tex`, but `latex` or something different. You can check it by opening the file and calling `:lua =vim.o.filetype`

**Comment by VolinM** [comment]
You are right!
The filetype is set to `plaintex`. I created a file `plaintex.lua` and it worked fine!
It might be out of scope here, but do you know how I can set it so that it's recognized as `tex` or `latex` rather than `plaintex`?

Thanks! And thanks for the quick response, I was not expecting that

**Comment by crumbtoo** [comment]
I'm having this same issue, but both `:set filetype?` and `:lua =vim.o.filetype` show `tex` :/
