### ISSUE TITLE
extend existing snippets is not working

### ISSUE THREAD

**Issue by OsmarJoseph** [L3MON4D3/LuaSnip#964]
How can I use existing `vscode` snippets and add custom ones ? 

I have made the setup to use custom snippets with `require("luasnip/loaders/from_vscode").lazy_load({ paths = { './custom-snippets' } })` 

but then the snippets from `friendly-snippets` don't show anymore, just the custom ones. Should I add both ? like:

```
require("luasnip/loaders/from_vscode").lazy_load()
require("luasnip/loaders/from_vscode").lazy_load({ paths = './custom-snippets' })
```

**Comment by L3MON4D3** [comment]
Yep, adding both should work :+1:

**Comment by OsmarJoseph** [comment]
Thanks!
