### ISSUE TITLE
Adding custom snippets on top of the VsCode like snippets

### ISSUE THREAD

**Issue by doganalper** [L3MON4D3/LuaSnip#971]
I created some snippets for myself and want to use them alongside with snippets that comes from `luasnip.loaders.from_vscode` any way to achieve this? It currently only loads my custom snippets when passed to `lazy_load` function.

**Comment by L3MON4D3** [comment]
https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#loaders has some information on this, take a look if you haven't solved it yet :sweat_smile:

**Comment by doganalper** [comment]
Sadly I couldn't solve it 😔
<img width="608" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/48688801/4734e675-c766-4836-89eb-738dffa1588b">

first line loads snippets from vscode but whenever I include code in second line it only loads my own snippets and I can't access vscode snippets.

**Comment by L3MON4D3** [comment]
Oh, yeah that's kind of a convenience-function: if there are no arguments to `lazy_load`, we look for in `runtimepath` (ie. load snippets from other plugins), if there is a path, we don't do that.
The solution is to `lazy_load` twice, once with, once without `paths` :D

**Comment by doganalper** [comment]
@L3MON4D3 Oh I would never thought about using `lazy_load` twice 😁 Thanks!

**Comment by rubiin** [comment]
I am still facing this even after reloading my custom snippets.
https://github.com/rubiin/init.lua/blob/b779020ad3dec8da90e1b571447e67319c6f8e63/lua/plugins/cmp.lua#L25
