### ISSUE TITLE
Autosnippets dont work with specifiy filetypes

### ISSUE THREAD

**Issue by Paultv04** [L3MON4D3/LuaSnip#972]
First of all, I'm just getting started with Neovim/Vim in general because I want to write Latex for university with it so I'm sorry if I make some obvious mistakes. ,:)

NVIM: v0.9.1
Plugins: lazy.nvim (v10.3.0), LuaSnip (v2.0.0)

init.lua:
```
require("config.lazy")
```

lua/config/lazy.lua:
```
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup("plugins")
```

lua/plugins/luasnip.lua:
```
return {
	"L3MON4D3/LuaSnip",
	-- follow latest release.
	version = "2.*", -- Replace <CurrentMajor> by the latest released major (first number of latest release)
	-- install jsregexp (optional!).
	build = "make install_jsregexp",
	
	main = "luasnip",
	
	opts = {
		enable_autosnippets = true,
		store_selction_keys = "<Tab>",
	},

	init = function()
		require("luasnip.loaders.from_lua").load({paths="~/.config/nvim/lua/snippets/"})
	end,
}
```

lua/snippets/tex/math.lua:
```
-- Abbreviations used in this article and the LuaSnip docs
local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local d = ls.dynamic_node
local fmt = require("luasnip.extras.fmt").fmt
local fmta = require("luasnip.extras.fmt").fmta
local rep = require("luasnip.extras").rep

return {
	-- Examples of Greek letter snippets, autotriggered for efficiency

	require("luasnip").snippet({filetype="<FILETYPE>", trig=";a", snippetType="autosnippet"}, 
		{
			require("luasnip").text_node("\\alpha"),
		}
	),
	require("luasnip").snippet({filetype="tex", trig=";b", snippetType="autosnippet"}, 
		{
			require("luasnip").text_node("\\beta"),
		}
	),
	require("luasnip").snippet({filetype="tex", trig=";c", snippetType="autosnippet"}, 
		{
			require("luasnip").text_node("\\gamma"),
		}
	),

	require("luasnip").snippet(
		{
			filetype="all",
			trig="hi",
			dscrd="An autotriggering snippet that expands 'hi' into 'Hello, world!'",
			regTrig=false,
			priority=100,
			snippetType="autosnippet"
		},
		{
			require("luasnip").text_node("Hello, world!"),
		}
	)
}
```

I'm following an article for writing latex with Neovim but it is not completly up to date and I made adjustments but sticking close to the documentation of lazy.nvim and Luasnip.
The autotrigger for "hi" triggers as expected in all filetypes.
I made tests for different filetypes for ";a" because it did not work with "tex" as <FILETYPE>.
Here are my results:

"tex": autotrigger does not work
"abc": autotrigger works
"json": autotrigger works
"test": autotrigger does not work
"md": autotrigger does not work
"java": autotrigger does work
"lua": autotrigger does work
"xyz": autotrigger does not work

I hope my tests can give you some insight but I really was not sure for what to test because I couldnt really find anything about this setting in the documentation.
Also thanks for this awesome plugin and for the help in advance. ^^

**Comment by L3MON4D3** [comment]
Hi!
All of this looks pretty good, is it possible you're only confusing filetype with file-extension?
luasnip will, when looking for the snippets for some buffer, look at its `vim.o.filetype`. For example, `a.md` will have filetype `"markdown"`, not `"md"`.
Hope this helps :)

**Comment by Paultv04** [comment]
Oh, that helps a lot. Thx ,:) i thought it gets the filetype by the specific extensions because it worked with "abc" but it solves my problem. :D
