### ISSUE TITLE
Include VSCode LuaSnip snippets in nvim-cmp auto complete

### ISSUE THREAD

**Issue by Werzi2001** [L3MON4D3/LuaSnip#977]
I'm not sure if this is the right place to ask (maybe `nvim-cmp` is better?) but I'll try it anyway.

I configured both `LuaSnip` (including VSCode snippets from `rafamadriz/friendly-snippets`) and `nvim-cmp` (added `LuaSnip` as source to `nvim-cmp`). I'm mostly writing Java code and the VSCode snippets seem to work. E.g. I can type `private_method` hit `Tab` and the snippet gets expanded. Anyhow I would prefer to include the snippets into the auto complete of `nvim-cmp` (`C-Space`). There are some snippets in the `nvim-cmp` autocomplete list but the ones from `LuaSnip` (only `friendly-snippets`?) are missing.

Is this expected or is there a way to include the `LuaSnip` snippets in the normal auto complete list of `nvim-cmp` and I'm missing something?

**Comment by L3MON4D3** [comment]
Oh, you'll need `cmp_luasnip`, I think the snippets you're seeing are provided by lsp.

**Comment by Werzi2001** [comment]
That's been it, it's working now. Thanks a lot.
