### ISSUE TITLE
Definition order for normal and postfix snippets with and without preceding "." in the trigger leads to inconsistent expansion

### ISSUE THREAD

**Issue by kylefhartzenberg** [L3MON4D3/LuaSnip#979]
As an example, consider the following snippets to be used to add the overline command inside LaTeX mathematics environments:
```lua
return{
    postfix( -- over-line (i.e. bar) post-fix
        {
            trig = ".ov",
            dscr = "Automatically post-fix text to be '\\overline{}'",
            snippetType = "autosnippet",
        },
        {
            f(function(_, parent)
                return "\\overline{" .. parent.snippet.env.POSTFIX_MATCH .. "}"
            end, {}),
        }
    ),
    s( -- over-line (i.e. bar)
        {
            trig = "ov",
            dscr="Automatically expand 'ov' to be '\\overline{}'",
            snippetType="autosnippet",
        },
        fmt(
            [[
            \overline{<>}
            ]],
            {  i(1),  },
            { delimiters = "<>" }
        )
    ),
}
```

If one types `x` followed by `.ov`, the postfix snippet expands correctly producing `\overline{x}`. However, if the `postfix` snippet above is defined *after* the normal snippet `s`, then the same key press sequence produces `x.\overline{}`.

I am not sure if this is an issue, or expected behaviour. If the latter, then it would be worth adding it to the [Postfix section of the documentation](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#postfix-snippet) as I couldn't readily find why my postfix snippets started behaving differently until I resorted to restoring my `tex.lua` snippets file. After restoration, I then noticed that it was the re-ordering that caused the inconsistent behaviour. Let me know if you'd like me to add a paragraph to the documentation and send through a pull request.

I am using the latest version of Neovim (0.9.1), LuaSnip and nvim-cmp at the time of writing.

**Comment by L3MON4D3** [comment]
Ah, I'd categorise that as expected behaviour: if there are two snippets that could match the buffer-position, either one may expand (in reality it's deterministic (at least for now), because we check whether a snippet matches in the order they were added).

You can make the preference explicit by providing a priority.

I think we have some documentation on this (for example in the documentation for `add_snippets`, and `snippet`, IIRC), but if you have a good place to put it, I'd welcome the addition :)
(maybe something like `Troubleshooting`?)

**Comment by kylefhartzenberg** [comment]
Merged pull request https://github.com/L3MON4D3/LuaSnip/pull/981 which updates the documentation makes this issue no longer relevant. It is recommended that users set a priority for snippets with similar triggers, or take care when ordering their definitions.
