### ISSUE TITLE
Some weird things with conditions inside snippets

### ISSUE THREAD

**Issue by dajohans** [L3MON4D3/LuaSnip#98]
When I write LaTeX, I want to have snippets in which part of the snippet _disappears_ if I leave some field _empty_. This seems very similar to what is discussed in https://github.com/L3MON4D3/LuaSnip/issues/71. When take the code suggested in https://github.com/L3MON4D3/LuaSnip/issues/71#issuecomment-886187876 and change it to be a snippet I want then I haven't managed to quite get the behaviour I want. What I then get is that code _appears_ is I leave a node _nonempty_ but what I want is that it _disappears_ if I leave it _empty_. I'm not sure if the issue is that I don't understand the conditional nodes or if I don't understand lua pattern matching or if maybe there's a bug somewhere. Due to the lack of documentation, I am certainly not confident that I understand how conditional nodes are supposed to work.

Any help is appreciated!

### Where I start off
First I have the following lines
```lua
local ls = require('luasnip')
local s = ls.s
local t = ls.t
local m = require("luasnip.extras").match
```
to get some functions used to create the snippet. Let's take the snippet in https://github.com/L3MON4D3/LuaSnip/issues/71#issuecomment-886187876 and make a slight change to make is use `m` instead of `n`: 
```lua
s('eq', {
m(1, '^$', '\\begin{equation*}', '\\begin{equation}\\label{eq:'),
i(1),
m(1, '^$', '', '}'),
t { '', '\t' },
i(0),
m(1, '^$', '\n\\end{equation*}', '\n\\end{equation}'),
})
```
Now if I write `eq` and expand the snippet, I get
```latex
\begin{equation*}|
	
\end{equation*}
```
and `|` is the cursor. If I jump to the next saved location I end up with
```latex
\begin{equation*}
	|
\end{equation*}
```
If instead I write something, for example `a`, and have
```latex
\begin{equation*}a|
	
\end{equation*}
```
and then jump to the next location then I end up with
```latex
\begin{equation}\label{eq:a}
	|
\end{equation}
```
As you can see, if I leave the first location empty then nothing happens and if I leave it nonempty then a `\label` _appears_ and `*` _disappears_.

### Attempt at adjusting to my desired behaviour
It seems that it should be easy: just switch some condition around. This condition is in the `m` function. My understanding of `m` is mainly from https://github.com/L3MON4D3/LuaSnip/pull/84 and I gather that it works as follows. If the signature is
```lua
m(index, pattern, if_match_then_this, else_this)
```
`index` seems to be the index of the jump locations in the snippets. So `i(1)` gives index `1`. The `pattern` in `m` seems to the be matched against the text which is inserted at the location `i(1)`. If the pattern is successfully matched, then the snippet adds the text at `if_match_then_this` and if the pattern doesn't match then it adds the text at `else_this`. And _before_ the text has been matched then the text in `if_match_then_this` is shown.

If this understanding is correct then it seems easy enough to adjust the above snippet to get my behaviour. I should negate the condition `^$` and I should switch places for the text at the `if_match_then_this` position and the `else_this` position. The condition `^$` checks for empty so in my negation I want to check for nonempty. To my understanding, this should be possible to do with `[.+]`, which should check for any character (`.`) at least once(`+`). So now I change
```lua
s('eq', {
m(1, '^$', '\\begin{equation*}', '\\begin{equation}\\label{eq:'),
i(1),
m(1, '^$', '', '}'),
t { '', '\t' },
i(0),
m(1, '^$', '\n\\end{equation*}', '\n\\end{equation}'),
})
```
into
```lua
s('eq', {
m(1, '[.+]', '\\begin{equation}\\label{eq:', '\\begin{equation*}'),
i(1),
m(1, '[.+]', '}', ''),
t { '', '\t' },
i(0),
m(1, '[.+]', '\n\\end{equation}', '\n\\end{equation*}'),
})
```
Now if I write `eq` and expand the snippet I get
```latex
\begin{equation*}|
	
\end{equation*}
```
and if I write `a` and then jump I get
```latex
\begin{equation*}a
	|
\end{equation*}
```
and if I leave the first location empty and jump then I get
```latex
\begin{equation*}
	|
\end{equation*}
```
So my `\label` is somehow never shown now.

What I _expect_ should happens is that when I write `eq` and expand, I get
```latex
\begin{equation}\label{eq:|}
	
\end{equation}
```
and if I write `a` and jump to the next location I expect to get 
```latex
\begin{equation}\label{eq:a}
	|
\end{equation}
```
If Instead I don't write anything and jump to the next location I expect to get
```latex
\begin{equation*}
	|
\end{equation*}
```

### Another weird behaviour
If I use the following snippet 
```lua
s('eq', {
m(1, '[^.+]', '\\begin{equation}\\label{eq:', '\\begin{equation*}'),
i(1),
m(1, '[^.+]', '}', ''),
t { '', '\t' },
i(0),
m(1, '[^.+]', '\n\\end{equation}', '\n\\end{equation*}'),
})
```
This is the same snippet that I tried to create under the heading **Attempt at adjusting to my desired behaviour** except that I have switched the check for nonempty `[.+]` to a check for empty but now I write empty as `[^.+]` instead of as `^$`.

Now if I write `eq` and expand the snippet I get the _exact_ same behaviour that I describes under the heading **Where I start off**. This is really weird, at least to me. Now, the text in the `else_this` position is shown _before_ the matching has been done, which is not how it worked in the snippet under the heading **Where I start off**. It seems that the `if_match_then_this` position and `else_this` position have swapped roles.

**Comment by L3MON4D3** [comment]
Nooo im so sorry: `[.+]` matches dot or plus literally. Try without the brackets (and check out a reference for lua patterns :D).

**Comment by L3MON4D3** [comment]
That also explains why your last attempt worked, you matched anything but dot or plus ie. pretty much any string.

**Comment by L3MON4D3** [comment]
Your understanding of match nodes is spot on, except for this
> And _before_ the text has been matched then the text in if_match_then_this is shown.

The match node checks text directly after expansion, there's no special case for before the user input anything

**Comment by dajohans** [comment]
> Nooo im so sorry: `[.+]` matches dot or plus literally. Try without the brackets (and check out a reference for lua patterns :D).

Thanks! I actually looked up several tutorials and what I think is an official reference to come up with the expression I used. I'm confused about `^` and negation in lua patterns. I guess I assumed it worked in what I thought was a logical way, but it doesn't. `^` apparently has several meanings.. :/ 

> Your understanding of match nodes is spot on, except for this
> 
> > And _before_ the text has been matched then the text in if_match_then_this is shown.
> 
> The match node checks text directly after expansion, there's no special case for "before the user input anything"

But _before_ user input, _something_ is shown. If I have 
```lua
m(index, pattern, if_match_then_this, else_this)
```
then both `if_match_then_this` and `else_this` is text that could be shown at some point. One of them is shown as soon as I expand the snippet and _before_ I do any new keyboard input. I wonder, which one is shown at that point(after I expand but before I do any additional input)? Or, what determines which one is shown before I do any new input? It seems to me that both can be shown first, and I have so far always had the _wrong_ one show first.

If I do
```lua
s('eq',
{
	m(1, '^$', '\\begin{equation*}', '\\begin{equation}\\label{eq:'), i(1), m(1, '^$', '', '}'), t({'', '\t'}),
	i(0),
	m(1, '^$', '\n\\end{equation*}', '\n\\end{equation}'),
})
```
then the thing in the `if_match_then_this` is printed first but I want the thing in the `else_this` position to be printed first.

If I switch roles of the text in the `if_match_then_this` position and `else_this` position and if I negate the pattern, then I would expect the text in the position of `if_match_then_this` to still be printed first. If I do this then I have the snippet 
```lua
s('eq',
{
	m(1, '.+', '\\begin{equation}\\label{eq:', '\\begin{equation*}'), i(1), m(1, '.+', '}', ''), t({'', '\t'}),
	i(0),
	m(1, '.+', '\n\\end{equation}', '\n\\end{equation*}'),
})
```
Now what I want is that the text which is in the position of `if_match_then_this` is printed first, just as it was in the previous snippet. But now the text in `else_this` is printed first. This is really weird to me.

I want
```latex
\begin{equation}\label{eq:|}
	
\end{equation}
```
to be printed first but somehow I always get
```latex
\begin{equation*}|
	
\end{equation*}
```
regardless of how I try to move the arguments around.

Any ideas?

**Comment by L3MON4D3** [comment]
> One of them is shown as soon as I expand the snippet and before I do any new keyboard input.

Yes, exactly: just after expansion, `i(1)` contains the text `""`, this text is then matched and the same text returned in both versions because `^$` matches `""` and `.+` does not match `""`. There is no 'default', because insertNodes always contain text, be it `""`.
To have the `\label`-part show after expansion, you could put some default text into `i(1)`, ie. `i(1, "sample_text")`.

**Comment by dajohans** [comment]
Yes, I could do something like this
```lua
s('eq',
{
	m(1, '.+', '\\begin{equation}\\label{eq:', '\\begin{equation*}'), i(1, "label-name"), m(1, '.+', '}', ''), t({'', '\t'}),
	i(0),
	m(1, '.+', '\n\\end{equation}', '\n\\end{equation*}'),
})
```
but then when I write `eq` and expand I get
```latex
\begin{equation}\label{eq:label-name}
	
\end{equation}
```
At this point `label-name` is marked by vim. If I don't write _anything_ and jump to the next location, then I want to get
```
\begin{equation*}
	|
\end{equation*}
```
because I left the node empty. But instead I get
```latex
\begin{equation}\label{eq:label-name}
	|
\end{equation}
```
So in order to remove the `\label` part I now have to manually delete all of `label-name` and then jump. This is weird, because _I_ didn't write `label-name`. I feel like `label-name` should just be placeholder text but somehow it is treated as if it was written by _me_.

**Comment by dajohans** [comment]
> Yes, exactly: just after expansion, `i(1)` contains the text `""`, this text is then matched and the same text returned in both versions because `^$` matches `""` and `.+` does not match `""`. There is no 'default', because insertNodes always contain text, be it `""`.

You say that the text is matched before I try to jump to the next location. This seems really weird to me, since I can write text without anything happening. The only time that the snippet is changed based on what I am writing is when I jump to the next location.

Based on what you say, it sounds to me like if I write `eq` and it expands into
```latex
\begin{equation*}|
	
\end{equation*}
```
and If I write `a`:
```latex
\begin{equation*}a|
	
\end{equation*}
```
then this text should now be matched against the pattern and therefore I should now get
```latex
\begin{equation}\label{eq:a|}
	
\end{equation}
```
but this doesn't happen. The only time the snippet is updated so that the `\label` part is shown is when I jump to the next location.

**Comment by dajohans** [comment]
(Sorry for spamming comments)

> There is no 'default', because insertNodes always contain text, be it `""`.

Since, as I described above, the snippet doesn't update automatically as I type based on how the newly typed text matches the pattern, there _appears_ to be a default text which is shown, namely the one which the original node text is matched against. I feel like it makes sense to have a default, as I will try to argue below.

In the above situation, I want to conditionally remove a `\label`. But I really want the `\label` to be there when I write the label name, because it doesn't make sense to write the label name where the cursor is in the below code 
```latex
\begin{equation*}|
	
\end{equation*}
```
It only makes sense to write the label name where the cursor is in this code:
```latex
\begin{equation}\label{eq:|}
	
\end{equation}
```
and therefore I want the `\label` part to be shown as the default _before_ I write the label name and have the `\label` part be removed only if I _don't_ provide a label name. Your previous suggestion to have default text in the node `i(1, "label-name")` is in my oppinion not good, because then there is the label name `label-name` despite me _not_ having provided a label name. Then there is a default label name, and this is not what I would like.

**Comment by L3MON4D3** [comment]
> I feel like label-name should just be placeholder text but somehow it is treated as if it was written by _me_.

That's because luasnip just looks at what text is inside the node, not who put it there(which is perfectly fine behaviour imo, no obvious (to me) reason to differentiate there).

> You say that the text is matched before I try to jump to the next location. This seems really weird to me, since I can write text without anything happening. The only time that the snippet is changed based on what I am writing is when I jump to the next location.

That behaviour is configurable, you can have your nodes update more often (on any events for autocommands, in fact. I like `InsertLeave`, but to get instant feedback `TextChangedI` would be appropriate) by setting said event('s) in `updateevents` (config).

**Comment by L3MON4D3** [comment]
I will not include a default text in `matchNode`, it doesn't really make sense because there is no way that there is no text to match against, so there is no third state besides 'matches' or 'doesn't match'.

I see that you have a pretty specific behaviour in mind, I don't think a `matchNode` is the right fit for that. One way to do it would be having luasnip call functions after jumping from/to some `insertNode`, and in those change global state, depending on which the `functionNode`'s contain text or don't.

**Comment by dajohans** [comment]
> I see that you have a pretty specific behaviour in mind, I don't think a `matchNode` is the right fit for that.

I am honestly a bit confused, as I thought this would be _exactly_ what this luasnip functionality is for. Whether I create a Latex snippet for some environment and conditionally want to add/remove things or if I want to have something like a snippet for a C++ class and want to conditionally add/remove things, I want them to behave in this way. But generally, I am more interested in conditionally _removing_ things than adding things. So if this is not what `matchNode` is intended to be used for, then what is it supposed to be used for?

> One way to do it would be having luasnip call functions after jumping from/to some `insertNode`, and in those change some state, depending on which the `functionNode`'s contain default text or actually match what is inside the argnodes.

This sounds a bit too much for me at the moment since 1) I don't really know anything about the internals of luasnip, and 2) I am super novice at custom modifications of (neo)vim via lua/vimscript.

**Comment by L3MON4D3** [comment]
> I am honestly a bit confused, as I thought this would be _exactly_ what this luasnip functionality is for. Whether I create a Latex snippet for some environment and conditionally want to add/remove things or if I want to have something like a snippet for a C++ class and want to conditionally add/remove things, I want them to behave in this way. But generally, I am more interested in conditionally _removing_ things than adding things. So if this is not what `matchNode` is intended to be used for, then what is it supposed to be used for?

It is supposed to be used for exactly what you described just there, what I mean is that `matchNode` doesn't support your expected behaviour of differentiating between default and user-entered text.

> This sounds a bit too much for me at the moment since 1) I don't really know anything about the internals of luasnip, and 2) I am super novice at custom modifications of (neo)vim via lua/vimscript.

I'd include the jump-function-support in luasnip, seems pretty nice to have. You'd have to
1: write a function that sets some state and deletes the text inside the `i(1)`, should it be the default (will be called after jumping out of the `i(1)`)
2: write functions for `functionNode`s that, as long as the state isn't set, return some default text and, once it is set, actually match on the text inside the `i(1)`.
Not trivial, but all doable :) I'd even be compelled to write that myself, to have something explicit to test with.

**Comment by dajohans** [comment]
I might have a decent workaround to get the behaviour I want. It requires to add default text to the nodes as you suggested `i(1, "label-name")` but if I don't write anything and instead jump then I want `label-name` to be removed and then jump. I now added the following keybind
```viml
smap <silent><expr> <tab> luasnip#jumpable(1) ? '<del>i<plug>luasnip-jump-next' : '<tab>'
```
If I haven't written anything after the snippet is expanded then the placeholder text `label-name` is marked and will therefore be removed before I jump with this keybind. I think this keybind might actually have some nice side effects. For example, if I use a snippet for a for-loop in C provided by clangd, then it has placeholder text instead of suggested code for the iteration variable. If I just jump through that for loop, then I automatically remove all that non-code placeholder text, which is kind of nice. I guess an unwanted side effect of this keybind is that it adds the deleted things to a register. But I think I can live with that.

**Comment by L3MON4D3** [comment]
Also keep in mind, you won't be able to keep any default-text, but if you're alright with that, it's an effective solution :+1:

**Comment by dajohans** [comment]
> It is supposed to be used for exactly what you described just there, what I mean is that `matchNode` doesn't support your expected behaviour of differentiating between default and user-entered text.

Right! I think differentiating between default text and user-written text isn't actually something I would want. It would probably solve the problem, but I don't think it would be my preferred solution.

> I'd include the jump-function-support in luasnip, seems pretty nice to have. You'd have to
> 1: write a function that sets some state and deletes the text inside the `i(1)`, should it be the default (will be called after jumping out of the `i(1)`)
> 2: write functions for `functionNode`s that, as long as the state isn't set, return some default text and, once it is set, actually match on the text inside the `i(1)`.
> Not trivial, but all doable :) I'd even be compelled to write that myself, to have something explicit to test with.

Doesn't sound too bad after all. But for now, I think I'm quite happy with how it works with the keybind mention in a few comments up.

> Also keep in mind, you won't be able to keep any default-text, but if you're alright with that, it's an effective solution

Maybe I'd like to keep the code if for example the for-loop snippet from clangd had placeholder text which said `int i = 0` instead of saying `init-statement`. But this is usually not how I do snippets. Generally, I tend to have placeholder text which is invalid code(just normal text, not suggested default code) and in those cases I would always want to remove it anyway.

I think this issue might be resolved now that 1) I have the correct lua patterns in the pattern match, and 2) I've actually managed to get the behaviour I want, albeit with some minor(at least as of now) caveats. We could probably close the issue.

Thank you! I've been bothering you a lot lately and you've always been very helpful! Thanks a lot!

**Comment by L3MON4D3** [comment]
> Right! I think differentiating between default text and user-written text isn't actually something I would want. It would probably solve the problem, but I don't think it would be my preferred solution.

👍
> Generally, I tend to have placeholder text which is invalid code(just normal text, not suggested default code)

Ahhh I see, in that case there really aren't any big drawbacks.

> Thank you! I've been bothering you a lot lately and you've always been very helpful! Thanks a lot!

No problem, glad I could help :D
