### ISSUE TITLE
`package_cache` is nil sometimes.

### ISSUE THREAD

**Issue by MushmeIIow** [L3MON4D3/LuaSnip#982]
Hi, from time to time, when I open Neovim, I get this error:
```
Error detected while processing BufWinEnter Autocommands for "*":
Error executing lua callback: ...re/nvim/lazy/LuaSnip/lua/luasnip/loaders/from_vscode.lua:329: attempt to index upvalue 'package_cache' (a nil value)
stack traceback:
        ...re/nvim/lazy/LuaSnip/lua/luasnip/loaders/from_vscode.lua:329: in function '_load_lazy_loaded'
        ...local/share/nvim/lazy/LuaSnip/plugin/luasnip.lua:103: in function <.../.local/share/nvim/lazy/LuaSnip/plugin/luasnip.lua:102>
```
I use the default setting for Luasnip and nothing special. I can't understand the concrete steps to 100% reproduce the issue. I can say that when the problem has happened when reopening Neovim for a second or third time helps.

**Comment by L3MON4D3** [comment]
Oh that should not be nil.. is it possible you have another version of luasnip floating around (ie. in `runtimepath`), maybe installed with a different package-manager?

**Comment by MushmeIIow** [comment]
That was a good point from you. After I migrated from packer to lazy, I forgot to clean up some packages in `pack/packer/` folder. These packages are not presented in `runtimepath`, so it was not evident that they still exist. So, I manually removed all leftovers, and the issue has been resolved. Thank you.

**Comment by brendonrapp** [comment]
I experienced this same issue. The old `pack` folder was hiding in `~/.local/share/nvim/site`, which was included in the `runtimepath` and was very easy to overlook.
