### ISSUE TITLE
Pasting text by `p` or `gp` breaks tabstops

### ISSUE THREAD

**Issue by hinell** [L3MON4D3/LuaSnip#984]
https://github.com/L3MON4D3/LuaSnip/assets/8136158/b69162a5-a47d-4603-8d37-13511184cfb6

Hi. In the above demo tabstops are deactivated (note switching from `select-mode` to `visual-mode` (`CTRL+O`)) when LuaSnip is active and pasting into tabstop by typing `p` or `gp`.

<details><summary>VS CODE SNIPPET (CLICK TO OPEN)</summary>

Snippet: 
```json
"testme": {
  "prefix": "testme",
  "body": [
    "${1:placeholder} -> ${2:secondJump} "
  ],
  "description": "testme"
}
```

</details>

Is this by intent or configurable?

**Comment by L3MON4D3** [comment]
Could it just be that the mapping is not set up for normal-mode? Does jumping work again if you switch to insert-mode?

**Comment by hinell** [comment]
Well yeah, it works again if after pasting (`p`utting) I hit `a` or `i`. Thanks!
