### ISSUE TITLE
edit_snippet_files() but showing "extends"?

### ISSUE THREAD

**Issue by 9mm** [L3MON4D3/LuaSnip#988]
I know there is a config option called 'extends', but I think I'm talking about something different.

I'm using snipmate format snippets, which often have things like:

**vue.snippets**

```
extends html
extends javascript

priority 1

snippet impc 'import component'
	import $1 from '@/components/$2${1/(\w+).*/$1/}.vue';$0

snippet impu 'import composable'
	import use$1 from '@/composables/use$2${1/(\w+).*/$1/}';$0
```

In my old vim config, `<Leader>es` would only edit the exact snippet file of the current buffer. But given that LuaSnip offers a really fancy dialog I'd like to take advantage of that. Unfortunately it has the problem of listing literally only the current single buffer, so it kind of defeats the purpose of a UI select if theres only 1 single item in it.

How might I get it to show:

```
vue
html
javascript
all
```

```lua
-- examples: https://github.com/honza/vim-snippets/tree/master/snippets
-- snippet format: https://github.com/garbas/vim-snipmate/blob/master/doc/SnipMate.txt#L228

return {
  'L3MON4D3/LuaSnip',
  event = 'InsertEnter',
  version = '*',
  build = 'make install_jsregexp',
  config = function()
    local luasnip = require('luasnip')

    -- https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#config-options
    luasnip.setup({
      update_events = 'TextChanged,TextChangedI',
    })

    require('luasnip.loaders.from_snipmate').lazy_load({
      paths = '~/.config/nvim/snippets',
    })

    vim.keymap.set(
      'n',
      '<Leader>es',
      function()
        require('luasnip.loaders').edit_snippet_files({
          extend = function(ft, paths)
            if #paths == 0 then
              return {
                {
                  '$CONFIG/' .. ft .. '.snippets',
                  string.format("%s/%s.snippets", '~/.config/nvim/snippets', ft),
                }
              }
            end

            return {}
          end
        })
      end,
      { desc = 'Edit snippet' }
    )
  end,
}
```

**Comment by L3MON4D3** [comment]
Ah, so essentially suggest all files that contribute snippets to the current buffer.. that information is not easily accessible at all, (but we have it, I think) so providing some api to that sounds very useful!
extends can certainly be used to at least hardcode this in some way, but obviously not as nice.

**Comment by L3MON4D3** [comment]
Correction: it is easily accessible, but we don't track files that are extended in this way. I'll have to think about how to fix this, since the snipmate-loader isn't really meant to work this way

**Comment by 9mm** [comment]
PS I love your github avatar lol. 10/10. Every time i see it I laugh. The fact it's deep fried makes it even better.

**Comment by L3MON4D3** [comment]
Ayy thank you :D

**Comment by L3MON4D3** [comment]
This should work now :)

**Comment by 9mm** [comment]
Awesome!! Thanks! How might I go about using it, should my default hotkey work ?

```
 vim.keymap.set(
      'n',
      '<Leader>es',
      function()
        require('luasnip.loaders').edit_snippet_files({
          extend = function(ft, paths)
            if #paths == 0 then
              return {
                {
                  '$CONFIG/' .. ft .. '.snippets',
                  string.format("%s/%s.snippets", '~/.config/nvim/snippets', ft),
                }
              }
            end

            return {}
          end
        })
      end,
      { desc = 'Edit snippet' }
```

**Comment by L3MON4D3** [comment]
Yup, they should show up by default

**Comment by 9mm** [comment]
Hmmmm im not sure if Im doing something wrong

**vue.snippets**

```
extends html
extends javascript

snippet impc "import component"
	import $1 from "@/components/$2${1/(\w+).*/$1/}.vue";$0
```

and if i go to a vue file and type `<Leader>es`

<img width="543" alt="image" src="https://github.com/L3MON4D3/LuaSnip/assets/1386207/fc819e4f-f842-4ec0-b989-66b465a4e878">

**Comment by 9mm** [comment]
i also entirely removed the plugin via lazy.nvim too just to be sure was latest version, it did a fresh install as i noticed a bunch of branch errors, maybe from force pushing or something

**Comment by L3MON4D3** [comment]
Ah, the way it's set up is that `html.snippets` and `javascript.snippets` (the files, if they exist) are behind `vue` in the menu.
The idea here is that the snippets from those files are registered for the `vue`-filetype, and not html or javascript, and as such are listed in there.

You can get html and javascript into the first list by using `require("luasnip").filetype_extend("vue", "html")`, but this will then be applied globally, and would not be limited to the html-snippets from the collection `vue.snippets` is in.

Do you think listing html in the top-level selection would make more sense?

**Comment by 9mm** [comment]
> Ah, the way it's set up is that `html.snippets` and `javascript.snippets` (the files, if they exist) are behind `vue` in the menu. The idea here is that the snippets from those files are registered for the `vue`-filetype, and not html or javascript, and as such are listed in there.
> 
> You can get html and javascript into the first list by using `require("luasnip").filetype_extend("vue", "html")`, but this will then be applied globally, and would not be limited to the html-snippets from the collection `vue.snippets` is in.
> 
> Do you think listing html in the top-level selection would make more sense?

Sorry I'm not trying to be dense but I dont follow you. From my screenshot they dont appear to show up in the menu at all, to begin with. It just shows the filetype of the current file, and ignores things that have been extended.

**Comment by L3MON4D3** [comment]
What I was trying to say with too many words was that `html.snippets` (the file) should be shown, as an option, once you have selected (and confirmed) `vue`.
So, there should be a second menu, and that one should contain `html.snippets`, `vue.snippets` and `javascript.snippets` as separate options.

Is that the case for you?

**Comment by 9mm** [comment]
Ahhh I see, I think thats also an acceptable approach. Its not as ideal as in same menu but better than having to manually fake change the filetype just to edit something. when I hit enter on `vue` however, it just opens the file. Is that the proper way to select something?

**Comment by L3MON4D3** [comment]
OH! when you say latest version, do you mean `master` or `2.1.1`? Only master has this feature

**Comment by L3MON4D3** [comment]
But good, okay, at least the feature isn't broken :D

**Comment by 9mm** [comment]
Awesome, works!
