### ISSUE TITLE
bug: nvim -u mini.lua => MYCONFIG_ROOT=nil

### ISSUE THREAD

**Issue by ayoubelmhamdi** [L3MON4D3/LuaSnip#99]
i can use require('luasnip.loaders.from_vscode').load() if i open nvim with -u
```
:require('luasnip.loaders.from_vscode').load(

E5108: Error executing lua ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:168: attemp
t to index field 'MYVIMRC' (a nil value)
```
i change line 168 ==> 
from
```
local MYCONFIG_ROOT = vim.env.MYVIMRC:gsub("/[^/]+$", "")

```
to
```
local MYCONFIG_ROOT = vim.fn.expand('$USER') ..'/.config/nvim'
```
and bug gone

**Comment by L3MON4D3** [comment]
See #74, `$MYVIMRC` is supposed to be set, always. You could try installing a different version of neovim, ie. build from source. Another way to circumvent the error is exporting `MYVIMRC` in your `.bashrc`.
Just seeing it to `.config/...` sadly won't do it, users may have it in some other dir and we'd like to still have Luasnip work as expected.

**Comment by leiserfg** [comment]
I see, when using `-u afile`  (n)vim does not sets `$MYVIMRC`. Crap, I'll have to deal with that.

**Comment by ayoubelmhamdi** [comment]
it's work now
