### ISSUE TITLE
edit_snippet_files not finding some snippet filetypes

### ISSUE THREAD

**Issue by tjex** [L3MON4D3/LuaSnip#991]
When running `:lua require('luasnip.loaders').edit_snippet_files()` (as outlined here in the [docs](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#edit_snippets)) I'm only presented with `lua` and `all` filetypes. 
But I have other snippet files for other filetypes in the same directory (see screenshots).

I've set luasnip to load snippets from the `~/.config/nvim/snippets` directory as outlined [here in the docs](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#lua).

luasnip.lua :
```lua
local ok, _ = pcall(require, "luasnip")
if not ok then
    print("luasnip not ok!")
    return
end

local ls = require("luasnip")
local key = vim.keymap.set
local s = ls.snippet
local i = ls.insert_node
local t = ls.text_node
local extras = require("luasnip.extras")
local rep = extras.rep
local fmt = require("luasnip.extras.fmt").fmt

-- snippets source
require("luasnip.loaders.from_lua").load({ paths = "~/.config/nvim/snippets" })

ls.config.set_config {
    history = true,
    updateevents = "TextChanged,TextChangedI",
    -- enable_autosnippets = true,
}

key({ "i", "s" }, "<c-s>", function()
    if ls.expand_or_jumpable() then
        ls.expand_or_jump()
    end
end, { silent = true })

key({ "i", "s" }, "<c-u>", function()
    if ls.jumpable(-1) then
        ls.jump(-1)
    end
end, { silent = true })

key({ "i", "s" }, "<c-l>", function()
    if ls.choice_active() then
        ls.change_choice(1)
    end
end, { silent = true })

key("n", "<leader><leader>es", ":EditSnippets<CR>")
```

![Screenshot 2023-08-29 at 11 13 02](https://github.com/L3MON4D3/LuaSnip/assets/83029642/dc9fcb2e-fee8-4258-a75e-82598a56c2e3)

![Screenshot 2023-08-29 at 11 13 12](https://github.com/L3MON4D3/LuaSnip/assets/83029642/ff274cb5-aa1a-45cd-a5f8-f8eae81dc879)

All snippet files are using the same syntax as each other, and that is shown in the docs. 

bash.lua
```lua
-- bash snippets
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

return {
    s("yesno",
        t({
            "read -p 'continue? (Y/N): ' confirm",

            "if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then",
            "   echo 'confirmed'",
            "else",
            "   echo 'denied'",
            "fi"
        }))
}
```

Very grateful for any help to a seemingly basic question and many thanks for an excellent (and critical!!) plugin 🙌

**Comment by tjex** [comment]
Ahhhh. Ok! But that's actually quite fine then; that it matches snippet file types to filetypes found in the buffer. I would say it's better even (👏) - as it narrows down the selection to those that are relevant. 

My use case in my head anyway was to edit snippets related to whatever code I was writing in that moment. So... Well done! haha. Thanks again. A satisfying "close with comment". Keep it up!

**Comment by L3MON4D3** [comment]
Ayyy perfect xD
Thank you! :)
