### ISSUE TITLE
[feature-request] load snipmate files from given location

### ISSUE THREAD

**Issue by skywind3000** [L3MON4D3/LuaSnip#992]
Currently, LuaSnip searches snipmate files from `snippets` folder in each rtp path.

The the folder in the original vim-snipmate is configurable (by specifying a `g:SnipMateSources`).

And it is configurable in other snippet engines which support snipmate files, for example in neosnippet:

```VimL
" Enable snipMate compatibility feature.
let g:neosnippet#enable_snipmate_compatibility = 1

" Tell Neosnippet about the other snippets
let g:neosnippet#snippets_directory='~/.vim/my-snippets/snipmate-files'
```

I keep my snipmate files in a special folder (onedrive folder) rather than `rtp/snippets`,

It would be more flexible if LuaSnip can have an option to specify the snipmate files location.

--

**Comment by L3MON4D3** [comment]
Oh we can load the snippet-collection from anywhere, check the code-block in [this](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snipmate) section.
The parameters are explained in a more detail a bit above that.

**Comment by skywind3000** [comment]
thanks, succeeded.
