### ISSUE TITLE
Exit snippet / Jump to last node (node 0)

### ISSUE THREAD

**Issue by gruvw** [L3MON4D3/LuaSnip#995]
I am looking for a keymap that I can set to bypass all the tabstops when triggering a snippet and land directly on the `$0` mark.

Is this possible ?

**Comment by L3MON4D3** [comment]
https://github.com/L3MON4D3/LuaSnip/issues/562#issuecomment-1231680079 should still work I think.
Downside is that you'll have to manually find the snippet and call `ls.snip_expand(snip, ...)`..

**Comment by gruvw** [comment]
https://github.com/L3MON4D3/LuaSnip/issues/562#issuecomment-1233122825 works like a charm thanks :)
