### ISSUE TITLE
Add Snippet Description

### ISSUE THREAD

**Issue by l2late** [L3MON4D3/LuaSnip#997]
Thanks for the great plugin!

I was wondering if there was a way to add a description to a snippet as can be done with vscode snippets for example with the "description" field.

This would ease the integration with [telescope-luasnip](https://github.com/benfowler/telescope-luasnip.nvim) which allows you to display the snippet description (and also to search for it)

If not, could anyone give a hint on how would I could go about implementing this?

**Comment by L3MON4D3** [comment]
Hi :)
Does `dscr` (see [here](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#snippets)) work for you? It can be accessed later on as `snippet.dscr`

**Comment by l2late** [comment]
That is exacly what I needed!
I somehow didn't find it myself.
Sorry to have bothered you and thank you for the quick answer!
Keep up the great work.

**Comment by bew** [comment]
I'm wondering, why it is not called `desc` ?
For example nvim uses that in `nvim_set_keymap`, and I think it reads better than `dscr`
(I personally made a local wrapper to use that instead for my snippets 👀)

**Comment by L3MON4D3** [comment]
Oh, yeah we could make it so both `dscr` and `desc` can be used to get/set he description, I'd be open to that :D

**Comment by bew** [comment]
I'll try to make a PR :smiley: 

Is it ok for you if I rename the key in `effective_context` to a more wordy `description` ?

**Comment by L3MON4D3** [comment]
Oh a PR would be great :+1:
Making `dscr` and `desc` behave the same in `context`, and then `dscr` and `description` for access would be best.. is `dscr` set anywhere but at its initial setting?

(IIRC `.dscr` is accessed by other plugins like `cmp_luasnip`, I don't really want to deal with that just for the small cosmetic change :sweat_smile:)
